import { textEffectsFields, textEffectsDefaults, borderFields, borderDefault, borderHoverDefault, borderEffectDefaults } from './_shared';
import { shadowField } from './_shared.js';

export default {
  type: 'accordion',
  name: 'Fisarmonica',
  icon: 'dashicons-list-view',
  category: 'interactive',
  defaults: {
    panels: [
      { id: 'p-1', title: 'Cos\'è Olobuild?', content: 'Un potente page builder.', image: '', video: '', icon: '' },
      { id: 'p-2', title: 'Come funziona?', content: 'Trascina e rilascia le tile.', image: '', video: '', icon: '' },
    ],
    toggle_mode: false,
    default_open: 'first',
    icon_position: 'right',
    icon_style: 'chevron',
    animate_icon: true,
    animation_speed: '300',
    content_transition: 'fade',
    media_align: 'right',
    media_width: '35',
    media_radius: '8',
    header_bg: '',
    header_bg_active: '',
    header_text_color: '',
    content_bg: '',
    border_color: '',
    text_color: '',
    gap: '0',
    border_radius: '8',
    faq_schema: false,
    separator_style: 'border',
    shadow: 'none',
    ...textEffectsDefaults,
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
  },
  fields: [
    { key: 'panels', label: 'Pannelli', type: 'content-items', supportsDynamic: true,
      itemFields: [
        { key: 'title', label: 'Titolo', type: 'text' },
        { key: 'icon', label: 'Icona intestazione', type: 'icon' },
        { key: 'content', label: 'Contenuto', type: 'textarea' },
        { key: 'video', label: 'Video URL', type: 'text', placeholder: 'https://...mp4 o YouTube/Vimeo' },
        { key: 'image', label: 'Immagine', type: 'image' },
        { key: 'hover_image', label: 'Immagine hover', type: 'image' },
      ],
      newItemDefaults: { title: 'Nuovo pannello', content: 'Contenuto del pannello.', image: '', video: '', icon: '', hover_image: '' },
      itemLabel: 'Pannello',
    },
    { key: 'toggle_mode', label: 'Modalità alternata', type: 'toggle' },
    { key: 'default_open', label: 'Aperto di default', type: 'select', options: [
      { value: 'first', label: 'Primo pannello' },
      { value: 'all', label: 'Tutti i pannelli' },
      { value: 'none', label: 'Nessuno' },
    ]},
    { key: 'icon_position', label: 'Posizione icona', type: 'select', options: [
      { value: 'right', label: 'Destra' },
      { value: 'left', label: 'Sinistra' },
      { value: 'none', label: 'Nessuna' },
    ]},
    { key: 'icon_style', label: 'Stile icona', type: 'select', options: [
      { value: 'chevron', label: 'Chevron \u203A' },
      { value: 'plus', label: 'Più/Meno \uFF0B' },
      { value: 'arrow', label: 'Freccia \u2193' },
      { value: 'caret', label: 'Triangolo \u25BC' },
    ]},
    { key: 'animate_icon', label: 'Anima icona', type: 'toggle' },
    { key: 'animation_speed', label: 'Velocità animazione (ms)', type: 'range', min: 100, max: 800, step: 50 },
    { key: 'content_transition', label: 'Transizione contenuto', type: 'select', options: [
      { value: 'none', label: 'Nessuna' },
      { value: 'fade', label: 'Dissolvenza' },
      { value: 'slide', label: 'Scorrimento' },
    ]},
    { type: 'separator', label: 'Media pannello' },
    { key: 'media_align', label: 'Allineamento media', type: 'select', options: [
      { value: 'right', label: 'Destra' },
      { value: 'left', label: 'Sinistra' },
    ]},
    { key: 'media_width', label: 'Larghezza media (%)', type: 'range', min: 20, max: 50, step: 5 },
    { key: 'media_radius', label: 'Raggio bordo (px)', type: 'border-radius' },
    { key: 'media_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius' },
    { key: 'separator_style', label: 'Separatore', type: 'select', options: [
      { value: 'border', label: 'Bordo' },
      { value: 'shadow', label: 'Ombra' },
      { value: 'none', label: 'Nessuno' },
    ]},
    { key: 'header_bg', label: 'Sfondo intestazione', type: 'color' },
    { key: 'header_bg_active', label: 'Sfondo intestazione attiva', type: 'color' },
    { key: 'header_text_color', label: 'Colore testo intestazione', type: 'color' },
    { key: 'content_bg', label: 'Sfondo contenuto', type: 'color' },
    { key: 'border_color', label: 'Colore bordo', type: 'color' },
    { key: 'text_color', label: 'Colore testo', type: 'color' },
    { key: 'gap', label: 'Gap (px)', type: 'range', min: 0, max: 48, step: 4 },
    { key: 'border_radius', label: 'Border Radius', type: 'border-radius' },
    { key: 'border_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius' },
    { key: 'faq_schema', label: 'Schema FAQ', type: 'toggle' },
    ...shadowField,
    ...textEffectsFields([
      { value: 'title', label: 'Solo Titolo' },
      { value: 'content', label: 'Solo Contenuto' },
      { value: 'all', label: 'Tutti gli elementi testuali' },
    ]),
    ...borderFields(),
  ],
};
