import { textEffectsFields, textEffectsDefaults, borderFields, borderDefault, borderHoverDefault, borderEffectDefaults, withHover, widgetTemplateField, wowEffectsFields, wowEffectsDefaults } from './_shared';
import { shadowField } from './_shared.js';
import { t } from '@/i18n';

/**
 * Tile Accordion — split CONTENUTO/STILE.
 *   fields[]      → pannelli (title+icon+content+image+video), toggle_mode, default_open, faq_schema
 *   styleFields[] → preset, bg, typo, effetti preset, icona aspetto, animazione, media layout, header/content style, separatore, hover, glassmorphism, ombra, bordo
 */
export default {
  type: 'accordion',
  name: t('Fisarmonica'),
  icon: 'dashicons-list-view',
  category: 'interactive',
  defaults: {
    bg: { type: 'none' },
    typography_preset: '',
    panels: [
      { id: 'p-1', title: t('Cos\'è Olobuild?'), content: 'Olobuild è il page builder olonico che ti consente di costruire siti professionali con drag & drop, tile riutilizzabili e un controllo granulare di stile e responsive.', image: '', video: '', icon: '' },
      { id: 'p-2', title: t('Come aggiungo un nuovo elemento?'), content: 'Apri la sidebar Elementi a sinistra, scegli una categoria nella rail laterale e trascina il tile sul canvas. In alternativa fai click sul tile per inserirlo nella sezione attiva.', image: '', video: '', icon: '' },
      { id: 'p-3', title: t('È compatibile con il mio tema WordPress?'), content: 'Sì, Olobuild funziona con qualsiasi tema WordPress moderno (block-theme inclusi). Supporta header, footer e template singoli completamente personalizzabili.', image: '', video: '', icon: '' },
    ],
    preset: 'card-soft',
    toggle_mode: false,
    default_open: 'first',
    icon_position: 'right',
    icon_style: 'plus',
    animate_icon: true,
    animation_speed: '280',
    content_transition: 'fade',
    media_align: 'right',
    media_width: '35',
    media_radius: '8',
    header_bg: 'var(--olo-color-surface, #ffffff)',
    header_bg_active: 'var(--olo-color-surface, #ffffff)',
    header_text_color: 'var(--olo-color-text, #1f2937)',
    header_text_color_active: '',
    header_padding_y: '16',
    header_padding_x: '20',
    header_font_size: '15',
    header_font_weight: '600',
    header_font_family: 'sans',
    content_bg: 'var(--olo-color-surface, #ffffff)',
    content_padding_y: '20',
    content_padding_x: '20',
    content_font_size: '14',
    border_color: 'var(--olo-color-border, #e5e7eb)',
    border_width: '1',
    text_color: 'var(--olo-color-text, #1f2937)',
    gap: '12',
    border_radius: '12',
    faq_schema: false,
    separator_style: 'border',
    shadow: 'sm',
    backdrop_blur: '0',
    backdrop_saturate: '100',
    icon_shape: 'none',
    icon_shape_size: '32',
    icon_shape_bg: '',
    panel_hover_lift: false,
    panel_hover_shadow: 'none',
    effect_color: '',
    effect_intensity: 'medium',
    effect_speed: 0,
    ...textEffectsDefaults,
    text_effect_target: 'all',
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
    ...wowEffectsDefaults,
  },

  fields: [
    { key: 'panels', label: t('Pannelli'), type: 'content-items', supportsDynamic: true,
      itemFields: [
        { key: 'title', label: t('Titolo'), type: 'text' },
        { key: 'icon', label: t('Icona intestazione'), type: 'icon' },
        widgetTemplateField,
        { key: 'content', label: t('Contenuto'), type: 'textarea' },
        { key: 'video', label: t('Video URL'), type: 'text', placeholder: t('https://...mp4 o YouTube/Vimeo') },
        { key: 'image', label: t('Immagine'), type: 'image' },
        { key: 'hover_image', label: t('Immagine hover'), type: 'image' },
      ],
      newItemDefaults: { title: t('Nuovo pannello'), content: 'Contenuto del pannello.', image: '', video: '', icon: '', hover_image: '', widget_template_id: 0, children: [] },
      itemLabel: 'Pannello',
    },

    { type: 'separator', label: t('Comportamento') },
    { key: 'toggle_mode', label: t('Modalità alternata'), type: 'toggle' },
    { key: 'default_open', label: t('Aperto di default'), type: 'select', options: [
      { value: 'first', label: t('Primo pannello') },
      { value: 'all', label: t('Tutti i pannelli') },
      { value: 'none', label: t('Nessuno') },
    ]},
    { key: 'faq_schema', label: t('Schema FAQ (SEO)'), type: 'toggle' },
  ],

  styleFields: [
    { type: 'separator', label: t('Preset stile') },
    { key: 'preset', label: t('Stile'), type: 'select', options: [
      { value: 'card-soft',         label: t('Card Soft (Stripe-style)') },
      { value: 'minimal-underline', label: t('Minimal Underline (Apple)') },
      { value: 'pill-brand',        label: t('Pill Brand (Linear)') },
      { value: 'outline-sharp',     label: t('Outline Sharp') },
      { value: 'glass-soft',        label: t('Glass Soft (glassmorphism soft)') },
      { value: 'liquid-glass',      label: t('Liquid Glass (Vision Pro)') },
      { value: 'neon-cyber',        label: t('Neon Cyberpunk (Tron)') },
      { value: 'brutalist-block',   label: t('Brutalist Block (neo-brutalist)') },
      { value: 'magnetic-liquid',   label: t('Magnetic Liquid (next-gen)') },
      { value: 'sticker',           label: t('Sticker / Scrapbook') },
      { value: 'retro-terminal',    label: t('Retro Terminal (CRT)') },
      { value: '3d-tilt',           label: t('3D Card Tilt') },
      { value: 'custom',            label: t('Personalizzato (usa controlli sotto)') },
    ]},
    { type: 'separator', label: t('Tweak effetto preset'),
      condition: { field: 'preset', op: 'in', value: ['liquid-glass','neon-cyber','brutalist-block','magnetic-liquid','sticker','retro-terminal','3d-tilt'] } },
    { key: 'effect_color', label: t('Colore effetto'), type: 'color',
      condition: { field: 'preset', op: 'in', value: ['neon-cyber','brutalist-block','magnetic-liquid','sticker','retro-terminal'] } },
    { key: 'effect_intensity', label: t('Intensità effetto'), type: 'select',
      options: [
        { value: 'low',    label: t('Bassa') },
        { value: 'medium', label: t('Media (default)') },
        { value: 'high',   label: t('Alta') },
      ],
      condition: { field: 'preset', op: 'in', value: ['liquid-glass','neon-cyber','brutalist-block','magnetic-liquid','sticker','retro-terminal','3d-tilt'] } },
    { key: 'effect_speed', label: t('Velocità animazioni (ms)'), type: 'range',
      min: 0, max: 4000, step: 100,
      condition: { field: 'preset', op: 'in', value: ['neon-cyber','magnetic-liquid','retro-terminal','3d-tilt'] } },

    { type: 'separator', label: t('Icona') },
    { key: 'icon_position', label: t('Posizione icona'), type: 'select', options: [
      { value: 'right', label: t('Destra') },
      { value: 'left', label: t('Sinistra') },
      { value: 'none', label: t('Nessuna') },
    ]},
    { key: 'icon_style', label: t('Stile icona'), type: 'select', options: [
      { value: 'chevron', label: t('Chevron ›') },
      { value: 'plus', label: t('Più/Meno ＋') },
      { value: 'arrow', label: t('Freccia ↓') },
      { value: 'caret', label: t('Triangolo ▼') },
    ]},
    { key: 'animate_icon', label: t('Anima icona'), type: 'toggle' },
    { key: 'icon_shape', label: t('Forma icona'), type: 'select', options: [
      { value: 'none', label: t('Nessuna (icona piatta)') },
      { value: 'pill', label: t('Pill (riquadro)') },
      { value: 'circle', label: t('Cerchio') },
    ]},
    { key: 'icon_shape_size', label: t('Dimensione riquadro (px)'), type: 'range', min: 24, max: 48, step: 1,
      condition: { field: 'icon_shape', op: 'in', value: [ 'pill', 'circle' ] } },
    { key: 'icon_shape_bg', label: t('Sfondo riquadro'), type: 'color',
      condition: { field: 'icon_shape', op: 'in', value: [ 'pill', 'circle' ] } },

    { type: 'separator', label: t('Animazione') },
    { key: 'animation_speed', label: t('Velocità animazione (ms)'), type: 'range', min: 100, max: 800, step: 50 },
    { key: 'content_transition', label: t('Transizione contenuto'), type: 'select', options: [
      { value: 'none', label: t('Nessuna') },
      { value: 'fade', label: t('Dissolvenza') },
      { value: 'slide', label: t('Scorrimento') },
    ]},

    ...textEffectsFields([
      { value: 'title', label: t('Solo Titolo') },
      { value: 'content', label: t('Solo Contenuto') },
      { value: 'all', label: t('Tutti gli elementi testuali') },
    ]),

    { type: 'separator', label: t('Media pannello') },
    { key: 'media_align', label: t('Allineamento media'), type: 'select', options: [
      { value: 'right', label: t('Destra') },
      { value: 'left', label: t('Sinistra') },
    ]},
    { key: 'media_width', label: t('Larghezza media (%)'), type: 'range', min: 20, max: 50, step: 5 },
    withHover({ key: 'media_radius', label: t('Raggio bordo (px)'), type: 'border-radius' }),

    { type: 'separator', label: t('Tipografia') },
    { key: 'typography_preset', label: t('Stile tipografico'), type: 'select', optionsSource: 'globalTypography' },
    { type: 'typography', label: t('Intestazione'),
      presetKey: 'typography_preset',
      responsiveKeys: ['size'],
      keys: {
        family: 'header_font_family',
        size:   'header_font_size',
        weight: 'header_font_weight',
        color:  'header_text_color',
        colorHover: 'header_text_color_active',
      },
      sizeMin: 12, sizeMax: 22, sizeStep: 1,
    },
    { type: 'typography', label: t('Contenuto'),
      presetKey: 'typography_preset',
      responsiveKeys: ['size'],
      keys: {
        size:  'content_font_size',
        color: 'text_color',
      },
      sizeMin: 11, sizeMax: 20, sizeStep: 1,
    },

    { type: 'separator', label: t('Intestazione') },
    { key: 'header_bg', label: t('Sfondo intestazione'), type: 'color' },
    { key: 'header_bg_active', label: t('Sfondo intestazione attiva'), type: 'color' },
    { key: 'header_padding_y', label: t('Padding verticale (px)'), type: 'range', min: 8, max: 32, step: 1 },
    { key: 'header_padding_x', label: t('Padding orizzontale (px)'), type: 'range', min: 8, max: 32, step: 1 },

    { type: 'separator', label: t('Contenuto pannello') },
    { key: 'content_bg', label: t('Sfondo contenuto'), type: 'color' },
    { key: 'content_padding_y', label: t('Padding verticale (px)'), type: 'range', min: 0, max: 32, step: 1 },
    { key: 'content_padding_x', label: t('Padding orizzontale (px)'), type: 'range', min: 0, max: 32, step: 1 },

    { type: 'separator', label: t('Bordo e separatore') },
    { key: 'separator_style', label: t('Stile separatore'), type: 'select', options: [
      { value: 'border', label: t('Bordo') },
      { value: 'shadow', label: t('Ombra') },
      { value: 'none', label: t('Nessuno') },
    ]},
    { key: 'border_color', label: t('Colore bordo'), type: 'color' },
    { key: 'border_width', label: t('Spessore bordo (px)'), type: 'range', min: 0, max: 4, step: 1 },

    { type: 'separator', label: t('Effetti pannello (hover)') },
    { key: 'panel_hover_lift', label: t('Sollevamento al hover'), type: 'toggle' },
    { key: 'panel_hover_shadow', label: t('Ombra al hover'), type: 'select', options: [
      { value: 'none', label: t('Nessuna') },
      { value: 'sm', label: t('Leggera') },
      { value: 'md', label: t('Media') },
      { value: 'lg', label: t('Grande') },
    ]},

    { type: 'separator', label: t('Glassmorphism') },
    { key: 'backdrop_blur', label: t('Sfocatura sfondo (px)'), type: 'range', min: 0, max: 20, step: 1 },
    { key: 'backdrop_saturate', label: t('Saturazione sfondo (%)'), type: 'range', min: 100, max: 200, step: 5 },

    { type: 'separator', label: t('Forma') },
    { key: 'gap', label: t('Gap (px)'), type: 'range', min: 0, max: 48, step: 4 },
    withHover({ key: 'border_radius', label: t('Border Radius'), type: 'border-radius' }),

    ...shadowField,
    ...wowEffectsFields(),
    ...borderFields(),
  ],
};
