import { shadowField, borderFields, borderDefault, borderHoverDefault, borderEffectDefaults } from './_shared.js';

export default {
  type: 'animatedheading',
  name: 'Titolo animato',
  icon: 'dashicons-editor-textcolor',
  category: 'text',
  defaults: {
    before_text: 'Noi siamo',
    animated_words: 'creativi\ninnovativi\nappassionati',
    after_text: '',
    animation: 'typing',
    tag: 'h2',
    alignment: 'center',
    text_color: '',
    animated_color: '',
    font_size: '36',
    font_weight: '700',
    typing_speed: '100',
    pause_time: '2000',
    highlight_style: 'underline',
    highlight_color: '',
    shadow: 'none',
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
  },
  fields: [
    { key: 'before_text', label: 'Testo prima', type: 'text' },
    { key: 'animated_words', label: 'Parole animate (una per riga)', type: 'textarea' },
    { key: 'after_text', label: 'Testo dopo', type: 'text' },
    { key: 'animation', label: 'Animazione', type: 'select', options: [
      { value: 'typing', label: 'Digitazione' },
      { value: 'rotating', label: 'Rotazione verticale' },
      { value: 'fade', label: 'Dissolvenza' },
      { value: 'slide', label: 'Scorrimento' },
      { value: 'highlight', label: 'Evidenziazione' },
      { value: 'clip', label: 'Clip (rivela)' },
    ]},
    { key: 'tag', label: 'Tag HTML', type: 'select', options: [
      { value: 'h1', label: 'H1' },
      { value: 'h2', label: 'H2' },
      { value: 'h3', label: 'H3' },
      { value: 'h4', label: 'H4' },
      { value: 'p', label: 'Paragrafo' },
    ]},
    { key: 'alignment', label: 'Allineamento', type: 'select', options: [
      { value: 'left', label: 'Sinistra' },
      { value: 'center', label: 'Centro' },
      { value: 'right', label: 'Destra' },
    ]},
    { type: 'separator', label: 'Stile' },
    { key: 'text_color', label: 'Colore testo', type: 'color' },
    { key: 'animated_color', label: 'Colore parola animata', type: 'color' },
    { key: 'font_size', label: 'Dimensione (px)', type: 'range', min: 18, max: 80, step: 2 },
    { key: 'font_weight', label: 'Peso', type: 'select', options: [
      { value: '400', label: 'Normale' },
      { value: '600', label: 'Semibold' },
      { value: '700', label: 'Bold' },
      { value: '800', label: 'Extra Bold' },
      { value: '900', label: 'Black' },
    ]},
    { type: 'separator', label: 'Velocità' },
    { key: 'typing_speed', label: 'Velocità digitazione (ms)', type: 'range', min: 50, max: 300, step: 10 },
    { key: 'pause_time', label: 'Pausa tra parole (ms)', type: 'range', min: 500, max: 5000, step: 100 },
    { key: 'highlight_style', label: 'Stile evidenziazione', type: 'select', options: [
      { value: 'underline', label: 'Sottolineatura' },
      { value: 'background', label: 'Sfondo' },
      { value: 'circle', label: 'Cerchio' },
      { value: 'strikethrough', label: 'Barrato' },
    ], condition: { field: 'animation', operator: '==', value: 'highlight' } },
    { key: 'highlight_color', label: 'Colore evidenziazione', type: 'color',
      condition: { field: 'animation', operator: '==', value: 'highlight' } },
    ...shadowField,
    ...borderFields(),
  ],
};
