import { textEffectsFields, textEffectsDefaults, borderFields, borderDefault, borderHoverDefault, borderEffectDefaults, withHover } from './_shared.js';
import { t } from '@/i18n';

/**
 * Tile AuthorBox — split CONTENUTO/STILE.
 *   fields[]      → visibilità (avatar/nome/bio/ruolo/post_count/website), tag nome, layout, alignment, gap
 *   styleFields[] → preset, bg, typo, text-effects, avatar (size/radius/border), tipografia, colori, padding, radius, border
 */
export default {
  type: 'authorbox',
  name: t('Author Box'),
  icon: 'dashicons-admin-users',
  category: 'dynamic',
  defaults: {
    preset: 'custom',
    bg: { type: 'none' },
    typography_preset: '',
    ...textEffectsDefaults,
    text_effect_target: 'name',
    layout: 'horizontal',
    avatar_size: '80',
    show_avatar: true,
    show_name: true,
    show_bio: true,
    show_role: false,
    show_post_count: false,
    show_website: false,
    name_tag: 'h3',
    name_color: '',
    name_size: '20',
    name_weight: '700',
    bio_color: '',
    bio_size: '14',
    role_color: '',
    role_size: '13',
    link_color: '',
    count_color: '',
    background_color: '',
    border_radius: '8',
    tile_padding: { top: 20, right: 20, bottom: 20, left: 20 },
    avatar_border_radius: '50',
    avatar_border_width: '0',
    avatar_border_color: '',
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
    gap: '16',
    text_align: 'left',
  },

  fields: [
    { type: 'separator', label: t('Contenuto') },
    { key: 'show_avatar', label: t('Mostra avatar'), type: 'toggle' },
    { key: 'show_name', label: t('Mostra nome'), type: 'toggle' },
    { key: 'show_bio', label: t('Mostra biografia'), type: 'toggle' },
    { key: 'show_role', label: t('Mostra ruolo'), type: 'toggle' },
    { key: 'show_post_count', label: t('Mostra conteggio articoli'), type: 'toggle' },
    { key: 'show_website', label: t('Mostra sito web'), type: 'toggle' },

    { type: 'separator', label: t('Layout') },
    { key: 'layout', label: t('Layout'), type: 'select', options: [
      { value: 'horizontal', label: t('Orizzontale') },
      { value: 'vertical', label: t('Verticale') },
    ]},
    { key: 'text_align', label: t('Allineamento testo'), type: 'select', options: [
      { value: 'left', label: t('Sinistra') },
      { value: 'center', label: t('Centro') },
      { value: 'right', label: t('Destra') },
    ]},
    { key: 'gap', label: t('Gap (px)'), type: 'range', min: 8, max: 40, step: 4 },
  ],

  styleFields: [
    { type: 'separator', label: t('Preset stilistico') },
    { key: 'preset', label: t('Stile'), type: 'select', options: [
      { value: 'modern-clean',    label: t('Modern Clean') },
      { value: 'minimal-mono',    label: t('Minimal Mono') },
      { value: 'magazine-bold',   label: t('Magazine Bold') },
      { value: 'editorial-serif', label: t('Editorial Serif') },
      { value: 'compact-inline',  label: t('Compact Inline') },
      { value: 'glass-frosted',   label: t('Glass Frosted') },
      { value: 'neon-glow',       label: t('Neon Glow') },
      { value: 'brutalist-stamp', label: t('Brutalist Stamp') },
      { value: 'gradient-aurora', label: t('Gradient Aurora') },
      { value: 'sticker-fun',     label: t('Sticker Fun') },
      { value: 'retro-terminal',  label: t('Retro Terminal') },
      { value: 'tilt-3d',         label: t('3D Tilt') },
      { value: 'custom',          label: t('Personalizzato') },
    ] },
    { key: 'typography_preset', label: t('Stile tipografico'), type: 'select', optionsSource: 'globalTypography' },

    ...textEffectsFields([
      { value: 'name', label: t('Nome autore') },
      { value: 'bio', label: t('Bio') },
    ]),

    { type: 'separator', label: t('Avatar') },
    { key: 'avatar_size', label: t('Dimensione avatar (px)'), type: 'range', min: 40, max: 160, step: 8,
      condition: { field: 'show_avatar', value: true } },
    withHover({ key: 'avatar_border_radius', label: t('Raggio bordo avatar (%)'), type: 'border-radius',
      condition: { field: 'show_avatar', value: true } }),
    { key: 'avatar_border_width', label: t('Bordo avatar (px)'), type: 'range', min: 0, max: 6, step: 1,
      condition: { field: 'show_avatar', value: true } },
    { key: 'avatar_border_color', label: t('Colore bordo avatar'), type: 'color',
      condition: { field: 'avatar_border_width', operator: '>', value: '0' } },

    { type: 'separator', label: t('Tipografia') },
    { type: 'typography', label: t('Nome'),
      presetKey: 'typography_preset',
      responsiveKeys: ['size'],
      keys: {
        tag:    'name_tag',
        size:   'name_size',
        weight: 'name_weight',
        color:  'name_color',
      },
      sizeMin: 14, sizeMax: 32, sizeStep: 1,
    },
    { type: 'typography', label: t('Biografia'),
      presetKey: 'typography_preset',
      responsiveKeys: ['size'],
      keys: {
        size:  'bio_size',
        color: 'bio_color',
      },
      sizeMin: 11, sizeMax: 18, sizeStep: 1,
    },
    { type: 'typography', label: t('Ruolo'),
      presetKey: 'typography_preset',
      responsiveKeys: ['size'],
      keys: {
        size:  'role_size',
        color: 'role_color',
      },
      sizeMin: 10, sizeMax: 18, sizeStep: 1,
    },
    { type: 'typography', label: t('Link'),
      presetKey: 'typography_preset',
      keys: {
        color: 'link_color',
      },
    },
    { type: 'typography', label: t('Conteggio'),
      presetKey: 'typography_preset',
      keys: {
        color: 'count_color',
      },
    },

    { type: 'separator', label: t('Colori') },
    { key: 'background_color', label: t('Sfondo'), type: 'color' },

    { type: 'separator', label: t('Aspetto') },
    { key: 'tile_padding', label: t('Padding (px)'), type: 'spacing', max: 48 },
    withHover({ key: 'border_radius', label: t('Raggio bordi (px)'), type: 'border-radius' }),

    ...borderFields(),
  ],
};
