import { textEffectsFields, textEffectsDefaults } from './_shared';
import { shadowField } from './_shared.js';

export default {
  type: 'button',
  name: 'Pulsante',
  icon: 'dashicons-button',
  category: 'essential',
  defaults: {
    text: 'Clicca qui',
    url: '#',
    target: '_self',
    alignment: 'center',
    full_width: false,

    // Style
    typography_preset: '',
    bg_color: '',
    text_color: '',
    border_radius: '6',
    tile_padding: { top: 14, right: 32, bottom: 14, left: 32 },
    font_size: '16',
    font_weight: '600',
    letter_spacing: '0',
    text_transform: 'none',
    icon: '',
    icon_position: 'before',
    icon_spacing: '8',
    border_width: '0',
    border_color: '',
    shadow: 'none',

    // Hover
    hover_bg_color: '',
    hover_text_color: '',
    hover_border_color: '',
    hover_shadow: '',
    hover_effect: 'lift',
    hover_image: '',
    hover_video: '',
    ...textEffectsDefaults,
  },
  fields: [
    { key: 'text', label: 'Testo pulsante', type: 'text' },
    { key: 'icon', label: 'Icona', type: 'icon' },
    { key: 'icon_position', label: 'Posizione icona', type: 'select', options: [
      { value: 'before', label: 'Prima del testo' },
      { value: 'after', label: 'Dopo il testo' },
    ]},
    { key: 'icon_spacing', label: 'Spazio icona (px)', type: 'range', min: 0, max: 24, step: 2 },
    { key: 'url', label: 'URL', type: 'text' },
    { key: 'target', label: 'Apri in', type: 'select', options: [
      { value: '_self', label: 'Stessa finestra' },
      { value: '_blank', label: 'Nuova scheda' },
    ]},
    { key: 'alignment', label: 'Allineamento', type: 'select', responsive: true, options: [
      { value: 'left', label: 'Sinistra' },
      { value: 'center', label: 'Centro' },
      { value: 'right', label: 'Destra' },
    ]},
    { key: 'full_width', label: 'Larghezza piena', type: 'toggle' },

    { type: 'separator', label: 'Stile' },

    { key: 'typography_preset', label: 'Stile tipografico', type: 'select', optionsSource: 'globalTypography' },
    { key: 'bg_color', label: 'Colore sfondo', type: 'color' },
    { key: 'text_color', label: 'Colore testo', type: 'color' },
    { key: 'border_radius', label: 'Border Radius', type: 'border-radius' },
    { key: 'border_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius' },
    { key: 'tile_padding', label: 'Padding (px)', type: 'spacing', max: 80 },
    { key: 'font_size', label: 'Dim. carattere (px)', type: 'range', min: 12, max: 32, step: 1, responsive: true },
    { key: 'font_weight', label: 'Peso font', type: 'select', options: [
      { value: '400', label: 'Normale' },
      { value: '500', label: 'Medio' },
      { value: '600', label: 'Semibold' },
      { value: '700', label: 'Bold' },
      { value: '800', label: 'Extra Bold' },
    ]},
    { key: 'letter_spacing', label: 'Spaziatura lettere (px)', type: 'range', min: 0, max: 5, step: 0.5 },
    { key: 'text_transform', label: 'Trasformazione testo', type: 'select', options: [
      { value: 'none', label: 'Nessuna' },
      { value: 'uppercase', label: 'MAIUSCOLO' },
      { value: 'lowercase', label: 'minuscolo' },
      { value: 'capitalize', label: 'Capitalizza' },
    ]},
    { key: 'border_width', label: 'Spessore bordo (px)', type: 'range', min: 0, max: 5, step: 1 },
    { key: 'border_color', label: 'Colore bordo', type: 'color' },
    ...shadowField,

    { type: 'separator', label: 'Stato hover' },

    { key: 'hover_effect', label: 'Effetto hover', type: 'select', options: [
      { value: 'none', label: 'Nessuno' },
      { value: 'lift', label: 'Solleva (↑)' },
      { value: 'grow', label: 'Ingrandisci' },
      { value: 'shrink', label: 'Rimpicciolisci' },
      { value: 'glow', label: 'Bagliore' },
      { value: 'pulse', label: 'Pulsazione' },
    ]},
    { key: 'hover_bg_color', label: 'Sfondo hover', type: 'color' },
    { key: 'hover_text_color', label: 'Testo hover', type: 'color' },
    { key: 'hover_border_color', label: 'Bordo hover', type: 'color' },
    { key: 'hover_shadow', label: 'Ombra hover', type: 'select', options: [
      { value: '', label: 'Invariata' },
      { value: 'none', label: 'Nessuna' },
      { value: 'sm', label: 'Piccola' },
      { value: 'md', label: 'Media' },
      { value: 'lg', label: 'Grande' },
      { value: 'xl', label: 'Extra grande' },
      { value: 'custom', label: 'Personalizzata' },
    ]},
    { key: 'hover_shadow_h', label: 'Offset H hover (px)', type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'hover_shadow', op: 'eq', value: 'custom' } },
    { key: 'hover_shadow_v', label: 'Offset V hover (px)', type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'hover_shadow', op: 'eq', value: 'custom' } },
    { key: 'hover_shadow_blur', label: 'Sfocatura hover (px)', type: 'range', min: 0, max: 100, step: 1,
      condition: { field: 'hover_shadow', op: 'eq', value: 'custom' } },
    { key: 'hover_shadow_spread', label: 'Espansione hover (px)', type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'hover_shadow', op: 'eq', value: 'custom' } },
    { key: 'hover_shadow_color', label: 'Colore ombra hover', type: 'color',
      condition: { field: 'hover_shadow', op: 'eq', value: 'custom' } },
    { key: 'hover_shadow_inset', label: 'Ombra interna hover', type: 'toggle',
      condition: { field: 'hover_shadow', op: 'eq', value: 'custom' } },
    { key: 'hover_image', label: 'Immagine hover', type: 'image' },
    { key: 'hover_video', label: 'Video hover (mp4)', type: 'media' },
    ...textEffectsFields([ { value: 'text', label: 'Solo Testo' } ]),
  ],
};
