import { textEffectsFields, textEffectsDefaults } from './_shared';
export default {
  type: 'carousel',
  name: 'Carosello immagini',
  icon: 'dashicons-format-image',
  category: 'media',
  defaults: {
    slides: [
      { id: 'cs-1', image_url: '', image_alt: '', link_url: '', caption: '' },
      { id: 'cs-2', image_url: '', image_alt: '', link_url: '', caption: '' },
      { id: 'cs-3', image_url: '', image_alt: '', link_url: '', caption: '' },
    ],
    slides_to_show: '3',
    gap: '16',
    autoplay: false,
    autoplay_speed: '4000',
    show_arrows: true,
    show_dots: true,
    loop: true,
    pause_on_hover: true,
    slide_height: 'auto',
    fixed_height: '300',
    border_radius: '8',
    arrow_color: '',
    arrow_bg: '',
    dot_color: '',
    dot_inactive_color: '',
    show_caption: false,
    caption_color: '',
    caption_bg: '',
    object_fit: 'cover',
    mobile_slides: '1',
    ...textEffectsDefaults,
  },
  fields: [
    { key: 'slides', label: 'Slide', type: 'content-items',
      itemFields: [
        { key: 'image_url', label: 'Immagine', type: 'image' },
        { key: 'image_alt', label: 'Testo alternativo', type: 'text' },
        { key: 'link_url', label: 'URL link', type: 'text' },
        { key: 'caption', label: 'Didascalia', type: 'text' },
      ],
      newItemDefaults: { image_url: '', image_alt: '', link_url: '', caption: '' },
      itemLabel: 'Slide',
    },

    { type: 'separator', label: 'Layout' },
    { key: 'slides_to_show', label: 'Slide visibili', type: 'range', min: 1, max: 6, step: 1 },
    { key: 'gap', label: 'Gap (px)', type: 'range', min: 0, max: 48, step: 4 },
    { key: 'slide_height', label: 'Altezza slide', type: 'select', options: [
      { value: 'auto', label: 'Automatica' },
      { value: 'fixed', label: 'Fissa' },
    ]},
    { key: 'fixed_height', label: 'Altezza fissa (px)', type: 'range', min: 150, max: 600, step: 10,
      condition: { field: 'slide_height', value: 'fixed' } },
    { key: 'object_fit', label: 'Adattamento', type: 'select', options: [
      { value: 'cover', label: 'Riempi' },
      { value: 'contain', label: 'Contieni' },
    ]},
    { key: 'border_radius', label: 'Raggio bordi (px)', type: 'border-radius' },
    { key: 'border_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius' },
    { key: 'mobile_slides', label: 'Slide mobile', type: 'range', min: 1, max: 3, step: 1 },

    { type: 'separator', label: 'Comportamento' },
    { key: 'autoplay', label: 'Autoplay', type: 'toggle' },
    { key: 'autoplay_speed', label: 'Velocita autoplay (ms)', type: 'range', min: 1000, max: 10000, step: 500,
      condition: { field: 'autoplay', value: true } },
    { key: 'loop', label: 'Loop infinito', type: 'toggle' },
    { key: 'pause_on_hover', label: 'Pausa al passaggio', type: 'toggle',
      condition: { field: 'autoplay', value: true } },
    { key: 'show_caption', label: 'Mostra didascalie', type: 'toggle' },

    { type: 'separator', label: 'Navigazione' },
    { key: 'show_arrows', label: 'Frecce navigazione', type: 'toggle' },
    { key: 'show_dots', label: 'Indicatori punti', type: 'toggle' },

    { type: 'separator', label: 'Colori' },
    { key: 'arrow_color', label: 'Colore frecce', type: 'color' },
    { key: 'arrow_bg', label: 'Sfondo frecce', type: 'color' },
    { key: 'dot_color', label: 'Colore punto attivo', type: 'color' },
    { key: 'dot_inactive_color', label: 'Colore punto inattivo', type: 'color' },
    { key: 'caption_color', label: 'Colore didascalia', type: 'color',
      condition: { field: 'show_caption', value: true } },
    { key: 'caption_bg', label: 'Sfondo didascalia', type: 'color',
      condition: { field: 'show_caption', value: true } },
    ...textEffectsFields([ { value: 'caption', label: 'Solo Didascalia' } ]),
  ],
};
