import { textEffectsFields, textEffectsDefaults } from './_shared';
import { shadowField } from './_shared.js';

export default {
  type: 'chart',
  name: 'Grafico',
  icon: 'dashicons-chart-area',
  category: 'interactive',
  defaults: {
    chart_type: 'bar',
    items: [
      { id: 'c-1', label: 'Gen', value: '65', color: '#6366F1' },
      { id: 'c-2', label: 'Feb', value: '45', color: '#8B5CF6' },
      { id: 'c-3', label: 'Mar', value: '80', color: '#A78BFA' },
      { id: 'c-4', label: 'Apr', value: '55', color: '#C4B5FD' },
    ],
    chart_height: '400',

    // Legenda
    show_legend: true,
    legend_position: 'bottom',
    legend_align: 'center',
    legend_color: '',
    legend_font_size: '12',
    legend_font_weight: '400',
    legend_box_width: '40',
    legend_padding: '10',
    legend_point_style: false,

    // Titolo
    show_title: false,
    chart_title: '',
    title_color: '',
    title_font_size: '16',
    title_font_weight: '700',
    title_padding: '10',

    // Sottotitolo
    show_subtitle: false,
    chart_subtitle: '',
    subtitle_color: '',
    subtitle_font_size: '12',

    // Tooltip
    tooltip_enabled: true,
    tooltip_bg: '#000000',
    tooltip_text_color: '#ffffff',
    tooltip_border_color: '',
    tooltip_border_width: '0',
    tooltip_corner_radius: '6',
    tooltip_font_size: '12',
    tooltip_padding: '8',

    // Stile dati
    animate: true,
    bg_color: 'transparent',
    border_width: '2',
    border_color_override: '',
    bar_radius: '0',
    bar_percentage: '0.8',
    category_percentage: '0.8',
    fill_area: false,
    point_radius: '4',
    point_hover_radius: '6',
    point_style: 'circle',
    tension: '0.4',
    doughnut_cutout: '50',

    // Griglia e assi
    grid_color: '',
    grid_line_width: '1',
    axis_color: '',
    text_color: '',
    tick_font_size: '11',
    show_x_grid: true,
    show_y_grid: true,
    show_x_border: true,
    show_y_border: true,
    begin_at_zero: true,
    y_min: '',
    y_max: '',
    y_step_size: '',
    index_axis: 'x',
    dataset_label: '',
    stacked: false,
    stepped_line: '',
    x_label: '',
    y_label: '',
    tooltip_prefix: '',
    tooltip_suffix: '',
    number_format: false,

    shadow: 'none',
    ...textEffectsDefaults,
  },
  fields: [
    { key: 'chart_type', label: 'Tipo grafico', type: 'select', options: [
      { value: 'bar', label: 'Barre' },
      { value: 'line', label: 'Linea' },
      { value: 'pie', label: 'Torta' },
      { value: 'doughnut', label: 'Ciambella' },
      { value: 'radar', label: 'Radar' },
      { value: 'polarArea', label: 'Area polare' },
    ]},
    { key: 'index_axis', label: 'Orientamento', type: 'select', options: [
      { value: 'x', label: 'Verticale' },
      { value: 'y', label: 'Orizzontale' },
    ], condition: { field: 'chart_type', op: 'in', value: ['bar'] } },
    { key: 'stacked', label: 'Impilato (stacked)', type: 'toggle',
      condition: { field: 'chart_type', op: 'in', value: ['bar', 'line'] } },
    { key: 'items', label: 'Dati', type: 'content-items',
      itemFields: [
        { key: 'label', label: 'Etichetta', type: 'text' },
        { key: 'value', label: 'Valore', type: 'text' },
        { key: 'color', label: 'Colore sfondo', type: 'color' },
        { key: 'border_color', label: 'Colore bordo', type: 'color' },
      ],
      newItemDefaults: { label: 'Nuovo', value: '50', color: '#6366F1', border_color: '' },
      itemLabel: 'Dato',
    },
    { key: 'dataset_label', label: 'Etichetta dataset', type: 'text', placeholder: 'Mostrata nella legenda',
      condition: { field: 'chart_type', op: 'in', value: ['bar', 'line', 'radar'] } },

    { type: 'separator', label: 'Dimensioni' },
    { key: 'chart_height', label: 'Altezza (px)', type: 'range', min: 200, max: 800, step: 10 },

    // ── Legenda ──
    { type: 'separator', label: 'Legenda' },
    { key: 'show_legend', label: 'Mostra legenda', type: 'toggle' },
    { key: 'legend_position', label: 'Posizione', type: 'select', options: [
      { value: 'top', label: 'Alto' },
      { value: 'bottom', label: 'Basso' },
      { value: 'left', label: 'Sinistra' },
      { value: 'right', label: 'Destra' },
    ], condition: { field: 'show_legend', value: true } },
    { key: 'legend_align', label: 'Allineamento', type: 'select', options: [
      { value: 'start', label: 'Inizio' },
      { value: 'center', label: 'Centro' },
      { value: 'end', label: 'Fine' },
    ], condition: { field: 'show_legend', value: true } },
    { key: 'legend_color', label: 'Colore testo', type: 'color',
      condition: { field: 'show_legend', value: true } },
    { key: 'legend_font_size', label: 'Dimensione font', type: 'range', min: 8, max: 20, step: 1,
      condition: { field: 'show_legend', value: true } },
    { key: 'legend_font_weight', label: 'Peso font', type: 'select', options: [
      { value: '400', label: 'Normal' },
      { value: '600', label: 'Semibold' },
      { value: '700', label: 'Bold' },
    ], condition: { field: 'show_legend', value: true } },
    { key: 'legend_box_width', label: 'Larghezza indicatore', type: 'range', min: 10, max: 60, step: 2,
      condition: { field: 'show_legend', value: true } },
    { key: 'legend_padding', label: 'Padding', type: 'spacing', max: 30,
      condition: { field: 'show_legend', value: true } },
    { key: 'legend_point_style', label: 'Indicatore circolare', type: 'toggle',
      condition: { field: 'show_legend', value: true } },

    // ── Titolo ──
    { type: 'separator', label: 'Titolo' },
    { key: 'show_title', label: 'Mostra titolo', type: 'toggle' },
    { key: 'chart_title', label: 'Testo titolo', type: 'text',
      condition: { field: 'show_title', value: true } },
    { key: 'title_color', label: 'Colore titolo', type: 'color',
      condition: { field: 'show_title', value: true } },
    { key: 'title_font_size', label: 'Dimensione titolo', type: 'range', min: 10, max: 32, step: 1,
      condition: { field: 'show_title', value: true } },
    { key: 'title_font_weight', label: 'Peso titolo', type: 'select', options: [
      { value: '400', label: 'Normal' },
      { value: '600', label: 'Semibold' },
      { value: '700', label: 'Bold' },
      { value: '800', label: 'Extra Bold' },
    ], condition: { field: 'show_title', value: true } },
    { key: 'title_padding', label: 'Padding titolo', type: 'spacing', max: 40,
      condition: { field: 'show_title', value: true } },

    // ── Sottotitolo ──
    { key: 'show_subtitle', label: 'Mostra sottotitolo', type: 'toggle' },
    { key: 'chart_subtitle', label: 'Testo sottotitolo', type: 'text',
      condition: { field: 'show_subtitle', value: true } },
    { key: 'subtitle_color', label: 'Colore sottotitolo', type: 'color',
      condition: { field: 'show_subtitle', value: true } },
    { key: 'subtitle_font_size', label: 'Dimensione sottotitolo', type: 'range', min: 8, max: 20, step: 1,
      condition: { field: 'show_subtitle', value: true } },

    // ── Tooltip ──
    { type: 'separator', label: 'Tooltip' },
    { key: 'tooltip_enabled', label: 'Mostra tooltip', type: 'toggle' },
    { key: 'tooltip_bg', label: 'Sfondo tooltip', type: 'color',
      condition: { field: 'tooltip_enabled', value: true } },
    { key: 'tooltip_text_color', label: 'Testo tooltip', type: 'color',
      condition: { field: 'tooltip_enabled', value: true } },
    { key: 'tooltip_border_color', label: 'Bordo tooltip', type: 'color',
      condition: { field: 'tooltip_enabled', value: true } },
    { key: 'tooltip_border_width', label: 'Spessore bordo tooltip', type: 'range', min: 0, max: 4, step: 1,
      condition: { field: 'tooltip_enabled', value: true } },
    { key: 'tooltip_corner_radius', label: 'Raggio angoli tooltip', type: 'border-radius',
      condition: { field: 'tooltip_enabled', value: true } },
    { key: 'tooltip_corner_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius' },
    { key: 'tooltip_font_size', label: 'Dimensione font tooltip', type: 'range', min: 8, max: 18, step: 1,
      condition: { field: 'tooltip_enabled', value: true } },
    { key: 'tooltip_padding', label: 'Padding tooltip', type: 'spacing', max: 20,
      condition: { field: 'tooltip_enabled', value: true } },

    // ── Stile dati ──
    { type: 'separator', label: 'Stile dati' },
    { key: 'animate', label: 'Animazione', type: 'toggle' },
    { key: 'border_width', label: 'Spessore bordo dati', type: 'range', min: 0, max: 6, step: 1 },
    { key: 'border_color_override', label: 'Colore bordo globale', type: 'color' },
    { key: 'bar_radius', label: 'Raggio angoli barre', type: 'border-radius',
      condition: { field: 'chart_type', value: 'bar' } },
    { key: 'bar_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius' },
    { key: 'bar_percentage', label: 'Larghezza barre (%)', type: 'range', min: 0.1, max: 1, step: 0.05,
      condition: { field: 'chart_type', value: 'bar' } },
    { key: 'category_percentage', label: 'Larghezza categoria (%)', type: 'range', min: 0.1, max: 1, step: 0.05,
      condition: { field: 'chart_type', value: 'bar' } },
    { key: 'tension', label: 'Curvatura linea', type: 'range', min: 0, max: 1, step: 0.05,
      condition: { field: 'chart_type', op: 'in', value: ['line', 'radar'] } },
    { key: 'fill_area', label: 'Riempi area', type: 'toggle',
      condition: { field: 'chart_type', op: 'in', value: ['line', 'radar'] } },
    { key: 'stepped_line', label: 'Linea a gradini', type: 'select', options: [
      { value: '', label: 'No' },
      { value: 'before', label: 'Prima' },
      { value: 'after', label: 'Dopo' },
      { value: 'middle', label: 'Centro' },
    ], condition: { field: 'chart_type', value: 'line' } },
    { key: 'point_radius', label: 'Raggio punti', type: 'range', min: 0, max: 12, step: 1,
      condition: { field: 'chart_type', op: 'in', value: ['line', 'radar'] } },
    { key: 'point_hover_radius', label: 'Raggio punti (hover)', type: 'range', min: 0, max: 16, step: 1,
      condition: { field: 'chart_type', op: 'in', value: ['line', 'radar'] } },
    { key: 'point_style', label: 'Stile punti', type: 'select', options: [
      { value: 'circle', label: 'Cerchio' },
      { value: 'rect', label: 'Quadrato' },
      { value: 'rectRounded', label: 'Quadrato arrotondato' },
      { value: 'triangle', label: 'Triangolo' },
      { value: 'star', label: 'Stella' },
      { value: 'cross', label: 'Croce' },
      { value: 'crossRot', label: 'Croce ruotata' },
      { value: 'dash', label: 'Trattino' },
    ], condition: { field: 'chart_type', op: 'in', value: ['line', 'radar'] } },
    { key: 'doughnut_cutout', label: 'Taglio ciambella (%)', type: 'range', min: 10, max: 90, step: 5,
      condition: { field: 'chart_type', value: 'doughnut' } },

    // ── Griglia e assi ──
    { type: 'separator', label: 'Griglia e assi' },
    { key: 'bg_color', label: 'Sfondo grafico', type: 'color' },
    { key: 'text_color', label: 'Colore testo assi', type: 'color' },
    { key: 'tick_font_size', label: 'Dimensione font assi', type: 'range', min: 8, max: 16, step: 1 },
    { key: 'grid_color', label: 'Colore griglia', type: 'color' },
    { key: 'grid_line_width', label: 'Spessore griglia', type: 'range', min: 0, max: 4, step: 0.5 },
    { key: 'axis_color', label: 'Colore bordo assi', type: 'color' },
    { key: 'show_x_grid', label: 'Griglia asse X', type: 'toggle',
      condition: { field: 'chart_type', op: 'in', value: ['bar', 'line'] } },
    { key: 'show_y_grid', label: 'Griglia asse Y', type: 'toggle',
      condition: { field: 'chart_type', op: 'in', value: ['bar', 'line'] } },
    { key: 'show_x_border', label: 'Bordo asse X', type: 'toggle',
      condition: { field: 'chart_type', op: 'in', value: ['bar', 'line'] } },
    { key: 'show_y_border', label: 'Bordo asse Y', type: 'toggle',
      condition: { field: 'chart_type', op: 'in', value: ['bar', 'line'] } },
    { key: 'begin_at_zero', label: 'Inizia da zero', type: 'toggle',
      condition: { field: 'chart_type', op: 'in', value: ['bar', 'line'] } },
    { key: 'y_min', label: 'Y minimo', type: 'text', placeholder: 'Auto',
      condition: { field: 'chart_type', op: 'in', value: ['bar', 'line'] } },
    { key: 'y_max', label: 'Y massimo', type: 'text', placeholder: 'Auto',
      condition: { field: 'chart_type', op: 'in', value: ['bar', 'line'] } },
    { key: 'y_step_size', label: 'Incremento Y', type: 'text', placeholder: 'Auto',
      condition: { field: 'chart_type', op: 'in', value: ['bar', 'line'] } },
    { key: 'x_label', label: 'Etichetta asse X', type: 'text',
      condition: { field: 'chart_type', op: 'in', value: ['bar', 'line'] } },
    { key: 'y_label', label: 'Etichetta asse Y', type: 'text',
      condition: { field: 'chart_type', op: 'in', value: ['bar', 'line'] } },

    // ── Formato valori ──
    { type: 'separator', label: 'Formato valori' },
    { key: 'tooltip_prefix', label: 'Prefisso valore', type: 'text', placeholder: 'es. €' },
    { key: 'tooltip_suffix', label: 'Suffisso valore', type: 'text', placeholder: 'es. %' },
    { key: 'number_format', label: 'Separatore migliaia', type: 'toggle' },

    ...shadowField,
    ...textEffectsFields([ { value: 'label', label: 'Solo Etichetta' } ]),
  ],
};
