
export default {
  type: 'content',
  name: 'Contenuto',
  icon: 'dashicons-text-page',
  category: 'essential',
  defaults: {
    heading: 'Titolo sezione',
    heading_tag: 'h2',
    heading_size: 'md',
    heading_color: '',
    text: 'Aggiungi il tuo contenuto qui.',
    text_color: '',
    image: '',
    image_position: 'top',
    image_width: '40',
    image_height: 'auto',
    image_fit: 'cover',
    image_radius: '0',
    image_border_width: '0',
    image_border_color: '',
    image_shadow: 'none',
    heading_gap: '8',
    image_gap: '16',
    hover_effect: 'none',
    hover_image: '',
    hover_video: '',
    link_url: '',
    link_target: '_self',
  },
  fields: [
    { key: 'heading', label: 'Titolo', type: 'text' },
    { key: 'heading_tag', label: 'Tag titolo', type: 'select', options: [
      { value: 'h2', label: 'H2' },
      { value: 'h3', label: 'H3' },
      { value: 'h4', label: 'H4' },
      { value: 'h5', label: 'H5' },
      { value: 'p', label: 'Paragrafo' },
    ]},
    { key: 'heading_size', label: 'Dim. titolo', type: 'select', responsive: true, options: [
      { value: 'sm', label: 'Piccolo' },
      { value: 'md', label: 'Medio' },
      { value: 'lg', label: 'Grande' },
      { value: 'xl', label: 'Extra grande' },
    ]},
    { key: 'heading_color', label: 'Colore titolo', type: 'color' },
    { key: 'text', label: 'Testo', type: 'editor', mode: 'block' },
    { key: 'text_color', label: 'Colore testo', type: 'color' },
    { key: 'heading_gap', label: 'Distanza titolo-testo (px)', type: 'range', min: 0, max: 60, step: 2 },

    { type: 'separator', label: 'Immagine' },

    { key: 'image', label: 'Immagine', type: 'image' },
    { key: 'image_position', label: 'Posizione immagine', type: 'select', responsive: true, options: [
      { value: 'top', label: 'Sopra' },
      { value: 'bottom', label: 'Sotto' },
      { value: 'left', label: 'Sinistra' },
      { value: 'right', label: 'Destra' },
    ]},
    { key: 'image_width', label: 'Larghezza immagine (%)', type: 'range', min: 20, max: 80, step: 5,
      condition: { field: 'image_position', value: ['left', 'right'] } },
    { key: 'image_height', label: 'Altezza immagine (px o auto)', type: 'text' },
    { key: 'image_fit', label: 'Adattamento immagine', type: 'select', options: [
      { value: 'cover', label: 'Cover' },
      { value: 'contain', label: 'Contain' },
      { value: 'fill', label: 'Fill' },
    ]},
    { key: 'image_radius', label: 'Raggio bordo (px)', type: 'border-radius' },
    { key: 'image_border_width', label: 'Spessore bordo (px)', type: 'range', min: 0, max: 10, step: 1 },
    { key: 'image_border_color', label: 'Colore bordo', type: 'color',
      condition: { field: 'image_border_width', operator: '>', value: '0' } },
    { key: 'image_shadow', label: 'Ombra', type: 'select', options: [
      { value: 'none', label: 'Nessuna' },
      { value: 'sm', label: 'Piccola' },
      { value: 'md', label: 'Media' },
      { value: 'lg', label: 'Grande' },
      { value: 'xl', label: 'Extra grande' },
      { value: 'custom', label: 'Personalizzata' },
    ]},
    { key: 'image_shadow_h', label: 'Offset H (px)', type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'image_shadow', op: 'eq', value: 'custom' } },
    { key: 'image_shadow_v', label: 'Offset V (px)', type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'image_shadow', op: 'eq', value: 'custom' } },
    { key: 'image_shadow_blur', label: 'Sfocatura (px)', type: 'range', min: 0, max: 100, step: 1,
      condition: { field: 'image_shadow', op: 'eq', value: 'custom' } },
    { key: 'image_shadow_spread', label: 'Espansione (px)', type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'image_shadow', op: 'eq', value: 'custom' } },
    { key: 'image_shadow_color', label: 'Colore ombra', type: 'color',
      condition: { field: 'image_shadow', op: 'eq', value: 'custom' } },
    { key: 'image_shadow_inset', label: 'Ombra interna', type: 'toggle',
      condition: { field: 'image_shadow', op: 'eq', value: 'custom' } },
    { key: 'image_gap', label: 'Distanza immagine-testo (px)', type: 'range', min: 0, max: 60, step: 4 },

    { type: 'separator', label: 'Effetti hover' },

    { key: 'hover_effect', label: 'Effetto immagine', type: 'select', options: [
      { value: 'none', label: 'Nessuno' },
      { value: 'zoom', label: 'Zoom' },
      { value: 'zoom-rotate', label: 'Zoom + rotazione' },
      { value: 'brightness', label: 'Luminosità' },
      { value: 'desaturate', label: 'Desatura → colore' },
      { value: 'blur-in', label: 'Sfocatura → nitido' },
    ]},
    { key: 'hover_image', label: 'Immagine hover', type: 'image' },
    { key: 'hover_video', label: 'Video hover (mp4)', type: 'media' },

    { type: 'separator', label: 'Link immagine' },

    { key: 'link_url', label: 'URL collegamento', type: 'text' },
    { key: 'link_target', label: 'Apri in', type: 'select', options: [
      { value: '_self', label: 'Stessa finestra' },
      { value: '_blank', label: 'Nuova finestra' },
    ]},
  ],
};
