
export default {
  type: 'content',
  name: 'Contenuto',
  icon: 'dashicons-text-page',
  category: 'essential',
  defaults: {
    heading: 'Titolo sezione',
    heading_tag: 'h2',
    heading_size: 'md',
    heading_color: '',
    text: 'Aggiungi il tuo contenuto qui.',
    text_color: '',
    image: '',
    image_position: 'top',
    image_width: '40',
    image_height: 'auto',
    image_fit: 'cover',
    image_radius: '0',
    image_border_width: '0',
    image_border_color: '',
    image_shadow: 'none',
    heading_gap: '8',
    image_gap: '16',
    hover_effect: 'none',
    hover_image: '',
    hover_video: '',
    link_url: '',
    link_target: '_self',
    // Text effects
    text_effect_target: 'heading',
    text_effect: 'none',
    text_effect_speed: '50',
    text_effect_delay: '0',
    text_effect_loop: false,
    text_effect_cursor: true,
    text_effect_cursor_char: '|',
    text_effect_color: '',
    text_effect_color_to: '',
    text_effect_phrases: '',
    text_effect_pause: '1500',
  },
  fields: [
    { key: 'heading', label: 'Titolo', type: 'text' },
    { key: 'heading_tag', label: 'Tag titolo', type: 'select', options: [
      { value: 'h2', label: 'H2' },
      { value: 'h3', label: 'H3' },
      { value: 'h4', label: 'H4' },
      { value: 'h5', label: 'H5' },
      { value: 'p', label: 'Paragrafo' },
    ]},
    { key: 'heading_size', label: 'Dim. titolo', type: 'select', responsive: true, options: [
      { value: 'sm', label: 'Piccolo' },
      { value: 'md', label: 'Medio' },
      { value: 'lg', label: 'Grande' },
      { value: 'xl', label: 'Extra grande' },
    ]},
    { key: 'heading_color', label: 'Colore titolo', type: 'color' },
    { key: 'text', label: 'Testo', type: 'editor', mode: 'block' },
    { key: 'text_color', label: 'Colore testo', type: 'color' },
    { key: 'heading_gap', label: 'Distanza titolo-testo (px)', type: 'range', min: 0, max: 60, step: 2 },

    { type: 'separator', label: 'Immagine' },

    { key: 'image', label: 'Immagine', type: 'image' },
    { key: 'image_position', label: 'Posizione immagine', type: 'select', responsive: true, options: [
      { value: 'top', label: 'Sopra' },
      { value: 'bottom', label: 'Sotto' },
      { value: 'left', label: 'Sinistra' },
      { value: 'right', label: 'Destra' },
    ]},
    { key: 'image_width', label: 'Larghezza immagine (%)', type: 'range', min: 20, max: 80, step: 5,
      condition: { field: 'image_position', value: ['left', 'right'] } },
    { key: 'image_height', label: 'Altezza immagine (px o auto)', type: 'text' },
    { key: 'image_fit', label: 'Adattamento immagine', type: 'select', options: [
      { value: 'cover', label: 'Cover' },
      { value: 'contain', label: 'Contain' },
      { value: 'fill', label: 'Fill' },
    ]},
    { key: 'image_radius', label: 'Raggio bordo (px)', type: 'border-radius' },
    { key: 'image_border_width', label: 'Spessore bordo (px)', type: 'range', min: 0, max: 10, step: 1 },
    { key: 'image_border_color', label: 'Colore bordo', type: 'color',
      condition: { field: 'image_border_width', operator: '>', value: '0' } },
    { key: 'image_shadow', label: 'Ombra', type: 'select', options: [
      { value: 'none', label: 'Nessuna' },
      { value: 'sm', label: 'Piccola' },
      { value: 'md', label: 'Media' },
      { value: 'lg', label: 'Grande' },
      { value: 'xl', label: 'Extra grande' },
      { value: 'custom', label: 'Personalizzata' },
    ]},
    { key: 'image_shadow_h', label: 'Offset H (px)', type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'image_shadow', op: 'eq', value: 'custom' } },
    { key: 'image_shadow_v', label: 'Offset V (px)', type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'image_shadow', op: 'eq', value: 'custom' } },
    { key: 'image_shadow_blur', label: 'Sfocatura (px)', type: 'range', min: 0, max: 100, step: 1,
      condition: { field: 'image_shadow', op: 'eq', value: 'custom' } },
    { key: 'image_shadow_spread', label: 'Espansione (px)', type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'image_shadow', op: 'eq', value: 'custom' } },
    { key: 'image_shadow_color', label: 'Colore ombra', type: 'color',
      condition: { field: 'image_shadow', op: 'eq', value: 'custom' } },
    { key: 'image_shadow_inset', label: 'Ombra interna', type: 'toggle',
      condition: { field: 'image_shadow', op: 'eq', value: 'custom' } },
    { key: 'image_gap', label: 'Distanza immagine-testo (px)', type: 'range', min: 0, max: 60, step: 4 },

    { type: 'separator', label: 'Effetti hover' },

    { key: 'hover_effect', label: 'Effetto immagine', type: 'select', options: [
      { value: 'none', label: 'Nessuno' },
      { value: 'zoom', label: 'Zoom' },
      { value: 'zoom-rotate', label: 'Zoom + rotazione' },
      { value: 'brightness', label: 'Luminosità' },
      { value: 'desaturate', label: 'Desatura → colore' },
      { value: 'blur-in', label: 'Sfocatura → nitido' },
    ]},
    { key: 'hover_image', label: 'Immagine hover', type: 'image' },
    { key: 'hover_video', label: 'Video hover (mp4)', type: 'media' },

    { type: 'separator', label: 'Link immagine' },

    { key: 'link_url', label: 'URL collegamento', type: 'text' },
    { key: 'link_target', label: 'Apri in', type: 'select', options: [
      { value: '_self', label: 'Stessa finestra' },
      { value: '_blank', label: 'Nuova finestra' },
    ]},

    { type: 'separator', label: 'Effetti testo' },
    { key: 'text_effect', label: 'Effetto', type: 'select', options: [
      { value: 'none', label: 'Nessuno' },
      { value: 'typewriter', label: 'Macchina da scrivere' },
      { value: 'typewriter-loop', label: 'Macchina da scrivere — loop frasi' },
      { value: 'reveal-letter', label: 'Reveal lettera per lettera' },
      { value: 'reveal-word', label: 'Reveal parola per parola' },
      { value: 'gradient-anim', label: 'Gradient animato' },
      { value: 'glitch', label: 'Glitch RGB' },
      { value: 'wave', label: 'Wave (lettere ondulanti)' },
      { value: 'underline-grow', label: 'Underline grow' },
      { value: 'highlight-grow', label: 'Highlight grow' },
      { value: 'scramble', label: 'Split scramble' },
    ]},
    { key: 'text_effect_target', label: 'Applica a', type: 'select', options: [
      { value: 'heading', label: 'Solo titolo' },
      { value: 'text', label: 'Solo testo' },
      { value: 'both', label: 'Titolo e testo' },
    ], condition: { field: 'text_effect', op: 'neq', value: 'none' } },
    { key: 'text_effect_speed', label: 'Velocità (ms per char/parola)', type: 'range', min: 10, max: 300, step: 5,
      condition: { field: 'text_effect', op: 'neq', value: 'none' } },
    { key: 'text_effect_delay', label: 'Ritardo iniziale (ms)', type: 'range', min: 0, max: 3000, step: 100,
      condition: { field: 'text_effect', op: 'neq', value: 'none' } },
    { key: 'text_effect_cursor', label: 'Mostra cursore lampeggiante', type: 'toggle',
      condition: { field: 'text_effect', op: 'eq', value: 'typewriter' } },
    { key: 'text_effect_cursor_char', label: 'Carattere cursore', type: 'text',
      condition: { field: 'text_effect_cursor', op: 'eq', value: true } },
    { key: 'text_effect_phrases', label: 'Frasi (una per riga)', type: 'textarea',
      description: 'Verranno mostrate in loop con effetto typewriter',
      condition: { field: 'text_effect', op: 'eq', value: 'typewriter-loop' } },
    { key: 'text_effect_pause', label: 'Pausa tra frasi (ms)', type: 'range', min: 500, max: 5000, step: 100,
      condition: { field: 'text_effect', op: 'eq', value: 'typewriter-loop' } },
    { key: 'text_effect_color', label: 'Colore primario', type: 'color',
      description: 'Per gradient/highlight/underline',
      condition: { field: 'text_effect', value: ['gradient-anim', 'highlight-grow', 'underline-grow'] } },
    { key: 'text_effect_color_to', label: 'Colore secondario (gradient)', type: 'color',
      condition: { field: 'text_effect', op: 'eq', value: 'gradient-anim' } },
    { key: 'text_effect_loop', label: 'Riproduci in loop', type: 'toggle',
      condition: { field: 'text_effect', value: ['typewriter', 'reveal-letter', 'reveal-word', 'wave', 'glitch', 'scramble'] } },
  ],
};
