import { shadowField, borderFields, borderDefault, borderHoverDefault, borderEffectDefaults } from './_shared.js';
import { t } from '@/i18n';

/**
 * Tile Countdown — split CONTENUTO/STILE.
 *   fields[]      → style/type, evergreen settings, target_date, expire_action+message+redirect, display_mode,
 *                   unità da mostrare, etichette, separator, expired_message
 *   styleFields[] → preset, bg, typo, tipografia (numeri/etichette/separator), padding, larghezza min item, colori, shadow, border
 */
export default {
  type: 'countdown',
  name: t('Conto alla rovescia'),
  icon: 'dashicons-clock',
  category: 'marketing',
  defaults: {
    bg: { type: 'none' },
    typography_preset: '',
    preset: 'custom',
    countdown_style: 'custom',
    countdown_type: 'date',
    evergreen_hours: '0',
    evergreen_minutes: '30',
    evergreen_loop: false,
    expire_action: 'none',
    expire_redirect_url: '',
    expire_message: 'Tempo scaduto!',
    display_mode: 'block',
    target_date: '2026-12-31T23:59',
    show_days: true,
    show_hours: true,
    show_minutes: true,
    show_seconds: true,
    expired_message: 'L\'evento è iniziato!',
    label_days: 'Giorni',
    label_hours: 'Ore',
    label_minutes: 'Minuti',
    label_seconds: 'Secondi',
    separator: ':',
    bg_color: '',
    text_color: '',
    accent_color: '',
    separator_color: '',
    number_font_size: '48',
    number_font_weight: '700',
    label_font_size: '12',
    label_font_weight: '500',
    separator_font_size: '32',
    item_min_width: '70',
    item_bg_color: '',
    item_radius: '0',
    item_padding: '0',
    tile_padding: { top: 32, right: 32, bottom: 32, left: 32 },
    shadow: 'none',
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
  },

  fields: [
    { key: 'countdown_style', label: t('Stile'), type: 'select', options: [
      { value: 'custom', label: t('Personalizzato') },
      { value: 'uikit', label: t('UIkit nativo') },
    ]},
    { key: 'countdown_type', label: t('Tipo countdown'), type: 'select', options: [
      { value: 'date', label: t('Data fissa') },
      { value: 'evergreen', label: t('Evergreen (per visitatore)') },
    ]},
    { key: 'target_date', label: t('Data obiettivo'), type: 'datetime',
      condition: { field: 'countdown_type', operator: '==', value: 'date' } },
    { key: 'evergreen_hours', label: t('Ore evergreen'), type: 'range', min: 0, max: 72, step: 1,
      condition: { field: 'countdown_type', operator: '==', value: 'evergreen' } },
    { key: 'evergreen_minutes', label: t('Minuti evergreen'), type: 'range', min: 0, max: 59, step: 1,
      condition: { field: 'countdown_type', operator: '==', value: 'evergreen' } },
    { key: 'evergreen_loop', label: t('Ricomincia automaticamente'), type: 'toggle',
      condition: { field: 'countdown_type', operator: '==', value: 'evergreen' } },

    { type: 'separator', label: t('Azione alla scadenza') },
    { key: 'expire_action', label: t('Azione'), type: 'select', options: [
      { value: 'none', label: t('Nessuna (mostra zero)') },
      { value: 'hide', label: t('Nascondi countdown') },
      { value: 'message', label: t('Mostra messaggio') },
      { value: 'redirect', label: t('Reindirizza') },
    ]},
    { key: 'expire_message', label: t('Messaggio scadenza'), type: 'text',
      condition: { field: 'expire_action', operator: '==', value: 'message' } },
    { key: 'expire_redirect_url', label: t('URL reindirizzamento'), type: 'link',
      condition: { field: 'expire_action', operator: '==', value: 'redirect' } },

    { type: 'separator', label: t('Visualizzazione & unità') },
    { key: 'display_mode', label: t('Visualizzazione'), type: 'select', options: [
      { value: 'block', label: t('Blocco (verticale)') },
      { value: 'inline', label: t('Inline (una riga)') },
    ]},
    { key: 'show_days', label: t('Mostra giorni'), type: 'toggle' },
    { key: 'show_hours', label: t('Mostra ore'), type: 'toggle' },
    { key: 'show_minutes', label: t('Mostra minuti'), type: 'toggle' },
    { key: 'show_seconds', label: t('Mostra secondi'), type: 'toggle' },
    { key: 'expired_message', label: t('Messaggio scaduto'), type: 'text' },

    { type: 'separator', label: t('Etichette') },
    { key: 'label_days', label: t('Etichetta giorni'), type: 'text' },
    { key: 'label_hours', label: t('Etichetta ore'), type: 'text' },
    { key: 'label_minutes', label: t('Etichetta minuti'), type: 'text' },
    { key: 'label_seconds', label: t('Etichetta secondi'), type: 'text' },
    { key: 'separator', label: t('Separatore'), type: 'text' },
  ],

  styleFields: [
    { type: 'separator', label: t('Preset stilistico') },
    { key: 'preset', label: t('Stile'), type: 'select', options: [
      { value: 'modern-digital',  label: t('Modern Digital') },
      { value: 'minimal-clean',   label: t('Minimal Clean') },
      { value: 'magazine-bold',   label: t('Magazine Bold') },
      { value: 'flip-cards',      label: t('Flip Cards') },
      { value: 'circle-rings',    label: t('Circle Rings') },
      { value: 'glass-tier',      label: t('Glass Tier') },
      { value: 'neon-clock',      label: t('Neon Clock') },
      { value: 'brutalist-mega',  label: t('Brutalist Mega') },
      { value: 'gradient-aurora', label: t('Gradient Aurora') },
      { value: 'sticker-fun',     label: t('Sticker Fun') },
      { value: 'retro-flip',      label: t('Retro Flip') },
      { value: 'tilt-3d',         label: t('3D Tilt') },
      { value: 'custom',          label: t('Personalizzato') },
    ]},
    { key: 'typography_preset', label: t('Stile tipografico'), type: 'select', optionsSource: 'globalTypography' },

    { type: 'separator', label: t('Tipografia') },
    // Nel PHP i NUMERI ereditano `accent_color` (uk-countdown-number) e le ETICHETTE
    // `text_color` (ereditato dal wrapper .olo-countdown). Il mapping precedente era
    // invertito: il color picker sotto "Numeri" cambiava le etichette.
    { type: 'typography', label: t('Numeri'),
      presetKey: 'typography_preset',
      responsiveKeys: ['size'],
      keys: {
        size:   'number_font_size',
        weight: 'number_font_weight',
        color:  'accent_color',
      },
      sizeMin: 16, sizeMax: 120, sizeStep: 2,
    },
    { type: 'typography', label: t('Etichette'),
      presetKey: 'typography_preset',
      responsiveKeys: ['size'],
      keys: {
        size:   'label_font_size',
        weight: 'label_font_weight',
        color:  'text_color',
      },
      sizeMin: 8, sizeMax: 24, sizeStep: 1,
    },
    { type: 'typography', label: t('Separatore'),
      presetKey: 'typography_preset',
      responsiveKeys: ['size'],
      keys: {
        size:  'separator_font_size',
        color: 'separator_color',
      },
      sizeMin: 12, sizeMax: 80, sizeStep: 2,
    },
    { key: 'item_min_width', label: t('Larghezza min elemento (px)'), type: 'range', min: 40, max: 160, step: 5 },
    { key: 'tile_padding', label: t('Padding interno tile (px)'), type: 'spacing', max: 64 },

    { type: 'separator', label: t('Card unità (giorni/ore/min/sec)') },
    { key: 'item_bg_color', label: t('Sfondo card'), type: 'color' },
    { key: 'item_radius', label: t('Raggio angoli card (px)'), type: 'border-radius' },
    { key: 'item_padding', label: t('Padding interno card (px)'), type: 'range', min: 0, max: 40, step: 2 },

    ...shadowField,
    ...borderFields(),
  ],
};
