import { textEffectsFields, textEffectsDefaults, borderFields, borderDefault, borderHoverDefault, borderEffectDefaults, withHover } from './_shared.js';
import { t } from '@/i18n';

/**
 * Tile FlipCard — split CONTENUTO/STILE.
 *   fields[]      → fronte (image/video/icon/title/description), retro (image/video/icon/title/description/cta), animazione flip
 *   styleFields[] → preset, bg, typo, text-effects, fronte aspetto (icon size/color, bg, overlay, fit/padding/radius, text color/align/valign),
 *                   retro aspetto identico + cta colori/radius, card (height/radius/border/shadow/padding), tipografia
 */
export default {
  type: 'flipcard',
  name: t('FlipCard'),
  icon: 'dashicons-image-flip-horizontal',
  category: 'marketing',

  // Unificazione sfondo: ogni faccia ha il suo pannello unico media (immagine/video/
  // gradiente/colore…). I campi legacy front_image/front_video e back_image/back_video
  // confluiscono rispettivamente in front_media e back_media. Non distruttivo: le chiavi
  // vecchie restano come fallback nei renderer (Vue+PHP) e nei defaults; front_media/
  // back_media hanno la precedenza. Migrazione al load in src/utils/bgMigrate.js.
  bgMigrate: [
    { imageKey: 'front_image', imagePosKey: 'front_image_position', videoKey: 'front_video', target: 'front_media' },
    { imageKey: 'back_image',  imagePosKey: 'back_image_position',  videoKey: 'back_video',  target: 'back_media' },
  ],

  defaults: {
    front_media: { type: 'none' },
    back_media: { type: 'none' },
    bg: { type: 'none' },
    typography_preset: '',
    preset: 'custom',
    front_image: '',
    front_video: '',
    front_icon: 'star',
    front_icon_size: '40',
    front_icon_color: '',
    front_title: 'Titolo fronte',
    front_description: 'Descrizione della card visibile.',
    front_bg: '',
    front_overlay: '',
    front_image_fit: 'cover',
    front_image_position: 'center center',
    front_image_padding: '0',
    front_image_radius: '0',
    front_text_color: '',
    front_text_align: 'center',
    front_valign: 'center',
    back_image: '',
    back_video: '',
    back_icon: '',
    back_icon_size: '40',
    back_icon_color: '',
    back_title: 'Titolo retro',
    back_description: 'Contenuto retro con dettagli.',
    back_bg: '',
    back_overlay: '',
    back_image_fit: 'cover',
    back_image_position: 'center center',
    back_image_padding: '0',
    back_image_radius: '0',
    back_text_color: '',
    back_text_align: 'center',
    back_valign: 'center',
    back_cta_text: 'Scopri di più',
    back_cta_url: '',
    back_cta_target: false,
    back_cta_bg: '',
    back_cta_color: '',
    back_cta_radius: '6',
    flip_direction: 'horizontal',
    flip_duration: '600',
    flip_trigger: 'hover',
    flip_easing: 'ease-in-out',
    card_height: '350',
    card_border_radius: '12',
    card_border: { ...borderDefault },
    card_border_hover: { ...borderHoverDefault },
    card_border_hover_duration: 300,
    card_shadow: 'md',
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
    tile_padding: { top: 24, right: 24, bottom: 24, left: 24 },
    title_size: '22',
    title_weight: '600',
    desc_size: '14',
    ...textEffectsDefaults,
    text_effect_target: 'all',
  },

  fields: [
    { type: 'separator', label: t('Fronte — Contenuto') },
    { key: 'front_media', label: t('Fronte — sfondo (immagine, video, gradiente…)'), type: 'background', showParallax: false },
    { key: 'front_icon', label: t('Icona'), type: 'icon' },
    { key: 'front_title', label: t('Titolo'), type: 'text' },
    { key: 'front_description', label: t('Descrizione'), type: 'textarea' },

    { type: 'separator', label: t('Retro — Contenuto') },
    { key: 'back_media', label: t('Retro — sfondo (immagine, video, gradiente…)'), type: 'background', showParallax: false },
    { key: 'back_icon', label: t('Icona'), type: 'icon' },
    { key: 'back_title', label: t('Titolo'), type: 'text' },
    { key: 'back_description', label: t('Descrizione'), type: 'textarea' },

    { type: 'separator', label: t('Retro — Pulsante CTA') },
    { key: 'back_cta_text', label: t('Testo pulsante'), type: 'text' },
    { key: 'back_cta_url', label: t('URL pulsante'), type: 'link' },
    { key: 'back_cta_target', label: t('Apri in nuova scheda'), type: 'toggle' },

    { type: 'separator', label: t('Animazione') },
    { key: 'flip_direction', label: t('Tipo animazione'), type: 'select', options: [
      { value: 'horizontal', label: t('Flip orizzontale') },
      { value: 'vertical', label: t('Flip verticale') },
      { value: 'diagonal', label: t('Flip diagonale') },
      { value: 'cube', label: t('Cubo 3D') },
      { value: 'slide-flip', label: t('Slide + Flip') },
      { value: 'zoom-flip', label: t('Zoom + Flip') },
    ]},
    { key: 'flip_duration', label: t('Durata (ms)'), type: 'range', min: 400, max: 1200, step: 50 },
    { key: 'flip_trigger', label: t('Trigger'), type: 'select', options: [
      { value: 'hover', label: t('Hover') },
      { value: 'click', label: t('Click') },
    ]},
    { key: 'flip_easing', label: t('Easing'), type: 'select', options: [
      { value: 'ease', label: t('Ease') },
      { value: 'ease-in-out', label: t('Ease In-Out') },
      { value: 'cubic-bezier(0.68,-0.55,0.265,1.55)', label: t('Bounce') },
    ]},
  ],

  styleFields: [
    { type: 'separator', label: t('Preset stilistico') },
    { key: 'preset', label: t('Stile'), type: 'select', options: [
      { value: 'modern-card',     label: t('Modern Card') },
      { value: 'photo-overlay',   label: t('Photo Overlay') },
      { value: 'magazine-flip',   label: t('Magazine Flip') },
      { value: 'minimal-clean',   label: t('Minimal Clean') },
      { value: 'icon-driven',     label: t('Icon Driven') },
      { value: 'glass-flip',      label: t('Glass Flip') },
      { value: 'neon-frame',      label: t('Neon Frame') },
      { value: 'brutalist-card',  label: t('Brutalist Card') },
      { value: 'gradient-aurora', label: t('Gradient Aurora') },
      { value: 'sticker-flip',    label: t('Sticker Flip') },
      { value: 'retro-poster',    label: t('Retro Poster') },
      { value: 'tilt-3d',         label: t('3D Tilt') },
      { value: 'custom',          label: t('Personalizzato') },
    ]},
    { key: 'typography_preset', label: t('Stile tipografico'), type: 'select', optionsSource: 'globalTypography' },

    ...textEffectsFields([
      { value: 'front_title', label: t('Solo Titolo (fronte)') },
      { value: 'front_description', label: t('Solo Descrizione (fronte)') },
      { value: 'back_title', label: t('Solo Titolo (retro)') },
      { value: 'back_description', label: t('Solo Descrizione (retro)') },
      { value: 'all', label: t('Tutti gli elementi testuali') },
    ]),

    { type: 'separator', label: t('Fronte — Aspetto') },
    { key: 'front_icon_size', label: t('Dimensione icona (px)'), type: 'range', min: 24, max: 80 },
    { key: 'front_icon_color', label: t('Colore icona'), type: 'color' },
    { key: 'front_bg', label: t('Colore sfondo'), type: 'color' },
    { key: 'front_image_fit', label: t('Adattamento immagine'), type: 'select', options: [
      { value: 'cover', label: t('Copri (taglia)') },
      { value: 'contain', label: t('Contieni (intera)') },
      { value: 'fill', label: t('Riempi (deforma)') },
    ], condition: { field: 'front_image', op: 'notEmpty' } },
    { key: 'front_image_position', label: t('Posizione contenuto'), type: 'object-position',
      contextKeys: { src: 'front_image', fit: 'front_image_fit' },
      condition: { field: 'front_image', op: 'notEmpty' } },
    { key: 'front_image_padding', label: t('Padding immagine (px)'), type: 'range', min: 0, max: 40, step: 1,
      condition: { field: 'front_image', op: 'notEmpty' } },
    withHover({ key: 'front_image_radius', label: t('Raggio immagine (px)'), type: 'border-radius',
      condition: { field: 'front_image', op: 'notEmpty' } }),
    { key: 'front_overlay', label: t('Overlay (su immagine)'), type: 'color',
      condition: { field: 'front_image', op: 'notEmpty' } },
    { key: 'front_text_align', label: t('Allineamento testo'), type: 'select', options: [
      { value: 'left', label: t('Sinistra') },
      { value: 'center', label: t('Centro') },
      { value: 'right', label: t('Destra') },
    ]},
    { key: 'front_valign', label: t('Allineamento verticale'), type: 'select', options: [
      { value: 'top', label: t('Alto') },
      { value: 'center', label: t('Centro') },
      { value: 'bottom', label: t('Basso') },
    ]},

    { type: 'separator', label: t('Retro — Aspetto') },
    { key: 'back_icon_size', label: t('Dimensione icona (px)'), type: 'range', min: 24, max: 80 },
    { key: 'back_icon_color', label: t('Colore icona'), type: 'color' },
    { key: 'back_bg', label: t('Colore sfondo'), type: 'color' },
    { key: 'back_image_fit', label: t('Adattamento immagine'), type: 'select', options: [
      { value: 'cover', label: t('Copri (taglia)') },
      { value: 'contain', label: t('Contieni (intera)') },
      { value: 'fill', label: t('Riempi (deforma)') },
    ], condition: { field: 'back_image', op: 'notEmpty' } },
    { key: 'back_image_position', label: t('Posizione contenuto'), type: 'object-position',
      contextKeys: { src: 'back_image', fit: 'back_image_fit' },
      condition: { field: 'back_image', op: 'notEmpty' } },
    { key: 'back_image_padding', label: t('Padding immagine (px)'), type: 'range', min: 0, max: 40, step: 1,
      condition: { field: 'back_image', op: 'notEmpty' } },
    withHover({ key: 'back_image_radius', label: t('Raggio immagine (px)'), type: 'border-radius',
      condition: { field: 'back_image', op: 'notEmpty' } }),
    { key: 'back_overlay', label: t('Overlay (su immagine)'), type: 'color',
      condition: { field: 'back_image', op: 'notEmpty' } },
    { key: 'back_text_align', label: t('Allineamento testo'), type: 'select', options: [
      { value: 'left', label: t('Sinistra') },
      { value: 'center', label: t('Centro') },
      { value: 'right', label: t('Destra') },
    ]},
    { key: 'back_valign', label: t('Allineamento verticale'), type: 'select', options: [
      { value: 'top', label: t('Alto') },
      { value: 'center', label: t('Centro') },
      { value: 'bottom', label: t('Basso') },
    ]},

    { type: 'separator', label: t('Retro — Pulsante CTA') },
    { key: 'back_cta_bg', label: t('Colore sfondo CTA'), type: 'color' },
    withHover({ key: 'back_cta_radius', label: t('Raggio bordo CTA (px)'), type: 'border-radius' }),

    { type: 'separator', label: t('Card') },
    { key: 'card_height', label: t('Altezza (px)'), type: 'range', min: 200, max: 600, step: 10 },
    withHover({ key: 'card_border_radius', label: t('Raggio bordo (px)'), type: 'border-radius' }),
    withHover(
      { key: 'card_border', label: t('Bordo card'), type: 'border' },
      { hoverKey: 'card_border_hover', hoverDurationKey: 'card_border_hover_duration' }
    ),
    { key: 'card_shadow', label: t('Ombra'), type: 'select', options: [
      { value: 'none', label: t('Nessuna') },
      { value: 'sm', label: t('Leggera') },
      { value: 'md', label: t('Media') },
      { value: 'lg', label: t('Grande') },
      { value: 'xl', label: t('Extra grande') },
      { value: 'custom', label: t('Personalizzata') },
    ]},
    { key: 'card_shadow_h', label: t('Offset H (px)'), type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'card_shadow', op: 'eq', value: 'custom' } },
    { key: 'card_shadow_v', label: t('Offset V (px)'), type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'card_shadow', op: 'eq', value: 'custom' } },
    { key: 'card_shadow_blur', label: t('Sfocatura (px)'), type: 'range', min: 0, max: 100, step: 1,
      condition: { field: 'card_shadow', op: 'eq', value: 'custom' } },
    { key: 'card_shadow_spread', label: t('Espansione (px)'), type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'card_shadow', op: 'eq', value: 'custom' } },
    { key: 'card_shadow_color', label: t('Colore ombra'), type: 'color',
      condition: { field: 'card_shadow', op: 'eq', value: 'custom' } },
    { key: 'card_shadow_inset', label: t('Ombra interna'), type: 'toggle',
      condition: { field: 'card_shadow', op: 'eq', value: 'custom' } },
    { key: 'tile_padding', label: t('Padding (px)'), type: 'spacing', max: 40 },
    ...borderFields(),

    { type: 'separator', label: t('Tipografia') },
    { type: 'typography', label: t('Titolo'),
      presetKey: 'typography_preset',
      responsiveKeys: ['size'],
      keys: {
        size:   'title_size',
        weight: 'title_weight',
        color:  'front_text_color',
      },
      sizeMin: 16, sizeMax: 40, sizeStep: 1,
    },
    { type: 'typography', label: t('Descrizione'),
      presetKey: 'typography_preset',
      responsiveKeys: ['size'],
      keys: {
        size:  'desc_size',
        color: 'back_text_color',
      },
      sizeMin: 12, sizeMax: 20, sizeStep: 1,
    },
    { type: 'typography', label: t('Pulsante CTA'),
      presetKey: 'typography_preset',
      keys: {
        color: 'back_cta_color',
      },
    },
  ],
};
