import { textEffectsFields, textEffectsDefaults, borderFields, borderDefault, borderHoverDefault, borderEffectDefaults, withHover } from './_shared';
import { t } from '@/i18n';

/**
 * Tile Form — split CONTENUTO/STILE.
 *   fields[]      → campi del form, impostazioni invio (email_to/cc/from/subject/messaggi/redirect/anim),
 *                   auto-reply, pulsante invio (text+icon+pos+align+fullwidth), multi-step toggle+style+labels,
 *                   conditions toggle, file upload, archiviazione, anti-spam, integrazioni (mailchimp/webhook/hubspot/AC/CK/brevo), privacy
 *   styleFields[] → preset, bg, text-effects, contenitore (max-width/align), stile campi (layout/colori/border/radius/size/focus/gap),
 *                   stile pulsante (colori/radius/padding/font/letter/transform/border+hover), checkbox/radio aspect
 */
export default {
  type: 'form',
  name: t('Form Contatti'),
  icon: 'dashicons-email-alt',
  category: 'marketing',
  defaults: {
    bg: { type: 'none' },
    typography_preset: '',
    preset: 'custom',
    fields: [
      { id: 'f-1', field_type: 'text', label: t('Nome'), placeholder: t('Il tuo nome'), name: 'nome', required: true, width: '1-2', options: '', icon: 'user', condition_field: '', condition_operator: 'equals', condition_value: '' },
      { id: 'f-2', field_type: 'email', label: t('Email'), placeholder: t('La tua email'), name: 'email', required: true, width: '1-2', options: '', icon: 'mail', condition_field: '', condition_operator: 'equals', condition_value: '' },
      { id: 'f-3', field_type: 'text', label: t('Oggetto'), placeholder: t('Oggetto del messaggio'), name: 'oggetto', required: false, width: '1-1', options: '', icon: '', condition_field: '', condition_operator: 'equals', condition_value: '' },
      { id: 'f-4', field_type: 'textarea', label: t('Messaggio'), placeholder: t('Scrivi il tuo messaggio...'), name: 'messaggio', required: true, width: '1-1', options: '', icon: '', condition_field: '', condition_operator: 'equals', condition_value: '' },
    ],
    email_to: '',
    email_cc: '',
    email_from_name: '',
    email_subject: 'Nuovo messaggio dal sito',
    success_message: 'Messaggio inviato con successo! Ti risponderemo al più presto.',
    error_message: 'Si è verificato un errore. Riprova più tardi.',
    redirect_url: '',
    success_animation: 'slide-top-small',
    error_animation: 'shake',
    auto_reply: false,
    auto_reply_subject: 'Grazie per averci contattato',
    auto_reply_message: 'Abbiamo ricevuto il tuo messaggio e ti risponderemo al più presto.',
    submit_text: 'Invia messaggio',
    submit_icon: '',
    submit_icon_pos: 'left',
    submit_alignment: 'left',
    submit_full_width: false,
    form_max_width: '0',
    form_align: 'left',
    form_layout: 'stacked',
    label_color: '',
    label_size: '14',
    label_weight: '500',
    label_transform: '',
    label_letter_spacing: '',
    label_font_family: '',
    input_bg: '',
    input_color: '',
    input_border_color: '',
    input_border_width: '1',
    input_border_style: 'box',
    input_font_family: '',
    input_radius: '6',
    input_size: 'default',
    input_focus_border: '',
    input_focus_shadow: true,
    input_placeholder_opacity: '0.4',
    gap: '16',
    submit_bg: '',
    submit_color: '',
    submit_radius: '6',
    tile_padding: { top: 12, right: 24, bottom: 12, left: 24 },
    submit_font_size: '16',
    submit_font_weight: '600',
    submit_hover_bg: '',
    submit_border_width: '0',
    submit_border_color: '',
    submit_hover_border_color: '',
    submit_letter_spacing: '0.3',
    submit_text_transform: 'none',
    submit_font_family: '',
    check_accent_color: '',
    check_bg: '',
    check_border_color: '',
    check_size: '18',
    check_label_gap: '8',
    honeypot: true,
    rate_limit: true,
    rate_limit_max: '5',
    rate_limit_window: '60',
    enable_multistep: false,
    step_style: 'progress',
    step_labels: '',
    enable_conditions: false,
    recaptcha_enabled: false,
    mailchimp_enabled: false,
    mailchimp_list_id: '',
    mailchimp_email_field: 'email',
    mailchimp_merge_fields: '',
    webhook_enabled: false,
    webhook_url: '',
    webhook_method: 'POST',
    hubspot_enabled: false,
    hubspot_portal_id: '',
    hubspot_form_guid: '',
    activecampaign_enabled: false,
    activecampaign_list_id: '',
    activecampaign_email_field: 'email',
    convertkit_enabled: false,
    convertkit_form_id: '',
    convertkit_email_field: 'email',
    brevo_enabled: false,
    brevo_list_id: '',
    brevo_email_field: 'email',
    file_max_size: '5',
    file_types: '.pdf,.doc,.docx,.jpg,.png',
    store_submissions: false,
    privacy_checkbox: false,
    privacy_text: 'Accetto il trattamento dei dati personali secondo la <a href="/privacy-policy">Privacy Policy</a>',
    ...textEffectsDefaults,
    text_effect_target: 'label',
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
  },

  fields: [
    { key: 'fields', label: t('Campi del form'), type: 'content-items',
      itemFields: [
        { key: 'field_type', label: t('Tipo campo'), type: 'select', options: [
          { value: 'text', label: t('Testo') },
          { value: 'email', label: t('Email') },
          { value: 'tel', label: t('Telefono') },
          { value: 'url', label: t('URL') },
          { value: 'number', label: t('Numero') },
          { value: 'date', label: t('Data') },
          { value: 'time', label: t('Ora') },
          { value: 'textarea', label: t('Area di testo') },
          { value: 'select', label: t('Seleziona') },
          { value: 'radio', label: t('Scelta singola') },
          { value: 'checkbox', label: t('Scelta multipla') },
          { value: 'hidden', label: t('Nascosto') },
          { value: 'file', label: t('File upload') },
          { value: 'datetime', label: t('Data e ora') },
          { value: 'range', label: t('Range slider') },
          { value: 'star_rating', label: t('Valutazione stelle') },
          { value: 'password', label: t('Password') },
          { value: 'password_confirm', label: t('Conferma password') },
          { value: 'color', label: t('Selettore colore') },
          { value: 'calculation', label: t('Campo calcolato') },
          { value: 'step', label: t('── Separatore step ──') },
        ]},
        { key: 'label', label: t('Etichetta'), type: 'text' },
        { key: 'name', label: t('Nome campo (email)'), type: 'text' },
        { key: 'placeholder', label: t('Placeholder'), type: 'text' },
        { key: 'icon', label: t('Icona campo'), type: 'icon',
          condition: { field: 'field_type', op: 'in', value: ['text', 'email', 'tel', 'url', 'number', 'date', 'time'] } },
        { key: 'required', label: t('Obbligatorio'), type: 'toggle' },
        { key: 'width', label: t('Larghezza'), type: 'select', options: [
          { value: '1-1', label: t('Intera (100%)') },
          { value: '1-2', label: t('Metà (50%)') },
          { value: '1-3', label: t('Un terzo (33%)') },
          { value: '2-3', label: t('Due terzi (66%)') },
          { value: '1-4', label: t('Un quarto (25%)') },
          { value: '3-4', label: t('Tre quarti (75%)') },
        ]},
        { key: 'options', label: t('Opzioni (una per riga)'), type: 'textarea',
          condition: { field: 'field_type', op: 'in', value: ['select', 'radio', 'checkbox'] } },
        { key: 'file_allowed_types', label: t('Tipi file ammessi'), type: 'text',
          condition: { field: 'field_type', op: 'in', value: ['file'] } },
        { key: 'file_max_size', label: t('Max dimensione (MB)'), type: 'number',
          condition: { field: 'field_type', op: 'in', value: ['file'] } },
        { key: 'file_max_files', label: t('Max file'), type: 'number',
          condition: { field: 'field_type', op: 'in', value: ['file'] } },
        { key: 'file_button_text', label: t('Testo pulsante'), type: 'text',
          condition: { field: 'field_type', op: 'in', value: ['file'] } },
        { key: 'range_min', label: t('Valore minimo'), type: 'number',
          condition: { field: 'field_type', op: 'in', value: ['range'] } },
        { key: 'range_max', label: t('Valore massimo'), type: 'number',
          condition: { field: 'field_type', op: 'in', value: ['range'] } },
        { key: 'range_step', label: t('Step'), type: 'number',
          condition: { field: 'field_type', op: 'in', value: ['range'] } },
        { key: 'range_default', label: t('Valore default'), type: 'number',
          condition: { field: 'field_type', op: 'in', value: ['range'] } },
        { key: 'star_count', label: t('Numero stelle'), type: 'number',
          condition: { field: 'field_type', op: 'in', value: ['star_rating'] } },
        { key: 'default_value', label: t('Valore default'), type: 'text',
          condition: { field: 'field_type', op: 'in', value: ['hidden'] } },
        { key: 'calc_formula', label: t('Formula (es. {quantita} * {prezzo})'), type: 'text',
          condition: { field: 'field_type', op: 'in', value: ['calculation'] } },
        { key: 'calc_prefix', label: t('Prefisso (es. €)'), type: 'text',
          condition: { field: 'field_type', op: 'in', value: ['calculation'] } },
        { key: 'calc_suffix', label: t('Suffisso'), type: 'text',
          condition: { field: 'field_type', op: 'in', value: ['calculation'] } },
        { key: 'calc_decimals', label: t('Decimali'), type: 'number',
          condition: { field: 'field_type', op: 'in', value: ['calculation'] } },
        { key: 'condition_field', label: t('Condizione: campo'), type: 'text', placeholder: t('Nome campo (es. nome)') },
        { key: 'condition_operator', label: t('Condizione: operatore'), type: 'select', options: [
          { value: 'equals', label: t('Uguale a') },
          { value: 'not_equals', label: t('Diverso da') },
          { value: 'contains', label: t('Contiene') },
          { value: 'not_empty', label: t('Non vuoto') },
          { value: 'empty', label: t('Vuoto') },
        ], condition: { field: 'condition_field', op: 'notEmpty' } },
        { key: 'condition_value', label: t('Condizione: valore'), type: 'text',
          condition: { field: 'condition_field', op: 'notEmpty' } },
      ],
      newItemDefaults: { field_type: 'text', label: t('Nuovo campo'), placeholder: '', name: '', required: false, width: '1-1', options: '', icon: '', file_allowed_types: '.pdf,.doc,.docx,.jpg,.png', file_max_size: 5, file_max_files: 1, file_button_text: 'Scegli file', range_min: 0, range_max: 100, range_step: 1, range_default: 50, star_count: 5, default_value: '', calc_formula: '', calc_prefix: '', calc_suffix: '', calc_decimals: 2, condition_field: '', condition_operator: 'equals', condition_value: '' },
      itemLabel: 'Campo',
    },

    { type: 'separator', label: t('Impostazioni invio') },
    { key: 'email_to', label: t('Email destinatario'), type: 'text', placeholder: t('admin@tuosito.it (vuoto = admin)') },
    { key: 'email_cc', label: t('Email CC (copia)'), type: 'text', placeholder: t('copia@tuosito.it') },
    { key: 'email_from_name', label: t('Nome mittente'), type: 'text', placeholder: t('Nome Sito (vuoto = nome sito)') },
    { key: 'email_subject', label: t('Oggetto email'), type: 'text' },
    { key: 'success_message', label: t('Messaggio di successo'), type: 'text' },
    { key: 'error_message', label: t('Messaggio di errore'), type: 'text' },
    { key: 'redirect_url', label: t('Redirect dopo invio (URL)'), type: 'link', placeholder: t('Lascia vuoto per mostrare messaggio') },

    { type: 'separator', label: t('Risposta automatica') },
    { key: 'auto_reply', label: t('Invia conferma al compilatore'), type: 'toggle' },
    { key: 'auto_reply_subject', label: t('Oggetto risposta'), type: 'text',
      condition: { field: 'auto_reply', op: 'eq', value: true } },
    { key: 'auto_reply_message', label: t('Testo risposta'), type: 'text',
      condition: { field: 'auto_reply', op: 'eq', value: true } },

    { type: 'separator', label: t('Pulsante invio') },
    { key: 'submit_text', label: t('Testo pulsante'), type: 'text' },
    { key: 'submit_icon', label: t('Icona pulsante'), type: 'icon' },
    { key: 'submit_icon_pos', label: t('Posizione icona'), type: 'select', options: [
      { value: 'left', label: t('Sinistra') },
      { value: 'right', label: t('Destra') },
    ], condition: { field: 'submit_icon', op: 'notEmpty' } },
    { key: 'submit_alignment', label: t('Allineamento pulsante'), type: 'select', options: [
      { value: 'left', label: t('Sinistra') },
      { value: 'center', label: t('Centro') },
      { value: 'right', label: t('Destra') },
    ]},
    { key: 'submit_full_width', label: t('Pulsante larghezza piena'), type: 'toggle' },

    { type: 'separator', label: t('Multi-step') },
    { key: 'enable_multistep', label: t('Form multi-step'), type: 'toggle' },
    { key: 'step_style', label: t('Stile step'), type: 'select', options: [
      { value: 'progress', label: t('Barra progresso') },
      { value: 'numbers', label: t('Numeri') },
      { value: 'dots', label: t('Pallini') },
    ], condition: { field: 'enable_multistep', operator: '==', value: true } },
    { key: 'step_labels', label: t('Etichette step (una per riga)'), type: 'textarea',
      condition: { field: 'enable_multistep', operator: '==', value: true } },

    { type: 'separator', label: t('Logica condizionale') },
    { key: 'enable_conditions', label: t('Abilita condizioni'), type: 'toggle' },

    { type: 'separator', label: t('File upload') },
    { key: 'file_max_size', label: t('Dimensione max file (MB)'), type: 'range', min: 1, max: 25, step: 1 },
    { key: 'file_types', label: t('Tipi file ammessi'), type: 'text' },

    { type: 'separator', label: t('Archiviazione') },
    { key: 'store_submissions', label: t('Salva invii nel database'), type: 'toggle' },

    { type: 'separator', label: t('Anti-spam') },
    { key: 'honeypot', label: t('Honeypot (consigliato)'), type: 'toggle' },
    { key: 'rate_limit', label: t('Rate limiting'), type: 'toggle' },
    { key: 'rate_limit_max', label: t('Max invii per finestra'), type: 'range', min: 1, max: 20,
      condition: { field: 'rate_limit', op: 'eq', value: true } },
    { key: 'rate_limit_window', label: t('Finestra (minuti)'), type: 'range', min: 5, max: 120, step: 5,
      condition: { field: 'rate_limit', op: 'eq', value: true } },
    { key: 'recaptcha_enabled', label: t('reCAPTCHA v3'), type: 'toggle' },

    { type: 'separator', label: t('Mailchimp') },
    { key: 'mailchimp_enabled', label: t('Mailchimp'), type: 'toggle' },
    { key: 'mailchimp_list_id', label: t('List/Audience ID'), type: 'text', placeholder: t('abc1234def'),
      condition: { field: 'mailchimp_enabled', op: 'eq', value: true } },
    { key: 'mailchimp_email_field', label: t('Nome campo email'), type: 'text', placeholder: t('email'),
      condition: { field: 'mailchimp_enabled', op: 'eq', value: true } },
    { key: 'mailchimp_merge_fields', label: t('Merge fields (campo=MERGE)'), type: 'textarea', placeholder: t('nome=FNAME\ncognome=LNAME'),
      condition: { field: 'mailchimp_enabled', op: 'eq', value: true } },

    { type: 'separator', label: t('Webhook') },
    { key: 'webhook_enabled', label: t('Webhook'), type: 'toggle' },
    { key: 'webhook_url', label: t('Webhook URL'), type: 'text', placeholder: t('https://...'),
      condition: { field: 'webhook_enabled', op: 'eq', value: true } },
    { key: 'webhook_method', label: t('Metodo HTTP'), type: 'select', options: [
      { value: 'POST', label: t('POST') },
      { value: 'PUT', label: t('PUT') },
    ], condition: { field: 'webhook_enabled', op: 'eq', value: true } },

    { type: 'separator', label: t('HubSpot') },
    { key: 'hubspot_enabled', label: t('HubSpot'), type: 'toggle' },
    { key: 'hubspot_portal_id', label: t('HubSpot Portal ID'), type: 'text', placeholder: '12345678',
      condition: { field: 'hubspot_enabled', op: 'eq', value: true } },
    { key: 'hubspot_form_guid', label: t('HubSpot Form GUID'), type: 'text', placeholder: t('xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'),
      condition: { field: 'hubspot_enabled', op: 'eq', value: true } },

    { type: 'separator', label: t('ActiveCampaign') },
    { key: 'activecampaign_enabled', label: t('ActiveCampaign'), type: 'toggle' },
    { key: 'activecampaign_list_id', label: t('List ID'), type: 'text', placeholder: '1',
      condition: { field: 'activecampaign_enabled', op: 'eq', value: true } },
    { key: 'activecampaign_email_field', label: t('Nome campo email'), type: 'text', placeholder: t('email'),
      condition: { field: 'activecampaign_enabled', op: 'eq', value: true } },

    { type: 'separator', label: t('ConvertKit') },
    { key: 'convertkit_enabled', label: t('ConvertKit'), type: 'toggle' },
    { key: 'convertkit_form_id', label: t('Form ID'), type: 'text', placeholder: '1234567',
      condition: { field: 'convertkit_enabled', op: 'eq', value: true } },
    { key: 'convertkit_email_field', label: t('Nome campo email'), type: 'text', placeholder: t('email'),
      condition: { field: 'convertkit_enabled', op: 'eq', value: true } },

    { type: 'separator', label: t('Brevo (Sendinblue)') },
    { key: 'brevo_enabled', label: t('Brevo (Sendinblue)'), type: 'toggle' },
    { key: 'brevo_list_id', label: t('List ID'), type: 'text', placeholder: '3',
      condition: { field: 'brevo_enabled', op: 'eq', value: true } },
    { key: 'brevo_email_field', label: t('Nome campo email'), type: 'text', placeholder: t('email'),
      condition: { field: 'brevo_enabled', op: 'eq', value: true } },

    { type: 'separator', label: t('Privacy') },
    { key: 'privacy_checkbox', label: t('Checkbox consenso privacy'), type: 'toggle' },
    { key: 'privacy_text', label: t('Testo consenso'), type: 'text',
      condition: { field: 'privacy_checkbox', op: 'eq', value: true } },
  ],

  styleFields: [
    { type: 'separator', label: t('Preset stilistico') },
    { key: 'preset', label: t('Stile'), type: 'select', options: [
      { value: 'modern-clean',    label: t('Modern Clean') },
      { value: 'minimal-line',    label: t('Minimal Line') },
      { value: 'magazine-bold',   label: t('Magazine Bold') },
      { value: 'card-floating',   label: t('Card Floating') },
      { value: 'compact-inline',  label: t('Compact Inline') },
      { value: 'glass-form',      label: t('Glass Form') },
      { value: 'neon-cyber',      label: t('Neon Cyber') },
      { value: 'brutalist-stamp', label: t('Brutalist Stamp') },
      { value: 'gradient-aurora', label: t('Gradient Aurora') },
      { value: 'sticker-fun',     label: t('Sticker Fun') },
      { value: 'retro-terminal',  label: t('Retro Terminal') },
      { value: 'tilt-3d',         label: t('3D Tilt') },
      { value: 'underline-dark',  label: t('Underline Dark') },
      { value: 'custom',          label: t('Personalizzato') },
    ]},
    { key: 'typography_preset', label: t('Stile tipografico'), type: 'select', optionsSource: 'globalTypography' },

    ...textEffectsFields([
      { value: 'label', label: t('Solo Etichetta') },
      { value: 'name', label: t('Solo Nome') },
      { value: 'all', label: t('Tutti gli elementi testuali') },
    ]),

    { type: 'separator', label: t('Animazioni messaggi') },
    { key: 'success_animation', label: t('Animazione successo'), type: 'select', options: [
      { value: 'fade', label: t('Dissolvenza') },
      { value: 'slide-top-small', label: t('Scorrimento dall\'alto') },
      { value: 'slide-bottom-small', label: t('Scorrimento dal basso') },
      { value: 'scale-up', label: t('Scala') },
    ]},
    { key: 'error_animation', label: t('Animazione errore'), type: 'select', options: [
      { value: 'shake', label: t('Vibrazione') },
      { value: 'fade', label: t('Dissolvenza') },
      { value: 'slide-top-small', label: t('Scorrimento dall\'alto') },
    ]},

    { type: 'separator', label: t('Contenitore') },
    { key: 'form_max_width', label: t('Larghezza massima (px)'), type: 'range', min: 0, max: 900, step: 10 },
    { key: 'form_align', label: t('Allineamento form'), type: 'select', options: [
      { value: 'left', label: t('Sinistra') },
      { value: 'center', label: t('Centro') },
      { value: 'right', label: t('Destra') },
    ], condition: { field: 'form_max_width', operator: '>', value: 0 } },

    { type: 'separator', label: t('Tipografia') },
    { type: 'typography', label: t('Etichetta'),
      presetKey: 'typography_preset',
      responsiveKeys: ['size'],
      keys: {
        family:        'label_font_family',
        size:          'label_size',
        weight:        'label_weight',
        color:         'label_color',
        transform:     'label_transform',
        letterSpacing: 'label_letter_spacing',
      },
      sizeMin: 11, sizeMax: 18, sizeStep: 1,
    },

    { type: 'separator', label: t('Stile campi') },
    { key: 'form_layout', label: t('Layout form'), type: 'select', options: [
      { value: 'stacked', label: t('Label sopra (stacked)') },
      { value: 'floating', label: t('Label fluttuante') },
    ]},
    { key: 'input_border_style', label: t('Stile bordo campo'), type: 'select', options: [
      { value: 'box', label: t('Riquadro (tutti i lati)') },
      { value: 'underline', label: t('Solo linea inferiore') },
      { value: 'none', label: t('Nessun bordo') },
    ]},
    { key: 'input_bg', label: t('Sfondo input'), type: 'color' },
    { key: 'input_color', label: t('Colore testo input'), type: 'color' },
    { key: 'input_border_color', label: t('Colore bordo input'), type: 'color' },
    { key: 'input_border_width', label: t('Spessore bordo (px)'), type: 'range', min: 0, max: 3 },
    withHover({ key: 'input_radius', label: t('Raggio bordo input (px)'), type: 'border-radius' }),
    { key: 'input_size', label: t('Dimensione input'), type: 'select', options: [
      { value: 'small', label: t('Piccolo') },
      { value: 'default', label: t('Normale') },
      { value: 'large', label: t('Grande') },
    ]},
    { type: 'typography', label: t('Font campi'),
      keys: { family: 'input_font_family' },
    },
    { key: 'input_focus_border', label: t('Colore bordo focus'), type: 'color' },
    { key: 'input_focus_shadow', label: t('Ombra focus'), type: 'toggle' },
    { key: 'input_placeholder_opacity', label: t('Opacità placeholder'), type: 'range', min: 0.2, max: 0.8, step: 0.05 },
    { key: 'gap', label: t('Gap tra campi (px)'), type: 'range', min: 8, max: 32, step: 4 },

    { type: 'separator', label: t('Stile pulsante') },
    { key: 'submit_bg', label: t('Sfondo pulsante'), type: 'color' },
    { key: 'submit_color', label: t('Colore testo pulsante'), type: 'color' },
    { key: 'submit_hover_bg', label: t('Sfondo pulsante hover'), type: 'color' },
    withHover({ key: 'submit_radius', label: t('Raggio bordo (px)'), type: 'border-radius' }),
    { key: 'tile_padding', label: t('Padding (px)'), type: 'spacing', max: 48 },
    { type: 'typography', label: t('Pulsante'),
      presetKey: 'typography_preset',
      responsiveKeys: ['size', 'letterSpacing'],
      keys: {
        family:        'submit_font_family',
        size:          'submit_font_size',
        weight:        'submit_font_weight',
        letterSpacing: 'submit_letter_spacing',
        transform:     'submit_text_transform',
      },
      sizeMin: 12, sizeMax: 22, sizeStep: 1,
    },
    { key: 'submit_border_width', label: t('Bordo pulsante (px)'), type: 'range', min: 0, max: 4 },
    withHover(
      { key: 'submit_border_color', label: t('Colore bordo pulsante'), type: 'color',
        condition: { field: 'submit_border_width', operator: '>', value: 0 } },
      { hoverKey: 'submit_hover_border_color' }
    ),

    { type: 'separator', label: t('Checkbox e Radio') },
    { key: 'check_accent_color', label: t('Colore accento (checked)'), type: 'color' },
    { key: 'check_bg', label: t('Sfondo'), type: 'color' },
    { key: 'check_border_color', label: t('Colore bordo'), type: 'color' },
    { key: 'check_size', label: t('Dimensione (px)'), type: 'range', min: 14, max: 24 },
    { key: 'check_label_gap', label: t('Gap etichetta (px)'), type: 'range', min: 4, max: 16 },

    ...borderFields(),
  ],
};
