import { textEffectsFields, textEffectsDefaults, withHover } from './_shared';
import { shadowField } from './_shared.js';
import { t } from '@/i18n';

/**
 * Tile Grid — split CONTENUTO/STILE (regola universale Olobuild).
 *   fields[]      → items (content-items), colonne, gap, equal_height, image_ratio,
 *                   image_fit, image_zoom, image_animation (behavior), toggle overlay_text,
 *                   posizione overlay, toggle show_filter, etichetta filtro, masonry
 *   styleFields[] → preset, bg, typography_preset, textEffectsFields, card_style, card_hover,
 *                   card_radius, padding, colori card, image_height, image_animation_speed (ms),
 *                   tipografia (dim titolo/testo, colori), stile filtro, allineamento filtro,
 *                   shadow
 */
export default {
  type: 'grid',
  name: t('Griglia'),
  icon: 'dashicons-grid-view',
  category: 'layout',
  defaults: {
    preset: 'custom',
    bg: { type: 'none' },
    typography_preset: '',
    items: [
      { id: 'g-1', title: t('Elemento 1'), content: 'Descrizione del primo elemento.', image: '', tag: 'all' },
      { id: 'g-2', title: t('Elemento 2'), content: 'Descrizione del secondo elemento.', image: '', tag: 'all' },
      { id: 'g-3', title: t('Elemento 3'), content: 'Descrizione del terzo elemento.', image: '', tag: 'all' },
    ],
    columns: '3',
    gap: 'default',
    show_filter: false,
    filter_style: 'pills',
    filter_align: 'left',
    masonry: false,
    card_style: 'default',
    shadow: 'none',
    card_hover: 'none',
    image_ratio: 'auto',
    image_height: '',
    image_fit: 'cover',
    object_position: 'center center',
    image_zoom: false,
    card_radius: '8',
    tile_padding: { top: 16, right: 16, bottom: 16, left: 16 },
    card_bg_color: '',
    card_border_color: '',
    equal_height: false,
    overlay_text: false,
    overlay_position: 'bottom',
    title_size: '',
    content_size: '',
    title_color: '',
    content_color: '',
    image_animation: 'none',
    image_animation_speed: '3',
    ...textEffectsDefaults,
    text_effect_target: 'title',
  },

  // ─── CONTENUTO ─────────────────────────────────────────────
  fields: [
    { key: 'items', label: t('Elementi'), type: 'content-items', supportsDynamic: true,
      itemFields: [
        { key: 'title', label: t('Titolo'), type: 'text' },
        { key: 'content', label: t('Contenuto'), type: 'textarea' },
        { key: 'image', label: t('Immagine'), type: 'image' },
        { key: 'hover_image', label: t('Immagine hover'), type: 'image' },
        { key: 'hover_video', label: t('Video hover'), type: 'media' },
        { key: 'tag', label: t('Tag filtro'), type: 'text', description: t('Separare più tag con virgola (es. natura, sport)') },
        { key: 'link', label: t('Link'), type: 'link' },
        { key: 'link_target', label: t('Apri in nuova scheda'), type: 'toggle' },
        { key: 'badge', label: t('Badge'), type: 'text' },
        { key: 'badge_color', label: t('Colore badge'), type: 'color' },
        { key: 'icon', label: t('Icona'), type: 'icon' },
      ],
      newItemDefaults: { title: t('Nuovo elemento'), content: '', image: '', hover_image: '', hover_video: '', tag: 'all', link: '', link_target: false, badge: '', badge_color: '', icon: '' },
    },
    { key: 'columns', label: t('Colonne'), type: 'select', responsive: true, options: [
      { value: '1', label: '1' },
      { value: '2', label: '2' },
      { value: '3', label: '3' },
      { value: '4', label: '4' },
      { value: '5', label: '5' },
      { value: '6', label: '6' },
    ]},
    { key: 'gap', label: t('Gap'), type: 'select', options: [
      { value: 'collapse', label: t('Collassato') },
      { value: 'small', label: t('Piccolo') },
      { value: 'default', label: t('Predefinito') },
      { value: 'medium', label: t('Medio') },
      { value: 'large', label: t('Grande') },
    ]},
    { key: 'equal_height', label: t('Altezza uguale'), type: 'toggle' },

    { type: 'separator', label: t('Immagine') },
    { key: 'image_ratio', label: t('Proporzione immagine'), type: 'select', options: [
      { value: 'auto', label: t('Automatica') },
      { value: '1/1', label: t('1:1 Quadrato') },
      { value: '4/3', label: '4:3' },
      { value: '3/2', label: '3:2' },
      { value: '16/9', label: '16:9' },
      { value: '3/4', label: t('3:4 Verticale') },
      { value: '2/3', label: t('2:3 Verticale') },
    ]},
    { key: 'image_fit', label: t('Adattamento immagine'), type: 'select', options: [
      { value: 'cover', label: t('Copri') },
      { value: 'contain', label: t('Contieni') },
      { value: 'fill', label: t('Riempi') },
    ]},
    { key: 'object_position', label: t('Posizione contenuto'), type: 'object-position', reveal: true,
      contextKeys: { fit: 'image_fit', ratio: 'image_ratio', ratioCustom: '' },
      description: t('Punto focale globale: applicato a tutte le immagini della griglia.') },
    { key: 'image_zoom', label: t('Zoom immagine al hover'), type: 'toggle' },
    { key: 'image_animation', label: t('Animazione continua immagine'), type: 'select', options: [
      { value: 'none', label: t('Nessuna') },
      { value: 'ken-burns', label: t('Ken Burns (zoom lento)') },
      { value: 'pan-left', label: t('Panoramica sinistra') },
      { value: 'pan-right', label: t('Panoramica destra') },
      { value: 'pan-up', label: t('Panoramica su') },
      { value: 'pan-down', label: t('Panoramica giù') },
      { value: 'pulse', label: t('Pulsazione') },
      { value: 'float', label: t('Galleggiamento') },
      { value: 'rotate', label: t('Rotazione lenta') },
      { value: 'shimmer', label: t('Luccichio (shimmer)') },
    ]},

    { type: 'separator', label: t('Overlay') },
    { key: 'overlay_text', label: t('Testo su immagine'), type: 'toggle' },
    { key: 'overlay_position', label: t('Posizione testo'), type: 'select', options: [
      { value: 'bottom', label: t('In basso') },
      { value: 'center', label: t('Centrato') },
      { value: 'top', label: t('In alto') },
    ], condition: { field: 'overlay_text', op: 'eq', value: true } },

    { type: 'separator', label: t('Filtro') },
    { key: 'show_filter', label: t('Mostra filtro'), type: 'toggle' },
    { key: 'filter_all_label', label: 'Etichetta "Tutti"', type: 'text', description: t('Vuoto = All'),
      condition: { field: 'show_filter', value: true } },

    { type: 'separator', label: t('Avanzato') },
    { key: 'masonry', label: t('Masonry'), type: 'toggle' },
  ],

  // ─── STILE ─────────────────────────────────────────────────
  styleFields: [
    { type: 'separator', label: t('Preset stilistico') },
    { key: 'preset', label: t('Stile'), type: 'select', options: [
      { value: 'modern-clean',    label: t('Modern Clean') },
      { value: 'minimal-mono',    label: t('Minimal Mono') },
      { value: 'magazine-bold',   label: t('Magazine Bold') },
      { value: 'editorial-serif', label: t('Editorial Serif') },
      { value: 'compact-inline',  label: t('Compact Inline') },
      { value: 'glass-frosted',   label: t('Glass Frosted') },
      { value: 'neon-glow',       label: t('Neon Glow') },
      { value: 'brutalist-stamp', label: t('Brutalist Stamp') },
      { value: 'gradient-aurora', label: t('Gradient Aurora') },
      { value: 'sticker-fun',     label: t('Sticker Fun') },
      { value: 'retro-terminal',  label: t('Retro Terminal') },
      { value: 'tilt-3d',         label: t('3D Tilt') },
      { value: 'custom',          label: t('Personalizzato') },
    ] },
    { key: 'typography_preset', label: t('Stile tipografico'), type: 'select', optionsSource: 'globalTypography' },

    ...textEffectsFields([
      { value: 'title', label: t('Solo Titolo') },
      { value: 'content', label: t('Solo Contenuto') },
      { value: 'all', label: t('Tutti gli elementi testuali') },
    ]),

    { type: 'separator', label: t('Stile Card') },
    { key: 'card_style', label: t('Stile card'), type: 'select', options: [
      { value: 'default', label: t('Predefinito') },
      { value: 'minimal', label: t('Minimale') },
      { value: 'outlined', label: t('Bordo') },
      { value: 'elevated', label: t('Elevata') },
      { value: 'glass', label: t('Vetro (Glass)') },
      { value: 'gradient', label: t('Bordo sfumato') },
      { value: 'flat', label: t('Piatta') },
    ]},
    { key: 'card_hover', label: t('Effetto hover card'), type: 'select', options: [
      { value: 'none', label: t('Nessuno') },
      { value: 'lift', label: t('Solleva') },
      { value: 'scale', label: t('Ingrandisci') },
      { value: 'glow', label: t('Bagliore') },
      { value: 'border-glow', label: t('Bordo luminoso') },
      { value: 'tilt', label: t('Inclinazione 3D') },
    ]},
    withHover({ key: 'card_radius', label: t('Raggio bordi (px)'), type: 'border-radius'}),
    { key: 'tile_padding', label: t('Padding (px)'), type: 'spacing', max: 48 },
    { key: 'card_bg_color', label: t('Colore sfondo card'), type: 'color' },
    { key: 'card_border_color', label: t('Colore bordo card'), type: 'color' },

    { type: 'separator', label: t('Immagine — stile') },
    { key: 'image_height', label: t('Altezza immagine (px)'), type: 'range', min: 0, max: 500, step: 10,
      description: t('0 = automatica') },
    { key: 'image_animation_speed', label: t('Velocità animazione (s)'), type: 'range', min: 2, max: 20, step: 1,
      condition: { field: 'image_animation', operator: '!=', value: 'none' } },

    { type: 'separator', label: t('Tipografia') },
    { type: 'typography', label: t('Titolo'),
      presetKey: 'typography_preset',
      responsiveKeys: ['size'],
      keys: {
        size:  'title_size',
        color: 'title_color',
      },
      sizeMin: 0, sizeMax: 48, sizeStep: 1,
    },
    { type: 'typography', label: t('Contenuto'),
      presetKey: 'typography_preset',
      responsiveKeys: ['size'],
      keys: {
        size:  'content_size',
        color: 'content_color',
      },
      sizeMin: 0, sizeMax: 24, sizeStep: 1,
    },

    { type: 'separator', label: t('Filtro — stile') },
    { key: 'filter_style', label: t('Stile filtro'), type: 'select', options: [
      { value: 'pills', label: t('Pills') },
      { value: 'minimal', label: t('Minimale') },
      { value: 'buttons', label: t('Bottoni') },
    ], condition: { field: 'show_filter', value: true } },
    { key: 'filter_align', label: t('Allineamento filtri'), type: 'select', options: [
      { value: 'left', label: t('Sinistra') },
      { value: 'center', label: t('Centro') },
      { value: 'right', label: t('Destra') },
    ], condition: { field: 'show_filter', value: true } },

    ...shadowField,
  ],
};
