import { shadowField } from './_shared.js';

export default {
  type: 'grid',
  name: 'Griglia',
  icon: 'dashicons-grid-view',
  category: 'layout',
  defaults: {
    items: [
      { id: 'g-1', title: 'Elemento 1', content: 'Descrizione del primo elemento.', image: '', tag: 'all' },
      { id: 'g-2', title: 'Elemento 2', content: 'Descrizione del secondo elemento.', image: '', tag: 'all' },
      { id: 'g-3', title: 'Elemento 3', content: 'Descrizione del terzo elemento.', image: '', tag: 'all' },
    ],
    columns: '3',
    gap: 'default',
    show_filter: false,
    filter_style: 'pills',
    filter_align: 'left',
    masonry: false,
    card_style: 'default',
    shadow: 'none',
    card_hover: 'none',
    image_ratio: 'auto',
    image_height: '',
    image_fit: 'cover',
    image_zoom: false,
    card_radius: '8',
    tile_padding: { top: 16, right: 16, bottom: 16, left: 16 },
    card_bg_color: '',
    card_border_color: '',
    equal_height: false,
    overlay_text: false,
    overlay_position: 'bottom',
    title_size: '',
    content_size: '',
    title_color: '',
    content_color: '',
    image_animation: 'none',
    image_animation_speed: '3',
  },
  fields: [
    { key: 'items', label: 'Elementi', type: 'content-items', supportsDynamic: true,
      itemFields: [
        { key: 'title', label: 'Titolo', type: 'text' },
        { key: 'content', label: 'Contenuto', type: 'textarea' },
        { key: 'image', label: 'Immagine', type: 'image' },
        { key: 'hover_image', label: 'Immagine hover', type: 'image' },
        { key: 'hover_video', label: 'Video hover', type: 'media' },
        { key: 'tag', label: 'Tag filtro', type: 'text', description: 'Separare più tag con virgola (es. natura, sport)' },
        { key: 'link', label: 'Link', type: 'text' },
        { key: 'link_target', label: 'Apri in nuova scheda', type: 'toggle' },
        { key: 'badge', label: 'Badge', type: 'text' },
        { key: 'badge_color', label: 'Colore badge', type: 'color' },
        { key: 'icon', label: 'Icona', type: 'icon' },
      ],
      newItemDefaults: { title: 'Nuovo elemento', content: '', image: '', hover_image: '', hover_video: '', tag: 'all', link: '', link_target: false, badge: '', badge_color: '', icon: '' },
    },
    { key: 'columns', label: 'Colonne', type: 'select', responsive: true, options: [
      { value: '1', label: '1' },
      { value: '2', label: '2' },
      { value: '3', label: '3' },
      { value: '4', label: '4' },
      { value: '5', label: '5' },
      { value: '6', label: '6' },
    ]},
    { key: 'gap', label: 'Gap', type: 'select', options: [
      { value: 'collapse', label: 'Collassato' },
      { value: 'small', label: 'Piccolo' },
      { value: 'default', label: 'Predefinito' },
      { value: 'medium', label: 'Medio' },
      { value: 'large', label: 'Grande' },
    ]},
    { key: 'equal_height', label: 'Altezza uguale', type: 'toggle' },

    { type: 'separator', label: 'Stile Card' },
    { key: 'card_style', label: 'Stile card', type: 'select', options: [
      { value: 'default', label: 'Predefinito' },
      { value: 'minimal', label: 'Minimale' },
      { value: 'outlined', label: 'Bordo' },
      { value: 'elevated', label: 'Elevata' },
      { value: 'glass', label: 'Vetro (Glass)' },
      { value: 'gradient', label: 'Bordo sfumato' },
      { value: 'flat', label: 'Piatta' },
    ]},
    { key: 'card_hover', label: 'Effetto hover card', type: 'select', options: [
      { value: 'none', label: 'Nessuno' },
      { value: 'lift', label: 'Solleva' },
      { value: 'scale', label: 'Ingrandisci' },
      { value: 'glow', label: 'Bagliore' },
      { value: 'border-glow', label: 'Bordo luminoso' },
      { value: 'tilt', label: 'Inclinazione 3D' },
    ]},
    { key: 'card_radius', label: 'Raggio bordi (px)', type: 'range', min: 0, max: 32, step: 2 },
    { key: 'tile_padding', label: 'Padding (px)', type: 'spacing', max: 48 },
    { key: 'card_bg_color', label: 'Colore sfondo card', type: 'color' },
    { key: 'card_border_color', label: 'Colore bordo card', type: 'color' },
    ...shadowField,

    { type: 'separator', label: 'Immagine' },
    { key: 'image_ratio', label: 'Proporzione immagine', type: 'select', options: [
      { value: 'auto', label: 'Automatica' },
      { value: '1/1', label: '1:1 Quadrato' },
      { value: '4/3', label: '4:3' },
      { value: '3/2', label: '3:2' },
      { value: '16/9', label: '16:9' },
      { value: '3/4', label: '3:4 Verticale' },
      { value: '2/3', label: '2:3 Verticale' },
    ]},
    { key: 'image_height', label: 'Altezza immagine (px)', type: 'range', min: 0, max: 500, step: 10,
      description: '0 = automatica' },
    { key: 'image_fit', label: 'Adattamento immagine', type: 'select', options: [
      { value: 'cover', label: 'Copri' },
      { value: 'contain', label: 'Contieni' },
      { value: 'fill', label: 'Riempi' },
    ]},
    { key: 'image_zoom', label: 'Zoom immagine al hover', type: 'toggle' },
    { key: 'image_animation', label: 'Animazione continua immagine', type: 'select', options: [
      { value: 'none', label: 'Nessuna' },
      { value: 'ken-burns', label: 'Ken Burns (zoom lento)' },
      { value: 'pan-left', label: 'Panoramica sinistra' },
      { value: 'pan-right', label: 'Panoramica destra' },
      { value: 'pan-up', label: 'Panoramica su' },
      { value: 'pan-down', label: 'Panoramica gi\u00f9' },
      { value: 'pulse', label: 'Pulsazione' },
      { value: 'float', label: 'Galleggiamento' },
      { value: 'rotate', label: 'Rotazione lenta' },
      { value: 'shimmer', label: 'Luccichio (shimmer)' },
    ]},
    { key: 'image_animation_speed', label: 'Velocit\u00e0 animazione (s)', type: 'range', min: 2, max: 20, step: 1,
      condition: { field: 'image_animation', operator: '!=', value: 'none' } },

    { type: 'separator', label: 'Overlay' },
    { key: 'overlay_text', label: 'Testo su immagine', type: 'toggle' },
    { key: 'overlay_position', label: 'Posizione testo', type: 'select', options: [
      { value: 'bottom', label: 'In basso' },
      { value: 'center', label: 'Centrato' },
      { value: 'top', label: 'In alto' },
    ], condition: { field: 'overlay_text', op: 'eq', value: true } },

    { type: 'separator', label: 'Tipografia' },
    { key: 'title_size', label: 'Dimensione titolo (px)', type: 'range', min: 0, max: 48, step: 1,
      description: '0 = predefinito' },
    { key: 'content_size', label: 'Dimensione testo (px)', type: 'range', min: 0, max: 24, step: 1,
      description: '0 = predefinito' },
    { key: 'title_color', label: 'Colore titolo', type: 'color' },
    { key: 'content_color', label: 'Colore testo', type: 'color' },

    { type: 'separator', label: 'Filtro' },
    { key: 'show_filter', label: 'Mostra filtro', type: 'toggle' },
    { key: 'filter_all_label', label: 'Etichetta "Tutti"', type: 'text', description: 'Vuoto = All',
      condition: { field: 'show_filter', value: true } },
    { key: 'filter_style', label: 'Stile filtro', type: 'select', options: [
      { value: 'pills', label: 'Pills' },
      { value: 'minimal', label: 'Minimale' },
      { value: 'buttons', label: 'Bottoni' },
    ], condition: { field: 'show_filter', value: true } },
    { key: 'filter_align', label: 'Allineamento filtri', type: 'select', options: [
      { value: 'left', label: 'Sinistra' },
      { value: 'center', label: 'Centro' },
      { value: 'right', label: 'Destra' },
    ], condition: { field: 'show_filter', value: true } },

    { type: 'separator', label: 'Avanzato' },
    { key: 'masonry', label: 'Masonry', type: 'toggle' },
  ],
};
