import { textEffectsFields, textEffectsDefaults, borderFields, borderDefault, borderHoverDefault, borderEffectDefaults } from './_shared';
import { shadowField } from './_shared.js';
import { t } from '@/i18n';

/**
 * Tile Headline — split CONTENUTO/STILE (regola universale Olobuild).
 *   fields[]      → solo dati testuali (heading, subtitle, tag HTML)
 *   styleFields[] → tutto l'aspetto (preset, colori, tipografia, decorazione, effetti, ombra, bordo)
 *   AVANZATE      → meta tecnico (id/class/condizioni)
 */
export default {
  type: 'headline',
  name: t('Titolo'),
  icon: 'dashicons-heading',
  category: 'essential',
  defaults: {
    bg: { type: 'none' },
    preset: 'custom',
    heading: t('Nuovo Titolo'),
    subtitle: '',
    tag: 'h2',
    alignment: 'center',
    typography_preset: '',
    heading_size: 'lg',
    heading_font_size: '0',
    subtitle_font_size: '0',
    heading_color: '',
    heading_italic: false,
    heading_uppercase: false,
    decoration: 'line',
    decoration_color: '',
    subtitle_color: '',
    text_stroke: '0',
    text_stroke_color: '',
    text_shadow: '',
    gradient_text: false,
    gradient_from: '',
    gradient_to: '',
    gradient_angle: '90',
    blend_mode: 'normal',
    shadow: 'none',
    ...textEffectsDefaults,
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
  },

  // ─── CONTENUTO ─────────────────────────────────────────────
  fields: [
    { key: 'heading', label: t('Titolo'), type: 'textarea' },
    { key: 'subtitle', label: t('Sottotitolo'), type: 'textarea' },
  ],

  // ─── STILE ─────────────────────────────────────────────────
  styleFields: [
    { type: 'separator', label: t('Preset stilistico') },
    { key: 'preset', label: t('Stile'), type: 'select', options: [
      { value: 'modern-clean', label: t('Modern Clean') },
      { value: 'minimal-mono', label: t('Minimal Mono') },
      { value: 'magazine-editorial', label: t('Magazine Editorial') },
      { value: 'editorial-serif', label: t('Editorial Serif') },
      { value: 'compact-inline', label: t('Compact Inline') },
      { value: 'glass-overlay', label: t('Glass Overlay') },
      { value: 'neon-glow', label: t('Neon Glow') },
      { value: 'brutalist-mega', label: t('Brutalist Mega') },
      { value: 'gradient-aurora', label: t('Gradient Aurora') },
      { value: 'sticker-fun', label: t('Sticker Fun') },
      { value: 'retro-terminal', label: t('Retro Terminal') },
      { value: 'tilt-3d', label: t('3D Tilt') },
      { value: 'custom', label: t('Personalizzato') },
    ]},
    ...textEffectsFields([
      { value: 'heading', label: t('Solo Titolo') },
      { value: 'subtitle', label: t('Solo Sottotitolo') },
      { value: 'all', label: t('Tutti gli elementi testuali') },
    ]),

    { type: 'separator', label: t('Tipografia') },
    { type: 'typography', label: t('Titolo'),
      presetKey: 'typography_preset',
      responsiveKeys: ['size'],
      keys: {
        tag:   'tag',
        size:  'heading_font_size',
        color: 'heading_color',
      },
      sizeMin: 0, sizeMax: 120, sizeStep: 1,
    },
    { type: 'typography', label: t('Sottotitolo'),
      responsiveKeys: ['size'],
      keys: {
        size:  'subtitle_font_size',
        color: 'subtitle_color',
      },
      sizeMin: 0, sizeMax: 60, sizeStep: 1,
    },
    { key: 'heading_size', label: t('Dimensione (preset)'), type: 'select', responsive: true, options: [
      { value: 'sm', label: t('Piccolo') },
      { value: 'md', label: t('Medio') },
      { value: 'lg', label: t('Grande') },
      { value: 'xl', label: t('Extra grande') },
    ]},
    { key: 'alignment', label: t('Allineamento'), type: 'select', responsive: true, options: [
      { value: 'left', label: t('Sinistra') },
      { value: 'center', label: t('Centro') },
      { value: 'right', label: t('Destra') },
      { value: 'justify', label: t('Giustificato') },
    ]},
    { key: 'heading_italic', label: t('Corsivo'), type: 'toggle' },
    { key: 'heading_uppercase', label: t('Maiuscolo'), type: 'toggle' },

    { type: 'separator', label: t('Decorazione') },
    { key: 'decoration', label: t('Tipo'), type: 'select', options: [
      { value: 'none', label: t('Nessuna') },
      { value: 'line', label: t('Linea') },
      { value: 'divider', label: t('Divisore') },
      { value: 'dot', label: t('Punto') },
      { value: 'star', label: t('Stella') },
    ]},
    { key: 'decoration_count', label: t('Quantità'), type: 'range', min: 1, max: 9, step: 1,
      condition: { field: 'decoration', value: ['dot', 'star'] } },
    { key: 'decoration_spacing', label: t('Spaziatura (px)'), type: 'range', min: 2, max: 20, step: 1,
      condition: { field: 'decoration', value: ['dot', 'star'] } },
    { key: 'decoration_color', label: t('Colore decorazione'), type: 'color',
      condition: { field: 'decoration', operator: '!=', value: 'none' } },

    { type: 'separator', label: t('Effetti testo') },
    { key: 'gradient_text', label: t('Testo gradiente'), type: 'toggle' },
    { key: 'gradient_from', label: t('Gradiente da'), type: 'color',
      condition: { field: 'gradient_text', operator: '==', value: true } },
    { key: 'gradient_to', label: t('Gradiente a'), type: 'color',
      condition: { field: 'gradient_text', operator: '==', value: true } },
    { key: 'gradient_angle', label: t('Angolo gradiente (°)'), type: 'range', min: 0, max: 360, step: 15,
      condition: { field: 'gradient_text', operator: '==', value: true } },
    { key: 'text_stroke', label: t('Contorno testo (px)'), type: 'range', min: 0, max: 5, step: 1 },
    { key: 'text_stroke_color', label: t('Colore contorno'), type: 'color',
      condition: { field: 'text_stroke', operator: '>', value: '0' } },
    { key: 'text_shadow', label: t('Ombra testo'), type: 'select', options: [
      { value: '', label: t('Nessuna') },
      { value: '2px 2px 4px rgba(0,0,0,0.3)', label: t('Leggera') },
      { value: '3px 3px 6px rgba(0,0,0,0.4)', label: t('Media') },
      { value: '4px 4px 10px rgba(0,0,0,0.5)', label: t('Forte') },
      { value: '0 0 10px rgba(99,102,241,0.6)', label: t('Bagliore') },
      { value: '0 0 20px rgba(99,102,241,0.8)', label: t('Bagliore forte') },
      { value: 'custom', label: t('Personalizzata') },
    ]},
    { key: 'text_shadow_h', label: t('Offset H (px)'), type: 'range', min: -20, max: 20, step: 1,
      condition: { field: 'text_shadow', op: 'eq', value: 'custom' } },
    { key: 'text_shadow_v', label: t('Offset V (px)'), type: 'range', min: -20, max: 20, step: 1,
      condition: { field: 'text_shadow', op: 'eq', value: 'custom' } },
    { key: 'text_shadow_blur', label: t('Sfocatura (px)'), type: 'range', min: 0, max: 40, step: 1,
      condition: { field: 'text_shadow', op: 'eq', value: 'custom' } },
    { key: 'text_shadow_color', label: t('Colore ombra'), type: 'color',
      condition: { field: 'text_shadow', op: 'eq', value: 'custom' } },
    { key: 'blend_mode', label: t('Blend mode'), type: 'select', options: [
      { value: 'normal', label: t('Normale') },
      { value: 'multiply', label: t('Moltiplica') },
      { value: 'screen', label: t('Schermo') },
      { value: 'overlay', label: t('Sovrapposizione') },
      { value: 'difference', label: t('Differenza') },
    ]},

    ...shadowField,
    ...borderFields(),
  ],
};
