import { textEffectsFields, textEffectsDefaults } from './_shared';
import { shadowField } from './_shared.js';

export default {
  type: 'headline',
  name: 'Titolo',
  icon: 'dashicons-heading',
  category: 'essential',
  defaults: {
    heading: 'Titolo sezione',
    subtitle: '',
    tag: 'h2',
    alignment: 'center',
    typography_preset: '',
    heading_size: 'lg',
    heading_color: '',
    heading_italic: false,
    heading_uppercase: false,
    decoration: 'line',
    decoration_color: '',
    subtitle_color: '',
    text_stroke: '0',
    text_stroke_color: '',
    text_shadow: '',
    gradient_text: false,
    gradient_from: '',
    gradient_to: '',
    gradient_angle: '90',
    blend_mode: 'normal',
    shadow: 'none',
    ...textEffectsDefaults,
  },
  fields: [
    { key: 'heading', label: 'Titolo', type: 'textarea' },
    { key: 'subtitle', label: 'Sottotitolo', type: 'textarea' },
    { type: 'separator', label: 'Aspetto titolo' },
    { key: 'typography_preset', label: 'Stile tipografico', type: 'select', optionsSource: 'globalTypography' },
    { key: 'tag', label: 'Tag HTML', type: 'select', options: [
      { value: 'h1', label: 'H1' },
      { value: 'h2', label: 'H2' },
      { value: 'h3', label: 'H3' },
      { value: 'h4', label: 'H4' },
      { value: 'h5', label: 'H5' },
      { value: 'h6', label: 'H6' },
      { value: 'p', label: 'Paragrafo' },
    ]},
    { key: 'heading_size', label: 'Dimensione', type: 'select', responsive: true, options: [
      { value: 'sm', label: 'Piccolo' },
      { value: 'md', label: 'Medio' },
      { value: 'lg', label: 'Grande' },
      { value: 'xl', label: 'Extra grande' },
    ]},
    { key: 'alignment', label: 'Allineamento', type: 'select', responsive: true, options: [
      { value: 'left', label: 'Sinistra' },
      { value: 'center', label: 'Centro' },
      { value: 'right', label: 'Destra' },
    ]},
    { key: 'heading_color', label: 'Colore titolo', type: 'color',
      condition: { field: 'gradient_text', operator: '!=', value: true } },
    { key: 'heading_italic', label: 'Corsivo', type: 'toggle' },
    { key: 'heading_uppercase', label: 'Maiuscolo', type: 'toggle' },
    { type: 'separator', label: 'Decorazione' },
    { key: 'decoration', label: 'Tipo', type: 'select', options: [
      { value: 'none', label: 'Nessuna' },
      { value: 'line', label: 'Linea' },
      { value: 'divider', label: 'Divisore' },
      { value: 'dot', label: 'Punto' },
      { value: 'star', label: 'Stella' },
    ]},
    { key: 'decoration_count', label: 'Quantità', type: 'range', min: 1, max: 9, step: 1,
      condition: { field: 'decoration', value: ['dot', 'star'] } },
    { key: 'decoration_spacing', label: 'Spaziatura (px)', type: 'range', min: 2, max: 20, step: 1,
      condition: { field: 'decoration', value: ['dot', 'star'] } },
    { key: 'decoration_color', label: 'Colore decorazione', type: 'color',
      condition: { field: 'decoration', operator: '!=', value: 'none' } },
    { type: 'separator', label: 'Effetti testo' },
    { key: 'gradient_text', label: 'Testo gradiente', type: 'toggle' },
    { key: 'gradient_from', label: 'Gradiente da', type: 'color',
      condition: { field: 'gradient_text', operator: '==', value: true } },
    { key: 'gradient_to', label: 'Gradiente a', type: 'color',
      condition: { field: 'gradient_text', operator: '==', value: true } },
    { key: 'gradient_angle', label: 'Angolo gradiente (°)', type: 'range', min: 0, max: 360, step: 15,
      condition: { field: 'gradient_text', operator: '==', value: true } },
    { key: 'text_stroke', label: 'Contorno testo (px)', type: 'range', min: 0, max: 5, step: 1 },
    { key: 'text_stroke_color', label: 'Colore contorno', type: 'color',
      condition: { field: 'text_stroke', operator: '>', value: '0' } },
    { key: 'text_shadow', label: 'Ombra testo', type: 'select', options: [
      { value: '', label: 'Nessuna' },
      { value: '2px 2px 4px rgba(0,0,0,0.3)', label: 'Leggera' },
      { value: '3px 3px 6px rgba(0,0,0,0.4)', label: 'Media' },
      { value: '4px 4px 10px rgba(0,0,0,0.5)', label: 'Forte' },
      { value: '0 0 10px rgba(99,102,241,0.6)', label: 'Bagliore' },
      { value: '0 0 20px rgba(99,102,241,0.8)', label: 'Bagliore forte' },
      { value: 'custom', label: 'Personalizzata' },
    ]},
    { key: 'text_shadow_h', label: 'Offset H (px)', type: 'range', min: -20, max: 20, step: 1,
      condition: { field: 'text_shadow', op: 'eq', value: 'custom' } },
    { key: 'text_shadow_v', label: 'Offset V (px)', type: 'range', min: -20, max: 20, step: 1,
      condition: { field: 'text_shadow', op: 'eq', value: 'custom' } },
    { key: 'text_shadow_blur', label: 'Sfocatura (px)', type: 'range', min: 0, max: 40, step: 1,
      condition: { field: 'text_shadow', op: 'eq', value: 'custom' } },
    { key: 'text_shadow_color', label: 'Colore ombra', type: 'color',
      condition: { field: 'text_shadow', op: 'eq', value: 'custom' } },
    { key: 'blend_mode', label: 'Blend mode', type: 'select', options: [
      { value: 'normal', label: 'Normale' },
      { value: 'multiply', label: 'Moltiplica' },
      { value: 'screen', label: 'Schermo' },
      { value: 'overlay', label: 'Sovrapposizione' },
      { value: 'difference', label: 'Differenza' },
    ]},
    { type: 'separator', label: 'Sottotitolo' },
    { key: 'subtitle_color', label: 'Colore sottotitolo', type: 'color' },
    ...shadowField,
    ...textEffectsFields([
      { value: 'heading', label: 'Solo Titolo' },
      { value: 'subtitle', label: 'Solo Sottotitolo' },
      { value: 'all', label: 'Tutti gli elementi testuali' },
    ]),
  ],
};
