export default {
  type: 'hiddenpop',
  name: 'Popup Nascosto',
  icon: 'dashicons-flag',
  category: 'interactive',
  defaults: {
    // Contenuto
    mode: 'simple',
    title: 'Titolo popup',
    subtitle: '',
    image: '',
    image_position: 'top',
    cta_text: '',
    cta_url: '#',
    cta_style: 'primary',
    cta_target: '_self',
    template_id: 0,
    // Modale
    modal_max_width: 560,
    modal_bg_color: '#ffffff',
    modal_shadow: 'lg',
    modal_radius: '16',
    modal_border_width: '0',
    modal_border_color: '',
    modal_overlay: '60',
    modal_close_button: true,
    popup_close_overlay: true,
    popup_overlay_blur: 0,
    popup_animation: 'slide-up',
    // Stile testo
    title_color: '#111827',
    title_size: '24',
    text_color: '#4b5563',
    // Trigger
    trigger_threshold: 50,
    trigger_direction: 'down',
    exit_intent: false,
    retrigger: false,
    popup_frequency: 'always',
    show_max_times: 0,
    // Display rules
    display_device: '',
    display_logged: '',
    display_date_from: '',
    display_date_to: '',
    display_referrer: '',
    tile_padding: { top: 0, right: 0, bottom: 0, left: 0 },
    border_radius: { tl: 0, tr: 0, br: 0, bl: 0 },
  },
  fields: [
    // ── Contenuto ──
    { key: 'mode', label: 'Modalità contenuto', type: 'select', options: [
      { value: 'simple', label: 'Semplice' },
      { value: 'template', label: 'Template Olobuild' },
    ]},
    { key: 'title', label: 'Titolo', type: 'text',
      condition: { field: 'mode', op: 'eq', value: 'simple' } },
    { key: 'subtitle', label: 'Testo / Descrizione', type: 'textarea',
      condition: { field: 'mode', op: 'eq', value: 'simple' } },
    { key: 'image', label: 'Immagine', type: 'image',
      condition: { field: 'mode', op: 'eq', value: 'simple' } },
    { key: 'image_position', label: 'Posizione immagine', type: 'select', options: [
      { value: 'top', label: 'Sopra' },
      { value: 'bottom', label: 'Sotto' },
      { value: 'left', label: 'Sinistra' },
      { value: 'right', label: 'Destra' },
    ], condition: { field: 'mode', op: 'eq', value: 'simple' } },
    { key: 'template_id', label: 'Template', type: 'select', optionsSource: 'templates',
      condition: { field: 'mode', op: 'eq', value: 'template' } },

    { type: 'separator', label: 'Pulsante CTA' },
    { key: 'cta_text', label: 'Testo pulsante', type: 'text', placeholder: 'Lascia vuoto per nascondere',
      condition: { field: 'mode', op: 'eq', value: 'simple' } },
    { key: 'cta_url', label: 'URL pulsante', type: 'text',
      condition: { field: 'mode', op: 'eq', value: 'simple' } },
    { key: 'cta_style', label: 'Stile pulsante', type: 'select', options: [
      { value: 'primary', label: 'Primario' },
      { value: 'secondary', label: 'Secondario' },
      { value: 'danger', label: 'Pericolo' },
      { value: 'text', label: 'Testo' },
    ], condition: { field: 'mode', op: 'eq', value: 'simple' } },
    { key: 'cta_target', label: 'Apri in', type: 'select', options: [
      { value: '_self', label: 'Stessa finestra' },
      { value: '_blank', label: 'Nuova finestra' },
    ], condition: { field: 'mode', op: 'eq', value: 'simple' } },

    { type: 'separator', label: 'Aspetto modale' },
    { key: 'modal_max_width', label: 'Larghezza max (px)', type: 'range', min: 300, max: 900, step: 10 },
    { key: 'modal_bg_color', label: 'Sfondo card', type: 'color' },
    { key: 'title_color', label: 'Colore titolo', type: 'color',
      condition: { field: 'mode', op: 'eq', value: 'simple' } },
    { key: 'title_size', label: 'Dimensione titolo (px)', type: 'range', min: 14, max: 48, step: 1,
      condition: { field: 'mode', op: 'eq', value: 'simple' } },
    { key: 'text_color', label: 'Colore testo', type: 'color',
      condition: { field: 'mode', op: 'eq', value: 'simple' } },
    { key: 'modal_shadow', label: 'Ombra', type: 'select', options: [
      { value: 'none', label: 'Nessuna' },
      { value: 'sm', label: 'Leggera' },
      { value: 'md', label: 'Media' },
      { value: 'lg', label: 'Grande' },
      { value: 'xl', label: 'Extra grande' },
    ]},
    { key: 'modal_radius', label: 'Bordo arrotondato', type: 'border-radius' },
    { key: 'modal_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius' },
    { key: 'modal_border_width', label: 'Spessore bordo', type: 'range', min: 0, max: 10, step: 1 },
    { key: 'modal_border_color', label: 'Colore bordo', type: 'color' },
    { key: 'modal_overlay', label: 'Oscuramento sfondo', type: 'range', min: 0, max: 100, step: 5 },
    { key: 'modal_close_button', label: 'Pulsante chiudi (X)', type: 'toggle' },
    { key: 'popup_close_overlay', label: 'Chiudi su click overlay', type: 'toggle' },
    { key: 'popup_overlay_blur', label: 'Sfocatura overlay (px)', type: 'range', min: 0, max: 20, step: 1 },
    { key: 'popup_animation', label: 'Animazione apertura', type: 'select', options: [
      { value: 'fade', label: 'Fade' },
      { value: 'slide-up', label: 'Scorrimento su' },
      { value: 'slide-down', label: 'Scorrimento giù' },
      { value: 'zoom', label: 'Zoom' },
      { value: 'flip', label: 'Flip' },
    ]},

    { type: 'separator', label: 'Trigger' },
    { key: 'exit_intent', label: 'Exit Intent (mouse verso top)', type: 'toggle' },
    { key: 'trigger_threshold', label: 'Punto di attivazione (% viewport)', type: 'range', min: 10, max: 90, step: 5,
      condition: { field: 'exit_intent', op: 'eq', value: false } },
    { key: 'trigger_direction', label: 'Direzione scroll', type: 'select', options: [
      { value: 'down', label: 'Solo verso il basso' },
      { value: 'up', label: 'Solo verso l\'alto' },
      { value: 'both', label: 'Entrambe le direzioni' },
    ], condition: { field: 'exit_intent', op: 'eq', value: false } },
    { key: 'retrigger', label: 'Ri-attiva a ogni passaggio', type: 'toggle',
      condition: { field: 'exit_intent', op: 'eq', value: false } },
    { key: 'popup_frequency', label: 'Frequenza', type: 'select', options: [
      { value: 'always', label: 'Sempre' },
      { value: 'once_session', label: 'Una volta per sessione' },
      { value: 'once_day', label: 'Una volta al giorno' },
      { value: 'once_week', label: 'Una volta a settimana' },
      { value: 'once_ever', label: 'Solo una volta' },
    ]},
    { key: 'show_max_times', label: 'Max visualizzazioni (0=illimitato)', type: 'range', min: 0, max: 50 },

    { type: 'separator', label: 'Regole visualizzazione' },
    { key: 'display_device', label: 'Dispositivo', type: 'select', options: [
      { value: '', label: 'Tutti' },
      { value: 'desktop', label: 'Solo desktop' },
      { value: 'mobile', label: 'Solo mobile' },
    ]},
    { key: 'display_logged', label: 'Stato utente', type: 'select', options: [
      { value: '', label: 'Tutti' },
      { value: 'logged_in', label: 'Solo loggati' },
      { value: 'logged_out', label: 'Solo visitatori' },
    ]},
    { key: 'display_date_from', label: 'Mostra dal', type: 'date' },
    { key: 'display_date_to', label: 'Mostra fino al', type: 'date' },
    { key: 'display_referrer', label: 'Solo da referrer (contiene)', type: 'text', placeholder: 'google.com' },

    { type: 'separator', label: 'Contenitore' },
    { key: 'tile_padding', type: 'spacing', label: 'Spaziatura interna' },
    { key: 'border_radius', type: 'border-radius', label: 'Raggio bordo' },
    { key: 'border_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius' },
  ],
};
