export default {
  type: 'hostcard',
  name: 'Host Card',
  icon: 'dashicons-admin-users',
  category: 'booking',
  defaults: {
    source: 'auto',
    manual_user_id: '',
    variant: 'card',
    button_text: 'Il tuo gestore',
    button_style: 'primary',
    button_icon: 'user',
    show_photo: true,
    show_bio: true,
    show_phone: true,
    show_email: true,
    show_languages: true,
    show_services: false,
    label_role: 'Gestore della struttura',
    photo_size: '100',
    photo_rounded: true,
    accent_color: '',
    card_bg: '',
    card_radius: '12',
    modal_shadow: 'lg',
    modal_overlay: '60',
  },
  fields: [
    // ── Sorgente ──
    { type: 'separator', label: 'Sorgente dati' },
    { key: 'source', label: 'Sorgente gestore', type: 'select', options: [
      { value: 'auto', label: 'Dal servizio corrente' },
      { value: 'manual', label: 'ID utente manuale' },
    ]},
    { key: 'manual_user_id', label: 'ID utente WordPress', type: 'text',
      condition: { field: 'source', value: 'manual' } },

    // ── Variante ──
    { type: 'separator', label: 'Trigger' },
    { key: 'variant', label: 'Variante', type: 'select', options: [
      { value: 'card', label: 'Mini-card (click apre modal)' },
      { value: 'button', label: 'Pulsante (click apre modal)' },
      { value: 'inline', label: 'Inline (tutto visibile)' },
    ]},
    { key: 'button_text', label: 'Testo pulsante', type: 'text',
      condition: { field: 'variant', value: 'button' } },
    { key: 'button_style', label: 'Stile pulsante', type: 'select', options: [
      { value: 'default', label: 'Default' },
      { value: 'primary', label: 'Primary' },
      { value: 'secondary', label: 'Secondary' },
      { value: 'text', label: 'Testo' },
      { value: 'link', label: 'Link' },
    ], condition: { field: 'variant', value: 'button' } },
    { key: 'button_icon', label: 'Icona pulsante', type: 'icon',
      condition: { field: 'variant', value: 'button' } },

    // ── Contenuto ──
    { type: 'separator', label: 'Contenuto' },
    { key: 'show_photo', label: 'Mostra foto', type: 'toggle' },
    { key: 'show_bio', label: 'Mostra biografia', type: 'toggle' },
    { key: 'show_phone', label: 'Mostra telefono', type: 'toggle' },
    { key: 'show_email', label: 'Mostra email', type: 'toggle' },
    { key: 'show_languages', label: 'Mostra lingue parlate', type: 'toggle' },
    { key: 'show_services', label: 'Mostra strutture gestite', type: 'toggle' },
    { key: 'label_role', label: 'Etichetta ruolo', type: 'text' },

    // ── Stile ──
    { type: 'separator', label: 'Stile' },
    { key: 'photo_size', label: 'Dimensione foto (px)', type: 'range', min: 60, max: 200, step: 4 },
    { key: 'photo_rounded', label: 'Foto circolare', type: 'toggle' },
    { key: 'accent_color', label: 'Colore accento', type: 'color' },
    { key: 'card_bg', label: 'Sfondo card', type: 'color' },
    { key: 'card_radius', label: 'Border radius (px)', type: 'border-radius' },

    // ── Modale ──
    { type: 'separator', label: 'Modale',
      condition: { field: 'variant', operator: '!=', value: 'inline' } },
    { key: 'modal_shadow', label: 'Ombra modale', type: 'select', options: [
      { value: 'none', label: 'Nessuna' },
      { value: 'sm', label: 'Leggera' },
      { value: 'md', label: 'Media' },
      { value: 'lg', label: 'Forte' },
      { value: 'xl', label: 'Molto forte' },
      { value: 'custom', label: 'Personalizzata' },
    ], condition: { field: 'variant', operator: '!=', value: 'inline' } },
    { key: 'modal_shadow_h', label: 'Offset H (px)', type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'modal_shadow', op: 'eq', value: 'custom' } },
    { key: 'modal_shadow_v', label: 'Offset V (px)', type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'modal_shadow', op: 'eq', value: 'custom' } },
    { key: 'modal_shadow_blur', label: 'Sfocatura (px)', type: 'range', min: 0, max: 100, step: 1,
      condition: { field: 'modal_shadow', op: 'eq', value: 'custom' } },
    { key: 'modal_shadow_spread', label: 'Espansione (px)', type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'modal_shadow', op: 'eq', value: 'custom' } },
    { key: 'modal_shadow_color', label: 'Colore ombra', type: 'color',
      condition: { field: 'modal_shadow', op: 'eq', value: 'custom' } },
    { key: 'modal_shadow_inset', label: 'Ombra interna', type: 'toggle',
      condition: { field: 'modal_shadow', op: 'eq', value: 'custom' } },
    { key: 'modal_overlay', label: 'Oscuramento sfondo (%)', type: 'range', min: 0, max: 100, step: 5,
      condition: { field: 'variant', operator: '!=', value: 'inline' } },
  ],
};
