import { textEffectsFields, textEffectsDefaults, borderFields, borderDefault, borderHoverDefault, borderEffectDefaults } from './_shared';
export default {
  type: 'hotspot',
  name: 'Hotspot',
  icon: 'dashicons-location-alt',
  category: 'interactive',
  defaults: {
    image: '',
    image_height: '400',
    markers: [
      { id: 'hs-1', pos_x: '30', pos_y: '40', title: 'Punto di interesse', description: 'Descrizione del primo hotspot.', icon: 'pin', tooltip_position: 'top' },
      { id: 'hs-2', pos_x: '65', pos_y: '55', title: 'Secondo punto', description: 'Descrizione del secondo hotspot.', icon: 'pin', tooltip_position: 'bottom' },
    ],
    border_radius: '0',
    marker_color: '',
    marker_size: '24',
    pulse_animation: true,
    tooltip_bg: '',
    tooltip_color: '',
    tooltip_width: '220',
    ...textEffectsDefaults,
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
  },
  fields: [
    { key: 'image', label: 'Immagine', type: 'image' },
    { key: 'border_radius', label: 'Border Radius immagine', type: 'border-radius' },
    { key: 'border_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius' },
    { key: 'image_height', label: 'Altezza immagine (px)', type: 'range', min: 200, max: 800, step: 10 },
    { key: 'markers', label: 'Marker', type: 'content-items',
      itemFields: [
        { key: 'pos_x', label: 'Posizione X (%)', type: 'range', min: 0, max: 100, step: 1 },
        { key: 'pos_y', label: 'Posizione Y (%)', type: 'range', min: 0, max: 100, step: 1 },
        { key: 'title', label: 'Titolo', type: 'text' },
        { key: 'description', label: 'Descrizione', type: 'text' },
        { key: 'icon', label: 'Icona', type: 'text' },
        { key: 'tooltip_position', label: 'Posizione tooltip', type: 'select', options: [
          { value: 'top', label: 'Sopra' },
          { value: 'bottom', label: 'Sotto' },
          { value: 'left', label: 'Sinistra' },
          { value: 'right', label: 'Destra' },
        ]},
      ],
      newItemDefaults: { pos_x: '50', pos_y: '50', title: 'Nuovo punto', description: 'Descrizione.', icon: 'pin', tooltip_position: 'top' },
      itemLabel: 'Marker',
    },
    { type: 'separator', label: 'Stile marker' },
    { key: 'marker_color', label: 'Colore marker', type: 'color' },
    { key: 'marker_size', label: 'Dimensione marker (px)', type: 'range', min: 16, max: 40, step: 2 },
    { key: 'pulse_animation', label: 'Animazione pulse', type: 'toggle' },
    { type: 'separator', label: 'Stile tooltip' },
    { key: 'tooltip_bg', label: 'Sfondo tooltip', type: 'color' },
    { key: 'tooltip_color', label: 'Colore testo tooltip', type: 'color' },
    { key: 'tooltip_width', label: 'Larghezza tooltip (px)', type: 'range', min: 150, max: 350, step: 10 },
    ...textEffectsFields([
      { value: 'title', label: 'Solo Titolo' },
      { value: 'description', label: 'Solo Descrizione' },
      { value: 'all', label: 'Tutti gli elementi testuali' },
    ]),
    ...borderFields(),
  ],
};
