import { textEffectsFields, textEffectsDefaults, borderFields, borderDefault, borderHoverDefault, borderEffectDefaults } from './_shared';
import { shadowField } from './_shared.js';

export default {
  type: 'iconlist',
  name: 'Lista icone',
  icon: 'dashicons-list-view',
  category: 'text',
  defaults: {
    items: [
      { id: 'il-1', icon: 'check', text: 'Prima voce della lista', color: '' },
      { id: 'il-2', icon: 'check', text: 'Seconda voce della lista', color: '' },
      { id: 'il-3', icon: 'check', text: 'Terza voce della lista', color: '' },
    ],
    icon_color: '',
    icon_size: '20',
    text_color: '',
    text_size: '16',
    gap: '12',
    icon_shape: 'none',
    icon_bg_color: '',
    divider: false,
    divider_color: '',
    layout: 'vertical',
    shadow: 'none',
    ...textEffectsDefaults,
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
  },
  fields: [
    { key: 'items', label: 'Voci lista', type: 'content-items',
      itemFields: [
        { key: 'icon', label: 'Icona', type: 'icon' },
        { key: 'text', label: 'Testo', type: 'text' },
        { key: 'link', label: 'Link', type: 'text', placeholder: 'https://...' },
        { key: 'color', label: 'Colore icona (override)', type: 'color' },
      ],
      itemDefaults: { icon: 'check', text: 'Nuova voce', color: '', link: '' },
    },
    { type: 'separator', label: 'Stile icone' },
    { key: 'icon_color', label: 'Colore icone', type: 'color' },
    { key: 'icon_size', label: 'Dimensione icone (px)', type: 'range', min: 12, max: 48, step: 2 },
    { key: 'icon_shape', label: 'Sfondo icona', type: 'select', options: [
      { value: 'none', label: 'Nessuno' },
      { value: 'circle', label: 'Cerchio' },
      { value: 'square', label: 'Quadrato' },
      { value: 'rounded', label: 'Arrotondato' },
    ]},
    { key: 'icon_bg_color', label: 'Colore sfondo icona', type: 'color',
      condition: { field: 'icon_shape', operator: '!=', value: 'none' } },
    { type: 'separator', label: 'Testo' },
    { key: 'text_color', label: 'Colore testo', type: 'color' },
    { key: 'text_size', label: 'Dimensione testo (px)', type: 'range', min: 12, max: 28, step: 1 },
    { type: 'separator', label: 'Layout' },
    { key: 'gap', label: 'Spazio tra voci (px)', type: 'range', min: 4, max: 32, step: 2 },
    { key: 'layout', label: 'Orientamento', type: 'select', options: [
      { value: 'vertical', label: 'Verticale' },
      { value: 'horizontal', label: 'Orizzontale' },
    ]},
    { key: 'divider', label: 'Separatore', type: 'toggle' },
    { key: 'divider_color', label: 'Colore separatore', type: 'color',
      condition: { field: 'divider', operator: '==', value: true } },
    ...shadowField,
    ...textEffectsFields([ { value: 'text', label: 'Solo Testo' } ]),
    ...borderFields(),
  ],
};
