import { textEffectsFields, textEffectsDefaults } from './_shared';
export default {
  type: 'icontabs',
  name: 'Tab a Icone',
  icon: 'dashicons-menu-alt',
  category: 'interactive',
  defaults: {
    items: [
      { id: 'it-1', icon: 'location', label: 'Viaggi', heading: 'HeyConad Viaggi', title: 'Catalogo vacanze di primavera ed estate', content: 'Destinazioni da sogno? Prenota subito la tua vacanza ideale.', link_text: 'Scopri tutte le offerte', link_url: '#' },
      { id: 'it-2', icon: 'tablet',   label: 'Mobile', heading: 'HeyConad Mobile',  title: 'Tariffe mobile esclusive',            content: 'Naviga e chiama senza pensieri a prezzi vantaggiosi.', link_text: 'Scopri le tariffe',       link_url: '#' },
      { id: 'it-3', icon: 'lock',     label: 'Tutela', heading: 'HeyConad Tutela',  title: 'Assicurazioni pensate per te',        content: 'Protezione per casa, persona e animali.',             link_text: 'Scopri i prodotti',       link_url: '#' },
    ],
    pill_bg: '#F5F2EB',
    active_bg: '#E8622A',
    active_color: '#FFFFFF',
    inactive_color: '#1A1A1A',
    card_bg: '#F9D7D7',
    card_radius: '16',
    heading_color: '#E8622A',
    title_color: '#1A1A1A',
    text_color: '#333333',
    link_color: '#2563EB',
    default_index: '0',
    ...textEffectsDefaults,
  },
  fields: [
    { key: 'items', label: 'Schede', type: 'content-items',
      itemFields: [
        { key: 'icon', label: 'Icona', type: 'icon' },
        { key: 'label', label: 'Etichetta attiva', type: 'text' },
        { type: 'separator', label: 'Contenuto scheda' },
        { key: 'heading', label: 'Occhiello', type: 'text' },
        { key: 'title', label: 'Titolo', type: 'text' },
        { key: 'content', label: 'Testo', type: 'textarea' },
        { key: 'link_text', label: 'Testo link', type: 'text' },
        { key: 'link_url', label: 'URL link', type: 'text' },
      ],
      newItemDefaults: { icon: 'star', label: 'Nuova', heading: '', title: '', content: '', link_text: '', link_url: '#' },
    },
    { type: 'separator', label: 'Stile pill' },
    { key: 'pill_bg', label: 'Sfondo pill', type: 'color' },
    { key: 'active_bg', label: 'Sfondo attivo', type: 'color' },
    { key: 'active_color', label: 'Icona attiva', type: 'color' },
    { key: 'inactive_color', label: 'Icone inattive', type: 'color' },
    { type: 'separator', label: 'Stile card' },
    { key: 'card_bg', label: 'Sfondo card', type: 'color' },
    { key: 'card_radius', label: 'Raggio card', type: 'border-radius'},
    { key: 'card_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius' },
    { key: 'heading_color', label: 'Occhiello', type: 'color' },
    { key: 'title_color', label: 'Titolo', type: 'color' },
    { key: 'text_color', label: 'Testo', type: 'color' },
    { key: 'link_color', label: 'Link', type: 'color' },
    { type: 'separator', label: 'Comportamento' },
    { key: 'default_index', label: 'Scheda attiva iniziale (0-based)', type: 'text' },
    ...textEffectsFields([
      { value: 'label', label: 'Solo Etichetta' },
      { value: 'heading', label: 'Solo Titolo' },
      { value: 'title', label: 'Solo Titolo' },
      { value: 'content', label: 'Solo Contenuto' },
      { value: 'all', label: 'Tutti gli elementi testuali' },
    ]),
  ],
};
