import { shadowField } from './_shared.js';

export default {
  type: 'iconbox',
  name: 'Icon Box',
  icon: 'dashicons-star-filled',
  category: 'content',
  defaults: {
    icon_emoji: 'star',
    title: 'Titolo funzionalità',
    description: 'Una breve descrizione.',
    link_url: '',
    link_text: 'Scopri di più',
    alignment: 'center',
    text_color: '',
    icon_size: '3',
    icon_position: 'top',
    icon_bg_color: '',
    icon_bg_shape: 'circle',
    icon_color: '',
    title_font_size: '20',
    title_font_weight: '600',
    title_color: '',
    link_color: '',
    shadow: 'none',
    icon_gap: '16',
    title_gap: '8',
    desc_gap: '16',
    bg_type: 'none',
    bg_color: '',
    bg_gradient: null,
    bg_image: '',
    bg_image_size: 'cover',
    bg_image_position: 'center center',
    tile_padding: { top: 24, right: 24, bottom: 24, left: 24 },
    border_radius: { tl: 0, tr: 0, br: 0, bl: 0 },
    border_width: '0',
    border_style: 'solid',
    border_color: '',
  },
  fields: [
    { key: 'icon_emoji', label: 'Icona / Emoji', type: 'icon' },
    { key: 'title', label: 'Titolo', type: 'text' },
    { key: 'description', label: 'Descrizione', type: 'textarea' },
    { key: 'link_url', label: 'URL link', type: 'text' },
    { key: 'link_text', label: 'Testo link', type: 'text' },
    { key: 'alignment', label: 'Allineamento', type: 'select', options: [
      { value: 'left', label: 'Sinistra' },
      { value: 'center', label: 'Centro' },
      { value: 'right', label: 'Destra' },
    ]},
    { type: 'separator', label: 'Icona' },
    { key: 'icon_size', label: 'Dimensione icona (em)', type: 'range', min: 1, max: 8, step: 0.5 },
    { key: 'icon_position', label: 'Posizione icona', type: 'select', options: [
      { value: 'top', label: 'Sopra' },
      { value: 'left', label: 'Sinistra' },
      { value: 'right', label: 'Destra' },
    ]},
    { key: 'icon_color', label: 'Colore icona', type: 'color' },
    { key: 'icon_bg_color', label: 'Sfondo icona', type: 'color' },
    { key: 'icon_bg_shape', label: 'Forma sfondo icona', type: 'select', options: [
      { value: 'circle', label: 'Cerchio' },
      { value: 'square', label: 'Quadrato' },
      { value: 'rounded', label: 'Arrotondato' },
    ],
      condition: { field: 'icon_bg_color', operator: '!=', value: '' } },
    { type: 'separator', label: 'Tipografia' },
    { key: 'title_font_size', label: 'Dimensione titolo (px)', type: 'range', min: 14, max: 48, step: 1 },
    { key: 'title_font_weight', label: 'Peso titolo', type: 'select', options: [
      { value: '400', label: 'Normale' },
      { value: '500', label: 'Medio' },
      { value: '600', label: 'Semi-grassetto' },
      { value: '700', label: 'Grassetto' },
    ]},
    { type: 'separator', label: 'Spaziatura elementi' },
    { key: 'icon_gap', label: 'Distanza icona-titolo (px)', type: 'range', min: 0, max: 48, step: 2 },
    { key: 'title_gap', label: 'Distanza titolo-testo (px)', type: 'range', min: 0, max: 32, step: 2 },
    { key: 'desc_gap', label: 'Distanza testo-link (px)', type: 'range', min: 0, max: 48, step: 2 },
    { type: 'separator', label: 'Colori' },
    { key: 'title_color', label: 'Colore titolo', type: 'color' },
    { key: 'text_color', label: 'Colore descrizione', type: 'color' },
    { key: 'link_color', label: 'Colore link', type: 'color' },
    { type: 'separator', label: 'Sfondo tile' },
    { key: 'bg_type', label: 'Tipo sfondo', type: 'select', options: [
      { value: 'none', label: 'Nessuno' },
      { value: 'color', label: 'Colore' },
      { value: 'gradient', label: 'Gradiente' },
      { value: 'image', label: 'Immagine' },
    ]},
    { key: 'bg_color', label: 'Colore sfondo', type: 'color',
      condition: { field: 'bg_type', value: 'color' } },
    { key: 'bg_gradient', label: 'Gradiente', type: 'gradient',
      condition: { field: 'bg_type', value: 'gradient' } },
    { key: 'bg_image', label: 'Immagine sfondo', type: 'image',
      condition: { field: 'bg_type', value: 'image' } },
    { key: 'bg_image_size', label: 'Dimensione sfondo', type: 'select', options: [
      { value: 'cover', label: 'Cover' },
      { value: 'contain', label: 'Contain' },
      { value: 'auto', label: 'Auto' },
    ], condition: { field: 'bg_type', value: 'image' } },
    { key: 'bg_image_position', label: 'Posizione sfondo', type: 'select', options: [
      { value: 'center center', label: 'Centro' },
      { value: 'top center', label: 'Alto' },
      { value: 'bottom center', label: 'Basso' },
      { value: 'left center', label: 'Sinistra' },
      { value: 'right center', label: 'Destra' },
    ], condition: { field: 'bg_type', value: 'image' } },
    { type: 'separator', label: 'Bordo e spaziatura' },
    { key: 'tile_padding', label: 'Padding (px)', type: 'spacing', max: 60 },
    { key: 'border_radius', label: 'Raggio bordi (px)', type: 'border-radius' },
    { key: 'border_width', label: 'Spessore bordo (px)', type: 'range', min: 0, max: 10, step: 1 },
    { key: 'border_style', label: 'Stile bordo', type: 'select', options: [
      { value: 'solid', label: 'Continuo' },
      { value: 'dashed', label: 'Tratteggiato' },
      { value: 'dotted', label: 'Punteggiato' },
      { value: 'double', label: 'Doppio' },
    ], condition: { field: 'border_width', operator: '>', value: '0' } },
    { key: 'border_color', label: 'Colore bordo', type: 'color',
      condition: { field: 'border_width', operator: '>', value: '0' } },
    ...shadowField,
  ],
};
