import { textEffectsFields, textEffectsDefaults, shadowField, borderFields, borderDefault, borderHoverDefault, borderEffectDefaults, withHover } from './_shared.js';
import { t } from '@/i18n';

/**
 * Tile Image — split CONTENUTO/STILE (regola universale Olobuild).
 *   fields[]      → asset (url, hover_image/video), alt, didascalia, link
 *   styleFields[] → preset, dimensioni, fit/position, allineamento, filtri, hover-anim, lightbox, ombra, bordo
 *   AVANZATE      → meta tecnico
 */
export default {
  type: 'image',
  name: t('Immagine'),
  icon: 'dashicons-format-image',
  category: 'essential',
  defaults: {
    typography_preset: '',
    preset: 'custom',
    image_url: '',
    media_bg: { type: 'none' },
    media_label: '',
    hover_image: '',
    hover_video: '',
    alt_text: '',
    caption: '',
    link_url: '',
    link_target: '_self',
    image_width: '100%',
    height: '300px',
    max_width: '',
    aspect_ratio: 'auto',
    aspect_ratio_custom: '16/9',
    object_fit: 'cover',
    object_position: 'center center',
    image_alignment: 'center',
    align_in_column: '',
    filter_blur: '0',
    filter_brightness: '100',
    filter_contrast: '100',
    filter_saturate: '100',
    filter_grayscale: '0',
    filter_sepia: '0',
    hover_filter_blur: '',
    hover_filter_brightness: '',
    hover_filter_contrast: '',
    hover_filter_saturate: '',
    hover_filter_grayscale: '',
    hover_filter_sepia: '',
    hover_animation: 'none',
    lightbox: false,
    // ── SpotlightFX (alone di luce sul cursore — tema 43) ──
    // Default OFF: le Immagini esistenti restano invariate (additivo).
    spotlight_enabled: false,
    spotlight_mode: 'mask',
    spotlight_radius: 260,
    spotlight_intensity: 80,
    spotlight_falloff: 55,
    spotlight_tint: '',
    // ── WaterDisplacement (filtro acqua SVG feTurbulence+feDisplacementMap — tema 68) ──
    // Default OFF: le Immagini esistenti restano invariate (additivo).
    water_enabled: false,
    water_target: 'image',
    water_base_freq_x: 0.012,
    water_base_freq_y: 0.02,
    water_octaves: 2,
    water_displace_scale: 12,
    water_ripple_scale: 34,
    water_anim_speed: 22,
    shadow: 'none',
    border_radius: '0',
    hover_border_radius: '',
    hover_radius_duration: '400',
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
    ...textEffectsDefaults,
    text_effect_target: 'caption',
  },

  // ─── CONTENUTO ─────────────────────────────────────────────
  fields: [
    { key: 'image_url', label: t('Immagine'), type: 'image' },
    { key: 'media_bg', label: t('Sfondo / media (se senza immagine — ogni tipo)'), type: 'background', showParallax: false,
      description: t('Usato quando il campo Immagine è vuoto: colore, gradiente, pattern, video o galleria. Vuoto = placeholder a righe.') },
    { key: 'media_label', label: t('Etichetta placeholder'), type: 'text',
      description: t('Testo mostrato sul placeholder a righe quando non c\'è né immagine né sfondo.') },
    { key: 'alt_text', label: t('Testo alternativo'), type: 'text', aiGenerate: 'alt' },
    { key: 'caption', label: t('Didascalia'), type: 'text' },
    { key: 'link_url', label: t('URL link'), type: 'link' },
    { key: 'link_target', label: t('Apri in'), type: 'select', options: [
      { value: '_self', label: t('Stessa finestra') },
      { value: '_blank', label: t('Nuova scheda') },
    ]},

    { type: 'separator', label: t('Sostituzione al passaggio del mouse') },
    { key: 'hover_image', label: t('Immagine al passaggio (opzionale)'), type: 'image' },
    { key: 'hover_video', label: t('Video al passaggio (opzionale)'), type: 'media', accept: 'video' },
  ],

  // ─── STILE ─────────────────────────────────────────────────
  styleFields: [
    { type: 'separator', label: t('Preset stilistico') },
    { key: 'preset', label: t('Stile'), type: 'select', options: [
      { value: 'modern-clean',    label: t('Modern Clean') },
      { value: 'minimal-frame',   label: t('Minimal Frame') },
      { value: 'magazine-bold',   label: t('Magazine Bold') },
      { value: 'cinema-wide',     label: t('Cinema Wide') },
      { value: 'polaroid',        label: t('Polaroid') },
      { value: 'glass-frame',     label: t('Glass Frame') },
      { value: 'neon-glow',       label: t('Neon Glow') },
      { value: 'brutalist-block', label: t('Brutalist Block') },
      { value: 'gradient-border', label: t('Gradient Border') },
      { value: 'sticker-tape',    label: t('Sticker Tape') },
      { value: 'retro-vhs',       label: t('Retro VHS') },
      { value: 'tilt-3d',         label: t('3D Tilt') },
      { value: 'custom',          label: t('Personalizzato') },
    ]},
    { key: 'typography_preset', label: t('Stile tipografico'), type: 'select', optionsSource: 'globalTypography' },

    { type: 'separator', label: t('Dimensioni') },
    { key: 'image_width', label: t('Larghezza'), type: 'text', responsive: true,
      placeholder: t('es. 100%, 320px, 50vw') },
    { key: 'height', label: t('Altezza'), type: 'text', responsive: true,
      placeholder: t('es. 300px, auto, 50vh') },
    { key: 'max_width', label: t('Larghezza massima'), type: 'text', responsive: true,
      placeholder: t('es. 600px, none') },
    { key: 'aspect_ratio', label: t('Proporzioni (Aspect Ratio)'), type: 'select', responsive: true, options: [
      { value: 'auto',  label: t('Auto (segui altezza)') },
      { value: '1/1',   label: t('1:1 (Quadrato)') },
      { value: '4/3',   label: t('4:3 (TV classico)') },
      { value: '3/2',   label: t('3:2 (Foto)') },
      { value: '16/9',  label: t('16:9 (Widescreen)') },
      { value: '21/9',  label: t('21:9 (Cinema)') },
      { value: '9/16',  label: t('9:16 (Verticale)') },
      { value: '2/3',   label: t('2:3 (Foto verticale)') },
      { value: 'custom', label: t('Personalizzato') },
    ]},
    { key: 'aspect_ratio_custom', label: t('Proporzioni personalizzate'), type: 'text',
      placeholder: t('es. 5/4, 1.618'),
      condition: { field: 'aspect_ratio', op: 'eq', value: 'custom' } },
    { key: 'object_fit', label: t('Adattamento'), type: 'select', options: [
      { value: 'cover',      label: t('Riempi (cover)') },
      { value: 'contain',    label: t('Contieni') },
      { value: 'fill',       label: t('Riempi (deforma)') },
      { value: 'none',       label: t('Originale') },
      { value: 'scale-down', label: t('Riduci se necessario') },
    ]},
    // Punto focale grafico (FieldObjectPosition): sostituisce il select a 9 voci.
    // Emette la STESSA stringa CSS object-position (keyword in "Aggancia", '% %' in
    // "Libero") → chiave e formato salvati INVARIATI, nessuna migrazione. Le `options`
    // restano come fallback documentale/legacy.
    { key: 'object_position', label: t('Posizione contenuto'), type: 'object-position', options: [
      { value: 'left top',      label: t('↖ Alto sinistra') },
      { value: 'center top',    label: t('↑ Alto centro') },
      { value: 'right top',     label: t('↗ Alto destra') },
      { value: 'left center',   label: t('← Centro sinistra') },
      { value: 'center center', label: t('• Centro') },
      { value: 'right center',  label: t('→ Centro destra') },
      { value: 'left bottom',   label: t('↙ Basso sinistra') },
      { value: 'center bottom', label: t('↓ Basso centro') },
      { value: 'right bottom',  label: t('↘ Basso destra') },
    ]},
    { key: 'image_alignment', label: t('Allineamento orizzontale'), type: 'select', responsive: true, options: [
      { value: 'left',   label: t('Sinistra') },
      { value: 'center', label: t('Centro') },
      { value: 'right',  label: t('Destra') },
    ]},
    { key: 'align_in_column', label: t('Posizione verticale nella colonna'), type: 'select', options: [
      { value: '',       label: t('Predefinita (flusso naturale)') },
      { value: 'top',    label: t('Ancora in alto') },
      { value: 'center', label: t('Centra verticalmente') },
      { value: 'bottom', label: t('Ancora in basso (utile nei loop)') },
    ], description: t('Allinea l\'immagine a una posizione fissa della colonna, indipendentemente dall\'altezza del contenuto sopra/sotto. Tipico per card uniformi nei loop.') },

    { type: 'separator', label: t('Forma') },
    withHover(
      { key: 'border_radius', label: t('Border Radius'), type: 'border-radius' },
      { hoverKey: 'hover_border_radius', hoverDurationKey: 'hover_radius_duration' }
    ),

    ...textEffectsFields([ { value: 'caption', label: t('Solo Didascalia') } ]),

    { type: 'separator', label: t('Filtri CSS') },
    withHover({ key: 'filter_blur',       label: t('Sfocatura (px)'),       type: 'range', min: 0, max: 20,  step: 1 }, { hoverKey: 'hover_filter_blur' }),
    withHover({ key: 'filter_brightness', label: t('Luminosità (%)'),       type: 'range', min: 0, max: 200, step: 5 }, { hoverKey: 'hover_filter_brightness' }),
    withHover({ key: 'filter_contrast',   label: t('Contrasto (%)'),        type: 'range', min: 0, max: 200, step: 5 }, { hoverKey: 'hover_filter_contrast' }),
    withHover({ key: 'filter_saturate',   label: t('Saturazione (%)'),      type: 'range', min: 0, max: 200, step: 5 }, { hoverKey: 'hover_filter_saturate' }),
    withHover({ key: 'filter_grayscale',  label: t('Scala di grigi (%)'),   type: 'range', min: 0, max: 100, step: 5 }, { hoverKey: 'hover_filter_grayscale' }),
    withHover({ key: 'filter_sepia',      label: t('Seppia (%)'),           type: 'range', min: 0, max: 100, step: 5 }, { hoverKey: 'hover_filter_sepia' }),

    { type: 'separator', label: t('Animazione hover') },
    { key: 'hover_animation', label: t('Animazione hover'), type: 'select', options: [
      { value: 'none', label: t('Nessuna') },
      { value: 'zoom-in', label: t('Zoom in') },
      { value: 'zoom-out', label: t('Zoom out') },
      { value: 'slide-up', label: t('Scorrimento su') },
      { value: 'rotate-cw', label: t('Rotazione oraria') },
      { value: 'rotate-ccw', label: t('Rotazione antioraria') },
      { value: 'blur-in', label: t('Sfocatura → nitido') },
    ]},
    { key: 'lightbox', label: t('Lightbox al click'), type: 'toggle' },

    { type: 'separator', label: t('SpotlightFX (luce sul cursore)') },
    { key: 'spotlight_enabled', label: t('Attiva alone di luce'), type: 'toggle',
      description: t('Una luce radiale segue il cursore sopra l\'immagine. Ideale su foto scure. Disattivata su touch; statica con riduzione movimento.') },
    { key: 'spotlight_mode', label: t('Modalità'), type: 'select', options: [
      { value: 'mask',    label: t('Maschera (scurisce attorno)') },
      { value: 'lighten', label: t('Luce (schiarisce al centro)') },
    ], condition: { field: 'spotlight_enabled', op: 'eq', value: true } },
    { key: 'spotlight_radius', label: t('Raggio (px)'), type: 'range', min: 80, max: 600, step: 10, responsive: true,
      condition: { field: 'spotlight_enabled', op: 'eq', value: true } },
    { key: 'spotlight_intensity', label: t('Intensità (%)'), type: 'range', min: 0, max: 100, step: 5,
      condition: { field: 'spotlight_enabled', op: 'eq', value: true } },
    { key: 'spotlight_falloff', label: t('Sfumatura (%)'), type: 'range', min: 0, max: 100, step: 5,
      description: t('Quanto è morbido il bordo dell\'alone: 0 = netto, 100 = molto graduale.'),
      condition: { field: 'spotlight_enabled', op: 'eq', value: true } },
    { key: 'spotlight_tint', label: t('Tinta luce'), type: 'color',
      description: t('Colore della luce in modalità "Luce". Vuoto = bianco caldo.'),
      condition: { field: 'spotlight_enabled', value: ['lighten'] } },

    { type: 'separator', label: t('WaterDisplacement (filtro acqua)') },
    { key: 'water_enabled', label: t('Attiva filtro acqua'), type: 'toggle',
      description: t('Distorce l\'immagine come acqua (turbolenza SVG animata). Al passaggio del cursore l\'acqua si increspa e poi si rilassa. Disattivata su touch; con riduzione movimento il filtro resta statico e leggero.') },
    { key: 'water_target', label: t('Applica a'), type: 'select', options: [
      { value: 'image',      label: t('Solo immagine') },
      { value: 'section-bg', label: t('Sfondo della sezione') },
    ], description: t('"Sfondo della sezione" applica il filtro alla sezione contenitore (utile per hero a tutta pagina).'),
      condition: { field: 'water_enabled', op: 'eq', value: true } },
    { key: 'water_base_freq_x', label: t('Frequenza onda X'), type: 'range', min: 0.002, max: 0.06, step: 0.002,
      description: t('Più alto = increspatura più fitta in orizzontale.'),
      condition: { field: 'water_enabled', op: 'eq', value: true } },
    { key: 'water_base_freq_y', label: t('Frequenza onda Y'), type: 'range', min: 0.002, max: 0.06, step: 0.002,
      description: t('Più alto = increspatura più fitta in verticale.'),
      condition: { field: 'water_enabled', op: 'eq', value: true } },
    { key: 'water_octaves', label: t('Dettaglio (octaves)'), type: 'range', min: 1, max: 4, step: 1,
      condition: { field: 'water_enabled', op: 'eq', value: true } },
    { key: 'water_displace_scale', label: t('Distorsione a riposo'), type: 'range', min: 0, max: 60, step: 1,
      condition: { field: 'water_enabled', op: 'eq', value: true } },
    { key: 'water_ripple_scale', label: t('Distorsione al cursore'), type: 'range', min: 0, max: 120, step: 1,
      description: t('Ampiezza dell\'increspatura quando il cursore passa sopra. Deve essere ≥ "Distorsione a riposo".'),
      condition: { field: 'water_enabled', op: 'eq', value: true } },
    { key: 'water_anim_speed', label: t('Durata ciclo onda (sec)'), type: 'range', min: 6, max: 60, step: 1,
      condition: { field: 'water_enabled', op: 'eq', value: true } },

    ...shadowField,
    ...borderFields(),
  ],
};
