import { textEffectsFields, textEffectsDefaults } from './_shared';
import { shadowField } from './_shared.js';

export default {
  type: 'linkinbio',
  name: 'Link in Bio',
  icon: 'dashicons-smartphone',
  category: 'marketing',
  defaults: {
    items: [
      { id: 'lib-1', title: 'Sito web',    url: 'https://example.com', icon: 'globe',     image_url: '', style: 'filled' },
      { id: 'lib-2', title: 'Portfolio',    url: 'https://example.com', icon: 'briefcase', image_url: '', style: 'filled' },
      { id: 'lib-3', title: 'Instagram',    url: 'https://instagram.com', icon: 'instagram', image_url: '', style: 'filled' },
      { id: 'lib-4', title: 'Contattami',   url: 'mailto:info@example.com', icon: 'mail', image_url: '', style: 'outline' },
    ],
    profile_image: '',
    profile_name: 'Il tuo nome',
    profile_bio: 'Una breve descrizione qui',
    max_width: '420',
    link_color: '',
    link_bg: '',
    link_hover_bg: '',
    link_border_radius: '12',
    tile_padding: { top: 14, right: 14, bottom: 14, left: 14 },
    gap: '12',
    text_align: 'center',
    profile_name_color: '',
    bio_color: '',
    background_color: '',
    background_gradient: '',
    show_social_icons: false,
    shadow: 'none',
    ...textEffectsDefaults,
  },
  fields: [
    { key: 'items', label: 'Link', type: 'content-items',
      itemFields: [
        { key: 'title', label: 'Titolo', type: 'text' },
        { key: 'url', label: 'URL', type: 'text' },
        { key: 'icon', label: 'Icona (nome)', type: 'text', placeholder: 'globe, mail, instagram...' },
        { key: 'image_url', label: 'Immagine icona', type: 'image' },
        { key: 'style', label: 'Stile', type: 'select', options: [
          { value: 'filled', label: 'Pieno' },
          { value: 'outline', label: 'Contorno' },
          { value: 'minimal', label: 'Minimale' },
        ]},
      ],
    },
    { type: 'separator', label: 'Profilo' },
    { key: 'profile_image', label: 'Foto profilo', type: 'image' },
    { key: 'profile_name', label: 'Nome', type: 'text' },
    { key: 'profile_bio', label: 'Bio', type: 'text' },
    { key: 'profile_name_color', label: 'Colore nome', type: 'color' },
    { key: 'bio_color', label: 'Colore bio', type: 'color' },
    { type: 'separator', label: 'Layout' },
    { key: 'max_width', label: 'Larghezza max (px)', type: 'range', min: 300, max: 600, step: 10 },
    { key: 'text_align', label: 'Allineamento', type: 'select', options: [
      { value: 'left', label: 'Sinistra' },
      { value: 'center', label: 'Centro' },
      { value: 'right', label: 'Destra' },
    ]},
    { key: 'gap', label: 'Gap tra link (px)', type: 'range', min: 4, max: 24, step: 2 },
    { type: 'separator', label: 'Stile bottoni' },
    { key: 'link_color', label: 'Colore testo link', type: 'color' },
    { key: 'link_bg', label: 'Sfondo link', type: 'color' },
    { key: 'link_hover_bg', label: 'Sfondo hover', type: 'color' },
    { key: 'link_border_radius', label: 'Arrotondamento (px)', type: 'border-radius' },
    { key: 'link_border_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius' },
    { key: 'tile_padding', label: 'Padding (px)', type: 'spacing', max: 24 },
    { type: 'separator', label: 'Sfondo' },
    { key: 'background_color', label: 'Colore sfondo', type: 'color' },
    { key: 'background_gradient', label: 'Gradiente CSS', type: 'text', placeholder: 'linear-gradient(135deg, #667eea, #764ba2)' },
    { key: 'show_social_icons', label: 'Mostra icone social', type: 'toggle' },
    ...shadowField,
    ...textEffectsFields([ { value: 'title', label: 'Solo Titolo' } ]),
  ],
};
