import { textEffectsFields, textEffectsDefaults } from './_shared';
import { shadowField } from './_shared.js';

export default {
  type: 'list',
  name: 'Lista',
  icon: 'dashicons-editor-ul',
  category: 'text',
  defaults: {
    items: [
      { text: 'Funzionalità uno', icon: 'check' },
      { text: 'Funzionalità due', icon: 'check' },
      { text: 'Funzionalità tre', icon: 'check' },
    ],
    icon_default: 'check',
    icon_color: '',
    text_color: '',
    spacing: '12',
    icon_size: '18',
    icon_gap: '10',
    tile_padding: { top: 16, right: 16, bottom: 16, left: 16 },
    shadow: 'none',
    ...textEffectsDefaults,
  },
  fields: [
    { key: 'items', label: 'Elementi', type: 'content-items',
      itemFields: [
        { key: 'text', label: 'Testo', type: 'text' },
        { key: 'link', label: 'Link', type: 'text', placeholder: 'https://...' },
        { key: 'icon', label: 'Icona', type: 'select', options: [
          { value: 'check', label: '✓ Spunta' },
          { value: 'arrow', label: '→ Freccia' },
          { value: 'star', label: '★ Stella' },
          { value: 'dot', label: '● Punto' },
          { value: 'number', label: '1. Numero' },
          { value: 'x', label: '✕ Croce' },
          { value: 'heart', label: '♥ Cuore' },
          { value: 'bolt', label: '⚡ Fulmine' },
          { value: 'info', label: 'ℹ Info' },
          { value: 'warning', label: '⚠ Attenzione' },
        ]},
      ],
      newItemDefaults: { text: 'Nuovo elemento', icon: '' },
    },
    { key: 'icon_default', label: 'Icona predefinita', type: 'select', description: 'Per elementi senza icona', options: [
      { value: 'check', label: '✓ Spunta' },
      { value: 'arrow', label: '→ Freccia' },
      { value: 'star', label: '★ Stella' },
      { value: 'dot', label: '● Punto' },
      { value: 'number', label: '1. Numero' },
      { value: 'x', label: '✕ Croce' },
      { value: 'heart', label: '♥ Cuore' },
      { value: 'bolt', label: '⚡ Fulmine' },
      { value: 'info', label: 'ℹ Info' },
      { value: 'warning', label: '⚠ Attenzione' },
    ]},
    { key: 'icon_color', label: 'Colore icona', type: 'color' },
    { key: 'text_color', label: 'Colore testo', type: 'color' },
    { key: 'spacing', label: 'Spaziatura (px)', type: 'range', min: 4, max: 32, step: 2 },
    { key: 'icon_size', label: 'Dim. icona (px)', type: 'range', min: 14, max: 32, step: 2 },
    { key: 'icon_gap', label: 'Spazio icona-testo (px)', type: 'range', min: 0, max: 32, step: 2 },
    { key: 'tile_padding', label: 'Padding (px)', type: 'spacing', max: 48 },
    ...shadowField,
    ...textEffectsFields([ { value: 'text', label: 'Solo Testo' } ]),
  ],
};
