import { shadowField, borderFields, borderDefault, borderHoverDefault, borderEffectDefaults } from './_shared.js';

// Map — mappa Google con marker.
// D1 (text effects) N/A: i testi popup vengono dai post WP (CMS dynamic), non da fields del config.
// D2 (filter sull'immagine) N/A: marker_image è una piccola icona (16-32px), filtri non hanno senso UX.
export default {
  type: 'map',
  name: 'Mappa Pro',
  icon: 'dashicons-location',
  category: 'media',
  defaults: {
    mode: 'single',
    // Single mode
    address: '',
    latitude: '41.9028',
    longitude: '12.4964',
    zoom: '13',
    tile_layer: 'standard',
    marker: true,
    marker_popup: '',
    marker_color: '#e74c3c',
    marker_type: 'pin',
    marker_image: '',
    marker_size: '36',
    border_radius: '0',
    // Locations mode
    loc_post_type: 'location',
    loc_osm_field: 'location_map',
    loc_taxonomy: '',
    loc_show_filters: false,
    loc_filter_style: 'pills',
    loc_filter_align: 'left',
    loc_cluster: true,
    loc_fit_bounds: true,
    loc_default_zoom: '13',
    loc_default_center: '41.9028, 12.4964',
    loc_popup_show_image: true,
    loc_popup_show_excerpt: true,
    loc_popup_show_link: true,
    loc_max_locations: '100',
    loc_tile_layer: 'osm',
    // Services mode
    svc_booking_mode: 'accommodation',
    svc_show_altitude_filter: true,
    svc_altitude_ranges: '0-1000,1000-1500,1500-2000,2000-9999',
    svc_show_locality_filter: true,
    svc_show_guests_filter: true,
    svc_guests_ranges: '1-2,3-5,6-8,9-99',
    svc_show_price_filter: true,
    svc_price_ranges: '0-100,100-150,150-200,200-9999',
    svc_show_bedrooms_filter: true,
    svc_show_amenities_filter: true,
    svc_amenities_list: 'wifi,fireplace,sauna,hottub,pets,ski,bbq,garden',
    svc_filter_style: 'default',
    svc_filter_position: 'top',
    svc_tile_layer: 'positron',
    svc_default_center: '46.07, 11.12',
    svc_default_zoom: '10',
    svc_fit_bounds: true,
    svc_cluster: true,
    svc_popup_show_image: true,
    svc_popup_show_excerpt: true,
    svc_popup_show_price: true,
    svc_popup_show_altitude: true,
    svc_popup_show_specs: true,
    svc_popup_show_amenities: false,
    svc_popup_show_gallery: false,
    svc_popup_show_valley: true,
    svc_popup_max_width: '280',
    svc_popup_img_height: '180',
    svc_popup_btn_text: 'Scopri e Prenota',
    svc_popup_btn_color: '',
    svc_popup_bg: '',
    svc_popup_color: '',
    svc_popup_radius: '8',
    // Shared split-view layout (locations + services)
    map_position: 'left',
    map_width: '',
    filter_columns: '2',
    filter_position: '',
    filter_width: '45',
    fullscreen_btn: true,
    view_mode: 'list',
    grid_columns: '2',
    sort_default: 'default',
    results_per_page: '10',
    card_max_height: '0',
    card_border_radius: '8',
    show_location_search: true,
    show_radius: false,
    radius_default: '5',
    marker_shape: 'pin',
    emit_schema: true,
    btn_text: 'Ricerca',
    btn_bg: '#2563EB',
    btn_color: '#FFFFFF',
    // Shared
    height: '400',
    shadow: 'none',
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
  },
  fields: [
    {
      key: 'mode',
      label: 'Modalità',
      type: 'select',
      options: [
        { value: 'single', label: 'Indirizzo singolo' },
        { value: 'dynamic_service', label: 'Servizio corrente (dinamico)' },
        { value: 'locations', label: 'Sedi (CPT)' },
        { value: 'services', label: 'Servizi / Baite (Olo Booking)' },
      ],
    },

    // ── Campi modalità singola ──
    { key: 'address', label: 'Cerca indirizzo', type: 'geocode', targetLat: 'latitude', targetLng: 'longitude', targetZoom: 'zoom', condition: { field: 'mode', value: 'single' } },
    { key: 'latitude', label: 'Latitudine', type: 'text', condition: { field: 'mode', value: 'single' } },
    { key: 'longitude', label: 'Longitudine', type: 'text', condition: { field: 'mode', value: 'single' } },
    { key: 'zoom', label: 'Zoom', type: 'range', min: 1, max: 19, step: 1, condition: { field: 'mode', value: 'single' } },

    { type: 'separator', label: 'Marker', condition: { field: 'mode', value: 'single' } },
    { key: 'marker', label: 'Mostra marker', type: 'toggle', condition: { field: 'mode', value: 'single' } },
    { key: 'marker_popup', label: 'Testo popup marker', type: 'text', condition: { field: 'mode', value: 'single' } },
    { key: 'marker_type', label: 'Tipo marker', type: 'select', options: [
      { value: 'pin', label: 'Pin classico' },
      { value: 'drop', label: 'Goccia' },
      { value: 'circle', label: 'Cerchio' },
      { value: 'square', label: 'Quadrato' },
      { value: 'diamond', label: 'Diamante' },
      { value: 'star', label: 'Stella' },
      { value: 'flag', label: 'Bandiera' },
      { value: 'flag-wave', label: 'Bandiera animata' },
      { value: 'heart', label: 'Cuore' },
      { value: 'image', label: 'Immagine personalizzata' },
    ], condition: { field: 'mode', value: 'single' } },
    { key: 'marker_color', label: 'Colore marker', type: 'color', condition: { field: 'mode', value: 'single' } },
    { key: 'marker_size', label: 'Dimensione marker (px)', type: 'range', min: 20, max: 64, step: 2, condition: { field: 'mode', value: 'single' } },
    { key: 'marker_image', label: 'Immagine marker', type: 'image', condition: { field: 'marker_type', value: 'image' } },

    { type: 'separator', label: 'Stile mappa', condition: { field: 'mode', value: 'single' } },
    { key: 'tile_layer', label: 'Stile mappa', type: 'select', condition: { field: 'mode', value: 'single' }, options: [
      { value: 'standard', label: 'Standard' },
      { value: 'hot', label: 'Humanitarian' },
      { value: 'positron', label: 'Positron (chiaro)' },
      { value: 'voyager', label: 'Voyager (colorato)' },
      { value: 'dark', label: 'Dark Matter' },
      { value: 'satellite', label: 'Satellite' },
      { value: 'topo', label: 'Topografica' },
      { value: 'esri_street', label: 'Esri Street' },
      { value: 'gray', label: 'Grigio minimal' },
      { value: 'opentopomap', label: 'OpenTopoMap' },
    ]},

    // ── Campi modalità dynamic_service ──
    { key: 'zoom', label: 'Zoom', type: 'range', min: 1, max: 19, step: 1, condition: { field: 'mode', value: 'dynamic_service' } },

    // ── Campi modalità sedi ──
    { type: 'separator', label: 'Sorgente dati', condition: { field: 'mode', value: 'locations' } },

    { key: 'loc_post_type', label: 'Post Type (slug)', type: 'text', condition: { field: 'mode', value: 'locations' } },
    { key: 'loc_osm_field', label: 'Nome campo ACF OSM', type: 'text', condition: { field: 'mode', value: 'locations' } },
    { key: 'loc_taxonomy', label: 'Tassonomia (slug)', type: 'text', condition: { field: 'mode', value: 'locations' } },
    { key: 'loc_max_locations', label: 'Max sedi', type: 'range', min: 1, max: 500, step: 1, condition: { field: 'mode', value: 'locations' } },

    { type: 'separator', label: 'Stile mappa', condition: { field: 'mode', value: 'locations' } },

    { key: 'loc_tile_layer', label: 'Stile mappa', type: 'select', options: [
      { value: 'osm', label: 'Standard' },
      { value: 'hot', label: 'Humanitarian' },
      { value: 'positron', label: 'Positron (chiaro)' },
      { value: 'voyager', label: 'Voyager (colorato)' },
      { value: 'dark', label: 'Dark Matter' },
      { value: 'satellite', label: 'Satellite' },
      { value: 'topo', label: 'Topografica' },
      { value: 'esri_street', label: 'Esri Street' },
      { value: 'gray', label: 'Grigio minimal' },
      { value: 'opentopomap', label: 'OpenTopoMap' },
    ], condition: { field: 'mode', value: 'locations' } },
    { key: 'loc_default_center', label: 'Centro predefinito (lat, lng)', type: 'text', condition: { field: 'mode', value: 'locations' } },
    { key: 'loc_default_zoom', label: 'Zoom predefinito', type: 'range', min: 1, max: 19, step: 1, condition: { field: 'mode', value: 'locations' } },
    { key: 'loc_fit_bounds', label: 'Adatta ai marker', type: 'toggle', condition: { field: 'mode', value: 'locations' } },
    { key: 'loc_cluster', label: 'Raggruppa marker', type: 'toggle', condition: { field: 'mode', value: 'locations' } },

    { type: 'separator', label: 'Filtri', condition: { field: 'mode', value: 'locations' } },

    { key: 'loc_show_filters', label: 'Mostra filtri tassonomia', type: 'toggle', condition: { field: 'mode', value: 'locations' } },
    // Nota: loc_filter_style e loc_filter_align (legacy) rimossi.
    // La disposizione dei filtri è determinata dal "Layout split-view" più in basso.

    { type: 'separator', label: 'Popup', condition: { field: 'mode', value: 'locations' } },

    { key: 'loc_popup_show_image', label: 'Mostra immagine', type: 'toggle', condition: { field: 'mode', value: 'locations' } },
    { key: 'loc_popup_show_excerpt', label: 'Mostra riassunto', type: 'toggle', condition: { field: 'mode', value: 'locations' } },
    { key: 'loc_popup_show_link', label: 'Mostra link', type: 'toggle', condition: { field: 'mode', value: 'locations' } },

    // ── Campi modalità servizi ──
    { type: 'separator', label: 'Tipo servizio', condition: { field: 'mode', value: 'services' } },

    { key: 'svc_booking_mode', label: 'Tipo servizio', type: 'select', options: [
      { value: 'accommodation', label: 'Alloggi (accommodation)' },
      { value: 'timeslot', label: 'Fasce orarie (timeslot)' },
      { value: '', label: 'Tutti i tipi' },
    ], condition: { field: 'mode', value: 'services' } },

    { type: 'separator', label: 'Stile mappa', condition: { field: 'mode', value: 'services' } },

    { key: 'svc_tile_layer', label: 'Stile mappa', type: 'select', options: [
      { value: 'osm', label: 'Standard' },
      { value: 'hot', label: 'Humanitarian' },
      { value: 'positron', label: 'Positron (chiaro)' },
      { value: 'voyager', label: 'Voyager (colorato)' },
      { value: 'dark', label: 'Dark Matter' },
      { value: 'satellite', label: 'Satellite' },
      { value: 'topo', label: 'Topografica' },
      { value: 'esri_street', label: 'Esri Street' },
      { value: 'gray', label: 'Grigio minimal' },
      { value: 'opentopomap', label: 'OpenTopoMap' },
    ], condition: { field: 'mode', value: 'services' } },
    { key: 'svc_default_center', label: 'Centro predefinito (lat, lng)', type: 'text', condition: { field: 'mode', value: 'services' } },
    { key: 'svc_default_zoom', label: 'Zoom predefinito', type: 'range', min: 1, max: 19, step: 1, condition: { field: 'mode', value: 'services' } },
    { key: 'svc_fit_bounds', label: 'Adatta ai marker', type: 'toggle', condition: { field: 'mode', value: 'services' } },
    { key: 'svc_cluster', label: 'Raggruppa marker', type: 'toggle', condition: { field: 'mode', value: 'services' } },

    { type: 'separator', label: 'Filtri', condition: { field: 'mode', value: 'services' } },
    // Nota: svc_filter_style e svc_filter_position (legacy) rimossi dall'UI.
    // La posizione del pannello filtri è ora controllata da "filter_position"
    // più in basso nella sezione "Layout split-view".

    { key: 'svc_show_altitude_filter', label: 'Mostra filtro altitudine', type: 'toggle', condition: { field: 'mode', value: 'services' } },
    { key: 'svc_altitude_ranges', label: 'Fasce altitudine (min-max,...)', type: 'text', condition: { field: 'mode', value: 'services' } },
    { key: 'svc_show_locality_filter', label: 'Mostra filtro localit\u00e0', type: 'toggle', condition: { field: 'mode', value: 'services' } },
    { key: 'svc_show_guests_filter', label: 'Mostra filtro ospiti', type: 'toggle', condition: { field: 'mode', value: 'services' } },
    { key: 'svc_guests_ranges', label: 'Fasce ospiti (min-max,...)', type: 'text', condition: { field: 'mode', value: 'services' } },
    { key: 'svc_show_price_filter', label: 'Mostra filtro prezzo', type: 'toggle', condition: { field: 'mode', value: 'services' } },
    { key: 'svc_price_ranges', label: 'Fasce prezzo (min-max,...)', type: 'text', condition: { field: 'mode', value: 'services' } },
    { key: 'svc_show_bedrooms_filter', label: 'Mostra filtro camere', type: 'toggle', condition: { field: 'mode', value: 'services' } },
    { key: 'svc_show_amenities_filter', label: 'Mostra filtro amenities', type: 'toggle', condition: { field: 'mode', value: 'services' } },
    { key: 'svc_amenities_list', label: 'Amenities da mostrare nel filtro', type: 'multi_pills', condition: { field: 'mode', value: 'services' }, options: [
      { value: 'wifi', label: 'WiFi', icon: 'wifi' },
      { value: 'fireplace', label: 'Camino', icon: 'fire' },
      { value: 'parking', label: 'Parcheggio', icon: 'car' },
      { value: 'kitchen', label: 'Cucina', icon: 'cup' },
      { value: 'tv', label: 'TV' },
      { value: 'bbq', label: 'BBQ', icon: 'fire' },
      { value: 'terrace', label: 'Terrazza' },
      { value: 'heating', label: 'Riscald.', icon: 'bolt' },
      { value: 'sauna', label: 'Sauna', icon: 'droplet' },
      { value: 'hottub', label: 'Idromassaggio', icon: 'droplet' },
      { value: 'ski', label: 'Sci', icon: 'snowflake' },
      { value: 'garden', label: 'Giardino', icon: 'tree' },
      { value: 'pets', label: 'Animali', icon: 'paw' },
      { value: 'washer', label: 'Lavatrice' },
      { value: 'highchair', label: 'Seggiolone' },
      { value: 'aircon', label: 'Aria Cond.', icon: 'snowflake' },
      { value: 'dishwasher', label: 'Lavastoviglie' },
      { value: 'linens', label: 'Biancheria', icon: 'bed' },
      { value: 'towels', label: 'Asciugamani' },
      { value: 'pool', label: 'Piscina', icon: 'droplet' },
      { value: 'hiking', label: 'Escursioni', icon: 'location' },
      { value: 'bikes', label: 'Biciclette' },
    ] },

    { type: 'separator', label: 'Contenuto popup', condition: { field: 'mode', value: 'services' } },

    { key: 'svc_popup_show_image', label: 'Mostra immagine', type: 'toggle', condition: { field: 'mode', value: 'services' } },
    { key: 'svc_popup_show_excerpt', label: 'Mostra descrizione', type: 'toggle', condition: { field: 'mode', value: 'services' } },
    { key: 'svc_popup_show_price', label: 'Mostra prezzo', type: 'toggle', condition: { field: 'mode', value: 'services' } },
    { key: 'svc_popup_show_altitude', label: 'Mostra altitudine', type: 'toggle', condition: { field: 'mode', value: 'services' } },
    { key: 'svc_popup_show_specs', label: 'Mostra specs (camere/bagni/ospiti)', type: 'toggle', condition: { field: 'mode', value: 'services' } },
    { key: 'svc_popup_show_valley', label: 'Mostra località/vallata', type: 'toggle', condition: { field: 'mode', value: 'services' } },
    { key: 'svc_popup_show_amenities', label: 'Mostra amenities', type: 'toggle', condition: { field: 'mode', value: 'services' } },
    { key: 'svc_popup_show_gallery', label: 'Mini gallery (4 thumb)', type: 'toggle', condition: { field: 'mode', value: 'services' } },

    { type: 'separator', label: 'Stile popup', condition: { field: 'mode', value: 'services' } },

    { key: 'svc_popup_max_width', label: 'Larghezza max (px)', type: 'range', min: 200, max: 500, step: 10, condition: { field: 'mode', value: 'services' } },
    { key: 'svc_popup_img_height', label: 'Altezza immagine (px)', type: 'range', min: 80, max: 300, step: 10, condition: { field: 'mode', value: 'services' } },
    { key: 'svc_popup_btn_text', label: 'Testo pulsante CTA', type: 'text', condition: { field: 'mode', value: 'services' } },
    { key: 'svc_popup_btn_color', label: 'Colore pulsante', type: 'color', condition: { field: 'mode', value: 'services' } },
    { key: 'svc_popup_bg', label: 'Sfondo', type: 'color', condition: { field: 'mode', value: 'services' } },
    { key: 'svc_popup_color', label: 'Colore testo', type: 'color', condition: { field: 'mode', value: 'services' } },
    { key: 'svc_popup_radius', label: 'Border radius', type: 'border-radius', condition: { field: 'mode', value: 'services' } },
    { key: 'svc_popup_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius' },

    // ══════ LAYOUT SPLIT-VIEW (locations + services) ══════
    // Il layout split-view ha mappa su un lato e pannello risultati (filtri + lista) dall'altro.
    // Queste opzioni si applicano solo alle modalità multi-marker.

    { type: 'separator', label: 'Layout split-view', condition: { field: 'mode', value: 'locations' } },
    { key: 'filter_width', label: 'Dimensione blocco filtri (% — la mappa prende il resto)', type: 'range', min: 20, max: 80, step: 1, condition: { field: 'mode', value: 'locations' } },
    { key: 'filter_position', label: 'Posizione filtri', type: 'select', options: [
      { value: 'top',    label: 'Sopra (riga in alto)' },
      { value: 'bottom', label: 'Sotto (riga in basso)' },
      { value: 'left',   label: 'Sinistra (colonna)' },
      { value: 'right',  label: 'Destra (colonna)' },
    ], condition: { field: 'mode', value: 'locations' } },
    { key: 'filter_columns', label: 'Colonne filtri', type: 'range', min: 1, max: 4, step: 1, condition: { field: 'mode', value: 'locations' } },
    { key: 'fullscreen_btn', label: 'Pulsante schermo intero', type: 'toggle', condition: { field: 'mode', value: 'locations' } },
    { key: 'show_location_search', label: 'Ricerca località (Nominatim)', type: 'toggle', condition: { field: 'mode', value: 'locations' } },
    { key: 'show_radius', label: 'Filtro raggio (km)', type: 'toggle', condition: { field: 'mode', value: 'locations' } },
    { key: 'radius_default', label: 'Raggio predefinito (km)', type: 'range', min: 1, max: 50, step: 1, condition: { field: 'show_radius', value: true } },
    { key: 'marker_shape', label: 'Forma marker', type: 'select', options: [
      { value: 'pin',     label: 'Pin classico' },
      { value: 'drop',    label: 'Goccia' },
      { value: 'circle',  label: 'Cerchio' },
      { value: 'square',  label: 'Quadrato' },
      { value: 'diamond', label: 'Diamante' },
      { value: 'star',    label: 'Stella' },
      { value: 'flag',    label: 'Bandiera' },
      { value: 'heart',   label: 'Cuore' },
    ], condition: { field: 'mode', value: 'locations' } },
    { key: 'marker_color', label: 'Colore marker/cluster', type: 'color', condition: { field: 'mode', value: 'locations' } },

    { type: 'separator', label: 'Elenco risultati', condition: { field: 'mode', value: 'locations' } },
    { key: 'view_mode', label: 'Vista predefinita', type: 'select', options: [
      { value: 'list', label: 'Lista' },
      { value: 'grid', label: 'Griglia' },
    ], condition: { field: 'mode', value: 'locations' } },
    { key: 'grid_columns', label: 'Colonne griglia', type: 'range', min: 1, max: 4, step: 1, condition: { field: 'view_mode', value: 'grid' } },
    { key: 'sort_default', label: 'Ordinamento predefinito', type: 'select', options: [
      { value: 'default',    label: 'Predefinito' },
      { value: 'title_asc',  label: 'Titolo A-Z' },
      { value: 'title_desc', label: 'Titolo Z-A' },
      { value: 'newest',     label: 'Più recenti' },
      { value: 'distance',   label: 'Distanza' },
    ], condition: { field: 'mode', value: 'locations' } },
    { key: 'results_per_page', label: 'Risultati per pagina (0 = tutti)', type: 'range', min: 0, max: 50, step: 1, condition: { field: 'mode', value: 'locations' } },
    { key: 'card_max_height', label: 'Altezza max card (px, 0 = auto)', type: 'range', min: 0, max: 400, step: 10, condition: { field: 'mode', value: 'locations' } },
    { key: 'card_border_radius', label: 'Raggio angoli card', type: 'border-radius', condition: { field: 'mode', value: 'locations' } },
    { key: 'card_border_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius', condition: { field: 'mode', value: 'locations' } },

    { type: 'separator', label: 'Pulsante ricerca', condition: { field: 'mode', value: 'locations' } },
    { key: 'btn_text',  label: 'Testo pulsante',  type: 'text',  condition: { field: 'mode', value: 'locations' } },
    { key: 'btn_bg',    label: 'Colore sfondo',   type: 'color', condition: { field: 'mode', value: 'locations' } },
    { key: 'btn_color', label: 'Colore testo',    type: 'color', condition: { field: 'mode', value: 'locations' } },

    { key: 'emit_schema', label: 'Schema.org JSON-LD (SEO)', type: 'toggle', condition: { field: 'mode', value: 'locations' } },

    // ── Stessi controlli per modalità services ──
    { type: 'separator', label: 'Layout split-view', condition: { field: 'mode', value: 'services' } },
    { key: 'filter_width', label: 'Dimensione blocco filtri (% — la mappa prende il resto)', type: 'range', min: 20, max: 80, step: 1, condition: { field: 'mode', value: 'services' } },
    { key: 'filter_position', label: 'Posizione filtri', type: 'select', options: [
      { value: 'top',    label: 'Sopra (riga in alto)' },
      { value: 'bottom', label: 'Sotto (riga in basso)' },
      { value: 'left',   label: 'Sinistra (colonna)' },
      { value: 'right',  label: 'Destra (colonna)' },
    ], condition: { field: 'mode', value: 'services' } },
    { key: 'filter_columns', label: 'Colonne filtri', type: 'range', min: 1, max: 4, step: 1, condition: { field: 'mode', value: 'services' } },
    { key: 'fullscreen_btn', label: 'Pulsante schermo intero', type: 'toggle', condition: { field: 'mode', value: 'services' } },
    { key: 'show_location_search', label: 'Ricerca località (Nominatim)', type: 'toggle', condition: { field: 'mode', value: 'services' } },
    { key: 'show_radius', label: 'Filtro raggio (km)', type: 'toggle', condition: { field: 'mode', value: 'services' } },
    { key: 'radius_default', label: 'Raggio predefinito (km)', type: 'range', min: 1, max: 50, step: 1, condition: { field: 'show_radius', value: true } },
    { key: 'marker_shape', label: 'Forma marker', type: 'select', options: [
      { value: 'pin',     label: 'Pin classico' },
      { value: 'drop',    label: 'Goccia' },
      { value: 'circle',  label: 'Cerchio' },
      { value: 'square',  label: 'Quadrato' },
      { value: 'diamond', label: 'Diamante' },
      { value: 'star',    label: 'Stella' },
      { value: 'flag',    label: 'Bandiera' },
      { value: 'heart',   label: 'Cuore' },
    ], condition: { field: 'mode', value: 'services' } },
    { key: 'marker_color', label: 'Colore marker/cluster', type: 'color', condition: { field: 'mode', value: 'services' } },

    { type: 'separator', label: 'Elenco risultati', condition: { field: 'mode', value: 'services' } },
    { key: 'view_mode', label: 'Vista predefinita', type: 'select', options: [
      { value: 'list', label: 'Lista' },
      { value: 'grid', label: 'Griglia' },
    ], condition: { field: 'mode', value: 'services' } },
    { key: 'grid_columns', label: 'Colonne griglia', type: 'range', min: 1, max: 4, step: 1, condition: { field: 'view_mode', value: 'grid' } },
    { key: 'sort_default', label: 'Ordinamento predefinito', type: 'select', options: [
      { value: 'default',    label: 'Predefinito' },
      { value: 'title_asc',  label: 'Titolo A-Z' },
      { value: 'title_desc', label: 'Titolo Z-A' },
      { value: 'newest',     label: 'Più recenti' },
      { value: 'distance',   label: 'Distanza' },
    ], condition: { field: 'mode', value: 'services' } },
    { key: 'results_per_page', label: 'Risultati per pagina (0 = tutti)', type: 'range', min: 0, max: 50, step: 1, condition: { field: 'mode', value: 'services' } },
    { key: 'card_max_height', label: 'Altezza max card (px, 0 = auto)', type: 'range', min: 0, max: 400, step: 10, condition: { field: 'mode', value: 'services' } },
    { key: 'card_border_radius', label: 'Raggio angoli card', type: 'border-radius', condition: { field: 'mode', value: 'services' } },
    { key: 'card_border_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius', condition: { field: 'mode', value: 'services' } },

    { type: 'separator', label: 'Pulsante ricerca', condition: { field: 'mode', value: 'services' } },
    { key: 'btn_text',  label: 'Testo pulsante',  type: 'text',  condition: { field: 'mode', value: 'services' } },
    { key: 'btn_bg',    label: 'Colore sfondo',   type: 'color', condition: { field: 'mode', value: 'services' } },
    { key: 'btn_color', label: 'Colore testo',    type: 'color', condition: { field: 'mode', value: 'services' } },

    { key: 'emit_schema', label: 'Schema.org JSON-LD (SEO)', type: 'toggle', condition: { field: 'mode', value: 'services' } },

    // ── Condivisi ──
    { type: 'separator', label: 'Dimensioni' },
    { key: 'height', label: 'Altezza (px)', type: 'range', min: 150, max: 800, step: 10 },
    { key: 'border_radius', label: 'Arrotondamento (px)', type: 'border-radius' },
    { key: 'border_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius' },
    ...shadowField,
    ...borderFields(),
  ],
};
