
import { borderFields, borderDefault, borderHoverDefault, borderEffectDefaults, withHover } from './_shared.js';
import { t } from '@/i18n';
import { MEGAMENU_TEMPLATES } from '../megamenuTemplates.js';

// Opzioni del selettore "Template pronti": placeholder + 40 template raggruppati
// per famiglia. La selezione NON è una chiave salvata: il valore arriva alla
// chiave sentinella `__megamenu_template__`, intercettata da BuilderInspector
// (applyMegamenuTemplate) e mai persistita — applica i settings una tantum.
const MEGAMENU_TEMPLATE_OPTIONS = [
  { value: '', label: t('— Applica un template… —') },
  ...MEGAMENU_TEMPLATES.map(tpl => ({ value: tpl.id, label: `${tpl.family} · ${tpl.name}` })),
];

/**
 * Tile Mega Menu — split CONTENUTO/STILE (regola universale Olobuild).
 *   fields[]      → menu WP, logo asset, panel templates, mega mode, social URLs, extra links,
 *                   topbar contenuti + CTA, search tile, visibilità componenti, header mode
 *   styleFields[] → preset, bg, typo, navbar aspect, bar spacing, hover effects, panel layout/typography,
 *                   CTA aspect, mobile aspect (animations, hamburger, panel)
 *   AVANZATE      → meta tecnico
 */
export default {
  type: 'megamenu',
  name: t('Mega Menu'),
  icon: 'dashicons-menu-alt3',
  category: 'navigation',

  defaults: {
    bg: { type: 'none' },
    preset: 'custom',
    typography_preset: '',
    menu_id: 0,

    logo_image: '',
    logo_width: '140',
    logo_min_height: '0',
    logo_position: 'left',
    logo_link: '',
    logo_sticky: '',
    logo_gap: '4',

    layout: 'left',
    nav_bg: '',
    nav_height: '0',
    text_color: '',
    hover_color: '',
    active_color: '',
    font_size: '15',
    font_weight: 'normal',
    text_transform: 'none',
    letter_spacing: '0',
    item_gap: '15',

    bar_width: 'full',
    bar_padding: { top: 16, right: 16, bottom: 16, left: 16 },
    bar_gap: '20',
    logo_margin_right: { top: 0, right: 0, bottom: 0, left: 0 },

    hover_effect: 'none',
    hover_effect_color: '',
    hover_effect_height: '2',
    hover_effect_padding: { top: 8, right: 8, bottom: 8, left: 8 },

    panel_templates: {},
    mega_mode: 'auto',
    panel_width: 'container',
    panel_max_width: '900',
    panel_columns: '4',
    panel_bg: '',
    panel_shadow: 'md',
    panel_radius: { tl: 8, tr: 8, br: 8, bl: 8 },
    panel_padding: { top: 32, right: 32, bottom: 32, left: 32 },
    panel_border_top: '3',
    panel_border_color: '',
    panel_animation: 'fade',
    panel_offset_top: '0',
    panel_origin: 'nav',
    panel_size: 'auto',
    panel_open_animation: 'fade',
    show_dividers: false,

    heading_color: '',
    heading_size: '14',
    heading_weight: '600',
    heading_transform: 'uppercase',
    link_color: '',
    link_hover_color: '',
    link_size: '14',
    link_spacing: '8',
    show_descriptions: false,
    desc_color: '',

    button_mode: 'none',
    btn_bg: '',
    btn_color: '',
    btn_radius: { tl: 6, tr: 6, br: 6, bl: 6 },
    btn_hover_bg: '',
    btn_padding_v: { top: 8, right: 0, bottom: 8, left: 0 },
    btn_padding_h: { top: 0, right: 20, bottom: 0, left: 20 },
    btn_margin_left: { top: 0, right: 0, bottom: 0, left: 0 },
    btn_margin_right: { top: 0, right: 0, bottom: 0, left: 0 },
    btn_border_width: '0',
    btn_border_color: '',

    search_icon: true,
    search_position: 'navbar',
    search_style: 'expand',
    search_icon_style: 'lens',
    search_tile_id: '',
    search_tile_position: 'after',

    // Predefiniti '#': le icone social compaiono come punto di partenza (link no-op
    // da sostituire con gli URL reali), niente URL fittizi/segnaposto.
    social_facebook: '#',
    social_instagram: '#',
    social_x: '#',
    social_linkedin: '#',
    social_youtube: '#',
    social_tiktok: '#',
    social_pinterest: '#',
    social_whatsapp: '#',
    social_position: 'bar-right+mobile-bottom',
    social_in_navbar: true,
    social_navbar_side: 'right',
    social_in_topbar: false,
    social_topbar_side: 'right',
    social_in_mobile: true,
    social_mobile_pos: 'bottom',
    social_size: '20',
    social_color: '',
    social_hover_color: '',
    social_style: 'plain',

    mobile_breakpoint: '1024',
    mobile_style: 'offcanvas',
    mobile_side: 'left',
    mobile_slide_direction: 'left',
    offcanvas_fullscreen: false,
    fullscreen_animation: 'fade',
    menu_items_animation: 'none',
    menu_items_stagger: '80',
    hamburger_style: 'classic',
    hamburger_size: '28',
    hamburger_color: '',
    mobile_bg: '',
    mobile_text_color: '',
    mobile_heading_color: '',
    mobile_accent_color: '',
    mob_separator_style: 'line',
    mob_toggle_style: 'chevron',
    mob_toggle_position: 'right',
    mob_toggle_size: '20',
    mob_toggle_color: '',
    mobile_font_size: '17',
    mobile_item_padding: { top: 16, right: 16, bottom: 16, left: 16 },
    mobile_logo: '',
    mobile_logo_height: '36',
    mobile_bar_logo: true,
    mobile_search: true,

    extra_link_1_label: '',
    extra_link_1_url: '',
    extra_link_2_label: '',
    extra_link_2_url: '',
    extra_link_3_label: '',
    extra_link_3_url: '',
    extra_link_4_label: '',
    extra_link_4_url: '',
    extra_link_1_blank: false,
    extra_link_2_blank: false,
    extra_link_3_blank: false,
    extra_link_4_blank: false,

    header_mode: 'overlay',
    sticky: false,
    sticky_show_on_up: false,
    sticky_bg: '',
    sticky_shadow: true,
    sticky_shrink: false,
    sticky_text_color: '',
    topbar_enabled: false,
    // Token-first: superficie scura "decisa" → ruolo dark; testo su scuro → ruolo light.
    // Hex storici mantenuti come fallback (resa identica se il token non è definito).
    topbar_bg: 'var(--olo-color-dark, #1F2937)',
    topbar_text_color: 'var(--olo-color-light, #9CA3AF)',
    topbar_link_color: '#FFFFFF',
    topbar_height: '40',
    topbar_font_size: '13',
    topbar_hide_mobile: true,
    topbar_hide_sticky: true,
    topbar_left_content: 'none',
    topbar_left_text: '',
    topbar_left_menu_id: 0,
    topbar_ticker_items: '',
    topbar_ticker_label: 'TRENDING:',
    topbar_ticker_speed: '5',
    topbar_right_social: true,
    topbar_right_search: true,
    topbar_right_cart: false,
    topbar_right_text: '',
    topbar_right_cta_label: '',
    topbar_right_cta_url: '',
    topbar_right_cta_bg: '',
    topbar_right_cta_color: 'var(--olo-color-light, #FFFFFF)',
    topbar_border_bottom: true,
    topbar_border_color: '',
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
  },

  // ─── CONTENUTO ─────────────────────────────────────────────
  fields: [
    { key: 'menu_id', label: t('Menu WordPress'), type: 'select', optionsSource: 'wpMenus' },

    { type: 'separator', label: t('Logo') },
    { key: 'logo_image', label: t('Logo desktop'), type: 'image' },
    { key: 'logo_sticky', label: t('Logo alternativo sticky'), type: 'image' },
    { key: 'logo_link', label: t('Link logo (vuoto = home)'), type: 'link' },
    { key: 'mobile_logo', label: t('Logo pannello mobile'), type: 'image' },

    { type: 'separator', label: t('Mega Panel — Sorgente') },
    { key: 'panel_templates', label: t('Template pannelli'), type: 'megapanel-map' },
    { key: 'mega_mode', label: t('Attivazione mega'), type: 'select', options: [
      { value: 'auto', label: t('Automatico (tutte con figli)') },
      { value: 'css-class', label: t('Solo classe mega-menu') },
    ]},
    { key: 'show_dividers', label: t('Divisori tra colonne'), type: 'toggle' },
    { key: 'show_descriptions', label: t('Mostra descrizioni'), type: 'toggle' },

    { type: 'separator', label: t('Voci CTA') },
    { key: 'button_mode', label: t('Modalità pulsanti'), type: 'select', options: [
      { value: 'none', label: t('Nessuno') },
      { value: 'last', label: t('Ultimo') },
      { value: 'last-2', label: t('Ultimi 2') },
      { value: 'css-class', label: t('Classe CSS olo-btn') },
    ]},

    { type: 'separator', label: t('Ricerca') },
    { key: 'search_icon', label: t('Mostra icona ricerca'), type: 'toggle' },
    { key: 'search_position', label: t('Posizione ricerca'), type: 'select', options: [
      { value: 'navbar', label: t('Navbar') },
      { value: 'topbar', label: t('Top bar') },
      { value: 'both', label: t('Entrambi') },
    ], condition: { field: 'search_icon', value: true } },
    { key: 'search_style', label: t('Comportamento ricerca'), type: 'select', options: [
      { value: 'expand', label: t('Espandi inline (default)') },
      { value: 'overlay', label: t('Overlay a tutta pagina') },
      { value: 'command', label: t('Command palette (⌘K)') },
    ], condition: { field: 'search_icon', value: true } },
    { key: 'search_tile_id', label: t('Tile ricerca (opzionale)'), type: 'select', optionsSource: 'searchTiles' },
    { key: 'search_tile_position', label: t('Posizione tile ricerca'), type: 'select',
      show: s => !!s.search_tile_id,
      options: [
        { value: 'before', label: t('Prima del menu (sinistra)') },
        { value: 'after', label: t('Dopo il menu (destra)') },
      ]},

    { type: 'separator', label: t('Social — Account') },
    { key: 'social_facebook', label: t('Facebook URL'), type: 'text' },
    { key: 'social_instagram', label: t('Instagram URL'), type: 'text' },
    { key: 'social_x', label: t('X (Twitter) URL'), type: 'text' },
    { key: 'social_linkedin', label: t('LinkedIn URL'), type: 'text' },
    { key: 'social_youtube', label: t('YouTube URL'), type: 'text' },
    { key: 'social_tiktok', label: t('TikTok URL'), type: 'text' },
    { key: 'social_pinterest', label: t('Pinterest URL'), type: 'text' },
    { key: 'social_whatsapp', label: t('WhatsApp URL'), type: 'text' },

    { type: 'separator', label: t('Social — Posizionamento') },
    { key: 'social_in_navbar', label: t('Mostra nella navbar'), type: 'toggle' },
    { key: 'social_navbar_side', label: t('Lato navbar'), type: 'select', options: [
      { value: 'right', label: t('Destra') },
      { value: 'left', label: t('Sinistra') },
    ], condition: { field: 'social_in_navbar', value: true } },
    { key: 'social_in_topbar', label: t('Mostra nella top bar'), type: 'toggle' },
    { key: 'social_topbar_side', label: t('Lato top bar'), type: 'select', options: [
      { value: 'right', label: t('Destra') },
      { value: 'left', label: t('Sinistra') },
    ], condition: { field: 'social_in_topbar', value: true } },
    { key: 'social_in_mobile', label: t('Mostra nel menu mobile'), type: 'toggle' },
    { key: 'social_mobile_pos', label: t('Posizione mobile'), type: 'select', options: [
      { value: 'bottom', label: t('In basso') },
      { value: 'top', label: t('In alto') },
    ], condition: { field: 'social_in_mobile', value: true } },

    { type: 'separator', label: t('Link extra') },
    { key: 'extra_link_1_label', label: t('Voce 1 — Testo'), type: 'text' },
    { key: 'extra_link_1_url', label: t('Voce 1 — URL'), type: 'link' },
    { key: 'extra_link_1_blank', label: t('Voce 1 — Apri in nuova finestra'), type: 'toggle' },
    { key: 'extra_link_2_label', label: t('Voce 2 — Testo'), type: 'text' },
    { key: 'extra_link_2_url', label: t('Voce 2 — URL'), type: 'link' },
    { key: 'extra_link_2_blank', label: t('Voce 2 — Apri in nuova finestra'), type: 'toggle' },
    { key: 'extra_link_3_label', label: t('Voce 3 — Testo'), type: 'text' },
    { key: 'extra_link_3_url', label: t('Voce 3 — URL'), type: 'link' },
    { key: 'extra_link_3_blank', label: t('Voce 3 — Apri in nuova finestra'), type: 'toggle' },
    { key: 'extra_link_4_label', label: t('Voce 4 — Testo'), type: 'text' },
    { key: 'extra_link_4_url', label: t('Voce 4 — URL'), type: 'link' },
    { key: 'extra_link_4_blank', label: t('Voce 4 — Apri in nuova finestra'), type: 'toggle' },

    { type: 'separator', label: t('Mobile — Bar') },
    { key: 'mobile_bar_logo', label: t('Logo nella barra mobile'), type: 'toggle' },
    { key: 'mobile_search', label: t('Icona ricerca mobile'), type: 'toggle' },

    { type: 'separator', label: t('Header') },
    { key: 'header_mode', label: t('Modalità header'), type: 'select', options: [
      { value: 'overlay', label: t('Sovrapposto (sopra la pagina)') },
      { value: 'classic', label: t('In linea (pagina inizia dopo)') },
    ]},
    { key: 'sticky', label: t('Header sticky'), type: 'toggle' },

    { type: 'separator', label: t('Top Bar — Attivazione') },
    { key: 'topbar_enabled', label: t('Mostra top bar'), type: 'toggle' },
    { key: 'topbar_hide_mobile', label: t('Nascondi su mobile'), type: 'toggle',
      condition: { field: 'topbar_enabled', value: true } },
    { key: 'topbar_hide_sticky', label: t('Nascondi in sticky'), type: 'toggle',
      condition: { field: 'topbar_enabled', value: true } },

    { type: 'separator', label: t('Top Bar — Sinistra') },
    { key: 'topbar_left_content', label: t('Contenuto sinistra'), type: 'select', options: [
      { value: 'none', label: t('Nessuno') },
      { value: 'text', label: t('Testo personalizzato') },
      { value: 'ticker', label: t('Newsticker scorrevole') },
      { value: 'hamburger', label: t('Menu hamburger') },
    ], condition: { field: 'topbar_enabled', value: true } },
    { key: 'topbar_left_text', label: t('Testo'), type: 'text', placeholder: t('es. Chiama: 0461 123456'),
      condition: { field: 'topbar_left_content', value: 'text' } },
    { key: 'topbar_ticker_label', label: t('Etichetta ticker'), type: 'text', placeholder: t('TRENDING:'),
      condition: { field: 'topbar_left_content', value: 'ticker' } },
    { key: 'topbar_ticker_items', label: t('Elementi ticker (uno per riga)'), type: 'textarea',
      condition: { field: 'topbar_left_content', value: 'ticker' } },
    { key: 'topbar_left_menu_id', label: t('Menu hamburger'), type: 'select', optionsSource: 'wpMenus',
      condition: { field: 'topbar_left_content', value: 'hamburger' } },

    { type: 'separator', label: t('Top Bar — Destra') },
    { key: 'topbar_right_social', label: t('Icone social'), type: 'toggle',
      condition: { field: 'topbar_enabled', value: true } },
    { key: 'topbar_right_search', label: t('Icona ricerca'), type: 'toggle',
      condition: { field: 'topbar_enabled', value: true } },
    { key: 'topbar_right_cart', label: t('Carrello WooCommerce'), type: 'toggle',
      condition: { field: 'topbar_enabled', value: true } },
    { key: 'topbar_right_text', label: t('Testo destro'), type: 'text', placeholder: t('es. Spedizione gratuita!'),
      condition: { field: 'topbar_enabled', value: true } },
    { key: 'topbar_right_cta_label', label: t('Pulsante CTA — testo'), type: 'text', placeholder: t('es. Prenota ora'),
      condition: { field: 'topbar_enabled', value: true } },
    { key: 'topbar_right_cta_url', label: t('Pulsante CTA — URL'), type: 'link', placeholder: t('https://...'),
      condition: { field: 'topbar_enabled', value: true } },

    { type: 'separator', label: t('Mobile — Breakpoint & Stile') },
    { key: 'mobile_breakpoint', label: t('Breakpoint'), type: 'select', options: [
      { value: '768', label: t('768px (Tablet)') },
      { value: '1024', label: t('1024px (Desktop)') },
      { value: '1200', label: t('1200px (Desktop largo)') },
    ]},
    { key: 'mobile_style', label: t('Stile menu mobile'), type: 'select', options: [
      { value: 'offcanvas', label: t('Off-canvas (pannello laterale)') },
      { value: 'dropdown', label: t('Dropdown (scende dalla barra)') },
      { value: 'fullscreen', label: t('Fullscreen (overlay completo)') },
    ]},
  ],

  // ─── STILE ─────────────────────────────────────────────────
  styleFields: [
    { type: 'separator', label: t('Template pronti') },
    { key: '__megamenu_template__', label: t('Template (punto di partenza)'), type: 'select',
      options: MEGAMENU_TEMPLATE_OPTIONS },

    { type: 'separator', label: t('Preset stilistico') },
    { key: 'preset', label: t('Stile'), type: 'select', options: [
      { value: 'modern-clean', label: t('Modern Clean') },
      { value: 'minimal-line', label: t('Minimal Line') },
      { value: 'magazine-bold', label: t('Magazine Bold') },
      { value: 'cinema-bar', label: t('Cinema Bar') },
      { value: 'compact-bar', label: t('Compact Bar') },
      { value: 'glass-bar', label: t('Glass Bar') },
      { value: 'neon-strip', label: t('Neon Strip') },
      { value: 'brutalist-block', label: t('Brutalist Block') },
      { value: 'gradient-bar', label: t('Gradient Bar') },
      { value: 'sticker-tape', label: t('Sticker Tape') },
      { value: 'retro-terminal', label: t('Retro Terminal') },
      { value: 'tilt-bar', label: t('Tilt Bar') },
      { value: 'custom', label: t('Personalizzato') },
    ]},
    { type: 'separator', label: t('Tipografia') },
    { key: 'typography_preset', label: t('Stile tipografico'), type: 'select', optionsSource: 'globalTypography' },
    { type: 'typography', label: t('Voce nav'),
      presetKey: 'typography_preset',
      responsiveKeys: ['size', 'letterSpacing'],
      keys: {
        size:          'font_size',
        weight:        'font_weight',
        transform:     'text_transform',
        letterSpacing: 'letter_spacing',
        color:         'text_color',
        colorHover:    'hover_color',
      },
      sizeMin: 12, sizeMax: 22, sizeStep: 1,
    },
    { type: 'typography', label: t('Voce attiva'),
      presetKey: 'typography_preset',
      keys: {
        color: 'active_color',
      },
    },
    { type: 'typography', label: t('Intestazione panel'),
      presetKey: 'typography_preset',
      responsiveKeys: ['size'],
      keys: {
        size:      'heading_size',
        weight:    'heading_weight',
        transform: 'heading_transform',
        color:     'heading_color',
      },
      sizeMin: 12, sizeMax: 20, sizeStep: 1,
    },
    { type: 'typography', label: t('Link panel'),
      presetKey: 'typography_preset',
      responsiveKeys: ['size'],
      keys: {
        size:       'link_size',
        color:      'link_color',
        colorHover: 'link_hover_color',
      },
      sizeMin: 12, sizeMax: 18, sizeStep: 1,
    },
    { type: 'typography', label: t('Descrizione panel'),
      presetKey: 'typography_preset',
      keys: {
        color: 'desc_color',
      },
      condition: { field: 'show_descriptions', value: true },
    },
    { type: 'typography', label: t('CTA pulsante'),
      presetKey: 'typography_preset',
      keys: {
        color:      'btn_color',
        colorHover: 'btn_hover_bg',
      },
      condition: { field: 'button_mode', operator: '!=', value: 'none' },
    },
    { type: 'typography', label: t('Testo mobile'),
      presetKey: 'typography_preset',
      responsiveKeys: ['size'],
      keys: {
        size:  'mobile_font_size',
        color: 'mobile_text_color',
      },
      sizeMin: 14, sizeMax: 24, sizeStep: 1,
    },
    { type: 'typography', label: t('Intestazione mobile'),
      presetKey: 'typography_preset',
      keys: {
        color: 'mobile_heading_color',
      },
    },
    { type: 'typography', label: t('Top bar testo'),
      presetKey: 'typography_preset',
      responsiveKeys: ['size'],
      keys: {
        size:  'topbar_font_size',
        color: 'topbar_text_color',
      },
      sizeMin: 10, sizeMax: 16, sizeStep: 1,
      condition: { field: 'topbar_enabled', value: true },
    },
    { type: 'typography', label: t('Top bar link'),
      presetKey: 'typography_preset',
      keys: {
        color: 'topbar_link_color',
      },
      condition: { field: 'topbar_enabled', value: true },
    },
    { type: 'typography', label: t('Sticky testo'),
      presetKey: 'typography_preset',
      keys: {
        color: 'sticky_text_color',
      },
      condition: { field: 'sticky', value: true },
    },

    { type: 'separator', label: t('Logo — Aspetto') },
    { key: 'logo_width', label: t('Larghezza logo (px)'), type: 'range', min: 60, max: 300, step: 5 },
    { key: 'logo_min_height', label: t('Altezza logo (px)'), type: 'range', min: 0, max: 120, step: 2 },
    { key: 'logo_position', label: t('Posizione logo'), type: 'select', options: [
      { value: 'left', label: t('Sinistra') },
      { value: 'center', label: t('Centro (sovrapposto)') },
      { value: 'right', label: t('Destra') },
      { value: 'stacked', label: t('Sopra il menu') },
      { value: 'split', label: t('In mezzo (split nav)') },
    ]},
    { key: 'logo_gap', label: t('Distanza logo-menu (px)'), type: 'range', min: 0, max: 40, step: 2,
      condition: { field: 'logo_position', op: 'eq', value: 'stacked' } },

    { type: 'separator', label: t('Navbar') },
    { key: 'layout', label: t('Allineamento menu'), type: 'select', options: [
      { value: 'left', label: t('Sinistra') },
      { value: 'center', label: t('Centro') },
      { value: 'right', label: t('Destra') },
    ]},
    { key: 'nav_bg', label: t('Sfondo navbar'), type: 'color' },
    { key: 'nav_height', label: t('Altezza min (px)'), type: 'range', min: 40, max: 120, step: 2 },
    { key: 'item_gap', label: t('Gap tra voci (px)'), type: 'range', min: 0, max: 40, step: 1 },

    { type: 'separator', label: t('Spaziatura barra') },
    { key: 'bar_width', label: t('Larghezza barra'), type: 'select', options: [
      { value: 'full', label: t('Tutta larghezza') },
      { value: 'wide', label: t('Wide (1400px)') },
      { value: 'classic', label: t('Classica (1200px)') },
    ]},
    { key: 'bar_padding', label: t('Padding barra (px)'), type: 'spacing', max: 60 },
    { key: 'bar_gap', label: t('Gap elementi barra (px)'), type: 'range', min: 0, max: 60, step: 2 },
    { key: 'logo_margin_right', label: t('Margine destro logo (px)'), type: 'spacing', max: 80 },

    { type: 'separator', label: t('Effetto hover voci') },
    { key: 'hover_effect', label: t('Tipo effetto'), type: 'select', options: [
      { value: 'none', label: t('Underline base (default)') },
      { value: 'underline', label: t('Underline (dal centro)') },
      { value: 'overline', label: t('Overline (sopra)') },
      { value: 'double-line', label: t('Doppia linea (sopra+sotto)') },
      { value: 'background', label: t('Sfondo colorato') },
      { value: 'framed', label: t('Cornice (bordo)') },
      { value: 'dot', label: t('Pallino sotto') },
      { value: 'bracket', label: t('Parentesi [voce]') },
      { value: 'highlight', label: t('Highlight (gradiente scivola)') },
      { value: 'fill-up', label: t('Fill Up (sfondo dal basso)') },
      { value: 'flip', label: t('Flip (rotazione 3D)') },
      { value: 'glitch', label: t('Glitch (doppio offset)') },
      { value: 'magnetic', label: t('Magnetic (segue il mouse)') },
      { value: 'underline-grow', label: t('Underline Grow (cresce)') },
    ]},
    { key: 'hover_effect_color', label: t('Colore effetto'), type: 'color' },
    { key: 'hover_effect_height', label: t('Spessore linea/bordo (px)'), type: 'range', min: 1, max: 5, step: 1 },
    { key: 'hover_effect_padding', label: t('Padding effetto (px)'), type: 'spacing', max: 30 },

    { type: 'separator', label: t('Mega Panel — Dimensione') },
    { key: 'panel_width', label: t('Larghezza panel (legacy)'), type: 'select', options: [
      { value: 'container', label: t('Contenitore') },
      { value: 'full', label: t('Full-width') },
    ]},
    { key: 'panel_size', label: t('Dimensione pannello'), type: 'select', options: [
      { value: 'auto', label: t('Automatica (adatta al contenuto)') },
      { value: 'centered', label: t('Centrato sotto la voce') },
      { value: 'section', label: t('Larghezza della barra') },
      { value: 'container', label: t('Larghezza sezione (container)') },
      { value: 'viewport', label: t('Larghezza viewport (full)') },
    ]},
    { key: 'panel_max_width', label: t('Larghezza max (px)'), type: 'range', min: 400, max: 1400, step: 10 },
    { key: 'panel_columns', label: t('Colonne'), type: 'range', min: 2, max: 6, step: 1 },

    { type: 'separator', label: t('Mega Panel — Sfondo e ombra') },
    { key: 'panel_bg', label: t('Sfondo panel'), type: 'color' },
    { key: 'panel_shadow', label: t('Ombra'), type: 'select', options: [
      { value: 'none', label: t('Nessuna') },
      { value: 'sm', label: t('Leggera') },
      { value: 'md', label: t('Media') },
      { value: 'lg', label: t('Grande') },
      { value: 'custom', label: t('Personalizzata') },
    ]},
    { key: 'panel_shadow_h', label: t('Offset H (px)'), type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'panel_shadow', op: 'eq', value: 'custom' } },
    { key: 'panel_shadow_v', label: t('Offset V (px)'), type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'panel_shadow', op: 'eq', value: 'custom' } },
    { key: 'panel_shadow_blur', label: t('Sfocatura (px)'), type: 'range', min: 0, max: 100, step: 1,
      condition: { field: 'panel_shadow', op: 'eq', value: 'custom' } },
    { key: 'panel_shadow_spread', label: t('Espansione (px)'), type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'panel_shadow', op: 'eq', value: 'custom' } },
    { key: 'panel_shadow_color', label: t('Colore ombra'), type: 'color',
      condition: { field: 'panel_shadow', op: 'eq', value: 'custom' } },
    { key: 'panel_shadow_inset', label: t('Ombra interna'), type: 'toggle',
      condition: { field: 'panel_shadow', op: 'eq', value: 'custom' } },

    { type: 'separator', label: t('Mega Panel — Layout') },
    withHover({ key: 'panel_radius', label: t('Arrotondamento (px)'), type: 'border-radius' }),
    { key: 'panel_padding', label: t('Padding (px)'), type: 'spacing', max: 60 },
    { key: 'panel_border_top', label: t('Linea accento top (px)'), type: 'range', min: 0, max: 5, step: 1 },
    { key: 'panel_border_color', label: t('Colore linea accento'), type: 'color' },
    { key: 'panel_offset_top', label: t('Distanza dal nav (px)'), type: 'range', min: 0, max: 30, step: 1 },
    { key: 'panel_origin', label: t('Origine pannello'), type: 'select', options: [
      { value: 'nav', label: t('Dal nav item (sotto la voce)') },
      { value: 'section', label: t('Dalla sezione (bordo inferiore header)') },
    ]},
    { key: 'panel_open_animation', label: t('Animazione apertura'), type: 'select', options: [
      { value: 'fade', label: t('Dissolvenza') },
      { value: 'slide-down', label: t('Scorrimento giu') },
      { value: 'slide-up', label: t('Scorrimento su') },
      { value: 'scale', label: t('Scala (dall\'alto)') },
      { value: 'scale-center', label: t('Scala (dal centro)') },
      { value: 'flip', label: t('Flip 3D') },
      { value: 'reveal', label: t('Reveal (clip-path)') },
      { value: 'blur', label: t('Sfocatura → nitido') },
    ]},

    { type: 'separator', label: t('Mega panel — Spaziatura link') },
    { key: 'link_spacing', label: t('Gap verticale link (px)'), type: 'range', min: 4, max: 16, step: 1 },

    { type: 'separator', label: t('CTA — Aspetto') },
    { key: 'btn_bg', label: t('Sfondo pulsante'), type: 'color',
      condition: { field: 'button_mode', operator: '!=', value: 'none' } },
    withHover({ key: 'btn_radius', label: t('Arrotondamento pulsante (px)'), type: 'border-radius',
      condition: { field: 'button_mode', operator: '!=', value: 'none' } }),
    { key: 'btn_padding_v', label: t('Padding verticale pulsante (px)'), type: 'spacing', max: 30,
      condition: { field: 'button_mode', operator: '!=', value: 'none' } },
    { key: 'btn_padding_h', label: t('Padding orizzontale pulsante (px)'), type: 'spacing', max: 60,
      condition: { field: 'button_mode', operator: '!=', value: 'none' } },
    { key: 'btn_margin_left', label: t('Margine sinistro pulsante (px)'), type: 'spacing', max: 40,
      condition: { field: 'button_mode', operator: '!=', value: 'none' } },
    { key: 'btn_margin_right', label: t('Margine destro pulsante (px)'), type: 'spacing', max: 40,
      condition: { field: 'button_mode', operator: '!=', value: 'none' } },
    { key: 'btn_border_width', label: t('Bordo pulsante (px)'), type: 'range', min: 0, max: 5, step: 1,
      condition: { field: 'button_mode', operator: '!=', value: 'none' } },
    { key: 'btn_border_color', label: t('Colore bordo pulsante'), type: 'color',
      condition: { field: 'button_mode', operator: '!=', value: 'none' } },

    { type: 'separator', label: t('Ricerca — Aspetto') },
    { key: 'search_icon_style', label: t('Stile icona ricerca'), type: 'select', options: [
      { value: 'lens', label: t('Lente classica') },
      { value: 'minimal', label: t('Cerchio minimal') },
      { value: 'thin', label: t('Lente sottile') },
      { value: 'target', label: t('Mirino') },
      { value: 'binocular', label: t('Binocolo') },
      { value: 'dot', label: t('Punto ricerca') },
    ]},

    { type: 'separator', label: t('Social — Aspetto') },
    { key: 'social_size', label: t('Dimensione icone (px)'), type: 'range', min: 14, max: 36, step: 1 },
    withHover({ key: 'social_color', label: t('Colore icone'), type: 'color' }, { hoverKey: 'social_hover_color' }),
    { key: 'social_style', label: t('Stile icone'), type: 'select', options: [
      { value: 'plain', label: t('Solo icona') },
      { value: 'circle', label: t('Cerchio') },
      { value: 'rounded', label: t('Rettangolo arrotondato') },
    ]},

    { type: 'separator', label: t('Mobile — Animazioni') },
    { key: 'mobile_side', label: t('Lato off-canvas'), type: 'select',
      condition: { field: 'mobile_style', op: 'eq', value: 'offcanvas' },
      options: [
        { value: 'left', label: t('Sinistra') },
        { value: 'right', label: t('Destra') },
      ]},
    { key: 'mobile_slide_direction', label: t('Direzione apertura'), type: 'select',
      condition: { field: 'mobile_style', op: 'eq', value: 'offcanvas' },
      options: [
        { value: 'left', label: t('Da sinistra') },
        { value: 'right', label: t('Da destra') },
        { value: 'top', label: t('Dall\'alto') },
      ]},
    { key: 'offcanvas_fullscreen', label: t('Off-canvas a tutto schermo'), type: 'toggle',
      condition: { field: 'mobile_style', op: 'eq', value: 'offcanvas' } },
    { key: 'fullscreen_animation', label: t('Animazione fullscreen'), type: 'select',
      condition: { field: 'mobile_style', op: 'eq', value: 'fullscreen' },
      options: [
        { value: 'fade', label: t('Dissolvenza') },
        { value: 'slide-left', label: t('Scorre da sinistra') },
        { value: 'slide-right', label: t('Scorre da destra') },
        { value: 'slide-up', label: t('Scorre dal basso') },
        { value: 'curtain', label: t('Sipario (dal centro)') },
        { value: 'circular', label: t('Cerchio (dal burger)') },
        { value: 'diagonal', label: t('Diagonale (wipe)') },
      ]},
    { key: 'menu_items_animation', label: t('Animazione voci menu'), type: 'select', options: [
      { value: 'none', label: t('Nessuna') },
      { value: 'fade-down', label: t('Fade dall\'alto') },
      { value: 'fade-up', label: t('Fade dal basso') },
      { value: 'slide-left', label: t('Slide da sinistra') },
      { value: 'slide-right', label: t('Slide da destra') },
      { value: 'scale', label: t('Scala') },
      { value: 'blur', label: t('Sfocatura') },
    ]},
    { key: 'menu_items_stagger', label: t('Ritardo stagger (ms)'), type: 'range', min: 30, max: 200, step: 10,
      condition: { field: 'menu_items_animation', operator: '!=', value: 'none' } },

    { type: 'separator', label: t('Hamburger') },
    { key: 'hamburger_style', label: t('Stile hamburger'), type: 'select', options: [
      { value: 'classic', label: t('Classic (3 linee → X)') },
      { value: 'squeeze', label: t('Squeeze (comprime → X)') },
      { value: 'arrow', label: t('Arrow (→ freccia)') },
      { value: 'minimal', label: t('Minimal (2 linee)') },
      { value: 'dot-grid', label: t('Dot Grid (9 pallini)') },
      { value: 'collapse', label: t('Collapse (centro scompare)') },
      { value: 'rotate', label: t('Rotate (ruota 180° → X)') },
      { value: 'elastic', label: t('Elastic (rimbalzo)') },
      { value: 'morph', label: t('Morph (trasformazione fluida)') },
      { value: 'magnetic', label: t('Magnetic (2 step → X)') },
    ]},
    { key: 'hamburger_size', label: t('Dimensione hamburger (px)'), type: 'range', min: 20, max: 44, step: 2 },
    { key: 'hamburger_color', label: t('Colore hamburger'), type: 'color' },

    { type: 'separator', label: t('Mobile — Pannello') },
    { key: 'mobile_bg', label: t('Sfondo pannello mobile'), type: 'color' },
    { key: 'mobile_accent_color', label: t('Colore accento mobile'), type: 'color' },
    { key: 'mob_separator_style', label: t('Separatore tra voci'), type: 'select', options: [
      { value: 'line', label: t('Linea solida') },
      { value: 'dotted', label: t('Puntinata') },
      { value: 'dashed', label: t('Tratteggiata') },
      { value: 'gradient', label: t('Sfumatura') },
      { value: 'none', label: t('Nessuno') },
    ]},
    { key: 'mobile_item_padding', label: t('Padding voci (px)'), type: 'spacing', max: 30 },
    { key: 'mobile_logo_height', label: t('Altezza logo mobile (px)'), type: 'range', min: 20, max: 120, step: 2 },

    { type: 'separator', label: t('Mobile — Indicatore sottomenu') },
    { key: 'mob_toggle_style', label: t('Stile indicatore'), type: 'select', options: [
      { value: 'chevron', label: t('Chevron (∨/∧)') },
      { value: 'plus-minus', label: t('Plus / Minus (+/−)') },
      { value: 'circle-plus', label: t('Cerchio plus (⊕/⊖)') },
      { value: 'arrow', label: t('Freccia (→/↓)') },
      { value: 'caret', label: t('Triangolo (▸/▾)') },
      { value: 'bracket', label: t('Parentesi (〉/〈)') },
      { value: 'dot-line', label: t('Punto/Linea (•/—)') },
      { value: 'none', label: t('Nessuno') },
    ]},
    { key: 'mob_toggle_position', label: t('Posizione indicatore'), type: 'select', options: [
      { value: 'right', label: t('Destra') },
      { value: 'left', label: t('Sinistra') },
    ]},
    { key: 'mob_toggle_size', label: t('Dimensione (px)'), type: 'range', min: 12, max: 32, step: 1 },
    { key: 'mob_toggle_color', label: t('Colore indicatore'), type: 'color' },

    { type: 'separator', label: t('Sticky — Aspetto') },
    { key: 'sticky_show_on_up', label: t('Mostra su scroll up'), type: 'toggle' },
    { key: 'sticky_bg', label: t('Sfondo sticky'), type: 'color',
      condition: { field: 'sticky', value: true } },
    { key: 'sticky_shadow', label: t('Ombra sticky'), type: 'toggle',
      condition: { field: 'sticky', value: true } },
    { key: 'sticky_shrink', label: t('Riduci altezza in sticky'), type: 'toggle',
      condition: { field: 'sticky', value: true } },

    { type: 'separator', label: t('Top Bar — Aspetto') },
    { key: 'topbar_bg', label: t('Sfondo top bar'), type: 'color',
      condition: { field: 'topbar_enabled', value: true } },
    { key: 'topbar_height', label: t('Altezza (px)'), type: 'range', min: 28, max: 60, step: 2,
      condition: { field: 'topbar_enabled', value: true } },
    { key: 'topbar_border_bottom', label: t('Bordo inferiore'), type: 'toggle',
      condition: { field: 'topbar_enabled', value: true } },
    { key: 'topbar_border_color', label: t('Colore bordo'), type: 'color',
      condition: { field: 'topbar_enabled', value: true } },
    { key: 'topbar_ticker_speed', label: t('Velocità ticker (sec)'), type: 'range', min: 2, max: 15, step: 1,
      condition: { field: 'topbar_left_content', value: 'ticker' } },
    { key: 'topbar_right_cta_bg', label: t('Pulsante CTA — sfondo'), type: 'color',
      condition: { field: 'topbar_enabled', value: true } },
    { key: 'topbar_right_cta_color', label: t('Pulsante CTA — colore testo'), type: 'color',
      condition: { field: 'topbar_enabled', value: true } },

    ...borderFields(),
  ],
};
