
import { borderFields, borderDefault, borderHoverDefault, borderEffectDefaults, withHover } from './_shared.js';
import { t } from '@/i18n';

/**
 * Tile NavMenu — split CONTENUTO/STILE (regola universale Olobuild).
 *   fields[]      → menu WP, stile struttura (navbar/vertical/subnav), search tile, mega menu sorgente, button voci, mobile toggle/breakpoint
 *   styleFields[] → preset, bg, typo preset, allineamento, stile verticale, indicatore, tipografia, dropdown, header/sticky, hamburger aspetto
 *   AVANZATE      → meta tecnico
 */
export default {
  type: 'navmenu',
  name: t('Menu Nav'),
  icon: 'dashicons-menu',
  category: 'navigation',
  defaults: {
    preset: 'custom',
    bg: { type: 'none' },
    typography_preset: '',
    menu_id: 0,
    style: 'navbar',
    alignment: 'left',
    mobile_toggle: true,
    mobile_style: 'offcanvas',
    text_color: '',
    hover_color: '',
    active_color: '',
    font_size: 15,
    font_weight: 'normal',
    text_transform: 'none',
    letter_spacing: 0,
    gap: 'medium',
    menu_pointer: 'none',
    menu_pointer_animation: 'fade',
    menu_pointer_color: '',
    dropdown_bg: '',
    dropdown_color: '',
    header_mode: 'overlay',
    sticky: false,
    sticky_show_on_up: false,
    sticky_bg: '',
    sticky_shadow: true,
    mega_menu: 'none',
    mega_columns: 3,
    button_items: 'none',
    button_style: 'primary',
    button_size: 'small',
    search_tile_id: '',
    search_position: 'after',
    v_show_icons: false,
    v_icon_style: 'line',
    v_icon_size: 20,
    v_icon_color: '',
    v_item_spacing: 4,
    v_item_padding: 10,
    v_separator: false,
    v_separator_color: '',
    v_active_indicator: 'left-border',
    v_active_bg: '',
    v_hover_bg: '',
    v_border_radius: 6,
    v_expand_subs: true,
    append_search: false,
    search_mode: 'modal',
    search_placeholder: 'Cerca...',
    search_post_types: 'post,page',
    search_max_results: 10,
    search_input_bg: '',
    search_input_color: '',
    search_icon_color: '',
    search_border_color: '',
    search_input_height: 36,
    search_results_bg: '',
    search_hover_bg: '',
    mobile_type: 'dropdown',
    mobile_breakpoint: 960,
    hamburger_style: 'default',
    hamburger_position: 'inline',
    hamburger_offset_x: 16,
    hamburger_offset_y: 16,
    hamburger_bg: '',
    hamburger_color: '',
    hamburger_size: 24,
    menu_badge_support: false,
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
  },

  // ─── CONTENUTO ─────────────────────────────────────────────
  fields: [
    { key: 'menu_id', label: t('Menu WordPress'), type: 'select', optionsSource: 'wpMenus' },
    { key: 'style', label: t('Tipo struttura'), type: 'select', options: [
      { value: 'navbar', label: t('Navbar orizzontale') },
      { value: 'vertical', label: t('Verticale') },
      { value: 'subnav', label: t('Link Subnav') },
    ]},

    { type: 'separator', label: t('Sotto-voci verticale') },
    { key: 'v_show_icons', label: t('Mostra icone'), type: 'toggle',
      show: s => s.style === 'vertical' },
    { key: 'v_expand_subs', label: t('Sottovoci espandibili'), type: 'toggle',
      show: s => s.style === 'vertical' },
    { key: 'v_separator', label: t('Separatore tra voci'), type: 'toggle',
      show: s => s.style === 'vertical' },

    { type: 'separator', label: t('Mega Menu — Sorgente') },
    { key: 'mega_menu', label: t('Mega Menu'), type: 'select', options: [
      { value: 'none', label: t('Disabilitato') },
      { value: 'auto', label: t('Auto (tutti i parent)') },
      { value: 'class', label: t('Classe CSS (mega-menu)') },
    ]},

    { type: 'separator', label: t('Voci pulsante') },
    { key: 'button_items', label: t('Voci da rendere pulsante'), type: 'select', options: [
      { value: 'none', label: t('Nessuna') },
      { value: 'last', label: t('Ultima voce') },
      { value: 'last-2', label: t('Ultime 2 voci') },
      { value: 'css-class', label: t('Classe CSS (olo-btn)') },
    ]},

    { type: 'separator', label: t('Ricerca integrata') },
    { key: 'search_tile_id', label: t('Tile ricerca'), type: 'select', optionsSource: 'searchTiles' },
    { key: 'search_position', label: t('Posizione'), type: 'select',
      show: s => !!s.search_tile_id,
      options: [
        { value: 'before', label: t('Prima del menu (sinistra)') },
        { value: 'after', label: t('Dopo il menu (destra)') },
      ]},

    { type: 'separator', label: t('Mobile') },
    { key: 'mobile_toggle', label: t('Hamburger mobile'), type: 'toggle' },
    { key: 'mobile_breakpoint', label: t('Breakpoint mobile (px)'), type: 'range', min: 640, max: 1200, step: 10 },
    { key: 'menu_badge_support', label: t('Supporto badge voci'), type: 'toggle' },
  ],

  // ─── STILE ─────────────────────────────────────────────────
  styleFields: [
    { type: 'separator', label: t('Preset stilistico') },
    { key: 'preset', label: t('Stile'), type: 'select', options: [
      { value: 'modern-clean',    label: t('Modern Clean') },
      { value: 'minimal-mono',    label: t('Minimal Mono') },
      { value: 'magazine-bold',   label: t('Magazine Bold') },
      { value: 'editorial-serif', label: t('Editorial Serif') },
      { value: 'compact-inline',  label: t('Compact Inline') },
      { value: 'glass-frosted',   label: t('Glass Frosted') },
      { value: 'neon-glow',       label: t('Neon Glow') },
      { value: 'brutalist-stamp', label: t('Brutalist Stamp') },
      { value: 'gradient-aurora', label: t('Gradient Aurora') },
      { value: 'sticker-fun',     label: t('Sticker Fun') },
      { value: 'retro-terminal',  label: t('Retro Terminal') },
      { value: 'tilt-3d',         label: t('3D Tilt') },
      { value: 'custom',          label: t('Personalizzato') },
    ] },
    { key: 'alignment', label: t('Allineamento'), type: 'select', options: [
      { value: 'left', label: t('Sinistra') },
      { value: 'center', label: t('Centro') },
      { value: 'right', label: t('Destra') },
    ]},

    { type: 'separator', label: t('Aspetto verticale'),
      show: s => s.style === 'vertical' },
    { key: 'v_icon_style', label: t('Stile icona'), type: 'select',
      show: s => s.style === 'vertical' && s.v_show_icons,
      options: [
        { value: 'line', label: t('Linea (outline)') },
        { value: 'filled', label: t('Pieno') },
        { value: 'circle', label: t('Cerchio sfondo') },
      ]},
    { key: 'v_icon_size', label: t('Dim. icona (px)'), type: 'range', min: 14, max: 32, step: 2,
      show: s => s.style === 'vertical' && s.v_show_icons },
    { key: 'v_item_spacing', label: t('Spaziatura voci (px)'), type: 'range', min: 0, max: 24, step: 2,
      show: s => s.style === 'vertical' },
    { key: 'v_item_padding', label: t('Padding voce (px)'), type: 'spacing', max: 20 },
    { key: 'v_separator_color', label: t('Colore separatore'), type: 'color',
      show: s => s.style === 'vertical' && s.v_separator },
    { key: 'v_active_indicator', label: t('Indicatore attivo'), type: 'select',
      show: s => s.style === 'vertical',
      options: [
        { value: 'none', label: t('Nessuno') },
        { value: 'left-border', label: t('Bordo sinistro') },
        { value: 'background', label: t('Sfondo') },
        { value: 'bold', label: t('Grassetto') },
      ]},
    { key: 'v_active_bg', label: t('Sfondo attivo'), type: 'color',
      show: s => s.style === 'vertical' && (s.v_active_indicator === 'background' || s.v_active_indicator === 'left-border') },
    { key: 'v_hover_bg', label: t('Sfondo hover'), type: 'color',
      show: s => s.style === 'vertical' },
    withHover({ key: 'v_border_radius', label: t('Raggio bordo voci (px)'), type: 'border-radius',
      show: s => s.style === 'vertical' }),

    { type: 'separator', label: t('Indicatore menu') },
    { key: 'menu_pointer', label: t('Tipo indicatore'), type: 'select', options: [
      { value: 'none', label: t('Nessuno') },
      { value: 'underline', label: t('Sottolineatura') },
      { value: 'overline', label: t('Linea sopra') },
      { value: 'framed', label: t('Cornice') },
      { value: 'background', label: t('Sfondo') },
      { value: 'double-line', label: t('Doppia linea') },
    ]},
    { key: 'menu_pointer_animation', label: t('Animazione indicatore'), type: 'select',
      show: s => s.menu_pointer && s.menu_pointer !== 'none',
      options: [
        { value: 'fade', label: t('Fade') },
        { value: 'slide', label: t('Slide') },
        { value: 'grow', label: t('Grow') },
        { value: 'drop', label: t('Drop') },
      ]},
    { key: 'menu_pointer_color', label: t('Colore indicatore'), type: 'color',
      show: s => s.menu_pointer && s.menu_pointer !== 'none' },

    { type: 'separator', label: t('Tipografia') },
    { key: 'typography_preset', label: t('Stile tipografico'), type: 'select', optionsSource: 'globalTypography' },
    { type: 'typography', label: t('Link nav'),
      presetKey: 'typography_preset',
      responsiveKeys: ['size', 'letterSpacing'],
      keys: {
        size:          'font_size',
        weight:        'font_weight',
        transform:     'text_transform',
        letterSpacing: 'letter_spacing',
        color:         'text_color',
        colorHover:    'hover_color',
      },
      sizeMin: 11, sizeMax: 24, sizeStep: 1,
    },
    { type: 'typography', label: t('Voce attiva'),
      presetKey: 'typography_preset',
      keys: {
        color: 'active_color',
      },
    },
    { type: 'typography', label: t('Dropdown'),
      presetKey: 'typography_preset',
      keys: {
        color: 'dropdown_color',
      },
    },
    { type: 'typography', label: t('Icona verticale'),
      presetKey: 'typography_preset',
      keys: {
        color: 'v_icon_color',
      },
      show: s => s.style === 'vertical' && s.v_show_icons,
    },
    { key: 'gap', label: t('Gap elementi'), type: 'select', options: [
      { value: 'small', label: t('Piccolo') },
      { value: 'medium', label: t('Medio') },
      { value: 'large', label: t('Grande') },
    ]},

    { type: 'separator', label: t('Dropdown') },
    { key: 'dropdown_bg', label: t('Sfondo dropdown'), type: 'color' },

    { type: 'separator', label: t('Header') },
    { key: 'header_mode', label: t('Modalità header'), type: 'select', options: [
      { value: 'overlay', label: t('Sovrapposto (sopra il contenuto)') },
      { value: 'classic', label: t('Classico (spinge il contenuto)') },
    ]},
    { key: 'sticky', label: t('Abilita sticky'), type: 'toggle' },
    { key: 'sticky_show_on_up', label: t('Mostra allo scroll in su'), type: 'toggle',
      show: s => !!s.sticky },
    { key: 'sticky_bg', label: t('Sfondo sticky'), type: 'color',
      show: s => !!s.sticky },
    { key: 'sticky_shadow', label: t('Ombra sticky'), type: 'toggle',
      show: s => !!s.sticky },

    { type: 'separator', label: t('Mega Menu — Aspetto') },
    { key: 'mega_columns', label: t('Colonne'), type: 'select',
      show: s => s.mega_menu && s.mega_menu !== 'none',
      options: [
        { value: 2, label: t('2 colonne') },
        { value: 3, label: t('3 colonne') },
        { value: 4, label: t('4 colonne') },
      ]},

    { type: 'separator', label: t('Voci pulsante — Aspetto') },
    { key: 'button_style', label: t('Stile pulsante'), type: 'select',
      show: s => s.button_items && s.button_items !== 'none',
      options: [
        { value: 'default', label: t('Predefinito') },
        { value: 'primary', label: t('Primary') },
        { value: 'secondary', label: t('Secondary') },
      ]},
    { key: 'button_size', label: t('Dimensione pulsante'), type: 'select',
      show: s => s.button_items && s.button_items !== 'none',
      options: [
        { value: 'small', label: t('Piccolo') },
        { value: 'default', label: t('Predefinito') },
      ]},

    { type: 'separator', label: t('Mobile — Aspetto') },
    { key: 'mobile_style', label: t('Stile mobile'), type: 'select', options: [
      { value: 'offcanvas', label: t('Pannello offcanvas') },
      { value: 'dropdown', label: t('Dropdown') },
    ]},
    { key: 'mobile_type', label: t('Menu mobile tipo'), type: 'select', options: [
      { value: 'dropdown', label: t('Dropdown') },
      { value: 'offcanvas', label: t('Offcanvas') },
      { value: 'fullscreen', label: t('Fullscreen') },
    ]},

    { type: 'separator', label: t('Hamburger') },
    { key: 'hamburger_style', label: t('Stile hamburger'), type: 'select', options: [
      { value: 'default', label: t('Default') },
      { value: 'squeeze', label: t('Squeeze') },
      { value: 'elastic', label: t('Elastic') },
    ]},
    { key: 'hamburger_position', label: t('Posizione trigger'), type: 'select', options: [
      { value: 'inline', label: t('Inline (nel flusso)') },
      { value: 'top-left', label: t('Fisso alto-sinistra') },
      { value: 'top-right', label: t('Fisso alto-destra') },
      { value: 'bottom-left', label: t('Fisso basso-sinistra') },
      { value: 'bottom-right', label: t('Fisso basso-destra') },
    ]},
    { key: 'hamburger_offset_x', label: t('Offset orizzontale (px)'), type: 'range',
      min: 0, max: 60, step: 2,
      show: s => s.hamburger_position && s.hamburger_position !== 'inline' },
    { key: 'hamburger_offset_y', label: t('Offset verticale (px)'), type: 'range',
      min: 0, max: 60, step: 2,
      show: s => s.hamburger_position && s.hamburger_position !== 'inline' },
    { key: 'hamburger_size', label: t('Dimensione icona (px)'), type: 'range', min: 16, max: 48, step: 2 },
    { key: 'hamburger_bg', label: t('Sfondo trigger'), type: 'color' },
    { key: 'hamburger_color', label: t('Colore trigger'), type: 'color' },

    ...borderFields(),
  ],
};
