import { textEffectsFields, textEffectsDefaults, borderFields, borderDefault, borderHoverDefault, borderEffectDefaults, withHover } from './_shared';
import { t } from '@/i18n';

/**
 * Tile NewsTicker — split CONTENUTO/STILE.
 *   fields[]      → items (title+url+badge+icon+timestamp), direction, etichetta (show+text+icon+position), comportamento (autoscroll/loop/random/stop_click/pause_hover), animazione tipo + marquee, controlli UI (frecce/indicatori/counter)
 *   styleFields[] → preset, bg, typo, text-effects, etichetta aspetto (shape/bg/color), badge colori, aspetto (bg/gradient/text/height/padding/radius/separator), tipografia, durate animazione, item hover effect
 */
export default {
  type: 'newsticker',
  name: t('News Ticker'),
  icon: 'dashicons-megaphone',
  category: 'dynamic',
  defaults: {
    preset: 'custom',
    bg: { type: 'none' },
    typography_preset: '',
    items: [
      { id: 'nt-1', title: t('Nuova funzionalità disponibile per tutti gli utenti'), url: '', badge: 'Novità', icon: 'star', badge_bg: '', timestamp: '' },
      { id: 'nt-2', title: t('Manutenzione programmata venerdì 21:00 - 23:00'), url: '', badge: 'Avviso', icon: 'warning', badge_bg: '', timestamp: '' },
      { id: 'nt-3', title: t('Aggiornamento versione 2.0 rilasciato con successo'), url: '', badge: '', icon: 'bolt', badge_bg: '', timestamp: '' },
    ],
    direction: 'horizontal',
    show_label: true,
    label_text: 'Breaking',
    label_icon: '',
    label_shape: 'arrow',
    label_position: 'left',
    label_bg: '',
    label_color: '',
    badge_bg: '',
    badge_color: '',
    bg_color: '',
    bg_gradient: false,
    bg_color2: '',
    bg_angle: 90,
    text_color: '',
    height: '42',
    separator: '|',
    font_size: 14,
    font_weight: '400',
    text_transform: 'none',
    letter_spacing: 0,
    tile_padding: { top: 0, right: 0, bottom: 0, left: 0 },
    animation_type: 'slide-up',
    transition_duration: 400,
    speed: '3000',
    auto_scroll: true,
    pause_on_hover: true,
    loop: true,
    random_order: false,
    stop_on_click: false,
    marquee_direction: 'left',
    marquee_gap: 60,
    marquee_duration: 25,
    show_controls: false,
    show_indicators: false,
    show_counter: false,
    logo_height: 32,
    logo_grayscale: false,
    logo_opacity: 100,
    item_hover_effect: 'none',
    ...textEffectsDefaults,
    text_effect_target: 'title',
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    border_radius: { tl: 0, tr: 0, br: 0, bl: 0 },
    border_radius_hover: null,
    border_radius_hover_duration: 300,
    ...borderEffectDefaults,
  },

  fields: [
    { key: 'items', label: t('Notizie'), type: 'content-items',
      itemFields: [
        { key: 'title', label: t('Titolo'), type: 'text' },
        { key: 'url', label: t('URL (opzionale)'), type: 'link', placeholder: t('https://...') },
        { key: 'logo', label: t('Logo (opzionale)'), type: 'image', description: t('Se valorizzato sostituisce il testo con il logo (loghi clienti)') },
        { key: 'badge', label: t('Badge (opzionale)'), type: 'text', placeholder: t('es. Novità') },
        { key: 'badge_bg', label: t('Colore badge (override)'), type: 'color' },
        { key: 'icon', label: t('Icona (opzionale)'), type: 'icon' },
        { key: 'timestamp', label: t('Timestamp (opzionale)'), type: 'text', placeholder: t('es. 2h fa') },
      ],
      newItemDefaults: { title: t('Nuova notizia'), url: '', logo: '', badge: '', badge_bg: '', icon: '', timestamp: '' },
      itemLabel: 'Notizia',
    },

    { type: 'separator', label: t('Layout') },
    { key: 'direction', label: t('Direzione'), type: 'select', options: [
      { value: 'horizontal', label: t('Orizzontale') },
      { value: 'vertical', label: t('Verticale') },
    ]},

    { type: 'separator', label: t('Etichetta') },
    { key: 'show_label', label: t('Mostra etichetta'), type: 'toggle' },
    { key: 'label_text', label: t('Testo etichetta'), type: 'text', condition: { field: 'show_label', value: true } },
    { key: 'label_icon', label: t('Icona etichetta'), type: 'icon', condition: { field: 'show_label', value: true } },
    { key: 'label_position', label: t('Posizione'), type: 'select', condition: { field: 'show_label', value: true }, options: [
      { value: 'left', label: t('Sinistra') },
      { value: 'right', label: t('Destra') },
    ]},

    { type: 'separator', label: t('Animazione & comportamento') },
    { key: 'animation_type', label: t('Transizione tra notizie'), type: 'select', options: [
      { value: 'slide-up', label: t('Slide su') },
      { value: 'slide-down', label: t('Slide giù') },
      { value: 'fade', label: t('Dissolvenza') },
      { value: 'marquee', label: t('Marquee (scroll continuo)') },
    ], description: t('Per effetti sul testo (typewriter, glitch, wave, ecc.) usa la sezione "Effetti testo"') },
    { key: 'speed', label: t('Intervallo (ms)'), type: 'range', min: 1500, max: 10000, step: 250,
      condition: { field: 'animation_type', op: 'neq', value: 'marquee' } },
    { key: 'auto_scroll', label: t('Scorrimento automatico'), type: 'toggle',
      condition: { field: 'animation_type', op: 'neq', value: 'marquee' } },
    { key: 'pause_on_hover', label: t('Pausa al passaggio mouse'), type: 'toggle' },
    { key: 'loop', label: t('Loop continuo'), type: 'toggle',
      condition: { field: 'animation_type', op: 'neq', value: 'marquee' } },
    { key: 'random_order', label: t('Ordine casuale'), type: 'toggle',
      condition: { field: 'animation_type', op: 'neq', value: 'marquee' } },
    { key: 'stop_on_click', label: t('Stop al click'), type: 'toggle',
      condition: { field: 'animation_type', op: 'neq', value: 'marquee' } },
    { key: 'marquee_direction', label: t('Direzione marquee'), type: 'select',
      condition: { field: 'animation_type', value: 'marquee' }, options: [
      { value: 'left', label: t('Da destra a sinistra') },
      { value: 'right', label: t('Da sinistra a destra') },
    ]},

    { type: 'separator', label: t('Controlli UI') },
    { key: 'show_controls', label: t('Mostra frecce prev/next'), type: 'toggle' },
    { key: 'show_indicators', label: t('Mostra indicatori (pallini)'), type: 'toggle' },
    { key: 'show_counter', label: t('Mostra contatore (1/N)'), type: 'toggle' },
  ],

  styleFields: [
    { type: 'separator', label: t('Preset stilistico') },
    { key: 'preset', label: t('Stile'), type: 'select', options: [
      { value: 'modern-clean',    label: t('Modern Clean') },
      { value: 'minimal-mono',    label: t('Minimal Mono') },
      { value: 'magazine-bold',   label: t('Magazine Bold') },
      { value: 'editorial-serif', label: t('Editorial Serif') },
      { value: 'compact-inline',  label: t('Compact Inline') },
      { value: 'glass-frosted',   label: t('Glass Frosted') },
      { value: 'neon-glow',       label: t('Neon Glow') },
      { value: 'brutalist-stamp', label: t('Brutalist Stamp') },
      { value: 'gradient-aurora', label: t('Gradient Aurora') },
      { value: 'sticker-fun',     label: t('Sticker Fun') },
      { value: 'retro-terminal',  label: t('Retro Terminal') },
      { value: 'tilt-3d',         label: t('3D Tilt') },
      { value: 'custom',          label: t('Personalizzato') },
    ] },
    { key: 'typography_preset', label: t('Stile tipografico'), type: 'select', optionsSource: 'globalTypography' },

    ...textEffectsFields([ { value: 'title', label: t('Solo Titolo') } ]),

    { type: 'separator', label: t('Etichetta — Aspetto') },
    { key: 'label_shape', label: t('Forma'), type: 'select', condition: { field: 'show_label', value: true }, options: [
      { value: 'arrow', label: t('Freccia') },
      { value: 'pill', label: t('Pillola') },
      { value: 'square', label: t('Quadrata') },
      { value: 'tag', label: t('Etichetta tag') },
    ]},
    { key: 'label_bg', label: t('Sfondo etichetta'), type: 'color', condition: { field: 'show_label', value: true } },

    { type: 'separator', label: t('Badge notizia') },
    { key: 'badge_bg', label: t('Sfondo badge'), type: 'color' },

    { type: 'separator', label: t('Aspetto') },
    { key: 'bg_color', label: t('Colore sfondo'), type: 'color' },
    { key: 'bg_gradient', label: t('Sfondo a gradiente'), type: 'toggle' },
    { key: 'bg_color2', label: t('Secondo colore gradiente'), type: 'color', condition: { field: 'bg_gradient', value: true } },
    { key: 'bg_angle', label: t('Angolo gradiente (°)'), type: 'range', min: 0, max: 360, step: 5, condition: { field: 'bg_gradient', value: true } },
    { key: 'height', label: t('Altezza (px)'), type: 'range', min: 30, max: 120 },
    { key: 'tile_padding', label: t('Padding interno'), type: 'spacing', max: 32 },
    withHover({ key: 'border_radius', label: t('Raggio bordi (px)'), type: 'border-radius' }),
    { key: 'separator', label: t('Separatore badge'), type: 'text' },

    { type: 'separator', label: t('Tipografia') },
    { type: 'typography', label: t('Notizie'),
      presetKey: 'typography_preset',
      responsiveKeys: ['size'],
      keys: {
        size:          'font_size',
        weight:        'font_weight',
        transform:     'text_transform',
        letterSpacing: 'letter_spacing',
        color:         'text_color',
      },
      sizeMin: 10, sizeMax: 24, sizeStep: 1,
    },
    { type: 'typography', label: t('Etichetta'),
      presetKey: 'typography_preset',
      keys: {
        color: 'label_color',
      },
    },
    { type: 'typography', label: t('Badge'),
      presetKey: 'typography_preset',
      keys: {
        color: 'badge_color',
      },
    },

    { type: 'separator', label: t('Durate animazione') },
    { key: 'transition_duration', label: t('Durata transizione (ms)'), type: 'range', min: 100, max: 1500, step: 50,
      condition: { field: 'animation_type', op: 'in', value: ['slide-up', 'slide-down', 'fade'] } },
    { key: 'marquee_duration', label: t('Durata loop marquee (s)'), type: 'range', min: 5, max: 120, step: 1,
      condition: { field: 'animation_type', value: 'marquee' } },
    { key: 'marquee_gap', label: t('Spazio tra notizie (px)'), type: 'range', min: 0, max: 200, step: 5,
      condition: { field: 'animation_type', value: 'marquee' } },

    { type: 'separator', label: t('Loghi') },
    { key: 'logo_height', label: t('Altezza logo (px)'), type: 'range', min: 16, max: 60, step: 2,
      description: t('Altezza normalizzata dei loghi (larghezza automatica)') },
    { key: 'logo_grayscale', label: t('Loghi in scala di grigi'), type: 'toggle',
      description: t('Look uniforme: monocromatici e schiariti, a colori in hover') },
    { key: 'logo_opacity', label: t('Opacità loghi (%)'), type: 'range', min: 0, max: 100, step: 5,
      condition: { field: 'logo_grayscale', value: true } },

    { type: 'separator', label: t('Hover notizia') },
    { key: 'item_hover_effect', label: t('Effetto hover notizia'), type: 'select', options: [
      { value: 'none', label: t('Nessuno') },
      { value: 'scale', label: t('Scala') },
      { value: 'brighten', label: t('Schiarisci') },
      { value: 'underline', label: t('Sottolinea testo') },
      { value: 'shift', label: t('Sposta a destra') },
    ]},

    ...borderFields(),
  ],
};
