import { textEffectsFields, textEffectsDefaults, borderFields, borderDefault, borderHoverDefault, borderEffectDefaults, withHover } from './_shared';
import { shadowField } from './_shared.js';
import { t } from '@/i18n';

/**
 * Tile Newsletter — split CONTENUTO/STILE.
 *   fields[]      → title, subtitle, icon (type+name+image), form (layout/show_name/placeholders/button/privacy),
 *                   successo (message/animation/redirect), content lock, integrazione email provider, anti-spam
 *   styleFields[] → preset, bg, typo, text-effects, contenitore (max_w/align/bg/radius/padding), tipografia titolo/sottotitolo,
 *                   icona aspetto, input aspetto, pulsante aspetto, shadow, border
 */
export default {
  type: 'newsletter',
  name: t('Newsletter'),
  icon: 'dashicons-email-alt',
  category: 'marketing',
  defaults: {
    bg: { type: 'none' },
    typography_preset: '',
    layout: 'horizontal',
    preset: 'custom',
    title: t('Iscriviti alla newsletter'),
    subtitle: t('Ricevi aggiornamenti e contenuti esclusivi direttamente nella tua casella email.'),
    icon_type: 'none',
    icon_name: 'mail',
    icon_image: '',
    show_name: false,
    name_placeholder: t('Il tuo nome'),
    email_placeholder: t('La tua email'),
    button_text: t('Iscriviti'),
    button_icon: true,
    privacy_text: '',
    privacy_required: false,
    success_message: t('Iscrizione completata! Controlla la tua email.'),
    success_animation: 'fade',
    redirect_url: '',
    content_lock: false,
    lock_message: t('Iscriviti alla newsletter per sbloccare questo contenuto'),
    lock_blur: 8,
    lock_height: 200,
    integration: 'none',
    mailchimp_api: '',
    mailchimp_list: '',
    brevo_api: '',
    brevo_list: '',
    activecampaign_url: '',
    activecampaign_api: '',
    activecampaign_list: '',
    convertkit_api: '',
    convertkit_form: '',
    hubspot_portal: '',
    hubspot_form: '',
    webhook_url: '',
    webhook_method: 'POST',
    honeypot: true,
    recaptcha: false,
    max_width: '600',
    alignment: 'center',
    bg_color: '',
    border_radius: 12,
    tile_padding: { top: 32, right: 32, bottom: 32, left: 32 },
    title_size: '24',
    title_weight: '700',
    title_color: '',
    subtitle_size: '14',
    subtitle_color: '',
    icon_size: '48',
    icon_color: '',
    input_bg: '#ffffff',
    input_color: '#1F2937',
    input_border: '#D1D5DB',
    input_focus_border: '',
    input_radius: 8,
    input_height: '44',
    btn_bg: '',
    btn_color: '#ffffff',
    btn_hover_bg: '',
    btn_radius: 8,
    btn_font_size: '14',
    btn_font_weight: '600',
    shadow: 'none',
    ...textEffectsDefaults,
    text_effect_target: 'title',
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
  },

  fields: [
    { key: 'title', label: t('Titolo'), type: 'text' },
    { key: 'subtitle', label: t('Sottotitolo'), type: 'textarea', rows: 2 },
    { key: 'icon_type', label: t('Icona'), type: 'select', options: [
      { value: 'none', label: t('Nessuna') },
      { value: 'emoji', label: t('Emoji / Testo') },
      { value: 'image', label: t('Immagine') },
    ]},
    { key: 'icon_name', label: t('Emoji o testo'), type: 'text', placeholder: t('📧'),
      condition: { field: 'icon_type', value: 'emoji' } },
    { key: 'icon_image', label: t('Immagine icona'), type: 'image',
      condition: { field: 'icon_type', value: 'image' } },

    { type: 'separator', label: t('Form') },
    { key: 'layout', label: t('Layout'), type: 'select', options: [
      { value: 'horizontal', label: t('Orizzontale (inline)') },
      { value: 'vertical', label: t('Verticale (stacked)') },
      { value: 'minimal', label: t('Minimal (solo email)') },
    ]},
    { key: 'show_name', label: t('Mostra campo nome'), type: 'toggle' },
    { key: 'name_placeholder', label: t('Placeholder nome'), type: 'text',
      condition: { field: 'show_name', value: true } },
    { key: 'email_placeholder', label: t('Placeholder email'), type: 'text' },
    { key: 'button_text', label: t('Testo pulsante'), type: 'text' },
    { key: 'button_icon', label: t('Icona pulsante (freccia)'), type: 'toggle' },
    { key: 'privacy_text', label: t('Testo privacy (HTML)'), type: 'textarea', rows: 2, placeholder: 'Accetto la <a href="/privacy">privacy policy</a>' },
    { key: 'privacy_required', label: t('Privacy obbligatoria'), type: 'toggle',
      condition: { field: 'privacy_text', operator: '!=', value: '' } },

    { type: 'separator', label: t('Successo') },
    { key: 'success_message', label: t('Messaggio successo'), type: 'textarea', rows: 2 },
    { key: 'redirect_url', label: t('Redirect dopo iscrizione'), type: 'link', placeholder: t('https://...') },

    { type: 'separator', label: t('Content Lock') },
    { key: 'content_lock', label: t('Blocca contenuto successivo'), type: 'toggle' },
    { key: 'lock_message', label: t('Messaggio blocco'), type: 'text',
      condition: { field: 'content_lock', value: true } },
    { key: 'lock_blur', label: t('Sfocatura contenuto (px)'), type: 'range', min: 0, max: 20, step: 1,
      condition: { field: 'content_lock', value: true } },
    { key: 'lock_height', label: t('Altezza anteprima (px)'), type: 'range', min: 50, max: 500, step: 10,
      condition: { field: 'content_lock', value: true } },

    { type: 'separator', label: t('Integrazione Email') },
    { key: 'integration', label: t('Provider'), type: 'select', options: [
      { value: 'none', label: t('Solo email (wp_mail)') },
      { value: 'mailchimp', label: t('Mailchimp') },
      { value: 'brevo', label: t('Brevo (ex Sendinblue)') },
      { value: 'activecampaign', label: t('ActiveCampaign') },
      { value: 'convertkit', label: t('ConvertKit') },
      { value: 'hubspot', label: t('HubSpot') },
      { value: 'webhook', label: t('Webhook personalizzato') },
    ]},
    { key: 'mailchimp_api', label: t('API Key'), type: 'text', condition: { field: 'integration', value: 'mailchimp' } },
    { key: 'mailchimp_list', label: t('List ID'), type: 'text', condition: { field: 'integration', value: 'mailchimp' } },
    { key: 'brevo_api', label: t('API Key'), type: 'text', condition: { field: 'integration', value: 'brevo' } },
    { key: 'brevo_list', label: t('List IDs (virgola)'), type: 'text', condition: { field: 'integration', value: 'brevo' } },
    { key: 'activecampaign_url', label: t('Account URL'), type: 'text', placeholder: t('https://account.api-us1.com'), condition: { field: 'integration', value: 'activecampaign' } },
    { key: 'activecampaign_api', label: t('API Key'), type: 'text', condition: { field: 'integration', value: 'activecampaign' } },
    { key: 'activecampaign_list', label: t('List ID'), type: 'text', condition: { field: 'integration', value: 'activecampaign' } },
    { key: 'convertkit_api', label: t('API Key'), type: 'text', condition: { field: 'integration', value: 'convertkit' } },
    { key: 'convertkit_form', label: t('Form ID'), type: 'text', condition: { field: 'integration', value: 'convertkit' } },
    { key: 'hubspot_portal', label: t('Portal ID'), type: 'text', condition: { field: 'integration', value: 'hubspot' } },
    { key: 'hubspot_form', label: t('Form GUID'), type: 'text', condition: { field: 'integration', value: 'hubspot' } },
    { key: 'webhook_url', label: t('URL Webhook'), type: 'text', condition: { field: 'integration', value: 'webhook' } },
    { key: 'webhook_method', label: t('Metodo'), type: 'select', options: [
      { value: 'POST', label: t('POST') },
      { value: 'PUT', label: t('PUT') },
    ], condition: { field: 'integration', value: 'webhook' } },

    { type: 'separator', label: t('Anti-spam') },
    { key: 'honeypot', label: t('Honeypot (consigliato)'), type: 'toggle' },
    { key: 'recaptcha', label: t('reCAPTCHA v3'), type: 'toggle' },
  ],

  styleFields: [
    { type: 'separator', label: t('Preset stilistico') },
    { key: 'preset', label: t('Stile'), type: 'select', options: [
      { value: 'modern-clean',    label: t('Modern Clean') },
      { value: 'minimal-inline',  label: t('Minimal Inline') },
      { value: 'magazine-promo',  label: t('Magazine Promo') },
      { value: 'centered-card',   label: t('Centered Card') },
      { value: 'split-image',     label: t('Split with Image') },
      { value: 'glass-floating',  label: t('Glass Floating') },
      { value: 'neon-cyber',      label: t('Neon Cyber') },
      { value: 'brutalist-stamp', label: t('Brutalist Stamp') },
      { value: 'gradient-aurora', label: t('Gradient Aurora') },
      { value: 'sticky-note',     label: t('Sticky Note') },
      { value: 'retro-zine',      label: t('Retro Zine') },
      { value: 'tilt-card',       label: t('Tilt Card') },
      { value: 'custom',          label: t('Personalizzato') },
    ]},
    { key: 'typography_preset', label: t('Stile tipografico'), type: 'select', optionsSource: 'globalTypography' },

    ...textEffectsFields([
      { value: 'title', label: t('Solo Titolo') },
      { value: 'subtitle', label: t('Solo Sottotitolo') },
      { value: 'all', label: t('Tutti gli elementi testuali') },
    ]),

    { type: 'separator', label: t('Successo — Animazione') },
    { key: 'success_animation', label: t('Animazione successo'), type: 'select', options: [
      { value: 'fade', label: t('Fade') },
      { value: 'slide-up', label: t('Scivola su') },
      { value: 'checkmark', label: t('Checkmark animato') },
    ]},

    { type: 'separator', label: t('Contenitore') },
    { key: 'max_width', label: t('Larghezza max (px)'), type: 'text' },
    { key: 'alignment', label: t('Allineamento'), type: 'select', options: [
      { value: 'left', label: t('Sinistra') },
      { value: 'center', label: t('Centro') },
      { value: 'right', label: t('Destra') },
    ]},
    { key: 'bg_color', label: t('Sfondo'), type: 'color' },
    withHover({ key: 'border_radius', label: t('Raggio bordi'), type: 'border-radius'}),
    { key: 'tile_padding', label: t('Padding (px)'), type: 'spacing', max: 60 },

    { type: 'separator', label: t('Tipografia') },
    { type: 'typography', label: t('Titolo'),
      presetKey: 'typography_preset',
      responsiveKeys: ['size'],
      keys: {
        size:   'title_size',
        weight: 'title_weight',
        color:  'title_color',
      },
      sizeMin: 14, sizeMax: 48, sizeStep: 1,
    },
    { type: 'typography', label: t('Sottotitolo'),
      presetKey: 'typography_preset',
      responsiveKeys: ['size'],
      keys: {
        size:  'subtitle_size',
        color: 'subtitle_color',
      },
      sizeMin: 11, sizeMax: 20, sizeStep: 1,
    },
    { type: 'typography', label: t('Pulsante'),
      presetKey: 'typography_preset',
      responsiveKeys: ['size'],
      keys: {
        size:   'btn_font_size',
        weight: 'btn_font_weight',
        color:  'btn_color',
      },
      sizeMin: 11, sizeMax: 20, sizeStep: 1,
    },

    { type: 'separator', label: t('Icona — Aspetto') },
    { key: 'icon_size', label: t('Dimensione icona (px)'), type: 'range', min: 24, max: 96, step: 2 },
    { key: 'icon_color', label: t('Colore icona'), type: 'color' },

    { type: 'separator', label: t('Stile input') },
    { key: 'input_bg', label: t('Sfondo input'), type: 'color' },
    { key: 'input_color', label: t('Colore testo input'), type: 'color' },
    { key: 'input_border', label: t('Bordo input'), type: 'color' },
    { key: 'input_focus_border', label: t('Bordo focus'), type: 'color' },
    withHover({ key: 'input_radius', label: t('Raggio input'), type: 'border-radius'}),
    { key: 'input_height', label: t('Altezza input (px)'), type: 'range', min: 32, max: 56, step: 2 },

    { type: 'separator', label: t('Stile pulsante') },
    { key: 'btn_bg', label: t('Sfondo pulsante'), type: 'color' },
    { key: 'btn_hover_bg', label: t('Sfondo hover'), type: 'color' },
    withHover({ key: 'btn_radius', label: t('Raggio pulsante'), type: 'border-radius'}),

    ...shadowField,
    ...borderFields(),
  ],
};
