export default {
  type: 'olo_room_grid',
  name: 'Sale - Mappa e Lista',
  icon: 'dashicons-building',
  category: 'olo-space',
  defaults: {
    // Filtri
    visible_filters: 'type,district,capacity,equipment',
    equipment_filter_list: '',
    // Mappa
    layout: 'map-left',
    map_height: '500',
    map_sticky: true,
    tile_layer: 'positron',
    default_zoom: '13',
    fit_bounds: true,
    marker_color: '',
    // Griglia
    columns: '1',
    columns_mobile: '1',
    gap: 'default',
    items_per_page: '8',
    pagination_style: 'numbers',
    // Card contenuto
    card_image: true,
    card_gallery: false,
    card_video: false,
    card_excerpt: true,
    card_equipment: true,
    card_price: true,
    gallery_counter: false,
    gallery_swipe: true,
    // Card sfondo
    card_bg_type: 'color',
    card_bg: '',
    card_bg_gradient_from: '',
    card_bg_gradient_to: '',
    card_bg_gradient_angle: '135',
    card_hover_bg: '',
    // Card bordo
    card_border_width: '1',
    card_border_style: 'solid',
    card_border_color: '',
    card_border_radius: '',
    card_radius: '10',
    card_border_hover: '',
    card_hover_border_width: '',
    card_shadow: 'none',
    card_hover_shadow: '',
    card_hover_lift: true,
    // Immagine
    image_height: '160',
    image_aspect_ratio: '',
    image_object_fit: 'cover',
    image_radius: '0',
    hover_effect: 'none',
    fx_kenburns: false,
    fx_kenburns_speed: '20',
    fx_kenburns_scale: '1.12',
    // Filtri immagine
    fx_vignette: false,
    fx_vignette_strength: '40',
    fx_grain: false,
    fx_grain_opacity: '6',
    fx_tint: false,
    fx_tint_color: '',
    fx_tint_opacity: '10',
    fx_tint_blend: 'multiply',
    // Overlay
    overlay_gradient: false,
    overlay_color: '#000000',
    overlay_opacity: '50',
    overlay_direction: 'bottom',
    overlay_height: '50',
    // Testo
    tile_padding: { top: 14, right: 14, bottom: 14, left: 14 },
    title_size: '1',
    title_color: '',
    excerpt_size: '0.85',
    excerpt_color: '',
    meta_color: '',
    tag_bg: '',
    tag_color: '',
    body_bg: '',
    body_bg_opacity: '100',
  },
  fields: [
    // ═══════════════════════════════════════════
    // 1. Filtri
    // ═══════════════════════════════════════════
    { type: 'separator', label: 'Filtri' },
    {
      key: 'visible_filters',
      label: 'Filtri visibili',
      type: 'multi_pills',
      options: [
        { value: 'type', label: 'Tipo sala', icon: 'home' },
        { value: 'district', label: 'Zona', icon: 'location' },
        { value: 'capacity', label: 'Capienza', icon: 'users' },
        { value: 'equipment', label: 'Dotazioni', icon: 'star' },
      ],
    },
    {
      key: 'equipment_filter_list',
      label: 'Dotazioni nel filtro',
      type: 'multi_pills',
      options: [
        { value: 'wifi', label: 'WiFi' },
        { value: 'climatizzazione', label: 'Climatizzazione' },
        { value: 'proiettore', label: 'Proiettore' },
        { value: 'proiettore-hd', label: 'Proiettore HD' },
        { value: 'proiettore-led', label: 'Proiettore LED' },
        { value: 'proiettore-cinematografico', label: 'Proiettore cinematografico' },
        { value: 'schermo-motorizzato', label: 'Schermo motorizzato' },
        { value: 'schermo-a-parete', label: 'Schermo a parete' },
        { value: 'schermo-avvolgibile-grande-formato', label: 'Schermo grande formato' },
        { value: 'lavagna', label: 'Lavagna' },
        { value: 'lavagna-a-fogli-mobili', label: 'Lavagna a fogli mobili' },
        { value: 'lavagna-interattiva', label: 'Lavagna interattiva' },
        { value: 'lavagna-interattiva-multimediale-lim', label: 'LIM' },
        { value: 'microfono-fisso', label: 'Microfono fisso' },
        { value: 'microfono-wireless', label: 'Microfono wireless' },
        { value: 'impianto-audio', label: 'Impianto Audio' },
        { value: 'impianto-audio-con-bluetooth', label: 'Audio Bluetooth' },
        { value: 'impianto-audio-professionale', label: 'Audio professionale' },
        { value: 'amplificazione', label: 'Amplificazione' },
        { value: 'mixer-audio-24-canali', label: 'Mixer audio 24ch' },
        { value: 'registrazione-audio', label: 'Registrazione audio' },
        { value: 'videoconferenza', label: 'Videoconferenza' },
        { value: 'webcam-per-videoconferenze', label: 'Webcam videoconferenze' },
        { value: 'collegamento-streaming', label: 'Streaming' },
        { value: 'postazioni-pc', label: 'Postazioni PC' },
        { value: 'stampante-multifunzione', label: 'Stampante' },
        { value: 'palco', label: 'Palco' },
        { value: 'predisposizione-palco-mobile', label: 'Palco mobile' },
        { value: 'illuminazione-scenografica', label: 'Luci scenografiche' },
        { value: 'luci-palcoscenico-dmx', label: 'Luci palcoscenico DMX' },
        { value: 'illuminazione-museale-led', label: 'Illuminazione museale LED' },
        { value: 'illuminazione-pubblica', label: 'Illuminazione pubblica' },
        { value: 'cabina-regia', label: 'Cabina regia' },
        { value: 'camerini', label: 'Camerini' },
        { value: 'leggio-relatori', label: 'Leggio relatori' },
        { value: 'tavolo-conferenze-modulare', label: 'Tavolo conferenze' },
        { value: 'pianoforte-a-coda', label: 'Pianoforte a coda' },
        { value: 'pianoforte-verticale', label: 'Pianoforte verticale' },
        { value: 'cucina', label: 'Cucina' },
        { value: 'cucina-di-servizio', label: 'Cucina di servizio' },
        { value: 'punto-acqua', label: 'Punto acqua' },
        { value: 'distributore-bevande-calde', label: 'Distributore bevande' },
        { value: 'guardaroba', label: 'Guardaroba' },
        { value: 'anticamera-di-accoglienza', label: 'Anticamera accoglienza' },
        { value: 'loop-induttivo-per-ipoudenti', label: 'Loop ipoudenti' },
        { value: 'allacci-elettrici', label: 'Allacci elettrici' },
        { value: 'prese-elettriche', label: 'Prese elettriche' },
        { value: 'prese-di-corrente-ai-posti', label: 'Prese ai posti' },
        { value: 'ciabatte-multipresa-ai-banchi', label: 'Multipresa ai banchi' },
        { value: 'controllo-umidita', label: 'Controllo umidita' },
        { value: 'videosorveglianza', label: 'Videosorveglianza' },
        { value: 'basi-espositive', label: 'Basi espositive' },
        { value: 'binari-appendimento-quadri', label: 'Binari quadri' },
        { value: 'teche-vetro', label: 'Teche vetro' },
        { value: 'transenne-e-delimitazioni', label: 'Transenne' },
        { value: 'pavimento-sportivo-antiurto', label: 'Pavimento sportivo' },
        { value: 'attrezzi-fitness-base', label: 'Attrezzi fitness' },
        { value: 'specchi-a-parete', label: 'Specchi a parete' },
        { value: 'spogliatoi-con-docce', label: 'Spogliatoi con docce' },
        { value: 'tappetini', label: 'Tappetini' },
      ],
      desc: 'Vuoto = mostra tutte le dotazioni nel filtro',
    },

    // ═══════════════════════════════════════════
    // 2. Mappa
    // ═══════════════════════════════════════════
    { type: 'separator', label: 'Mappa' },
    { key: 'layout', label: 'Posizione mappa', type: 'select', options: [
      { value: 'map-left', label: 'Mappa a sinistra' },
      { value: 'map-right', label: 'Mappa a destra' },
      { value: 'map-top', label: 'Mappa in alto' },
      { value: 'cards-only', label: 'Nessuna mappa (solo card)' },
    ]},
    { key: 'map_height', label: 'Altezza mappa (px)', type: 'range', min: 300, max: 800, step: 10,
      condition: { field: 'layout', operator: '!=', value: 'cards-only' } },
    { key: 'map_sticky', label: 'Mappa fissa durante lo scroll', type: 'toggle',
      condition: { field: 'layout', operator: '!=', value: 'cards-only' } },
    { key: 'tile_layer', label: 'Stile mappa', type: 'select', options: [
      { value: 'osm', label: 'OpenStreetMap' },
      { value: 'positron', label: 'Positron (chiaro)' },
      { value: 'dark', label: 'Dark' },
    ], condition: { field: 'layout', operator: '!=', value: 'cards-only' } },
    { key: 'default_zoom', label: 'Zoom iniziale', type: 'range', min: 5, max: 18, step: 1,
      condition: { field: 'layout', operator: '!=', value: 'cards-only' } },
    { key: 'fit_bounds', label: 'Auto-zoom sui risultati', type: 'toggle',
      condition: { field: 'layout', operator: '!=', value: 'cards-only' } },
    { key: 'marker_color', label: 'Colore pin', type: 'color',
      condition: { field: 'layout', operator: '!=', value: 'cards-only' } },

    // ═══════════════════════════════════════════
    // 3. Griglia
    // ═══════════════════════════════════════════
    { type: 'separator', label: 'Griglia' },
    { key: 'columns', label: 'Colonne', type: 'select', options: [
      { value: '1', label: '1' }, { value: '2', label: '2' }, { value: '3', label: '3' },
    ]},
    { key: 'columns_mobile', label: 'Colonne su mobile', type: 'select', options: [
      { value: '1', label: '1' }, { value: '2', label: '2' },
    ]},
    { key: 'gap', label: 'Spaziatura tra card', type: 'select', options: [
      { value: 'collapse', label: 'Nessuna' },
      { value: 'small', label: 'Piccola' },
      { value: 'default', label: 'Standard' },
      { value: 'medium', label: 'Media' },
      { value: 'large', label: 'Grande' },
    ]},
    { key: 'items_per_page', label: 'Sale per pagina', type: 'select', options: [
      { value: '4', label: '4' }, { value: '6', label: '6' },
      { value: '8', label: '8' }, { value: '12', label: '12' },
      { value: '16', label: '16' }, { value: '24', label: '24' },
    ]},
    { key: 'pagination_style', label: 'Stile navigazione', type: 'select', options: [
      { value: 'numbers', label: 'Numeri pagina' },
      { value: 'arrows', label: 'Frecce avanti/indietro' },
      { value: 'loadmore', label: 'Pulsante Carica altro' },
    ]},

    // ═══════════════════════════════════════════
    // 4. Card contenuto
    // ═══════════════════════════════════════════
    { type: 'separator', label: 'Card contenuto' },
    { key: 'card_image', label: 'Mostra immagine', type: 'toggle' },
    { key: 'card_gallery', label: 'Galleria sfogliabile', type: 'toggle',
      condition: { field: 'card_image', value: true } },
    { key: 'card_video', label: 'Video nelle card', type: 'toggle',
      condition: { field: 'card_image', value: true } },
    { key: 'card_excerpt', label: 'Mostra descrizione breve', type: 'toggle' },
    { key: 'card_equipment', label: 'Mostra dotazioni', type: 'toggle' },
    { key: 'card_price', label: 'Mostra tariffa', type: 'toggle' },
    { key: 'gallery_counter', label: 'Contatore foto (2/5)', type: 'toggle',
      condition: { field: 'card_gallery', value: true } },
    { key: 'gallery_swipe', label: 'Swipe touch su mobile', type: 'toggle',
      condition: { field: 'card_gallery', value: true } },

    // ═══════════════════════════════════════════
    // 5. Card sfondo
    // ═══════════════════════════════════════════
    { type: 'separator', label: 'Card sfondo' },
    { key: 'card_bg_type', label: 'Tipo sfondo', type: 'select', options: [
      { value: 'color', label: 'Colore piatto' },
      { value: 'gradient', label: 'Gradiente' },
    ]},
    { key: 'card_bg', label: 'Colore sfondo card', type: 'color',
      condition: { field: 'card_bg_type', value: 'color' } },
    { key: 'card_bg_gradient_from', label: 'Gradiente da', type: 'color',
      condition: { field: 'card_bg_type', value: 'gradient' } },
    { key: 'card_bg_gradient_to', label: 'Gradiente a', type: 'color',
      condition: { field: 'card_bg_type', value: 'gradient' } },
    { key: 'card_bg_gradient_angle', label: 'Angolo gradiente', type: 'range', min: 0, max: 360, step: 5,
      condition: { field: 'card_bg_type', value: 'gradient' } },
    { key: 'card_hover_bg', label: 'Sfondo card su hover', type: 'color' },

    // ═══════════════════════════════════════════
    // 6. Card bordo
    // ═══════════════════════════════════════════
    { type: 'separator', label: 'Card bordo' },
    { key: 'card_border_width', label: 'Spessore bordo (px)', type: 'range', min: 0, max: 5, step: 1 },
    { key: 'card_border_style', label: 'Stile bordo', type: 'select', options: [
      { value: 'solid', label: 'Continuo' },
      { value: 'dashed', label: 'Tratteggiato' },
      { value: 'dotted', label: 'Puntinato' },
      { value: 'none', label: 'Nessuno' },
    ]},
    { key: 'card_border_color', label: 'Colore bordo', type: 'color' },
    { key: 'card_border_radius', label: 'Raggio angoli (4 valori)', type: 'border-radius' },
    { key: 'card_border_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius' },
    { key: 'card_border_hover', label: 'Colore bordo hover', type: 'color' },
    { key: 'card_hover_border_width', label: 'Spessore bordo hover (px)', type: 'range', min: 0, max: 5, step: 1 },
    { key: 'card_shadow', label: 'Ombra card', type: 'select', options: [
      { value: 'none', label: 'Nessuna' },
      { value: 'sm', label: 'Leggera' },
      { value: 'md', label: 'Media' },
      { value: 'lg', label: 'Forte' },
      { value: 'xl', label: 'Molto forte' },
      { value: 'custom', label: 'Personalizzata' },
    ]},
    { key: 'card_shadow_h', label: 'Offset H (px)', type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'card_shadow', op: 'eq', value: 'custom' } },
    { key: 'card_shadow_v', label: 'Offset V (px)', type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'card_shadow', op: 'eq', value: 'custom' } },
    { key: 'card_shadow_blur', label: 'Sfocatura (px)', type: 'range', min: 0, max: 100, step: 1,
      condition: { field: 'card_shadow', op: 'eq', value: 'custom' } },
    { key: 'card_shadow_spread', label: 'Espansione (px)', type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'card_shadow', op: 'eq', value: 'custom' } },
    { key: 'card_shadow_color', label: 'Colore ombra', type: 'color',
      condition: { field: 'card_shadow', op: 'eq', value: 'custom' } },
    { key: 'card_shadow_inset', label: 'Ombra interna', type: 'toggle',
      condition: { field: 'card_shadow', op: 'eq', value: 'custom' } },
    { key: 'card_hover_shadow', label: 'Ombra card su hover', type: 'select', options: [
      { value: '', label: 'Predefinita' },
      { value: 'none', label: 'Nessuna' },
      { value: 'sm', label: 'Leggera' },
      { value: 'md', label: 'Media' },
      { value: 'lg', label: 'Forte' },
      { value: 'xl', label: 'Molto forte' },
      { value: 'custom', label: 'Personalizzata' },
    ]},
    { key: 'card_hover_shadow_h', label: 'Offset H hover (px)', type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'card_hover_shadow', op: 'eq', value: 'custom' } },
    { key: 'card_hover_shadow_v', label: 'Offset V hover (px)', type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'card_hover_shadow', op: 'eq', value: 'custom' } },
    { key: 'card_hover_shadow_blur', label: 'Sfocatura hover (px)', type: 'range', min: 0, max: 100, step: 1,
      condition: { field: 'card_hover_shadow', op: 'eq', value: 'custom' } },
    { key: 'card_hover_shadow_spread', label: 'Espansione hover (px)', type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'card_hover_shadow', op: 'eq', value: 'custom' } },
    { key: 'card_hover_shadow_color', label: 'Colore ombra hover', type: 'color',
      condition: { field: 'card_hover_shadow', op: 'eq', value: 'custom' } },
    { key: 'card_hover_shadow_inset', label: 'Ombra interna hover', type: 'toggle',
      condition: { field: 'card_hover_shadow', op: 'eq', value: 'custom' } },
    { key: 'card_hover_lift', label: 'Sollevamento su hover', type: 'toggle' },

    // ═══════════════════════════════════════════
    // 7. Immagine
    // ═══════════════════════════════════════════
    { type: 'separator', label: 'Immagine' },
    { key: 'image_height', label: 'Altezza immagine (px)', type: 'range', min: 80, max: 350, step: 10,
      condition: { field: 'image_aspect_ratio', value: '' } },
    { key: 'image_aspect_ratio', label: 'Proporzioni', type: 'select', options: [
      { value: '', label: 'Altezza fissa (px)' },
      { value: '1/1', label: '1:1 Quadrato' },
      { value: '4/3', label: '4:3 Classico' },
      { value: '3/2', label: '3:2 Foto' },
      { value: '16/9', label: '16:9 Panoramico' },
      { value: '2/1', label: '2:1 Ultra-wide' },
    ]},
    { key: 'image_object_fit', label: 'Adattamento immagine', type: 'select', options: [
      { value: 'cover', label: 'Riempi (cover)' },
      { value: 'contain', label: 'Adatta (contain)' },
      { value: 'fill', label: 'Distorci (fill)' },
    ]},
    { key: 'image_radius', label: 'Raggio bordo immagine (px)', type: 'border-radius' },
    { key: 'image_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius' },
    { key: 'hover_effect', label: 'Effetto hover', type: 'select', options: [
      { value: 'none', label: 'Nessuno' },
      { value: 'zoom', label: 'Zoom' },
      { value: 'zoom-rotate', label: 'Zoom + rotazione' },
      { value: 'brightness', label: 'Luminosita' },
      { value: 'desaturate', label: 'Desatura → colore' },
      { value: 'blur-in', label: 'Sfocatura → nitido' },
      { value: 'slide-up', label: 'Scorrimento in alto' },
      { value: 'glow', label: 'Bagliore' },
      { value: 'tilt', label: 'Tilt 3D' },
    ]},
    { key: 'fx_kenburns', label: 'Ken Burns (zoom cinematico)', type: 'toggle' },
    { key: 'fx_kenburns_speed', label: 'Velocita Ken Burns (s)', type: 'range', min: 10, max: 40, step: 1,
      condition: { field: 'fx_kenburns', value: true } },
    { key: 'fx_kenburns_scale', label: 'Intensita zoom', type: 'range', min: 1.05, max: 1.25, step: 0.01,
      condition: { field: 'fx_kenburns', value: true } },

    // ═══════════════════════════════════════════
    // 8. Filtri immagine
    // ═══════════════════════════════════════════
    { type: 'separator', label: 'Filtri immagine' },
    { key: 'fx_vignette', label: 'Vignettatura', type: 'toggle' },
    { key: 'fx_vignette_strength', label: 'Intensita vignettatura (%)', type: 'range', min: 10, max: 80, step: 5,
      condition: { field: 'fx_vignette', value: true } },
    { key: 'fx_grain', label: 'Grana pellicola', type: 'toggle' },
    { key: 'fx_grain_opacity', label: 'Opacita grana (%)', type: 'range', min: 2, max: 20, step: 1,
      condition: { field: 'fx_grain', value: true } },
    { key: 'fx_tint', label: 'Tinta colore', type: 'toggle' },
    { key: 'fx_tint_color', label: 'Colore tinta', type: 'color',
      condition: { field: 'fx_tint', value: true } },
    { key: 'fx_tint_opacity', label: 'Opacita tinta (%)', type: 'range', min: 5, max: 50, step: 5,
      condition: { field: 'fx_tint', value: true } },
    { key: 'fx_tint_blend', label: 'Modo fusione', type: 'select', options: [
      { value: 'multiply', label: 'Moltiplica' },
      { value: 'overlay', label: 'Sovrapposizione' },
      { value: 'color', label: 'Colore' },
      { value: 'soft-light', label: 'Luce soffusa' },
      { value: 'hard-light', label: 'Luce forte' },
    ], condition: { field: 'fx_tint', value: true } },

    // ═══════════════════════════════════════════
    // 9. Overlay
    // ═══════════════════════════════════════════
    { type: 'separator', label: 'Overlay immagine' },
    { key: 'overlay_gradient', label: 'Overlay sfumato', type: 'toggle' },
    { key: 'overlay_color', label: 'Colore overlay', type: 'color',
      condition: { field: 'overlay_gradient', value: true } },
    { key: 'overlay_opacity', label: 'Opacita overlay (%)', type: 'range', min: 10, max: 90, step: 5,
      condition: { field: 'overlay_gradient', value: true } },
    { key: 'overlay_direction', label: 'Direzione sfumatura', type: 'select', options: [
      { value: 'bottom', label: 'Dal basso' },
      { value: 'top', label: "Dall'alto" },
      { value: 'left', label: 'Da sinistra' },
      { value: 'right', label: 'Da destra' },
    ], condition: { field: 'overlay_gradient', value: true } },
    { key: 'overlay_height', label: 'Altezza gradiente (%)', type: 'range', min: 20, max: 100, step: 5,
      condition: { field: 'overlay_gradient', value: true } },

    // ═══════════════════════════════════════════
    // 10. Testo
    // ═══════════════════════════════════════════
    { type: 'separator', label: 'Stile testo' },
    { key: 'tile_padding', label: 'Padding (px)', type: 'spacing', max: 40 },
    { key: 'title_size', label: 'Dimensione titolo (em)', type: 'range', min: 0.7, max: 2.5, step: 0.05 },
    { key: 'title_color', label: 'Colore titolo', type: 'color' },
    { key: 'excerpt_size', label: 'Dimensione estratto (em)', type: 'range', min: 0.7, max: 1.5, step: 0.05 },
    { key: 'excerpt_color', label: 'Colore estratto', type: 'color' },
    { key: 'meta_color', label: 'Colore riga meta (persone, mq, prezzo)', type: 'color' },
    { key: 'tag_bg', label: 'Sfondo pill dotazioni', type: 'color' },
    { key: 'tag_color', label: 'Testo pill dotazioni', type: 'color' },
    { key: 'body_bg', label: 'Sfondo area testo', type: 'color' },
    { key: 'body_bg_opacity', label: 'Opacita sfondo (%)', type: 'range', min: 0, max: 100, step: 5,
      condition: { field: 'body_bg', operator: '!=', value: '' } },
  ],
};
