import { t } from '@/i18n';
import { oloxAccentField } from './_oloxShared.js';

/**
 * OLOX Hero — hero delle pagine prodotto OLOtheme (.dhero .grid2):
 * logo prodotto, kicker, H1 Fraunces con <em> (effetto drop/scramble), sub,
 * tag pill, 2 CTA + scena animata a destra (wall/clock/console/term/porthole/medal).
 * Render Vue == PHP (OloxHeroTile.vue / class-oloxhero-tile.php).
 */
export default {
  type: 'oloxhero',
  name: t('OLOX — Hero prodotto'),
  icon: 'dashicons-superhero',
  category: 'marketing',
  // Ritirata dalla palette: le pagine della replica olotheme.com sono composte
  // con tile classiche (headline, badge, info-cards, pricing, cta-banner, toc,
  // desclist, flipcard, counter, marquee). Resta per i template salvati.
  hidden: true,

  defaults: {
    accent: 'build',
    bg_variant: 'build',
    logo: '',
    kicker: 'Il telaio · page builder olonico',
    title_html: 'Mattone su <em>mattone.</em>',
    title_fx: 'drop',
    scramble_words: [
      { text: 'Benvenuto' }, { text: 'Welcome' }, { text: 'Willkommen' },
      { text: 'Bienvenue' }, { text: 'Bienvenido' }, { text: 'Bem-vindo' },
      { text: 'Welkom' }, { text: 'Välkommen' }, { text: 'ようこそ' }, { text: '欢迎' },
    ],
    sub_html: '<strong>187 tile in 12 famiglie</strong>, auto-discovered, con animazioni ed effetti di serie.',
    tags: [
      { text: '€0 free · 100+ tile', hot: true },
      { text: '36 animazioni', hot: false },
    ],
    cta1_text: 'Guarda il cantiere ↓',
    cta1_url: '#cantiere',
    cta2_text: 'Free vs Pro',
    cta2_url: '#prezzi',
    scene: 'wall',
    wall_count: 187,
    wall_label: 'tile / 187',
    clock_label: 'lo scroll muove le lancette',
    console_title: 'translator',
    console_sub: '· dashboard · batch in corso',
    console_rows: [
      { lc: 'EN', w: 100, pc: '' }, { lc: 'DE', w: 100, pc: '' }, { lc: 'FR', w: 96, pc: '' },
      { lc: 'ES', w: 92, pc: '' }, { lc: 'PT', w: 84, pc: '' }, { lc: 'NL', w: 78, pc: '' },
      { lc: 'JA', w: 64, pc: '' }, { lc: '+21', w: 52, pc: '…' },
    ],
    term_title: 'sentinel',
    term_sub: '· boot sequence',
    term_lines: [
      { cls: 'cy', text: '[sentinel] avvio pannello v1.2.0 …' },
      { cls: 'ok', text: '[waf]      regole OWASP caricate (4 famiglie)' },
      { cls: 'bad', text: '[waf]      SQLi da 185.220.•.•  → BLOCCATO' },
    ],
    medal_top: 'livello',
    medal_big: '1',
    medal_bot: 'studente',
    pad_top: 0,
  },

  fields: [
    { type: 'separator', label: t('Contenuto') },
    { key: 'logo', label: t('Logo prodotto (reso bianco)'), type: 'image' },
    { key: 'kicker', label: t('Kicker'), type: 'text' },
    { key: 'title_html', label: t('Titolo (HTML, <em> per corsivo colorato)'), type: 'textarea' },
    { key: 'title_fx', label: t('Effetto titolo'), type: 'select', options: [
      { value: 'drop', label: t('Blocchi che cadono') },
      { value: 'scramble', label: t('Parola scramble ({scramble} nel titolo)') },
      { value: 'none', label: t('Nessuno') },
    ] },
    { key: 'scramble_words', label: t('Parole scramble'), type: 'content-items', itemLabel: t('Parola'),
      defaults: { text: 'Benvenuto' },
      itemFields: [ { key: 'text', label: t('Parola'), type: 'text' } ],
      condition: { field: 'title_fx', op: 'eq', value: 'scramble' } },
    { key: 'sub_html', label: t('Sottotitolo (HTML)'), type: 'textarea' },
    { key: 'tags', label: t('Tag pill'), type: 'content-items', itemLabel: t('Tag'),
      defaults: { text: 'tag', hot: false },
      itemFields: [
        { key: 'text', label: t('Testo'), type: 'text' },
        { key: 'hot', label: t('Evidenziato (colore prodotto)'), type: 'toggle' },
      ] },
    { type: 'separator', label: t('CTA') },
    { key: 'cta1_text', label: t('CTA 1 — testo'), type: 'text' },
    { key: 'cta1_url', label: t('CTA 1 — link'), type: 'link' },
    { key: 'cta2_text', label: t('CTA 2 — testo (ghost)'), type: 'text' },
    { key: 'cta2_url', label: t('CTA 2 — link'), type: 'link' },
    { type: 'separator', label: t('Scena destra') },
    { key: 'scene', label: t('Scena'), type: 'select', options: [
      { value: 'wall', label: t('Muro di mattoni + contatore (build)') },
      { value: 'clock', label: t('Orologio mosso dallo scroll (booking)') },
      { value: 'console', label: t('Console translator (lang)') },
      { value: 'term', label: t('Terminale boot (security)') },
      { value: 'porthole', label: t('Oblò 360° (tour)') },
      { value: 'medal', label: t('Medaglia livello (tutor)') },
      { value: 'none', label: t('Nessuna') },
    ] },
    { key: 'wall_count', label: t('Contatore finale'), type: 'number',
      condition: { field: 'scene', op: 'eq', value: 'wall' } },
    { key: 'wall_label', label: t('Etichetta contatore'), type: 'text',
      condition: { field: 'scene', op: 'eq', value: 'wall' } },
    { key: 'clock_label', label: t('Etichetta orologio'), type: 'text',
      condition: { field: 'scene', op: 'eq', value: 'clock' } },
    { key: 'console_title', label: t('Titolo console'), type: 'text',
      condition: { field: 'scene', op: 'eq', value: 'console' } },
    { key: 'console_sub', label: t('Sottotitolo console'), type: 'text',
      condition: { field: 'scene', op: 'eq', value: 'console' } },
    { key: 'console_rows', label: t('Righe console'), type: 'content-items', itemLabel: t('Riga'),
      defaults: { lc: 'EN', w: 100, pc: '' },
      itemFields: [
        { key: 'lc', label: t('Codice lingua'), type: 'text' },
        { key: 'w', label: t('Percentuale barra'), type: 'number' },
        { key: 'pc', label: t('Testo % (vuoto = auto)'), type: 'text' },
      ],
      condition: { field: 'scene', op: 'eq', value: 'console' } },
    { key: 'term_title', label: t('Titolo terminale'), type: 'text',
      condition: { field: 'scene', op: 'eq', value: 'term' } },
    { key: 'term_sub', label: t('Sottotitolo terminale'), type: 'text',
      condition: { field: 'scene', op: 'eq', value: 'term' } },
    { key: 'term_lines', label: t('Righe boot'), type: 'content-items', itemLabel: t('Riga'),
      defaults: { cls: 'ok', text: '[waf] regola caricata' },
      itemFields: [
        { key: 'cls', label: t('Tipo'), type: 'select', options: [
          { value: 'cy', label: t('Ciano (sistema)') }, { value: 'ok', label: t('Verde (ok)') }, { value: 'bad', label: t('Rosso (bloccato)') },
        ] },
        { key: 'text', label: t('Testo'), type: 'text' },
      ],
      condition: { field: 'scene', op: 'eq', value: 'term' } },
    { key: 'medal_top', label: t('Medaglia — sopra'), type: 'text',
      condition: { field: 'scene', op: 'eq', value: 'medal' } },
    { key: 'medal_big', label: t('Medaglia — numero'), type: 'text',
      condition: { field: 'scene', op: 'eq', value: 'medal' } },
    { key: 'medal_bot', label: t('Medaglia — sotto'), type: 'text',
      condition: { field: 'scene', op: 'eq', value: 'medal' } },
  ],

  styleFields: [
    oloxAccentField(),
    { key: 'bg_variant', label: t('Sfondo hero'), type: 'select', options: [
      { value: 'build', label: t('Blueprint griglia (build)') },
      { value: 'booking', label: t('Alone blu (booking)') },
      { value: 'lang', label: t('Alone magenta (lang)') },
      { value: 'secur', label: t('Alone ciano (security)') },
      { value: 'tutor', label: t('Alone verde (tutor)') },
      { value: 'none', label: t('Nessuno') },
    ] },
    { key: 'pad_top', label: t('Padding top extra (px, 0 = default)'), type: 'number' },
  ],
};
