import { t } from '@/i18n';

/**
 * OLOX Home — la home "Experience" di olotheme.com: one-page a scorrimento
 * orizzontale con 8 fermate (intro + 6 pannelli prodotto con minigioco +
 * finale mad-lib), chrome fisso (logo, jump dots, progress, hint, alone),
 * modale "olonica". I minigiochi vivono in assets/js/olox.js (solo frontend).
 * Render Vue (anteprima statica scorrevole) / PHP (esperienza completa).
 */
export default {
  type: 'oloxhome',
  name: t('OLOX — Home Experience (rail + giochi)'),
  icon: 'dashicons-games',
  category: 'marketing',

  defaults: {
    logo: '',
    langs: [
      { code: 'IT', url: '/', active: true },
      { code: 'EN', url: '#', active: false },
      { code: 'FR', url: '#', active: false },
      { code: 'DE', url: '#', active: false },
      { code: 'ES', url: '#', active: false },
    ],
    intro_kicker: 'OLOtheme · suite WordPress',
    olw_text: 'olonica',
    intro_title: 'Un telaio. Sei prodotti. <em>Nessuna catena.</em>',
    intro_sub: 'Niente SaaS, niente lock-in, niente cloud altrui: tutto vive <strong>sul tuo hosting</strong>, in GPL, scritto a Trento. Scorri: ogni fermata è un prodotto.',
    intro_cta1: 'Inizia il viaggio →',
    intro_cta2: 'Contatti',
    marquee_items: [
      { text: 'no SaaS' }, { text: 'GPL' }, { text: '187 tile' }, { text: '28 lingue' },
      { text: '6 verticali booking' }, { text: '100% locale' }, { text: 'made in Trento' },
    ],
    op_kicker: 'olos · intero e parte',
    op_title: 'La cellula <em>olonica</em>',
    op_p1: 'Un <strong>olone</strong> è qualcosa che è insieme <strong>un tutto e una parte</strong>: completo da solo, più forte dentro un organismo.',
    op_p2: 'Niente monolite: <strong>i prodotti si uniscono a seconda della battaglia</strong> da affrontare.',
    battles: [
      { q: 'Aprire un B&B', chips: 'build,booking,lang' },
      { q: 'Respingere un attacco', chips: 'secur' },
    ],
    panels: [
      { color: 'build', label: 'OLObuild', logo: '', kicker: 'Il telaio · page builder', title_html: 'Costruisce come un <em>cantiere</em>', sub_html: 'Mattone su mattone…', tags: '€0 free · 100+ tile|36 animazioni', cta_text: 'Entra nel cantiere', cta_url: 'olobuild', scene: 'wall', coord: 'grid · 44×44 · lot 187' },
    ],
    outro_kicker: 'Capolinea · si scende',
    outro_title: 'Tutto questo, <em>sul tuo hosting</em>',
    outro_sub: 'GPL · niente SaaS · GDPR in casa.',
    outro_fine: 'OLOtheme · made in Trento · no SaaS · nessuna catena',
    mad_doc: 'modulo · OLO-CNT-07',
    mad_line: 'linea diretta · Trento',
    mad_intro: 'Ciao, mi chiamo',
    mad_nome_ph: 'nome e cognome',
    mad_mid: 'e il mio sito sogna di diventare',
    mad_picks: [
      { label: 'cantiere', value: 'un cantiere', color: 'build' },
      { label: 'agenda piena', value: 'un’agenda piena', color: 'booking' },
    ],
    mad_pre_mail: 'Scrivetemi a',
    mad_mail_ph: 'nome@dominio.it',
    mad_end: ', promesso, niente catene.',
    mad_btn: 'Timbra e invia ▾',
    mad_note: 'il timbro apre la tua mail già compilata',
    mad_stamp: 'Ricevuto ◦ OLOtheme',
    mad_mailto: 'info@olotheme.com',
    hint_desktop: 'Scrolla in basso',
    hint_desktop2: 'si va a destra',
    hint_mobile: 'Scorri',
    hint_mobile2: 'una fermata alla volta',
    credits_html: 'OLOtheme by <a href="https://clod.eu" target="_blank" rel="noopener">clod.eu</a> | @2026 | sito introduttivo | <a href="mailto:info@olotheme.com">info@olotheme.com</a>',
  },

  fields: [
    { type: 'separator', label: t('Chrome') },
    { key: 'logo', label: t('Logo (reso bianco)'), type: 'image' },
    { key: 'langs', label: t('Lingue'), type: 'content-items', itemLabel: t('Lingua'),
      defaults: { code: 'EN', url: '#', active: false },
      itemFields: [
        { key: 'code', label: t('Codice'), type: 'text' },
        { key: 'url', label: t('Link (# = non ancora attiva)'), type: 'link' },
        { key: 'active', label: t('Lingua corrente'), type: 'toggle' },
      ] },
    { key: 'credits_html', label: t('Credits fissi (HTML)'), type: 'textarea' },
    { type: 'separator', label: t('Intro (fermata 0)') },
    { key: 'intro_kicker', label: t('Kicker (prima della parola lampeggiante)'), type: 'text' },
    { key: 'olw_text', label: t('Parola lampeggiante (apre la modale)'), type: 'text' },
    { key: 'intro_title', label: t('Titolo gigante (HTML)'), type: 'textarea' },
    { key: 'intro_sub', label: t('Sottotitolo (HTML)'), type: 'textarea' },
    { key: 'intro_cta1', label: t('CTA 1 (→ fermata 1)'), type: 'text' },
    { key: 'intro_cta2', label: t('CTA 2 (→ finale)'), type: 'text' },
    { key: 'marquee_items', label: t('Marquee in basso'), type: 'content-items', itemLabel: t('Voce'),
      defaults: { text: 'voce' },
      itemFields: [ { key: 'text', label: t('Testo'), type: 'text' } ] },
    { type: 'separator', label: t('Modale "olonica"') },
    { key: 'op_kicker', label: t('Kicker'), type: 'text' },
    { key: 'op_title', label: t('Titolo (HTML)'), type: 'text' },
    { key: 'op_p1', label: t('Paragrafo 1 (HTML)'), type: 'textarea' },
    { key: 'op_p2', label: t('Paragrafo 2 (HTML)'), type: 'textarea' },
    { key: 'battles', label: t('Battaglie'), type: 'content-items', itemLabel: t('Battaglia'),
      defaults: { q: 'Obiettivo', chips: 'build,lang' },
      itemFields: [
        { key: 'q', label: t('Obiettivo'), type: 'text' },
        { key: 'chips', label: t('Prodotti (chiavi CSV: build,booking,lang,secur,tour,tutor)'), type: 'text' },
      ] },
    { type: 'separator', label: t('Fermate prodotto') },
    { key: 'panels', label: t('Pannelli'), type: 'content-items', itemLabel: t('Pannello'),
      defaults: { color: 'build', label: 'OLOprodotto', logo: '', kicker: 'Kicker', title_html: 'Titolo <em>em</em>', sub_html: 'Sottotitolo…', tags: 'tag 1|tag 2', cta_text: 'CTA', cta_url: '#', scene: 'wall', coord: 'coordinate · deco' },
      itemFields: [
        { key: 'label', label: t('Nome (jump/outro)'), type: 'text' },
        { key: 'color', label: t('Colore'), type: 'select', options: [
          { value: 'build', label: 'build' }, { value: 'booking', label: 'booking' },
          { value: 'lang', label: 'lang' }, { value: 'secur', label: 'security' },
          { value: 'tour', label: 'tour' }, { value: 'tutor', label: 'tutor' },
        ] },
        { key: 'logo', label: t('Logo prodotto'), type: 'image' },
        { key: 'kicker', label: t('Kicker'), type: 'text' },
        { key: 'title_html', label: t('Titolo (HTML)'), type: 'text' },
        { key: 'sub_html', label: t('Sottotitolo (HTML)'), type: 'textarea' },
        { key: 'tags', label: t('Tag (separati da |, il 1° è hot)'), type: 'text' },
        { key: 'cta_text', label: t('CTA — testo'), type: 'text' },
        { key: 'cta_url', label: t('CTA — link'), type: 'link' },
        { key: 'scene', label: t('Scena-minigioco'), type: 'select', options: [
          { value: 'wall', label: t('Forza-4 del cantiere (build)') },
          { value: 'cal', label: t('Acchiappa imprevisti (booking)') },
          { value: 'lang', label: t('Indovina la lingua (lang)') },
          { value: 'radar', label: t('Radar di difesa (security)') },
          { value: 'pano', label: t('Oblò 360° con indovinelli (tour)') },
          { value: 'course', label: t('Quiz a trascinamento + XP (tutor)') },
        ] },
        { key: 'coord', label: t('Coordinate deco (testo tecnico)'), type: 'text' },
      ] },
    { type: 'separator', label: t('Finale (mad-lib)') },
    { key: 'outro_kicker', label: t('Kicker'), type: 'text' },
    { key: 'outro_title', label: t('Titolo (HTML)'), type: 'text' },
    { key: 'outro_sub', label: t('Sottotitolo (HTML)'), type: 'textarea' },
    { key: 'outro_fine', label: t('Riga finale'), type: 'text' },
    { key: 'mad_doc', label: t('Etichetta modulo'), type: 'text' },
    { key: 'mad_line', label: t('Etichetta destra'), type: 'text' },
    { key: 'mad_intro', label: t('Testo prima del nome'), type: 'text' },
    { key: 'mad_nome_ph', label: t('Placeholder nome'), type: 'text' },
    { key: 'mad_mid', label: t('Testo prima dei sogni'), type: 'text' },
    { key: 'mad_picks', label: t('Sogni cliccabili'), type: 'content-items', itemLabel: t('Sogno'),
      defaults: { label: 'sogno', value: 'un sogno', color: 'build' },
      itemFields: [
        { key: 'label', label: t('Etichetta bottone'), type: 'text' },
        { key: 'value', label: t('Testo nella mail'), type: 'text' },
        { key: 'color', label: t('Colore'), type: 'select', options: [
          { value: 'build', label: 'build' }, { value: 'booking', label: 'booking' },
          { value: 'lang', label: 'lang' }, { value: 'secur', label: 'security' },
          { value: 'tour', label: 'tour' }, { value: 'tutor', label: 'tutor' },
        ] },
      ] },
    { key: 'mad_pre_mail', label: t('Testo prima della mail'), type: 'text' },
    { key: 'mad_mail_ph', label: t('Placeholder mail'), type: 'text' },
    { key: 'mad_end', label: t('Testo finale'), type: 'text' },
    { key: 'mad_btn', label: t('Bottone timbro'), type: 'text' },
    { key: 'mad_note', label: t('Nota sotto il bottone'), type: 'text' },
    { key: 'mad_stamp', label: t('Testo timbro'), type: 'text' },
    { key: 'mad_mailto', label: t('Email destinataria'), type: 'text' },
    { type: 'separator', label: t('Hint scroll') },
    { key: 'hint_desktop', label: t('Hint desktop — prima parte'), type: 'text' },
    { key: 'hint_desktop2', label: t('Hint desktop — seconda parte'), type: 'text' },
    { key: 'hint_mobile', label: t('Hint mobile — prima parte'), type: 'text' },
    { key: 'hint_mobile2', label: t('Hint mobile — seconda parte'), type: 'text' },
  ],

  styleFields: [],
};
