import { t } from '@/i18n';

/**
 * OLOX Scena minigioco — l'unico pezzo custom della Home Experience "vera
 * olobuild": una scena interattiva da mettere in una colonna di una sezione
 * normale. Il resto della fermata si compone con tile classiche (Titolo,
 * Testo, Pulsante, Badge, Immagine…) e lo scorrimento orizzontale lo fa la
 * sezione nativa (Stile → Sticky → "Cover orizzontale").
 * Render Vue == PHP (OloxSceneTile.vue / class-oloxscene-tile.php).
 */
export default {
  type: 'oloxscene',
  name: t('OLOX — Scena minigioco'),
  icon: 'dashicons-games',
  category: 'interactive',

  defaults: {
    scene: 'wall',
    color: 'build',
    coord: 'grid · 44×44 · lot 187',
    show_deco: true,
    // Scene showcase hero-* (fonte unica: tile oloxhero)
    wall_count: 187,
    wall_label: 'tile / 187',
    clock_label: 'lo scroll muove le lancette',
    console_title: 'translator',
    console_sub: '· dashboard · batch in corso',
    console_rows: [
      { lc: 'EN', w: 100 }, { lc: 'DE', w: 100 }, { lc: 'FR', w: 96 },
      { lc: 'ES', w: 92 }, { lc: 'PT', w: 84 }, { lc: 'NL', w: 78 },
      { lc: 'JA', w: 64 }, { lc: '+21', w: 52, pc: '…' },
    ],
    term_title: 'sentinel',
    term_sub: '· boot sequence',
    term_lines: [],
    medal_top: 'livello',
    medal_big: '1',
    medal_bot: 'studente',
    mad_doc: 'modulo · OLO-CNT-07',
    mad_line: 'linea diretta · Trento',
    mad_intro: 'Ciao, mi chiamo',
    mad_nome_ph: 'nome e cognome',
    mad_mid: 'e il mio sito sogna di diventare',
    mad_picks: [
      { label: 'cantiere', value: 'un cantiere', color: 'build' },
      { label: 'agenda piena', value: 'un’agenda piena', color: 'booking' },
      { label: 'poliglotta', value: 'poliglotta', color: 'lang' },
      { label: 'fortezza', value: 'una fortezza', color: 'secur' },
      { label: 'tour 360°', value: 'un tour 360°', color: 'tour' },
      { label: 'aula', value: 'un’aula', color: 'tutor' },
    ],
    mad_pre_mail: 'Scrivetemi a',
    mad_mail_ph: 'nome@dominio.it',
    mad_end: ', promesso, niente catene.',
    mad_btn: 'Timbra e invia ▾',
    mad_note: 'il timbro apre la tua mail già compilata',
    mad_stamp: 'Ricevuto ◦ OLOtheme',
    mad_mailto: 'info@olotheme.com',
  },

  fields: [
    { key: 'scene', label: t('Scena'), type: 'select', options: [
      { value: 'wall', label: t('Forza-4 del cantiere (build)') },
      { value: 'cal', label: t('Acchiappa imprevisti (booking)') },
      { value: 'lang', label: t('Indovina la lingua (lang)') },
      { value: 'radar', label: t('Radar di difesa (security)') },
      { value: 'pano', label: t('Oblò 360° con indovinelli (tour)') },
      { value: 'course', label: t('Quiz a trascinamento + XP (tutor)') },
      { value: 'madlib', label: t('Modulo mad-lib (contatti)') },
      { value: 'hero-wall', label: t('Showcase: griglia cantiere (build)') },
      { value: 'hero-clock', label: t('Showcase: orologio (booking)') },
      { value: 'hero-console', label: t('Showcase: console traduzioni (lang)') },
      { value: 'hero-term', label: t('Showcase: terminale sentinel (security)') },
      { value: 'hero-porthole', label: t('Showcase: oblò panoramico (tour)') },
      { value: 'hero-medal', label: t('Showcase: medaglia livello (tutor)') },
    ] },
    { key: 'color', label: t('Colore accento'), type: 'select', options: [
      { value: 'build', label: 'build' }, { value: 'booking', label: 'booking' },
      { value: 'lang', label: 'lang' }, { value: 'secur', label: 'security' },
      { value: 'tour', label: 'tour' }, { value: 'tutor', label: 'tutor' },
      { value: 'olo', label: t('rosso OLO') },
    ] },
    { key: 'coord', label: t('Coordinate deco (testo tecnico)'), type: 'text',
      condition: { field: 'scene', op: '!=', value: 'madlib' } },
    { key: 'show_deco', label: t('Decorazioni vettoriali'), type: 'toggle',
      condition: { field: 'scene', op: '!=', value: 'madlib' } },

    { type: 'separator', label: t('Mad-lib') },
    { key: 'mad_doc', label: t('Etichetta modulo'), type: 'text',
      condition: { field: 'scene', op: 'eq', value: 'madlib' } },
    { key: 'mad_line', label: t('Etichetta destra'), type: 'text',
      condition: { field: 'scene', op: 'eq', value: 'madlib' } },
    { key: 'mad_intro', label: t('Testo prima del nome'), type: 'text',
      condition: { field: 'scene', op: 'eq', value: 'madlib' } },
    { key: 'mad_nome_ph', label: t('Placeholder nome'), type: 'text',
      condition: { field: 'scene', op: 'eq', value: 'madlib' } },
    { key: 'mad_mid', label: t('Testo prima dei sogni'), type: 'text',
      condition: { field: 'scene', op: 'eq', value: 'madlib' } },
    { key: 'mad_picks', label: t('Sogni cliccabili'), type: 'content-items', itemLabel: t('Sogno'),
      defaults: { label: 'sogno', value: 'un sogno', color: 'build' },
      itemFields: [
        { key: 'label', label: t('Etichetta'), type: 'text' },
        { key: 'value', label: t('Testo nella mail'), type: 'text' },
        { key: 'color', label: t('Colore'), type: 'select', options: [
          { value: 'build', label: 'build' }, { value: 'booking', label: 'booking' },
          { value: 'lang', label: 'lang' }, { value: 'secur', label: 'security' },
          { value: 'tour', label: 'tour' }, { value: 'tutor', label: 'tutor' },
        ] },
      ],
      condition: { field: 'scene', op: 'eq', value: 'madlib' } },
    { key: 'mad_pre_mail', label: t('Testo prima della mail'), type: 'text',
      condition: { field: 'scene', op: 'eq', value: 'madlib' } },
    { key: 'mad_mail_ph', label: t('Placeholder mail'), type: 'text',
      condition: { field: 'scene', op: 'eq', value: 'madlib' } },
    { key: 'mad_end', label: t('Testo finale'), type: 'text',
      condition: { field: 'scene', op: 'eq', value: 'madlib' } },
    { key: 'mad_btn', label: t('Bottone timbro'), type: 'text',
      condition: { field: 'scene', op: 'eq', value: 'madlib' } },
    { key: 'mad_note', label: t('Nota sotto il bottone'), type: 'text',
      condition: { field: 'scene', op: 'eq', value: 'madlib' } },
    { key: 'mad_stamp', label: t('Testo timbro'), type: 'text',
      condition: { field: 'scene', op: 'eq', value: 'madlib' } },
    { key: 'mad_mailto', label: t('Email destinataria'), type: 'text',
      condition: { field: 'scene', op: 'eq', value: 'madlib' } },

    { type: 'separator', label: t('Showcase') },
    { key: 'wall_count', label: t('Contatore griglia'), type: 'number',
      condition: { field: 'scene', op: 'eq', value: 'hero-wall' } },
    { key: 'wall_label', label: t('Etichetta contatore'), type: 'text',
      condition: { field: 'scene', op: 'eq', value: 'hero-wall' } },
    { key: 'clock_label', label: t('Etichetta orologio'), type: 'text',
      condition: { field: 'scene', op: 'eq', value: 'hero-clock' } },
    { key: 'console_title', label: t('Titolo console'), type: 'text',
      condition: { field: 'scene', op: 'eq', value: 'hero-console' } },
    { key: 'console_sub', label: t('Sottotitolo console'), type: 'text',
      condition: { field: 'scene', op: 'eq', value: 'hero-console' } },
    { key: 'console_rows', label: t('Righe console'), type: 'content-items', itemLabel: t('Riga'),
      newItemDefaults: { lc: 'EN', w: 100, pc: '' },
      itemFields: [
        { key: 'lc', label: t('Etichetta'), type: 'text' },
        { key: 'w', label: t('Barra (%)'), type: 'number' },
        { key: 'pc', label: t('Testo % (vuoto = auto)'), type: 'text' },
      ],
      condition: { field: 'scene', op: 'eq', value: 'hero-console' } },
    { key: 'term_title', label: t('Titolo terminale'), type: 'text',
      condition: { field: 'scene', op: 'eq', value: 'hero-term' } },
    { key: 'term_sub', label: t('Sottotitolo terminale'), type: 'text',
      condition: { field: 'scene', op: 'eq', value: 'hero-term' } },
    { key: 'term_lines', label: t('Righe terminale'), type: 'content-items', itemLabel: t('Riga'),
      newItemDefaults: { cls: 'cy', text: '' },
      itemFields: [
        { key: 'cls', label: t('Tipo'), type: 'select', options: [
          { value: 'cy', label: t('Info (ciano)') },
          { value: 'ok', label: t('OK (verde)') },
          { value: 'bad', label: t('Bloccato (rosso)') },
        ] },
        { key: 'text', label: t('Testo'), type: 'text' },
      ],
      condition: { field: 'scene', op: 'eq', value: 'hero-term' } },
    { key: 'medal_top', label: t('Testo sopra'), type: 'text',
      condition: { field: 'scene', op: 'eq', value: 'hero-medal' } },
    { key: 'medal_big', label: t('Numero grande'), type: 'text',
      condition: { field: 'scene', op: 'eq', value: 'hero-medal' } },
    { key: 'medal_bot', label: t('Testo sotto'), type: 'text',
      condition: { field: 'scene', op: 'eq', value: 'hero-medal' } },
  ],

  styleFields: [],
};
