import { t } from '@/i18n';

/**
 * OLOX Panel — UNA fermata della Home Experience, da usare una per sezione:
 * la home "vera olobuild" è composta da tante sezioni (intro, un prodotto per
 * pannello con minigioco, finale mad-lib); la tile OLOX Rail le raccoglie a
 * runtime nel binario orizzontale e le numera automaticamente.
 * Render Vue == PHP (OloxPanelTile.vue / class-oloxpanel-tile.php).
 */
export default {
  type: 'oloxpanel',
  name: t('OLOX — Fermata Experience (pannello)'),
  icon: 'dashicons-slides',
  category: 'marketing',

  defaults: {
    variant: 'product',
    label: 'OLObuild',
    intro_kicker: 'OLOtheme · suite WordPress',
    olw_text: 'olonica',
    intro_title: 'Un telaio. Sei prodotti. <em>Nessuna catena.</em>',
    intro_sub: 'Niente SaaS, niente lock-in, niente cloud altrui: tutto vive <strong>sul tuo hosting</strong>, in GPL, scritto a Trento.',
    intro_cta1: 'Inizia il viaggio →',
    intro_cta2: 'Contatti',
    marquee_items: [
      { text: 'no SaaS' }, { text: 'GPL' }, { text: '187 tile' }, { text: '28 lingue' },
      { text: '6 verticali booking' }, { text: '100% locale' }, { text: 'made in Trento' },
    ],
    color: 'build',
    logo: '',
    kicker: 'Il telaio · page builder',
    title_html: 'Costruisce come un <em>cantiere</em>',
    sub_html: 'Mattone su mattone: <strong>187 tile in 12 famiglie</strong>.',
    tags: '€0 free · 100+ tile|36 animazioni|Woo nativo|dark mode',
    cta_text: 'Entra nel cantiere',
    cta_url: '/olobuild/',
    scene: 'wall',
    coord: 'grid · 44×44 · lot 187',
    outro_kicker: 'Capolinea · si scende',
    outro_title: 'Tutto questo, <em>sul tuo hosting</em>',
    outro_sub: 'GPL · niente SaaS · GDPR in casa.',
    outro_links: [
      { label: 'OLObuild', url: '/olobuild/', color: 'build' },
      { label: 'OLObooking', url: '/olobooking/', color: 'booking' },
      { label: 'OLOlang', url: '/ololang/', color: 'lang' },
      { label: 'OLOsecurity', url: '/olosecurity/', color: 'secur' },
      { label: 'OLOtour', url: '/olotour/', color: 'tour' },
      { label: 'OLOtutor', url: '/olotutor/', color: 'tutor' },
    ],
    outro_fine: 'OLOtheme · made in Trento · no SaaS · nessuna catena',
    mad_doc: 'modulo · OLO-CNT-07',
    mad_line: 'linea diretta · Trento',
    mad_intro: 'Ciao, mi chiamo',
    mad_nome_ph: 'nome e cognome',
    mad_mid: 'e il mio sito sogna di diventare',
    mad_picks: [
      { label: 'cantiere', value: 'un cantiere', color: 'build' },
      { label: 'agenda piena', value: 'un’agenda piena', color: 'booking' },
      { label: 'poliglotta', value: 'poliglotta', color: 'lang' },
      { label: 'fortezza', value: 'una fortezza', color: 'secur' },
      { label: 'tour 360°', value: 'un tour 360°', color: 'tour' },
      { label: 'aula', value: 'un’aula', color: 'tutor' },
    ],
    mad_pre_mail: 'Scrivetemi a',
    mad_mail_ph: 'nome@dominio.it',
    mad_end: ', promesso, niente catene.',
    mad_btn: 'Timbra e invia ▾',
    mad_note: 'il timbro apre la tua mail già compilata',
    mad_stamp: 'Ricevuto ◦ OLOtheme',
    mad_mailto: 'info@olotheme.com',
  },

  fields: [
    { key: 'variant', label: t('Tipo di fermata'), type: 'select', options: [
      { value: 'intro', label: t('Intro (fermata 0)') },
      { value: 'product', label: t('Prodotto con minigioco') },
      { value: 'outro', label: t('Finale (mad-lib)') },
    ] },
    { key: 'label', label: t('Nome fermata (jump/tooltip)'), type: 'text' },

    { type: 'separator', label: t('Intro') },
    { key: 'intro_kicker', label: t('Kicker'), type: 'text',
      condition: { field: 'variant', op: 'eq', value: 'intro' } },
    { key: 'olw_text', label: t('Parola lampeggiante (apre la modale)'), type: 'text',
      condition: { field: 'variant', op: 'eq', value: 'intro' } },
    { key: 'intro_title', label: t('Titolo gigante (HTML)'), type: 'textarea',
      condition: { field: 'variant', op: 'eq', value: 'intro' } },
    { key: 'intro_sub', label: t('Sottotitolo (HTML)'), type: 'textarea',
      condition: { field: 'variant', op: 'eq', value: 'intro' } },
    { key: 'intro_cta1', label: t('CTA 1 (→ fermata 1)'), type: 'text',
      condition: { field: 'variant', op: 'eq', value: 'intro' } },
    { key: 'intro_cta2', label: t('CTA 2 (→ finale)'), type: 'text',
      condition: { field: 'variant', op: 'eq', value: 'intro' } },
    { key: 'marquee_items', label: t('Marquee in basso'), type: 'content-items', itemLabel: t('Voce'),
      defaults: { text: 'voce' },
      itemFields: [ { key: 'text', label: t('Testo'), type: 'text' } ],
      condition: { field: 'variant', op: 'eq', value: 'intro' } },

    { type: 'separator', label: t('Prodotto') },
    { key: 'color', label: t('Colore'), type: 'select', options: [
      { value: 'build', label: 'build' }, { value: 'booking', label: 'booking' },
      { value: 'lang', label: 'lang' }, { value: 'secur', label: 'security' },
      { value: 'tour', label: 'tour' }, { value: 'tutor', label: 'tutor' },
    ], condition: { field: 'variant', op: 'eq', value: 'product' } },
    { key: 'logo', label: t('Logo prodotto'), type: 'image',
      condition: { field: 'variant', op: 'eq', value: 'product' } },
    { key: 'kicker', label: t('Kicker'), type: 'text',
      condition: { field: 'variant', op: 'eq', value: 'product' } },
    { key: 'title_html', label: t('Titolo (HTML)'), type: 'text',
      condition: { field: 'variant', op: 'eq', value: 'product' } },
    { key: 'sub_html', label: t('Sottotitolo (HTML)'), type: 'textarea',
      condition: { field: 'variant', op: 'eq', value: 'product' } },
    { key: 'tags', label: t('Tag (separati da |, il 1° è hot)'), type: 'text',
      condition: { field: 'variant', op: 'eq', value: 'product' } },
    { key: 'cta_text', label: t('CTA — testo'), type: 'text',
      condition: { field: 'variant', op: 'eq', value: 'product' } },
    { key: 'cta_url', label: t('CTA — link'), type: 'link',
      condition: { field: 'variant', op: 'eq', value: 'product' } },
    { key: 'scene', label: t('Scena-minigioco'), type: 'select', options: [
      { value: 'wall', label: t('Forza-4 del cantiere (build)') },
      { value: 'cal', label: t('Acchiappa imprevisti (booking)') },
      { value: 'lang', label: t('Indovina la lingua (lang)') },
      { value: 'radar', label: t('Radar di difesa (security)') },
      { value: 'pano', label: t('Oblò 360° con indovinelli (tour)') },
      { value: 'course', label: t('Quiz a trascinamento + XP (tutor)') },
    ], condition: { field: 'variant', op: 'eq', value: 'product' } },
    { key: 'coord', label: t('Coordinate deco (testo tecnico)'), type: 'text',
      condition: { field: 'variant', op: 'eq', value: 'product' } },

    { type: 'separator', label: t('Finale') },
    { key: 'outro_kicker', label: t('Kicker'), type: 'text',
      condition: { field: 'variant', op: 'eq', value: 'outro' } },
    { key: 'outro_title', label: t('Titolo (HTML)'), type: 'text',
      condition: { field: 'variant', op: 'eq', value: 'outro' } },
    { key: 'outro_sub', label: t('Sottotitolo (HTML)'), type: 'textarea',
      condition: { field: 'variant', op: 'eq', value: 'outro' } },
    { key: 'outro_links', label: t('Link alle fermate'), type: 'content-items', itemLabel: t('Link'),
      defaults: { label: 'OLOprodotto', url: '#', color: 'build' },
      itemFields: [
        { key: 'label', label: t('Etichetta'), type: 'text' },
        { key: 'url', label: t('Link'), type: 'link' },
        { key: 'color', label: t('Colore'), type: 'select', options: [
          { value: 'build', label: 'build' }, { value: 'booking', label: 'booking' },
          { value: 'lang', label: 'lang' }, { value: 'secur', label: 'security' },
          { value: 'tour', label: 'tour' }, { value: 'tutor', label: 'tutor' },
        ] },
      ],
      condition: { field: 'variant', op: 'eq', value: 'outro' } },
    { key: 'outro_fine', label: t('Riga finale'), type: 'text',
      condition: { field: 'variant', op: 'eq', value: 'outro' } },
    { key: 'mad_doc', label: t('Etichetta modulo'), type: 'text',
      condition: { field: 'variant', op: 'eq', value: 'outro' } },
    { key: 'mad_line', label: t('Etichetta destra'), type: 'text',
      condition: { field: 'variant', op: 'eq', value: 'outro' } },
    { key: 'mad_intro', label: t('Testo prima del nome'), type: 'text',
      condition: { field: 'variant', op: 'eq', value: 'outro' } },
    { key: 'mad_nome_ph', label: t('Placeholder nome'), type: 'text',
      condition: { field: 'variant', op: 'eq', value: 'outro' } },
    { key: 'mad_mid', label: t('Testo prima dei sogni'), type: 'text',
      condition: { field: 'variant', op: 'eq', value: 'outro' } },
    { key: 'mad_picks', label: t('Sogni cliccabili'), type: 'content-items', itemLabel: t('Sogno'),
      defaults: { label: 'sogno', value: 'un sogno', color: 'build' },
      itemFields: [
        { key: 'label', label: t('Etichetta'), type: 'text' },
        { key: 'value', label: t('Testo nella mail'), type: 'text' },
        { key: 'color', label: t('Colore'), type: 'select', options: [
          { value: 'build', label: 'build' }, { value: 'booking', label: 'booking' },
          { value: 'lang', label: 'lang' }, { value: 'secur', label: 'security' },
          { value: 'tour', label: 'tour' }, { value: 'tutor', label: 'tutor' },
        ] },
      ],
      condition: { field: 'variant', op: 'eq', value: 'outro' } },
    { key: 'mad_pre_mail', label: t('Testo prima della mail'), type: 'text',
      condition: { field: 'variant', op: 'eq', value: 'outro' } },
    { key: 'mad_mail_ph', label: t('Placeholder mail'), type: 'text',
      condition: { field: 'variant', op: 'eq', value: 'outro' } },
    { key: 'mad_end', label: t('Testo finale'), type: 'text',
      condition: { field: 'variant', op: 'eq', value: 'outro' } },
    { key: 'mad_btn', label: t('Bottone timbro'), type: 'text',
      condition: { field: 'variant', op: 'eq', value: 'outro' } },
    { key: 'mad_note', label: t('Nota sotto il bottone'), type: 'text',
      condition: { field: 'variant', op: 'eq', value: 'outro' } },
    { key: 'mad_stamp', label: t('Testo timbro'), type: 'text',
      condition: { field: 'variant', op: 'eq', value: 'outro' } },
    { key: 'mad_mailto', label: t('Email destinataria'), type: 'text',
      condition: { field: 'variant', op: 'eq', value: 'outro' } },
  ],

  styleFields: [],
};
