import { textEffectsFields, textEffectsDefaults } from './_shared';
import { shadowField } from './_shared.js';

export default {
  type: 'overlaygrid',
  name: 'Overlay Grid',
  icon: 'dashicons-grid-view',
  category: 'interactive',
  defaults: {
    items: [
      { id: 'og-1', image: '', title: 'Elemento 1', subtitle: '', link: '' },
      { id: 'og-2', image: '', title: 'Elemento 2', subtitle: '', link: '' },
      { id: 'og-3', image: '', title: 'Elemento 3', subtitle: '', link: '' },
    ],
    columns: '3',
    columns_mobile: '1',
    gap: 'medium',
    height: '300',
    match_height: true,
    overlay_position: 'bottom',
    overlay_horizontal: 'left',
    overlay_style: 'overlay-primary',
    overlay_padding: 'medium',
    title_size: 'h3',
    hover_effect: 'none',
    hover_overlay: 'always',
    ribbon_position: 'top-right',
    ribbon_bg: '',
    ribbon_color: '',
    shadow: 'none',
    ...textEffectsDefaults,
  },
  fields: [
    { key: 'items', label: 'Elementi', type: 'content-items', supportsDynamic: true,
      itemFields: [
        { key: 'image', label: 'Immagine', type: 'image' },
        { key: 'hover_image', label: 'Immagine hover', type: 'image' },
        { key: 'hover_video', label: 'Video hover', type: 'media' },
        { key: 'title', label: 'Titolo', type: 'text' },
        { key: 'subtitle', label: 'Sottotitolo', type: 'text' },
        { key: 'link', label: 'Link', type: 'text', placeholder: 'https://...' },
        { key: 'ribbon', label: 'Ribbon', type: 'text' },
      ],
      newItemDefaults: { image: '', hover_image: '', hover_video: '', title: 'Nuovo elemento', subtitle: '', link: '', ribbon: '' },
      itemLabel: 'Elemento',
    },
    { type: 'separator', label: 'Griglia' },
    { key: 'columns', label: 'Colonne (desktop)', type: 'select', options: [
      { value: '1', label: '1' },
      { value: '2', label: '2' },
      { value: '3', label: '3' },
      { value: '4', label: '4' },
      { value: '5', label: '5' },
    ]},
    { key: 'columns_mobile', label: 'Colonne (mobile)', type: 'select', options: [
      { value: '1', label: '1' },
      { value: '2', label: '2' },
    ]},
    { key: 'gap', label: 'Spaziatura', type: 'select', options: [
      { value: 'collapse', label: 'Nessuna' },
      { value: 'small', label: 'Piccola' },
      { value: 'medium', label: 'Media' },
      { value: 'large', label: 'Grande' },
    ]},
    { key: 'height', label: 'Altezza (px)', type: 'range', min: 150, max: 800, step: 25 },
    { key: 'match_height', label: 'Altezza uniforme', type: 'toggle' },
    { type: 'separator', label: 'Overlay' },
    { key: 'overlay_position', label: 'Posizione', type: 'select', options: [
      { value: 'bottom', label: 'In basso' },
      { value: 'top', label: 'In alto' },
      { value: 'center', label: 'Centro' },
      { value: 'cover', label: 'Copertura' },
      { value: 'bottom-left', label: 'Basso-sinistra' },
      { value: 'bottom-center', label: 'Basso-centro' },
      { value: 'bottom-right', label: 'Basso-destra' },
      { value: 'top-left', label: 'Alto-sinistra' },
      { value: 'top-center', label: 'Alto-centro' },
      { value: 'top-right', label: 'Alto-destra' },
      { value: 'center-left', label: 'Centro-sinistra' },
      { value: 'center-right', label: 'Centro-destra' },
    ]},
    { key: 'overlay_horizontal', label: 'Allineamento testo', type: 'select', options: [
      { value: 'left', label: 'Sinistra' },
      { value: 'center', label: 'Centro' },
      { value: 'right', label: 'Destra' },
    ]},
    { key: 'overlay_style', label: 'Stile overlay', type: 'select', options: [
      { value: 'overlay-primary', label: 'Primary' },
      { value: 'overlay-default', label: 'Predefinito' },
    ]},
    { key: 'overlay_padding', label: 'Padding overlay', type: 'select', options: [
      { value: 'small', label: 'Piccolo' },
      { value: 'medium', label: 'Medio' },
      { value: 'large', label: 'Grande' },
    ]},
    { key: 'title_size', label: 'Dimensione titolo', type: 'select', options: [
      { value: 'h1', label: 'H1' },
      { value: 'h2', label: 'H2' },
      { value: 'h3', label: 'H3' },
      { value: 'h4', label: 'H4' },
    ]},
    { type: 'separator', label: 'Effetti hover' },
    { key: 'hover_effect', label: 'Effetto immagine', type: 'select', options: [
      { value: 'none', label: 'Nessuno' },
      { value: 'zoom', label: 'Zoom' },
      { value: 'zoom-rotate', label: 'Zoom + rotazione' },
      { value: 'brightness', label: 'Luminosità' },
      { value: 'desaturate', label: 'Desatura → colore' },
      { value: 'blur-in', label: 'Sfocatura → nitido' },
    ]},
    { key: 'hover_overlay', label: 'Overlay', type: 'select', options: [
      { value: 'always', label: 'Sempre visibile' },
      { value: 'fade', label: 'Fade in' },
      { value: 'slide-bottom', label: 'Scorre dal basso' },
      { value: 'slide-top', label: "Scorre dall'alto" },
      { value: 'slide-left', label: 'Scorre da sinistra' },
      { value: 'slide-right', label: 'Scorre da destra' },
    ]},
    { type: 'separator', label: 'Ribbon' },
    { key: 'ribbon_position', label: 'Posizione ribbon', type: 'select', options: [
      { value: 'top-left', label: 'Alto sinistra' },
      { value: 'top-right', label: 'Alto destra' },
    ]},
    { key: 'ribbon_bg', label: 'Sfondo ribbon', type: 'color' },
    { key: 'ribbon_color', label: 'Testo ribbon', type: 'color' },
    ...shadowField,
    ...textEffectsFields([
      { value: 'title', label: 'Solo Titolo' },
      { value: 'subtitle', label: 'Solo Sottotitolo' },
      { value: 'all', label: 'Tutti gli elementi testuali' },
    ]),
  ],
};
