import { textEffectsFields, textEffectsDefaults, borderFields, borderDefault, borderHoverDefault, borderEffectDefaults } from './_shared';
import { shadowField } from './_shared.js';

export default {
  type: 'pagetitlebar',
  name: 'Page Title Bar',
  icon: 'dashicons-format-aside',
  category: 'structure',
  defaults: {
    title_tag: 'h1',
    title_color: '#FFFFFF',
    title_size: '36',
    title_weight: '700',
    title_align: 'center',
    subtitle: '',
    subtitle_color: '#D1D5DB',
    subtitle_size: '16',
    show_breadcrumbs: true,
    breadcrumb_color: '#9CA3AF',
    breadcrumb_separator: '/',
    bg_color: '',
    bg_image: '',
    bg_overlay: '60',
    bg_overlay_color: '#000000',
    bg_size: 'cover',
    bg_position: 'center center',
    bg_parallax: false,
    min_height: '200',
    tile_padding: { top: 40, right: 0, bottom: 40, left: 0 },
    content_width: '1200',
    border_bottom: false,
    border_color: '#374151',
    shadow: 'none',
    ...textEffectsDefaults,
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
  },
  fields: [
    { key: 'title_tag', label: 'Tag titolo', type: 'select', options: { h1: 'H1', h2: 'H2', h3: 'H3', h4: 'H4', div: 'DIV' } },
    { key: 'title_color', label: 'Colore titolo', type: 'color' },
    { key: 'title_size', label: 'Dimensione titolo (px)', type: 'range', min: 14, max: 80 },
    { key: 'title_weight', label: 'Peso titolo', type: 'select', options: { '300': 'Light', '400': 'Normal', '600': 'Semi-bold', '700': 'Bold', '800': 'Extra-bold' } },
    { key: 'title_align', label: 'Allineamento', type: 'select', options: { left: 'Sinistra', center: 'Centro', right: 'Destra' } },
    { key: 'subtitle', label: 'Sottotitolo', type: 'text' },
    { key: 'subtitle_color', label: 'Colore sottotitolo', type: 'color' },
    { key: 'subtitle_size', label: 'Dimensione sottotitolo (px)', type: 'range', min: 12, max: 40 },
    { key: 'show_breadcrumbs', label: 'Mostra breadcrumbs', type: 'toggle' },
    { key: 'breadcrumb_color', label: 'Colore breadcrumbs', type: 'color', show: s => s.show_breadcrumbs },
    { key: 'breadcrumb_separator', label: 'Separatore', type: 'text', show: s => s.show_breadcrumbs },
    { key: 'bg_color', label: 'Colore sfondo', type: 'color' },
    { key: 'bg_image', label: 'Immagine sfondo', type: 'media' },
    { key: 'bg_overlay', label: 'Opacita overlay (%)', type: 'range', min: 0, max: 100, show: s => !!s.bg_image },
    { key: 'bg_overlay_color', label: 'Colore overlay', type: 'color', show: s => !!s.bg_image },
    { key: 'bg_size', label: 'Dimensione sfondo', type: 'select', options: { cover: 'Cover', contain: 'Contain', auto: 'Auto' }, show: s => !!s.bg_image },
    { key: 'bg_position', label: 'Posizione sfondo', type: 'select', options: { 'center center': 'Centro', 'top center': 'Alto', 'bottom center': 'Basso', 'left center': 'Sinistra', 'right center': 'Destra' }, show: s => !!s.bg_image },
    { key: 'bg_parallax', label: 'Parallax', type: 'toggle', show: s => !!s.bg_image },
    { key: 'min_height', label: 'Altezza minima (px)', type: 'range', min: 0, max: 600, step: 10 },
    { key: 'tile_padding', label: 'Padding (px)', type: 'spacing', max: 200 },
    { key: 'content_width', label: 'Larghezza contenuto (px)', type: 'range', min: 600, max: 1600, step: 50 },
    { key: 'border_bottom', label: 'Bordo inferiore', type: 'toggle' },
    { key: 'border_color', label: 'Colore bordo', type: 'color', show: s => s.border_bottom },
    ...shadowField,
    ...textEffectsFields([ { value: 'subtitle', label: 'Solo Sottotitolo' } ]),
    ...borderFields(),
  ],
};
