import { textEffectsFields, textEffectsDefaults, shadowField, borderFields, borderDefault, borderHoverDefault, borderEffectDefaults, withHover, wowEffectsFields, wowEffectsDefaults } from './_shared.js';
import { t } from '@/i18n';

/**
 * Tile Panel — split CONTENUTO/STILE (regola universale Olobuild).
 *   fields[]      → titolo, meta, contenuto, media (image/video), link
 *   styleFields[] → preset, effect tweaks, text-effects, dimensioni media, tipografia, padding card, radius, shadow, border, bg
 *   AVANZATE      → meta tecnico
 */
export default {
  type: 'panel',
  name: t('Pannello'),
  icon: 'dashicons-id-alt',
  category: 'interactive',
  defaults: {
    typography_preset: '',
    preset: 'card-classic',
    style: 'default',
    title: t('Titolo Provvisorio'),
    meta: 'Scritto da Autore',
    content: 'Il contenuto del pannello va qui. Aggiungi testo, immagini o qualsiasi altro contenuto.',
    media_type: 'image',
    image: '',
    effect_color: '',
    effect_intensity: 'medium',
    effect_speed: 0,
    image_ratio: 'auto',
    image_height: '',
    image_fit: 'cover',
    object_position: 'center center',
    image_zoom: false,
    media_padding: { top: 0, right: 0, bottom: 0, left: 0 },
    text_align: 'left',
    title_size: '',
    title_weight: '',
    title_color: '',
    meta_size: '',
    meta_color: '',
    content_size: '',
    content_color: '',
    link_label: '',
    link_color: '',
    hover_image: '',
    hover_video: '',
    video: '',
    video_autoplay: true,
    video_loop: true,
    video_muted: true,
    video_controls: false,
    video_poster: '',
    link_url: '',
    link_target: '_self',
    title_element: 'h3',
    card_padding: { top: 20, right: 20, bottom: 20, left: 20 },
    shadow: 'none',
    border_radius: '0',
    card_radius: '0',
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
    ...wowEffectsDefaults,
    ...textEffectsDefaults,
    text_effect_target: 'all',
  },

  // ─── CONTENUTO ─────────────────────────────────────────────
  fields: [
    { key: 'title', label: t('Titolo'), type: 'text' },
    { key: 'meta', label: t('Meta'), type: 'text' },
    { key: 'content', label: t('Contenuto'), type: 'textarea' },

    { type: 'separator', label: t('Media') },
    { key: 'media_type', label: t('Tipo media'), type: 'select', options: [
      { value: 'none', label: t('Nessuno') },
      { value: 'image', label: t('Immagine') },
      { value: 'video', label: t('Video') },
    ]},
    { key: 'image', label: t('Immagine'), type: 'image',
      condition: { field: 'media_type', op: 'eq', value: 'image' } },
    { key: 'hover_image', label: t('Immagine hover'), type: 'image',
      condition: { field: 'media_type', op: 'eq', value: 'image' } },
    { key: 'hover_video', label: t('Video hover'), type: 'media',
      condition: { field: 'media_type', op: 'eq', value: 'image' } },
    { key: 'video', label: t('Video (mp4)'), type: 'media',
      condition: { field: 'media_type', op: 'eq', value: 'video' } },
    { key: 'video_poster', label: t('Poster (immagine anteprima)'), type: 'image',
      condition: { field: 'media_type', op: 'eq', value: 'video' } },
    { key: 'video_autoplay', label: t('Autoplay'), type: 'toggle',
      condition: { field: 'media_type', op: 'eq', value: 'video' } },
    { key: 'video_loop', label: t('Loop'), type: 'toggle',
      condition: { field: 'media_type', op: 'eq', value: 'video' } },
    { key: 'video_muted', label: t('Muto'), type: 'toggle',
      condition: { field: 'media_type', op: 'eq', value: 'video' } },
    { key: 'video_controls', label: t('Mostra controlli'), type: 'toggle',
      condition: { field: 'media_type', op: 'eq', value: 'video' } },

    { type: 'separator', label: t('Link') },
    { key: 'link_url', label: t('URL link'), type: 'link' },
    { key: 'link_target', label: t('Apri in'), type: 'select', options: [
      { value: '_self', label: t('Stessa finestra') },
      { value: '_blank', label: t('Nuova finestra') },
    ]},
    { key: 'link_label', label: t('Etichetta link'), type: 'text',
      description: 'Vuoto = "Read more →"',
      condition: { field: 'link_url', op: 'notEmpty' } },
  ],

  // ─── STILE ─────────────────────────────────────────────────
  styleFields: [
    { type: 'separator', label: t('Preset stile') },
    { key: 'preset', label: t('Stile'), type: 'select', options: [
      { value: 'card-classic',     label: t('Card Classic (default)') },
      { value: 'magazine',         label: t('Magazine (foto grande)') },
      { value: 'editorial',        label: t('Editorial (no bordi)') },
      { value: 'polaroid',         label: t('Polaroid (bordo bianco)') },
      { value: 'overlay-caption',  label: t('Overlay Caption (testo su foto)') },
      { value: 'liquid-glass',     label: t('Liquid Glass (Vision Pro)') },
      { value: 'neon-cyber',       label: t('Neon Cyberpunk (Tron)') },
      { value: 'brutalist-block',  label: t('Brutalist Block (neo-brutalist)') },
      { value: 'magnetic-liquid',  label: t('Magnetic Liquid (next-gen)') },
      { value: 'sticker',          label: t('Sticker / Scrapbook') },
      { value: 'retro-terminal',   label: t('Retro Terminal (CRT)') },
      { value: '3d-tilt',          label: t('3D Card Tilt') },
      { value: 'custom',           label: t('Personalizzato (usa controlli sotto)') },
    ]},
    { key: 'typography_preset', label: t('Stile tipografico'), type: 'select', optionsSource: 'globalTypography' },

    { key: 'style', label: t('Stile UIkit'), type: 'select', options: [
      { value: 'default', label: t('Predefinito') },
      { value: 'primary', label: t('Primary') },
      { value: 'secondary', label: t('Secondary') },
      { value: 'hover', label: t('Hover') },
    ]},

    { type: 'separator', label: t('Tweak effetto preset'),
      condition: { field: 'preset', op: 'in', value: ['liquid-glass','neon-cyber','brutalist-block','magnetic-liquid','sticker','retro-terminal','3d-tilt'] } },
    { key: 'effect_color', label: t('Colore effetto'), type: 'color',
      condition: { field: 'preset', op: 'in', value: ['neon-cyber','brutalist-block','magnetic-liquid','sticker','retro-terminal'] } },
    { key: 'effect_intensity', label: t('Intensità effetto'), type: 'select',
      options: [
        { value: 'low',    label: t('Bassa') },
        { value: 'medium', label: t('Media (default)') },
        { value: 'high',   label: t('Alta') },
      ],
      condition: { field: 'preset', op: 'in', value: ['liquid-glass','neon-cyber','brutalist-block','magnetic-liquid','sticker','retro-terminal','3d-tilt'] } },
    { key: 'effect_speed', label: t('Velocità animazioni (ms)'), type: 'range',
      min: 0, max: 4000, step: 100,
      condition: { field: 'preset', op: 'in', value: ['neon-cyber','magnetic-liquid','retro-terminal','3d-tilt'] } },

    ...textEffectsFields([
      { value: 'title', label: t('Solo Titolo') },
      { value: 'content', label: t('Solo Contenuto') },
      { value: 'all', label: t('Tutti gli elementi testuali') },
    ]),

    { type: 'separator', label: t('Dimensioni media') },
    { key: 'image_ratio', label: t('Proporzione'), type: 'select', options: [
      { value: 'auto', label: t('Automatica') },
      { value: '1/1', label: t('1:1 Quadrato') },
      { value: '4/3', label: t('4:3 Standard') },
      { value: '3/2', label: t('3:2 Foto') },
      { value: '16/9', label: t('16:9 Wide') },
      { value: '21/9', label: t('21:9 Cinema') },
      { value: '3/4', label: t('3:4 Verticale') },
      { value: '2/3', label: t('2:3 Verticale') },
    ], condition: { field: 'media_type', op: 'neq', value: 'none' } },
    { key: 'image_height', label: t('Altezza fissa (px)'), type: 'range', min: 0, max: 600, step: 10,
      description: t('0 = automatica'),
      condition: { field: 'media_type', op: 'neq', value: 'none' } },
    { key: 'image_fit', label: t('Adattamento'), type: 'select', options: [
      { value: 'cover', label: t('Copri (riempie e taglia)') },
      { value: 'contain', label: t('Contieni (visibile interamente)') },
      { value: 'fill', label: t('Riempi (deforma)') },
    ], condition: { field: 'media_type', op: 'neq', value: 'none' } },
    { key: 'object_position', label: t('Posizione contenuto'), type: 'object-position',
      contextKeys: { src: 'image', fit: 'image_fit', ratio: 'image_ratio' },
      condition: { field: 'media_type', op: 'neq', value: 'none' } },
    { key: 'image_zoom', label: t('Zoom al hover'), type: 'toggle',
      condition: { field: 'media_type', op: 'neq', value: 'none' } },
    { key: 'media_padding', label: t('Spazio attorno al media (px)'), type: 'spacing', max: 60,
      description: t('Aggiunge uno spazio bianco attorno al media'),
      condition: { field: 'media_type', op: 'neq', value: 'none' } },
    withHover({ key: 'border_radius', label: t('Border radius media'), type: 'border-radius',
      condition: { field: 'media_type', op: 'neq', value: 'none' } }),

    { type: 'separator', label: t('Tipografia') },
    { key: 'text_align', label: t('Allineamento testo'), type: 'select', options: [
      { value: 'left', label: t('Sinistra') },
      { value: 'center', label: t('Centro') },
      { value: 'right', label: t('Destra') },
      { value: 'justify', label: t('Giustificato') },
    ]},
    { type: 'typography', label: t('Titolo'),
      presetKey: 'typography_preset',
      responsiveKeys: ['size'],
      keys: {
        tag:    'title_element',
        size:   'title_size',
        weight: 'title_weight',
        color:  'title_color',
      },
      sizeMin: 0, sizeMax: 60, sizeStep: 1,
    },
    { type: 'typography', label: t('Meta'),
      presetKey: 'typography_preset',
      responsiveKeys: ['size'],
      keys: {
        size:  'meta_size',
        color: 'meta_color',
      },
      sizeMin: 0, sizeMax: 24, sizeStep: 1,
    },
    { type: 'typography', label: t('Contenuto'),
      presetKey: 'typography_preset',
      responsiveKeys: ['size'],
      keys: {
        size:  'content_size',
        color: 'content_color',
      },
      sizeMin: 0, sizeMax: 28, sizeStep: 1,
    },
    { type: 'typography', label: t('Link'),
      presetKey: 'typography_preset',
      keys: {
        color: 'link_color',
      },
      condition: { field: 'link_url', op: 'notEmpty' },
    },

    { type: 'separator', label: t('Stile card') },
    { key: 'card_padding', label: t('Padding interno'), type: 'spacing', max: 60 },
    withHover({ key: 'card_radius', label: t('Border radius card (px)'), type: 'border-radius'}),
    ...shadowField,
    ...wowEffectsFields(),
    ...borderFields(),
  ],
};
