import { shadowField } from './_shared.js';

export default {
  type: 'panel',
  name: 'Pannello',
  icon: 'dashicons-id-alt',
  category: 'interactive',
  defaults: {
    style: 'default',
    title: 'Titolo pannello',
    meta: 'Scritto da Autore',
    content: 'Il contenuto del pannello va qui. Aggiungi testo, immagini o qualsiasi altro contenuto.',
    media_type: 'image',
    image: '',
    image_ratio: 'auto',
    image_height: '',
    image_fit: 'cover',
    image_zoom: false,
    media_padding: { top: 0, right: 0, bottom: 0, left: 0 },
    text_align: 'left',
    title_size: '',
    title_weight: '',
    title_color: '',
    meta_size: '',
    meta_color: '',
    content_size: '',
    content_color: '',
    link_label: '',
    link_color: '',
    hover_image: '',
    hover_video: '',
    video: '',
    video_autoplay: true,
    video_loop: true,
    video_muted: true,
    video_controls: false,
    video_poster: '',
    link_url: '',
    link_target: '_self',
    title_element: 'h3',
    card_padding: { top: 20, right: 20, bottom: 20, left: 20 },
    shadow: 'none',
    border_radius: '0',
    card_radius: '0',
  },
  fields: [
    { key: 'style', label: 'Stile', type: 'select', options: [
      { value: 'default', label: 'Predefinito' },
      { value: 'primary', label: 'Primary' },
      { value: 'secondary', label: 'Secondary' },
      { value: 'hover', label: 'Hover' },
    ]},

    { type: 'separator', label: 'Media' },
    { key: 'media_type', label: 'Tipo media', type: 'select', options: [
      { value: 'none', label: 'Nessuno' },
      { value: 'image', label: 'Immagine' },
      { value: 'video', label: 'Video' },
    ]},
    { key: 'image', label: 'Immagine', type: 'image',
      condition: { field: 'media_type', op: 'eq', value: 'image' } },
    { key: 'hover_image', label: 'Immagine hover', type: 'image',
      condition: { field: 'media_type', op: 'eq', value: 'image' } },
    { key: 'hover_video', label: 'Video hover', type: 'media',
      condition: { field: 'media_type', op: 'eq', value: 'image' } },

    { key: 'video', label: 'Video (mp4)', type: 'media',
      condition: { field: 'media_type', op: 'eq', value: 'video' } },
    { key: 'video_poster', label: 'Poster (immagine anteprima)', type: 'image',
      condition: { field: 'media_type', op: 'eq', value: 'video' } },
    { key: 'video_autoplay', label: 'Autoplay', type: 'toggle',
      condition: { field: 'media_type', op: 'eq', value: 'video' } },
    { key: 'video_loop', label: 'Loop', type: 'toggle',
      condition: { field: 'media_type', op: 'eq', value: 'video' } },
    { key: 'video_muted', label: 'Muto', type: 'toggle',
      condition: { field: 'media_type', op: 'eq', value: 'video' } },
    { key: 'video_controls', label: 'Mostra controlli', type: 'toggle',
      condition: { field: 'media_type', op: 'eq', value: 'video' } },

    { type: 'separator', label: 'Dimensioni media' },
    { key: 'image_ratio', label: 'Proporzione', type: 'select', options: [
      { value: 'auto', label: 'Automatica' },
      { value: '1/1', label: '1:1 Quadrato' },
      { value: '4/3', label: '4:3 Standard' },
      { value: '3/2', label: '3:2 Foto' },
      { value: '16/9', label: '16:9 Wide' },
      { value: '21/9', label: '21:9 Cinema' },
      { value: '3/4', label: '3:4 Verticale' },
      { value: '2/3', label: '2:3 Verticale' },
    ], condition: { field: 'media_type', op: 'neq', value: 'none' } },
    { key: 'image_height', label: 'Altezza fissa (px)', type: 'range', min: 0, max: 600, step: 10,
      description: '0 = automatica',
      condition: { field: 'media_type', op: 'neq', value: 'none' } },
    { key: 'image_fit', label: 'Adattamento', type: 'select', options: [
      { value: 'cover', label: 'Copri (riempie e taglia)' },
      { value: 'contain', label: 'Contieni (visibile interamente)' },
      { value: 'fill', label: 'Riempi (deforma)' },
    ], condition: { field: 'media_type', op: 'neq', value: 'none' } },
    { key: 'image_zoom', label: 'Zoom al hover', type: 'toggle',
      condition: { field: 'media_type', op: 'neq', value: 'none' } },
    { key: 'media_padding', label: 'Spazio attorno al media (px)', type: 'spacing', max: 60,
      description: 'Aggiunge uno spazio bianco attorno al media',
      condition: { field: 'media_type', op: 'neq', value: 'none' } },
    { key: 'border_radius', label: 'Border radius media', type: 'border-radius',
      condition: { field: 'media_type', op: 'neq', value: 'none' } },

    { type: 'separator', label: 'Contenuto' },
    { key: 'title', label: 'Titolo', type: 'text' },
    { key: 'meta', label: 'Meta', type: 'text' },
    { key: 'content', label: 'Contenuto', type: 'textarea' },
    { key: 'title_element', label: 'Elemento titolo', type: 'select', options: [
      { value: 'h2', label: 'H2' },
      { value: 'h3', label: 'H3' },
      { value: 'h4', label: 'H4' },
      { value: 'div', label: 'DIV' },
    ]},

    { type: 'separator', label: 'Tipografia' },
    { key: 'text_align', label: 'Allineamento testo', type: 'select', options: [
      { value: 'left', label: 'Sinistra' },
      { value: 'center', label: 'Centro' },
      { value: 'right', label: 'Destra' },
    ]},
    { key: 'title_size', label: 'Dimensione titolo (px)', type: 'range', min: 0, max: 60, step: 1,
      description: '0 = predefinito' },
    { key: 'title_weight', label: 'Peso titolo', type: 'select', options: [
      { value: '', label: 'Predefinito' },
      { value: '400', label: 'Normale (400)' },
      { value: '500', label: 'Medio (500)' },
      { value: '600', label: 'Semi-bold (600)' },
      { value: '700', label: 'Bold (700)' },
      { value: '800', label: 'Extra bold (800)' },
      { value: '900', label: 'Black (900)' },
    ]},
    { key: 'title_color', label: 'Colore titolo', type: 'color' },
    { key: 'meta_size', label: 'Dimensione meta (px)', type: 'range', min: 0, max: 24, step: 1,
      description: '0 = predefinito' },
    { key: 'meta_color', label: 'Colore meta', type: 'color' },
    { key: 'content_size', label: 'Dimensione testo (px)', type: 'range', min: 0, max: 28, step: 1,
      description: '0 = predefinito' },
    { key: 'content_color', label: 'Colore testo', type: 'color' },

    { type: 'separator', label: 'Link' },
    { key: 'link_url', label: 'URL link', type: 'text' },
    { key: 'link_target', label: 'Apri in', type: 'select', options: [
      { value: '_self', label: 'Stessa finestra' },
      { value: '_blank', label: 'Nuova finestra' },
    ]},
    { key: 'link_label', label: 'Etichetta link', type: 'text',
      description: 'Vuoto = "Read more →"',
      condition: { field: 'link_url', op: 'notEmpty' } },
    { key: 'link_color', label: 'Colore link', type: 'color',
      condition: { field: 'link_url', op: 'notEmpty' } },

    { type: 'separator', label: 'Stile card' },
    { key: 'card_padding', label: 'Padding interno', type: 'spacing', max: 60 },
    { key: 'card_radius', label: 'Border radius card (px)', type: 'range', min: 0, max: 32, step: 1 },
    ...shadowField,
  ],
};
