import { textEffectsFields, textEffectsDefaults, borderFields, borderDefault, borderHoverDefault, borderEffectDefaults } from './_shared';
import { shadowField } from './_shared.js';

export default {
  type: 'panelslider',
  name: 'Panel Slider',
  icon: 'dashicons-slides',
  category: 'interactive',
  defaults: {
    panels: [
      { id: 'ps-1', title: 'Card 1', content: 'Contenuto...', image: '' },
      { id: 'ps-2', title: 'Card 2', content: 'Contenuto...', image: '' },
      { id: 'ps-3', title: 'Card 3', content: 'Contenuto...', image: '' },
    ],
    columns: '3',
    gap: 'default',
    card_style: 'default',
    card_radius: '8',
    card_padding: { top: 16, right: 16, bottom: 16, left: 16 },
    equal_height: true,
    image_ratio: '4/3',
    image_height: '',
    image_fit: 'cover',
    image_zoom: false,
    show_arrows: true,
    arrow_style: 'circle',
    arrow_size: '40',
    arrow_color: '',
    arrow_bg: '',
    show_dots: false,
    autoplay: false,
    autoplay_interval: '5000',
    title_size: '',
    title_color: '',
    content_size: '',
    content_color: '',
    shadow: 'none',
    ...textEffectsDefaults,
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
  },
  fields: [
    { key: 'panels', label: 'Pannelli', type: 'content-items', supportsDynamic: true,
      itemFields: [
        { key: 'title', label: 'Titolo', type: 'text' },
        { key: 'content', label: 'Contenuto', type: 'textarea' },
        { key: 'image', label: 'Immagine', type: 'image' },
        { key: 'hover_image', label: 'Immagine hover', type: 'image' },
        { key: 'hover_video', label: 'Video hover', type: 'media' },
        { key: 'link', label: 'Link', type: 'text' },
        { key: 'link_target', label: 'Apri in nuova scheda', type: 'toggle' },
      ],
      newItemDefaults: { title: 'Nuova card', content: 'Contenuto...', image: '', hover_image: '', hover_video: '', link: '', link_target: false },
      itemLabel: 'Card',
    },

    { type: 'separator', label: 'Layout' },
    { key: 'columns', label: 'Colonne', type: 'select', responsive: true, options: [
      { value: '1', label: '1 colonna' },
      { value: '2', label: '2 colonne' },
      { value: '3', label: '3 colonne' },
      { value: '4', label: '4 colonne' },
      { value: '5', label: '5 colonne' },
      { value: '6', label: '6 colonne' },
    ]},
    { key: 'gap', label: 'Gap', type: 'select', options: [
      { value: 'collapse', label: 'Collassato' },
      { value: 'small', label: 'Piccolo' },
      { value: 'default', label: 'Predefinito' },
      { value: 'medium', label: 'Medio' },
      { value: 'large', label: 'Grande' },
    ]},
    { key: 'equal_height', label: 'Altezza card uniforme', type: 'toggle',
      description: 'Tutte le card della riga avranno la stessa altezza' },

    { type: 'separator', label: 'Stile Card' },
    { key: 'card_style', label: 'Stile card', type: 'select', options: [
      { value: 'default', label: 'Predefinito' },
      { value: 'primary', label: 'Primary' },
      { value: 'secondary', label: 'Secondary' },
      { value: 'hover', label: 'Hover' },
    ]},
    { key: 'card_radius', label: 'Raggio bordi (px)', type: 'border-radius'},
    { key: 'card_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius' },
    { key: 'card_padding', label: 'Padding interno (px)', type: 'spacing', max: 48 },
    ...shadowField,

    { type: 'separator', label: 'Immagine' },
    { key: 'image_ratio', label: 'Proporzione immagine', type: 'select', options: [
      { value: 'auto', label: 'Automatica (sconsigliato)' },
      { value: '1/1', label: '1:1 Quadrato' },
      { value: '4/3', label: '4:3 Standard' },
      { value: '3/2', label: '3:2 Foto' },
      { value: '16/9', label: '16:9 Wide' },
      { value: '21/9', label: '21:9 Cinema' },
      { value: '3/4', label: '3:4 Verticale' },
      { value: '2/3', label: '2:3 Verticale' },
    ], description: 'Uniforma le proporzioni di tutte le immagini' },
    { key: 'image_height', label: 'Altezza fissa (px)', type: 'range', min: 0, max: 500, step: 10,
      description: '0 = usa proporzione', condition: { field: 'image_ratio', op: 'eq', value: 'auto' } },
    { key: 'image_fit', label: 'Adattamento immagine', type: 'select', options: [
      { value: 'cover', label: 'Copri (riempie e taglia)' },
      { value: 'contain', label: 'Contieni (visibile interamente)' },
      { value: 'fill', label: 'Riempi (deforma)' },
    ]},
    { key: 'image_zoom', label: 'Zoom al hover', type: 'toggle' },

    { type: 'separator', label: 'Tipografia' },
    { key: 'title_size', label: 'Dimensione titolo (px)', type: 'range', min: 0, max: 48, step: 1,
      description: '0 = predefinito' },
    { key: 'title_color', label: 'Colore titolo', type: 'color' },
    { key: 'content_size', label: 'Dimensione testo (px)', type: 'range', min: 0, max: 24, step: 1,
      description: '0 = predefinito' },
    { key: 'content_color', label: 'Colore testo', type: 'color' },

    { type: 'separator', label: 'Frecce e navigazione' },
    { key: 'show_arrows', label: 'Mostra frecce', type: 'toggle' },
    { key: 'arrow_style', label: 'Stile frecce', type: 'select', options: [
      { value: 'circle', label: 'Cerchio pieno' },
      { value: 'circle-outline', label: 'Cerchio bordato' },
      { value: 'square', label: 'Quadrato' },
      { value: 'minimal', label: 'Minimale (solo chevron)' },
      { value: 'chevron-bold', label: 'Chevron grasso' },
      { value: 'arrow-long', label: 'Freccia lunga' },
      { value: 'fancy', label: 'Stilizzato (gradient)' },
      { value: 'uikit', label: 'UIkit classico' },
    ], condition: { field: 'show_arrows', op: 'eq', value: true } },
    { key: 'arrow_size', label: 'Dimensione frecce (px)', type: 'range', min: 24, max: 80, step: 2,
      condition: { field: 'show_arrows', op: 'eq', value: true } },
    { key: 'arrow_color', label: 'Colore icona', type: 'color',
      condition: { field: 'show_arrows', op: 'eq', value: true } },
    { key: 'arrow_bg', label: 'Colore sfondo', type: 'color',
      condition: { field: 'show_arrows', op: 'eq', value: true } },
    { key: 'show_dots', label: 'Mostra dots', type: 'toggle' },

    { type: 'separator', label: 'Autoplay' },
    { key: 'autoplay', label: 'Autoplay', type: 'toggle' },
    { key: 'autoplay_interval', label: 'Intervallo (ms)', type: 'range', min: 1000, max: 10000, step: 500,
      condition: { field: 'autoplay', op: 'eq', value: true } },
    ...textEffectsFields([
      { value: 'title', label: 'Solo Titolo' },
      { value: 'content', label: 'Solo Contenuto' },
      { value: 'all', label: 'Tutti gli elementi testuali' },
    ]),
    ...borderFields(),
  ],
};
