
import { borderFields, borderDefault, borderHoverDefault, borderEffectDefaults } from './_shared.js';

export default {
  type: 'pdfviewer',
  name: 'PDF Viewer',
  icon: 'dashicons-media-document',
  category: 'media',
  defaults: {
    pdf_url: '',
    mode: 'flipbook',
    viewer_height: '600',
    start_page: '1',
    initial_zoom: 'fit-width',
    theme: 'light',
    bg_color: '',
    show_toolbar: true,
    show_page_nav: true,
    show_zoom: true,
    show_fullscreen: true,
    show_download: true,
    show_print: true,
    show_search: false,
    show_thumbnails: false,
    show_bottombar: true,
    show_bottombar_pages: true,
    show_bottombar_zoom: false,
    show_bottombar_fullscreen: false,
    nav_click: true,
    nav_swipe: true,
    nav_keyboard: true,
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
  },
  fields: [
    { type: 'separator', label: 'Sorgente' },
    { key: 'pdf_url', label: 'File PDF', type: 'media' },

    { type: 'separator', label: 'Visualizzazione' },
    { key: 'mode', label: 'Modalità', type: 'select', options: [
      { value: 'flipbook', label: 'Flipbook (sfoglia)' },
      { value: 'single', label: 'Pagina singola' },
      { value: 'double', label: 'Doppia pagina' },
      { value: 'scroll', label: 'Scroll continuo' },
    ]},
    { key: 'viewer_height', label: 'Altezza viewer (px)', type: 'range', min: 300, max: 1200, step: 10 },
    { key: 'start_page', label: 'Pagina iniziale', type: 'range', min: 1, max: 500, step: 1 },
    { key: 'initial_zoom', label: 'Zoom iniziale', type: 'select', options: [
      { value: 'fit-width', label: 'Adatta alla larghezza' },
      { value: 'fit-page', label: 'Adatta alla pagina' },
      { value: '100', label: '100%' },
      { value: '75', label: '75%' },
      { value: '50', label: '50%' },
    ]},
    { key: 'theme', label: 'Tema', type: 'select', options: [
      { value: 'light', label: 'Chiaro' },
      { value: 'dark', label: 'Scuro' },
    ]},
    { key: 'bg_color', label: 'Colore sfondo', type: 'color' },

    { type: 'separator', label: 'Controlli toolbar' },
    { key: 'show_toolbar', label: 'Mostra toolbar', type: 'toggle' },
    { key: 'show_page_nav', label: 'Navigazione pagine', type: 'toggle',
      condition: { field: 'show_toolbar', value: true } },
    { key: 'show_zoom', label: 'Zoom', type: 'toggle',
      condition: { field: 'show_toolbar', value: true } },
    { key: 'show_fullscreen', label: 'Schermo intero', type: 'toggle',
      condition: { field: 'show_toolbar', value: true } },
    { key: 'show_download', label: 'Download', type: 'toggle',
      condition: { field: 'show_toolbar', value: true } },
    { key: 'show_print', label: 'Stampa', type: 'toggle',
      condition: { field: 'show_toolbar', value: true } },
    { key: 'show_thumbnails', label: 'Miniature', type: 'toggle',
      condition: { field: 'show_toolbar', value: true } },

    { type: 'separator', label: 'Barra inferiore' },
    { key: 'show_bottombar', label: 'Mostra barra inferiore', type: 'toggle' },
    { key: 'show_bottombar_pages', label: 'Slider pagine', type: 'toggle',
      condition: { field: 'show_bottombar', value: true } },
    { key: 'show_bottombar_zoom', label: 'Zoom (barra inferiore)', type: 'toggle',
      condition: { field: 'show_bottombar', value: true } },
    { key: 'show_bottombar_fullscreen', label: 'Schermo intero (barra inferiore)', type: 'toggle',
      condition: { field: 'show_bottombar', value: true } },

    { type: 'separator', label: 'Navigazione pagine' },
    { key: 'nav_click', label: 'Click su pagina (volta pagina)', type: 'toggle' },
    { key: 'nav_swipe', label: 'Swipe touch (mobile)', type: 'toggle' },
    { key: 'nav_keyboard', label: 'Frecce tastiera', type: 'toggle' },
    ...borderFields(),
  ],
};
