import { textEffectsFields, textEffectsDefaults, borderFields, borderDefault, borderHoverDefault, borderEffectDefaults, withHover } from './_shared';
import { demo, demoAlt } from '../demoMedia.js';
import { t } from '@/i18n';

/**
 * Tile Popup — split CONTENUTO/STILE.
 *   fields[]      → mode (simple/template), pulsante (text+icon+fullwidth), contenuto (title/content/image/template_id), trigger avanzati, regole display
 *   styleFields[] → preset, bg, typo, effetti preset, text-effects, pulsante stile (size/style/radius/weight/uppercase), modale aspetto (size/shadow/radius/border/colori/overlay/animation)
 */
export default {
  type: 'popup',
  name: t('Popup'),
  icon: 'dashicons-external',
  category: 'interactive',
  defaults: {
    bg: { type: 'none' },
    typography_preset: '',
    mode: 'simple',
    button_text: 'Scopri l\'offerta',
    button_style: 'primary',
    button_size: 'large',
    button_icon: '',
    button_fullwidth: false,
    modal_size: '',
    modal_close_button: true,
    modal_title: 'Offerta di benvenuto',
    modal_shadow: 'lg',
    modal_overlay: '60',
    modal_radius: '16',
    modal_border_width: '0',
    modal_border_color: '',
    // Testo neutro, senza promettere moduli che il popup non ha (stesso default del PHP).
    content: '<p>Per i nuovi clienti, il primo ordine ha uno sconto del 10%. Contattaci per sapere come richiederlo.</p>',
    image: '',
    image_alt: '',
    image_position: 'top',
    preset: 'modal-classic',
    modal_bg: 'var(--olo-color-surface, #ffffff)',
    modal_text_color: 'var(--olo-color-text, #1f2937)',
    modal_title_color: 'var(--olo-color-text, #1f2937)',
    modal_title_size: 24,
    modal_title_weight: '700',
    modal_title_uppercase: false,
    modal_title_letter_spacing: 0,
    button_radius: 6,
    button_uppercase: false,
    button_color: '',
    button_underline: false,
    button_letter_spacing: 0.02,
    button_weight: '600',
    effect_color: '',
    effect_intensity: 'medium',
    effect_speed: 0,
    // Effetti avanzati modale (v1.0.60+): permettono di personalizzare gli effetti
    // wow dei preset audaci (liquid-glass, neon, retro-terminal, 3d-tilt, sticker)
    // tramite controlli granulari invece di CSS hardcoded con !important.
    modal_backdrop_blur: 0,
    modal_backdrop_saturate: 100,
    modal_border_style: 'solid',
    modal_font_family: 'inherit',
    modal_rotation: 0,
    modal_perspective: 0,
    modal_tilt_x: 0,
    modal_glow_pulse: false,
    modal_title_glow: false,
    modal_scanlines: false,
    modal_terminal_prompt: false,
    template_id: 0,
    popup_trigger: 'click',
    popup_anchor: '',
    popup_delay: 5,
    popup_scroll_percent: 50,
    popup_frequency: 'always',
    popup_animation: 'fade',
    popup_close_overlay: true,
    popup_overlay_blur: 0,
    scroll_percent: '50',
    timer_delay: '5',
    inactivity_delay: '30',
    key_sequence_keys: '',
    show_max_times: '0',
    show_once_per_session: false,
    display_device: '',
    display_logged: '',
    display_date_from: '',
    display_date_to: '',
    display_referrer: '',
    display_woo_cart: '',
    display_page_views: '0',
    display_click_count: '0',
    ...textEffectsDefaults,
    text_effect_target: 'content',
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
  },

  // Come nasce dalla palette: un pulsante primario grande con l'icona del regalo che apre (solo al
  // clic) la finestra dell'offerta di benvenuto, con la foto a sinistra del testo, raggio morbido e
  // un'apertura a zoom sulla pagina appena sfocata.
  partenza: {
    // Conflitti PHP/config: vince il config (testo, stile, raggio, colori del dialogo).
    button_text: t('Scopri l\'offerta'),
    button_style: 'primary',
    modal_radius: '16',
    modal_text_color: 'var(--olo-color-text, #1f2937)',
    modal_title_color: 'var(--olo-color-text, #1f2937)',
    button_size: 'large',
    button_icon: 'gift',
    modal_title: t('Offerta di benvenuto'),
    image: demo('vaso'),
    image_alt: demoAlt('vaso'),
    image_position: 'left',
    modal_bg: 'var(--olo-color-background, #ffffff)',
    popup_overlay_blur: 4,
    popup_animation: 'zoom',
  },

  fields: [
    { key: 'mode', label: t('Modalità contenuto'), type: 'select', options: [
      { value: 'simple', label: t('Semplice') },
      { value: 'template', label: t('Template Olobuild') },
    ]},

    { type: 'separator', label: t('Pulsante') },
    { key: 'button_text', label: t('Testo pulsante'), type: 'text' },
    { key: 'button_icon', label: t('Icona pulsante'), type: 'icon' },
    { key: 'button_fullwidth', label: t('Larghezza piena'), type: 'toggle' },

    { type: 'separator', label: t('Contenuto Popup') },
    { key: 'modal_title', label: t('Titolo modale'), type: 'text' },
    { key: 'content', label: t('Contenuto'), type: 'textarea', supportsDynamic: true },
    { key: 'image', label: t('Immagine'), type: 'image', supportsDynamic: true },
    { key: 'image_alt', label: t('Testo alternativo'), type: 'text',
      description: t('Descrive l’immagine a chi non la vede. Vuoto = il testo alternativo dell’immagine nella libreria media.'),
      condition: { field: 'image', op: 'notEmpty' } },
    { key: 'template_id', label: t('Template'), type: 'select', optionsSource: 'templates' },

    { type: 'separator', label: t('Modale — Comportamento') },
    { key: 'modal_close_button', label: t('Pulsante chiudi'), type: 'toggle' },
    { key: 'popup_close_overlay', label: t('Chiudi su click overlay'), type: 'toggle' },

    { type: 'separator', label: t('Trigger avanzati') },
    { key: 'popup_trigger', label: t('Attivazione'), type: 'select',
      description: t('Nel builder i trigger automatici non partono: il popup si apre con il suo pulsante. Sul sito il pulsante compare solo con «Click».'),
      options: [
      { value: 'click', label: t('Click (default)') },
      { value: 'page_load', label: t('Caricamento pagina') },
      { value: 'scroll_percent', label: t('Scroll percentuale') },
      { value: 'exit_intent', label: t('Exit Intent') },
      { value: 'time_delay', label: t('Timer (secondi)') },
      { value: 'inactivity', label: t('Inattività utente') },
      { value: 'reach', label: t('Arrivo a questo punto della pagina') },
      { value: 'key_sequence', label: t('Sequenza di tasti') },
      { value: 'link', label: t('Solo da un link (#ancora)') },
    ]},
    { key: 'popup_anchor', label: t('Ancora'), type: 'text', placeholder: t('Es. offerta'),
      condition: { field: 'popup_trigger', op: 'eq', value: 'link' },
      description: t('Si scrive senza #. Ogni link a #ancora della pagina apre il popup: un pulsante, una voce di menu, il pulsante di una card. Anche un indirizzo che finisce con #ancora lo apre appena la pagina si carica. Senza ancora il popup torna ad aprirsi col suo pulsante.') },
    { key: 'key_sequence_keys', label: t('Sequenza'), type: 'text',
      condition: { field: 'popup_trigger', op: 'eq', value: 'key_sequence' },
      description: t('I tasti da premere in fila; le frecce si scrivono ↑ ↓ ← →. Vuoto: il codice Konami (↑↑↓↓←→←→ba).') },
    { key: 'popup_delay', label: t('Ritardo (secondi)'), type: 'range', min: 0, max: 30, step: 1,
      condition: { field: 'popup_trigger', op: 'in', value: ['page_load', 'time_delay'] } },
    { key: 'popup_scroll_percent', label: t('Scroll'), type: 'range', min: 10, max: 100, step: 10,
      condition: { field: 'popup_trigger', op: 'eq', value: 'scroll_percent' } },
    { key: 'inactivity_delay', label: t('Secondi inattività'), type: 'range', min: 5, max: 120, step: 5,
      condition: { field: 'popup_trigger', op: 'eq', value: 'inactivity' } },
    { key: 'popup_frequency', label: t('Frequenza'), type: 'select', options: [
      { value: 'always', label: t('Sempre') },
      { value: 'once_session', label: t('Una volta per sessione') },
      { value: 'once_day', label: t('Una volta al giorno') },
      { value: 'once_week', label: t('Una volta a settimana') },
      { value: 'once_ever', label: t('Solo una volta') },
    ]},
    { key: 'show_max_times', label: t('Mostra max (0=illimitato)'), type: 'range', min: 0, max: 100 },
    { key: 'show_once_per_session', label: t('Solo una volta per sessione'), type: 'toggle' },

    { type: 'separator', label: t('Regole di visualizzazione') },
    { key: 'display_device', label: t('Dispositivo'), type: 'select',
      description: t('Si decide dalla larghezza della finestra: telefono sotto 640 px, tablet da 640 a 959 px, desktop da 960 px.'),
      options: [
      { value: '', label: t('Tutti') },
      { value: 'desktop', label: t('Solo desktop') },
      { value: 'tablet', label: t('Solo tablet') },
      { value: 'mobile', label: t('Solo mobile') },
    ]},
    { key: 'display_logged', label: t('Stato utente'), type: 'select', options: [
      { value: '', label: t('Tutti') },
      { value: 'logged_in', label: t('Solo loggati') },
      { value: 'logged_out', label: t('Solo visitatori') },
    ]},
    { key: 'display_date_from', label: t('Mostra dal'), type: 'date' },
    { key: 'display_date_to', label: t('Mostra fino al'), type: 'date' },
    { key: 'display_referrer', label: t('Solo da referrer (contiene)'), type: 'text', placeholder: t('google.com'),
      description: t('Il popup compare solo a chi arriva da un indirizzo che contiene questo testo. Vale per tutta la visita, non solo per la prima pagina.') },
    { key: 'display_woo_cart', label: t('Carrello WooCommerce'), type: 'select', options: [
      { value: '', label: t('Ignora') },
      { value: 'has_items', label: t('Solo se ha prodotti') },
      { value: 'empty', label: t('Solo se vuoto') },
    ]},
    { key: 'display_page_views', label: t('Dopo N pagine visitate (0=ignora)'), type: 'range', min: 0, max: 20,
      description: t('Conta le pagine viste nella visita, compresa quella attuale. Si contano le pagine che contengono un popup: per contarle tutte mettilo in un modello globale, per esempio il footer.') },
  ],

  styleFields: [
    { type: 'separator', label: t('Preset stile') },
    { key: 'preset', label: t('Stile'), type: 'select', options: [
      { value: 'modal-classic',     label: t('Modal Classic (default)') },
      { value: 'newsletter-promo',  label: t('Newsletter Promo (foto + CTA)') },
      { value: 'sale-banner',       label: t('Sale Banner (promo audace)') },
      { value: 'editorial-card',    label: t('Editorial Card (magazine)') },
      { value: 'compact-dialog',    label: t('Compact Dialog (alert minimal)') },
      { value: 'liquid-glass',      label: t('Liquid Glass (Vision Pro)') },
      { value: 'neon-cyber',        label: t('Neon Cyberpunk (Tron)') },
      { value: 'brutalist-block',   label: t('Brutalist Block (neo-brutalist)') },
      { value: 'magnetic-liquid',   label: t('Magnetic Liquid (next-gen)') },
      { value: 'sticker',           label: t('Sticker / Scrapbook') },
      { value: 'retro-terminal',    label: t('Retro Terminal (CRT)') },
      { value: '3d-tilt',           label: t('3D Card Tilt') },
      { value: 'custom',            label: t('Personalizzato (usa controlli sotto)') },
    ]},
    { key: 'typography_preset', label: t('Stile tipografico'), type: 'select', optionsSource: 'globalTypography' },

    // Condizione = i preset in cui almeno uno dei due campi sotto compare (Liquid Glass
    // ne aveva solo «Intensità effetto», tolta: la sezione sarebbe rimasta vuota).
    { type: 'separator', label: t('Tweak effetto preset'),
      condition: { field: 'preset', op: 'in', value: ['neon-cyber','brutalist-block','magnetic-liquid','sticker','retro-terminal','3d-tilt'] } },
    { key: 'effect_color', label: t('Colore effetto'), type: 'color',
      condition: { field: 'preset', op: 'in', value: ['neon-cyber','brutalist-block','magnetic-liquid','sticker','retro-terminal'] } },
    // «Intensità effetto» (effect_intensity) qui non c'è: il popup disegna i suoi effetti
    // da sé, non con gli effetti wow condivisi che la leggono. La chiave resta nei default.
    { key: 'effect_speed', label: t('Velocità animazioni'), type: 'range',
      min: 0, max: 4000, step: 100,
      condition: { field: 'preset', op: 'in', value: ['neon-cyber','magnetic-liquid','retro-terminal','3d-tilt'] } },

    ...textEffectsFields([ { value: 'content', label: t('Solo Contenuto') } ]),

    { type: 'separator', label: t('Pulsante — Aspetto') },
    { key: 'button_style', label: t('Stile pulsante'), type: 'select', options: [
      { value: 'default', label: t('Default') },
      { value: 'primary', label: t('Primary') },
      { value: 'secondary', label: t('Secondary') },
      { value: 'danger', label: t('Danger') },
      { value: 'text', label: t('Text') },
      { value: 'link', label: t('Link') },
    ]},
    { key: 'button_size', label: t('Dimensione'), type: 'select', options: [
      { value: '', label: t('Auto') },
      { value: 'small', label: t('Small') },
      { value: 'large', label: t('Large') },
    ]},
    { key: 'button_radius', label: t('Raggio pulsante'), type: 'border-radius' },
    { key: 'button_uppercase', label: t('Pulsante maiuscolo'), type: 'toggle' },
    { key: 'button_color', label: t('Colore trigger (vuoto = tema)'), type: 'color' },
    { key: 'button_underline', label: t('Sottolinea trigger'), type: 'toggle' },

    { type: 'separator', label: t('Modale — Aspetto') },
    { key: 'modal_size', label: t('Dimensione modale'), type: 'select', options: [
      { value: '', label: t('Auto') },
      { value: 'container', label: t('Container') },
      { value: 'full', label: t('Full screen') },
    ]},
    { key: 'modal_shadow', label: t('Ombra modale'), type: 'select', options: [
      { value: 'none', label: t('Nessuna') },
      { value: 'sm', label: t('Leggera') },
      { value: 'md', label: t('Media') },
      { value: 'lg', label: t('Grande') },
      { value: 'xl', label: t('Extra grande') },
      { value: 'custom', label: t('Personalizzata') },
    ]},
    { key: 'modal_shadow_custom', label: t('Ombra personalizzata'), type: 'box-shadow',
      legacyKeys: { h: 'modal_shadow_h', v: 'modal_shadow_v', blur: 'modal_shadow_blur', spread: 'modal_shadow_spread', color: 'modal_shadow_color', inset: 'modal_shadow_inset' },
      condition: { field: 'modal_shadow', op: 'eq', value: 'custom' } },
    withHover({ key: 'modal_radius', label: t('Raggio'), type: 'border-radius' }),
    // UN solo bordo per il dialogo: «Bordo modale» con hover ed effetti (borderFields
    // sulla chiave `modal_border`). Il vecchio «Bordo» condiviso in fondo al tab salvava
    // `border` su un selettore inesistente e non disegnava niente: il renderer lo legge
    // ancora come riserva. `legacyKeys`: le chiavi piatte dei preset restano in sincronia.
    ...borderFields({ key: 'modal_border' })
      .filter((f) => f.type !== 'separator')
      .map((f) => (f.key === 'modal_border' ? { ...f, label: t('Bordo modale'),
        legacyKeys: { width: 'modal_border_width', style: 'modal_border_style', color: 'modal_border_color' } } : f)),

    { key: 'modal_bg', label: t('Sfondo modale'), type: 'color' },
    { key: 'modal_text_color', label: t('Colore testo modale'), type: 'color' },
    { key: 'modal_backdrop_blur', label: t('Sfocatura sfondo modale (blur)'), type: 'range', min: 0, max: 40, step: 1 },
    { key: 'modal_backdrop_saturate', label: t('Saturazione sfondo modale'), type: 'range', min: 100, max: 200, step: 5 },
    { key: 'modal_font_family', label: t('Font modale'), type: 'font-family' },

    { type: 'separator', label: t('Tipografia') },
    { type: 'typography', label: t('Titolo modale'),
      responsiveKeys: [],
      letterSpacingUnit: 'em',
      keys: {
        size:          'modal_title_size',
        weight:        'modal_title_weight',
        letterSpacing: 'modal_title_letter_spacing',
        color:         'modal_title_color',
      },
      sizeMin: 14, sizeMax: 48, sizeStep: 1,
    },
    { type: 'typography', label: t('Pulsante'),
      responsiveKeys: [],
      letterSpacingUnit: 'em',
      keys: {
        weight:        'button_weight',
        letterSpacing: 'button_letter_spacing',
      },
    },
    { key: 'modal_title_uppercase', label: t('Titolo maiuscolo'), type: 'toggle' },

    { type: 'separator', label: t('Overlay & Animazione') },
    { key: 'modal_overlay', label: t('Oscuramento sfondo'), type: 'range', min: 0, max: 100, step: 5 },
    { key: 'popup_overlay_blur', label: t('Sfocatura overlay'), type: 'range', min: 0, max: 20, step: 1 },
    { key: 'popup_animation', label: t('Animazione apertura'), type: 'select', options: [
      { value: 'fade', label: t('Fade') },
      { value: 'slide-up', label: t('Slide Up') },
      { value: 'slide-down', label: t('Slide Down') },
      { value: 'zoom', label: t('Zoom') },
      { value: 'flip', label: t('Flip') },
    ]},

    { type: 'separator', label: t('Effetti avanzati modale') },
    { key: 'modal_rotation', label: t('Rotazione modale (gradi)'), type: 'range', min: -10, max: 10, step: 0.5 },
    { key: 'modal_perspective', label: t('Prospettiva 3D'), type: 'range', min: 0, max: 2000, step: 100 },
    { key: 'modal_tilt_x', label: t('Tilt 3D asse X (gradi)'), type: 'range', min: -10, max: 10, step: 0.5 },
    { key: 'modal_glow_pulse', label: t('Glow pulsante (animazione bordo)'), type: 'toggle' },
    { key: 'modal_title_glow', label: t('Glow titolo'), type: 'toggle' },
    { key: 'modal_scanlines', label: t('Effetto scanlines (CRT)'), type: 'toggle' },
    { key: 'modal_terminal_prompt', label: t('Prompt terminale (> + cursore)'), type: 'toggle' },

    { type: 'separator', label: t('Disposizione') },
    { key: 'image_position', label: t('Posizione immagine'), type: 'select', options: [
      { value: 'top', label: t('Sopra') },
      { value: 'bottom', label: t('Sotto') },
      { value: 'left', label: t('Sinistra') },
      { value: 'right', label: t('Destra') },
    ]},
  ],
};
