import { textEffectsFields, textEffectsDefaults, borderFields, borderDefault, borderHoverDefault, borderEffectDefaults } from './_shared';
export default {
  type: 'popup',
  name: 'Popup',
  icon: 'dashicons-external',
  category: 'interactive',
  defaults: {
    // Modalità
    mode: 'simple',
    // Pulsante
    button_text: 'Apri',
    button_style: 'default',
    button_size: '',
    button_icon: '',
    button_fullwidth: false,
    // Modal
    modal_size: '',
    modal_close_button: true,
    modal_title: '',
    modal_shadow: 'lg',
    modal_overlay: '60',
    modal_radius: '12',
    modal_border_width: '0',
    modal_border_color: '',
    // Modo simple
    content: '<p>Contenuto del popup...</p>',
    image: '',
    image_position: 'top',
    // Modo template
    template_id: 0,
    // Trigger avanzati
    popup_trigger: 'click',
    popup_delay: 5,
    popup_scroll_percent: 50,
    popup_frequency: 'always',
    popup_animation: 'fade',
    popup_close_overlay: true,
    popup_overlay_blur: 0,
    scroll_percent: '50',
    timer_delay: '5',
    inactivity_delay: '30',
    show_max_times: '0',
    show_once_per_session: false,
    // Display rules
    display_device: '',
    display_logged: '',
    display_date_from: '',
    display_date_to: '',
    display_referrer: '',
    display_woo_cart: '',
    display_page_views: '0',
    display_click_count: '0',
    ...textEffectsDefaults,
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
  },
  fields: [
    { type: 'separator', label: 'Pulsante' },
    { key: 'button_text', label: 'Testo pulsante', type: 'text' },
    { key: 'button_style', label: 'Stile pulsante', type: 'select', options: [
      { value: 'default', label: 'Default' },
      { value: 'primary', label: 'Primary' },
      { value: 'secondary', label: 'Secondary' },
      { value: 'danger', label: 'Danger' },
      { value: 'text', label: 'Text' },
      { value: 'link', label: 'Link' },
    ]},
    { key: 'button_size', label: 'Dimensione', type: 'select', options: [
      { value: '', label: 'Auto' },
      { value: 'small', label: 'Small' },
      { value: 'large', label: 'Large' },
    ]},
    { key: 'button_icon', label: 'Icona pulsante', type: 'icon' },
    { key: 'button_fullwidth', label: 'Larghezza piena', type: 'toggle' },

    { type: 'separator', label: 'Contenuto Popup' },
    { key: 'mode', label: 'Modalità contenuto', type: 'select', options: [
      { value: 'simple', label: 'Semplice' },
      { value: 'template', label: 'Template Olobuild' },
    ]},
    { key: 'modal_title', label: 'Titolo modale', type: 'text' },
    { key: 'content', label: 'Contenuto', type: 'textarea', supportsDynamic: true },
    { key: 'image', label: 'Immagine', type: 'image', supportsDynamic: true },
    { key: 'image_position', label: 'Posizione immagine', type: 'select', options: [
      { value: 'top', label: 'Sopra' },
      { value: 'bottom', label: 'Sotto' },
      { value: 'left', label: 'Sinistra' },
      { value: 'right', label: 'Destra' },
    ]},
    { key: 'template_id', label: 'Template', type: 'select', optionsSource: 'templates' },

    { type: 'separator', label: 'Modale' },
    { key: 'modal_size', label: 'Dimensione modale', type: 'select', options: [
      { value: '', label: 'Auto' },
      { value: 'container', label: 'Container' },
      { value: 'full', label: 'Full screen' },
    ]},
    { key: 'modal_shadow', label: 'Ombra modale', type: 'select', options: [
      { value: 'none', label: 'Nessuna' },
      { value: 'sm', label: 'Leggera' },
      { value: 'md', label: 'Media' },
      { value: 'lg', label: 'Grande' },
      { value: 'xl', label: 'Extra grande' },
      { value: 'custom', label: 'Personalizzata' },
    ]},
    { key: 'modal_shadow_h', label: 'Offset H (px)', type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'modal_shadow', op: 'eq', value: 'custom' } },
    { key: 'modal_shadow_v', label: 'Offset V (px)', type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'modal_shadow', op: 'eq', value: 'custom' } },
    { key: 'modal_shadow_blur', label: 'Sfocatura (px)', type: 'range', min: 0, max: 100, step: 1,
      condition: { field: 'modal_shadow', op: 'eq', value: 'custom' } },
    { key: 'modal_shadow_spread', label: 'Espansione (px)', type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'modal_shadow', op: 'eq', value: 'custom' } },
    { key: 'modal_shadow_color', label: 'Colore ombra', type: 'color',
      condition: { field: 'modal_shadow', op: 'eq', value: 'custom' } },
    { key: 'modal_shadow_inset', label: 'Ombra interna', type: 'toggle',
      condition: { field: 'modal_shadow', op: 'eq', value: 'custom' } },
    { key: 'modal_radius', label: 'Bordo arrotondato', type: 'border-radius' },
    { key: 'modal_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius' },
    { key: 'modal_border_width', label: 'Spessore bordo', type: 'range', min: 0, max: 10, step: 1 },
    { key: 'modal_border_color', label: 'Colore bordo', type: 'color' },
    { key: 'modal_overlay', label: 'Oscuramento sfondo', type: 'range', min: 0, max: 100, step: 5 },
    { key: 'modal_close_button', label: 'Pulsante chiudi', type: 'toggle' },
    { key: 'popup_close_overlay', label: 'Chiudi su click overlay', type: 'toggle' },
    { key: 'popup_overlay_blur', label: 'Sfocatura overlay', type: 'range', min: 0, max: 20, step: 1 },
    { key: 'popup_animation', label: 'Animazione apertura', type: 'select', options: [
      { value: 'fade', label: 'Fade' },
      { value: 'slide-up', label: 'Slide Up' },
      { value: 'slide-down', label: 'Slide Down' },
      { value: 'zoom', label: 'Zoom' },
      { value: 'flip', label: 'Flip' },
    ]},

    { type: 'separator', label: 'Trigger avanzati' },
    { key: 'popup_trigger', label: 'Attivazione', type: 'select', options: [
      { value: 'click', label: 'Click (default)' },
      { value: 'page_load', label: 'Caricamento pagina' },
      { value: 'scroll_percent', label: 'Scroll percentuale' },
      { value: 'exit_intent', label: 'Exit Intent' },
      { value: 'time_delay', label: 'Timer (secondi)' },
      { value: 'inactivity', label: 'Inattivita utente' },
    ]},
    { key: 'popup_delay', label: 'Ritardo (secondi)', type: 'range', min: 0, max: 30, step: 1,
      condition: { field: 'popup_trigger', op: 'in', value: ['page_load', 'time_delay'] } },
    { key: 'popup_scroll_percent', label: 'Scroll (%)', type: 'range', min: 10, max: 100, step: 10,
      condition: { field: 'popup_trigger', op: 'eq', value: 'scroll_percent' } },
    { key: 'inactivity_delay', label: 'Secondi inattivita', type: 'range', min: 5, max: 120, step: 5,
      condition: { field: 'popup_trigger', op: 'eq', value: 'inactivity' } },
    { key: 'popup_frequency', label: 'Frequenza', type: 'select', options: [
      { value: 'always', label: 'Sempre' },
      { value: 'once_session', label: 'Una volta per sessione' },
      { value: 'once_day', label: 'Una volta al giorno' },
      { value: 'once_week', label: 'Una volta a settimana' },
      { value: 'once_ever', label: 'Solo una volta' },
    ]},
    { key: 'show_max_times', label: 'Mostra max (0=illimitato)', type: 'range', min: 0, max: 100 },
    { key: 'show_once_per_session', label: 'Solo una volta per sessione', type: 'toggle' },

    { type: 'separator', label: 'Regole di visualizzazione' },
    { key: 'display_device', label: 'Dispositivo', type: 'select', options: [
      { value: '', label: 'Tutti' },
      { value: 'desktop', label: 'Solo desktop' },
      { value: 'mobile', label: 'Solo mobile' },
    ]},
    { key: 'display_logged', label: 'Stato utente', type: 'select', options: [
      { value: '', label: 'Tutti' },
      { value: 'logged_in', label: 'Solo loggati' },
      { value: 'logged_out', label: 'Solo visitatori' },
    ]},
    { key: 'display_date_from', label: 'Mostra dal', type: 'date' },
    { key: 'display_date_to', label: 'Mostra fino al', type: 'date' },
    { key: 'display_referrer', label: 'Solo da referrer (contiene)', type: 'text', placeholder: 'google.com' },
    { key: 'display_woo_cart', label: 'Carrello WooCommerce', type: 'select', options: [
      { value: '', label: 'Ignora' },
      { value: 'has_items', label: 'Solo se ha prodotti' },
      { value: 'empty', label: 'Solo se vuoto' },
    ]},
    { key: 'display_page_views', label: 'Dopo N pagine visitate (0=ignora)', type: 'range', min: 0, max: 20 },
    ...textEffectsFields([ { value: 'content', label: 'Solo Contenuto' } ]),
    ...borderFields(),
  ],
};
