import { textEffectsFields, textEffectsDefaults, borderFields, borderDefault, borderHoverDefault, borderEffectDefaults, withHover } from './_shared';
import { t } from '@/i18n';

/**
 * Tile Popup — split CONTENUTO/STILE.
 *   fields[]      → mode (simple/template), pulsante (text+icon+fullwidth), contenuto (title/content/image/template_id), trigger avanzati, regole display
 *   styleFields[] → preset, bg, typo, effetti preset, text-effects, pulsante stile (size/style/radius/weight/uppercase), modale aspetto (size/shadow/radius/border/colori/overlay/animation)
 */
export default {
  type: 'popup',
  name: t('Popup'),
  icon: 'dashicons-external',
  category: 'interactive',
  defaults: {
    bg: { type: 'none' },
    typography_preset: '',
    mode: 'simple',
    button_text: 'Scopri l\'offerta',
    button_style: 'primary',
    button_size: 'large',
    button_icon: '',
    button_fullwidth: false,
    modal_size: '',
    modal_close_button: true,
    modal_title: 'Offerta esclusiva',
    modal_shadow: 'lg',
    modal_overlay: '60',
    modal_radius: '16',
    modal_border_width: '0',
    modal_border_color: '',
    content: '<p>Iscriviti alla nostra newsletter per ricevere offerte esclusive e contenuti riservati.</p>',
    image: 'https://images.unsplash.com/photo-1759563867665-f93d66272338?w=1200&q=75&auto=format&fit=crop',
    image_position: 'top',
    preset: 'modal-classic',
    modal_bg: 'var(--olo-color-surface, #ffffff)',
    modal_text_color: 'var(--olo-color-text, #1f2937)',
    modal_title_color: 'var(--olo-color-text, #1f2937)',
    modal_title_size: 24,
    modal_title_weight: '700',
    modal_title_uppercase: false,
    modal_title_letter_spacing: 0,
    button_radius: 6,
    button_uppercase: false,
    button_color: '',
    button_underline: false,
    button_letter_spacing: 0.02,
    button_weight: '600',
    effect_color: '',
    effect_intensity: 'medium',
    effect_speed: 0,
    // Effetti avanzati modale (v1.0.60+): permettono di personalizzare gli effetti
    // wow dei preset audaci (liquid-glass, neon, retro-terminal, 3d-tilt, sticker)
    // tramite controlli granulari invece di CSS hardcoded con !important.
    modal_backdrop_blur: 0,
    modal_backdrop_saturate: 100,
    modal_border_style: 'solid',
    modal_font_family: 'inherit',
    modal_rotation: 0,
    modal_perspective: 0,
    modal_tilt_x: 0,
    modal_glow_pulse: false,
    modal_title_glow: false,
    modal_scanlines: false,
    modal_terminal_prompt: false,
    template_id: 0,
    popup_trigger: 'click',
    popup_delay: 5,
    popup_scroll_percent: 50,
    popup_frequency: 'always',
    popup_animation: 'fade',
    popup_close_overlay: true,
    popup_overlay_blur: 0,
    scroll_percent: '50',
    timer_delay: '5',
    inactivity_delay: '30',
    show_max_times: '0',
    show_once_per_session: false,
    display_device: '',
    display_logged: '',
    display_date_from: '',
    display_date_to: '',
    display_referrer: '',
    display_woo_cart: '',
    display_page_views: '0',
    display_click_count: '0',
    ...textEffectsDefaults,
    text_effect_target: 'content',
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
  },

  fields: [
    { key: 'mode', label: t('Modalità contenuto'), type: 'select', options: [
      { value: 'simple', label: t('Semplice') },
      { value: 'template', label: t('Template Olobuild') },
    ]},

    { type: 'separator', label: t('Pulsante') },
    { key: 'button_text', label: t('Testo pulsante'), type: 'text' },
    { key: 'button_icon', label: t('Icona pulsante'), type: 'icon' },
    { key: 'button_fullwidth', label: t('Larghezza piena'), type: 'toggle' },

    { type: 'separator', label: t('Contenuto Popup') },
    { key: 'modal_title', label: t('Titolo modale'), type: 'text' },
    { key: 'content', label: t('Contenuto'), type: 'textarea', supportsDynamic: true },
    { key: 'image', label: t('Immagine'), type: 'image', supportsDynamic: true },
    { key: 'image_position', label: t('Posizione immagine'), type: 'select', options: [
      { value: 'top', label: t('Sopra') },
      { value: 'bottom', label: t('Sotto') },
      { value: 'left', label: t('Sinistra') },
      { value: 'right', label: t('Destra') },
    ]},
    { key: 'template_id', label: t('Template'), type: 'select', optionsSource: 'templates' },

    { type: 'separator', label: t('Modale — Comportamento') },
    { key: 'modal_close_button', label: t('Pulsante chiudi'), type: 'toggle' },
    { key: 'popup_close_overlay', label: t('Chiudi su click overlay'), type: 'toggle' },

    { type: 'separator', label: t('Trigger avanzati') },
    { key: 'popup_trigger', label: t('Attivazione'), type: 'select', options: [
      { value: 'click', label: t('Click (default)') },
      { value: 'page_load', label: t('Caricamento pagina') },
      { value: 'scroll_percent', label: t('Scroll percentuale') },
      { value: 'exit_intent', label: t('Exit Intent') },
      { value: 'time_delay', label: t('Timer (secondi)') },
      { value: 'inactivity', label: t('Inattività utente') },
    ]},
    { key: 'popup_delay', label: t('Ritardo (secondi)'), type: 'range', min: 0, max: 30, step: 1,
      condition: { field: 'popup_trigger', op: 'in', value: ['page_load', 'time_delay'] } },
    { key: 'popup_scroll_percent', label: t('Scroll (%)'), type: 'range', min: 10, max: 100, step: 10,
      condition: { field: 'popup_trigger', op: 'eq', value: 'scroll_percent' } },
    { key: 'inactivity_delay', label: t('Secondi inattività'), type: 'range', min: 5, max: 120, step: 5,
      condition: { field: 'popup_trigger', op: 'eq', value: 'inactivity' } },
    { key: 'popup_frequency', label: t('Frequenza'), type: 'select', options: [
      { value: 'always', label: t('Sempre') },
      { value: 'once_session', label: t('Una volta per sessione') },
      { value: 'once_day', label: t('Una volta al giorno') },
      { value: 'once_week', label: t('Una volta a settimana') },
      { value: 'once_ever', label: t('Solo una volta') },
    ]},
    { key: 'show_max_times', label: t('Mostra max (0=illimitato)'), type: 'range', min: 0, max: 100 },
    { key: 'show_once_per_session', label: t('Solo una volta per sessione'), type: 'toggle' },

    { type: 'separator', label: t('Regole di visualizzazione') },
    { key: 'display_device', label: t('Dispositivo'), type: 'select', options: [
      { value: '', label: t('Tutti') },
      { value: 'desktop', label: t('Solo desktop') },
      { value: 'mobile', label: t('Solo mobile') },
    ]},
    { key: 'display_logged', label: t('Stato utente'), type: 'select', options: [
      { value: '', label: t('Tutti') },
      { value: 'logged_in', label: t('Solo loggati') },
      { value: 'logged_out', label: t('Solo visitatori') },
    ]},
    { key: 'display_date_from', label: t('Mostra dal'), type: 'date' },
    { key: 'display_date_to', label: t('Mostra fino al'), type: 'date' },
    { key: 'display_referrer', label: t('Solo da referrer (contiene)'), type: 'text', placeholder: t('google.com') },
    { key: 'display_woo_cart', label: t('Carrello WooCommerce'), type: 'select', options: [
      { value: '', label: t('Ignora') },
      { value: 'has_items', label: t('Solo se ha prodotti') },
      { value: 'empty', label: t('Solo se vuoto') },
    ]},
    { key: 'display_page_views', label: t('Dopo N pagine visitate (0=ignora)'), type: 'range', min: 0, max: 20 },
  ],

  styleFields: [
    { type: 'separator', label: t('Preset stile') },
    { key: 'preset', label: t('Stile'), type: 'select', options: [
      { value: 'modal-classic',     label: t('Modal Classic (default)') },
      { value: 'newsletter-promo',  label: t('Newsletter Promo (foto + CTA)') },
      { value: 'sale-banner',       label: t('Sale Banner (promo audace)') },
      { value: 'editorial-card',    label: t('Editorial Card (magazine)') },
      { value: 'compact-dialog',    label: t('Compact Dialog (alert minimal)') },
      { value: 'liquid-glass',      label: t('Liquid Glass (Vision Pro)') },
      { value: 'neon-cyber',        label: t('Neon Cyberpunk (Tron)') },
      { value: 'brutalist-block',   label: t('Brutalist Block (neo-brutalist)') },
      { value: 'magnetic-liquid',   label: t('Magnetic Liquid (next-gen)') },
      { value: 'sticker',           label: t('Sticker / Scrapbook') },
      { value: 'retro-terminal',    label: t('Retro Terminal (CRT)') },
      { value: '3d-tilt',           label: t('3D Card Tilt') },
      { value: 'custom',            label: t('Personalizzato (usa controlli sotto)') },
    ]},
    { key: 'typography_preset', label: t('Stile tipografico'), type: 'select', optionsSource: 'globalTypography' },

    { type: 'separator', label: t('Tweak effetto preset'),
      condition: { field: 'preset', op: 'in', value: ['liquid-glass','neon-cyber','brutalist-block','magnetic-liquid','sticker','retro-terminal','3d-tilt'] } },
    { key: 'effect_color', label: t('Colore effetto'), type: 'color',
      condition: { field: 'preset', op: 'in', value: ['neon-cyber','brutalist-block','magnetic-liquid','sticker','retro-terminal'] } },
    { key: 'effect_intensity', label: t('Intensità effetto'), type: 'select',
      options: [
        { value: 'low',    label: t('Bassa') },
        { value: 'medium', label: t('Media (default)') },
        { value: 'high',   label: t('Alta') },
      ],
      condition: { field: 'preset', op: 'in', value: ['liquid-glass','neon-cyber','brutalist-block','magnetic-liquid','sticker','retro-terminal','3d-tilt'] } },
    { key: 'effect_speed', label: t('Velocità animazioni (ms)'), type: 'range',
      min: 0, max: 4000, step: 100,
      condition: { field: 'preset', op: 'in', value: ['neon-cyber','magnetic-liquid','retro-terminal','3d-tilt'] } },

    ...textEffectsFields([ { value: 'content', label: t('Solo Contenuto') } ]),

    { type: 'separator', label: t('Pulsante — Aspetto') },
    { key: 'button_style', label: t('Stile pulsante'), type: 'select', options: [
      { value: 'default', label: t('Default') },
      { value: 'primary', label: t('Primary') },
      { value: 'secondary', label: t('Secondary') },
      { value: 'danger', label: t('Danger') },
      { value: 'text', label: t('Text') },
      { value: 'link', label: t('Link') },
    ]},
    { key: 'button_size', label: t('Dimensione'), type: 'select', options: [
      { value: '', label: t('Auto') },
      { value: 'small', label: t('Small') },
      { value: 'large', label: t('Large') },
    ]},
    { key: 'button_radius', label: t('Arrotondamento pulsante (px)'), type: 'border-radius' },
    { key: 'button_uppercase', label: t('Pulsante maiuscolo'), type: 'toggle' },
    { key: 'button_color', label: t('Colore trigger (vuoto = tema)'), type: 'color' },
    { key: 'button_underline', label: t('Sottolinea trigger'), type: 'toggle' },

    { type: 'separator', label: t('Modale — Aspetto') },
    { key: 'modal_size', label: t('Dimensione modale'), type: 'select', options: [
      { value: '', label: t('Auto') },
      { value: 'container', label: t('Container') },
      { value: 'full', label: t('Full screen') },
    ]},
    { key: 'modal_shadow', label: t('Ombra modale'), type: 'select', options: [
      { value: 'none', label: t('Nessuna') },
      { value: 'sm', label: t('Leggera') },
      { value: 'md', label: t('Media') },
      { value: 'lg', label: t('Grande') },
      { value: 'xl', label: t('Extra grande') },
      { value: 'custom', label: t('Personalizzata') },
    ]},
    { key: 'modal_shadow_h', label: t('Offset H (px)'), type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'modal_shadow', op: 'eq', value: 'custom' } },
    { key: 'modal_shadow_v', label: t('Offset V (px)'), type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'modal_shadow', op: 'eq', value: 'custom' } },
    { key: 'modal_shadow_blur', label: t('Sfocatura (px)'), type: 'range', min: 0, max: 100, step: 1,
      condition: { field: 'modal_shadow', op: 'eq', value: 'custom' } },
    { key: 'modal_shadow_spread', label: t('Espansione (px)'), type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'modal_shadow', op: 'eq', value: 'custom' } },
    { key: 'modal_shadow_color', label: t('Colore ombra'), type: 'color',
      condition: { field: 'modal_shadow', op: 'eq', value: 'custom' } },
    { key: 'modal_shadow_inset', label: t('Ombra interna'), type: 'toggle',
      condition: { field: 'modal_shadow', op: 'eq', value: 'custom' } },
    withHover({ key: 'modal_radius', label: t('Bordo arrotondato'), type: 'border-radius' }),
    { key: 'modal_border_width', label: t('Spessore bordo'), type: 'range', min: 0, max: 10, step: 1 },
    { key: 'modal_border_style', label: t('Stile bordo'), type: 'select', options: [
      { value: 'solid',  label: t('Continuo') },
      { value: 'dashed', label: t('Tratteggiato') },
      { value: 'dotted', label: t('Puntinato') },
      { value: 'double', label: t('Doppio') },
    ]},
    { key: 'modal_border_color', label: t('Colore bordo'), type: 'color' },
    { key: 'modal_bg', label: t('Sfondo modale'), type: 'color' },
    { key: 'modal_text_color', label: t('Colore testo modale'), type: 'color' },
    { key: 'modal_backdrop_blur', label: t('Sfocatura sfondo modale (blur)'), type: 'range', min: 0, max: 40, step: 1 },
    { key: 'modal_backdrop_saturate', label: t('Saturazione sfondo modale (%)'), type: 'range', min: 100, max: 200, step: 5 },
    { key: 'modal_font_family', label: t('Font modale'), type: 'font-family' },

    { type: 'separator', label: t('Tipografia') },
    { type: 'typography', label: t('Titolo modale'),
      presetKey: 'typography_preset',
      responsiveKeys: ['size', 'letterSpacing'],
      letterSpacingUnit: 'em',
      keys: {
        size:          'modal_title_size',
        weight:        'modal_title_weight',
        letterSpacing: 'modal_title_letter_spacing',
        color:         'modal_title_color',
      },
      sizeMin: 14, sizeMax: 48, sizeStep: 1,
    },
    { type: 'typography', label: t('Pulsante'),
      presetKey: 'typography_preset',
      responsiveKeys: ['letterSpacing'],
      letterSpacingUnit: 'em',
      keys: {
        weight:        'button_weight',
        letterSpacing: 'button_letter_spacing',
      },
    },
    { key: 'modal_title_uppercase', label: t('Titolo maiuscolo'), type: 'toggle' },

    { type: 'separator', label: t('Overlay & Animazione') },
    { key: 'modal_overlay', label: t('Oscuramento sfondo'), type: 'range', min: 0, max: 100, step: 5 },
    { key: 'popup_overlay_blur', label: t('Sfocatura overlay'), type: 'range', min: 0, max: 20, step: 1 },
    { key: 'popup_animation', label: t('Animazione apertura'), type: 'select', options: [
      { value: 'fade', label: t('Fade') },
      { value: 'slide-up', label: t('Slide Up') },
      { value: 'slide-down', label: t('Slide Down') },
      { value: 'zoom', label: t('Zoom') },
      { value: 'flip', label: t('Flip') },
    ]},

    { type: 'separator', label: t('Effetti avanzati modale') },
    { key: 'modal_rotation', label: t('Rotazione modale (gradi)'), type: 'range', min: -10, max: 10, step: 0.5 },
    { key: 'modal_perspective', label: t('Prospettiva 3D (px)'), type: 'range', min: 0, max: 2000, step: 100 },
    { key: 'modal_tilt_x', label: t('Tilt 3D asse X (gradi)'), type: 'range', min: -10, max: 10, step: 0.5 },
    { key: 'modal_glow_pulse', label: t('Glow pulsante (animazione bordo)'), type: 'toggle' },
    { key: 'modal_title_glow', label: t('Glow titolo'), type: 'toggle' },
    { key: 'modal_scanlines', label: t('Effetto scanlines (CRT)'), type: 'toggle' },
    { key: 'modal_terminal_prompt', label: t('Prompt terminale (> + cursore)'), type: 'toggle' },

    ...borderFields(),
  ],
};
