import { textEffectsFields, textEffectsDefaults, borderFields, borderDefault, borderHoverDefault, borderEffectDefaults, withHover, wowEffectsFields, wowEffectsDefaults } from './_shared';
import { shadowField } from './_shared.js';
import { t } from '@/i18n';

/**
 * Tile Portfolio — split CONTENUTO/STILE (regola universale Olobuild).
 *   fields[]      → sorgente dati (manual/posts/custom_taxonomy), post_type/taxonomy/posts_per_page,
 *                   items array (manual), modalità layout, colonne, proporzione immagine,
 *                   hover_effect/animation (comportamento), posizione caption, magic toggles
 *                   (search/cursor/stagger/dim/ribbon/year/index/external badge/grayscale),
 *                   visibilità filter bar + label, visibilità show_* (title/category/excerpt)
 *   styleFields[] → preset, sfondo, tipografia, effect_color/intensity (preset accent),
 *                   gap, raggio bordi card, carousel speed/pause, tipografia font/peso/transform/spacing,
 *                   colori titolo/testo/sfondo/accent/overlay, opacità overlay, container padding/raggio,
 *                   stile filtri + colori filtri, text effects, ombra, bordi
 *   AVANZATE      → meta tecnico (id/class/condizioni)
 */
export default {
  type: 'portfolio',
  name: t('Portfolio'),
  icon: 'dashicons-portfolio',
  category: 'dynamic',
  defaults: {
    bg: { type: 'none' },
    typography_preset: '',
    preset: 'editorial-magazine',
    // Sorgente dati
    source: 'manual',
    post_type: 'post',
    taxonomy: 'category',
    posts_per_page: '12',
    // Layout
    layout: 'grid',
    columns: '3',
    gap: '20',
    image_ratio: '4:3',
    // Filtri
    filter_bar: true,
    filter_style: 'buttons',
    filter_all_label: 'Tutti',
    filter_color: '',
    filter_active_color: '',
    // Effetti
    hover_effect: 'fade',
    animation: 'fade',
    // Caption
    caption_position: 'overlay',
    caption_corner: 'bottom-left',
    // Magic features
    enable_search: false,
    search_placeholder: 'Cerca progetto…',
    cursor_label_enabled: false,
    cursor_label_text: 'Vedi progetto',
    stagger_entrance: false,
    stagger_delay: 80,
    dim_others: false,
    featured_ribbon: false,
    featured_ribbon_text: 'Featured',
    year_stamp: false,
    index_numbering: false,
    external_link_badge: false,
    grayscale_default: false,
    // Show
    show_title: true,
    show_category: true,
    show_excerpt: false,
    // Tipografia
    font_family: 'inherit',
    font_weight: '500',
    text_transform: 'none',
    letter_spacing: 0,
    // Colori
    title_color: '',
    text_color: '',
    bg_color: '',
    accent_color: '',
    overlay_color: '#000000',
    overlay_opacity: '80',
    border_radius: '8',
    // Container
    container_padding: { top: 0, right: 0, bottom: 0, left: 0 },
    container_radius: { tl: 0, tr: 0, br: 0, bl: 0 },
    // Effetti preset
    effect_color: '',
    effect_intensity: 'medium',
    effect_speed: 0,
    // Carousel
    carousel_speed: 30,
    carousel_pause_on_hover: true,
    items: [
      { id: 'pf-1', title: t('Progetto Alpha'), image_url: '', category: 'Design', description: t('Un progetto di design innovativo.'), link_url: '', year: '2026', featured: true },
      { id: 'pf-2', title: t('Progetto Beta'), image_url: '', category: 'Web', description: t('Sviluppo web full-stack.'), link_url: '', year: '2026', featured: false },
      { id: 'pf-3', title: t('Progetto Gamma'), image_url: '', category: 'Design', description: t('Brand identity completa.'), link_url: '', year: '2025', featured: false },
      { id: 'pf-4', title: t('Progetto Delta'), image_url: '', category: 'Foto', description: t('Servizio fotografico professionale.'), link_url: '', year: '2025', featured: true },
      { id: 'pf-5', title: t('Progetto Epsilon'), image_url: '', category: 'Web', description: t('E-commerce moderno.'), link_url: '', year: '2024', featured: false },
      { id: 'pf-6', title: t('Progetto Zeta'), image_url: '', category: 'Foto', description: t('Reportage aziendale.'), link_url: '', year: '2024', featured: false },
    ],
    shadow: 'none',
    ...textEffectsDefaults,
    text_effect_target: 'title',
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
    ...wowEffectsDefaults,
  },

  // ─── CONTENUTO ─────────────────────────────────────────────
  fields: [
    { type: 'separator', label: t('Sorgente dati') },
    { key: 'source', label: t('Origine dati'), type: 'select', options: [
      { value: 'manual', label: t('Manuale') },
      { value: 'posts', label: t('Articoli WordPress') },
      { value: 'custom_taxonomy', label: t('Tassonomia personalizzata') },
    ]},
    { key: 'post_type', label: t('Tipo articolo'), type: 'select', optionsSource: 'postTypes', options: [],
      condition: { field: 'source', op: 'eq', value: 'posts' } },
    { key: 'taxonomy', label: t('Tassonomia'), type: 'select', optionsSource: 'taxonomies', options: [],
      condition: { field: 'source', op: 'in', value: ['posts', 'custom_taxonomy'] } },
    { key: 'posts_per_page', label: t('Numero articoli'), type: 'range', min: 1, max: 50, step: 1,
      condition: { field: 'source', op: 'in', value: ['posts', 'custom_taxonomy'] } },

    { key: 'items', label: t('Progetti'), type: 'content-items',
      condition: { field: 'source', op: 'eq', value: 'manual' },
      itemFields: [
        { key: 'title', label: t('Titolo'), type: 'text' },
        { key: 'image_url', label: t('Immagine'), type: 'image' },
        { key: 'category', label: t('Categoria'), type: 'text' },
        { key: 'description', label: t('Descrizione'), type: 'text' },
        { key: 'link_url', label: t('URL link'), type: 'link' },
        { key: 'year', label: t('Anno'), type: 'text', placeholder: '2026' },
        { key: 'featured', label: t('In evidenza'), type: 'toggle' },
      ],
      newItemDefaults: { title: t('Nuovo progetto'), image_url: '', category: '', description: '', link_url: '', year: '', featured: false },
      itemLabel: 'Progetto',
    },

    { type: 'separator', label: t('Layout') },
    { key: 'layout', label: t('Modalità layout'), type: 'select', options: [
      { value: 'grid',           label: t('Griglia uniforme') },
      { value: 'masonry',        label: t('Masonry classico') },
      { value: 'masonry-pin',    label: t('Pinterest Masonry') },
      { value: 'bento',          label: t('Bento asimmetrico') },
      { value: 'magazine',       label: t('Magazine (1 large + thumbs)') },
      { value: 'mosaic',         label: t('Mosaic art-direction') },
      { value: 'split-index',    label: t('Split Index (lista + preview)') },
      { value: 'carousel',       label: t('Carousel orizzontale') },
      { value: 'polaroid',       label: t('Polaroid Wall') },
      { value: 'postcard-stack', label: t('Postcard Stack 3D') },
    ]},
    { key: 'columns', label: t('Colonne'), type: 'range', min: 1, max: 6, step: 1,
      condition: { field: 'layout', op: 'in', value: ['grid', 'masonry', 'masonry-pin', 'bento', 'mosaic', 'polaroid'] } },
    { key: 'image_ratio', label: t('Proporzione immagine'), type: 'select', options: [
      { value: '1:1', label: t('1:1 Quadrato') },
      { value: '4:3', label: '4:3' },
      { value: '16:9', label: '16:9' },
      { value: '3:2', label: '3:2' },
      { value: '3:4', label: '3:4 Verticale' },
      { value: 'auto', label: t('Automatico') },
    ]},

    { type: 'separator', label: t('Hover effect (comportamento)') },
    { key: 'hover_effect', label: t('Effetto hover'), type: 'select', options: [
      { value: 'none',          label: t('Nessuno') },
      { value: 'zoom',          label: t('Zoom') },
      { value: 'fade',          label: t('Dissolvenza') },
      { value: 'slide-up',      label: t('Scorrimento dal basso') },
      { value: 'overlay',       label: t('Overlay completo') },
      { value: 'reveal-mask',   label: t('🪄 Reveal Mask (clip da centro)') },
      { value: 'tilt-3d',       label: t('🪄 Tilt 3D Parallax') },
      { value: 'color-splash',  label: t('🪄 Color Splash (B&W → color)') },
      { value: 'glitch-rgb',    label: t('🪄 Glitch RGB') },
      { value: 'cinemagraph',   label: t('🪄 Cinemagraph (zoom continuo)') },
      { value: 'image-cycle',   label: t('🪄 Image Cycle (sequenza)') },
      { value: 'caption-corner', label: t('🪄 Caption from Corner') },
    ]},
    { key: 'caption_corner', label: t('Angolo caption'), type: 'select',
      condition: { field: 'hover_effect', value: 'caption-corner' }, options: [
      { value: 'bottom-left',  label: t('Basso sinistra') },
      { value: 'bottom-right', label: t('Basso destra') },
      { value: 'top-left',     label: t('Alto sinistra') },
      { value: 'top-right',    label: t('Alto destra') },
    ]},
    { key: 'caption_position', label: t('Posizione testo'), type: 'select', options: [
      { value: 'below',   label: t('Sotto immagine') },
      { value: 'overlay', label: t('Overlay (su hover)') },
      { value: 'always',  label: t('Sempre visibile sopra') },
      { value: 'diagonal', label: t('Diagonale (basso-sx)') },
    ]},
    { key: 'animation', label: t('Animazione filtro'), type: 'select', options: [
      { value: 'fade', label: t('Dissolvenza') },
      { value: 'scale', label: t('Scala') },
      { value: 'slide', label: t('Scorrimento') },
    ]},

    { type: 'separator', label: t('🪄 Magic features') },
    { key: 'enable_search',     label: t('Campo ricerca live'), type: 'toggle' },
    { key: 'search_placeholder', label: t('Placeholder ricerca'), type: 'text',
      condition: { field: 'enable_search', value: true } },
    { key: 'cursor_label_enabled', label: t('Cursore custom "Vedi progetto →"'), type: 'toggle' },
    { key: 'cursor_label_text', label: t('Testo cursore'), type: 'text',
      condition: { field: 'cursor_label_enabled', value: true } },
    { key: 'stagger_entrance',  label: t('Entrata stagger (al scroll)'), type: 'toggle' },
    { key: 'dim_others',        label: t('Sfuma le altre card al hover'), type: 'toggle' },
    { key: 'featured_ribbon',   label: t('Ribbon "Featured" su item evidenziati'), type: 'toggle' },
    { key: 'featured_ribbon_text', label: t('Testo ribbon'), type: 'text',
      condition: { field: 'featured_ribbon', value: true } },
    { key: 'year_stamp',        label: t('Anno overlay grande (Awwwards-style)'), type: 'toggle' },
    { key: 'index_numbering',   label: t('Numerazione 01/N (Editorial)'), type: 'toggle' },
    { key: 'external_link_badge', label: t('Badge ↗ se URL esterno'), type: 'toggle' },
    { key: 'grayscale_default', label: t('B&W di default (color al hover)'), type: 'toggle',
      condition: { field: 'hover_effect', op: 'neq', value: 'color-splash' } },

    { type: 'separator', label: t('Barra filtri') },
    { key: 'filter_bar', label: t('Mostra barra filtri'), type: 'toggle' },
    { key: 'filter_all_label', label: 'Etichetta "Tutti"', type: 'text',
      condition: { field: 'filter_bar', value: true } },

    { type: 'separator', label: t('Contenuto') },
    { key: 'show_title', label: t('Mostra titolo'), type: 'toggle' },
    { key: 'show_category', label: t('Mostra categoria'), type: 'toggle' },
    { key: 'show_excerpt', label: t('Mostra descrizione'), type: 'toggle' },
  ],

  // ─── STILE ─────────────────────────────────────────────────
  styleFields: [
    { type: 'separator', label: t('Preset stilistico') },
    { key: 'preset', label: t('Stile'), type: 'select', options: [
      { value: 'editorial-magazine', label: t('Editorial Magazine') },
      { value: 'bento-asymmetric',   label: t('Bento Asymmetric') },
      { value: 'pinterest-masonry',  label: t('Pinterest Masonry') },
      { value: 'cinema-showcase',    label: t('Cinema Showcase') },
      { value: 'studio-index',       label: t('Studio Index Split') },
      { value: 'polaroid-wall',      label: t('Polaroid Wall') },
      { value: 'postcard-stack',     label: t('Postcard Stack 3D') },
      { value: 'dribbble-cards',     label: t('Dribbble Cards') },
      { value: 'awwwards-hero',      label: t('Awwwards Hero (numerati)') },
      { value: 'photographer-mosaic', label: t('Photographer Mosaic') },
      { value: 'agency-tape',        label: t('Agency Tape (carousel)') },
      { value: 'architect-line',     label: t('Architect Wireframe') },
      { value: 'custom',             label: t('Personalizzato') },
    ]},
    { key: 'typography_preset', label: t('Stile tipografico'), type: 'select', optionsSource: 'globalTypography' },
    { key: 'effect_color', label: t('Colore accento preset'), type: 'color',
      condition: { field: 'preset', op: 'in', value: ['awwwards-hero', 'cinema-showcase', 'studio-index', 'architect-line', 'dribbble-cards'] } },
    { key: 'effect_intensity', label: t('Intensità effetto'), type: 'select', options: [
      { value: 'low',    label: t('Bassa') },
      { value: 'medium', label: t('Media') },
      { value: 'high',   label: t('Alta') },
    ], condition: { field: 'preset', op: 'in', value: ['postcard-stack', 'polaroid-wall', 'cinema-showcase'] } },

    ...textEffectsFields([
      { value: 'title', label: t('Solo Titolo') },
      { value: 'description', label: t('Solo Descrizione') },
      { value: 'all', label: t('Tutti gli elementi testuali') },
    ]),

    { type: 'separator', label: t('Layout — aspetto') },
    { key: 'gap', label: t('Gap (px)'), type: 'range', min: 0, max: 60, step: 2 },
    withHover({ key: 'border_radius', label: t('Raggio bordi card (px)'), type: 'border-radius' }),

    { type: 'separator', label: t('Carousel — aspetto') },
    { key: 'carousel_speed', label: t('Velocità (s per loop)'), type: 'range', min: 10, max: 120, step: 5,
      condition: { field: 'layout', value: 'carousel' } },
    { key: 'carousel_pause_on_hover', label: t('Pausa al passaggio mouse'), type: 'toggle',
      condition: { field: 'layout', value: 'carousel' } },

    { type: 'separator', label: t('Magic — parametri visivi') },
    { key: 'stagger_delay', label: t('Ritardo stagger (ms)'), type: 'range', min: 30, max: 300, step: 10,
      condition: { field: 'stagger_entrance', value: true } },

    { type: 'separator', label: t('Barra filtri — stile') },
    { key: 'filter_style', label: t('Stile filtri'), type: 'select', options: [
      { value: 'buttons', label: t('Pulsanti') },
      { value: 'pills', label: t('Pillole') },
      { value: 'underline', label: t('Sottolineato') },
      { value: 'dropdown', label: t('Dropdown') },
    ], condition: { field: 'filter_bar', value: true } },
    { key: 'filter_color', label: t('Colore filtri'), type: 'color',
      condition: { field: 'filter_bar', value: true } },
    { key: 'filter_active_color', label: t('Colore filtro attivo'), type: 'color',
      condition: { field: 'filter_bar', value: true } },

    { type: 'separator', label: t('Tipografia') },
    { type: 'typography', label: t('Titolo'),
      presetKey: 'typography_preset',
      keys: {
        family: 'font_family',
        weight: 'font_weight',
        color:  'title_color',
      },
    },
    { type: 'typography', label: t('Testo'),
      presetKey: 'typography_preset',
      keys: {
        transform:     'text_transform',
        letterSpacing: 'letter_spacing',
        color:         'text_color',
      },
    },
    { type: 'typography', label: t('Accento'),
      presetKey: 'typography_preset',
      keys: {
        color: 'accent_color',
      },
    },

    { type: 'separator', label: t('Colori') },
    { key: 'bg_color', label: t('Sfondo container'), type: 'color' },
    { key: 'overlay_color', label: t('Colore overlay'), type: 'color' },
    { key: 'overlay_opacity', label: t('Opacità overlay (%)'), type: 'range', min: 0, max: 100, step: 5 },

    { type: 'separator', label: t('Container') },
    { key: 'container_padding', label: t('Padding container'), type: 'spacing', max: 60 },
    { key: 'container_radius', label: t('Raggio bordi container'), type: 'border-radius' },

    ...shadowField,
    ...wowEffectsFields(),
    ...borderFields(),
  ],
};
