import { textEffectsFields, textEffectsDefaults, borderFields, borderDefault, borderHoverDefault, borderEffectDefaults } from './_shared';
import { shadowField } from './_shared.js';

export default {
  type: 'portfolio',
  name: 'Portfolio',
  icon: 'dashicons-portfolio',
  category: 'dynamic',
  defaults: {
    source: 'manual',
    post_type: 'post',
    taxonomy: 'category',
    posts_per_page: '12',
    columns: '3',
    gap: '20',
    filter_bar: true,
    filter_style: 'buttons',
    filter_all_label: 'Tutti',
    filter_color: '',
    filter_active_color: '',
    layout: 'grid',
    hover_effect: 'fade',
    show_title: true,
    show_category: true,
    show_excerpt: false,
    title_color: '',
    text_color: '',
    overlay_color: '#000000',
    overlay_opacity: '80',
    image_ratio: '4:3',
    border_radius: '8',
    animation: 'fade',
    items: [
      { id: 'pf-1', title: 'Progetto Alpha', image_url: '', category: 'Design', description: 'Un progetto di design innovativo.', link_url: '' },
      { id: 'pf-2', title: 'Progetto Beta', image_url: '', category: 'Web', description: 'Sviluppo web full-stack.', link_url: '' },
      { id: 'pf-3', title: 'Progetto Gamma', image_url: '', category: 'Design', description: 'Brand identity completa.', link_url: '' },
      { id: 'pf-4', title: 'Progetto Delta', image_url: '', category: 'Foto', description: 'Servizio fotografico professionale.', link_url: '' },
      { id: 'pf-5', title: 'Progetto Epsilon', image_url: '', category: 'Web', description: 'E-commerce moderno.', link_url: '' },
      { id: 'pf-6', title: 'Progetto Zeta', image_url: '', category: 'Foto', description: 'Reportage aziendale.', link_url: '' },
    ],
    shadow: 'none',
    ...textEffectsDefaults,
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
  },
  fields: [
    { key: 'source', label: 'Origine dati', type: 'select', options: [
      { value: 'manual', label: 'Manuale' },
      { value: 'posts', label: 'Articoli WordPress' },
      { value: 'custom_taxonomy', label: 'Tassonomia personalizzata' },
    ]},
    { key: 'post_type', label: 'Tipo articolo', type: 'text',
      condition: { field: 'source', op: 'eq', value: 'posts' } },
    { key: 'taxonomy', label: 'Tassonomia', type: 'text',
      condition: { field: 'source', op: 'in', value: ['posts', 'custom_taxonomy'] } },
    { key: 'posts_per_page', label: 'Numero articoli', type: 'range', min: 1, max: 50, step: 1,
      condition: { field: 'source', op: 'in', value: ['posts', 'custom_taxonomy'] } },

    { key: 'items', label: 'Progetti', type: 'content-items',
      condition: { field: 'source', op: 'eq', value: 'manual' },
      itemFields: [
        { key: 'title', label: 'Titolo', type: 'text' },
        { key: 'image_url', label: 'Immagine', type: 'image' },
        { key: 'category', label: 'Categoria', type: 'text' },
        { key: 'description', label: 'Descrizione', type: 'text' },
        { key: 'link_url', label: 'URL link', type: 'text' },
      ],
      newItemDefaults: { title: 'Nuovo progetto', image_url: '', category: '', description: '', link_url: '' },
      itemLabel: 'Progetto',
    },

    { type: 'separator', label: 'Layout' },
    { key: 'columns', label: 'Colonne', type: 'range', min: 1, max: 6, step: 1 },
    { key: 'gap', label: 'Gap (px)', type: 'range', min: 0, max: 60, step: 2 },
    { key: 'layout', label: 'Layout', type: 'select', options: [
      { value: 'grid', label: 'Griglia' },
      { value: 'masonry', label: 'Masonry' },
    ]},
    { key: 'image_ratio', label: 'Proporzione immagine', type: 'select', options: [
      { value: '1:1', label: '1:1 Quadrato' },
      { value: '4:3', label: '4:3' },
      { value: '16:9', label: '16:9' },
      { value: '3:2', label: '3:2' },
      { value: 'auto', label: 'Automatico' },
    ]},
    { key: 'border_radius', label: 'Raggio bordi (px)', type: 'border-radius' },
    { key: 'border_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius' },

    { type: 'separator', label: 'Barra filtri' },
    { key: 'filter_bar', label: 'Mostra barra filtri', type: 'toggle' },
    { key: 'filter_style', label: 'Stile filtri', type: 'select', options: [
      { value: 'buttons', label: 'Pulsanti' },
      { value: 'pills', label: 'Pillole' },
      { value: 'underline', label: 'Sottolineato' },
      { value: 'dropdown', label: 'Dropdown' },
    ], condition: { field: 'filter_bar', value: true } },
    { key: 'filter_all_label', label: 'Etichetta "Tutti"', type: 'text',
      condition: { field: 'filter_bar', value: true } },
    { key: 'filter_color', label: 'Colore filtri', type: 'color',
      condition: { field: 'filter_bar', value: true } },
    { key: 'filter_active_color', label: 'Colore filtro attivo', type: 'color',
      condition: { field: 'filter_bar', value: true } },

    { type: 'separator', label: 'Effetti' },
    { key: 'hover_effect', label: 'Effetto hover', type: 'select', options: [
      { value: 'none', label: 'Nessuno' },
      { value: 'zoom', label: 'Zoom' },
      { value: 'fade', label: 'Dissolvenza' },
      { value: 'slide-up', label: 'Scorrimento dal basso' },
      { value: 'overlay', label: 'Overlay' },
    ]},
    { key: 'animation', label: 'Animazione filtro', type: 'select', options: [
      { value: 'fade', label: 'Dissolvenza' },
      { value: 'scale', label: 'Scala' },
      { value: 'slide', label: 'Scorrimento' },
    ]},

    { type: 'separator', label: 'Contenuto' },
    { key: 'show_title', label: 'Mostra titolo', type: 'toggle' },
    { key: 'show_category', label: 'Mostra categoria', type: 'toggle' },
    { key: 'show_excerpt', label: 'Mostra descrizione', type: 'toggle' },

    { type: 'separator', label: 'Colori' },
    { key: 'title_color', label: 'Colore titolo', type: 'color' },
    { key: 'text_color', label: 'Colore testo', type: 'color' },
    { key: 'overlay_color', label: 'Colore overlay', type: 'color' },
    { key: 'overlay_opacity', label: 'Opacità overlay (%)', type: 'range', min: 0, max: 100, step: 5 },

    ...shadowField,
    ...textEffectsFields([
      { value: 'title', label: 'Solo Titolo' },
      { value: 'description', label: 'Solo Descrizione' },
      { value: 'all', label: 'Tutti gli elementi testuali' },
    ]),
    ...borderFields(),
  ],
};
