
import { borderFields, borderDefault, borderHoverDefault, borderEffectDefaults, wowEffectsFields, wowEffectsDefaults } from './_shared.js';
import { t } from '@/i18n';

/**
 * Tile PostMeta — split CONTENUTO/STILE.
 *   fields[]      → visibilità (date/author/categories/tags/comments/reading_time), format data, layout, separator, item_gap, icone, link autore/category
 *   styleFields[] → preset, bg, typo, effetti preset, tipografia (font/weight/transform/spacing), colori, container padding/radius, chip aspect
 */
export default {
  type: 'postmeta',
  name: t('Post Meta'),
  icon: 'dashicons-media-text',
  category: 'dynamic',
  defaults: {
    bg: { type: 'none' },
    typography_preset: '',
    preset: 'editorial-classic',
    show_date: true,
    show_author: true,
    show_categories: true,
    show_tags: false,
    show_comments_count: false,
    show_reading_time: false,
    date_format: 'd/m/Y',
    layout: 'inline',
    separator: ' · ',
    icon_style: 'none',
    text_color: '',
    link_color: '',
    icon_color: '',
    bg_color: '',
    font_size: '14',
    font_family: 'inherit',
    font_weight: '400',
    text_transform: 'none',
    letter_spacing: 0,
    item_gap: 0,
    chip_style: 'none',
    chip_bg: '',
    chip_padding_x: 0,
    chip_padding_y: 0,
    chip_radius: 0,
    container_padding: { top: 0, right: 0, bottom: 0, left: 0 },
    container_radius: { tl: 0, tr: 0, br: 0, bl: 0 },
    effect_color: '',
    effect_intensity: 'medium',
    effect_speed: 0,
    author_link: true,
    category_link: true,
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
    ...wowEffectsDefaults,
  },

  fields: [
    { type: 'separator', label: t('Elementi da mostrare') },
    { key: 'show_date', label: t('Mostra data'), type: 'toggle' },
    { key: 'show_author', label: t('Mostra autore'), type: 'toggle' },
    { key: 'show_categories', label: t('Mostra categorie'), type: 'toggle' },
    { key: 'show_tags', label: t('Mostra tag'), type: 'toggle' },
    { key: 'show_comments_count', label: t('Mostra numero commenti'), type: 'toggle' },
    { key: 'show_reading_time', label: t('Mostra tempo di lettura'), type: 'toggle' },

    { type: 'separator', label: t('Formato') },
    { key: 'date_format', label: t('Formato data'), type: 'select', options: [
      { value: 'd/m/Y', label: t('05/03/2026') },
      { value: 'j F Y', label: t('5 Marzo 2026') },
      { value: 'F j, Y', label: t('Marzo 5, 2026') },
      { value: 'Y-m-d', label: t('2026-03-05') },
      { value: 'd M Y', label: t('05 Mar 2026') },
    ], condition: { field: 'show_date', value: true } },
    { key: 'layout', label: t('Layout'), type: 'select', options: [
      { value: 'inline', label: t('In linea') },
      { value: 'stacked', label: t('Impilato') },
    ]},
    { key: 'separator', label: t('Separatore'), type: 'text',
      condition: { field: 'layout', value: 'inline' } },
    { key: 'icon_style', label: t('Icone'), type: 'select', options: [
      { value: 'none', label: t('Nessuna') },
      { value: 'before', label: t('Prima del testo') },
    ]},

    { type: 'separator', label: t('Link') },
    { key: 'author_link', label: t('Link autore'), type: 'toggle',
      condition: { field: 'show_author', value: true } },
    { key: 'category_link', label: t('Link categorie'), type: 'toggle',
      condition: { field: 'show_categories', value: true } },
  ],

  styleFields: [
    { type: 'separator', label: t('Preset stilistico') },
    { key: 'preset', label: t('Stile'), type: 'select', options: [
      { value: 'editorial-classic',  label: t('Editorial Classic') },
      { value: 'magazine-bold',      label: t('Magazine Bold') },
      { value: 'minimal-mono',       label: t('Minimal Mono') },
      { value: 'tag-pills',          label: t('Tag Pills') },
      { value: 'underline-animated', label: t('Underline Animated') },
      { value: 'glass-floating',     label: t('Glass Floating') },
      { value: 'neon-cyber',         label: t('Neon Cyberpunk') },
      { value: 'brutalist-stamp',    label: t('Brutalist Stamp') },
      { value: 'gradient-glow',      label: t('Gradient Glow') },
      { value: 'sticker-scrap',      label: t('Sticker Scrapbook') },
      { value: 'retro-terminal',     label: t('Retro Terminal') },
      { value: 'tilt-3d',            label: t('3D Tilt Chip') },
      { value: 'custom',             label: t('Personalizzato') },
    ]},
    { key: 'typography_preset', label: t('Stile tipografico'), type: 'select', optionsSource: 'globalTypography' },
    { key: 'effect_color', label: t('Colore effetto (neon/brutalist/glow)'), type: 'color',
      condition: { field: 'preset', op: 'in', value: ['neon-cyber', 'brutalist-stamp', 'gradient-glow', 'glass-floating'] } },
    { key: 'effect_intensity', label: t('Intensità effetto'), type: 'select', options: [
      { value: 'low',    label: t('Bassa') },
      { value: 'medium', label: t('Media') },
      { value: 'high',   label: t('Alta') },
    ], condition: { field: 'preset', op: 'in', value: ['neon-cyber', 'brutalist-stamp', 'glass-floating', 'tilt-3d'] } },
    { key: 'effect_speed', label: t('Velocità animazione (ms, 0 = default)'), type: 'range', min: 0, max: 5000, step: 100,
      condition: { field: 'preset', op: 'in', value: ['neon-cyber', 'gradient-glow', 'retro-terminal'] } },

    { type: 'separator', label: t('Spaziatura') },
    { key: 'item_gap', label: t('Spazio tra elementi (px)'), type: 'range', min: 0, max: 40, step: 2 },

    { type: 'separator', label: t('Tipografia') },
    { type: 'typography', label: t('Voci'),
      presetKey: 'typography_preset',
      responsiveKeys: ['size'],
      keys: {
        size:          'font_size',
        family:        'font_family',
        weight:        'font_weight',
        transform:     'text_transform',
        letterSpacing: 'letter_spacing',
        color:         'text_color',
      },
      sizeMin: 10, sizeMax: 24, sizeStep: 1,
    },
    { type: 'typography', label: t('Link'),
      presetKey: 'typography_preset',
      keys: {
        color: 'link_color',
      },
    },

    { type: 'separator', label: t('Colori') },
    { key: 'icon_color', label: t('Colore icone'), type: 'color',
      condition: { field: 'icon_style', value: 'before' } },
    { key: 'bg_color', label: t('Colore sfondo container'), type: 'color' },

    { type: 'separator', label: t('Container') },
    { key: 'container_padding', label: t('Padding container'), type: 'spacing', max: 32 },
    { key: 'container_radius', label: t('Raggio bordi container'), type: 'border-radius' },

    { type: 'separator', label: t('Chip per item') },
    { key: 'chip_style', label: t('Stile chip'), type: 'select', options: [
      { value: 'none',    label: t('Nessuno (testo)') },
      { value: 'pill',    label: t('Pill rounded') },
      { value: 'tag',     label: t('Tag squadrato') },
      { value: 'sticker', label: t('Sticker rotato') },
      { value: 'chip-3d', label: t('Chip 3D') },
    ]},
    { key: 'chip_bg', label: t('Sfondo chip'), type: 'color',
      condition: { field: 'chip_style', op: 'neq', value: 'none' } },
    { key: 'chip_padding_x', label: t('Padding orizzontale chip (px)'), type: 'range', min: 0, max: 24, step: 1,
      condition: { field: 'chip_style', op: 'neq', value: 'none' } },
    { key: 'chip_padding_y', label: t('Padding verticale chip (px)'), type: 'range', min: 0, max: 16, step: 1,
      condition: { field: 'chip_style', op: 'neq', value: 'none' } },
    { key: 'chip_radius', label: t('Raggio bordi chip (px)'), type: 'border-radius',
      condition: { field: 'chip_style', op: 'neq', value: 'none' } },

    ...wowEffectsFields(),
    ...borderFields(),
  ],
};
