export default {
  type: 'postmeta',
  name: 'Post Meta',
  icon: 'dashicons-media-text',
  category: 'dynamic',
  defaults: {
    show_date: true,
    show_author: true,
    show_categories: true,
    show_tags: false,
    show_comments_count: false,
    show_reading_time: false,
    date_format: 'd/m/Y',
    layout: 'inline',
    separator: ' · ',
    icon_style: 'none',
    text_color: '',
    link_color: '',
    icon_color: '',
    font_size: '14',
    author_link: true,
    category_link: true,
  },
  fields: [
    { type: 'separator', label: 'Elementi da mostrare' },
    { key: 'show_date', label: 'Mostra data', type: 'toggle' },
    { key: 'show_author', label: 'Mostra autore', type: 'toggle' },
    { key: 'show_categories', label: 'Mostra categorie', type: 'toggle' },
    { key: 'show_tags', label: 'Mostra tag', type: 'toggle' },
    { key: 'show_comments_count', label: 'Mostra numero commenti', type: 'toggle' },
    { key: 'show_reading_time', label: 'Mostra tempo di lettura', type: 'toggle' },

    { type: 'separator', label: 'Formato' },
    { key: 'date_format', label: 'Formato data', type: 'select', options: [
      { value: 'd/m/Y', label: '05/03/2026' },
      { value: 'j F Y', label: '5 Marzo 2026' },
      { value: 'F j, Y', label: 'Marzo 5, 2026' },
      { value: 'Y-m-d', label: '2026-03-05' },
      { value: 'd M Y', label: '05 Mar 2026' },
    ], condition: { field: 'show_date', value: true } },
    { key: 'layout', label: 'Layout', type: 'select', options: [
      { value: 'inline', label: 'In linea' },
      { value: 'stacked', label: 'Impilato' },
    ]},
    { key: 'separator', label: 'Separatore', type: 'text',
      condition: { field: 'layout', value: 'inline' } },
    { key: 'icon_style', label: 'Icone', type: 'select', options: [
      { value: 'none', label: 'Nessuna' },
      { value: 'before', label: 'Prima del testo' },
    ]},

    { type: 'separator', label: 'Link' },
    { key: 'author_link', label: 'Link autore', type: 'toggle',
      condition: { field: 'show_author', value: true } },
    { key: 'category_link', label: 'Link categorie', type: 'toggle',
      condition: { field: 'show_categories', value: true } },

    { type: 'separator', label: 'Stile' },
    { key: 'text_color', label: 'Colore testo', type: 'color' },
    { key: 'link_color', label: 'Colore link', type: 'color' },
    { key: 'icon_color', label: 'Colore icone', type: 'color',
      condition: { field: 'icon_style', value: 'before' } },
    { key: 'font_size', label: 'Dimensione font (px)', type: 'range', min: 10, max: 24, step: 1 },
  ],
};
