import { shadowField, conditionFields, conditionDefaults } from './_shared.js';

export default {
  type: 'queryloop',
  name: 'Query Loop',
  icon: 'dashicons-database',
  category: 'dynamic',
  defaults: {
    post_type: 'post',
    custom_post_type: '',
    posts_per_page: '6',
    orderby: 'date',
    order: 'DESC',
    taxonomy: '',
    terms: '',
    tax_relation: 'IN',
    second_taxonomy: '',
    second_terms: '',
    offset: '0',
    exclude_current: true,
    include_ids: '',
    exclude_ids: '',
    author_ids: '',
    sticky_posts: 'include',
    date_after: '',
    date_before: '',
    meta_key: '',
    meta_value: '',
    meta_compare: '=',
    meta_type: 'CHAR',
    search_keyword: '',
    layout: 'grid',
    columns: '3',
    gap: '30',
    show_image: true,
    show_title: true,
    show_excerpt: true,
    show_date: true,
    show_author: false,
    show_category: true,
    show_read_more: true,
    read_more_text: 'Leggi tutto',
    excerpt_length: '20',
    image_ratio: '16:9',
    pagination_type: 'none',
    title_tag: 'h3',
    title_color: '',
    text_color: '',
    meta_color: '',
    link_color: '',
    bg_color: '',
    hover_bg: '',
    card_style: 'none',
    loop_template_id: '',
    shadow: 'none',
    ...conditionDefaults,
  },
  fields: [
    { type: 'separator', label: 'Query' },
    { key: 'post_type', label: 'Tipo contenuto', type: 'select', options: [
      { value: 'post', label: 'Articoli' },
      { value: 'page', label: 'Pagine' },
      { value: 'custom', label: 'Custom Post Type' },
    ] },
    { key: 'custom_post_type', label: 'CPT slug', type: 'text', placeholder: 'es: product, portfolio',
      condition: { field: 'post_type', op: 'eq', value: 'custom' } },
    { key: 'posts_per_page', label: 'Numero di post', type: 'number', min: 1, max: 100 },
    { key: 'orderby', label: 'Ordina per', type: 'select', options: [
      { value: 'date', label: 'Data' },
      { value: 'title', label: 'Titolo' },
      { value: 'menu_order', label: 'Ordine menu' },
      { value: 'rand', label: 'Casuale' },
      { value: 'modified', label: 'Data modifica' },
      { value: 'comment_count', label: 'N. commenti' },
      { value: 'meta_value', label: 'Valore meta' },
      { value: 'meta_value_num', label: 'Valore meta (numerico)' },
    ] },
    { key: 'order', label: 'Direzione', type: 'select', options: [
      { value: 'DESC', label: 'Decrescente' },
      { value: 'ASC', label: 'Crescente' },
    ] },
    { key: 'taxonomy', label: 'Tassonomia', type: 'text', placeholder: 'category' },
    { key: 'terms', label: 'Termini (separati da virgola)', type: 'text', placeholder: 'news, tutorial' },
    { key: 'tax_relation', label: 'Relazione tassonomia', type: 'select', options: [
      { value: 'IN', label: 'IN (qualsiasi termine)' },
      { value: 'AND', label: 'AND (tutti i termini)' },
      { value: 'NOT IN', label: 'NOT IN (escludi)' },
    ] },
    { key: 'second_taxonomy', label: 'Seconda tassonomia', type: 'text', placeholder: 'post_tag' },
    { key: 'second_terms', label: 'Secondo gruppo termini', type: 'text', placeholder: 'tag1, tag2' },
    { key: 'offset', label: 'Offset', type: 'number', min: 0, max: 100 },
    { key: 'exclude_current', label: 'Escludi post corrente', type: 'toggle' },
    { key: 'include_ids', label: 'Includi solo ID (virgola)', type: 'text', placeholder: '12, 34, 56' },
    { key: 'exclude_ids', label: 'Escludi ID (virgola)', type: 'text', placeholder: '78, 90' },
    { key: 'author_ids', label: 'Autore ID (virgola)', type: 'text', placeholder: '1, 2' },
    { key: 'sticky_posts', label: 'Post in evidenza', type: 'select', options: [
      { value: 'include', label: 'Includi normalmente' },
      { value: 'only', label: 'Solo in evidenza' },
      { value: 'exclude', label: 'Escludi in evidenza' },
    ] },

    { type: 'separator', label: 'Filtro data' },
    { key: 'date_after', label: 'Dopo il', type: 'date' },
    { key: 'date_before', label: 'Prima del', type: 'date' },

    { type: 'separator', label: 'Filtro meta (ACF / custom field)' },
    { key: 'meta_key', label: 'Meta key', type: 'text', placeholder: 'prezzo, colore, etc.' },
    { key: 'meta_value', label: 'Meta value', type: 'text', placeholder: 'valore da confrontare' },
    { key: 'meta_compare', label: 'Operatore', type: 'select', options: [
      { value: '=', label: '= Uguale' },
      { value: '!=', label: '!= Diverso' },
      { value: '>', label: '> Maggiore' },
      { value: '<', label: '< Minore' },
      { value: '>=', label: '>= Maggiore o uguale' },
      { value: '<=', label: '<= Minore o uguale' },
      { value: 'LIKE', label: 'LIKE (contiene)' },
      { value: 'NOT LIKE', label: 'NOT LIKE' },
      { value: 'EXISTS', label: 'EXISTS (campo presente)' },
      { value: 'NOT EXISTS', label: 'NOT EXISTS' },
    ] },
    { key: 'meta_type', label: 'Tipo meta', type: 'select', options: [
      { value: 'CHAR', label: 'Testo' },
      { value: 'NUMERIC', label: 'Numerico' },
      { value: 'DATE', label: 'Data' },
      { value: 'DECIMAL', label: 'Decimale' },
    ] },
    { key: 'search_keyword', label: 'Keyword ricerca', type: 'text', placeholder: 'filtra per parola chiave' },

    { type: 'separator', label: 'Layout' },
    { key: 'layout', label: 'Layout', type: 'select', options: [
      { value: 'grid', label: 'Griglia' },
      { value: 'list', label: 'Lista' },
      { value: 'carousel', label: 'Carosello' },
      { value: 'masonry', label: 'Masonry' },
    ] },
    { key: 'columns', label: 'Colonne', type: 'range', min: 1, max: 6, step: 1,
      condition: { field: 'layout', op: 'in', value: ['grid', 'masonry'] } },
    { key: 'gap', label: 'Gap (px)', type: 'range', min: 0, max: 80, step: 5 },

    { type: 'separator', label: 'Loop Item Template' },
    { key: 'loop_template_id', label: 'Template ID (0 = card default)', type: 'text', placeholder: 'ID template Olobuild per loop item' },

    { type: 'separator', label: 'Contenuto card' },
    { key: 'show_image', label: 'Mostra immagine', type: 'toggle' },
    { key: 'image_ratio', label: 'Proporzione immagine', type: 'select', options: [
      { value: '16:9', label: '16:9' },
      { value: '4:3', label: '4:3' },
      { value: '1:1', label: '1:1' },
      { value: '3:2', label: '3:2' },
      { value: 'auto', label: 'Auto' },
    ], condition: { field: 'show_image', op: 'eq', value: true } },
    { key: 'show_title', label: 'Mostra titolo', type: 'toggle' },
    { key: 'title_tag', label: 'Tag titolo', type: 'select', options: [
      { value: 'h2', label: 'H2' },
      { value: 'h3', label: 'H3' },
      { value: 'h4', label: 'H4' },
      { value: 'h5', label: 'H5' },
      { value: 'h6', label: 'H6' },
    ], condition: { field: 'show_title', op: 'eq', value: true } },
    { key: 'show_excerpt', label: 'Mostra estratto', type: 'toggle' },
    { key: 'excerpt_length', label: 'Lunghezza estratto (parole)', type: 'number', min: 5, max: 100,
      condition: { field: 'show_excerpt', op: 'eq', value: true } },
    { key: 'show_date', label: 'Mostra data', type: 'toggle' },
    { key: 'show_author', label: 'Mostra autore', type: 'toggle' },
    { key: 'show_category', label: 'Mostra categoria', type: 'toggle' },
    { key: 'show_read_more', label: 'Mostra "Leggi tutto"', type: 'toggle' },
    { key: 'read_more_text', label: 'Testo link', type: 'text',
      condition: { field: 'show_read_more', op: 'eq', value: true } },

    { type: 'separator', label: 'Paginazione' },
    { key: 'pagination_type', label: 'Tipo paginazione', type: 'select', options: [
      { value: 'none', label: 'Nessuna' },
      { value: 'numbers', label: 'Numeri' },
      { value: 'loadmore', label: 'Carica altro' },
      { value: 'infinite', label: 'Scroll infinito' },
    ] },

    { type: 'separator', label: 'Stile card' },
    { key: 'card_style', label: 'Stile card', type: 'select', options: [
      { value: 'none', label: 'Nessuno' },
      { value: 'shadow', label: 'Ombra' },
      { value: 'border', label: 'Bordo' },
      { value: 'filled', label: 'Sfondo' },
    ] },

    { type: 'separator', label: 'Colori' },
    { key: 'title_color', label: 'Colore titolo', type: 'color' },
    { key: 'text_color', label: 'Colore testo', type: 'color' },
    { key: 'meta_color', label: 'Colore meta', type: 'color' },
    { key: 'link_color', label: 'Colore link', type: 'color' },
    { key: 'bg_color', label: 'Sfondo card', type: 'color' },
    { key: 'hover_bg', label: 'Sfondo hover', type: 'color' },

    ...shadowField,
    ...conditionFields,
  ],
};
