import { shadowField, withHover, wowEffectsFields, wowEffectsDefaults } from './_shared.js';
import { t } from '@/i18n';

/**
 * Tile QueryLoop — split CONTENUTO/STILE.
 *   fields[]      → query (post_type/cpt/posts_per_page/orderby/order/taxonomy/terms/relations/offset/exclude/include/author/sticky),
 *                   filtri data/meta/search, layout, image ratio, loop_template_id,
 *                   contenuto card (show_image/title/excerpt/date/author/category/read_more), magic features (reading time/badge/trending/comments/search/sort/tabs/skeleton),
 *                   paginazione type
 *   styleFields[] → preset, bg, typo, effetti preset, hover effect, stile card legacy, tipografia, colori, container padding/radius, shadow
 */
export default {
  type: 'queryloop',
  name: t('Query Loop'),
  icon: 'dashicons-database',
  category: 'dynamic',
  defaults: {
    bg: { type: 'none' },
    typography_preset: '',
    preset: 'magazine-trio',
    post_type: 'post',
    custom_post_type: '',
    posts_per_page: '6',
    orderby: 'date',
    order: 'DESC',
    taxonomy: '',
    terms: '',
    tax_relation: 'IN',
    second_taxonomy: '',
    second_terms: '',
    offset: '0',
    exclude_current: true,
    include_ids: '',
    exclude_ids: '',
    author_ids: '',
    sticky_posts: 'include',
    date_after: '',
    date_before: '',
    meta_key: '',
    meta_value: '',
    meta_compare: '=',
    meta_type: 'CHAR',
    search_keyword: '',
    layout: 'grid',
    columns: '3',
    gap: '30',
    image_ratio: '16:9',
    show_image: true,
    show_title: true,
    show_excerpt: true,
    show_date: true,
    show_author: false,
    show_category: true,
    show_read_more: true,
    read_more_text: 'Leggi tutto',
    excerpt_length: '20',
    title_tag: 'h3',
    show_reading_time: false,
    new_badge: false,
    new_badge_days: 7,
    new_badge_text: 'New',
    trending_badge: false,
    show_comment_count: false,
    enable_search: false,
    search_placeholder: 'Cerca…',
    enable_sort_ui: false,
    enable_taxonomy_tabs: false,
    taxonomy_tabs_taxonomy: 'category',
    timeline_group_by: 'month',
    sticky_filter_rail: false,
    skeleton_loading: false,
    hover_effect: 'none',
    pagination_type: 'none',
    font_family: 'inherit',
    font_weight: '500',
    title_weight: '700',
    text_transform: 'none',
    letter_spacing: 0,
    title_color: '',
    text_color: '',
    meta_color: '',
    link_color: '',
    bg_color: '',
    hover_bg: '',
    accent_color: '',
    overlay_color: '#000000',
    overlay_opacity: 60,
    container_padding: { top: 0, right: 0, bottom: 0, left: 0 },
    container_radius: { tl: 0, tr: 0, br: 0, bl: 0 },
    card_radius: { tl: 8, tr: 8, br: 8, bl: 8 },
    effect_color: '',
    effect_intensity: 'medium',
    effect_speed: 0,
    card_style: 'none',
    loop_template_id: '',
    shadow: 'none',
    ...wowEffectsDefaults,
  },

  fields: [
    { type: 'separator', label: t('Query') },
    { key: 'post_type', label: t('Tipo contenuto'), type: 'select', options: [
      { value: 'post', label: t('Articoli') },
      { value: 'page', label: t('Pagine') },
      { value: 'custom', label: t('Custom Post Type') },
    ]},
    { key: 'custom_post_type', label: t('CPT slug'), type: 'text', placeholder: t('es: product, portfolio'),
      condition: { field: 'post_type', op: 'eq', value: 'custom' } },
    { key: 'posts_per_page', label: t('Numero di post'), type: 'number', min: 1, max: 100 },
    { key: 'orderby', label: t('Ordina per'), type: 'select', options: [
      { value: 'date', label: t('Data') },
      { value: 'title', label: t('Titolo') },
      { value: 'menu_order', label: t('Ordine menu') },
      { value: 'rand', label: t('Casuale') },
      { value: 'modified', label: t('Data modifica') },
      { value: 'comment_count', label: t('N. commenti') },
      { value: 'meta_value', label: t('Valore meta') },
      { value: 'meta_value_num', label: t('Valore meta (numerico)') },
    ]},
    { key: 'order', label: t('Direzione'), type: 'select', options: [
      { value: 'DESC', label: t('Decrescente') },
      { value: 'ASC', label: t('Crescente') },
    ]},
    { key: 'taxonomy', label: t('Tassonomia'), type: 'text', placeholder: t('category') },
    { key: 'terms', label: t('Termini (separati da virgola)'), type: 'text', placeholder: t('news, tutorial') },
    { key: 'tax_relation', label: t('Relazione tassonomia'), type: 'select', options: [
      { value: 'IN', label: t('IN (qualsiasi termine)') },
      { value: 'AND', label: t('AND (tutti i termini)') },
      { value: 'NOT IN', label: t('NOT IN (escludi)') },
    ]},
    { key: 'second_taxonomy', label: t('Seconda tassonomia'), type: 'text', placeholder: t('post_tag') },
    { key: 'second_terms', label: t('Secondo gruppo termini'), type: 'text', placeholder: t('tag1, tag2') },
    { key: 'offset', label: t('Offset'), type: 'number', min: 0, max: 100 },
    { key: 'exclude_current', label: t('Escludi post corrente'), type: 'toggle' },
    { key: 'include_ids', label: t('Includi solo ID (virgola)'), type: 'text', placeholder: t('12, 34, 56') },
    { key: 'exclude_ids', label: t('Escludi ID (virgola)'), type: 'text', placeholder: '78, 90' },
    { key: 'author_ids', label: t('Autore ID (virgola)'), type: 'text', placeholder: '1, 2' },
    { key: 'sticky_posts', label: t('Post in evidenza'), type: 'select', options: [
      { value: 'include', label: t('Includi normalmente') },
      { value: 'only', label: t('Solo in evidenza') },
      { value: 'exclude', label: t('Escludi in evidenza') },
    ]},

    { type: 'separator', label: t('Filtro data') },
    { key: 'date_after', label: t('Dopo il'), type: 'date' },
    { key: 'date_before', label: t('Prima del'), type: 'date' },

    { type: 'separator', label: t('Filtro meta (ACF / custom field)') },
    { key: 'meta_key', label: t('Meta key'), type: 'text', placeholder: t('prezzo, colore, etc.') },
    { key: 'meta_value', label: t('Meta value'), type: 'text', placeholder: t('valore da confrontare') },
    { key: 'meta_compare', label: t('Operatore'), type: 'select', options: [
      { value: '=', label: t('= Uguale') },
      { value: '!=', label: t('!= Diverso') },
      { value: '>', label: t('> Maggiore') },
      { value: '<', label: t('< Minore') },
      { value: '>=', label: t('>= Maggiore o uguale') },
      { value: '<=', label: t('<= Minore o uguale') },
      { value: 'LIKE', label: t('LIKE (contiene)') },
      { value: 'NOT LIKE', label: t('NOT LIKE') },
      { value: 'EXISTS', label: t('EXISTS (campo presente)') },
      { value: 'NOT EXISTS', label: t('NOT EXISTS') },
    ]},
    { key: 'meta_type', label: t('Tipo meta'), type: 'select', options: [
      { value: 'CHAR', label: t('Testo') },
      { value: 'NUMERIC', label: t('Numerico') },
      { value: 'DATE', label: t('Data') },
      { value: 'DECIMAL', label: t('Decimale') },
    ]},
    { key: 'search_keyword', label: t('Keyword ricerca preset'), type: 'text', placeholder: t('filtra per parola chiave') },

    { type: 'separator', label: t('Layout strutturale') },
    { key: 'layout', label: t('Layout'), type: 'select', options: [
      { value: 'grid',          label: t('Griglia') },
      { value: 'list',          label: t('Lista') },
      { value: 'list-rich',     label: t('Lista rich (thumb sx)') },
      { value: 'carousel',      label: t('Carosello') },
      { value: 'masonry',       label: t('Masonry') },
      { value: 'magazine-trio', label: t('Magazine Trio (1+2)') },
      { value: 'magazine-hero', label: t('Magazine Hero + Grid') },
      { value: 'alternating',   label: t('Alternating slots') },
      { value: 'bento',         label: t('Bento asimmetrico') },
      { value: 'newspaper',     label: t('Newspaper columns') },
      { value: 'timeline',      label: t('Timeline verticale') },
      { value: 'ticker-strip',  label: t('Ticker strip (auto-scroll)') },
      { value: 'stacked',       label: t('Stacked Cards (full width)') },
    ]},
    { key: 'timeline_group_by', label: t('Raggruppa timeline per'), type: 'select', options: [
      { value: 'month', label: t('Mese') },
      { value: 'year',  label: t('Anno') },
      { value: 'day',   label: t('Giorno') },
    ], condition: { field: 'layout', op: 'eq', value: 'timeline' } },
    { key: 'loop_template_id', label: t('Loop template ID (vuoto = card default)'), type: 'text', placeholder: t('ID template Olobuild per loop item') },

    { type: 'separator', label: t('Contenuto card') },
    { key: 'show_image', label: t('Mostra immagine'), type: 'toggle' },
    { key: 'show_title', label: t('Mostra titolo'), type: 'toggle' },
    { key: 'title_tag', label: t('Tag titolo'), type: 'select', options: [
      { value: 'h2', label: t('H2') },
      { value: 'h3', label: t('H3') },
      { value: 'h4', label: t('H4') },
      { value: 'h5', label: t('H5') },
      { value: 'h6', label: t('H6') },
    ], condition: { field: 'show_title', op: 'eq', value: true } },
    { key: 'show_excerpt', label: t('Mostra estratto'), type: 'toggle' },
    { key: 'excerpt_length', label: t('Lunghezza estratto (parole)'), type: 'number', min: 5, max: 100,
      condition: { field: 'show_excerpt', op: 'eq', value: true } },
    { key: 'show_date', label: t('Mostra data'), type: 'toggle' },
    { key: 'show_author', label: t('Mostra autore'), type: 'toggle' },
    { key: 'show_category', label: t('Mostra categoria'), type: 'toggle' },
    { key: 'show_read_more', label: 'Mostra "Leggi tutto"', type: 'toggle' },
    { key: 'read_more_text', label: t('Testo link'), type: 'text',
      condition: { field: 'show_read_more', op: 'eq', value: true } },

    { type: 'separator', label: t('🪄 Magic features') },
    { key: 'show_reading_time', label: t('Tempo di lettura calcolato'), type: 'toggle' },
    { key: 'show_comment_count', label: t('Contatore commenti'), type: 'toggle' },
    { key: 'new_badge', label: t('Badge "Novità" su post recenti'), type: 'toggle' },
    { key: 'new_badge_days', label: t('Soglia giorni per "Novità"'), type: 'range', min: 1, max: 60, step: 1,
      condition: { field: 'new_badge', value: true } },
    { key: 'new_badge_text', label: t('Testo badge novità'), type: 'text',
      condition: { field: 'new_badge', value: true } },
    { key: 'trending_badge', label: t('Badge "Trending" sui top 3 commentati'), type: 'toggle' },
    { key: 'enable_search', label: t('Campo ricerca live'), type: 'toggle' },
    { key: 'search_placeholder', label: t('Placeholder ricerca'), type: 'text',
      condition: { field: 'enable_search', value: true } },
    { key: 'enable_sort_ui', label: t('Selettore ordinamento UI'), type: 'toggle' },
    { key: 'enable_taxonomy_tabs', label: t('Tabs per tassonomia (filtro UI)'), type: 'toggle' },
    { key: 'taxonomy_tabs_taxonomy', label: t('Tassonomia per tabs'), type: 'text', placeholder: 'category',
      condition: { field: 'enable_taxonomy_tabs', value: true } },
    { key: 'sticky_filter_rail', label: t('Sidebar filtri sticky (sx)'), type: 'toggle' },
    { key: 'skeleton_loading', label: t('Skeleton loading durante AJAX'), type: 'toggle',
      condition: { field: 'pagination_type', op: 'in', value: ['loadmore', 'infinite'] } },

    { type: 'separator', label: t('Paginazione') },
    { key: 'pagination_type', label: t('Tipo paginazione'), type: 'select', options: [
      { value: 'none', label: t('Nessuna') },
      { value: 'numbers', label: t('Numeri') },
      { value: 'loadmore', label: t('Carica altro') },
      { value: 'infinite', label: t('Scroll infinito') },
    ]},
  ],

  styleFields: [
    { type: 'separator', label: t('Preset stilistico') },
    { key: 'preset', label: t('Stile'), type: 'select', options: [
      { value: 'magazine-trio',     label: t('Magazine Trio (1 hero + 2 small)') },
      { value: 'magazine-hero',     label: t('Magazine Hero + Grid') },
      { value: 'news-timeline',     label: t('News Timeline') },
      { value: 'newspaper-cols',    label: t('Newspaper Columns') },
      { value: 'editorial-list',    label: t('Editorial List (thumb sx)') },
      { value: 'news-ticker-strip', label: t('News Strip (ticker orizzontale)') },
      { value: 'cards-modern',      label: t('Cards Modern (Medium-style)') },
      { value: 'compact-index',     label: t('Compact Index (alta densità)') },
      { value: 'bento-news',        label: t('Bento News (asimmetrico)') },
      { value: 'alternating',       label: t('Alternating Slots') },
      { value: 'stacked-blog',      label: t('Stacked Cards Blog') },
      { value: 'tabs-categories',   label: t('Tabs Categories') },
      { value: 'custom',            label: t('Personalizzato') },
    ]},
    { key: 'typography_preset', label: t('Stile tipografico'), type: 'select', optionsSource: 'globalTypography' },
    { key: 'effect_color', label: t('Colore accento preset'), type: 'color',
      condition: { field: 'preset', op: 'in', value: ['magazine-trio', 'magazine-hero', 'news-timeline', 'editorial-list', 'cards-modern', 'tabs-categories', 'newspaper-cols'] } },

    { type: 'separator', label: t('Layout — Aspetto') },
    { key: 'columns', label: t('Colonne'), type: 'range', min: 1, max: 6, step: 1,
      condition: { field: 'layout', op: 'in', value: ['grid', 'masonry', 'bento', 'newspaper'] } },
    { key: 'gap', label: t('Gap (px)'), type: 'range', min: 0, max: 80, step: 5 },
    { key: 'image_ratio', label: t('Proporzione immagine'), type: 'select', options: [
      { value: '16:9', label: '16:9' },
      { value: '4:3', label: '4:3' },
      { value: '1:1', label: '1:1' },
      { value: '3:2', label: '3:2' },
      { value: '3:4', label: '3:4 verticale' },
      { value: 'auto', label: t('Auto') },
    ], condition: { field: 'show_image', op: 'eq', value: true } },

    { type: 'separator', label: t('Hover card') },
    { key: 'hover_effect', label: t('Effetto hover'), type: 'select', options: [
      { value: 'none',           label: t('Nessuno') },
      { value: 'lift',           label: t('Lift (alza con shadow)') },
      { value: 'image-zoom',     label: t('Zoom immagine') },
      { value: 'title-underline', label: t('Underline titolo cresce') },
      { value: 'arrow-slide',    label: t('Freccia "Leggi tutto" scorre') },
      { value: 'color-tint',     label: t('Tint immagine accent') },
      { value: 'border-grow',    label: t('Bordo cresce in basso') },
      { value: 'glassy-border',  label: t('Bordo glassy + glow') },
    ]},

    { type: 'separator', label: t('Stile card') },
    { key: 'card_style', label: t('Stile card legacy'), type: 'select', options: [
      { value: 'none', label: t('Nessuno') },
      { value: 'shadow', label: t('Ombra') },
      { value: 'border', label: t('Bordo') },
      { value: 'filled', label: t('Sfondo') },
    ]},
    { key: 'card_radius', label: t('Raggio card'), type: 'border-radius' },

    { type: 'separator', label: t('Tipografia') },
    { type: 'typography', label: t('Titolo card'),
      presetKey: 'typography_preset',
      responsiveKeys: ['letterSpacing'],
      keys: {
        family:        'font_family',
        weight:        'title_weight',
        transform:     'text_transform',
        letterSpacing: 'letter_spacing',
        color:         'title_color',
      },
    },
    { type: 'typography', label: t('Testo'),
      presetKey: 'typography_preset',
      keys: {
        color: 'text_color',
      },
    },
    { type: 'typography', label: t('Meta'),
      presetKey: 'typography_preset',
      keys: {
        color: 'meta_color',
      },
    },
    { type: 'typography', label: t('Link / Accento'),
      presetKey: 'typography_preset',
      keys: {
        color: 'link_color',
      },
    },

    { type: 'separator', label: t('Colori card') },
    { key: 'accent_color', label: t('Colore accento (badge, cat, hover)'), type: 'color' },
    withHover({ key: 'bg_color', label: t('Sfondo card'), type: 'color' }, { hoverKey: 'hover_bg' }),
    { key: 'overlay_color', label: t('Colore overlay (magazine)'), type: 'color',
      condition: { field: 'layout', op: 'in', value: ['magazine-trio', 'magazine-hero', 'alternating'] } },
    { key: 'overlay_opacity', label: t('Opacità overlay (%)'), type: 'range', min: 0, max: 100, step: 5,
      condition: { field: 'layout', op: 'in', value: ['magazine-trio', 'magazine-hero', 'alternating'] } },

    { type: 'separator', label: t('Container') },
    { key: 'container_padding', label: t('Padding container'), type: 'spacing', max: 60 },
    { key: 'container_radius', label: t('Raggio bordi container'), type: 'border-radius' },

    ...shadowField,
    ...wowEffectsFields(),
  ],
};
