
import { borderFields, borderDefault, borderHoverDefault, borderEffectDefaults } from './_shared.js';
export default {
  type: 'relatedposts',
  name: 'Articoli Correlati',
  icon: 'dashicons-screenoptions',
  category: 'dynamic',
  defaults: {
    source: 'categories',
    count: '3',
    columns: '3',
    show_image: true,
    show_date: true,
    show_excerpt: false,
    show_category: false,
    excerpt_length: '20',
    image_ratio: '16/9',
    gap: '20',
    title_tag: 'h4',
    title_color: '',
    text_color: '',
    date_color: '',
    card_background: '',
    tile_padding: { top: 16, right: 16, bottom: 16, left: 16 },
    card_border_radius: '8',
    hover_effect: 'shadow',
    fallback_text: 'Nessun articolo correlato',
    orderby: 'rand',
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
  },
  fields: [
    { type: 'separator', label: 'Query' },
    { key: 'source', label: 'Correlazione per', type: 'select', options: [
      { value: 'categories', label: 'Categorie' },
      { value: 'tags', label: 'Tag' },
      { value: 'both', label: 'Categorie + Tag' },
    ]},
    { key: 'count', label: 'Numero articoli', type: 'range', min: 1, max: 12, step: 1 },
    { key: 'orderby', label: 'Ordina per', type: 'select', options: [
      { value: 'rand', label: 'Casuale' },
      { value: 'date', label: 'Data' },
      { value: 'title', label: 'Titolo' },
    ]},

    { type: 'separator', label: 'Layout' },
    { key: 'columns', label: 'Colonne', type: 'select', options: [
      { value: '1', label: '1' },
      { value: '2', label: '2' },
      { value: '3', label: '3' },
      { value: '4', label: '4' },
    ]},
    { key: 'gap', label: 'Spaziatura (px)', type: 'range', min: 0, max: 40, step: 2 },

    { type: 'separator', label: 'Contenuto card' },
    { key: 'show_image', label: 'Mostra immagine', type: 'toggle' },
    { key: 'image_ratio', label: 'Rapporto immagine', type: 'select', options: [
      { value: '16/9', label: '16:9' },
      { value: '4/3', label: '4:3' },
      { value: '1/1', label: '1:1' },
      { value: 'auto', label: 'Automatico' },
    ], condition: { field: 'show_image', value: true } },
    { key: 'show_date', label: 'Mostra data', type: 'toggle' },
    { key: 'show_excerpt', label: 'Mostra estratto', type: 'toggle' },
    { key: 'excerpt_length', label: 'Parole estratto', type: 'range', min: 5, max: 50, step: 1,
      condition: { field: 'show_excerpt', value: true } },
    { key: 'show_category', label: 'Mostra categoria', type: 'toggle' },
    { key: 'title_tag', label: 'Tag titolo', type: 'select', options: [
      { value: 'h3', label: 'H3' },
      { value: 'h4', label: 'H4' },
      { value: 'h5', label: 'H5' },
      { value: 'p', label: 'Paragrafo' },
    ]},

    { type: 'separator', label: 'Stile' },
    { key: 'title_color', label: 'Colore titolo', type: 'color' },
    { key: 'text_color', label: 'Colore testo', type: 'color' },
    { key: 'date_color', label: 'Colore data', type: 'color' },
    { key: 'card_background', label: 'Sfondo card', type: 'color' },
    { key: 'tile_padding', label: 'Padding (px)', type: 'spacing', max: 32 },
    { key: 'card_border_radius', label: 'Raggio bordo (px)', type: 'border-radius' },
    { key: 'card_border_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius' },
    { key: 'hover_effect', label: 'Effetto hover', type: 'select', options: [
      { value: 'none', label: 'Nessuno' },
      { value: 'shadow', label: 'Ombra' },
      { value: 'scale', label: 'Ingrandisci' },
    ]},

    { type: 'separator', label: 'Fallback' },
    { key: 'fallback_text', label: 'Testo fallback', type: 'text' },
    ...borderFields(),
  ],
};
