export default {
  type: 'revealbox',
  name: 'Reveal Box',
  icon: 'dashicons-arrow-up-alt',
  category: 'interactive',
  defaults: {
    visible_height: '300',
    top_image_url: '',
    top_image_position: 'center center',
    top_image_size: 'cover',
    top_video_url: '',
    bottom_image_url: '',
    bottom_image_position: 'center center',
    bottom_image_size: 'cover',
    bottom_video_url: '',
    top_content: '<h3>Titolo</h3>',
    bottom_content: '<p>Contenuto rivelato al passaggio del mouse</p>',
    top_icon: '',
    top_icon_size: '2',
    top_icon_color: '#ffffff',
    bottom_icon: '',
    bottom_icon_size: '2',
    bottom_icon_color: '#ffffff',
    reveal_effect: 'slide-up',
    reveal_amount: '',
    transition_speed: '0.5',
    transition_easing: 'ease',
    top_text_color: '#ffffff',
    top_font_size: '',
    bottom_text_color: '#ffffff',
    bottom_font_size: '',
    overlay_color: '#000000',
    overlay_opacity: '0',
    reveal_overlay_color: '#000000',
    reveal_overlay_opacity: '60',
    text_color: '#ffffff',
    top_align: 'flex-end',
    top_justify: 'flex-start',
    bottom_align: 'flex-start',
    bottom_justify: 'flex-start',
    top_padding: '24',
    bottom_padding: '24',
    border_radius: { tl: 0, tr: 0, br: 0, bl: 0 },
    perspective: '800',
    tile_padding: { top: 0, right: 0, bottom: 0, left: 0 },
  },
  fields: [
    { type: 'separator', label: 'Effetto reveal' },
    {
      key: 'reveal_effect', label: 'Tipo effetto', type: 'select',
      options: [
        { value: 'slide-up', label: 'Scorrimento ↑' },
        { value: 'slide-down', label: 'Scorrimento ↓' },
        { value: 'slide-left', label: 'Scorrimento ←' },
        { value: 'slide-right', label: 'Scorrimento →' },
        { value: 'fade', label: 'Dissolvenza' },
        { value: 'zoom-in', label: 'Zoom in' },
        { value: 'zoom-out', label: 'Zoom out' },
        { value: 'flip-x', label: 'Giro 3D orizzontale' },
        { value: 'flip-y', label: 'Giro 3D verticale' },
        { value: 'rotate-in', label: 'Rotazione' },
      ],
    },
    {
      key: 'perspective', label: 'Prospettiva 3D (px)', type: 'range', min: 200, max: 2000, step: 50,
      condition: { field: 'reveal_effect', operator: 'in', value: ['flip-x', 'flip-y'] },
    },

    { type: 'separator', label: 'Sfondo globale' },
    { key: 'image_url', label: 'Immagine di sfondo (entrambe le zone)', type: 'media' },
    {
      key: 'image_size', label: 'Dimensione', type: 'select',
      options: [
        { value: 'cover', label: 'Copri' },
        { value: 'contain', label: 'Contieni' },
        { value: 'auto', label: 'Originale' },
      ],
      condition: { field: 'image_url', operator: '!=', value: '' },
    },
    {
      key: 'image_position', label: 'Posizione', type: 'select',
      options: [
        { value: 'center center', label: 'Centro' },
        { value: 'center top', label: 'Centro alto' },
        { value: 'center bottom', label: 'Centro basso' },
        { value: 'left center', label: 'Sinistra' },
        { value: 'right center', label: 'Destra' },
      ],
      condition: { field: 'image_url', operator: '!=', value: '' },
    },

    { type: 'separator', label: 'Zona visibile (fronte)' },
    { key: 'top_image_url', label: 'Immagine di sfondo', type: 'media' },
    {
      key: 'top_image_size', label: 'Dimensione immagine', type: 'select',
      options: [
        { value: 'cover', label: 'Copri' },
        { value: 'contain', label: 'Contieni' },
        { value: 'auto', label: 'Originale' },
      ],
      condition: { field: 'top_image_url', operator: '!=', value: '' },
    },
    {
      key: 'top_image_position', label: 'Posizione immagine', type: 'select',
      options: [
        { value: 'center center', label: 'Centro' },
        { value: 'center top', label: 'Centro alto' },
        { value: 'center bottom', label: 'Centro basso' },
        { value: 'left center', label: 'Sinistra' },
        { value: 'right center', label: 'Destra' },
      ],
      condition: { field: 'top_image_url', operator: '!=', value: '' },
    },
    { key: 'top_video_url', label: 'Video di sfondo', type: 'media', mediaType: 'video' },
    { key: 'visible_height', label: 'Altezza visibile (px)', type: 'range', min: 100, max: 800, step: 10 },
    { key: 'top_icon', label: 'Icona', type: 'icon' },
    {
      key: 'top_icon_size', label: 'Dimensione icona', type: 'range', min: 0.5, max: 6, step: 0.1,
      condition: { field: 'top_icon', operator: '!=', value: '' },
    },
    {
      key: 'top_icon_color', label: 'Colore icona', type: 'color',
      condition: { field: 'top_icon', operator: '!=', value: '' },
    },
    { key: 'top_content', label: 'Contenuto visibile', type: 'richtext' },
    { key: 'top_text_color', label: 'Colore testo', type: 'color' },
    { key: 'top_font_size', label: 'Grandezza testo (px)', type: 'range', min: 10, max: 72, step: 1 },
    {
      key: 'top_align', label: 'Allineamento verticale', type: 'select',
      options: [
        { value: 'flex-start', label: 'Alto' },
        { value: 'center', label: 'Centro' },
        { value: 'flex-end', label: 'Basso' },
      ],
    },
    {
      key: 'top_justify', label: 'Allineamento orizzontale', type: 'select',
      options: [
        { value: 'flex-start', label: 'Sinistra' },
        { value: 'center', label: 'Centro' },
        { value: 'flex-end', label: 'Destra' },
      ],
    },
    { key: 'top_padding', label: 'Padding interno (px)', type: 'range', min: 0, max: 80, step: 4 },
    { key: 'overlay_color', label: 'Colore overlay', type: 'color' },
    { key: 'overlay_opacity', label: 'Opacità overlay (%)', type: 'range', min: 0, max: 100 },

    { type: 'separator', label: 'Zona rivelata (hover)' },
    { key: 'bottom_image_url', label: 'Immagine di sfondo', type: 'media' },
    {
      key: 'bottom_image_size', label: 'Dimensione immagine', type: 'select',
      options: [
        { value: 'cover', label: 'Copri' },
        { value: 'contain', label: 'Contieni' },
        { value: 'auto', label: 'Originale' },
      ],
      condition: { field: 'bottom_image_url', operator: '!=', value: '' },
    },
    {
      key: 'bottom_image_position', label: 'Posizione immagine', type: 'select',
      options: [
        { value: 'center center', label: 'Centro' },
        { value: 'center top', label: 'Centro alto' },
        { value: 'center bottom', label: 'Centro basso' },
        { value: 'left center', label: 'Sinistra' },
        { value: 'right center', label: 'Destra' },
      ],
      condition: { field: 'bottom_image_url', operator: '!=', value: '' },
    },
    { key: 'bottom_video_url', label: 'Video di sfondo', type: 'media', mediaType: 'video' },
    { key: 'bottom_icon', label: 'Icona', type: 'icon' },
    {
      key: 'bottom_icon_size', label: 'Dimensione icona', type: 'range', min: 0.5, max: 6, step: 0.1,
      condition: { field: 'bottom_icon', operator: '!=', value: '' },
    },
    {
      key: 'bottom_icon_color', label: 'Colore icona', type: 'color',
      condition: { field: 'bottom_icon', operator: '!=', value: '' },
    },
    { key: 'bottom_content', label: 'Contenuto rivelato', type: 'richtext' },
    { key: 'bottom_text_color', label: 'Colore testo', type: 'color' },
    { key: 'bottom_font_size', label: 'Grandezza testo (px)', type: 'range', min: 10, max: 72, step: 1 },
    { key: 'reveal_amount', label: 'Scorrimento (px, vuoto = auto)', type: 'text', placeholder: 'auto',
      condition: { field: 'reveal_effect', operator: 'in', value: ['slide-up', 'slide-down', 'slide-left', 'slide-right'] },
    },
    {
      key: 'bottom_align', label: 'Allineamento verticale', type: 'select',
      options: [
        { value: 'flex-start', label: 'Alto' },
        { value: 'center', label: 'Centro' },
        { value: 'flex-end', label: 'Basso' },
      ],
    },
    {
      key: 'bottom_justify', label: 'Allineamento orizzontale', type: 'select',
      options: [
        { value: 'flex-start', label: 'Sinistra' },
        { value: 'center', label: 'Centro' },
        { value: 'flex-end', label: 'Destra' },
      ],
    },
    { key: 'bottom_padding', label: 'Padding interno (px)', type: 'range', min: 0, max: 80, step: 4 },
    { key: 'reveal_overlay_color', label: 'Colore overlay rivelato', type: 'color' },
    { key: 'reveal_overlay_opacity', label: 'Opacità overlay rivelato (%)', type: 'range', min: 0, max: 100 },

    { type: 'separator', label: 'Stile' },
    { key: 'transition_speed', label: 'Velocità transizione (s)', type: 'range', min: 0.1, max: 2, step: 0.1 },
    {
      key: 'transition_easing', label: 'Curva transizione', type: 'select',
      options: [
        { value: 'ease', label: 'Ease' },
        { value: 'ease-in-out', label: 'Ease In/Out' },
        { value: 'ease-out', label: 'Ease Out' },
        { value: 'cubic-bezier(0.4,0,0.2,1)', label: 'Smooth' },
        { value: 'linear', label: 'Lineare' },
      ],
    },
    { key: 'border_radius', label: 'Bordo arrotondato (px)', type: 'border-radius' },
    { key: 'tile_padding', type: 'spacing', label: 'Spaziatura interna' },
  ],
};
