import { flexContainerFields, flexContainerDefaults } from './_shared.js';

export default {
  type: 'row',
  name: 'Riga / Colonne',
  icon: 'dashicons-columns',
  category: 'layout',
  defaults: {
    layout: '50-50',
    gap: '16',
    column_gap: 'default',
    vertical_align: 'stretch',
    stack_mobile: true,
    stack_tablet: false,
    // Grid-specific defaults
    grid_column_gap: '',
    grid_row_gap: '',
    grid_auto_flow: 'row',
    grid_auto_flow_dense: false,
    grid_justify_content: 'stretch',
    grid_align_items: 'stretch',
    grid_align_content: 'stretch',
    // Loop defaults
    loop_enabled: false,
    loop_post_type: 'post',
    loop_posts_per_page: '6',
    loop_orderby: 'date',
    loop_order: 'DESC',
    loop_taxonomy: '',
    loop_terms: '',
    loop_terms_exclude: '',
    loop_offset: '0',
    loop_exclude_current: true,
    loop_meta_key: '',
    loop_meta_value: '',
    loop_meta_compare: '=',
    ...flexContainerDefaults,
  },
  fields: [
    { key: 'layout', label: 'Layout', type: 'select', options: [
      { value: '100', label: '100' },
      { value: '50-50', label: '50 / 50' },
      { value: '33-33-33', label: '33 / 33 / 33' },
      { value: '25-50-25', label: '25 / 50 / 25' },
      { value: '25-25-25-25', label: '25 / 25 / 25 / 25' },
      { value: '66-33', label: '66 / 33' },
      { value: '33-66', label: '33 / 66' },
      { value: 'custom', label: 'Personalizzato (%)' },
    ]},
    { key: 'custom_widths', label: 'Larghezze personalizzate', type: 'text', placeholder: 'es: 20,30,50', condition: { field: 'layout', value: 'custom' } },
    { key: 'gap', label: 'Gap (px)', type: 'range', min: 0, max: 48, step: 4,
      show: (s) => {
        const fcg = parseInt(s.flex_column_gap || 0);
        const frg = parseInt(s.flex_row_gap || 0);
        return !(fcg > 0 || frg > 0);
      }
    },
    { key: 'vertical_align', label: 'Allineamento verticale', type: 'select', options: [
      { value: 'stretch', label: 'Stretch' },
      { value: 'start', label: 'Alto' },
      { value: 'center', label: 'Centro' },
      { value: 'end', label: 'Basso' },
    ]},
    { key: 'stack_mobile', label: 'Impila su mobile', type: 'toggle' },
    { key: 'stack_tablet', label: 'Impila su tablet', type: 'toggle' },

    // ── Loop Post ──
    { key: '_loop_sep', label: 'Loop', type: 'separator' },
    { key: 'loop_enabled', label: 'Loop Element', type: 'toggle' },
    { key: 'loop_post_type', label: 'Tipo contenuto', type: 'select', optionsSource: 'postTypes', options: [],
      condition: { field: 'loop_enabled', value: true } },
    { key: 'loop_posts_per_page', label: 'Numero di post', type: 'range', min: 1, max: 50, step: 1,
      condition: { field: 'loop_enabled', value: true } },
    { key: 'loop_orderby', label: 'Ordina per', type: 'select', options: [
      { value: 'date', label: 'Data' },
      { value: 'title', label: 'Titolo' },
      { value: 'modified', label: 'Data modifica' },
      { value: 'rand', label: 'Casuale' },
      { value: 'menu_order', label: 'Ordine menu' },
      { value: 'comment_count', label: 'N. commenti' },
      { value: 'meta_value_num', label: 'Meta value (numerico)' },
    ], condition: { field: 'loop_enabled', value: true } },
    { key: 'loop_order', label: 'Direzione', type: 'select', options: [
      { value: 'DESC', label: 'Decrescente' },
      { value: 'ASC', label: 'Crescente' },
    ], condition: { field: 'loop_enabled', value: true } },
    { key: 'loop_taxonomy', label: 'Tassonomia filtro', type: 'text', placeholder: 'category, post_tag...',
      condition: { field: 'loop_enabled', value: true } },
    { key: 'loop_terms', label: 'Includi termini (slug, virgola)', type: 'text', placeholder: 'news, tutorial',
      condition: { field: 'loop_enabled', value: true } },
    { key: 'loop_terms_exclude', label: 'Escludi termini (slug, virgola)', type: 'text', placeholder: 'bozze, privati',
      condition: { field: 'loop_enabled', value: true } },
    { key: 'loop_offset', label: 'Offset', type: 'range', min: 0, max: 50, step: 1,
      condition: { field: 'loop_enabled', value: true } },
    { key: 'loop_exclude_current', label: 'Escludi post corrente', type: 'toggle',
      condition: { field: 'loop_enabled', value: true } },
    { key: 'loop_meta_key', label: 'Meta key filtro', type: 'text', placeholder: 'prezzo, colore...',
      condition: { field: 'loop_enabled', value: true } },
    { key: 'loop_meta_value', label: 'Meta value', type: 'text',
      condition: { field: 'loop_enabled', value: true } },
    { key: 'loop_meta_compare', label: 'Operatore meta', type: 'select', options: [
      { value: '=', label: '= Uguale' },
      { value: '!=', label: '!= Diverso' },
      { value: '>', label: '> Maggiore' },
      { value: '<', label: '< Minore' },
      { value: 'LIKE', label: 'LIKE (contiene)' },
      { value: 'EXISTS', label: 'EXISTS' },
      { value: 'NOT EXISTS', label: 'NOT EXISTS' },
    ], condition: { field: 'loop_enabled', value: true } },

    // ── Grid-specific controls (visible only when layout_mode=grid) ──
    { key: '_grid_sep', label: 'Controlli CSS Grid', type: 'separator', condition: { field: 'layout_mode', value: 'grid' } },
    { key: 'grid_column_gap', label: 'Gap Orizzontale (px)', type: 'range', min: 0, max: 60, step: 2, condition: { field: 'layout_mode', value: 'grid' } },
    { key: 'grid_row_gap', label: 'Gap Verticale (px)', type: 'range', min: 0, max: 60, step: 2, condition: { field: 'layout_mode', value: 'grid' } },
    { key: 'grid_auto_flow', label: 'Direzione Grid', type: 'icon-select', options: [
      { value: 'row', label: 'Riga', icon: 'arrow-right' },
      { value: 'column', label: 'Colonna', icon: 'arrow-down' },
    ], condition: { field: 'layout_mode', value: 'grid' } },
    { key: 'grid_auto_flow_dense', label: 'Densità (dense)', type: 'toggle', condition: { field: 'layout_mode', value: 'grid' } },
    { key: 'grid_justify_content', label: 'Justify Content', type: 'icon-select', options: [
      { value: 'start', label: 'Start', icon: 'align-left' },
      { value: 'center', label: 'Center', icon: 'align-center' },
      { value: 'end', label: 'End', icon: 'align-right' },
      { value: 'stretch', label: 'Stretch', icon: 'align-justify' },
      { value: 'space-between', label: 'Space Between', icon: 'space-between' },
      { value: 'space-around', label: 'Space Around', icon: 'space-around' },
      { value: 'space-evenly', label: 'Space Evenly', icon: 'space-evenly' },
    ], condition: { field: 'layout_mode', value: 'grid' } },
    { key: 'grid_align_items', label: 'Align Items', type: 'icon-select', options: [
      { value: 'start', label: 'Start', icon: 'align-top' },
      { value: 'center', label: 'Center', icon: 'align-middle' },
      { value: 'end', label: 'End', icon: 'align-bottom' },
      { value: 'stretch', label: 'Stretch', icon: 'align-stretch-v' },
      { value: 'baseline', label: 'Baseline', icon: 'align-baseline' },
    ], condition: { field: 'layout_mode', value: 'grid' } },
    { key: 'grid_align_content', label: 'Align Content', type: 'icon-select', options: [
      { value: 'start', label: 'Start', icon: 'align-top' },
      { value: 'center', label: 'Center', icon: 'align-middle' },
      { value: 'end', label: 'End', icon: 'align-bottom' },
      { value: 'stretch', label: 'Stretch', icon: 'align-stretch-v' },
      { value: 'space-between', label: 'Space Between', icon: 'space-between-v' },
      { value: 'space-around', label: 'Space Around', icon: 'space-around-v' },
    ], condition: { field: 'layout_mode', value: 'grid' } },

    ...flexContainerFields,
  ],
};
