import { shadowField, borderFields, borderDefault, borderHoverDefault, borderEffectDefaults } from './_shared.js';

export default {
  type: 'search',
  name: 'Ricerca',
  icon: 'dashicons-search',
  category: 'navigation',
  defaults: {
    placeholder: 'Cerca...',
    style: 'default',
    size: 'medium',
    show_icon: true,
    icon_position: 'left',
    show_button: false,
    button_text: 'Cerca',
    button_style: 'filled',
    full_width: true,
    max_width: '',
    alignment: 'center',
    bg_color: '#FFFFFF',
    text_color: '#374151',
    placeholder_color: '#9CA3AF',
    icon_color: '#6B7280',
    border_color: '#E5E7EB',
    border_width: '1',
    border_radius: '8',
    focus_border_color: '#6366F1',
    button_bg: '#6366F1',
    button_color: '#FFFFFF',
    button_radius: '8',
    input_shadow: false,
    focus_shadow: true,
    animated_placeholder: false,
    placeholder_words: '',
    shadow: 'none',
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
  },
  fields: [
    { type: 'separator', label: 'Contenuto' },
    { key: 'placeholder', label: 'Placeholder', type: 'text' },
    { key: 'animated_placeholder', label: 'Placeholder animato', type: 'toggle' },
    { key: 'placeholder_words', label: 'Parole animate (una per riga)', type: 'textarea',
      show: s => s.animated_placeholder },

    { type: 'separator', label: 'Layout' },
    { key: 'style', label: 'Stile', type: 'select', options: [
      { value: 'default', label: 'Predefinito' },
      { value: 'minimal', label: 'Minimale' },
      { value: 'pill', label: 'Pillola' },
      { value: 'underline', label: 'Sottolineato' },
      { value: 'hero', label: 'Hero (grande)' },
      { value: 'floating', label: 'Flottante' },
    ]},
    { key: 'size', label: 'Dimensione', type: 'select', options: [
      { value: 'small', label: 'Piccola' },
      { value: 'medium', label: 'Media' },
      { value: 'large', label: 'Grande' },
    ]},
    { key: 'full_width', label: 'Larghezza piena', type: 'toggle' },
    { key: 'max_width', label: 'Larghezza massima (px)', type: 'text',
      show: s => !s.full_width },
    { key: 'alignment', label: 'Allineamento', type: 'select', options: [
      { value: 'left', label: 'Sinistra' },
      { value: 'center', label: 'Centro' },
      { value: 'right', label: 'Destra' },
    ], show: s => !s.full_width },

    { type: 'separator', label: 'Icona' },
    { key: 'show_icon', label: 'Mostra icona', type: 'toggle' },
    { key: 'icon_position', label: 'Posizione icona', type: 'select', options: [
      { value: 'left', label: 'Sinistra' },
      { value: 'right', label: 'Destra' },
    ], show: s => s.show_icon },

    { type: 'separator', label: 'Pulsante' },
    { key: 'show_button', label: 'Mostra pulsante', type: 'toggle' },
    { key: 'button_text', label: 'Testo pulsante', type: 'text', show: s => s.show_button },
    { key: 'button_style', label: 'Stile pulsante', type: 'select', options: [
      { value: 'filled', label: 'Pieno' },
      { value: 'outline', label: 'Contorno' },
      { value: 'icon-only', label: 'Solo icona' },
    ], show: s => s.show_button },

    { type: 'separator', label: 'Colori' },
    { key: 'bg_color', label: 'Sfondo input', type: 'color' },
    { key: 'text_color', label: 'Colore testo', type: 'color' },
    { key: 'placeholder_color', label: 'Colore placeholder', type: 'color' },
    { key: 'icon_color', label: 'Colore icona', type: 'color' },
    { key: 'border_color', label: 'Colore bordo', type: 'color' },
    { key: 'focus_border_color', label: 'Colore bordo focus', type: 'color' },
    { key: 'button_bg', label: 'Sfondo pulsante', type: 'color', show: s => s.show_button },
    { key: 'button_color', label: 'Colore testo pulsante', type: 'color', show: s => s.show_button },

    { type: 'separator', label: 'Bordi' },
    { key: 'border_width', label: 'Spessore bordo (px)', type: 'range', min: 0, max: 4 },
    { key: 'border_radius', label: 'Arrotondamento (px)', type: 'border-radius' },
    { key: 'border_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius' },
    { key: 'button_radius', label: 'Arrotondamento pulsante (px)', type: 'border-radius',
      show: s => s.show_button },
    { key: 'button_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius' },

    { type: 'separator', label: 'Effetti' },
    { key: 'input_shadow', label: 'Ombra input', type: 'toggle' },
    { key: 'focus_shadow', label: 'Ombra su focus', type: 'toggle' },
    ...shadowField,
    ...borderFields(),
  ],
};
