export default {
  type: 'servicedirections',
  name: 'Come Arrivare',
  icon: 'dashicons-car',
  category: 'booking',
  defaults: {
    meta_prefix: '_olo_service_',
    show_icon: true,
    show_title: true,
    title_text: 'Come arrivare',
    title_size: '18',
    text_size: '14',
    title_color: '',
    text_color: '',
    icon_color: '',
    bg_color: '',
    border_color: '',
    border_radius: '8',
    tile_padding: { top: 16, right: 16, bottom: 16, left: 16 },
  },
  fields: [
    { type: 'separator', label: 'Sorgente dati' },
    { key: 'meta_prefix', label: 'Tipo servizio', type: 'select', optionsSource: 'metaPrefixes' },

    { type: 'separator', label: 'Titolo' },
    { key: 'show_title', label: 'Mostra titolo', type: 'toggle' },
    { key: 'show_icon', label: 'Mostra icona', type: 'toggle' },
    { key: 'title_text', label: 'Testo titolo', type: 'text',
      condition: { field: 'show_title', value: true } },

    { type: 'separator', label: 'Stile' },
    { key: 'title_size', label: 'Dimensione titolo (px)', type: 'range', min: 14, max: 28, step: 1 },
    { key: 'text_size', label: 'Dimensione testo (px)', type: 'range', min: 12, max: 20, step: 1 },
    { key: 'title_color', label: 'Colore titolo', type: 'color' },
    { key: 'text_color', label: 'Colore testo', type: 'color' },
    { key: 'icon_color', label: 'Colore icona', type: 'color' },

    { type: 'separator', label: 'Contenitore' },
    { key: 'bg_color', label: 'Sfondo', type: 'color' },
    { key: 'border_color', label: 'Bordo', type: 'color' },
    { key: 'border_radius', label: 'Raggio bordi (px)', type: 'border-radius' },
    { key: 'tile_padding', label: 'Padding (px)', type: 'spacing', max: 24 },
  ],
};
