export default {
  type: 'servicelist',
  name: 'Lista Servizi',
  icon: 'dashicons-grid-view',
  category: 'booking',
  defaults: {
    columns: '3',
    gap: '24',
    style: 'cards',
    show_image: true,
    show_price: true,
    show_duration: true,
    show_excerpt: true,
    show_booking_btn: true,
    booking_btn_text: 'Prenota',
    link_to: 'service_page',
    booking_page_url: '/prenota',
    card_bg: '',
    card_border_radius: '12',
    card_border_color: '',
    card_shadow: 'sm',
    tile_padding: { top: 24, right: 24, bottom: 24, left: 24 },
    card_hover_shadow: 'md',
    title_size: '18',
    title_weight: '600',
    title_color: '',
    price_color: '',
    price_size: '16',
    duration_color: '',
    excerpt_color: '',
    excerpt_size: '14',
    btn_bg: '',
    btn_color: '',
    btn_radius: '8',
    btn_full_width: false,
    image_height: '200',
    image_radius: '8',
    color_bar: true,
    color_bar_height: '4',
  },
  fields: [
    // ── Layout ──
    { key: 'columns', label: 'Colonne', type: 'range', min: 1, max: 4, step: 1 },
    { key: 'gap', label: 'Spaziatura (px)', type: 'range', min: 8, max: 48, step: 4 },
    { key: 'style', label: 'Stile', type: 'select', options: [
      { value: 'cards', label: 'Card' },
      { value: 'list', label: 'Lista' },
      { value: 'minimal', label: 'Minimale' },
    ]},

    { type: 'separator', label: 'Contenuto' },

    // ── Contenuto ──
    { key: 'show_image', label: 'Mostra immagine', type: 'toggle' },
    { key: 'show_price', label: 'Mostra prezzo', type: 'toggle' },
    { key: 'show_duration', label: 'Mostra durata', type: 'toggle' },
    { key: 'show_excerpt', label: 'Mostra descrizione', type: 'toggle' },
    { key: 'show_booking_btn', label: 'Pulsante prenotazione', type: 'toggle' },
    { key: 'booking_btn_text', label: 'Testo pulsante', type: 'text',
      condition: { field: 'show_booking_btn', value: true } },
    { key: 'link_to', label: 'Link destinazione', type: 'select', options: [
      { value: 'service_page', label: 'Pagina servizio' },
      { value: 'booking_page', label: 'Pagina booking' },
      { value: 'none', label: 'Nessuno' },
    ]},
    { key: 'booking_page_url', label: 'URL pagina booking', type: 'text',
      condition: { field: 'link_to', value: 'booking_page' } },
    { key: 'color_bar', label: 'Barra colore', type: 'toggle' },
    { key: 'color_bar_height', label: 'Altezza barra (px)', type: 'range', min: 2, max: 8, step: 1,
      condition: { field: 'color_bar', value: true } },

    { type: 'separator', label: 'Card' },

    // ── Card ──
    { key: 'card_bg', label: 'Sfondo card', type: 'color' },
    { key: 'card_border_radius', label: 'Radius card (px)', type: 'border-radius' },
    { key: 'card_border_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius' },
    { key: 'card_border_color', label: 'Bordo colore', type: 'color' },
    { key: 'tile_padding', label: 'Padding (px)', type: 'spacing', max: 48 },
    { key: 'card_shadow', label: 'Ombra', type: 'select', options: [
      { value: 'none', label: 'Nessuna' },
      { value: 'sm', label: 'Leggera' },
      { value: 'md', label: 'Media' },
      { value: 'lg', label: 'Forte' },
      { value: 'custom', label: 'Personalizzata' },
    ]},
    { key: 'card_shadow_h', label: 'Offset H (px)', type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'card_shadow', op: 'eq', value: 'custom' } },
    { key: 'card_shadow_v', label: 'Offset V (px)', type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'card_shadow', op: 'eq', value: 'custom' } },
    { key: 'card_shadow_blur', label: 'Sfocatura (px)', type: 'range', min: 0, max: 100, step: 1,
      condition: { field: 'card_shadow', op: 'eq', value: 'custom' } },
    { key: 'card_shadow_spread', label: 'Espansione (px)', type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'card_shadow', op: 'eq', value: 'custom' } },
    { key: 'card_shadow_color', label: 'Colore ombra', type: 'color',
      condition: { field: 'card_shadow', op: 'eq', value: 'custom' } },
    { key: 'card_shadow_inset', label: 'Ombra interna', type: 'toggle',
      condition: { field: 'card_shadow', op: 'eq', value: 'custom' } },
    { key: 'card_hover_shadow', label: 'Ombra hover', type: 'select', options: [
      { value: 'none', label: 'Nessuna' },
      { value: 'sm', label: 'Leggera' },
      { value: 'md', label: 'Media' },
      { value: 'lg', label: 'Forte' },
      { value: 'custom', label: 'Personalizzata' },
    ]},
    { key: 'card_hover_shadow_h', label: 'Offset H hover (px)', type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'card_hover_shadow', op: 'eq', value: 'custom' } },
    { key: 'card_hover_shadow_v', label: 'Offset V hover (px)', type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'card_hover_shadow', op: 'eq', value: 'custom' } },
    { key: 'card_hover_shadow_blur', label: 'Sfocatura hover (px)', type: 'range', min: 0, max: 100, step: 1,
      condition: { field: 'card_hover_shadow', op: 'eq', value: 'custom' } },
    { key: 'card_hover_shadow_spread', label: 'Espansione hover (px)', type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'card_hover_shadow', op: 'eq', value: 'custom' } },
    { key: 'card_hover_shadow_color', label: 'Colore ombra hover', type: 'color',
      condition: { field: 'card_hover_shadow', op: 'eq', value: 'custom' } },
    { key: 'card_hover_shadow_inset', label: 'Ombra interna hover', type: 'toggle',
      condition: { field: 'card_hover_shadow', op: 'eq', value: 'custom' } },
    { key: 'image_height', label: 'Altezza immagine (px)', type: 'range', min: 100, max: 400, step: 10,
      condition: { field: 'show_image', value: true } },
    { key: 'image_radius', label: 'Radius immagine (px)', type: 'border-radius',
      condition: { field: 'show_image', value: true } },
    { key: 'image_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius' },

    { type: 'separator', label: 'Tipografia' },

    // ── Tipografia ──
    { key: 'title_size', label: 'Dimensione titolo (px)', type: 'range', min: 14, max: 28, step: 1 },
    { key: 'title_weight', label: 'Peso titolo', type: 'select', options: [
      { value: '400', label: 'Normal' },
      { value: '600', label: 'Semi Bold' },
      { value: '700', label: 'Bold' },
    ]},
    { key: 'title_color', label: 'Colore titolo', type: 'color' },
    { key: 'price_color', label: 'Colore prezzo', type: 'color' },
    { key: 'price_size', label: 'Dimensione prezzo (px)', type: 'range', min: 12, max: 24, step: 1 },
    { key: 'duration_color', label: 'Colore durata', type: 'color' },
    { key: 'excerpt_color', label: 'Colore descrizione', type: 'color' },
    { key: 'excerpt_size', label: 'Dimensione descrizione (px)', type: 'range', min: 12, max: 18, step: 1 },

    { type: 'separator', label: 'Pulsante' },

    // ── Pulsante ──
    { key: 'btn_bg', label: 'Sfondo pulsante', type: 'color' },
    { key: 'btn_color', label: 'Testo pulsante', type: 'color' },
    { key: 'btn_radius', label: 'Border radius (px)', type: 'border-radius' },
    { key: 'btn_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius' },
    { key: 'btn_full_width', label: 'Larghezza piena', type: 'toggle' },
  ],
};
