export default {
  type: 'serviceexcerpt',
  name: 'Descrizione Breve',
  icon: 'dashicons-editor-paragraph',
  category: 'booking',
  defaults: {
    show_title: false,
    title_text: '',
    title_size: '16',
    text_size: '15',
    title_color: '',
    text_color: '',
    font_style: 'italic',
    line_height: '1.7',
    max_width: '0',
    text_align: 'left',
    bg_color: '',
    border_color: '',
    border_radius: '0',
    tile_padding: { top: 0, right: 0, bottom: 0, left: 0 },
  },
  fields: [
    { type: 'separator', label: 'Titolo' },
    { key: 'show_title', label: 'Mostra titolo', type: 'toggle' },
    { key: 'title_text', label: 'Testo titolo', type: 'text',
      condition: { field: 'show_title', value: true } },

    { type: 'separator', label: 'Stile testo' },
    { key: 'text_size', label: 'Dimensione testo (px)', type: 'range', min: 12, max: 22, step: 1 },
    { key: 'font_style', label: 'Stile font', type: 'select', options: [
      { value: 'italic', label: 'Corsivo' },
      { value: 'normal', label: 'Normale' },
    ] },
    { key: 'line_height', label: 'Interlinea', type: 'range', min: 1.2, max: 2.2, step: 0.1 },
    { key: 'text_align', label: 'Allineamento', type: 'select', options: [
      { value: 'left', label: 'Sinistra' },
      { value: 'center', label: 'Centro' },
      { value: 'right', label: 'Destra' },
      { value: 'justify', label: 'Giustificato' },
    ] },
    { key: 'max_width', label: 'Larghezza massima (px, 0 = auto)', type: 'range', min: 0, max: 900, step: 10 },

    { type: 'separator', label: 'Colori' },
    { key: 'title_size', label: 'Dimensione titolo (px)', type: 'range', min: 14, max: 28, step: 1 },
    { key: 'title_color', label: 'Colore titolo', type: 'color' },
    { key: 'text_color', label: 'Colore testo', type: 'color' },

    { type: 'separator', label: 'Contenitore' },
    { key: 'bg_color', label: 'Sfondo', type: 'color' },
    { key: 'border_color', label: 'Bordo', type: 'color' },
    { key: 'border_radius', label: 'Raggio bordi (px)', type: 'border-radius' },
    { key: 'border_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius' },
    { key: 'tile_padding', label: 'Padding (px)', type: 'spacing', max: 32 },
  ],
};
