export default {
  type: 'serviceclub',
  name: 'Club di Prodotto',
  icon: 'dashicons-awards',
  category: 'booking',
  defaults: {
    meta_prefix: '_olo_service_',
    layout: 'horizontal',
    logo_url: '',
    logo_width: '80',
    show_group: false,
    show_category: true,
    text_size: '14',
    text_color: '',
    text_weight: '600',
    group_size: '12',
    group_color: '',
    gap: '12',
    align: 'left',
    bg_color: '',
    border_color: '',
    border_radius: '10',
    tile_padding: { top: 12, right: 12, bottom: 12, left: 12 },
  },
  fields: [
    { type: 'separator', label: 'Sorgente dati' },
    { key: 'meta_prefix', label: 'Tipo servizio', type: 'select', optionsSource: 'metaPrefixes' },

    { type: 'separator', label: 'Layout' },
    { key: 'layout', label: 'Disposizione', type: 'select', options: [
      { value: 'horizontal', label: 'Orizzontale (logo + testo)' },
      { value: 'vertical', label: 'Verticale (logo sopra)' },
    ]},
    { key: 'align', label: 'Allineamento', type: 'select', options: [
      { value: 'left', label: 'Sinistra' },
      { value: 'center', label: 'Centro' },
      { value: 'right', label: 'Destra' },
    ]},
    { key: 'gap', label: 'Spaziatura (px)', type: 'range', min: 0, max: 24, step: 2 },

    { type: 'separator', label: 'Logo' },
    { key: 'logo_url', label: 'URL logo', type: 'image' },
    { key: 'logo_width', label: 'Larghezza logo (px)', type: 'range', min: 30, max: 200, step: 5 },

    { type: 'separator', label: 'Testo' },
    { key: 'show_category', label: 'Mostra categoria', type: 'toggle' },
    { key: 'text_size', label: 'Dim. categoria (px)', type: 'range', min: 11, max: 22, step: 1,
      condition: { field: 'show_category', value: true } },
    { key: 'text_color', label: 'Colore categoria', type: 'color',
      condition: { field: 'show_category', value: true } },
    { key: 'text_weight', label: 'Peso categoria', type: 'select', options: [
      { value: '400', label: 'Regular' },
      { value: '600', label: 'Semi Bold' },
      { value: '700', label: 'Bold' },
    ], condition: { field: 'show_category', value: true } },

    { key: 'show_group', label: 'Mostra gruppo', type: 'toggle' },
    { key: 'group_size', label: 'Dim. gruppo (px)', type: 'range', min: 10, max: 18, step: 1,
      condition: { field: 'show_group', value: true } },
    { key: 'group_color', label: 'Colore gruppo', type: 'color',
      condition: { field: 'show_group', value: true } },

    { type: 'separator', label: 'Sfondo e bordi' },
    { key: 'bg_color', label: 'Colore sfondo', type: 'color' },
    { key: 'border_color', label: 'Colore bordo', type: 'color' },
    { key: 'border_radius', label: 'Raggio bordi (px)', type: 'border-radius' },
    { key: 'border_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius' },
    { key: 'tile_padding', label: 'Padding (px)', type: 'spacing', max: 32 },
  ],
};
