export default {
  type: 'shapedivider',
  name: 'Shape Divider',
  icon: 'dashicons-editor-contract',
  category: 'layout',
  defaults: {
    shape: 'wave',
    position: 'bottom',
    flip_horizontal: false,
    flip_vertical: false,
    width: '100',
    height: '80',
    color: '',
    z_index: '1',
    responsive_height_tablet: '',
    responsive_height_mobile: '',
  },
  fields: [
    { key: 'shape', label: 'Forma', type: 'select', options: [
      { value: 'wave', label: 'Onda' },
      { value: 'wave2', label: 'Onda doppia' },
      { value: 'triangle', label: 'Triangolo' },
      { value: 'tilt', label: 'Inclinato' },
      { value: 'arrow', label: 'Freccia' },
      { value: 'zigzag', label: 'Zigzag' },
      { value: 'mountains', label: 'Montagne' },
      { value: 'clouds', label: 'Nuvole' },
      { value: 'drops', label: 'Gocce' },
      { value: 'curve', label: 'Curva' },
    ]},
    { key: 'position', label: 'Posizione', type: 'select', options: [
      { value: 'top', label: 'Alto' },
      { value: 'bottom', label: 'Basso' },
    ]},
    { key: 'color', label: 'Colore', type: 'color' },
    { key: 'height', label: 'Altezza (px)', type: 'range', min: 10, max: 500, step: 5 },
    { key: 'width', label: 'Larghezza (%)', type: 'range', min: 100, max: 300, step: 5 },
    { key: 'flip_horizontal', label: 'Specchia orizzontale', type: 'toggle' },
    { key: 'flip_vertical', label: 'Specchia verticale', type: 'toggle' },
    { key: 'z_index', label: 'Z-Index', type: 'range', min: 0, max: 99, step: 1 },

    { type: 'separator', label: 'Responsive' },
    { key: 'responsive_height_tablet', label: 'Altezza tablet (px)', type: 'text' },
    { key: 'responsive_height_mobile', label: 'Altezza mobile (px)', type: 'text' },
  ],
};
