
import { borderFields, borderDefault, borderHoverDefault, borderEffectDefaults } from './_shared.js';
export default {
  type: 'sharebuttons',
  name: 'Condivisione',
  icon: 'dashicons-share-alt',
  category: 'marketing',
  defaults: {
    buttons: [
      { id: 'sh-1', platform: 'facebook',  custom_label: '' },
      { id: 'sh-2', platform: 'twitter',   custom_label: '' },
      { id: 'sh-3', platform: 'whatsapp',  custom_label: '' },
      { id: 'sh-4', platform: 'linkedin',  custom_label: '' },
      { id: 'sh-5', platform: 'email',     custom_label: '' },
    ],
    style: 'icon-only',
    size: '36',
    gap: '10',
    alignment: 'center',
    icon_color: '',
    icon_hover_color: '',
    bg_color: '',
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
  },
  fields: [
    { key: 'buttons', label: 'Pulsanti', type: 'content-items',
      itemFields: [
        { key: 'platform', label: 'Piattaforma', type: 'select', options: [
          { value: 'facebook',  label: 'Facebook' },
          { value: 'twitter',   label: 'X / Twitter' },
          { value: 'whatsapp',  label: 'WhatsApp' },
          { value: 'linkedin',  label: 'LinkedIn' },
          { value: 'email',     label: 'Email' },
          { value: 'copylink',  label: 'Copia link' },
          { value: 'telegram',  label: 'Telegram' },
          { value: 'pinterest', label: 'Pinterest' },
        ]},
        { key: 'custom_label', label: 'Etichetta personalizzata', type: 'text' },
      ],
    },
    { key: 'style', label: 'Stile', type: 'select', options: [
      { value: 'icon-only',  label: 'Solo icona' },
      { value: 'icon-text',  label: 'Icona + testo' },
      { value: 'text-only',  label: 'Solo testo' },
    ]},
    { key: 'size', label: 'Dimensione (px)', type: 'range', min: 24, max: 64, step: 2 },
    { key: 'gap', label: 'Gap (px)', type: 'range', min: 4, max: 24, step: 2 },
    { key: 'alignment', label: 'Allineamento', type: 'select', options: [
      { value: 'left',   label: 'Sinistra' },
      { value: 'center', label: 'Centro' },
      { value: 'right',  label: 'Destra' },
    ]},
    { key: 'icon_color', label: 'Colore icona', type: 'color' },
    { key: 'icon_hover_color', label: 'Colore icona hover', type: 'color' },
    { key: 'bg_color', label: 'Colore sfondo', type: 'color' },
    ...borderFields(),
  ],
};
