import { shadowField, borderFields, borderDefault, borderHoverDefault, borderEffectDefaults, withHover } from './_shared.js';
import { t } from '@/i18n';

/**
 * Tile ShatteredImage — split CONTENUTO/STILE.
 *   fields[]      → immagine, preset maschera, height, image_position, zoom variation, kenburns toggle/style/duration/intensity, scroll effects, overlay
 *   styleFields[] → gap (mascherata), gap_color, border_radius esterno, shadow, border
 */
export default {
  type: 'shatteredimage',
  name: t('Shattered Image'),
  icon: 'dashicons-shield',
  category: 'media',
  defaults: {
    image_url: '',
    preset: 'shards',
    gap: 4,
    height: '400px',
    image_position: 'center center',
    gap_color: 'transparent',
    zoom_variation: false,
    zoom_min: 100,
    zoom_max: 180,
    zoom_random: false,
    scroll_parallax: false,
    scroll_parallax_intensity: 30,
    scroll_reveal: false,
    scroll_reveal_stagger: 150,
    scroll_reveal_duration: 600,
    kenburns: true,
    kenburns_style: 'mixed',
    kenburns_duration: 20,
    kenburns_intensity: 1.25,
    overlay: false,
    overlay_color: 'var(--olo-color-dark, #16263d)',
    overlay_opacity: 30,
    border_radius_outer: 0,
    shadow: 'none',
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
  },

  fields: [
    { key: 'image_url', label: t('Immagine'), type: 'image' },

    { type: 'separator', label: t('Maschera') },
    { key: 'preset', label: t('Preset'), type: 'select', options: [
      { value: 'shards', label: t('Frantumi (simmetrico 5)') },
      { value: 'radial_center', label: t('Radiale centro (8)') },
      { value: 'shards_left', label: t('Radiale sinistra (6)') },
      { value: 'shards_right', label: t('Radiale destra (6)') },
      { value: 'shards_top', label: t('Radiale alto (6)') },
      { value: 'shards_bottom', label: t('Radiale basso (6)') },
      { value: 'columns', label: t('Colonne (3)') },
      { value: 'columns_4', label: t('Colonne (4)') },
      { value: 'columns_5', label: t('Colonne (5)') },
      { value: 'columns_6', label: t('Colonne (6)') },
      { value: 'mosaic', label: t('Mosaico (3+2)') },
      { value: 'mosaic_4', label: t('Mosaico (2×2)') },
      { value: 'mosaic_6', label: t('Mosaico (3×2)') },
      { value: 'diagonal', label: t('Diagonali (3)') },
      { value: 'diagonal_4', label: t('Diagonali (4)') },
      { value: 'diagonal_5', label: t('Diagonali (5)') },
      { value: 'diagonal_reverse', label: t('Diagonali inverse (3)') },
      { value: 'honeycomb', label: t('Esagoni (4)') },
      { value: 'honeycomb_6', label: t('Esagoni (6)') },
      { value: 'honeycomb_8', label: t('Esagoni (8)') },
      { value: 'circles_3', label: t('Cerchi (3)') },
      { value: 'circles_4', label: t('Cerchi (2×2)') },
      { value: 'circles_5', label: t('Cerchi (3+2)') },
      { value: 'circles_6', label: t('Cerchi (3×2)') },
      { value: 'circles_7', label: t('Cerchi (7 hex)') },
      { value: 'circles_scattered', label: t('Cerchi sparsi (9)') },
    ]},
    { key: 'height', label: t('Altezza'), type: 'unit', units: ['px', 'vh'], min: 0 },
    { key: 'image_position', label: t('Posizione immagine'), type: 'object-position',
      contextKeys: { src: 'image_url', fit: null, ratio: null, ratioCustom: null },
      options: [
        { value: 'center center', label: t('Centro') },
        { value: 'top center', label: t('Alto') },
        { value: 'bottom center', label: t('Basso') },
        { value: 'left center', label: t('Sinistra') },
        { value: 'right center', label: t('Destra') },
      ]},

    { type: 'separator', label: t('Zoom frammenti') },
    { key: 'zoom_variation', label: t('Zoom variato per frammento'), type: 'toggle' },
    { key: 'zoom_min', label: t('Zoom minimo (%)'), type: 'range', min: 100, max: 250, step: 5,
      show: s => !!s.zoom_variation },
    { key: 'zoom_max', label: t('Zoom massimo (%)'), type: 'range', min: 120, max: 350, step: 5,
      show: s => !!s.zoom_variation },
    { key: 'zoom_random', label: t('Ordine casuale'), type: 'toggle',
      show: s => !!s.zoom_variation },

    { type: 'separator', label: t('Ken Burns') },
    { key: 'kenburns', label: t('Attiva Ken Burns'), type: 'toggle' },
    { key: 'kenburns_style', label: t('Stile movimento'), type: 'select',
      show: s => !!s.kenburns,
      options: [
        { value: 'mixed', label: t('Misto (ogni frammento diverso)') },
        { value: 'horizontal', label: t('Orizzontale') },
        { value: 'vertical', label: t('Verticale') },
        { value: 'diagonal', label: t('Diagonale') },
        { value: 'radial', label: t('Radiale (dal centro)') },
        { value: 'zoom', label: t('Solo zoom (nessuno spostamento)') },
        { value: 'rotation', label: t('Rotazione (zoom + leggera rotazione)') },
        { value: 'chaotic', label: t('Caotico (massima variazione)') },
      ]},
    { key: 'kenburns_duration', label: t('Durata ciclo (s)'), type: 'range', min: 10, max: 40, step: 1,
      show: s => !!s.kenburns },
    { key: 'kenburns_intensity', label: t('Intensità zoom'), type: 'range', min: 1.10, max: 1.40, step: 0.01,
      show: s => !!s.kenburns },

    { type: 'separator', label: t('Effetti scroll (solo frontend)') },
    { key: 'scroll_parallax', label: t('Parallax per frammento'), type: 'toggle' },
    { key: 'scroll_parallax_intensity', label: t('Intensità (px)'), type: 'range', min: 10, max: 80, step: 5,
      show: s => !!s.scroll_parallax },
    { key: 'scroll_reveal', label: t('Reveal sequenziale'), type: 'toggle' },
    { key: 'scroll_reveal_stagger', label: t('Stagger (ms)'), type: 'range', min: 50, max: 400, step: 25,
      show: s => !!s.scroll_reveal },
    { key: 'scroll_reveal_duration', label: t('Durata (ms)'), type: 'range', min: 200, max: 1200, step: 50,
      show: s => !!s.scroll_reveal },

    { type: 'separator', label: t('Overlay') },
    { key: 'overlay', label: t('Attiva overlay'), type: 'toggle' },
  ],

  styleFields: [
    { type: 'separator', label: t('Maschera — Aspetto') },
    { key: 'gap', label: t('Gap (px)'), type: 'range', min: 0, max: 16, step: 1 },
    { key: 'gap_color', label: t('Colore sfondo gap'), type: 'color' },

    { type: 'separator', label: t('Overlay — Aspetto') },
    { key: 'overlay_color', label: t('Colore overlay'), type: 'color',
      show: s => !!s.overlay },
    { key: 'overlay_opacity', label: t('Opacità (%)'), type: 'range', min: 5, max: 90, step: 1,
      show: s => !!s.overlay },

    { type: 'separator', label: t('Avanzato') },
    withHover({ key: 'border_radius_outer', label: t('Border radius'), type: 'border-radius' }),

    ...shadowField,
    ...borderFields(),
  ],
};
