import { shadowField, borderFields, borderDefault, borderHoverDefault, borderEffectDefaults, withHover, wowEffectsFields, wowEffectsDefaults } from './_shared.js';
import { t } from '@/i18n';

/**
 * Tile Sitemap HTML — split CONTENUTO/STILE (regola universale Olobuild).
 *   fields[]      → contenuto (show_pages/posts/categories/tags/authors/archives/cpt,
 *                   cpt_names, exclude_ids, page_tree, limit_per_section, order_by),
 *                   layout_mode, columns, title_tag, list_style, indent (px),
 *                   toggle arricchimento voci (show_counter/icons/excerpt/date/thumb),
 *                   excerpt_length, behavior ricerca (enable_search + placeholder)
 *   styleFields[] → preset, effect_color, effect_intensity, effect_speed (ms),
 *                   gap/item_gap (spaziatura sezioni/voci), tipografia (font_family,
 *                   font_weight, text_transform, letter_spacing),
 *                   colori (title/link+hover/text/bg/accent), container_padding,
 *                   container_radius, shadow, borderFields
 */
export default {
  type: 'sitemap',
  name: t('Sitemap HTML'),
  icon: 'dashicons-networking',
  category: 'dynamic',
  defaults: {
    preset: 'classic-columns',
    typography_preset: '',
    // Contenuto
    show_pages: true,
    show_posts: true,
    show_categories: true,
    show_tags: false,
    show_authors: false,
    show_archives: false,
    show_cpt: false,
    cpt_names: '',
    exclude_ids: '',
    page_tree: true,
    limit_per_section: 100,
    order_by: 'title',
    // Layout
    layout_mode: 'columns',
    columns: '2',
    title_tag: 'h3',
    list_style: 'disc',
    indent: '20',
    gap: 24,
    item_gap: 6,
    // Item arricchito
    show_counter: false,
    show_icons: false,
    show_excerpt: false,
    excerpt_length: 80,
    show_date: false,
    show_thumb: false,
    // Behavior
    enable_search: false,
    search_placeholder: 'Cerca…',
    // Tipografia
    font_family: 'inherit',
    font_weight: '400',
    text_transform: 'none',
    letter_spacing: 0,
    // Colori
    title_color: '',
    link_color: '',
    hover_color: '',
    text_color: '',
    bg_color: '',
    accent_color: '',
    // Container
    container_padding: { top: 16, right: 16, bottom: 16, left: 16 },
    container_radius: { tl: 0, tr: 0, br: 0, bl: 0 },
    // Effetti preset
    effect_color: '',
    effect_intensity: 'medium',
    effect_speed: 0,
    shadow: 'none',
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
    ...wowEffectsDefaults,
  },

  // ─── CONTENUTO ─────────────────────────────────────────────
  fields: [
    { type: 'separator', label: t('Contenuto') },
    { key: 'show_pages',      label: t('Mostra pagine'), type: 'toggle' },
    { key: 'page_tree',       label: t('Pagine ad albero (gerarchia)'), type: 'toggle',
      condition: { field: 'show_pages', value: true } },
    { key: 'show_posts',      label: t('Mostra articoli'), type: 'toggle' },
    { key: 'show_categories', label: t('Mostra categorie'), type: 'toggle' },
    { key: 'show_tags',       label: t('Mostra tag'), type: 'toggle' },
    { key: 'show_authors',    label: t('Mostra autori'), type: 'toggle' },
    { key: 'show_archives',   label: t('Mostra archivi mensili'), type: 'toggle' },
    { key: 'show_cpt',        label: t('Mostra CPT'), type: 'toggle' },
    { key: 'cpt_names',       label: t('Nomi CPT (virgola)'), type: 'text', placeholder: t('portfolio,prodotto'),
      condition: { field: 'show_cpt', value: true } },
    { key: 'exclude_ids',     label: t('Escludi ID (virgola)'), type: 'text', placeholder: '1,42,99' },
    { key: 'limit_per_section', label: t('Massimo voci per sezione'), type: 'range', min: 5, max: 500, step: 5 },
    { key: 'order_by', label: t('Ordina per'), type: 'select', options: [
      { value: 'title',     label: t('Titolo (A-Z)') },
      { value: 'date',      label: t('Data (più recenti prima)') },
      { value: 'date_asc',  label: t('Data (più vecchi prima)') },
      { value: 'menu_order', label: t('Ordine menu') },
    ]},

    { type: 'separator', label: t('Layout') },
    { key: 'layout_mode', label: t('Modalità layout'), type: 'select', options: [
      { value: 'columns',   label: t('Colonne (lista classica)') },
      { value: 'cards',     label: t('Card grid') },
      { value: 'tree',      label: t('Tree indentato') },
      { value: 'index-az',  label: t('Indice A-Z') },
      { value: 'cloud',     label: t('Cloud (font pesato)') },
      { value: 'compact',   label: t('Compact chips') },
      { value: 'honeycomb', label: t('Honeycomb (esagoni)') },
      { value: 'mindmap',   label: t('Mind map (radiale)') },
      { value: 'terminal',  label: t('Terminal ASCII') },
    ]},
    { key: 'columns', label: t('Colonne'), type: 'select',
      condition: { field: 'layout_mode', op: 'in', value: ['columns', 'cards', 'compact'] }, options: [
      { value: '1', label: t('1 colonna') },
      { value: '2', label: t('2 colonne') },
      { value: '3', label: t('3 colonne') },
      { value: '4', label: t('4 colonne') },
    ]},
    { key: 'title_tag', label: t('Tag titolo sezione'), type: 'select', options: [
      { value: 'h2', label: t('H2') },
      { value: 'h3', label: t('H3') },
      { value: 'h4', label: t('H4') },
      { value: 'h5', label: t('H5') },
    ]},
    { key: 'list_style', label: t('Stile bullet'), type: 'select',
      condition: { field: 'layout_mode', op: 'in', value: ['columns', 'cards'] }, options: [
      { value: 'disc',   label: t('Punto pieno') },
      { value: 'circle', label: t('Cerchio vuoto') },
      { value: 'arrow',  label: t('Freccia →') },
      { value: 'check',  label: t('Spunta ✓') },
      { value: 'none',   label: t('Nessuno') },
    ]},
    { key: 'indent', label: t('Indentazione (px)'), type: 'range', min: 0, max: 60, step: 4,
      condition: { field: 'layout_mode', op: 'in', value: ['columns', 'cards', 'tree'] } },

    { type: 'separator', label: t('Arricchimento voci') },
    { key: 'show_counter',  label: t('Contatore (N) accanto alla sezione'), type: 'toggle' },
    { key: 'show_icons',    label: t('Icona per tipo (page/post/tag/…)'), type: 'toggle' },
    { key: 'show_date',     label: t('Mostra data accanto al titolo'), type: 'toggle' },
    { key: 'show_excerpt',  label: t('Mostra anteprima testo'), type: 'toggle' },
    { key: 'excerpt_length', label: t('Lunghezza anteprima (caratteri)'), type: 'range', min: 30, max: 200, step: 10,
      condition: { field: 'show_excerpt', value: true } },
    { key: 'show_thumb',    label: t('Mostra thumbnail'), type: 'toggle' },

    { type: 'separator', label: t('Comportamento') },
    { key: 'enable_search', label: t('Abilita campo ricerca'), type: 'toggle' },
    { key: 'search_placeholder', label: t('Placeholder ricerca'), type: 'text',
      condition: { field: 'enable_search', value: true } },
  ],

  // ─── STILE ─────────────────────────────────────────────────
  styleFields: [
    { type: 'separator', label: t('Preset stilistico') },
    { key: 'preset', label: t('Stile'), type: 'select', options: [
      { value: 'classic-columns', label: t('Classic Columns') },
      { value: 'card-grid',       label: t('Card Grid') },
      { value: 'index-az',        label: t('Index A-Z') },
      { value: 'tag-cloud',       label: t('Tag Cloud') },
      { value: 'compact-chips',   label: t('Compact Chips') },
      { value: 'glass-cards',     label: t('Glass Cards') },
      { value: 'neon-schematic',  label: t('Neon Schematic') },
      { value: 'brutalist-map',   label: t('Brutalist Map') },
      { value: 'mind-map',        label: t('Mind Map') },
      { value: 'sticky-notes',    label: t('Sticky Notes') },
      { value: 'retro-terminal',  label: t('Retro Terminal') },
      { value: 'honeycomb',       label: t('Honeycomb') },
      { value: 'custom',          label: t('Personalizzato') },
    ]},
    { key: 'effect_color', label: t('Colore effetto'), type: 'color',
      condition: { field: 'preset', op: 'in', value: ['neon-schematic', 'brutalist-map', 'mind-map', 'retro-terminal', 'glass-cards', 'honeycomb'] } },
    { key: 'effect_intensity', label: t('Intensità effetto'), type: 'select', options: [
      { value: 'low',    label: t('Bassa') },
      { value: 'medium', label: t('Media') },
      { value: 'high',   label: t('Alta') },
    ], condition: { field: 'preset', op: 'in', value: ['neon-schematic', 'brutalist-map', 'glass-cards', 'mind-map'] } },
    { key: 'effect_speed', label: t('Velocità animazione (ms, 0=default)'), type: 'range', min: 0, max: 5000, step: 100,
      condition: { field: 'preset', op: 'in', value: ['neon-schematic', 'retro-terminal', 'mind-map'] } },

    { type: 'separator', label: t('Spaziatura layout') },
    { key: 'gap', label: t('Spazio tra sezioni (px)'), type: 'range', min: 0, max: 80, step: 4 },
    { key: 'item_gap', label: t('Spazio tra voci (px)'), type: 'range', min: 0, max: 24, step: 1 },

    { type: 'separator', label: t('Tipografia') },
    { type: 'typography', label: t('Voci'),
      presetKey: 'typography_preset',
      keys: {
        family:        'font_family',
        weight:        'font_weight',
        transform:     'text_transform',
        letterSpacing: 'letter_spacing',
        color:         'text_color',
      },
    },
    { type: 'typography', label: t('Titolo sezione'),
      presetKey: 'typography_preset',
      keys: {
        color: 'title_color',
      },
    },
    { type: 'typography', label: t('Link'),
      presetKey: 'typography_preset',
      keys: {
        color:      'link_color',
        colorHover: 'hover_color',
      },
    },

    { type: 'separator', label: t('Colori') },
    { key: 'bg_color',      label: t('Sfondo container'), type: 'color' },
    { key: 'accent_color',  label: t('Colore accento (icone, bullet, hub)'), type: 'color' },

    { type: 'separator', label: t('Container') },
    { key: 'container_padding', label: t('Padding container'), type: 'spacing', max: 48 },
    { key: 'container_radius', label: t('Raggio bordi container'), type: 'border-radius' },

    ...shadowField,
    ...wowEffectsFields(),
    ...borderFields(),
  ],
};
