import { shadowField } from './_shared.js';

export default {
  type: 'sitemap',
  name: 'Sitemap HTML',
  icon: 'dashicons-networking',
  category: 'dynamic',
  defaults: {
    show_pages: true,
    show_posts: true,
    show_cpt: false,
    cpt_names: '',
    show_categories: true,
    columns: '2',
    title_tag: 'h3',
    title_color: '',
    link_color: '',
    hover_color: '',
    list_style: 'disc',
    indent: '20',
    exclude_ids: '',
    shadow: 'none',
  },
  fields: [
    { type: 'separator', label: 'Contenuto' },
    { key: 'show_pages', label: 'Mostra pagine', type: 'toggle' },
    { key: 'show_posts', label: 'Mostra articoli', type: 'toggle' },
    { key: 'show_categories', label: 'Mostra categorie', type: 'toggle' },
    { key: 'show_cpt', label: 'Mostra CPT', type: 'toggle' },
    { key: 'cpt_names', label: 'Nomi CPT (virgola)', type: 'text', placeholder: 'portfolio,prodotto',
      condition: { field: 'show_cpt', operator: '==', value: true } },
    { key: 'exclude_ids', label: 'Escludi ID (virgola)', type: 'text', placeholder: '1,42,99' },
    { type: 'separator', label: 'Layout' },
    { key: 'columns', label: 'Colonne', type: 'select', options: [
      { value: '1', label: '1 colonna' },
      { value: '2', label: '2 colonne' },
      { value: '3', label: '3 colonne' },
      { value: '4', label: '4 colonne' },
    ]},
    { key: 'title_tag', label: 'Tag titolo', type: 'select', options: [
      { value: 'h2', label: 'H2' },
      { value: 'h3', label: 'H3' },
      { value: 'h4', label: 'H4' },
      { value: 'h5', label: 'H5' },
    ]},
    { key: 'list_style', label: 'Stile lista', type: 'select', options: [
      { value: 'disc', label: 'Punto pieno' },
      { value: 'circle', label: 'Cerchio vuoto' },
      { value: 'none', label: 'Nessuno' },
    ]},
    { key: 'indent', label: 'Indentazione (px)', type: 'range', min: 0, max: 60, step: 4 },
    { type: 'separator', label: 'Colori' },
    { key: 'title_color', label: 'Colore titolo', type: 'color' },
    { key: 'link_color', label: 'Colore link', type: 'color' },
    { key: 'hover_color', label: 'Colore hover', type: 'color' },
    ...shadowField,
  ],
};
