import { shadowField, borderFields, borderDefault, borderHoverDefault, borderEffectDefaults } from './_shared.js';

export default {
  type: 'social',
  name: 'Link social',
  icon: 'dashicons-share',
  category: 'marketing',
  defaults: {
    links: [
      { id: 's-1', platform: 'facebook',  url: 'https://facebook.com' },
      { id: 's-2', platform: 'twitter',   url: 'https://x.com' },
      { id: 's-3', platform: 'instagram', url: 'https://instagram.com' },
      { id: 's-4', platform: 'linkedin',  url: 'https://linkedin.com' },
    ],
    size: '32',
    alignment: 'center',
    gap: '12',
    shadow: 'none',
    style: 'filled',
    show_labels: false,
    icon_color: '',
    hover_effect: 'lift',
    use_brand_colors: true,
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
  },
  fields: [
    { type: 'separator', label: 'Piattaforme' },
    { key: 'links', label: 'Piattaforme', type: 'content-items',
      itemFields: [
        { key: 'platform', label: 'Piattaforma', type: 'select', options: [
          { value: 'facebook',  label: 'Facebook' },
          { value: 'twitter',   label: 'X / Twitter' },
          { value: 'instagram', label: 'Instagram' },
          { value: 'linkedin',  label: 'LinkedIn' },
          { value: 'youtube',   label: 'YouTube' },
          { value: 'tiktok',    label: 'TikTok' },
          { value: 'whatsapp',  label: 'WhatsApp' },
          { value: 'telegram',  label: 'Telegram' },
          { value: 'pinterest', label: 'Pinterest' },
          { value: 'discord',   label: 'Discord' },
          { value: 'twitch',    label: 'Twitch' },
          { value: 'spotify',   label: 'Spotify' },
          { value: 'snapchat',  label: 'Snapchat' },
          { value: 'github',    label: 'GitHub' },
          { value: 'email',     label: 'Email' },
          { value: 'website',   label: 'Sito web' },
        ]},
        { key: 'url', label: 'URL', type: 'text' },
      ],
    },
    { key: 'show_labels', label: 'Mostra nomi piattaforma', type: 'toggle' },

    { type: 'separator', label: 'Layout' },
    { key: 'size', label: 'Dim. icona (px)', type: 'range', min: 20, max: 60, step: 4 },
    { key: 'gap', label: 'Gap (px)', type: 'range', min: 0, max: 48, step: 4 },
    { key: 'alignment', label: 'Allineamento', type: 'select', options: [
      { value: 'left', label: 'Sinistra' },
      { value: 'center', label: 'Centro' },
      { value: 'right', label: 'Destra' },
    ]},

    { type: 'separator', label: 'Stile' },
    { key: 'style', label: 'Stile', type: 'select', options: [
      { value: 'filled', label: 'Pieno (sfondo colorato)' },
      { value: 'outline', label: 'Contorno' },
      { value: 'minimal', label: 'Minimale' },
    ]},
    { key: 'use_brand_colors', label: 'Colori brand', type: 'toggle' },
    { key: 'icon_color', label: 'Colore personalizzato', type: 'color',
      condition: { field: 'use_brand_colors', operator: '!=', value: true } },

    { type: 'separator', label: 'Hover' },
    { key: 'hover_effect', label: 'Effetto hover', type: 'select', options: [
      { value: 'none', label: 'Nessuno' },
      { value: 'lift', label: 'Solleva' },
      { value: 'grow', label: 'Ingrandisci' },
      { value: 'glow', label: 'Bagliore' },
    ]},

    { type: 'separator', label: 'Aspetto' },
    ...shadowField,
    ...borderFields(),
  ],
};
