
import { borderFields, borderDefault, borderHoverDefault, borderEffectDefaults } from './_shared.js';
export default {
  type: 'soundcloud',
  name: 'SoundCloud',
  icon: 'dashicons-format-audio',
  category: 'media',
  defaults: {
    url: '',
    auto_play: false,
    show_artwork: true,
    show_user: true,
    color: '',
    visual: true,
    height: '166',
    alignment: 'center',
    border_radius: '8',
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
  },
  fields: [
    { key: 'url', label: 'URL SoundCloud', type: 'text', placeholder: 'https://soundcloud.com/...' },
    { key: 'visual', label: 'Player visuale (grande)', type: 'toggle' },
    { key: 'height', label: 'Altezza (px)', type: 'range', min: 100, max: 600, step: 10 },
    { type: 'separator', label: 'Riproduzione' },
    { key: 'auto_play', label: 'Riproduzione automatica', type: 'toggle' },
    { key: 'show_artwork', label: 'Mostra copertina', type: 'toggle' },
    { key: 'show_user', label: 'Mostra autore', type: 'toggle' },
    { type: 'separator', label: 'Stile' },
    { key: 'color', label: 'Colore accento', type: 'color' },
    { key: 'alignment', label: 'Allineamento', type: 'select', options: [
      { value: 'left', label: 'Sinistra' },
      { value: 'center', label: 'Centro' },
      { value: 'right', label: 'Destra' },
    ]},
    { key: 'border_radius', label: 'Arrotondamento angoli (px)', type: 'border-radius' },
    { key: 'border_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius' },
    ...borderFields(),
  ],
};
