import { textEffectsFields, textEffectsDefaults, borderFields, borderDefault, borderHoverDefault, borderEffectDefaults, shadowField, widgetTemplateField, wowEffectsFields, wowEffectsDefaults } from './_shared';
import { t } from '@/i18n';

/**
 * Tile SwitcherPanel — split CONTENUTO/STILE.
 *   fields[]      → items pannelli (nav_label+title+text+button+image), hero image + height, layout (nav_position/image_position), animation
 *   styleFields[] → preset, bg, typo, effetti, text-effects, hero overlay & radius, nav typo/container/colori/indicator, pannello stile, button style, shadow, border
 */
export default {
  type: 'switcherpanel',
  name: t('Switcher Panel'),
  icon: 'dashicons-images-alt',
  category: 'interactive',
  defaults: {
    bg: { type: 'none' },
    typography_preset: '',
    items: [
      { id: 'sp-1', nav_label: 'About Us', title: t('Benvenuti nel nostro mondo'), text: 'Un\'esperienza unica che unisce eleganza, comfort e attenzione ai dettagli. Scopri ciò che ci rende speciali.', button_text: 'SCOPRI DI PIÙ', button_url: '#', image: 'https://images.unsplash.com/photo-1774192621035-20d11389f781?w=1200&q=75&auto=format&fit=crop' },
      { id: 'sp-2', nav_label: 'Bar & Cocktails', title: t('Mixology d\'autore'), text: 'Cocktail signature creati dai nostri bartender, con ingredienti selezionati e una carta che cambia con le stagioni.', button_text: 'VEDI LA CARTA', button_url: '#', image: 'https://images.unsplash.com/photo-1760463502141-2b5166df169e?w=1200&q=75&auto=format&fit=crop' },
      { id: 'sp-3', nav_label: 'Restaurant', title: t('Cucina contemporanea'), text: 'Piatti raffinati che raccontano il territorio attraverso una cucina di stagione, leggera e creativa.', button_text: 'PRENOTA UN TAVOLO', button_url: '#', image: 'https://images.unsplash.com/photo-1731941465921-eb4285693713?w=1200&q=75&auto=format&fit=crop' },
    ],
    hero_image: 'https://images.unsplash.com/photo-1723465308831-29da05e011f3?w=1600&q=75&auto=format&fit=crop',
    hero_height: 400,
    image_position: 'right',
    image_bleed: false,
    nav_style: 'minimal',
    animation: 'fade',
    animation_duration: 300,
    tile_padding: { top: 40, right: 40, bottom: 40, left: 40 },
    title_tag: 'h3',
    button_style: 'primary',
    preset: 'editorial-overlay',
    nav_position: 'overlay',
    layout_mode: 'split',
    panel_gap: 24,
    nav_padding_y: 12,
    nav_padding_x: 18,
    nav_font_size: 12,
    nav_font_weight: '700',
    nav_letter_spacing: 0.08,
    nav_uppercase: true,
    nav_gap: 0,
    nav_radius: 0,
    nav_container_bg: 'transparent',
    nav_container_padding: 0,
    nav_container_radius: 0,
    nav_active_bg: 'transparent',
    nav_active_color: '#ffffff',
    nav_inactive_color: 'rgba(255,255,255,0.65)',
    nav_hover_bg: 'transparent',
    nav_indicator_type: 'underline',
    nav_indicator_color: '#ffffff',
    nav_indicator_thickness: 2,
    hero_overlay_color: 'rgba(0,0,0,0.35)',
    hero_overlay_gradient: true,
    hero_radius: 0,
    hero_object_position: 'center center',
    panel_bg: '#ffffff',
    panel_text_color: '#1e293b',
    panel_title_color: '#0f172a',
    panel_title_size: 28,
    panel_title_weight: '700',
    panel_text_size: 15,
    panel_radius: 0,
    panel_image_radius: 0,
    panel_image_ratio: 'auto',
    panel_image_width: 40,
    shadow: 'none',
    effect_color: '',
    effect_intensity: 'medium',
    effect_speed: 0,
    ...textEffectsDefaults,
    text_effect_target: 'title',
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
    ...wowEffectsDefaults,
  },

  fields: [
    { key: 'items', label: t('Pannelli'), type: 'content-items',
      itemFields: [
        { key: 'nav_label', label: t('Etichetta navigazione'), type: 'text' },
        { key: 'title', label: t('Titolo'), type: 'text' },
        widgetTemplateField,
        { key: 'text', label: t('Testo'), type: 'textarea' },
        { key: 'button_text', label: t('Testo pulsante'), type: 'text' },
        { key: 'button_url', label: t('URL pulsante'), type: 'link' },
        { key: 'image', label: t('Immagine'), type: 'image' },
        { key: 'hover_image', label: t('Immagine hover'), type: 'image' },
        { key: 'hover_video', label: t('Video hover'), type: 'media' },
      ],
      newItemDefaults: { nav_label: 'Nuovo', title: t('Nuovo pannello'), text: 'Contenuto del pannello.', button_text: 'SCOPRI', button_url: '#', image: '', hover_image: '', hover_video: '', widget_template_id: 0 },
      itemLabel: 'Pannello',
    },

    { type: 'separator', label: t('Hero') },
    { key: 'hero_image', label: t('Immagine hero'), type: 'image' },
    { key: 'hero_height', label: t('Altezza hero (px)'), type: 'range', min: 200, max: 800, step: 10 },

    { type: 'separator', label: t('Layout') },
    { key: 'nav_position', label: t('Posizione navigazione'), type: 'select', options: [
      { value: 'overlay',    label: t('Sopra hero (overlay)') },
      { value: 'top',        label: t('Sopra il pannello') },
      { value: 'bottom',     label: t('Sotto il pannello') },
      { value: 'side-left',  label: t('Lato sinistro (verticale)') },
      { value: 'side-right', label: t('Lato destro (verticale)') },
    ]},
    { key: 'image_position', label: t('Posizione immagine pannello'), type: 'select', options: [
      { value: 'right', label: t('Destra') },
      { value: 'left',  label: t('Sinistra') },
    ]},
    { key: 'image_bleed', label: t('Immagine a filo bordo (full-bleed)'), type: 'toggle',
      description: t('L\'immagine raggiunge il bordo esterno del viewport (lato della posizione immagine).') },

    { type: 'separator', label: t('Animazione') },
    { key: 'animation', label: t('Animazione'), type: 'select', options: [
      { value: '',             label: t('Nessuna') },
      { value: 'fade',         label: t('Dissolvenza') },
      { value: 'slide-left',   label: t('Scorrimento sinistra') },
      { value: 'slide-right',  label: t('Scorrimento destra') },
      { value: 'slide-top',    label: t('Scorrimento alto') },
      { value: 'slide-bottom', label: t('Scorrimento basso') },
      { value: 'scale',        label: t('Scala') },
    ]},
    { key: 'animation_duration', label: t('Durata transizioni (ms)'), type: 'range', min: 100, max: 800, step: 50 },
  ],

  styleFields: [
    { type: 'separator', label: t('Preset stile') },
    { key: 'preset', label: t('Stile'), type: 'select', options: [
      { value: 'editorial-overlay',  label: t('Editorial Overlay (boutique hotel)') },
      { value: 'magazine-tabs',      label: t('Magazine Tabs (sotto immagine)') },
      { value: 'split-card',         label: t('Split Card (corporate)') },
      { value: 'minimal-text',       label: t('Minimal Text (gallery)') },
      { value: 'sidebar-elegant',    label: t('Sidebar Elegant (Spotify-like)') },
      { value: 'liquid-glass',       label: t('Liquid Glass (Vision Pro)') },
      { value: 'neon-cyber',         label: t('Neon Cyberpunk (Tron)') },
      { value: 'brutalist-block',    label: t('Brutalist Block (neo-brutalist)') },
      { value: 'magnetic-liquid',    label: t('Magnetic Liquid (next-gen)') },
      { value: 'sticker',            label: t('Sticker / Scrapbook') },
      { value: 'retro-terminal',     label: t('Retro Terminal (CRT)') },
      { value: '3d-tilt',            label: t('3D Card Tilt') },
      { value: 'custom',             label: t('Personalizzato (usa controlli sotto)') },
    ]},
    { key: 'typography_preset', label: t('Stile tipografico'), type: 'select', optionsSource: 'globalTypography' },

    { type: 'separator', label: t('Tweak effetto preset'),
      condition: { field: 'preset', op: 'in', value: ['liquid-glass','neon-cyber','brutalist-block','magnetic-liquid','sticker','retro-terminal','3d-tilt'] } },
    { key: 'effect_color', label: t('Colore effetto'), type: 'color',
      condition: { field: 'preset', op: 'in', value: ['neon-cyber','brutalist-block','magnetic-liquid','sticker','retro-terminal'] } },
    { key: 'effect_intensity', label: t('Intensità effetto'), type: 'select',
      options: [
        { value: 'low',    label: t('Bassa') },
        { value: 'medium', label: t('Media (default)') },
        { value: 'high',   label: t('Alta') },
      ],
      condition: { field: 'preset', op: 'in', value: ['liquid-glass','neon-cyber','brutalist-block','magnetic-liquid','sticker','retro-terminal','3d-tilt'] } },
    { key: 'effect_speed', label: t('Velocità animazioni (ms)'), type: 'range',
      min: 0, max: 4000, step: 100,
      condition: { field: 'preset', op: 'in', value: ['neon-cyber','magnetic-liquid','retro-terminal','3d-tilt'] } },

    ...textEffectsFields([
      { value: 'title', label: t('Solo Titolo') },
      { value: 'text', label: t('Solo Testo') },
      { value: 'all', label: t('Tutti gli elementi testuali') },
    ]),

    { type: 'separator', label: t('Hero — Aspetto') },
    { key: 'hero_radius', label: t('Arrotondamento hero (px)'), type: 'border-radius' },
    { key: 'hero_object_position', label: t('Posizione contenuto'), type: 'object-position',
      contextKeys: { src: 'hero_image', height: 'hero_height' } },
    { key: 'hero_overlay_color', label: t('Overlay colore'), type: 'color',
      condition: { field: 'nav_position', op: 'eq', value: 'overlay' } },
    { key: 'hero_overlay_gradient', label: t('Overlay gradiente (alto→basso)'), type: 'toggle',
      condition: { field: 'nav_position', op: 'eq', value: 'overlay' } },

    { type: 'separator', label: t('Pannello — Layout') },
    { key: 'panel_image_width', label: t('Larghezza immagine (%)'), type: 'range', min: 25, max: 60, step: 1 },
    { key: 'panel_image_ratio', label: t('Proporzione immagine'), type: 'select', options: [
      { value: 'auto', label: t('Auto') },
      { value: '16:9', label: '16:9' },
      { value: '4:3',  label: '4:3' },
      { value: '1:1',  label: t('1:1 (quadrata)') },
      { value: '3:4',  label: t('3:4 (verticale)') },
    ]},
    { key: 'panel_gap', label: t('Spazio testo↔immagine (px)'), type: 'range', min: 0, max: 80, step: 4 },
    { key: 'tile_padding', label: t('Padding pannello (px)'), type: 'spacing', max: 80 },
    { key: 'panel_radius', label: t('Arrotondamento pannello (px)'), type: 'border-radius' },
    { key: 'panel_image_radius', label: t('Arrotondamento immagine (px)'), type: 'border-radius' },

    { type: 'separator', label: t('Tipografia') },
    { type: 'typography', label: t('Voce nav'),
      presetKey: 'typography_preset',
      responsiveKeys: ['size', 'letterSpacing'],
      letterSpacingUnit: 'em',
      keys: {
        size:          'nav_font_size',
        weight:        'nav_font_weight',
        letterSpacing: 'nav_letter_spacing',
        color:         'nav_inactive_color',
      },
      sizeMin: 9, sizeMax: 20, sizeStep: 1,
    },
    { type: 'typography', label: t('Titolo pannello'),
      presetKey: 'typography_preset',
      responsiveKeys: ['size'],
      keys: {
        tag:    'title_tag',
        size:   'panel_title_size',
        weight: 'panel_title_weight',
        color:  'panel_title_color',
      },
      sizeMin: 16, sizeMax: 56, sizeStep: 1,
    },
    { type: 'typography', label: t('Testo pannello'),
      presetKey: 'typography_preset',
      responsiveKeys: ['size'],
      keys: {
        size:  'panel_text_size',
        color: 'panel_text_color',
      },
      sizeMin: 12, sizeMax: 22, sizeStep: 1,
    },

    { type: 'separator', label: t('Nav — Spaziatura') },
    { key: 'nav_padding_y', label: t('Padding verticale (px)'), type: 'range', min: 4, max: 24, step: 1 },
    { key: 'nav_padding_x', label: t('Padding orizzontale (px)'), type: 'range', min: 8, max: 32, step: 1 },
    { key: 'nav_uppercase', label: t('Maiuscole'), type: 'toggle' },
    { key: 'nav_gap', label: t('Spazio tra voci (px)'), type: 'range', min: 0, max: 32, step: 1 },
    { key: 'nav_radius', label: t('Arrotondamento voce (px)'), type: 'border-radius' },

    { type: 'separator', label: t('Nav — Container') },
    { key: 'nav_container_bg', label: t('Sfondo container'), type: 'color' },
    { key: 'nav_container_padding', label: t('Padding container (px)'), type: 'range', min: 0, max: 24, step: 1 },
    { key: 'nav_container_radius', label: t('Arrotondamento container (px)'), type: 'border-radius' },

    { type: 'separator', label: t('Nav — Stati') },
    { key: 'nav_active_bg', label: t('Sfondo voce attiva'), type: 'color' },
    { key: 'nav_active_color', label: t('Colore testo attivo'), type: 'color' },
    { key: 'nav_hover_bg', label: t('Sfondo voce hover'), type: 'color' },

    { type: 'separator', label: t('Nav — Indicatore') },
    { key: 'nav_indicator_type', label: t('Tipo indicatore'), type: 'select', options: [
      { value: 'none',      label: t('Nessuno') },
      { value: 'underline', label: t('Sottolineatura') },
      { value: 'overline',  label: t('Linea sopra') },
      { value: 'pill',      label: t('Pill di sfondo') },
      { value: 'left-bar',  label: t('Barra sinistra (verticale)') },
    ]},
    { key: 'nav_indicator_color', label: t('Colore indicatore'), type: 'color' },
    { key: 'nav_indicator_thickness', label: t('Spessore indicatore (px)'), type: 'range', min: 1, max: 6, step: 1 },

    { type: 'separator', label: t('Pannello — Stile') },
    { key: 'panel_bg', label: t('Sfondo pannello'), type: 'color' },

    { type: 'separator', label: t('Pulsante') },
    { key: 'button_style', label: t('Stile pulsante'), type: 'select', options: [
      { value: 'default',   label: t('Predefinito') },
      { value: 'primary',   label: t('Primary') },
      { value: 'secondary', label: t('Secondary') },
      { value: 'text',      label: t('Solo testo (link)') },
      { value: 'underline', label: t('Underline arrow') },
      { value: 'pill',      label: t('Pill rounded') },
    ]},

    ...shadowField,
    ...wowEffectsFields(),
    ...borderFields(),
  ],
};
