import { shadowField } from './_shared.js';

export default {
  type: 'table',
  name: 'Tabella',
  icon: 'dashicons-editor-table',
  category: 'text',
  defaults: {
    table_data: [
      ['Funzionalità', 'Base', 'Pro'],
      ['Spazio', '5 GB', '50 GB'],
      ['Utenti', '1', '10'],
      ['Supporto', 'Email', 'Prioritario'],
    ],
    has_header: true,
    striped: true,
    bordered: true,
    hover_effect: true,
    compact: false,
    first_col_bold: false,
    col_alignments: [],
    responsive_mode: 'scroll',
    header_bg: '',
    header_text_color: '',
    text_color: '',
    border_color: '',
    even_row_bg: '',
    shadow: 'none',
  },
  fields: [
    {
      key: '_table_info',
      type: 'html',
      html: '<div style="font-size:11px;color:#9CA3AF;margin:-4px 0 8px;line-height:1.4">Clicca sulle celle nel canvas per modificarle. Usa i pulsanti + e − per aggiungere o rimuovere righe e colonne.</div>',
    },
    { key: 'has_header', label: 'Riga intestazione', type: 'toggle' },
    { key: 'striped', label: 'Righe alternate', type: 'toggle' },
    { key: 'bordered', label: 'Con bordi', type: 'toggle' },
    { key: 'hover_effect', label: 'Effetto hover', type: 'toggle' },
    { key: 'compact', label: 'Compatto', type: 'toggle' },
    { key: 'first_col_bold', label: 'Prima colonna in grassetto', type: 'toggle' },
    {
      key: 'responsive_mode',
      label: 'Responsive',
      type: 'select',
      options: [
        { value: 'scroll', label: 'Scroll orizzontale' },
        { value: 'stack', label: 'Stack verticale' },
      ],
    },
    { key: 'header_bg', label: 'Sfondo intestazione', type: 'color' },
    { key: 'header_text_color', label: 'Colore testo intestazione', type: 'color' },
    { key: 'text_color', label: 'Colore testo', type: 'color' },
    { key: 'border_color', label: 'Colore bordi', type: 'color' },
    { key: 'even_row_bg', label: 'Sfondo righe pari', type: 'color' },
    ...shadowField,
  ],
};
