import { textEffectsFields, textEffectsDefaults, borderFields, borderDefault, borderHoverDefault, borderEffectDefaults } from './_shared';

export default {
  type: 'tagcloud',
  name: 'Tag Cloud',
  icon: 'dashicons-tag',
  category: 'dynamic',
  defaults: {
    ...textEffectsDefaults,
    taxonomy: 'post_tag',
    custom_taxonomy: '',
    min_font: '12',
    max_font: '28',
    max_tags: '30',
    orderby: 'name',
    order: 'ASC',
    show_count: false,
    separator: ' ',
    layout: 'cloud',
    columns: '3',
    text_color: '',
    hover_color: '',
    background_color: '',
    hover_background: '',
    border_radius: '16',
    padding: { top: 6, right: 14, bottom: 6, left: 14 },
    gap: '8',
    font_weight: '500',
    link_underline: false,
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
  },
  fields: [
    { key: 'taxonomy', label: 'Tassonomia', type: 'select', options: [
      { value: 'post_tag', label: 'Tag' },
      { value: 'category', label: 'Categorie' },
      { value: 'custom', label: 'Tassonomia personalizzata' },
    ]},
    { key: 'custom_taxonomy', label: 'Slug tassonomia', type: 'text', placeholder: 'es. product_tag',
      condition: { field: 'taxonomy', operator: '==', value: 'custom' } },
    { key: 'max_tags', label: 'Numero massimo tag', type: 'range', min: 5, max: 100, step: 5 },
    { key: 'orderby', label: 'Ordina per', type: 'select', options: [
      { value: 'name', label: 'Nome' },
      { value: 'count', label: 'Conteggio' },
    ]},
    { key: 'order', label: 'Ordine', type: 'select', options: [
      { value: 'ASC', label: 'Crescente' },
      { value: 'DESC', label: 'Decrescente' },
    ]},
    { key: 'show_count', label: 'Mostra conteggio', type: 'toggle' },
    { type: 'separator', label: 'Layout' },
    { key: 'layout', label: 'Layout', type: 'select', options: [
      { value: 'cloud', label: 'Cloud (flex)' },
      { value: 'list', label: 'Lista verticale' },
      { value: 'grid', label: 'Griglia' },
    ]},
    { key: 'columns', label: 'Colonne (griglia)', type: 'range', min: 2, max: 6, step: 1,
      condition: { field: 'layout', operator: '==', value: 'grid' } },
    { key: 'gap', label: 'Gap (px)', type: 'range', min: 0, max: 24, step: 2 },
    { type: 'separator', label: 'Tipografia' },
    { key: 'min_font', label: 'Dimensione min (px)', type: 'range', min: 8, max: 24, step: 1 },
    { key: 'max_font', label: 'Dimensione max (px)', type: 'range', min: 16, max: 60, step: 1 },
    { key: 'font_weight', label: 'Peso font', type: 'select', options: [
      { value: '400', label: 'Normale (400)' },
      { value: '500', label: 'Medium (500)' },
      { value: '600', label: 'Semibold (600)' },
      { value: '700', label: 'Bold (700)' },
    ]},
    { key: 'link_underline', label: 'Sottolineatura link', type: 'toggle' },
    { type: 'separator', label: 'Colori' },
    { key: 'text_color', label: 'Colore testo', type: 'color' },
    { key: 'hover_color', label: 'Colore testo hover', type: 'color' },
    { key: 'background_color', label: 'Sfondo tag', type: 'color' },
    { key: 'hover_background', label: 'Sfondo hover', type: 'color' },
    { type: 'separator', label: 'Stile tag' },
    { key: 'border_radius', label: 'Arrotondamento (px)', type: 'border-radius' },
    { key: 'border_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius' },
    { key: 'padding', label: 'Padding (px)', type: 'spacing', max: 32 },

    ...textEffectsFields([
      { value: 'tag', label: 'Etichetta tag' },
    ]),
    ...borderFields(),
  ],
};
