import { textEffectsFields, textEffectsDefaults, filterFields, filterDefaults, borderFields, borderDefault, borderHoverDefault, borderEffectDefaults, withHover } from './_shared.js';
import { t } from '@/i18n';

/**
 * Tile Team — split CONTENUTO/STILE.
 *   fields[]      → photo + hover_image/video, nome, ruolo, bio, link (text+url)
 *   styleFields[] → preset, bg, typo, text-effects, foto aspetto, contenitore info, tipografia, tile aspect, filtri
 */
export default {
  type: 'team',
  name: t('Membro del team'),
  icon: 'dashicons-businessperson',
  category: 'marketing',
  defaults: {
    bg: { type: 'none' },
    typography_preset: '',
    preset: 'custom',
    ...filterDefaults,
    photo: '',
    hover_image: '',
    hover_video: '',
    name: 'Jane Smith',
    role: 'Lead Designer',
    bio: 'Appassionata di creare esperienze utente eccellenti.',
    link_text: 'Profilo',
    link_url: '',
    photo_size: '120',
    photo_shape: 'circle',
    photo_radius: '12',
    photo_border_width: '3',
    photo_border_color: '',
    photo_shadow: 'md',
    photo_gap: '12',
    info_bg_color: '',
    info_text_color: '',
    info_padding: { top: 24, right: 24, bottom: 24, left: 24 },
    info_width: '100',
    info_margin: '0',
    info_radius: '16',
    info_border_width: '0',
    info_border_color: '',
    info_align: 'center',
    name_size: '20',
    name_weight: '600',
    role_size: '14',
    role_color: '',
    bio_size: '14',
    bg_color: '',
    tile_padding: { top: 16, right: 16, bottom: 16, left: 16 },
    border_radius: '16',
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
    ...textEffectsDefaults,
    text_effect_target: 'name',
  },

  fields: [
    { key: 'photo', label: t('Foto / Video'), type: 'media' },
    { key: 'hover_image', label: t('Immagine hover'), type: 'image' },
    { key: 'hover_video', label: t('Video hover'), type: 'media' },
    { key: 'name', label: t('Nome'), type: 'text' },
    { key: 'role', label: t('Ruolo'), type: 'text' },
    { key: 'bio', label: t('Biografia'), type: 'textarea' },
    { key: 'link_text', label: t('Testo link'), type: 'text' },
    { key: 'link_url', label: t('URL link'), type: 'link' },
  ],

  styleFields: [
    { type: 'separator', label: t('Preset stilistico') },
    { key: 'preset', label: t('Stile'), type: 'select', options: [
      { value: 'corporate-card',   label: t('Corporate Card') },
      { value: 'magazine-row',     label: t('Magazine Row') },
      { value: 'minimal-clean',    label: t('Minimal Clean') },
      { value: 'editorial-bold',   label: t('Editorial Bold') },
      { value: 'photographer',     label: t('Photographer (B&N)') },
      { value: 'glass-portrait',   label: t('Glass Portrait') },
      { value: 'neon-frame',       label: t('Neon Frame') },
      { value: 'brutalist-stamp',  label: t('Brutalist Stamp') },
      { value: 'polaroid-photo',   label: t('Polaroid') },
      { value: 'sticker-portrait', label: t('Sticker Portrait') },
      { value: 'retro-yearbook',   label: t('Retro Yearbook') },
      { value: 'tilt-3d',          label: t('3D Tilt') },
      { value: 'custom',           label: t('Personalizzato') },
    ]},
    { key: 'typography_preset', label: t('Stile tipografico'), type: 'select', optionsSource: 'globalTypography' },

    ...textEffectsFields([ { value: 'name', label: t('Solo Nome') } ]),

    { type: 'separator', label: t('Foto') },
    { key: 'photo_size', label: t('Dimensione foto (px)'), type: 'range', min: 60, max: 250, step: 5 },
    { key: 'photo_shape', label: t('Maschera foto'), type: 'select', options: [
      { value: 'circle', label: t('Tonda') },
      { value: 'square', label: t('Quadrata') },
      { value: 'rounded', label: t('Arrotondata') },
      { value: 'hexagon', label: t('Esagonale') },
    ]},
    withHover({ key: 'photo_radius', label: t('Raggio bordo foto (px)'), type: 'border-radius',
      condition: { field: 'photo_shape', value: 'rounded' } }),
    { key: 'photo_border_width', label: t('Bordo foto (px)'), type: 'range', min: 0, max: 8, step: 1 },
    { key: 'photo_border_color', label: t('Colore bordo foto'), type: 'color',
      condition: { field: 'photo_border_width', operator: '>', value: '0' } },
    { key: 'photo_shadow', label: t('Ombra foto'), type: 'select', options: [
      { value: 'none', label: t('Nessuna') },
      { value: 'sm', label: t('Leggera') },
      { value: 'md', label: t('Media') },
      { value: 'lg', label: t('Grande') },
      { value: 'custom', label: t('Personalizzata') },
    ]},
    { key: 'photo_shadow_h', label: t('Offset H (px)'), type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'photo_shadow', op: 'eq', value: 'custom' } },
    { key: 'photo_shadow_v', label: t('Offset V (px)'), type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'photo_shadow', op: 'eq', value: 'custom' } },
    { key: 'photo_shadow_blur', label: t('Sfocatura (px)'), type: 'range', min: 0, max: 100, step: 1,
      condition: { field: 'photo_shadow', op: 'eq', value: 'custom' } },
    { key: 'photo_shadow_spread', label: t('Espansione (px)'), type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'photo_shadow', op: 'eq', value: 'custom' } },
    { key: 'photo_shadow_color', label: t('Colore ombra'), type: 'color',
      condition: { field: 'photo_shadow', op: 'eq', value: 'custom' } },
    { key: 'photo_shadow_inset', label: t('Ombra interna'), type: 'toggle',
      condition: { field: 'photo_shadow', op: 'eq', value: 'custom' } },
    { key: 'photo_gap', label: t('Distanza foto-contenitore (px)'), type: 'range', min: -40, max: 40, step: 4 },

    { type: 'separator', label: t('Contenitore info') },
    { key: 'info_bg_color', label: t('Sfondo contenitore'), type: 'color' },
    { key: 'info_width', label: t('Larghezza contenitore (%)'), type: 'range', min: 50, max: 100, step: 5 },
    { key: 'info_margin', label: t('Margine dal tile (px)'), type: 'spacing', max: 40 },
    { key: 'info_padding', label: t('Padding contenitore (px)'), type: 'spacing', max: 48 },
    withHover({ key: 'info_radius', label: t('Arrotondamento (px)'), type: 'border-radius' }),
    { key: 'info_border_width', label: t('Bordo contenitore (px)'), type: 'range', min: 0, max: 5, step: 1 },
    { key: 'info_border_color', label: t('Colore bordo contenitore'), type: 'color',
      condition: { field: 'info_border_width', operator: '>', value: '0' } },
    { key: 'info_align', label: t('Allineamento testo'), type: 'select', options: [
      { value: 'left', label: t('Sinistra') },
      { value: 'center', label: t('Centro') },
      { value: 'right', label: t('Destra') },
    ]},

    { type: 'separator', label: t('Tipografia') },
    { type: 'typography', label: t('Nome'),
      presetKey: 'typography_preset',
      responsiveKeys: ['size'],
      keys: {
        size:   'name_size',
        weight: 'name_weight',
        color:  'info_text_color',
      },
      sizeMin: 14, sizeMax: 36, sizeStep: 1,
    },
    { type: 'typography', label: t('Ruolo'),
      presetKey: 'typography_preset',
      responsiveKeys: ['size'],
      keys: {
        size:  'role_size',
        color: 'role_color',
      },
      sizeMin: 10, sizeMax: 24, sizeStep: 1,
    },
    { type: 'typography', label: t('Biografia'),
      presetKey: 'typography_preset',
      responsiveKeys: ['size'],
      keys: {
        size:  'bio_size',
        color: 'info_text_color',
      },
      sizeMin: 10, sizeMax: 20, sizeStep: 1,
    },

    { type: 'separator', label: t('Aspetto tile') },
    { key: 'bg_color', label: t('Colore sfondo tile'), type: 'color' },
    { key: 'tile_padding', label: t('Padding tile (px)'), type: 'spacing', max: 40 },
    withHover({ key: 'border_radius', label: t('Arrotondamento tile (px)'), type: 'border-radius' }),

    ...borderFields(),
    ...filterFields,
  ],
};
