import { textEffectsFields, textEffectsDefaults, filterFields, filterDefaults, borderFields, borderDefault, borderHoverDefault, borderEffectDefaults } from './_shared.js';
export default {
  type: 'team',
  name: 'Membro del team',
  icon: 'dashicons-businessperson',
  category: 'marketing',
  defaults: {
    ...filterDefaults,
    // Contenuto
    photo: '',
    hover_image: '',
    hover_video: '',
    name: 'Jane Smith',
    role: 'Lead Designer',
    bio: 'Appassionata di creare esperienze utente eccellenti.',
    link_text: 'Profilo',
    link_url: '',

    // Foto
    photo_size: '120',
    photo_shape: 'circle',
    photo_radius: '12',
    photo_border_width: '3',
    photo_border_color: '',
    photo_shadow: 'md',
    photo_gap: '12',

    // Contenitore info
    info_bg_color: '',
    info_text_color: '',
    tile_padding: { top: 24, right: 24, bottom: 24, left: 24 },
    info_width: '100',
    info_margin: '0',
    info_radius: '16',
    info_border_width: '0',
    info_border_color: '',
    info_align: 'center',

    // Tipografia
    name_size: '20',
    name_weight: '600',
    role_size: '14',
    role_color: '',
    bio_size: '14',

    // Tile
    bg_color: '',
    tile_padding: '16',
    border_radius: '16',
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
    ...textEffectsDefaults,
  },
  fields: [
    // ── Contenuto ──
    { key: 'photo', label: 'Foto / Video', type: 'media' },
    { key: 'hover_image', label: 'Immagine hover', type: 'image' },
    { key: 'hover_video', label: 'Video hover', type: 'media' },
    { key: 'name', label: 'Nome', type: 'text' },
    { key: 'role', label: 'Ruolo', type: 'text' },
    { key: 'bio', label: 'Biografia', type: 'textarea' },
    { key: 'link_text', label: 'Testo link', type: 'text' },
    { key: 'link_url', label: 'URL link', type: 'text' },

    // ── Foto ──
    { type: 'separator', label: 'Foto' },
    { key: 'photo_size', label: 'Dimensione foto (px)', type: 'range', min: 60, max: 250, step: 5 },
    { key: 'photo_shape', label: 'Maschera foto', type: 'select', options: [
      { value: 'circle', label: 'Tonda' },
      { value: 'square', label: 'Quadrata' },
      { value: 'rounded', label: 'Arrotondata' },
      { value: 'hexagon', label: 'Esagonale' },
    ]},
    { key: 'photo_radius', label: 'Raggio bordo foto (px)', type: 'border-radius',
      condition: { field: 'photo_shape', value: 'rounded' } },
    { key: 'photo_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius' },
    { key: 'photo_border_width', label: 'Bordo foto (px)', type: 'range', min: 0, max: 8, step: 1 },
    { key: 'photo_border_color', label: 'Colore bordo foto', type: 'color',
      condition: { field: 'photo_border_width', operator: '>', value: '0' } },
    { key: 'photo_shadow', label: 'Ombra foto', type: 'select', options: [
      { value: 'none', label: 'Nessuna' },
      { value: 'sm', label: 'Leggera' },
      { value: 'md', label: 'Media' },
      { value: 'lg', label: 'Grande' },
      { value: 'custom', label: 'Personalizzata' },
    ]},
    { key: 'photo_shadow_h', label: 'Offset H (px)', type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'photo_shadow', op: 'eq', value: 'custom' } },
    { key: 'photo_shadow_v', label: 'Offset V (px)', type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'photo_shadow', op: 'eq', value: 'custom' } },
    { key: 'photo_shadow_blur', label: 'Sfocatura (px)', type: 'range', min: 0, max: 100, step: 1,
      condition: { field: 'photo_shadow', op: 'eq', value: 'custom' } },
    { key: 'photo_shadow_spread', label: 'Espansione (px)', type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'photo_shadow', op: 'eq', value: 'custom' } },
    { key: 'photo_shadow_color', label: 'Colore ombra', type: 'color',
      condition: { field: 'photo_shadow', op: 'eq', value: 'custom' } },
    { key: 'photo_shadow_inset', label: 'Ombra interna', type: 'toggle',
      condition: { field: 'photo_shadow', op: 'eq', value: 'custom' } },
    { key: 'photo_gap', label: 'Distanza foto-contenitore (px)', type: 'range', min: -40, max: 40, step: 4 },

    // ── Contenitore info ──
    { type: 'separator', label: 'Contenitore info' },
    { key: 'info_bg_color', label: 'Sfondo contenitore', type: 'color' },
    { key: 'info_text_color', label: 'Colore testo', type: 'color' },
    { key: 'info_width', label: 'Larghezza contenitore (%)', type: 'range', min: 50, max: 100, step: 5 },
    { key: 'info_margin', label: 'Margine dal tile (px)', type: 'spacing', max: 40 },
    { key: 'tile_padding', label: 'Padding (px)', type: 'spacing', max: 48 },
    { key: 'info_radius', label: 'Arrotondamento (px)', type: 'border-radius' },
    { key: 'info_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius' },
    { key: 'info_border_width', label: 'Bordo contenitore (px)', type: 'range', min: 0, max: 5, step: 1 },
    { key: 'info_border_color', label: 'Colore bordo contenitore', type: 'color',
      condition: { field: 'info_border_width', operator: '>', value: '0' } },
    { key: 'info_align', label: 'Allineamento testo', type: 'select', options: [
      { value: 'left', label: 'Sinistra' },
      { value: 'center', label: 'Centro' },
      { value: 'right', label: 'Destra' },
    ]},

    // ── Tipografia ──
    { type: 'separator', label: 'Tipografia' },
    { key: 'name_size', label: 'Dim. nome (px)', type: 'range', min: 14, max: 36, step: 1 },
    { key: 'name_weight', label: 'Peso nome', type: 'select', options: [
      { value: '400', label: 'Normale' },
      { value: '500', label: 'Medio' },
      { value: '600', label: 'Semi-grassetto' },
      { value: '700', label: 'Grassetto' },
    ]},
    { key: 'role_size', label: 'Dim. ruolo (px)', type: 'range', min: 10, max: 24, step: 1 },
    { key: 'role_color', label: 'Colore ruolo', type: 'color' },
    { key: 'bio_size', label: 'Dim. biografia (px)', type: 'range', min: 10, max: 20, step: 1 },

    // ── Tile ──
    { type: 'separator', label: 'Aspetto tile' },
    { key: 'bg_color', label: 'Colore sfondo tile', type: 'color' },
    { key: 'tile_padding', label: 'Padding tile (px)', type: 'spacing', max: 40 },
    { key: 'border_radius', label: 'Arrotondamento tile (px)', type: 'border-radius' },
    { key: 'border_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius' },
    ...borderFields(),
    ...filterFields,
    ...textEffectsFields([ { value: 'name', label: 'Solo Nome' } ]),
  ],
};
