import { textEffectsFields, textEffectsDefaults, filterFields, filterDefaults, borderFields, borderDefault, borderHoverDefault, borderEffectDefaults, withHover, focalField } from './_shared.js';
import { t } from '@/i18n';

/**
 * Tile Testimonial — split CONTENUTO/STILE.
 *   fields[]      → quote, author, role, avatar, rating, items multiple, layout (single/carousel/grid) + autoplay/dots/arrows
 *   styleFields[] → preset, bg, typo, text-effects, colori, linea decorativa, posizione testimone, avatar aspetto/ombra/bordo/filtro, radius card, bordo, filtri
 */
export default {
  type: 'testimonial',
  name: t('Testimonianza'),
  icon: 'dashicons-format-quote',
  category: 'marketing',
  defaults: {
    bg: { type: 'none' },
    typography_preset: '',
    preset: 'custom',
    ...filterDefaults,
    quote: t('Un prodotto fantastico!'),
    logo: '',
    author_name: t('Mario Rossi'),
    author_role: t('CEO'),
    avatar: '',
    rating: '5',
    bg_color: '',
    text_color: '',
    star_color: '',
    author_color: '',
    quote_accent_color: '',
    quote_font: 'inherit',
    quote_size: 0,
    author_uppercase: false,
    quote_uppercase: false,
    layout: 'single',
    autoplay: false,
    autoplay_interval: 5,
    slides_to_show: 1,
    show_dots: true,
    show_arrows: true,
    grid_columns: 2,
    items: [],
    show_line: true,
    line_color: '',
    author_position: 'bottom-left',
    avatar_size: '48',
    avatar_shape: 'circle',
    // L'avatar è sempre ritagliato in quadrato (width = height = avatar_size) con
    // `object-fit: cover` cablato nel CSS: l'unico pezzo di cornice che mancava era
    // DOVE cade quel ritaglio. 'center center' = esattamente la resa di oggi.
    avatar_object_position: 'center center',
    avatar_radius: '6',
    avatar_shadow: 'none',
    avatar_border_width: '0',
    avatar_border_color: '',
    avatar_filter: 'none',
    border_radius: '12',
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    card_border: { ...borderDefault },
    card_border_hover: { ...borderHoverDefault },
    card_border_hover_duration: 300,
    ...borderEffectDefaults,
    ...textEffectsDefaults,
    text_effect_target: 'quote',
  },

  fields: [
    { key: 'quote', label: t('Citazione'), type: 'textarea' },
    { key: 'logo', label: t('Logo cliente (in alto nella card)'), type: 'image' },
    { key: 'author_name', label: t('Nome autore'), type: 'text' },
    { key: 'author_role', label: t('Ruolo autore'), type: 'text' },
    { key: 'avatar', label: t('Avatar'), type: 'image' },
    { key: 'rating', label: t('Valutazione'), type: 'select', options: [
      { value: '0', label: t('Nessuna') },
      { value: '1', label: t('1 stella') },
      { value: '2', label: t('2 stelle') },
      { value: '3', label: t('3 stelle') },
      { value: '4', label: t('4 stelle') },
      { value: '5', label: t('5 stelle') },
    ]},

    { type: 'separator', label: t('Layout') },
    { key: 'autoplay', label: t('Autoplay'), type: 'toggle',
      condition: { field: 'layout', value: 'carousel' } },
    { key: 'autoplay_interval', label: t('Intervallo autoplay'), type: 'number', min: 1, max: 30,
      condition: { field: 'layout', value: 'carousel' } },
    { key: 'slides_to_show', label: t('Slide visibili'), type: 'range', min: 1, max: 4, step: 1,
      condition: { field: 'layout', value: 'carousel' } },
    { key: 'show_dots', label: t('Mostra punti navigazione'), type: 'toggle',
      condition: { field: 'layout', value: 'carousel' } },
    { key: 'show_arrows', label: t('Mostra frecce'), type: 'toggle',
      condition: { field: 'layout', value: 'carousel' } },
    { key: 'items', label: t('Testimonianze multiple'), type: 'content-items',
      condition: { field: 'layout', operator: '!=', value: 'single' },
      itemFields: [
        { key: 'quote', label: t('Citazione'), type: 'textarea' },
        { key: 'logo', label: t('Logo cliente (in alto nella card)'), type: 'image' },
        { key: 'author_name', label: t('Nome autore'), type: 'text' },
        { key: 'author_role', label: t('Ruolo'), type: 'text' },
        { key: 'avatar', label: t('Avatar'), type: 'image' },
        { key: 'rating', label: t('Valutazione'), type: 'select', options: [
          { value: '0', label: t('Nessuna') },
          { value: '1', label: t('1 stella') },
          { value: '2', label: t('2 stelle') },
          { value: '3', label: t('3 stelle') },
          { value: '4', label: t('4 stelle') },
          { value: '5', label: t('5 stelle') },
        ]},
      ],
      newItemDefaults: { quote: t('Un ottimo servizio!'), logo: '', author_name: t('Nome'), author_role: '', avatar: '', rating: '5' },
      itemLabel: t('Testimonianza'),
    },

    { type: 'separator', label: t('Linea decorativa') },
    { key: 'show_line', label: t('Mostra linea verticale'), type: 'toggle' },
  ],

  styleFields: [
    { type: 'separator', label: t('Preset stilistico') },
    { key: 'preset', label: t('Stile'), type: 'select', options: [
      { value: 'modern-card',      label: t('Modern Card') },
      { value: 'magazine-pull',    label: t('Magazine Pull-quote') },
      { value: 'editorial-serif',  label: t('Editorial Serif') },
      { value: 'minimal-line',     label: t('Minimal Line') },
      { value: 'agency-bold',      label: t('Agency Bold') },
      { value: 'glass-frosted',    label: t('Glass Frosted') },
      { value: 'neon-quote',       label: t('Neon Quote') },
      { value: 'brutalist-stamp',  label: t('Brutalist Stamp') },
      { value: 'gradient-soft',    label: t('Gradient Soft') },
      { value: 'sticky-note',      label: t('Sticky Note') },
      { value: 'retro-typewriter', label: t('Retro Typewriter') },
      { value: 'tilt-card',        label: t('Tilt Card') },
      { value: 'custom',           label: t('Personalizzato') },
    ]},
    ...textEffectsFields([ { value: 'quote', label: t('Solo Citazione') } ]),

    { type: 'separator', label: t('Tipografia') },
    { key: 'typography_preset', label: t('Stile tipografico'), type: 'select', optionsSource: 'globalTypography' },
    { type: 'typography', label: t('Citazione'),
      responsiveKeys: [],
      keys: {
        size:      'quote_size',
        color:     'text_color',
        family:    'quote_font',
        uppercase: 'quote_uppercase',
      },
      sizeMin: 0, sizeMax: 56,
    },

    { type: 'separator', label: t('Autore') },
    { type: 'typography', label: t('Autore'), responsiveKeys: [],
      keys: { color: 'author_color', uppercase: 'author_uppercase' } },

    { type: 'separator', label: t('Colori') },
    { key: 'bg_color', label: t('Colore sfondo'), type: 'color' },
    { key: 'star_color', label: t('Colore stelle (vuoto = ambra)'), type: 'color' },
    { key: 'quote_accent_color', label: t('Colore accento citazione (<em>)'), type: 'color' },
    { key: 'line_color', label: t('Colore linea decorativa'), type: 'color',
      condition: { field: 'show_line', value: true } },

    { type: 'separator', label: t('Testimone') },
    { key: 'author_position', label: t('Posizione testimone'), type: 'select', options: [
      { value: 'bottom-left', label: t('Sotto a sinistra') },
      { value: 'bottom-center', label: t('Sotto al centro') },
      { value: 'bottom-right', label: t('Sotto a destra') },
      { value: 'left', label: t('Sinistra') },
      { value: 'right', label: t('Destra') },
    ]},
    { key: 'avatar_size', label: t('Dimensione avatar'), type: 'range', min: 30, max: 120, step: 5 },
    { key: 'avatar_shape', label: t('Forma avatar'), type: 'select', options: [
      { value: 'circle', label: t('Tonda') },
      { value: 'square', label: t('Quadrata') },
    ]},
    withHover({ key: 'avatar_radius', label: t('Raggio avatar'), type: 'border-radius',
      condition: { field: 'avatar_shape', value: 'square' } }),
    // Ritaglio sempre quadrato e sempre «riempi»: ratio e fit sono LETTERALI nel
    // contesto dell'anteprima (non esistono chiavi da leggere), si sceglie solo il
    // punto. Vale per tutte le testimonianze della lista, non una per voce:
    // altrimenti in griglia i volti si sfalserebbero riga per riga.
    focalField('avatar', { ratio: '1/1', fit: '(cover)', label: t('Punto focale avatar') }),
    { key: 'avatar_shadow', label: t('Ombra avatar'), type: 'select', options: [
      { value: 'none', label: t('Nessuna') },
      { value: 'sm', label: t('Piccola') },
      { value: 'md', label: t('Media') },
      { value: 'lg', label: t('Grande') },
      { value: 'custom', label: t('Personalizzata') },
    ]},
    { key: 'avatar_shadow_custom', label: t('Ombra personalizzata'), type: 'box-shadow',
      legacyKeys: { h: 'avatar_shadow_h', v: 'avatar_shadow_v', blur: 'avatar_shadow_blur', spread: 'avatar_shadow_spread', color: 'avatar_shadow_color', inset: 'avatar_shadow_inset' },
      condition: { field: 'avatar_shadow', op: 'eq', value: 'custom' } },
    { key: 'avatar_border', label: t('Bordo avatar'), type: 'border',
      legacyKeys: { width: 'avatar_border_width', color: 'avatar_border_color' } },
    { key: 'avatar_filter', label: t('Filtro avatar'), type: 'select', options: [
      { value: 'none', label: t('Nessuno') },
      { value: 'grayscale', label: t('Scala di grigi') },
      { value: 'sepia', label: t('Seppia') },
      { value: 'brightness', label: t('Luminoso') },
      { value: 'contrast', label: t('Alto contrasto') },
    ]},

    { type: 'separator', label: t('Aspetto card') },
    withHover({ key: 'border_radius', label: t('Raggio tile'), type: 'border-radius' }),
    withHover(
      { key: 'card_border', label: t('Bordo card'), type: 'border' },
      { hoverKey: 'card_border_hover', hoverDurationKey: 'card_border_hover_duration' }
    ),

    ...borderFields(),
    ...filterFields,
    { type: 'separator', label: t('Disposizione') },
    { key: 'layout', label: t('Layout'), type: 'select', options: [
      { value: 'single', label: t('Singola') },
      { value: 'editorial', label: t('Editoriale (centrato: stelle · citazione serif · autore)') },
      { value: 'carousel', label: t('Carousel') },
      { value: 'grid', label: t('Griglia') },
    ]},
    { key: 'grid_columns', label: t('Colonne griglia'), type: 'range', min: 1, max: 4, step: 1,
      condition: { field: 'layout', value: 'grid' } },
  ],
};
