import { textEffectsFields, textEffectsDefaults } from './_shared';
export default {
  type: 'testimonial',
  name: 'Testimonianza',
  icon: 'dashicons-format-quote',
  category: 'marketing',
  defaults: {
    quote: 'Un prodotto fantastico!',
    author_name: 'Mario Rossi',
    author_role: 'CEO',
    avatar: '',
    rating: '5',
    bg_color: '',
    text_color: '',

    // Layout
    layout: 'single',
    autoplay: false,
    autoplay_interval: 5,
    slides_to_show: 1,
    show_dots: true,
    show_arrows: true,
    grid_columns: 2,
    items: [],

    // Linea decorativa
    show_line: true,
    line_color: '',

    // Posizione testimone
    author_position: 'bottom-left',

    // Avatar
    avatar_size: '48',
    avatar_shape: 'circle',
    avatar_radius: '6',
    avatar_shadow: 'none',
    avatar_border_width: '0',
    avatar_border_color: '',
    avatar_filter: 'none',

    // Tile
    border_radius: '12',
    border_width: '0',
    border_color: '',
    ...textEffectsDefaults,
  },
  fields: [
    { key: 'quote', label: 'Citazione', type: 'textarea' },
    { key: 'author_name', label: 'Nome autore', type: 'text' },
    { key: 'author_role', label: 'Ruolo autore', type: 'text' },
    { key: 'avatar', label: 'Avatar', type: 'image' },
    { key: 'rating', label: 'Valutazione', type: 'select', options: [
      { value: '0', label: 'Nessuna' },
      { value: '1', label: '1 stella' },
      { value: '2', label: '2 stelle' },
      { value: '3', label: '3 stelle' },
      { value: '4', label: '4 stelle' },
      { value: '5', label: '5 stelle' },
    ]},

    { type: 'separator', label: 'Layout' },
    { key: 'layout', label: 'Layout', type: 'select', options: [
      { value: 'single', label: 'Singola' },
      { value: 'carousel', label: 'Carousel' },
      { value: 'grid', label: 'Griglia' },
    ]},
    { key: 'autoplay', label: 'Autoplay', type: 'toggle',
      condition: { field: 'layout', value: 'carousel' } },
    { key: 'autoplay_interval', label: 'Intervallo autoplay (s)', type: 'number', min: 1, max: 30,
      condition: { field: 'layout', value: 'carousel' } },
    { key: 'slides_to_show', label: 'Slide visibili', type: 'range', min: 1, max: 4, step: 1,
      condition: { field: 'layout', value: 'carousel' } },
    { key: 'show_dots', label: 'Mostra punti navigazione', type: 'toggle',
      condition: { field: 'layout', value: 'carousel' } },
    { key: 'show_arrows', label: 'Mostra frecce', type: 'toggle',
      condition: { field: 'layout', value: 'carousel' } },
    { key: 'grid_columns', label: 'Colonne griglia', type: 'range', min: 1, max: 4, step: 1,
      condition: { field: 'layout', value: 'grid' } },
    { key: 'items', label: 'Testimonianze', type: 'content-items',
      condition: { field: 'layout', operator: '!=', value: 'single' },
      itemFields: [
        { key: 'quote', label: 'Citazione', type: 'textarea' },
        { key: 'author_name', label: 'Nome autore', type: 'text' },
        { key: 'author_role', label: 'Ruolo', type: 'text' },
        { key: 'avatar', label: 'Avatar', type: 'image' },
        { key: 'rating', label: 'Valutazione', type: 'select', options: [
          { value: '0', label: 'Nessuna' },
          { value: '1', label: '1 stella' },
          { value: '2', label: '2 stelle' },
          { value: '3', label: '3 stelle' },
          { value: '4', label: '4 stelle' },
          { value: '5', label: '5 stelle' },
        ]},
      ],
      newItemDefaults: { quote: 'Un ottimo servizio!', author_name: 'Nome', author_role: '', avatar: '', rating: '5' },
      itemLabel: 'Testimonianza',
    },

    { type: 'separator', label: 'Colori' },
    { key: 'bg_color', label: 'Colore sfondo', type: 'color' },
    { key: 'text_color', label: 'Colore testo', type: 'color' },

    { type: 'separator', label: 'Linea decorativa' },
    { key: 'show_line', label: 'Mostra linea verticale', type: 'toggle' },
    { key: 'line_color', label: 'Colore linea', type: 'color',
      condition: { field: 'show_line', value: true } },

    { type: 'separator', label: 'Testimone' },
    { key: 'author_position', label: 'Posizione testimone', type: 'select', options: [
      { value: 'bottom-left', label: 'Sotto a sinistra' },
      { value: 'bottom-center', label: 'Sotto al centro' },
      { value: 'bottom-right', label: 'Sotto a destra' },
      { value: 'left', label: 'Sinistra' },
      { value: 'right', label: 'Destra' },
    ]},
    { key: 'avatar_size', label: 'Dimensione avatar (px)', type: 'range', min: 30, max: 120, step: 5 },
    { key: 'avatar_shape', label: 'Forma avatar', type: 'select', options: [
      { value: 'circle', label: 'Tonda' },
      { value: 'square', label: 'Quadrata' },
    ]},
    { key: 'avatar_radius', label: 'Arrotondamento avatar (px)', type: 'border-radius',
      condition: { field: 'avatar_shape', value: 'square' } },
    { key: 'avatar_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius' },
    { key: 'avatar_shadow', label: 'Ombra avatar', type: 'select', options: [
      { value: 'none', label: 'Nessuna' },
      { value: 'sm', label: 'Piccola' },
      { value: 'md', label: 'Media' },
      { value: 'lg', label: 'Grande' },
      { value: 'custom', label: 'Personalizzata' },
    ]},
    { key: 'avatar_shadow_h', label: 'Offset H (px)', type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'avatar_shadow', op: 'eq', value: 'custom' } },
    { key: 'avatar_shadow_v', label: 'Offset V (px)', type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'avatar_shadow', op: 'eq', value: 'custom' } },
    { key: 'avatar_shadow_blur', label: 'Sfocatura (px)', type: 'range', min: 0, max: 100, step: 1,
      condition: { field: 'avatar_shadow', op: 'eq', value: 'custom' } },
    { key: 'avatar_shadow_spread', label: 'Espansione (px)', type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'avatar_shadow', op: 'eq', value: 'custom' } },
    { key: 'avatar_shadow_color', label: 'Colore ombra', type: 'color',
      condition: { field: 'avatar_shadow', op: 'eq', value: 'custom' } },
    { key: 'avatar_shadow_inset', label: 'Ombra interna', type: 'toggle',
      condition: { field: 'avatar_shadow', op: 'eq', value: 'custom' } },
    { key: 'avatar_border_width', label: 'Bordo avatar (px)', type: 'range', min: 0, max: 5, step: 1 },
    { key: 'avatar_border_color', label: 'Colore bordo avatar', type: 'color',
      condition: { field: 'avatar_border_width', operator: '>', value: '0' } },
    { key: 'avatar_filter', label: 'Filtro avatar', type: 'select', options: [
      { value: 'none', label: 'Nessuno' },
      { value: 'grayscale', label: 'Scala di grigi' },
      { value: 'sepia', label: 'Seppia' },
      { value: 'brightness', label: 'Luminoso' },
      { value: 'contrast', label: 'Alto contrasto' },
    ]},

    { type: 'separator', label: 'Aspetto' },
    { key: 'border_radius', label: 'Arrotondamento tile (px)', type: 'border-radius' },
    { key: 'border_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius' },
    { key: 'border_width', label: 'Spessore bordo (px)', type: 'range', min: 0, max: 5, step: 1 },
    { key: 'border_color', label: 'Colore bordo', type: 'color',
      condition: { field: 'border_width', operator: '>', value: '0' } },
    ...textEffectsFields([ { value: 'quote', label: 'Solo Citazione' } ]),
  ],
};
