import { textEffectsFields, textEffectsDefaults, borderFields, borderDefault, borderHoverDefault, borderEffectDefaults } from './_shared';
import { shadowField } from './_shared.js';

export default {
  type: 'toc',
  name: 'Indice contenuti',
  icon: 'dashicons-list-view',
  category: 'navigation',
  defaults: {
    title: 'Sommario',
    max_depth: '3',
    list_style: 'numbered',
    text_color: '',
    link_color: '',
    title_color: '',
    font_size: '15',
    indent: '20',
    sticky: false,
    highlight_active: true,
    smooth_scroll: true,
    shadow: 'none',
    ...textEffectsDefaults,
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
  },
  fields: [
    { key: 'title', label: 'Titolo', type: 'text' },
    { key: 'max_depth', label: 'Profondità max', type: 'select', options: [
      { value: '1', label: 'Solo H1' },
      { value: '2', label: 'Fino a H2' },
      { value: '3', label: 'Fino a H3' },
      { value: '4', label: 'Fino a H4' },
      { value: '5', label: 'Fino a H5' },
      { value: '6', label: 'Fino a H6' },
    ]},
    { key: 'list_style', label: 'Stile lista', type: 'select', options: [
      { value: 'numbered', label: 'Numerata' },
      { value: 'bullets', label: 'Pallini' },
      { value: 'none', label: 'Senza' },
    ]},
    { type: 'separator', label: 'Stile' },
    { key: 'text_color', label: 'Colore testo', type: 'color' },
    { key: 'link_color', label: 'Colore link', type: 'color' },
    { key: 'title_color', label: 'Colore titolo', type: 'color' },
    { key: 'font_size', label: 'Dimensione font (px)', type: 'range', min: 12, max: 22, step: 1 },
    { key: 'indent', label: 'Indentazione sotto-livelli (px)', type: 'range', min: 0, max: 40, step: 4 },
    { type: 'separator', label: 'Comportamento' },
    { key: 'sticky', label: 'Sticky (fisso nello scroll)', type: 'toggle' },
    { key: 'highlight_active', label: 'Evidenzia sezione attiva', type: 'toggle' },
    { key: 'smooth_scroll', label: 'Scroll fluido', type: 'toggle' },
    ...shadowField,
    ...textEffectsFields([ { value: 'title', label: 'Solo Titolo' } ]),
    ...borderFields(),
  ],
};
