import { textEffectsFields, textEffectsDefaults, shadowField, borderFields, borderDefault, borderHoverDefault, borderEffectDefaults } from './_shared.js';

export default {
  type: 'video',
  name: 'Video',
  icon: 'dashicons-video-alt3',
  category: 'essential',
  defaults: {
    source_type: 'embed',
    video_url: '',
    file_url: '',
    display_mode: '16:9',
    cover_height: '500',
    border_radius: 0,
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
    facade: true,
    autoplay: false,
    muted: false,
    loop: false,
    controls: true,
    start_time: '',
    end_time: '',
    poster_image: '',
    privacy_mode: false,
    show_play_icon: true,
    play_icon_size: '80',
    play_icon_color: '',
    overlay_text: '',
    overlay_color: '#000000',
    overlay_opacity: '0',
    overlay_text_size: '32',
    overlay_text_color: '#ffffff',
    overlay_text_weight: '700',
    overlay_text_align: 'center',
    caption: '',
    shadow: 'none',
    ...textEffectsDefaults,
  },
  fields: [
    { key: 'source_type', label: 'Sorgente', type: 'select', options: [
      { value: 'embed', label: 'YouTube / Vimeo' },
      { value: 'file', label: 'File (MP4 / WebM)' },
    ]},
    { key: 'video_url', label: 'URL video', type: 'text' },
    { key: 'file_url', label: 'File video', type: 'media', accept: 'video' },
    { key: 'facade', label: 'Lazy Load (Facade)', type: 'toggle' },
    { key: 'display_mode', label: 'Visualizzazione', type: 'select', options: [
      { value: '16:9', label: '16:9' },
      { value: '4:3', label: '4:3' },
      { value: '1:1', label: '1:1' },
      { value: 'cover', label: 'Cover (altezza fissa)' },
    ]},
    { key: 'cover_height', label: 'Altezza (px)', type: 'range', min: 100, max: 1200, step: 10 },
    { key: 'border_radius', label: 'Raggio bordi (px)', type: 'border-radius' },
    { key: 'border_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius' },
    { type: 'separator', label: 'Riproduzione' },
    { key: 'autoplay', label: 'Riproduzione automatica', type: 'toggle' },
    { key: 'muted', label: 'Silenziato', type: 'toggle' },
    { key: 'loop', label: 'Ripeti', type: 'toggle' },
    { key: 'controls', label: 'Mostra controlli', type: 'toggle' },
    { key: 'start_time', label: 'Inizio (secondi)', type: 'text' },
    { key: 'end_time', label: 'Fine (secondi)', type: 'text' },
    { type: 'separator', label: 'Poster e overlay' },
    { key: 'poster_image', label: 'Immagine poster', type: 'image' },
    { key: 'show_play_icon', label: 'Mostra icona play', type: 'toggle' },
    { key: 'play_icon_size', label: 'Dimensione icona play (px)', type: 'range', min: 40, max: 160, step: 10 },
    { key: 'play_icon_color', label: 'Colore icona play', type: 'color' },
    { type: 'separator', label: 'Privacy' },
    { key: 'privacy_mode', label: 'Modo privacy (no-cookie)', type: 'toggle' },
    { type: 'separator', label: 'Overlay (cover)' },
    { key: 'overlay_text', label: 'Testo overlay', type: 'textarea' },
    { key: 'overlay_color', label: 'Colore overlay', type: 'color' },
    { key: 'overlay_opacity', label: 'Opacità overlay (%)', type: 'range', min: 0, max: 100, step: 5 },
    { key: 'overlay_text_size', label: 'Dimensione testo (px)', type: 'range', min: 12, max: 120, step: 1,
      condition: { field: 'overlay_text', op: 'notEmpty' } },
    { key: 'overlay_text_weight', label: 'Peso testo', type: 'select', options: [
      { value: '300', label: 'Light (300)' },
      { value: '400', label: 'Normale (400)' },
      { value: '500', label: 'Medio (500)' },
      { value: '600', label: 'Semi-bold (600)' },
      { value: '700', label: 'Bold (700)' },
      { value: '800', label: 'Extra bold (800)' },
      { value: '900', label: 'Black (900)' },
    ], condition: { field: 'overlay_text', op: 'notEmpty' } },
    { key: 'overlay_text_color', label: 'Colore testo', type: 'color',
      condition: { field: 'overlay_text', op: 'notEmpty' } },
    { key: 'overlay_text_align', label: 'Allineamento testo', type: 'select', options: [
      { value: 'left', label: 'Sinistra' },
      { value: 'center', label: 'Centro' },
      { value: 'right', label: 'Destra' },
    ], condition: { field: 'overlay_text', op: 'notEmpty' } },
    { type: 'separator', label: 'Didascalia' },
    { key: 'caption', label: 'Didascalia', type: 'text' },
    ...shadowField,
    ...borderFields(),
    ...textEffectsFields([
      { value: 'overlay_text', label: 'Solo Testo overlay' },
      { value: 'caption', label: 'Solo Didascalia' },
      { value: 'all', label: 'Entrambi' },
    ]),
  ],
};
