import { textEffectsFields, textEffectsDefaults } from './_shared';
export default {
  type: 'videoplaylist',
  name: 'Video Playlist',
  icon: 'dashicons-playlist-video',
  category: 'media',
  defaults: {
    videos: [
      { id: 'vp-1', url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', title: 'Primo video', duration: '3:32', thumbnail: '' },
      { id: 'vp-2', url: 'https://www.youtube.com/watch?v=9bZkp7q19f0', title: 'Secondo video', duration: '4:12', thumbnail: '' },
      { id: 'vp-3', url: 'https://www.youtube.com/watch?v=kJQP7kiw5Fk', title: 'Terzo video', duration: '5:01', thumbnail: '' },
    ],
    layout: 'sidebar-right',
    player_height: '360',
    sidebar_width: '280',
    sidebar_bg: '',
    text_color: '',
    active_color: '',
    show_duration: true,
    autoplay_next: false,
    ...textEffectsDefaults,
  },
  fields: [
    { key: 'videos', label: 'Video', type: 'content-items',
      itemFields: [
        { key: 'url', label: 'URL video', type: 'text', placeholder: 'YouTube, Vimeo o URL MP4' },
        { key: 'title', label: 'Titolo', type: 'text' },
        { key: 'duration', label: 'Durata', type: 'text', placeholder: 'es. 3:45' },
        { key: 'thumbnail', label: 'Anteprima', type: 'image' },
      ],
      newItemDefaults: { url: '', title: 'Nuovo video', duration: '', thumbnail: '' },
      itemLabel: 'Video',
    },
    { type: 'separator', label: 'Layout' },
    { key: 'layout', label: 'Disposizione', type: 'select', options: [
      { value: 'sidebar-right', label: 'Playlist a destra' },
      { value: 'sidebar-left', label: 'Playlist a sinistra' },
      { value: 'below', label: 'Playlist sotto' },
    ]},
    { key: 'player_height', label: 'Altezza player (px)', type: 'range', min: 200, max: 600, step: 10 },
    { key: 'sidebar_width', label: 'Larghezza sidebar (px)', type: 'range', min: 200, max: 400, step: 10 },
    { type: 'separator', label: 'Stile' },
    { key: 'sidebar_bg', label: 'Sfondo playlist', type: 'color' },
    { key: 'text_color', label: 'Colore testo', type: 'color' },
    { key: 'active_color', label: 'Colore attivo', type: 'color' },
    { key: 'show_duration', label: 'Mostra durata', type: 'toggle' },
    { key: 'autoplay_next', label: 'Autoplay successivo', type: 'toggle' },
    ...textEffectsFields([ { value: 'title', label: 'Solo Titolo' } ]),
  ],
};
