
import { shadowField, borderFields, borderDefault, borderHoverDefault, borderEffectDefaults } from './_shared.js';
import { t } from '@/i18n';

/**
 * Tile WooCommerce Prodotti — split CONTENUTO/STILE (regola universale Olobuild).
 *   fields[]      → query (posts_per_page, orderby/order, category/tag, on_sale, featured),
 *                   toggle visibilita (image/title/price/rating/cart/badge/compare/pagination),
 *                   layout grid/carousel + behaviour carousel (autoplay/loop/arrows/dots)
 *   styleFields[] → preset, sfondo, tipografia, columns/gap/image_ratio/card/hover,
 *                   carousel_speed (animation duration ms), colori, shadow, bordo
 *   AVANZATE      → meta tecnico (id/class/condizioni)
 */
export default {
  type: 'woo_products',
  name: t('Prodotti WC'),
  icon: 'dashicons-products',
  category: 'woocommerce',
  placeholder: t('Griglia prodotti WooCommerce'),
  defaults: {
    preset: 'custom',
    bg: { type: 'none' },
    typography_preset: '',
    posts_per_page: '12',
    columns: '4',
    orderby: 'date',
    order: 'DESC',
    category: '',
    tag: '',
    on_sale: false,
    featured: false,
    show_image: true,
    show_title: true,
    show_price: true,
    show_rating: false,
    show_add_to_cart: true,
    show_badge: true,
    image_ratio: '4-3',
    gap: '24',
    card_style: 'shadow',
    hover_effect: 'zoom',
    title_color: '',
    price_color: '',
    sale_color: '',
    button_color: '',
    button_bg: '',
    badge_bg: '',
    show_compare: false,
    pagination: false,
    layout: 'grid',
    carousel_autoplay: false,
    carousel_speed: '4000',
    carousel_loop: true,
    carousel_arrows: true,
    carousel_dots: true,
    columns_tablet: '2',
    columns_mobile: '1',
    shadow: 'none',
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
  },

  // ─── CONTENUTO ─────────────────────────────────────────────
  fields: [
    { type: 'separator', label: t('Query prodotti') },
    { key: 'posts_per_page', label: t('Prodotti per pagina'), type: 'range', min: 1, max: 48, step: 1 },
    { key: 'orderby', label: t('Ordina per'), type: 'select', options: [
      { value: 'date', label: t('Data') },
      { value: 'price', label: t('Prezzo') },
      { value: 'popularity', label: t('Popolarita') },
      { value: 'rating', label: t('Valutazione') },
      { value: 'title', label: t('Titolo') },
    ]},
    { key: 'order', label: t('Direzione'), type: 'select', options: [
      { value: 'DESC', label: t('Decrescente') },
      { value: 'ASC', label: t('Crescente') },
    ]},
    { key: 'category', label: t('Categoria (slug)'), type: 'text', placeholder: t('es. magliette') },
    { key: 'tag', label: t('Tag (slug)'), type: 'text', placeholder: t('es. novita') },
    { key: 'on_sale', label: t('Solo in saldo'), type: 'toggle' },
    { key: 'featured', label: t('Solo in evidenza'), type: 'toggle' },

    { type: 'separator', label: t('Elementi visibili') },
    { key: 'show_image', label: t('Mostra immagine'), type: 'toggle' },
    { key: 'show_title', label: t('Mostra titolo'), type: 'toggle' },
    { key: 'show_price', label: t('Mostra prezzo'), type: 'toggle' },
    { key: 'show_rating', label: t('Mostra valutazione'), type: 'toggle' },
    { key: 'show_add_to_cart', label: t('Mostra pulsante carrello'), type: 'toggle' },
    { key: 'show_badge', label: t('Mostra badge (saldo/nuovo)'), type: 'toggle' },
    { key: 'show_compare', label: t('Mostra pulsante Confronta'), type: 'toggle' },
    { key: 'pagination', label: t('Paginazione'), type: 'toggle' },

    { type: 'separator', label: t('Modalita') },
    { key: 'layout', label: t('Modalità'), type: 'select', options: [
      { value: 'grid', label: t('Griglia') },
      { value: 'carousel', label: t('Carosello') },
    ]},
    { key: 'carousel_autoplay', label: t('Autoplay'), type: 'toggle',
      condition: { field: 'layout', value: 'carousel' } },
    { key: 'carousel_loop', label: t('Loop infinito'), type: 'toggle',
      condition: { field: 'layout', value: 'carousel' } },
    { key: 'carousel_arrows', label: t('Mostra frecce'), type: 'toggle',
      condition: { field: 'layout', value: 'carousel' } },
    { key: 'carousel_dots', label: t('Mostra pallini'), type: 'toggle',
      condition: { field: 'layout', value: 'carousel' } },
  ],

  // ─── STILE ─────────────────────────────────────────────────
  styleFields: [
    { type: 'separator', label: t('Preset stilistico') },
    { key: 'preset', label: t('Stile'), type: 'select', options: [
      { value: 'modern-clean',    label: t('Modern Clean') },
      { value: 'minimal-mono',    label: t('Minimal Mono') },
      { value: 'magazine-bold',   label: t('Magazine Bold') },
      { value: 'editorial-serif', label: t('Editorial Serif') },
      { value: 'compact-inline',  label: t('Compact Inline') },
      { value: 'glass-frosted',   label: t('Glass Frosted') },
      { value: 'neon-glow',       label: t('Neon Glow') },
      { value: 'brutalist-stamp', label: t('Brutalist Stamp') },
      { value: 'gradient-aurora', label: t('Gradient Aurora') },
      { value: 'sticker-fun',     label: t('Sticker Fun') },
      { value: 'retro-terminal',  label: t('Retro Terminal') },
      { value: 'tilt-3d',         label: t('3D Tilt') },
      { value: 'custom',          label: t('Personalizzato') },
    ] },
    { type: 'separator', label: t('Tipografia') },
    { key: 'typography_preset', label: t('Stile tipografico'), type: 'select', optionsSource: 'globalTypography' },
    { type: 'typography', label: t('Titolo'),
      presetKey: 'typography_preset',
      responsiveKeys: ['size'],
      keys: {
        color: 'title_color',
      },
      sizeMin: 12, sizeMax: 60,
    },
    { type: 'typography', label: t('Prezzo'),
      presetKey: 'typography_preset',
      responsiveKeys: ['size'],
      keys: {
        color: 'price_color',
      },
      sizeMin: 12, sizeMax: 60,
    },
    { type: 'typography', label: t('Pulsante'),
      presetKey: 'typography_preset',
      responsiveKeys: ['size'],
      keys: {
        color: 'button_color',
      },
      sizeMin: 12, sizeMax: 60,
    },

    { type: 'separator', label: t('Layout') },
    { key: 'columns', label: t('Colonne'), type: 'range', min: 1, max: 6, step: 1 },
    { key: 'columns_tablet', label: t('Colonne tablet'), type: 'range', min: 1, max: 4, step: 1 },
    { key: 'columns_mobile', label: t('Colonne mobile'), type: 'range', min: 1, max: 2, step: 1 },
    { key: 'gap', label: t('Gap (px)'), type: 'range', min: 0, max: 48, step: 4 },
    { key: 'image_ratio', label: t('Proporzione immagine'), type: 'select', options: [
      { value: '1-1', label: t('1:1 Quadrato') },
      { value: '4-3', label: '4:3' },
      { value: '3-4', label: t('3:4 Verticale') },
      { value: '16-9', label: '16:9' },
      { value: 'auto', label: t('Automatico') },
    ]},
    { key: 'card_style', label: t('Stile card'), type: 'select', options: [
      { value: 'none', label: t('Nessuno') },
      { value: 'shadow', label: t('Ombra') },
      { value: 'border', label: t('Bordo') },
    ]},
    { key: 'hover_effect', label: t('Effetto hover'), type: 'select', options: [
      { value: 'none', label: t('Nessuno') },
      { value: 'zoom', label: t('Zoom') },
      { value: 'shadow', label: t('Ombra') },
    ]},
    { key: 'carousel_speed', label: t('Velocità (ms)'), type: 'range', min: 1000, max: 10000, step: 500,
      condition: { field: 'layout', value: 'carousel' } },

    { type: 'separator', label: t('Colori') },
    { key: 'sale_color', label: t('Colore saldo'), type: 'color' },
    { key: 'button_bg', label: t('Sfondo pulsante'), type: 'color' },
    { key: 'badge_bg', label: t('Sfondo badge'), type: 'color' },

    ...shadowField,
    ...borderFields(),
  ],
};
