export default {
  type: 'woo_myaccount',
  name: 'WC My Account',
  icon: 'dashicons-admin-users',
  category: 'woocommerce',
  placeholder: 'Dashboard account WooCommerce',
  defaults: {
    layout: 'default',
    sidebar_bg: '#F9FAFB',
    sidebar_active_bg: '#4f46e5',
    sidebar_active_color: '#FFFFFF',
    sidebar_color: '#374151',
    content_bg: '#FFFFFF',
    heading_color: '',
    text_color: '#374151',
    link_color: '#4f46e5',
    button_bg: '#4f46e5',
    button_color: '#FFFFFF',
    border_color: '#E5E7EB',
    border_radius: '8',
    avatar_size: '64',
  },
  fields: [
    { key: 'layout', label: 'Layout', type: 'select', options: [
      { value: 'default', label: 'Default' },
      { value: 'sidebar', label: 'Con sidebar' },
      { value: 'tabs', label: 'Tab' },
    ]},
    { key: 'avatar_size', label: 'Dimensione avatar (px)', type: 'range', min: 32, max: 128, step: 8 },
    { key: 'border_radius', label: 'Arrotondamento (px)', type: 'border-radius' },
    { key: 'border_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius' },
    { type: 'separator', label: 'Colori sidebar' },
    { key: 'sidebar_bg', label: 'Sfondo sidebar', type: 'color' },
    { key: 'sidebar_color', label: 'Colore testo', type: 'color' },
    { key: 'sidebar_active_bg', label: 'Sfondo attivo', type: 'color' },
    { key: 'sidebar_active_color', label: 'Colore attivo', type: 'color' },
    { type: 'separator', label: 'Colori contenuto' },
    { key: 'content_bg', label: 'Sfondo contenuto', type: 'color' },
    { key: 'heading_color', label: 'Colore intestazioni', type: 'color' },
    { key: 'text_color', label: 'Colore testo', type: 'color' },
    { key: 'link_color', label: 'Colore link', type: 'color' },
    { key: 'border_color', label: 'Colore bordi', type: 'color' },
    { key: 'button_bg', label: 'Sfondo pulsante', type: 'color' },
    { key: 'button_color', label: 'Colore testo pulsante', type: 'color' },
  ],
};
