
import { borderFields, borderDefault, borderHoverDefault, borderEffectDefaults } from './_shared.js';
export default {
  type: 'woo_upsells',
  name: 'Prodotti Suggeriti',
  icon: 'dashicons-star-filled',
  category: 'woocommerce',
  placeholder: 'Griglia prodotti suggeriti (upsell) WooCommerce',
  defaults: {
    columns: '4',
    show_image: true,
    show_title: true,
    show_price: true,
    card_style: 'shadow',
    gap: '24',
    title_text: 'Ti potrebbe interessare',
    show_heading: true,
    columns_tablet: '2',
    columns_mobile: '1',
    title_color: '',
    price_color: '',
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
  },
  fields: [
    { type: 'separator', label: 'Layout' },
    { key: 'columns', label: 'Colonne', type: 'range', min: 1, max: 6, step: 1 },
    { key: 'gap', label: 'Gap (px)', type: 'range', min: 0, max: 48, step: 4 },
    { key: 'card_style', label: 'Stile card', type: 'select', options: [
      { value: 'none', label: 'Nessuno' },
      { value: 'shadow', label: 'Ombra' },
      { value: 'border', label: 'Bordo' },
    ]},
    { key: 'columns_tablet', label: 'Colonne tablet', type: 'range', min: 1, max: 4, step: 1 },
    { key: 'columns_mobile', label: 'Colonne mobile', type: 'range', min: 1, max: 2, step: 1 },

    { type: 'separator', label: 'Elementi visibili' },
    { key: 'show_heading', label: 'Mostra titolo sezione', type: 'toggle' },
    { key: 'title_text', label: 'Testo titolo', type: 'text', condition: { key: 'show_heading', value: true } },
    { key: 'show_image', label: 'Mostra immagine', type: 'toggle' },
    { key: 'show_title', label: 'Mostra titolo', type: 'toggle' },
    { key: 'show_price', label: 'Mostra prezzo', type: 'toggle' },

    { type: 'separator', label: 'Colori' },
    { key: 'title_color', label: 'Colore titolo', type: 'color' },
    { key: 'price_color', label: 'Colore prezzo', type: 'color' },
    ...borderFields(),
  ],
};
