import { shadowField, borderFields, borderDefault, borderHoverDefault, borderEffectDefaults } from './_shared.js';

export default {
  type: 'woo_products',
  name: 'Prodotti WC',
  icon: 'dashicons-products',
  category: 'woocommerce',
  placeholder: 'Griglia prodotti WooCommerce',
  defaults: {
    posts_per_page: '12',
    columns: '4',
    orderby: 'date',
    order: 'DESC',
    category: '',
    tag: '',
    on_sale: false,
    featured: false,
    show_image: true,
    show_title: true,
    show_price: true,
    show_rating: false,
    show_add_to_cart: true,
    show_badge: true,
    image_ratio: '4-3',
    gap: '24',
    card_style: 'shadow',
    hover_effect: 'zoom',
    title_color: '',
    price_color: '',
    sale_color: '',
    button_color: '',
    button_bg: '',
    badge_bg: '',
    show_compare: false,
    pagination: false,
    layout: 'grid',
    carousel_autoplay: false,
    carousel_speed: '4000',
    carousel_loop: true,
    carousel_arrows: true,
    carousel_dots: true,
    columns_tablet: '2',
    columns_mobile: '1',
    shadow: 'none',
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
  },
  fields: [
    { type: 'separator', label: 'Query prodotti' },
    { key: 'posts_per_page', label: 'Prodotti per pagina', type: 'range', min: 1, max: 48, step: 1 },
    { key: 'columns', label: 'Colonne', type: 'range', min: 1, max: 6, step: 1 },
    { key: 'orderby', label: 'Ordina per', type: 'select', options: [
      { value: 'date', label: 'Data' },
      { value: 'price', label: 'Prezzo' },
      { value: 'popularity', label: 'Popolarita' },
      { value: 'rating', label: 'Valutazione' },
      { value: 'title', label: 'Titolo' },
    ]},
    { key: 'order', label: 'Direzione', type: 'select', options: [
      { value: 'DESC', label: 'Decrescente' },
      { value: 'ASC', label: 'Crescente' },
    ]},
    { key: 'category', label: 'Categoria (slug)', type: 'text', placeholder: 'es. magliette' },
    { key: 'tag', label: 'Tag (slug)', type: 'text', placeholder: 'es. novita' },
    { key: 'on_sale', label: 'Solo in saldo', type: 'toggle' },
    { key: 'featured', label: 'Solo in evidenza', type: 'toggle' },

    { type: 'separator', label: 'Elementi visibili' },
    { key: 'show_image', label: 'Mostra immagine', type: 'toggle' },
    { key: 'show_title', label: 'Mostra titolo', type: 'toggle' },
    { key: 'show_price', label: 'Mostra prezzo', type: 'toggle' },
    { key: 'show_rating', label: 'Mostra valutazione', type: 'toggle' },
    { key: 'show_add_to_cart', label: 'Mostra pulsante carrello', type: 'toggle' },
    { key: 'show_badge', label: 'Mostra badge (saldo/nuovo)', type: 'toggle' },
    { key: 'show_compare', label: 'Mostra pulsante Confronta', type: 'toggle' },
    { key: 'pagination', label: 'Paginazione', type: 'toggle' },

    { type: 'separator', label: 'Layout' },
    { key: 'layout', label: 'Modalità', type: 'select', options: [
      { value: 'grid', label: 'Griglia' },
      { value: 'carousel', label: 'Carosello' },
    ]},
    { key: 'carousel_autoplay', label: 'Autoplay', type: 'toggle',
      condition: { field: 'layout', value: 'carousel' } },
    { key: 'carousel_speed', label: 'Velocità (ms)', type: 'range', min: 1000, max: 10000, step: 500,
      condition: { field: 'layout', value: 'carousel' } },
    { key: 'carousel_loop', label: 'Loop infinito', type: 'toggle',
      condition: { field: 'layout', value: 'carousel' } },
    { key: 'carousel_arrows', label: 'Mostra frecce', type: 'toggle',
      condition: { field: 'layout', value: 'carousel' } },
    { key: 'carousel_dots', label: 'Mostra pallini', type: 'toggle',
      condition: { field: 'layout', value: 'carousel' } },
    { key: 'image_ratio', label: 'Proporzione immagine', type: 'select', options: [
      { value: '1-1', label: '1:1 Quadrato' },
      { value: '4-3', label: '4:3' },
      { value: '3-4', label: '3:4 Verticale' },
      { value: '16-9', label: '16:9' },
      { value: 'auto', label: 'Automatico' },
    ]},
    { key: 'gap', label: 'Gap (px)', type: 'range', min: 0, max: 48, step: 4 },
    { key: 'card_style', label: 'Stile card', type: 'select', options: [
      { value: 'none', label: 'Nessuno' },
      { value: 'shadow', label: 'Ombra' },
      { value: 'border', label: 'Bordo' },
    ]},
    { key: 'hover_effect', label: 'Effetto hover', type: 'select', options: [
      { value: 'none', label: 'Nessuno' },
      { value: 'zoom', label: 'Zoom' },
      { value: 'shadow', label: 'Ombra' },
    ]},
    { key: 'columns_tablet', label: 'Colonne tablet', type: 'range', min: 1, max: 4, step: 1 },
    { key: 'columns_mobile', label: 'Colonne mobile', type: 'range', min: 1, max: 2, step: 1 },

    { type: 'separator', label: 'Colori' },
    { key: 'title_color', label: 'Colore titolo', type: 'color' },
    { key: 'price_color', label: 'Colore prezzo', type: 'color' },
    { key: 'sale_color', label: 'Colore saldo', type: 'color' },
    { key: 'button_color', label: 'Colore testo pulsante', type: 'color' },
    { key: 'button_bg', label: 'Sfondo pulsante', type: 'color' },
    { key: 'badge_bg', label: 'Sfondo badge', type: 'color' },

    ...shadowField,
    ...borderFields(),
  ],
};
