
import { borderFields, borderDefault, borderHoverDefault, borderEffectDefaults } from './_shared.js';
export default {
  type: 'woo_comparison',
  name: 'WC Confronto Prodotti',
  icon: 'dashicons-columns',
  category: 'woocommerce',
  placeholder: 'Tabella confronto prodotti WooCommerce',
  defaults: {
    max_products: 4,
    show_image: true,
    show_price: true,
    show_rating: true,
    show_stock: true,
    show_sku: true,
    show_description: true,
    show_attributes: true,
    show_add_to_cart: true,
    header_bg: '#F9FAFB',
    header_color: '',
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
  },
  fields: [
    { key: 'max_products', label: 'Massimo prodotti', type: 'range', min: 2, max: 6 },
    { type: 'separator', label: 'Visibilita righe' },
    { key: 'show_image', label: 'Mostra immagine', type: 'toggle' },
    { key: 'show_price', label: 'Mostra prezzo', type: 'toggle' },
    { key: 'show_rating', label: 'Mostra valutazione', type: 'toggle' },
    { key: 'show_stock', label: 'Mostra disponibilita', type: 'toggle' },
    { key: 'show_sku', label: 'Mostra SKU', type: 'toggle' },
    { key: 'show_description', label: 'Mostra descrizione', type: 'toggle' },
    { key: 'show_attributes', label: 'Mostra attributi', type: 'toggle' },
    { key: 'show_add_to_cart', label: 'Mostra aggiungi al carrello', type: 'toggle' },
    { type: 'separator', label: 'Colori' },
    { key: 'header_bg', label: 'Sfondo intestazione', type: 'color' },
    { key: 'header_color', label: 'Colore intestazione', type: 'color' },
    ...borderFields(),
  ],
};
