export default {
  type: 'woo_addtocart',
  name: 'Aggiungi al Carrello',
  icon: 'dashicons-cart',
  category: 'woocommerce',
  placeholder: 'Pulsante aggiungi al carrello WooCommerce',
  defaults: {
    button_text: 'Aggiungi al carrello',
    show_quantity: true,
    show_icon: true,
    icon: 'cart',
    style: 'filled',
    size: 'medium',
    full_width: false,
    bg_color: '',
    text_color: '',
    hover_bg: '',
    hover_text: '',
    border_radius: '6',
    quantity_style: 'input',
  },
  fields: [
    { key: 'button_text', label: 'Testo pulsante', type: 'text' },
    { key: 'show_quantity', label: 'Mostra quantita', type: 'toggle' },
    { key: 'show_icon', label: 'Mostra icona', type: 'toggle' },
    { key: 'icon', label: 'Icona', type: 'select', options: [
      { value: 'cart', label: 'Carrello' },
      { value: 'bag', label: 'Borsa' },
      { value: 'plus', label: 'Piu' },
    ], condition: { field: 'show_icon', value: true } },
    { key: 'style', label: 'Stile', type: 'select', options: [
      { value: 'filled', label: 'Pieno' },
      { value: 'outline', label: 'Contorno' },
      { value: 'text', label: 'Solo testo' },
    ]},
    { key: 'size', label: 'Dimensione', type: 'select', options: [
      { value: 'small', label: 'Piccolo' },
      { value: 'medium', label: 'Medio' },
      { value: 'large', label: 'Grande' },
    ]},
    { key: 'full_width', label: 'Larghezza piena', type: 'toggle' },
    { key: 'quantity_style', label: 'Stile quantita', type: 'select', options: [
      { value: 'input', label: 'Campo numerico' },
      { value: 'stepper', label: 'Stepper +/-' },
    ], condition: { field: 'show_quantity', value: true } },
    { key: 'border_radius', label: 'Arrotondamento (px)', type: 'border-radius' },
    { key: 'border_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius' },

    { type: 'separator', label: 'Colori' },
    { key: 'bg_color', label: 'Sfondo', type: 'color' },
    { key: 'text_color', label: 'Colore testo', type: 'color' },
    { key: 'hover_bg', label: 'Sfondo hover', type: 'color' },
    { key: 'hover_text', label: 'Colore testo hover', type: 'color' },
  ],
};
