
import { borderFields, borderDefault, borderHoverDefault, borderEffectDefaults } from './_shared.js';
export default {
  type: 'woo_minicart',
  name: 'Mini Carrello',
  icon: 'dashicons-cart',
  category: 'woocommerce',
  placeholder: 'Mini carrello WooCommerce',
  defaults: {
    style: 'icon-text',
    icon: 'cart',
    show_count: true,
    show_total: true,
    dropdown: true,
    icon_size: '24',
    text_color: '',
    icon_color: '',
    badge_bg: '',
    badge_color: '',
    dropdown_width: '320',
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
  },
  fields: [
    { key: 'style', label: 'Stile', type: 'select', options: [
      { value: 'icon', label: 'Solo icona' },
      { value: 'icon-text', label: 'Icona + testo' },
      { value: 'text', label: 'Solo testo' },
    ]},
    { key: 'icon', label: 'Icona', type: 'select', options: [
      { value: 'cart', label: 'Carrello' },
      { value: 'bag', label: 'Borsa' },
      { value: 'basket', label: 'Cestino' },
    ]},
    { key: 'show_count', label: 'Mostra conteggio', type: 'toggle' },
    { key: 'show_total', label: 'Mostra totale', type: 'toggle' },
    { key: 'dropdown', label: 'Dropdown al hover', type: 'toggle' },
    { key: 'icon_size', label: 'Dimensione icona (px)', type: 'range', min: 16, max: 48, step: 2 },
    { key: 'dropdown_width', label: 'Larghezza dropdown (px)', type: 'range', min: 240, max: 480, step: 20,
      condition: { field: 'dropdown', value: true } },

    { type: 'separator', label: 'Colori' },
    { key: 'text_color', label: 'Colore testo', type: 'color' },
    { key: 'icon_color', label: 'Colore icona', type: 'color' },
    { key: 'badge_bg', label: 'Sfondo badge', type: 'color' },
    { key: 'badge_color', label: 'Colore badge', type: 'color' },
    ...borderFields(),
  ],
};
