
import { borderFields, borderDefault, borderHoverDefault, borderEffectDefaults } from './_shared.js';

export default {
  type: 'woo_categories',
  name: 'Categorie Prodotti',
  icon: 'dashicons-category',
  category: 'woocommerce',
  placeholder: 'Griglia categorie WooCommerce',
  defaults: {
    columns: '4',
    show_image: true,
    show_count: true,
    show_description: false,
    hide_empty: true,
    orderby: 'name',
    parent_only: false,
    overlay: true,
    overlay_color: 'rgba(0,0,0,0.4)',
    text_color: '',
    title_tag: 'h3',
    gap: '24',
    image_ratio: '1-1',
    border_radius: '8',
    hover_effect: 'zoom',
    columns_tablet: '2',
    columns_mobile: '1',
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
  },
  fields: [
    { type: 'separator', label: 'Query' },
    { key: 'orderby', label: 'Ordina per', type: 'select', options: [
      { value: 'name', label: 'Nome' },
      { value: 'count', label: 'Conteggio prodotti' },
      { value: 'id', label: 'ID' },
      { value: 'slug', label: 'Slug' },
    ]},
    { key: 'parent_only', label: 'Solo categorie padre', type: 'toggle' },
    { key: 'hide_empty', label: 'Nascondi vuote', type: 'toggle' },

    { type: 'separator', label: 'Elementi visibili' },
    { key: 'show_image', label: 'Mostra immagine', type: 'toggle' },
    { key: 'show_count', label: 'Mostra conteggio prodotti', type: 'toggle' },
    { key: 'show_description', label: 'Mostra descrizione', type: 'toggle' },

    { type: 'separator', label: 'Layout' },
    { key: 'columns', label: 'Colonne', type: 'range', min: 1, max: 6, step: 1 },
    { key: 'gap', label: 'Gap (px)', type: 'range', min: 0, max: 48, step: 4 },
    { key: 'image_ratio', label: 'Proporzione immagine', type: 'select', options: [
      { value: '1-1', label: '1:1 Quadrato' },
      { value: '4-3', label: '4:3' },
      { value: '3-4', label: '3:4 Verticale' },
      { value: '16-9', label: '16:9' },
    ]},
    { key: 'title_tag', label: 'Tag titolo', type: 'select', options: [
      { value: 'h2', label: 'H2' },
      { value: 'h3', label: 'H3' },
      { value: 'h4', label: 'H4' },
      { value: 'h5', label: 'H5' },
    ]},
    { key: 'hover_effect', label: 'Effetto hover', type: 'select', options: [
      { value: 'none', label: 'Nessuno' },
      { value: 'zoom', label: 'Zoom' },
      { value: 'darken', label: 'Scurisci' },
    ]},
    { key: 'columns_tablet', label: 'Colonne tablet', type: 'range', min: 1, max: 4, step: 1 },
    { key: 'columns_mobile', label: 'Colonne mobile', type: 'range', min: 1, max: 2, step: 1 },

    { type: 'separator', label: 'Colori' },
    { key: 'overlay', label: 'Overlay', type: 'toggle' },
    { key: 'overlay_color', label: 'Colore overlay', type: 'color',
      condition: { field: 'overlay', value: true } },
    { key: 'text_color', label: 'Colore testo', type: 'color' },
    { key: 'border_radius', label: 'Arrotondamento (px)', type: 'border-radius' },
    { key: 'border_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius' },
    ...borderFields(),
  ],
};
