import { shadowField, borderFields, borderDefault, borderHoverDefault, borderEffectDefaults } from './_shared.js';

export default {
  type: 'woo_product_gallery_slider',
  name: 'WC Gallery Slider',
  icon: 'dashicons-images-alt2',
  category: 'woocommerce',
  placeholder: 'Gallery slider prodotto WooCommerce',
  defaults: {
    show_thumbnails: true,
    thumbnail_position: 'bottom',
    enable_zoom: true,
    enable_lightbox: true,
    main_height: '500px',
    thumbnail_size: '80',
    thumbnail_gap: '8',
    autoplay: false,
    autoplay_speed: '3000',
    transition: 'slide',
    arrows: true,
    dots: false,
    border_radius: '8',
    main_bg: '',
    thumbnail_border: '',
    thumbnail_active_border: '',
    arrow_color: '',
    arrow_bg: '',
    dot_color: '',
    dot_active_color: '',
    shadow: 'none',
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
  },
  fields: [
    { type: 'separator', label: 'Immagine principale' },
    { key: 'main_height', label: 'Altezza principale', type: 'text', placeholder: 'es. 500px, 60vh' },
    { key: 'enable_zoom', label: 'Abilita zoom', type: 'toggle' },
    { key: 'enable_lightbox', label: 'Abilita lightbox', type: 'toggle' },
    { key: 'border_radius', label: 'Raggio bordi (px)', type: 'border-radius' },
    { key: 'border_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius' },

    { type: 'separator', label: 'Miniature' },
    { key: 'show_thumbnails', label: 'Mostra miniature', type: 'toggle' },
    { key: 'thumbnail_position', label: 'Posizione miniature', type: 'select', options: [
      { value: 'bottom', label: 'Sotto' },
      { value: 'left', label: 'Sinistra' },
      { value: 'right', label: 'Destra' },
    ]},
    { key: 'thumbnail_size', label: 'Dimensione miniature (px)', type: 'range', min: 40, max: 150, step: 5 },
    { key: 'thumbnail_gap', label: 'Gap miniature (px)', type: 'range', min: 0, max: 24, step: 2 },

    { type: 'separator', label: 'Slider' },
    { key: 'transition', label: 'Transizione', type: 'select', options: [
      { value: 'slide', label: 'Slide' },
      { value: 'fade', label: 'Fade' },
    ]},
    { key: 'autoplay', label: 'Autoplay', type: 'toggle' },
    { key: 'autoplay_speed', label: 'Velocita autoplay (ms)', type: 'range', min: 1000, max: 10000, step: 500 },
    { key: 'arrows', label: 'Mostra frecce', type: 'toggle' },
    { key: 'dots', label: 'Mostra dots', type: 'toggle' },

    { type: 'separator', label: 'Colori' },
    { key: 'main_bg', label: 'Sfondo immagine', type: 'color' },
    { key: 'thumbnail_border', label: 'Bordo miniature', type: 'color' },
    { key: 'thumbnail_active_border', label: 'Bordo miniatura attiva', type: 'color' },
    { key: 'arrow_color', label: 'Colore frecce', type: 'color' },
    { key: 'arrow_bg', label: 'Sfondo frecce', type: 'color' },
    { key: 'dot_color', label: 'Colore dots', type: 'color' },
    { key: 'dot_active_color', label: 'Colore dot attivo', type: 'color' },

    ...shadowField,
    ...borderFields(),
  ],
};
