import { textEffectsFields, textEffectsDefaults, borderFields, borderDefault, borderHoverDefault, borderEffectDefaults } from './_shared';
import { shadowField } from './_shared.js';

export default {
  type: 'woo_recently_viewed',
  name: 'WC Visti di Recente',
  icon: 'dashicons-clock',
  category: 'woocommerce',
  placeholder: 'Prodotti visti di recente WooCommerce',
  defaults: {
    columns: '4',
    limit: '8',
    card_style: 'default',
    show_price: true,
    heading: 'Visti di recente',
    show_image: true,
    show_rating: false,
    show_add_to_cart: true,
    image_ratio: '4-3',
    gap: '24',
    hover_effect: 'zoom',
    heading_tag: 'h3',
    heading_color: '',
    title_color: '',
    price_color: '',
    button_color: '',
    button_bg: '',
    empty_text: 'Nessun prodotto visualizzato di recente',
    empty_color: '',
    columns_tablet: '2',
    columns_mobile: '1',
    shadow: 'none',
    ...textEffectsDefaults,
    border: { ...borderDefault },
    border_hover: { ...borderHoverDefault },
    border_hover_duration: 300,
    ...borderEffectDefaults,
  },
  fields: [
    { type: 'separator', label: 'Intestazione' },
    { key: 'heading', label: 'Titolo sezione', type: 'text' },
    { key: 'heading_tag', label: 'Tag heading', type: 'select', options: [
      { value: 'h2', label: 'H2' },
      { value: 'h3', label: 'H3' },
      { value: 'h4', label: 'H4' },
      { value: 'div', label: 'DIV' },
    ]},

    { type: 'separator', label: 'Layout' },
    { key: 'columns', label: 'Colonne', type: 'range', min: 1, max: 6, step: 1 },
    { key: 'limit', label: 'Numero massimo prodotti', type: 'range', min: 1, max: 24, step: 1 },
    { key: 'gap', label: 'Gap (px)', type: 'range', min: 0, max: 48, step: 4 },
    { key: 'image_ratio', label: 'Proporzione immagine', type: 'select', options: [
      { value: '1-1', label: '1:1 Quadrato' },
      { value: '4-3', label: '4:3' },
      { value: '3-4', label: '3:4 Verticale' },
      { value: '16-9', label: '16:9' },
      { value: 'auto', label: 'Automatico' },
    ]},
    { key: 'card_style', label: 'Stile card', type: 'select', options: [
      { value: 'default', label: 'Default' },
      { value: 'shadow', label: 'Ombra' },
      { value: 'border', label: 'Bordo' },
    ]},
    { key: 'hover_effect', label: 'Effetto hover', type: 'select', options: [
      { value: 'none', label: 'Nessuno' },
      { value: 'zoom', label: 'Zoom' },
      { value: 'shadow', label: 'Ombra' },
    ]},
    { key: 'columns_tablet', label: 'Colonne tablet', type: 'range', min: 1, max: 4, step: 1 },
    { key: 'columns_mobile', label: 'Colonne mobile', type: 'range', min: 1, max: 2, step: 1 },

    { type: 'separator', label: 'Elementi visibili' },
    { key: 'show_image', label: 'Mostra immagine', type: 'toggle' },
    { key: 'show_price', label: 'Mostra prezzo', type: 'toggle' },
    { key: 'show_rating', label: 'Mostra valutazione', type: 'toggle' },
    { key: 'show_add_to_cart', label: 'Mostra pulsante carrello', type: 'toggle' },
    { key: 'empty_text', label: 'Testo lista vuota', type: 'text' },

    { type: 'separator', label: 'Colori' },
    { key: 'heading_color', label: 'Colore intestazione', type: 'color' },
    { key: 'title_color', label: 'Colore titolo', type: 'color' },
    { key: 'price_color', label: 'Colore prezzo', type: 'color' },
    { key: 'button_color', label: 'Colore testo pulsante', type: 'color' },
    { key: 'button_bg', label: 'Sfondo pulsante', type: 'color' },
    { key: 'empty_color', label: 'Colore testo vuoto', type: 'color' },

    ...shadowField,
    ...textEffectsFields([ { value: 'heading', label: 'Solo Titolo' } ]),
    ...borderFields(),
  ],
};
