export default {
  type: 'wpcomments',
  name: 'Commenti',
  icon: 'dashicons-admin-comments',
  category: 'dynamic',
  defaults: {
    show_title: true,
    title_text: 'Commenti',
    title_tag: 'h3',
    show_avatar: true,
    avatar_size: '48',
    show_date: true,
    show_reply_link: true,
    show_form: true,
    comments_per_page: '10',
    order: 'desc',
    title_color: '',
    text_color: '',
    author_color: '',
    date_color: '',
    link_color: '',
    form_background: '',
    border_color: '',
    avatar_border_radius: '50',
  },
  fields: [
    { type: 'separator', label: 'Titolo' },
    { key: 'show_title', label: 'Mostra titolo', type: 'toggle' },
    { key: 'title_text', label: 'Testo titolo', type: 'text',
      condition: { field: 'show_title', operator: '==', value: true } },
    { key: 'title_tag', label: 'Tag titolo', type: 'select', options: [
      { value: 'h2', label: 'H2' },
      { value: 'h3', label: 'H3' },
      { value: 'h4', label: 'H4' },
      { value: 'h5', label: 'H5' },
    ], condition: { field: 'show_title', operator: '==', value: true } },

    { type: 'separator', label: 'Commenti' },
    { key: 'show_avatar', label: 'Mostra avatar', type: 'toggle' },
    { key: 'avatar_size', label: 'Dimensione avatar (px)', type: 'range', min: 24, max: 96, step: 4,
      condition: { field: 'show_avatar', operator: '==', value: true } },
    { key: 'avatar_border_radius', label: 'Raggio avatar (%)', type: 'border-radius',
      condition: { field: 'show_avatar', operator: '==', value: true } },
    { key: 'avatar_border_radius_hover', label: 'Raggio bordo (hover)', type: 'border-radius' },
    { key: 'show_date', label: 'Mostra data', type: 'toggle' },
    { key: 'show_reply_link', label: 'Mostra link rispondi', type: 'toggle' },
    { key: 'comments_per_page', label: 'Commenti per pagina', type: 'range', min: 5, max: 50, step: 5 },
    { key: 'order', label: 'Ordine', type: 'select', options: [
      { value: 'desc', label: 'Più recenti prima' },
      { value: 'asc', label: 'Più vecchi prima' },
    ]},

    { type: 'separator', label: 'Modulo commento' },
    { key: 'show_form', label: 'Mostra modulo commento', type: 'toggle' },

    { type: 'separator', label: 'Colori' },
    { key: 'title_color', label: 'Colore titolo', type: 'color' },
    { key: 'text_color', label: 'Colore testo', type: 'color' },
    { key: 'author_color', label: 'Colore autore', type: 'color' },
    { key: 'date_color', label: 'Colore data', type: 'color' },
    { key: 'link_color', label: 'Colore link', type: 'color' },
    { key: 'form_background', label: 'Sfondo modulo', type: 'color' },
    { key: 'border_color', label: 'Colore bordo', type: 'color' },
  ],
};
