/* Fiori — ricomposizione TILE-PURE (image-free). Wedding/Events · sage + blush + ivory. */
const K = require('./tmp_theme_kit.cjs');
const { sec, row, col, tile, R } = K.builders('fi');

// ── Palette (da :root fiori.css) ──────────────────────────────
const SAGE   = '#5f6f4e';
const SAGE_D = '#4c5a3e';
const SAGE2  = '#2c3327';
const BLUSH  = '#cfa6a0';
const BLUSH_D= '#bb8b84';
const IVORY  = '#f3efe6';
const IVORY2 = '#eae3d5';
const PAPER  = '#fbf9f3';
const TXT    = '#34372e';
const SOFT   = '#6a6d60';
const FAINT  = '#9a9b8d';
const LINE   = '#e3ddce';
const LINE_DK= 'rgba(255,255,255,.16)';
const WHITE  = '#ffffff';

const home = [];

// ── 1) HERO — hero-split image-free ──────────────────────────
// Blueprint: centrato, full-bleed, nomi grandi con "&" in blush, data + RSVP button
// Approximazione con hero-split (tile più vicino per coppie nome+CTA)
home.push(sec(SAGE2, 'large', [ row([ col('1-1', [ tile('hero-split', {
  eyebrow_text: `We're getting married`,
  eyebrow_dot_color: BLUSH,
  eyebrow_color: 'rgba(255,255,255,.85)',
  headline_lines: [
    { text: 'Marta', color: WHITE, italic: false },
    { text: '&', color: BLUSH, italic: false },
    { text: 'Elia', color: WHITE, italic: false },
  ],
  headline_font_family: 'serif',
  headline_font_size: 88,
  headline_line_height: 0.95,
  headline_font_weight: '400',
  headline_align: 'left',
  subhead: `12 September 2026 · Villa Serbelloni, Lago di Como`,
  subhead_color: 'rgba(255,255,255,.8)',
  subhead_size: 18,
  subhead_italic: false,
  subhead_max_width: 480,
  cta1_text: 'RSVP now',
  cta1_url: '#rsvp',
  cta1_bg: BLUSH,
  cta1_color: WHITE,
  cta1_size: 12,
  cta1_radius: R(999),
  cta1_radius_hover: R(999),
  cta2_text: 'Our story',
  cta2_url: '#story',
  cta2_bg: 'rgba(255,255,255,.08)',
  cta2_color: WHITE,
  cta2_border: 'rgba(255,255,255,.4)',
  cta2_size: 12,
  cta2_radius: R(999),
  cta2_radius_hover: R(999),
  stats: [],
  showcase_enabled: true,
  showcase_bg: { type: 'solid', color: '#1e2a1a' },
  showcase_padding: 32,
  showcase_radius: R(8),
  showcase_radius_hover: R(8),
  showcase_badge_text: 'SAVE THE DATE · 12 · IX · 2026',
  showcase_badge_dot: BLUSH,
  showcase_badge_bg: SAGE2,
  showcase_badge_color: 'rgba(255,255,255,.7)',
  showcase_items: [
    { number: 'Ceremony', text: '4:00 pm', italic: false, text_color: WHITE, bg: { type: 'solid', color: '#2c3327' } },
    { number: 'Reception', text: '6:30 pm', italic: false, text_color: WHITE, bg: { type: 'solid', color: '#2c3327' } },
    { number: 'Venue', text: 'Villa Serbelloni', italic: false, text_color: BLUSH, bg: { type: 'solid', color: '#2c3327' } },
    { number: 'Dress code', text: 'Garden formal', italic: false, text_color: WHITE, bg: { type: 'solid', color: '#2c3327' } },
  ],
  showcase_card_radius: R(6),
  showcase_card_radius_hover: R(6),
  showcase_card_shadow: 'none',
  showcase_caption_left: 'LAGO DI COMO',
  showcase_caption_right: 'ITALY',
  showcase_hover_effect: 'none',
  split_ratio: '.85fr 1.15fr',
  gap: 56,
  min_height: 0,
  tile_padding: { top: 0, right: 0, bottom: 0, left: 0 },
}) ]) ]) ]));

// ── 2) COUNTDOWN ─────────────────────────────────────────────
// Blueprint: script "Counting down to forever" sopra le unità
// → section-header come label script, poi countdown tile
home.push(sec(SAGE2, 'small', [
  row([ col('1-1', [ tile('section-header', {
    eyebrow_show: false,
    eyebrow_text: '',
    headline_lines: [ { text: 'Counting down to forever', color: BLUSH, italic: false } ],
    headline_font_family: 'serif',
    headline_font_size: 48,
    headline_font_weight: '400',
    headline_align: 'center',
    headline_inline: false,
    tagline_show: false,
    tagline_text: '',
    layout: 'center',
    gap: 0,
    tile_padding: { top: 0, right: 0, bottom: 0, left: 0 },
  }) ]) ]),
  row([ col('1-1', [ tile('countdown', {
    countdown_type: 'date',
    target_date: '2026-09-12T16:00',
    countdown_style: 'custom',
    display_mode: 'block',
    show_days: true,
    show_hours: true,
    show_minutes: true,
    show_seconds: true,
    label_days: 'Days',
    label_hours: 'Hours',
    label_minutes: 'Minutes',
    label_seconds: 'Seconds',
    separator: '',
    expired_message: `The big day has arrived!`,
    expire_action: 'message',
    expire_message: `The big day has arrived!`,
    bg_color: 'transparent',
    accent_color: WHITE,
    text_color: 'rgba(255,255,255,.55)',
    separator_color: 'transparent',
    number_font_size: '60',
    number_font_weight: '400',
    label_font_size: '11',
    label_font_weight: '600',
    separator_font_size: '32',
    item_min_width: '90',
    item_bg_color: 'rgba(255,255,255,.05)',
    item_radius: '4',
    item_padding: '20',
    tile_padding: { top: 12, right: 32, bottom: 24, left: 32 },
  }) ]) ]),
]));

// ── helpers centrati ──────────────────────────────────────────
const shead = (script, title, intro) => tile('section-header', {
  eyebrow_show: true,
  eyebrow_text: script,
  eyebrow_color: BLUSH_D,
  eyebrow_dot_color: BLUSH_D,
  eyebrow_separator: '',
  headline_lines: [ { text: title, color: TXT, italic: false } ],
  headline_font_family: 'serif',
  headline_font_size: 36,
  headline_font_weight: '400',
  headline_align: 'center',
  headline_inline: false,
  tagline_show: !!intro,
  tagline_text: intro || '',
  tagline_text_italic: false,
  tagline_text_color: SOFT,
  tagline_text_size: 16,
  layout: 'center',
  gap: 14,
});

// ── 3) OUR STORY — hero-split (text left, abstract panel right) ─
// Blueprint: grid 2 col (media + text), parag×2, btn ghost sage
home.push(sec(IVORY, 'large', [ row([ col('1-1', [ tile('hero-split', {
  eyebrow_text: 'our story',
  eyebrow_dot_color: BLUSH_D,
  eyebrow_color: BLUSH_D,
  headline_lines: [
    { text: 'From a rainy', color: TXT, italic: false },
    { text: `café to forever`, color: SAGE, italic: false },
  ],
  headline_font_family: 'serif',
  headline_font_size: 40,
  headline_line_height: 1.1,
  headline_font_weight: '400',
  headline_align: 'left',
  subhead: `We met eight years ago, sheltering from the same downpour under the same café awning. Marta ordered the last cornetto; Elia has never quite forgiven her, and never quite left her side since.\n\nTwo cities, one very stubborn houseplant, and a thousand small mornings later — we’re doing the most natural thing in the world. We’d love you there when we do.`,
  subhead_color: SOFT,
  subhead_size: 16,
  subhead_italic: false,
  subhead_max_width: 520,
  cta1_text: 'All the details',
  cta1_url: '#details',
  cta1_bg: 'transparent',
  cta1_color: SAGE,
  cta1_border: SAGE,
  cta1_size: 12,
  cta1_radius: R(999),
  cta1_radius_hover: R(999),
  stats: [],
  showcase_enabled: true,
  showcase_bg: { type: 'solid', color: IVORY2 },
  showcase_padding: 0,
  showcase_radius: R(4),
  showcase_radius_hover: R(4),
  showcase_badge_text: 'Eight years together',
  showcase_badge_dot: BLUSH_D,
  showcase_badge_bg: IVORY,
  showcase_badge_color: SOFT,
  showcase_items: [
    { number: 'Met', text: '2018', italic: false, text_color: TXT, bg: { type: 'solid', color: IVORY2 } },
    { number: 'Engaged', text: '2025', italic: false, text_color: TXT, bg: { type: 'solid', color: IVORY2 } },
    { number: 'Getting married', text: `♥ 2026`, italic: false, text_color: BLUSH_D, bg: { type: 'solid', color: IVORY2 } },
  ],
  showcase_card_radius: R(4),
  showcase_card_radius_hover: R(4),
  showcase_card_shadow: 'none',
  showcase_caption_left: '',
  showcase_caption_right: '',
  showcase_hover_effect: 'none',
  split_ratio: '1.1fr .9fr',
  gap: 56,
  min_height: 0,
  tile_padding: { top: 0, right: 0, bottom: 0, left: 0 },
}) ]) ]) ]));

// ── 4) DETAILS CARDS — section-header + info-cards ────────────
// Blueprint: .det{background:var(--paper); border:1px solid var(--line); border-radius:6px; padding:36px 28px; text-align:center}
// .det__ic{border:1px solid var(--blush); border-radius:50%}; .when{font-family:var(--disp);color:var(--blush-d)}
// Section bg: var(--paper) con border-block:1px solid var(--line)
home.push(sec(PAPER, 'large', [
  row([ col('1-1', [ shead('the day', 'Where & when', '') ]) ]),
  row([ col('1-1', [ tile('info-cards', {
    container_bg: { type: 'solid', color: 'transparent' },
    container_padding: 0,
    container_gap: 24,
    columns: 3,
    items_gap: 24,
    card_bg: { type: 'solid', color: PAPER },
    card_color: SOFT,
    card_radius: R(6),
    card_padding: 36,
    show_icon: true,
    show_counter: false,
    show_arrow: false,
    show_footer: true,
    show_media: false,
    icon_color: SAGE,
    icon_bg_color: 'transparent',
    icon_border_color: BLUSH,
    icon_border_width: 1,
    icon_shape: 'circle',
    icon_size: 24,
    icon_container_size: 54,
    title_color: TXT,
    title_font_family: 'serif',
    title_size: 22,
    title_weight: '400',
    title_italic: false,
    description_size: 14,
    footer_size: 17,
    footer_color: BLUSH_D,
    footer_font_family: 'serif',
    card_border_color: LINE,
    card_border_width: 1,
    card_hover_effect: 'lift',
    items: [
      {
        icon: 'home',
        title: 'Ceremony',
        description: 'Villa Serbelloni gardens, overlooking the lake.',
        footer_text: '4:00 pm',
      },
      {
        icon: 'glass-water',
        title: 'Reception',
        description: 'Dinner, dancing and far too much cake on the terrace.',
        footer_text: '6:30 pm',
      },
      {
        icon: 'shirt',
        title: 'Dress code',
        description: 'Garden formal. Comfortable shoes for the lawn, please.',
        footer_text: 'Garden formal',
      },
    ],
  }) ]) ]),
]));

// ── 5) SCHEDULE — section-header + step-timeline (layout verticale, 1 colonna) ─
// Blueprint: .sched a lista verticale: .sched__i{grid-template-columns:120px 1fr}
// .sched__t{font-family:var(--disp);font-size:22px;color:var(--sage);text-align:right}
// .sched__c h3 uppercase 18px + p 14px
// step-timeline columns:1 riproduce layout verticale con counter=orario, title=titolo evento
home.push(sec(PAPER, 'large', [
  row([ col('1-1', [ shead('the timeline', 'How the day unfolds', '') ]) ]),
  row([ col('1-1', [ tile('step-timeline', {
    columns: 1,
    gap: 0,
    items_align: 'start',
    show_timeline: false,
    timeline_line_color: `rgba(227,221,206,.6)`,
    timeline_dot_color: BLUSH_D,
    timeline_dot_size: 10,
    timeline_height: 1,
    timeline_margin_bottom: 0,
    counter_font_family: 'serif',
    counter_size: 44,
    counter_color: SAGE,
    counter_italic: false,
    counter_weight: '400',
    tag_size: 11,
    tag_color: SOFT,
    media_aspect_ratio: '4/3',
    media_radius: R(0),
    media_radius_hover: R(0),
    media_radius_hover_duration: 300,
    media_shadow: 'none',
    show_media_label: false,
    pre_title_size: 11,
    pre_title_color: FAINT,
    title_font_family: 'serif',
    title_size: 18,
    title_weight: '400',
    title_color: TXT,
    title_accent_color: SAGE,
    description_size: 14,
    description_color: SOFT,
    footer_icon: '',
    footer_value_size: 14,
    footer_label_size: 10,
    footer_value_color: SAGE,
    footer_label_color: FAINT,
    separator_color: LINE,
    show_separator: true,
    items: [
      {
        counter: '3:30 pm',
        tag_text: '',
        tag_dot_color: BLUSH_D,
        media_label: '',
        media_type: 'placeholder',
        media_content: '',
        media_image: '',
        media_bg: IVORY2,
        media_color: BLUSH_D,
        pre_title: '',
        title: 'Arrival',
        title_accent: 'welcome',
        title_accent_italic: false,
        title_after: '',
        title_after_italic: false,
        description: `Find your seat in the gardens — a glass of something cold awaits.`,
        footer_value: '',
        footer_label: '',
        separator_text: '',
      },
      {
        counter: '4:00 pm',
        tag_text: '',
        tag_dot_color: BLUSH_D,
        media_label: '',
        media_type: 'placeholder',
        media_content: '',
        media_image: '',
        media_bg: IVORY2,
        media_color: SAGE,
        pre_title: '',
        title: 'Ceremony',
        title_accent: '',
        title_accent_italic: false,
        title_after: '',
        title_after_italic: false,
        description: `The bit we’ve all been waiting for.`,
        footer_value: '',
        footer_label: '',
        separator_text: '',
      },
      {
        counter: '5:00 pm',
        tag_text: '',
        tag_dot_color: BLUSH_D,
        media_label: '',
        media_type: 'placeholder',
        media_content: '',
        media_image: '',
        media_bg: IVORY2,
        media_color: BLUSH_D,
        pre_title: '',
        title: 'Aperitivo',
        title_accent: 'photos',
        title_accent_italic: false,
        title_after: '',
        title_after_italic: false,
        description: `Lakeside drinks while we steal away for a few pictures.`,
        footer_value: '',
        footer_label: '',
        separator_text: '',
      },
      {
        counter: '6:30 pm',
        tag_text: '',
        tag_dot_color: BLUSH_D,
        media_label: '',
        media_type: 'placeholder',
        media_content: '',
        media_image: '',
        media_bg: IVORY2,
        media_color: SAGE,
        pre_title: '',
        title: 'Dinner',
        title_accent: '',
        title_accent_italic: false,
        title_after: '',
        title_after_italic: false,
        description: `A long table, a longer menu, and the speeches you’ve been warned about.`,
        footer_value: '',
        footer_label: '',
        separator_text: '',
      },
      {
        counter: '9:00 pm',
        tag_text: '',
        tag_dot_color: SAGE,
        media_label: '',
        media_type: 'placeholder',
        media_content: '',
        media_image: '',
        media_bg: SAGE2,
        media_color: BLUSH,
        pre_title: '',
        title: 'Dancing',
        title_accent: '',
        title_accent_italic: false,
        title_after: '',
        title_after_italic: false,
        description: `Until the band gives up or the sun comes back — whichever’s first.`,
        footer_value: '',
        footer_label: '',
        separator_text: '',
      },
    ],
  }) ]) ]),
]));

// ── 6) GALLERY — section-header + progallery (image-free placeholder grid) ─
// Blueprint: fi-gal 4-col grid, 6 pannelli (.tall span 2 row, .wide span 2 col)
// progallery con images vuote rende placeholder nativi, layout metro/masonry
home.push(sec(IVORY, 'large', [
  row([ col('1-1', [ shead('us, lately', 'A few favourites', '') ]) ]),
  row([ col('1-1', [ tile('progallery', {
    images: [],
    layout: 'metro',
    layout_family: 'classic',
    columns: '4',
    gap: '12',
    img_height: '160px',
    object_fit: 'cover',
    thumb_radius: '4',
    mobile_columns: '2',
    expand_ratio: '4',
    bg: { type: 'none' },
    tile_padding: { top: 0, right: 0, bottom: 0, left: 0 },
  }) ]) ]),
]));

// ── 7) RSVP — form tile (vero form RSVP) ─────────────────────────────────────
// Blueprint: .fi-rsvp — sfondo sage-2 con overlay scuro; form: nome+cognome(row),
// email(full), attending+guests(row), submit btn blush pill
// Form tile stilizzato su dark bg: input trasparenti, testo bianco
home.push(sec(SAGE2, 'large', [
  row([ col('1-1', [ tile('section-header', {
    eyebrow_show: true,
    eyebrow_text: 'join us',
    eyebrow_color: BLUSH,
    eyebrow_dot_color: BLUSH,
    eyebrow_separator: '',
    headline_lines: [ { text: 'Kindly reply', color: WHITE, italic: false } ],
    headline_font_family: 'serif',
    headline_font_size: 40,
    headline_font_weight: '400',
    headline_align: 'center',
    headline_inline: false,
    tagline_show: true,
    tagline_text: `We’d be honoured to have you there. Please let us know by 1 July 2026.`,
    tagline_text_italic: false,
    tagline_text_color: 'rgba(255,255,255,.82)',
    tagline_text_size: 16,
    layout: 'center',
    gap: 14,
    tile_padding: { top: 0, right: 0, bottom: 32, left: 0 },
  }) ]) ]),
  row([ col('1-1', [ tile('form', {
    fields: [
      { id: 'rsvp-1', field_type: 'text',    label: 'First name',    placeholder: 'First name',    name: 'first_name',  required: true,  width: '1-2', options: '', icon: 'user',  condition_field: '', condition_operator: 'equals', condition_value: '' },
      { id: 'rsvp-2', field_type: 'text',    label: 'Last name',     placeholder: 'Last name',     name: 'last_name',   required: true,  width: '1-2', options: '', icon: 'user',  condition_field: '', condition_operator: 'equals', condition_value: '' },
      { id: 'rsvp-3', field_type: 'email',   label: 'Email address', placeholder: 'Email address', name: 'email',       required: true,  width: '1-1', options: '', icon: 'mail',  condition_field: '', condition_operator: 'equals', condition_value: '' },
      { id: 'rsvp-4', field_type: 'select',  label: 'Attending',     placeholder: '',              name: 'attending',   required: true,  width: '1-2', options: 'Joyfully accepts\nRegretfully declines', icon: '', condition_field: '', condition_operator: 'equals', condition_value: '' },
      { id: 'rsvp-5', field_type: 'select',  label: 'Guests',        placeholder: '',              name: 'guests',      required: false, width: '1-2', options: '1 guest\n2 guests\n3 guests', icon: '', condition_field: '', condition_operator: 'equals', condition_value: '' },
    ],
    email_to: '',
    email_subject: 'RSVP — Marta & Elia',
    success_message: 'Thank you! We look forward to celebrating with you.',
    error_message: 'Something went wrong. Please try again.',
    submit_text: 'Send RSVP',
    submit_icon: '',
    submit_alignment: 'center',
    submit_full_width: false,
    form_max_width: '560',
    form_align: 'center',
    form_layout: 'stacked',
    label_color: 'rgba(255,255,255,.7)',
    label_size: '13',
    label_weight: '500',
    input_bg: 'rgba(255,255,255,.08)',
    input_color: WHITE,
    input_border_color: 'rgba(255,255,255,.3)',
    input_border_width: '1',
    input_border_style: 'box',
    input_radius: R(4),
    input_size: 'default',
    input_focus_border: BLUSH,
    input_focus_shadow: false,
    input_placeholder_opacity: '0.5',
    gap: '12',
    submit_bg: BLUSH,
    submit_color: WHITE,
    submit_radius: R(999),
    submit_font_size: '13',
    submit_font_weight: '600',
    submit_hover_bg: BLUSH_D,
    submit_border_width: '0',
    submit_letter_spacing: '0.1',
    submit_text_transform: 'uppercase',
    honeypot: true,
    rate_limit: true,
    tile_padding: { top: 0, right: 0, bottom: 0, left: 0 },
  }) ]) ]),
]));

K.emit({
  slug: 'fiori',
  name: 'Fiori',
  tags: ['wedding', 'events', 'florist', 'romantic', 'elegant'],
  description: `Fiori — Wedding & Events. Sage + blush + ivory, Marcellus (display) + Work Sans. Countdown nozze live, story split, details cards, schedule step-timeline verticale, gallery progallery, RSVP form vero. Riproduzione fedele dell'OLOtheme Fiori.`,
  colors: {
    primary: SAGE,
    primary_contrast: WHITE,
    secondary: BLUSH,
    secondary_contrast: WHITE,
    muted: IVORY2,
    muted_contrast: SOFT,
    text: TXT,
    text_muted: SOFT,
    background: IVORY,
    border: LINE,
    link: SAGE,
  },
  css_disp: `"Marcellus", Georgia, serif`,
  css_sans: `"Work Sans", -apple-system, sans-serif`,
  heading_weight: '400',
  heading_line_height: '1.12',
  google_fonts: ['Marcellus', 'Work Sans'],
  logo_variant: 'dark',
  menu: [
    { title: 'Our story', url: '#story' },
    { title: 'Details',   url: '#details' },
    { title: 'Schedule',  url: '#schedule' },
    { title: 'RSVP',      url: '#rsvp' },
  ],
  header: {
    bg: SAGE2,
    text_color: 'rgba(255,255,255,.75)',
    sticky_bg: `rgba(44,51,39,.9)`,
    logo_width: 130,
  },
  footer: {
    bg: SAGE2,
    headColor: WHITE,
    brand: {
      name: 'Marta & Elia',
      tagline: '12 September 2026 · Villa Serbelloni, Lago di Como',
    },
    columns: [
      { title: 'The day',  links: ['Our story', 'Details', 'Schedule', 'RSVP'] },
      { title: 'Venue',    links: ['Villa Serbelloni', 'Getting there', 'Accommodation'] },
      { title: 'Contact',  links: ['marta@esempio.it', 'elia@esempio.it'] },
    ],
    bottom: {
      left: '12 September 2026 · Lago di Como',
      right: 'An OLOtheme demo · Built with OLObuild',
    },
  },
  cursor: false,
}, home);
