export default {
  type: 'authorbox',
  name: 'Author Box',
  icon: 'dashicons-admin-users',
  category: 'dynamic',
  defaults: {
    layout: 'horizontal',
    avatar_size: '80',
    show_avatar: true,
    show_name: true,
    show_bio: true,
    show_role: false,
    show_post_count: false,
    show_website: false,
    name_tag: 'h3',
    name_color: '',
    name_size: '20',
    name_weight: '700',
    bio_color: '',
    bio_size: '14',
    role_color: '',
    role_size: '13',
    link_color: '',
    count_color: '',
    background_color: '',
    border_radius: '8',
    padding: '20',
    avatar_border_radius: '50',
    avatar_border_width: '0',
    avatar_border_color: '',
    border_width: '0',
    border_color: '',
    gap: '16',
    text_align: 'left',
  },
  fields: [
    { type: 'separator', label: 'Contenuto' },
    { key: 'show_avatar', label: 'Mostra avatar', type: 'toggle' },
    { key: 'show_name', label: 'Mostra nome', type: 'toggle' },
    { key: 'show_bio', label: 'Mostra biografia', type: 'toggle' },
    { key: 'show_role', label: 'Mostra ruolo', type: 'toggle' },
    { key: 'show_post_count', label: 'Mostra conteggio articoli', type: 'toggle' },
    { key: 'show_website', label: 'Mostra sito web', type: 'toggle' },

    { type: 'separator', label: 'Layout' },
    { key: 'layout', label: 'Layout', type: 'select', options: [
      { value: 'horizontal', label: 'Orizzontale' },
      { value: 'vertical', label: 'Verticale' },
    ]},
    { key: 'name_tag', label: 'Tag nome', type: 'select', options: [
      { value: 'h3', label: 'H3' },
      { value: 'h4', label: 'H4' },
      { value: 'h5', label: 'H5' },
      { value: 'div', label: 'Div' },
    ]},
    { key: 'text_align', label: 'Allineamento testo', type: 'select', options: [
      { value: 'left', label: 'Sinistra' },
      { value: 'center', label: 'Centro' },
      { value: 'right', label: 'Destra' },
    ]},
    { key: 'gap', label: 'Gap (px)', type: 'range', min: 8, max: 40, step: 4 },

    { type: 'separator', label: 'Avatar' },
    { key: 'avatar_size', label: 'Dimensione avatar (px)', type: 'range', min: 40, max: 160, step: 8,
      condition: { field: 'show_avatar', value: true } },
    { key: 'avatar_border_radius', label: 'Raggio bordo avatar (%)', type: 'border-radius',
      condition: { field: 'show_avatar', value: true } },
    { key: 'avatar_border_width', label: 'Bordo avatar (px)', type: 'range', min: 0, max: 6, step: 1,
      condition: { field: 'show_avatar', value: true } },
    { key: 'avatar_border_color', label: 'Colore bordo avatar', type: 'color',
      condition: { field: 'avatar_border_width', operator: '>', value: '0' } },

    { type: 'separator', label: 'Tipografia' },
    { key: 'name_size', label: 'Dim. nome (px)', type: 'range', min: 14, max: 32, step: 1 },
    { key: 'name_weight', label: 'Peso nome', type: 'select', options: [
      { value: '400', label: 'Normale' },
      { value: '500', label: 'Medio' },
      { value: '600', label: 'Semi-grassetto' },
      { value: '700', label: 'Grassetto' },
    ]},
    { key: 'bio_size', label: 'Dim. biografia (px)', type: 'range', min: 11, max: 18, step: 1 },
    { key: 'role_size', label: 'Dim. ruolo (px)', type: 'range', min: 10, max: 18, step: 1 },

    { type: 'separator', label: 'Colori' },
    { key: 'name_color', label: 'Colore nome', type: 'color' },
    { key: 'bio_color', label: 'Colore biografia', type: 'color' },
    { key: 'role_color', label: 'Colore ruolo', type: 'color' },
    { key: 'link_color', label: 'Colore link', type: 'color' },
    { key: 'count_color', label: 'Colore conteggio', type: 'color' },
    { key: 'background_color', label: 'Sfondo', type: 'color' },

    { type: 'separator', label: 'Aspetto' },
    { key: 'padding', label: 'Padding (px)', type: 'range', min: 0, max: 48, step: 4 },
    { key: 'border_radius', label: 'Raggio bordi (px)', type: 'border-radius' },
    { key: 'border_width', label: 'Bordo (px)', type: 'range', min: 0, max: 5, step: 1 },
    { key: 'border_color', label: 'Colore bordo', type: 'color',
      condition: { field: 'border_width', operator: '>', value: '0' } },
  ],
};
