export default {
  type: 'blendtext',
  name: 'Blend Text',
  icon: 'dashicons-editor-textcolor',
  category: 'creative',
  defaults: {
    text: 'BLEND',
    tag: 'div',
    font_size: '120',
    font_size_tablet: '80',
    font_size_mobile: '50',
    font_weight: '900',
    font_family: '',
    text_transform: 'uppercase',
    letter_spacing: '5',
    line_height: '1',
    text_align: 'center',
    text_color: '#ffffff',
    blend_mode: 'difference',
    padding_top: '40',
    padding_bottom: '40',
    padding_left: '20',
    padding_right: '20',
  },
  fields: [
    { key: 'text', label: 'Testo', type: 'text' },
    { key: 'tag', label: 'Tag HTML', type: 'select', options: [
      { value: 'div', label: 'Div' },
      { value: 'h1', label: 'H1' },
      { value: 'h2', label: 'H2' },
      { value: 'h3', label: 'H3' },
      { value: 'h4', label: 'H4' },
      { value: 'p', label: 'Paragrafo' },
    ]},
    { key: 'blend_mode', label: 'Blend Mode', type: 'select', options: [
      { value: 'normal', label: 'Normale' },
      { value: 'multiply', label: 'Moltiplica' },
      { value: 'screen', label: 'Schermo' },
      { value: 'overlay', label: 'Sovrapposizione' },
      { value: 'darken', label: 'Scurisci' },
      { value: 'lighten', label: 'Schiarisci' },
      { value: 'color-dodge', label: 'Color Dodge' },
      { value: 'color-burn', label: 'Color Burn' },
      { value: 'hard-light', label: 'Hard Light' },
      { value: 'soft-light', label: 'Soft Light' },
      { value: 'difference', label: 'Differenza' },
      { value: 'exclusion', label: 'Esclusione' },
      { value: 'hue', label: 'Tonalità' },
      { value: 'saturation', label: 'Saturazione' },
      { value: 'color', label: 'Colore' },
      { value: 'luminosity', label: 'Luminosità' },
    ]},
    { key: 'text_color', label: 'Colore testo', type: 'color' },
    { type: 'separator', label: 'Tipografia' },
    { key: 'font_size', label: 'Dimensione (px)', type: 'range', min: 12, max: 300, step: 1, responsive: true },
    { key: 'font_weight', label: 'Peso', type: 'select', options: [
      { value: '100', label: '100 Thin' },
      { value: '200', label: '200 Extra Light' },
      { value: '300', label: '300 Light' },
      { value: '400', label: '400 Regular' },
      { value: '500', label: '500 Medium' },
      { value: '600', label: '600 Semi Bold' },
      { value: '700', label: '700 Bold' },
      { value: '800', label: '800 Extra Bold' },
      { value: '900', label: '900 Black' },
    ]},
    { key: 'font_family', label: 'Font', type: 'font-family' },
    { key: 'text_transform', label: 'Trasformazione', type: 'select', options: [
      { value: 'none', label: 'Nessuna' },
      { value: 'uppercase', label: 'MAIUSCOLO' },
      { value: 'lowercase', label: 'minuscolo' },
      { value: 'capitalize', label: 'Capitalizza' },
    ]},
    { key: 'letter_spacing', label: 'Spaziatura lettere (px)', type: 'range', min: -5, max: 30, step: 1 },
    { key: 'line_height', label: 'Altezza riga', type: 'range', min: 0.5, max: 3, step: 0.05 },
    { key: 'text_align', label: 'Allineamento', type: 'select', responsive: true, options: [
      { value: 'left', label: 'Sinistra' },
      { value: 'center', label: 'Centro' },
      { value: 'right', label: 'Destra' },
    ]},
    { type: 'separator', label: 'Spaziatura' },
    { key: 'padding_top', label: 'Padding sopra (px)', type: 'range', min: 0, max: 200, step: 5 },
    { key: 'padding_bottom', label: 'Padding sotto (px)', type: 'range', min: 0, max: 200, step: 5 },
    { key: 'padding_left', label: 'Padding sinistra (px)', type: 'range', min: 0, max: 200, step: 5 },
    { key: 'padding_right', label: 'Padding destra (px)', type: 'range', min: 0, max: 200, step: 5 },
  ],
};
