export default {
  type: 'countdown',
  name: 'Conto alla rovescia',
  icon: 'dashicons-clock',
  category: 'content',
  defaults: {
    countdown_style: 'custom',
    target_date: '2026-12-31T23:59',
    show_days: true,
    show_hours: true,
    show_minutes: true,
    show_seconds: true,
    expired_message: 'L\'evento è iniziato!',
    label_days: 'Giorni',
    label_hours: 'Ore',
    label_minutes: 'Minuti',
    label_seconds: 'Secondi',
    separator: ':',
    bg_color: '#111827',
    text_color: '#F3F4F6',
    accent_color: '#6366F1',
    number_font_size: '48',
    number_font_weight: '700',
    label_font_size: '12',
    label_font_weight: '500',
    separator_font_size: '32',
    item_min_width: '70',
    padding: '32',
  },
  fields: [
    { key: 'countdown_style', label: 'Stile', type: 'select', options: [
      { value: 'custom', label: 'Personalizzato' },
      { value: 'uikit', label: 'UIkit nativo' },
    ]},
    { key: 'target_date', label: 'Data obiettivo', type: 'text' },
    { type: 'separator', label: 'Unità' },
    { key: 'show_days', label: 'Mostra giorni', type: 'toggle' },
    { key: 'show_hours', label: 'Mostra ore', type: 'toggle' },
    { key: 'show_minutes', label: 'Mostra minuti', type: 'toggle' },
    { key: 'show_seconds', label: 'Mostra secondi', type: 'toggle' },
    { key: 'expired_message', label: 'Messaggio scaduto', type: 'text' },
    { type: 'separator', label: 'Etichette' },
    { key: 'label_days', label: 'Etichetta giorni', type: 'text' },
    { key: 'label_hours', label: 'Etichetta ore', type: 'text' },
    { key: 'label_minutes', label: 'Etichetta minuti', type: 'text' },
    { key: 'label_seconds', label: 'Etichetta secondi', type: 'text' },
    { key: 'separator', label: 'Separatore', type: 'text' },
    { type: 'separator', label: 'Tipografia' },
    { key: 'number_font_size', label: 'Dim. numeri (px)', type: 'range', min: 16, max: 120, step: 2 },
    { key: 'number_font_weight', label: 'Peso numeri', type: 'select', options: [
      { value: '400', label: 'Normale' },
      { value: '500', label: 'Medio' },
      { value: '600', label: 'Semi-grassetto' },
      { value: '700', label: 'Grassetto' },
      { value: '800', label: 'Extra-grassetto' },
      { value: '900', label: 'Nero' },
    ]},
    { key: 'label_font_size', label: 'Dim. etichette (px)', type: 'range', min: 8, max: 24, step: 1 },
    { key: 'label_font_weight', label: 'Peso etichette', type: 'select', options: [
      { value: '400', label: 'Normale' },
      { value: '500', label: 'Medio' },
      { value: '600', label: 'Semi-grassetto' },
      { value: '700', label: 'Grassetto' },
    ]},
    { key: 'separator_font_size', label: 'Dim. separatore (px)', type: 'range', min: 12, max: 80, step: 2 },
    { key: 'item_min_width', label: 'Largh. min elemento (px)', type: 'range', min: 40, max: 160, step: 5 },
    { key: 'padding', label: 'Padding (px)', type: 'range', min: 8, max: 64, step: 4 },
    { type: 'separator', label: 'Colori' },
    { key: 'bg_color', label: 'Colore sfondo', type: 'color' },
    { key: 'text_color', label: 'Colore testo', type: 'color' },
    { key: 'accent_color', label: 'Colore accento', type: 'color' },
  ],
};
