import { shadowField } from './_shared.js';

export default {
  type: 'countdown',
  name: 'Conto alla rovescia',
  icon: 'dashicons-clock',
  category: 'marketing',
  defaults: {
    countdown_style: 'custom',
    countdown_type: 'date',
    evergreen_hours: '0',
    evergreen_minutes: '30',
    evergreen_loop: false,
    expire_action: 'none',
    expire_redirect_url: '',
    expire_message: 'Tempo scaduto!',
    display_mode: 'block',
    target_date: '2026-12-31T23:59',
    show_days: true,
    show_hours: true,
    show_minutes: true,
    show_seconds: true,
    expired_message: 'L\'evento è iniziato!',
    label_days: 'Giorni',
    label_hours: 'Ore',
    label_minutes: 'Minuti',
    label_seconds: 'Secondi',
    separator: ':',
    bg_color: '',
    text_color: '',
    accent_color: '',
    number_font_size: '48',
    number_font_weight: '700',
    label_font_size: '12',
    label_font_weight: '500',
    separator_font_size: '32',
    item_min_width: '70',
    padding: '32',
    shadow: 'none',
  },
  fields: [
    { key: 'countdown_style', label: 'Stile', type: 'select', options: [
      { value: 'custom', label: 'Personalizzato' },
      { value: 'uikit', label: 'UIkit nativo' },
    ]},
    { key: 'countdown_type', label: 'Tipo countdown', type: 'select', options: [
      { value: 'date', label: 'Data fissa' },
      { value: 'evergreen', label: 'Evergreen (per visitatore)' },
    ]},
    { key: 'target_date', label: 'Data obiettivo', type: 'datetime',
      condition: { field: 'countdown_type', operator: '==', value: 'date' } },
    { key: 'evergreen_hours', label: 'Ore evergreen', type: 'range', min: 0, max: 72, step: 1,
      condition: { field: 'countdown_type', operator: '==', value: 'evergreen' } },
    { key: 'evergreen_minutes', label: 'Minuti evergreen', type: 'range', min: 0, max: 59, step: 1,
      condition: { field: 'countdown_type', operator: '==', value: 'evergreen' } },
    { key: 'evergreen_loop', label: 'Ricomincia automaticamente', type: 'toggle',
      condition: { field: 'countdown_type', operator: '==', value: 'evergreen' } },
    { type: 'separator', label: 'Azione alla scadenza' },
    { key: 'expire_action', label: 'Azione', type: 'select', options: [
      { value: 'none', label: 'Nessuna (mostra zero)' },
      { value: 'hide', label: 'Nascondi countdown' },
      { value: 'message', label: 'Mostra messaggio' },
      { value: 'redirect', label: 'Reindirizza' },
    ]},
    { key: 'expire_message', label: 'Messaggio scadenza', type: 'text',
      condition: { field: 'expire_action', operator: '==', value: 'message' } },
    { key: 'expire_redirect_url', label: 'URL reindirizzamento', type: 'text',
      condition: { field: 'expire_action', operator: '==', value: 'redirect' } },
    { key: 'display_mode', label: 'Visualizzazione', type: 'select', options: [
      { value: 'block', label: 'Blocco (verticale)' },
      { value: 'inline', label: 'Inline (una riga)' },
    ]},
    { type: 'separator', label: 'Unità' },
    { key: 'show_days', label: 'Mostra giorni', type: 'toggle' },
    { key: 'show_hours', label: 'Mostra ore', type: 'toggle' },
    { key: 'show_minutes', label: 'Mostra minuti', type: 'toggle' },
    { key: 'show_seconds', label: 'Mostra secondi', type: 'toggle' },
    { key: 'expired_message', label: 'Messaggio scaduto', type: 'text' },
    { type: 'separator', label: 'Etichette' },
    { key: 'label_days', label: 'Etichetta giorni', type: 'text' },
    { key: 'label_hours', label: 'Etichetta ore', type: 'text' },
    { key: 'label_minutes', label: 'Etichetta minuti', type: 'text' },
    { key: 'label_seconds', label: 'Etichetta secondi', type: 'text' },
    { key: 'separator', label: 'Separatore', type: 'text' },
    { type: 'separator', label: 'Tipografia' },
    { key: 'number_font_size', label: 'Dim. numeri (px)', type: 'range', min: 16, max: 120, step: 2 },
    { key: 'number_font_weight', label: 'Peso numeri', type: 'select', options: [
      { value: '400', label: 'Normale' },
      { value: '500', label: 'Medio' },
      { value: '600', label: 'Semi-grassetto' },
      { value: '700', label: 'Grassetto' },
      { value: '800', label: 'Extra-grassetto' },
      { value: '900', label: 'Nero' },
    ]},
    { key: 'label_font_size', label: 'Dim. etichette (px)', type: 'range', min: 8, max: 24, step: 1 },
    { key: 'label_font_weight', label: 'Peso etichette', type: 'select', options: [
      { value: '400', label: 'Normale' },
      { value: '500', label: 'Medio' },
      { value: '600', label: 'Semi-grassetto' },
      { value: '700', label: 'Grassetto' },
    ]},
    { key: 'separator_font_size', label: 'Dim. separatore (px)', type: 'range', min: 12, max: 80, step: 2 },
    { key: 'item_min_width', label: 'Largh. min elemento (px)', type: 'range', min: 40, max: 160, step: 5 },
    { key: 'padding', label: 'Padding (px)', type: 'range', min: 8, max: 64, step: 4 },
    { type: 'separator', label: 'Colori' },
    { key: 'bg_color', label: 'Colore sfondo', type: 'color' },
    { key: 'text_color', label: 'Colore testo', type: 'color' },
    { key: 'accent_color', label: 'Colore accento', type: 'color' },
    ...shadowField,
  ],
};
