import { shadowField } from './_shared.js';

export default {
  type: 'desclist',
  name: 'Lista descrittiva',
  icon: 'dashicons-editor-justify',
  category: 'text',
  defaults: {
    items: [
      { id: 'dl-1', term: 'Framework', definition: 'Vue.js 3 con Composition API', icon: 'code' },
      { id: 'dl-2', term: 'Linguaggio', definition: 'PHP 7.4+ con WordPress', icon: 'server' },
      { id: 'dl-3', term: 'Build Tool', definition: 'Vite 5', icon: 'bolt' },
    ],
    layout: 'stacked',
    show_icon: true,
    icon_color: '',
    icon_size: '20',
    term_color: '',
    term_font_size: '15',
    term_font_weight: '600',
    definition_color: '',
    definition_font_size: '14',
    separator: true,
    border_color: '',
    spacing: '16',
    striped: false,
    striped_color: '',
    shadow: 'none',
  },
  fields: [
    { key: 'items', label: 'Elementi', type: 'content-items', supportsDynamic: true,
      itemFields: [
        { key: 'term', label: 'Termine', type: 'text' },
        { key: 'definition', label: 'Definizione', type: 'textarea' },
        { key: 'icon', label: 'Icona', type: 'icon' },
      ],
      newItemDefaults: { term: 'Nuovo termine', definition: 'Definizione.', icon: '' },
      itemLabel: 'Voce',
    },
    { key: 'layout', label: 'Layout', type: 'select', options: [
      { value: 'stacked', label: 'Impilato' },
      { value: 'inline', label: 'In linea' },
      { value: 'grid', label: 'Griglia' },
    ]},
    { type: 'separator', label: 'Icona' },
    { key: 'show_icon', label: 'Mostra icona', type: 'toggle' },
    { key: 'icon_color', label: 'Colore icona', type: 'color' },
    { key: 'icon_size', label: 'Dim. icona (px)', type: 'range', min: 14, max: 32, step: 2 },
    { type: 'separator', label: 'Tipografia' },
    { key: 'term_font_size', label: 'Dim. termine (px)', type: 'range', min: 12, max: 24, step: 1 },
    { key: 'term_font_weight', label: 'Peso termine', type: 'select', options: [
      { value: '400', label: 'Normale' },
      { value: '500', label: 'Medio' },
      { value: '600', label: 'Semi-grassetto' },
      { value: '700', label: 'Grassetto' },
    ]},
    { key: 'definition_font_size', label: 'Dim. definizione (px)', type: 'range', min: 12, max: 20, step: 1 },
    { key: 'spacing', label: 'Spaziatura tra voci (px)', type: 'range', min: 4, max: 32, step: 2 },
    { type: 'separator', label: 'Colori' },
    { key: 'term_color', label: 'Colore termine', type: 'color' },
    { key: 'definition_color', label: 'Colore definizione', type: 'color' },
    { key: 'separator', label: 'Separatore', type: 'toggle' },
    { key: 'border_color', label: 'Colore bordo', type: 'color' },
    { key: 'striped', label: 'Righe alternate', type: 'toggle' },
    { key: 'striped_color', label: 'Colore riga alternata', type: 'color' },
    ...shadowField,
  ],
};
