export default {
  type: 'facebookpage',
  name: 'Facebook Page',
  icon: 'dashicons-facebook',
  category: 'marketing',
  defaults: {
    page_url: '',
    width: '340',
    height: '500',
    tabs: 'timeline',
    show_cover: true,
    show_facepile: true,
    small_header: false,
    adapt_container: true,
    language: 'it_IT',
    alignment: 'center',
  },
  fields: [
    { key: 'page_url', label: 'URL pagina Facebook', type: 'text', placeholder: 'https://www.facebook.com/...' },
    { key: 'width', label: 'Larghezza (px)', type: 'range', min: 180, max: 500, step: 10 },
    { key: 'height', label: 'Altezza (px)', type: 'range', min: 70, max: 1000, step: 10 },
    { key: 'tabs', label: 'Tab (timeline,events,messages)', type: 'text', placeholder: 'timeline' },
    { key: 'show_cover', label: 'Mostra copertina', type: 'toggle' },
    { key: 'show_facepile', label: 'Mostra facce amici', type: 'toggle' },
    { key: 'small_header', label: 'Header compatto', type: 'toggle' },
    { key: 'adapt_container', label: 'Adatta al contenitore', type: 'toggle' },
    { key: 'language', label: 'Lingua SDK', type: 'select', options: [
      { value: 'it_IT', label: 'Italiano' },
      { value: 'en_US', label: 'English' },
      { value: 'de_DE', label: 'Deutsch' },
      { value: 'fr_FR', label: 'Francais' },
      { value: 'es_ES', label: 'Espanol' },
    ]},
    { key: 'alignment', label: 'Allineamento', type: 'select', options: [
      { value: 'left', label: 'Sinistra' },
      { value: 'center', label: 'Centro' },
      { value: 'right', label: 'Destra' },
    ]},
  ],
};
