export default {
  type: 'floatingpanel',
  name: 'Pannello flottante',
  icon: 'dashicons-move',
  category: 'interactive',
  isContainer: true,
  defaults: {
    position: 'fixed',
    placement: 'bottom-right',
    offset_x: '20',
    offset_y: '20',
    custom_top: '',
    custom_left: '',
    custom_bottom: '',
    custom_right: '',
    width: '300',
    height: '',
    z_index: '9999',
    bg_color: '#ffffff',
    border_color: '',
    border_width: '0',
    border_radius: '12',
    shadow: true,
    shadow_color: 'rgba(0,0,0,0.15)',
    shadow_blur: '20',
    shadow_y: '4',
    tile_padding: { top: 20, right: 20, bottom: 20, left: 20 },
    trigger_mode: 'always',
    trigger_icon: 'plus',
    trigger_size: '48',
    trigger_bg: '',
    trigger_color: '#ffffff',
    trigger_radius: '50',
    trigger_shadow: true,
    show_close: true,
    close_color: '#666666',
    close_size: '20',
    close_outside: true,
    animation: 'fade',
    animation_duration: '300',
    visible_desktop: true,
    visible_tablet: true,
    visible_mobile: true,
    layout_direction: 'column',
    layout_gap: '12',
    layout_align: 'stretch',
  },
  fields: [
    // ─── Posizionamento ───
    { type: 'separator', label: 'Posizionamento' },
    {
      key: 'position',
      label: 'Tipo posizione',
      type: 'select',
      options: [
        { value: 'fixed', label: 'Fisso (viewport)' },
        { value: 'absolute', label: 'Assoluto (pagina)' },
        { value: 'sticky', label: 'Appiccicoso' },
      ],
    },
    {
      key: 'placement',
      label: 'Posizione',
      type: 'select',
      options: [
        { value: 'top-left', label: '↖ Alto sinistra' },
        { value: 'top-center', label: '↑ Alto centro' },
        { value: 'top-right', label: '↗ Alto destra' },
        { value: 'center-left', label: '← Centro sinistra' },
        { value: 'center', label: '● Centro' },
        { value: 'center-right', label: '→ Centro destra' },
        { value: 'bottom-left', label: '↙ Basso sinistra' },
        { value: 'bottom-center', label: '↓ Basso centro' },
        { value: 'bottom-right', label: '↘ Basso destra' },
        { value: 'custom', label: '✎ Personalizzato' },
      ],
    },
    { key: 'offset_x', label: 'Offset orizzontale (px)', type: 'range', min: 0, max: 200, step: 5,
      condition: { field: 'placement', value: 'custom', operator: '!=' } },
    { key: 'offset_y', label: 'Offset verticale (px)', type: 'range', min: 0, max: 200, step: 5,
      condition: { field: 'placement', value: 'custom', operator: '!=' } },
    { key: 'custom_top', label: 'Top (px o %)', type: 'text',
      condition: { field: 'placement', value: 'custom' } },
    { key: 'custom_left', label: 'Left (px o %)', type: 'text',
      condition: { field: 'placement', value: 'custom' } },
    { key: 'custom_bottom', label: 'Bottom (px o %)', type: 'text',
      condition: { field: 'placement', value: 'custom' } },
    { key: 'custom_right', label: 'Right (px o %)', type: 'text',
      condition: { field: 'placement', value: 'custom' } },

    { type: 'separator', label: 'Dimensioni' },
    { key: 'width', label: 'Larghezza (px o %)', type: 'text' },
    { key: 'height', label: 'Altezza (vuoto = auto)', type: 'text' },
    { key: 'z_index', label: 'Z-Index', type: 'range', min: 1, max: 99999, step: 1 },

    // ─── Layout figli ───
    { type: 'separator', label: 'Layout contenuto' },
    {
      key: 'layout_direction',
      label: 'Direzione',
      type: 'select',
      options: [
        { value: 'column', label: 'Verticale' },
        { value: 'row', label: 'Orizzontale' },
      ],
    },
    { key: 'layout_gap', label: 'Spaziatura figli (px)', type: 'range', min: 0, max: 40, step: 2 },
    {
      key: 'layout_align',
      label: 'Allineamento figli',
      type: 'select',
      options: [
        { value: 'stretch', label: 'Estendi' },
        { value: 'flex-start', label: 'Inizio' },
        { value: 'center', label: 'Centro' },
        { value: 'flex-end', label: 'Fine' },
      ],
    },

    // ─── Aspetto ───
    { type: 'separator', label: 'Aspetto' },
    { key: 'bg_color', label: 'Sfondo', type: 'color' },
    { key: 'border_color', label: 'Colore bordo', type: 'color' },
    { key: 'border_width', label: 'Spessore bordo (px)', type: 'range', min: 0, max: 10, step: 1 },
    { key: 'border_radius', label: 'Arrotondamento (px)', type: 'border-radius' },
    { key: 'tile_padding', label: 'Padding (px)', type: 'spacing', max: 60 },
    { key: 'shadow', label: 'Ombra', type: 'toggle' },
    { key: 'shadow_color', label: 'Colore ombra', type: 'color',
      condition: { field: 'shadow', value: true } },
    { key: 'shadow_blur', label: 'Sfocatura ombra (px)', type: 'range', min: 0, max: 60, step: 2,
      condition: { field: 'shadow', value: true } },
    { key: 'shadow_y', label: 'Offset Y ombra (px)', type: 'range', min: 0, max: 30, step: 1,
      condition: { field: 'shadow', value: true } },

    // ─── Trigger ───
    { type: 'separator', label: 'Visibilità' },
    {
      key: 'trigger_mode',
      label: 'Modalità',
      type: 'select',
      options: [
        { value: 'always', label: 'Sempre visibile' },
        { value: 'button', label: 'Con pulsante trigger' },
      ],
    },
    {
      key: 'trigger_icon',
      label: 'Icona trigger',
      type: 'select',
      options: [
        { value: 'plus', label: '+ Plus' },
        { value: 'chat', label: '💬 Chat' },
        { value: 'info', label: 'ℹ Info' },
        { value: 'menu', label: '☰ Menu' },
        { value: 'arrow-up', label: '↑ Freccia su' },
        { value: 'star', label: '★ Stella' },
        { value: 'heart', label: '♥ Cuore' },
        { value: 'settings', label: '⚙ Impostazioni' },
      ],
      condition: { field: 'trigger_mode', value: 'button' },
    },
    { key: 'trigger_size', label: 'Dimensione trigger (px)', type: 'range', min: 32, max: 80, step: 2,
      condition: { field: 'trigger_mode', value: 'button' } },
    { key: 'trigger_bg', label: 'Sfondo trigger', type: 'color',
      condition: { field: 'trigger_mode', value: 'button' } },
    { key: 'trigger_color', label: 'Colore icona trigger', type: 'color',
      condition: { field: 'trigger_mode', value: 'button' } },
    { key: 'trigger_radius', label: 'Arrotondamento trigger (%)', type: 'range', min: 0, max: 50, step: 5,
      condition: { field: 'trigger_mode', value: 'button' } },
    { key: 'trigger_shadow', label: 'Ombra trigger', type: 'toggle',
      condition: { field: 'trigger_mode', value: 'button' } },

    // ─── Chiusura ───
    { type: 'separator', label: 'Chiusura' },
    { key: 'show_close', label: 'Mostra pulsante chiudi', type: 'toggle',
      condition: { field: 'trigger_mode', value: 'button' } },
    { key: 'close_color', label: 'Colore X', type: 'color',
      condition: { field: 'show_close', value: true } },
    { key: 'close_size', label: 'Dimensione X (px)', type: 'range', min: 12, max: 32, step: 2,
      condition: { field: 'show_close', value: true } },
    { key: 'close_outside', label: 'Chiudi cliccando fuori', type: 'toggle',
      condition: { field: 'trigger_mode', value: 'button' } },

    // ─── Animazione ───
    { type: 'separator', label: 'Animazione' },
    {
      key: 'animation',
      label: 'Animazione apertura',
      type: 'select',
      options: [
        { value: 'fade', label: 'Dissolvenza' },
        { value: 'slide-up', label: 'Scorrimento dal basso' },
        { value: 'slide-down', label: "Scorrimento dall'alto" },
        { value: 'slide-left', label: 'Scorrimento da destra' },
        { value: 'slide-right', label: 'Scorrimento da sinistra' },
        { value: 'scale', label: 'Scala' },
      ],
      condition: { field: 'trigger_mode', value: 'button' },
    },
    { key: 'animation_duration', label: 'Durata (ms)', type: 'range', min: 100, max: 800, step: 50,
      condition: { field: 'trigger_mode', value: 'button' } },

    // ─── Responsive ───
    { type: 'separator', label: 'Responsive' },
    { key: 'visible_desktop', label: 'Visibile su desktop', type: 'toggle' },
    { key: 'visible_tablet', label: 'Visibile su tablet', type: 'toggle' },
    { key: 'visible_mobile', label: 'Visibile su mobile', type: 'toggle' },
  ],
};
