export default {
  type: 'headline',
  name: 'Titolo',
  icon: 'dashicons-heading',
  category: 'content',
  defaults: {
    heading: 'Titolo sezione',
    subtitle: 'Un breve sottotitolo va qui',
    tag: 'h2',
    alignment: 'center',
    decoration: 'line',
    decoration_color: '#6366F1',
    heading_color: '#F3F4F6',
    subtitle_color: '#9CA3AF',
    heading_size: 'lg',
  },
  fields: [
    { key: 'heading', label: 'Titolo', type: 'editor', mode: 'inline' },
    { key: 'subtitle', label: 'Sottotitolo', type: 'editor', mode: 'inline' },
    { key: 'tag', label: 'Tag HTML', type: 'select', options: [
      { value: 'h1', label: 'H1' },
      { value: 'h2', label: 'H2' },
      { value: 'h3', label: 'H3' },
      { value: 'h4', label: 'H4' },
      { value: 'h5', label: 'H5' },
      { value: 'h6', label: 'H6' },
      { value: 'p', label: 'Paragrafo' },
    ]},
    { key: 'alignment', label: 'Allineamento', type: 'select', options: [
      { value: 'left', label: 'Sinistra' },
      { value: 'center', label: 'Centro' },
      { value: 'right', label: 'Destra' },
    ]},
    { key: 'decoration', label: 'Decorazione', type: 'select', options: [
      { value: 'none', label: 'Nessuna' },
      { value: 'line', label: 'Linea' },
      { value: 'dot', label: 'Punto' },
      { value: 'star', label: 'Stella' },
    ]},
    { key: 'decoration_color', label: 'Colore decorazione', type: 'color' },
    { key: 'heading_color', label: 'Colore titolo', type: 'color' },
    { key: 'subtitle_color', label: 'Colore sottotitolo', type: 'color' },
    { key: 'heading_size', label: 'Dim. titolo', type: 'select', options: [
      { value: 'sm', label: 'Piccolo' },
      { value: 'md', label: 'Medio' },
      { value: 'lg', label: 'Grande' },
      { value: 'xl', label: 'Extra grande' },
    ]},
  ],
};
