import { shadowField } from './_shared.js';

export default {
  type: 'image',
  name: 'Immagine',
  icon: 'dashicons-format-image',
  category: 'essential',
  defaults: {
    image_url: '',
    hover_image: '',
    hover_video: '',
    alt_text: '',
    caption: '',
    link_url: '',
    link_target: '_self',
    object_fit: 'cover',
    height: '300px',
    // CSS Filters
    filter_blur: '0',
    filter_brightness: '100',
    filter_contrast: '100',
    filter_saturate: '100',
    filter_grayscale: '0',
    filter_sepia: '0',
    // Hover filters
    hover_filter_blur: '',
    hover_filter_brightness: '',
    hover_filter_contrast: '',
    hover_filter_saturate: '',
    hover_filter_grayscale: '',
    hover_filter_sepia: '',
    // Hover animation
    hover_animation: 'none',
    // Lightbox
    lightbox: false,
    shadow: 'none',
  },
  fields: [
    { key: 'image_url', label: 'Immagine', type: 'image' },
    { key: 'hover_image', label: 'Immagine hover', type: 'image' },
    { key: 'hover_video', label: 'Video hover', type: 'media' },
    { key: 'alt_text', label: 'Testo alternativo', type: 'text', aiGenerate: 'alt' },
    { key: 'caption', label: 'Didascalia', type: 'text' },
    { key: 'link_url', label: 'URL link', type: 'text' },
    { key: 'link_target', label: 'Apri in', type: 'select', options: [
      { value: '_self', label: 'Stessa finestra' },
      { value: '_blank', label: 'Nuova scheda' },
    ]},
    { key: 'object_fit', label: 'Adattamento', type: 'select', options: [
      { value: 'cover', label: 'Riempi' },
      { value: 'contain', label: 'Contieni' },
      { value: 'fill', label: 'Riempi (deforma)' },
    ]},
    { key: 'height', label: 'Altezza', type: 'text', responsive: true },
    { type: 'separator', label: 'Filtri CSS' },
    { key: 'filter_blur', label: 'Sfocatura (px)', type: 'range', min: 0, max: 20, step: 1 },
    { key: 'filter_brightness', label: 'Luminosità (%)', type: 'range', min: 0, max: 200, step: 5 },
    { key: 'filter_contrast', label: 'Contrasto (%)', type: 'range', min: 0, max: 200, step: 5 },
    { key: 'filter_saturate', label: 'Saturazione (%)', type: 'range', min: 0, max: 200, step: 5 },
    { key: 'filter_grayscale', label: 'Scala di grigi (%)', type: 'range', min: 0, max: 100, step: 5 },
    { key: 'filter_sepia', label: 'Seppia (%)', type: 'range', min: 0, max: 100, step: 5 },
    { type: 'separator', label: 'Filtri hover (vuoto = invariato)' },
    { key: 'hover_filter_blur', label: 'Sfocatura hover (px)', type: 'range', min: 0, max: 20, step: 1 },
    { key: 'hover_filter_brightness', label: 'Luminosità hover (%)', type: 'range', min: 0, max: 200, step: 5 },
    { key: 'hover_filter_contrast', label: 'Contrasto hover (%)', type: 'range', min: 0, max: 200, step: 5 },
    { key: 'hover_filter_saturate', label: 'Saturazione hover (%)', type: 'range', min: 0, max: 200, step: 5 },
    { key: 'hover_filter_grayscale', label: 'Scala di grigi hover (%)', type: 'range', min: 0, max: 100, step: 5 },
    { key: 'hover_filter_sepia', label: 'Seppia hover (%)', type: 'range', min: 0, max: 100, step: 5 },
    { type: 'separator', label: 'Animazione hover' },
    { key: 'hover_animation', label: 'Animazione hover', type: 'select', options: [
      { value: 'none', label: 'Nessuna' },
      { value: 'zoom-in', label: 'Zoom in' },
      { value: 'zoom-out', label: 'Zoom out' },
      { value: 'slide-up', label: 'Scorrimento su' },
      { value: 'rotate-cw', label: 'Rotazione oraria' },
      { value: 'rotate-ccw', label: 'Rotazione antioraria' },
      { value: 'blur-in', label: 'Sfocatura → nitido' },
    ]},
    { key: 'lightbox', label: 'Lightbox al click', type: 'toggle' },
    ...shadowField,
  ],
};
