export default {
  type: 'langswitcher',
  name: 'Selettore lingua',
  icon: 'dashicons-translation',
  category: 'header',
  defaults: {
    style: 'flags',
    flag_shape: 'circle',
    flag_size: 24,
    show_label: false,
    label_format: 'name',
    layout: 'inline',
    floating_pos: 'bottom-right',
    gap: 8,
    active_bg: '#6366F1',
    active_color: '#ffffff',
    bg: '#ffffff',
    color: '#374151',
    border_color: '#e5e7eb',
    border_radius: 8,
    show_dropdown_arrow: true,
  },
  fields: [
    { key: 'style', label: 'Stile', type: 'select', options: [
      { value: 'flags', label: 'Bandiere' },
      { value: 'codes', label: 'Codici (IT/EN/DE)' },
      { value: 'names', label: 'Nomi (Italiano/English)' },
      { value: 'flags_text', label: 'Bandiere + codice' },
    ]},
    { key: 'layout', label: 'Layout', type: 'select', options: [
      { value: 'inline', label: 'Inline (dentro header/footer)' },
      { value: 'dropdown', label: 'Dropdown' },
      { value: 'floating', label: 'Fluttuante (fisso su schermo)' },
    ]},
    { key: 'floating_pos', label: 'Posizione fluttuante', type: 'select', options: [
      { value: 'bottom-right', label: 'Basso destra' },
      { value: 'bottom-left', label: 'Basso sinistra' },
      { value: 'top-right', label: 'Alto destra' },
      { value: 'top-left', label: 'Alto sinistra' },
      { value: 'middle-right', label: 'Centro destra' },
      { value: 'middle-left', label: 'Centro sinistra' },
    ], condition: { field: 'layout', value: 'floating' } },
    { key: 'flag_shape', label: 'Forma bandiere', type: 'select', options: [
      { value: 'circle', label: 'Cerchio' },
      { value: 'rounded', label: 'Rettangolo arrotondato' },
    ], condition: { field: 'style', value: ['flags', 'flags_text'] } },
    { key: 'flag_size', label: 'Dimensione bandiere (px)', type: 'range', min: 16, max: 48,
      condition: { field: 'style', value: ['flags', 'flags_text'] } },
    { key: 'show_label', label: 'Mostra etichetta sotto', type: 'toggle',
      condition: { field: 'style', value: 'flags' } },
    { key: 'label_format', label: 'Formato etichetta', type: 'select', options: [
      { value: 'name', label: 'Nome completo' },
      { value: 'code', label: 'Codice (IT/EN)' },
    ], condition: { field: 'show_label', value: true } },
    { key: 'gap', label: 'Spazio tra elementi (px)', type: 'range', min: 0, max: 24 },
    { key: 'show_dropdown_arrow', label: 'Freccia dropdown', type: 'toggle',
      condition: { field: 'layout', value: 'dropdown' } },

    // Colori
    { key: '_sep_colors', label: 'Colori', type: 'separator' },
    { key: 'active_bg', label: 'Sfondo lingua attiva', type: 'color' },
    { key: 'active_color', label: 'Testo lingua attiva', type: 'color' },
    { key: 'bg', label: 'Sfondo', type: 'color' },
    { key: 'color', label: 'Testo', type: 'color' },
    { key: 'border_color', label: 'Bordo', type: 'color' },
    { key: 'border_radius', label: 'Raggio bordo (px)', type: 'range', min: 0, max: 24 },
  ],
};
