import { shadowField } from './_shared.js';

export default {
  type: 'offcanvas',
  name: 'Off-Canvas',
  icon: 'dashicons-slides',
  category: 'interactive',
  defaults: {
    /* ─── Pannello ─── */
    mode: 'right',
    panel_width: '320',
    panel_width_unit: 'px',
    bg_color: '#1F2937',
    text_color: '#FFFFFF',
    backdrop_blur: false,
    backdrop_blur_amount: '8',
    overlay: true,
    overlay_color: '#000000',
    overlay_opacity: '50',
    content_align: 'top',

    /* ─── Contenuto ─── */
    template_id: 0,

    /* ─── Header pannello ─── */
    show_logo: false,
    logo_url: '',
    logo_height: '36',

    /* ─── Chiusura ─── */
    close_button: true,
    close_style: 'x',
    close_color: '#FFFFFF',
    close_bg: '',
    close_size: '28',
    close_position: 'top-right',
    close_offset_x: 16,
    close_offset_y: 16,
    close_border_radius: 50,
    close_outside: true,

    /* ─── Trigger hamburger ─── */
    show_trigger: true,
    trigger_style: 'bars',
    trigger_color: '',
    trigger_size: '24',
    trigger_bg: '',
    trigger_position: 'inline',
    trigger_offset_x: 16,
    trigger_offset_y: 16,
    trigger_border_radius: 6,
    trigger_selector: '',

    /* ─── Animazione ─── */
    transition: 'slide',
    transition_duration: '350',
    stagger_items: false,
    stagger_delay: '60',

    shadow: 'none',
  },
  fields: [
    { type: 'separator', label: 'Pannello' },
    { key: 'mode', label: 'Modalità', type: 'select', options: [
      { value: 'left', label: 'Offcanvas Sinistra' },
      { value: 'right', label: 'Offcanvas Destra' },
      { value: 'fullscreen', label: 'Fullscreen' },
    ]},
    { key: 'panel_width', label: 'Larghezza pannello', type: 'range', min: 200, max: 800, step: 10,
      show: s => s.mode !== 'fullscreen' },
    { key: 'panel_width_unit', label: 'Unità', type: 'select',
      show: s => s.mode !== 'fullscreen',
      options: [
        { value: 'px', label: 'px' },
        { value: '%', label: '%' },
        { value: 'vw', label: 'vw' },
      ]},
    { key: 'bg_color', label: 'Sfondo', type: 'color' },
    { key: 'text_color', label: 'Colore testo', type: 'color' },
    { key: 'content_align', label: 'Allineamento contenuto', type: 'select', options: [
      { value: 'top', label: 'In alto' },
      { value: 'center', label: 'Centrato' },
      { value: 'bottom', label: 'In basso' },
      { value: 'between', label: 'Distribuito' },
    ]},

    { type: 'separator', label: 'Contenuto' },
    { key: 'template_id', label: 'Template', type: 'select', optionsSource: 'templates' },

    { type: 'separator', label: 'Logo nel pannello' },
    { key: 'show_logo', label: 'Mostra logo', type: 'toggle' },
    { key: 'logo_url', label: 'Immagine logo', type: 'media',
      show: s => s.show_logo },
    { key: 'logo_height', label: 'Altezza logo (px)', type: 'range', min: 20, max: 80, step: 2,
      show: s => s.show_logo },

    { type: 'separator', label: 'Overlay / Backdrop' },
    { key: 'overlay', label: 'Overlay scuro', type: 'toggle' },
    { key: 'overlay_color', label: 'Colore overlay', type: 'color',
      show: s => s.overlay },
    { key: 'overlay_opacity', label: 'Opacità (%)', type: 'range', min: 0, max: 100, step: 5,
      show: s => s.overlay },
    { key: 'backdrop_blur', label: 'Sfocatura sfondo', type: 'toggle' },
    { key: 'backdrop_blur_amount', label: 'Intensità blur (px)', type: 'range', min: 2, max: 20, step: 1,
      show: s => s.backdrop_blur },

    { type: 'separator', label: 'Pulsante chiudi' },
    { key: 'close_button', label: 'Mostra pulsante chiudi', type: 'toggle' },
    { key: 'close_style', label: 'Stile', type: 'select',
      show: s => s.close_button,
      options: [
        { value: 'x', label: '✕ Croce' },
        { value: 'x-circle', label: '⊗ Croce cerchiata' },
        { value: 'arrow-left', label: '← Freccia sinistra' },
        { value: 'arrow-right', label: '→ Freccia destra' },
        { value: 'chevron-left', label: '‹ Chevron sinistra' },
        { value: 'chevron-right', label: '› Chevron destra' },
        { value: 'text', label: 'CHIUDI (testo)' },
      ]},
    { key: 'close_color', label: 'Colore', type: 'color',
      show: s => s.close_button },
    { key: 'close_bg', label: 'Sfondo', type: 'color',
      show: s => s.close_button },
    { key: 'close_size', label: 'Dimensione (px)', type: 'range', min: 16, max: 48, step: 2,
      show: s => s.close_button },
    { key: 'close_position', label: 'Posizione', type: 'select',
      show: s => s.close_button,
      options: [
        { value: 'top-left', label: 'Alto sinistra' },
        { value: 'top-right', label: 'Alto destra' },
        { value: 'top-center', label: 'Alto centro' },
        { value: 'bottom-right', label: 'Basso destra' },
        { value: 'bottom-left', label: 'Basso sinistra' },
      ]},
    { key: 'close_offset_x', label: 'Offset orizzontale (px)', type: 'range', min: 4, max: 40, step: 2,
      show: s => s.close_button },
    { key: 'close_offset_y', label: 'Offset verticale (px)', type: 'range', min: 4, max: 40, step: 2,
      show: s => s.close_button },
    { key: 'close_border_radius', label: 'Raggio bordo (%)', type: 'range', min: 0, max: 50, step: 5,
      show: s => s.close_button && s.close_bg },
    { key: 'close_outside', label: 'Chiudi cliccando fuori', type: 'toggle' },

    { type: 'separator', label: 'Trigger (hamburger)' },
    { key: 'show_trigger', label: 'Mostra pulsante', type: 'toggle' },
    { key: 'trigger_style', label: 'Stile icona', type: 'select',
      show: s => s.show_trigger,
      options: [
        { value: 'bars', label: '☰ Tre linee' },
        { value: 'dots', label: '⋮ Tre punti' },
        { value: 'grid', label: '⊞ Griglia' },
        { value: 'arrow', label: '→ Freccia' },
      ]},
    { key: 'trigger_color', label: 'Colore', type: 'color',
      show: s => s.show_trigger },
    { key: 'trigger_bg', label: 'Sfondo', type: 'color',
      show: s => s.show_trigger },
    { key: 'trigger_size', label: 'Dimensione (px)', type: 'range', min: 16, max: 48, step: 2,
      show: s => s.show_trigger },
    { key: 'trigger_position', label: 'Posizione', type: 'select',
      show: s => s.show_trigger,
      options: [
        { value: 'inline', label: 'Inline (nel flusso)' },
        { value: 'top-left', label: 'Fisso alto-sinistra' },
        { value: 'top-right', label: 'Fisso alto-destra' },
        { value: 'bottom-left', label: 'Fisso basso-sinistra' },
        { value: 'bottom-right', label: 'Fisso basso-destra' },
      ]},
    { key: 'trigger_offset_x', label: 'Offset orizzontale (px)', type: 'range', min: 0, max: 80, step: 2,
      show: s => s.show_trigger && s.trigger_position && s.trigger_position !== 'inline' },
    { key: 'trigger_offset_y', label: 'Offset verticale (px)', type: 'range', min: 0, max: 80, step: 2,
      show: s => s.show_trigger && s.trigger_position && s.trigger_position !== 'inline' },
    { key: 'trigger_border_radius', label: 'Raggio bordo (px)', type: 'range', min: 0, max: 50, step: 2,
      show: s => s.show_trigger && s.trigger_bg },
    { key: 'trigger_selector', label: 'Selettore CSS trigger esterno', type: 'text' },

    { type: 'separator', label: 'Animazione' },
    { key: 'transition', label: 'Transizione', type: 'select', options: [
      { value: 'slide', label: 'Slide' },
      { value: 'push', label: 'Push (sposta pagina)' },
      { value: 'fade', label: 'Fade' },
    ]},
    { key: 'transition_duration', label: 'Durata (ms)', type: 'range', min: 150, max: 800, step: 50 },
    { key: 'stagger_items', label: 'Stagger figli', type: 'toggle' },
    { key: 'stagger_delay', label: 'Ritardo stagger (ms)', type: 'range', min: 20, max: 200, step: 10,
      show: s => s.stagger_items },

    ...shadowField,
  ],
};
