export default {
  type: 'overlayslider',
  name: 'Overlay Slider',
  icon: 'dashicons-format-gallery',
  category: 'content',
  defaults: {
    slides: [
      { id: 'os-1', image: '', title: 'Slide 1', subtitle: '', link: '' },
      { id: 'os-2', image: '', title: 'Slide 2', subtitle: '', link: '' },
    ],
    columns: '1',
    height: '400',
    overlay_position: 'bottom',
    overlay_horizontal: 'left',
    overlay_style: 'overlay-primary',
    overlay_padding: 'medium',
    title_size: 'h3',
    hover_effect: 'none',
    hover_overlay: 'always',
    show_arrows: true,
    show_dots: true,
    ribbon_position: 'top-right',
    ribbon_bg: '#e11d48',
    ribbon_color: '#ffffff',
  },
  fields: [
    { key: 'slides', label: 'Slide', type: 'content-items', supportsDynamic: true,
      itemFields: [
        { key: 'image', label: 'Immagine', type: 'image' },
        { key: 'hover_image', label: 'Immagine hover', type: 'image' },
        { key: 'hover_video', label: 'Video hover', type: 'media' },
        { key: 'title', label: 'Titolo', type: 'text' },
        { key: 'subtitle', label: 'Sottotitolo', type: 'text' },
        { key: 'link', label: 'Link', type: 'text', placeholder: 'https://...' },
        { key: 'ribbon', label: 'Ribbon', type: 'text' },
      ],
      newItemDefaults: { image: '', hover_image: '', hover_video: '', title: 'Nuova slide', subtitle: '', link: '', ribbon: '' },
      itemLabel: 'Slide',
    },
    { key: 'columns', label: 'Colonne', type: 'select', options: [
      { value: '1', label: '1 colonna' },
      { value: '2', label: '2 colonne' },
      { value: '3', label: '3 colonne' },
    ]},
    { key: 'height', label: 'Altezza (px)', type: 'range', min: 200, max: 800, step: 50 },
    { type: 'separator', label: 'Overlay' },
    { key: 'overlay_position', label: 'Posizione verticale', type: 'select', options: [
      { value: 'bottom', label: 'In basso' },
      { value: 'top', label: 'In alto' },
      { value: 'center', label: 'Centro' },
      { value: 'cover', label: 'Copertura' },
      { value: 'bottom-left', label: 'Basso-sinistra' },
      { value: 'bottom-center', label: 'Basso-centro' },
      { value: 'bottom-right', label: 'Basso-destra' },
      { value: 'top-left', label: 'Alto-sinistra' },
      { value: 'top-center', label: 'Alto-centro' },
      { value: 'top-right', label: 'Alto-destra' },
      { value: 'center-left', label: 'Centro-sinistra' },
      { value: 'center-right', label: 'Centro-destra' },
    ]},
    { key: 'overlay_horizontal', label: 'Allineamento testo', type: 'select', options: [
      { value: 'left', label: 'Sinistra' },
      { value: 'center', label: 'Centro' },
      { value: 'right', label: 'Destra' },
    ]},
    { key: 'overlay_style', label: 'Stile overlay', type: 'select', options: [
      { value: 'overlay-primary', label: 'Primary' },
      { value: 'overlay-default', label: 'Predefinito' },
    ]},
    { key: 'overlay_padding', label: 'Padding overlay', type: 'select', options: [
      { value: 'small', label: 'Piccolo' },
      { value: 'medium', label: 'Medio' },
      { value: 'large', label: 'Grande' },
    ]},
    { key: 'title_size', label: 'Dimensione titolo', type: 'select', options: [
      { value: 'h1', label: 'H1' },
      { value: 'h2', label: 'H2' },
      { value: 'h3', label: 'H3' },
      { value: 'h4', label: 'H4' },
    ]},
    { type: 'separator', label: 'Effetti hover' },
    { key: 'hover_effect', label: 'Effetto immagine', type: 'select', options: [
      { value: 'none', label: 'Nessuno' },
      { value: 'zoom', label: 'Zoom' },
      { value: 'zoom-rotate', label: 'Zoom + rotazione' },
      { value: 'brightness', label: 'Luminosità' },
      { value: 'desaturate', label: 'Desatura → colore' },
      { value: 'blur-in', label: 'Sfocatura → nitido' },
    ]},
    { key: 'hover_overlay', label: 'Overlay', type: 'select', options: [
      { value: 'always', label: 'Sempre visibile' },
      { value: 'fade', label: 'Fade in' },
      { value: 'slide-bottom', label: 'Scorre dal basso' },
      { value: 'slide-top', label: "Scorre dall'alto" },
      { value: 'slide-left', label: 'Scorre da sinistra' },
      { value: 'slide-right', label: 'Scorre da destra' },
    ]},
    { key: 'show_arrows', label: 'Mostra frecce', type: 'toggle' },
    { key: 'show_dots', label: 'Mostra indicatori', type: 'toggle' },
    { type: 'separator', label: 'Ribbon' },
    { key: 'ribbon_position', label: 'Posizione ribbon', type: 'select', options: [
      { value: 'top-left', label: 'Alto sinistra' },
      { value: 'top-right', label: 'Alto destra' },
    ]},
    { key: 'ribbon_bg', label: 'Sfondo ribbon', type: 'color' },
    { key: 'ribbon_color', label: 'Testo ribbon', type: 'color' },
  ],
};
