export default {
  type: 'pagination',
  name: 'Paginazione',
  icon: 'dashicons-ellipsis',
  category: 'dynamic',
  defaults: {
    style: 'both',
    alignment: 'center',
    show_first_last: false,
    prev_text: '\u00ab Precedente',
    next_text: 'Successivo \u00bb',
    gap: '8',
    button_padding: '8 16',
    text_color: '',
    active_color: '',
    active_text_color: '',
    background_color: '',
    active_background: '',
    border_radius: '4',
    hover_background: '',
    font_size: '14',
    border_color: '',
    border_width: '1',
  },
  fields: [
    { type: 'separator', label: 'Stile' },
    { key: 'style', label: 'Modalit\u00e0', type: 'select', options: [
      { value: 'numbered', label: 'Solo numeri' },
      { value: 'prev-next', label: 'Solo Prec/Succ' },
      { value: 'both', label: 'Numeri + Prec/Succ' },
    ]},
    { key: 'alignment', label: 'Allineamento', type: 'select', options: [
      { value: 'left', label: 'Sinistra' },
      { value: 'center', label: 'Centro' },
      { value: 'right', label: 'Destra' },
    ]},
    { key: 'show_first_last', label: 'Mostra Primo/Ultimo', type: 'toggle' },
    { key: 'prev_text', label: 'Testo Precedente', type: 'text' },
    { key: 'next_text', label: 'Testo Successivo', type: 'text' },

    { type: 'separator', label: 'Dimensioni' },
    { key: 'gap', label: 'Distanza tra pulsanti (px)', type: 'range', min: 0, max: 24, step: 2 },
    { key: 'button_padding', label: 'Padding pulsanti (px)', type: 'text' },
    { key: 'font_size', label: 'Dimensione testo (px)', type: 'range', min: 10, max: 24, step: 1 },
    { key: 'border_radius', label: 'Raggio bordo (px)', type: 'border-radius' },
    { key: 'border_width', label: 'Spessore bordo (px)', type: 'range', min: 0, max: 4, step: 1 },

    { type: 'separator', label: 'Colori' },
    { key: 'text_color', label: 'Colore testo', type: 'color' },
    { key: 'background_color', label: 'Sfondo pulsanti', type: 'color' },
    { key: 'border_color', label: 'Colore bordo', type: 'color' },
    { key: 'hover_background', label: 'Sfondo hover', type: 'color' },
    { key: 'active_color', label: 'Colore testo pagina attiva', type: 'color' },
    { key: 'active_text_color', label: 'Testo pagina attiva', type: 'color' },
    { key: 'active_background', label: 'Sfondo pagina attiva', type: 'color' },
  ],
};
