import { shadowField } from './_shared.js';

export default {
  type: 'panelslider',
  name: 'Panel Slider',
  icon: 'dashicons-slides',
  category: 'interactive',
  defaults: {
    panels: [
      { id: 'ps-1', title: 'Card 1', content: 'Contenuto...', image: '' },
      { id: 'ps-2', title: 'Card 2', content: 'Contenuto...', image: '' },
      { id: 'ps-3', title: 'Card 3', content: 'Contenuto...', image: '' },
    ],
    columns: '3',
    gap: 'default',
    card_style: 'default',
    show_arrows: true,
    autoplay: false,
    autoplay_interval: '5000',
    shadow: 'none',
  },
  fields: [
    { key: 'panels', label: 'Pannelli', type: 'content-items', supportsDynamic: true,
      itemFields: [
        { key: 'title', label: 'Titolo', type: 'text' },
        { key: 'content', label: 'Contenuto', type: 'textarea' },
        { key: 'image', label: 'Immagine', type: 'image' },
        { key: 'hover_image', label: 'Immagine hover', type: 'image' },
        { key: 'hover_video', label: 'Video hover', type: 'media' },
      ],
      newItemDefaults: { title: 'Nuova card', content: 'Contenuto...', image: '', hover_image: '', hover_video: '' },
      itemLabel: 'Card',
    },
    { key: 'columns', label: 'Colonne', type: 'select', options: [
      { value: '1', label: '1 colonna' },
      { value: '2', label: '2 colonne' },
      { value: '3', label: '3 colonne' },
      { value: '4', label: '4 colonne' },
      { value: '5', label: '5 colonne' },
      { value: '6', label: '6 colonne' },
    ]},
    { key: 'gap', label: 'Gap', type: 'select', options: [
      { value: 'collapse', label: 'Collassato' },
      { value: 'small', label: 'Piccolo' },
      { value: 'default', label: 'Predefinito' },
      { value: 'medium', label: 'Medio' },
      { value: 'large', label: 'Grande' },
    ]},
    { key: 'card_style', label: 'Stile card', type: 'select', options: [
      { value: 'default', label: 'Predefinito' },
      { value: 'primary', label: 'Primary' },
      { value: 'secondary', label: 'Secondary' },
      { value: 'hover', label: 'Hover' },
    ]},
    { key: 'show_arrows', label: 'Mostra frecce', type: 'toggle' },
    { key: 'autoplay', label: 'Autoplay', type: 'toggle' },
    { key: 'autoplay_interval', label: 'Intervallo autoplay (ms)', type: 'range', min: 1000, max: 10000, step: 500 },
    ...shadowField,
  ],
};
