
export default {
  type: 'pdfpro',
  name: 'PDF Pro',
  icon: 'dashicons-media-document',
  category: 'media',
  defaults: {
    pdf_url: '',
    mode: 'flipbook',
    viewer_height: '600',
    start_page: '1',
    initial_zoom: 'fit-width',
    theme: 'light',
    bg_color: '',
    show_toolbar: true,
    show_page_nav: true,
    show_zoom: true,
    show_fullscreen: true,
    show_download: true,
    show_print: true,
    show_search: false,
    show_thumbnails: false,
    hotspots: [],
    hotspot_color: '',
    hotspot_size: '14',
    hotspot_pulse: true,
  },
  fields: [
    { type: 'separator', label: 'Sorgente' },
    { key: 'pdf_url', label: 'File PDF', type: 'media' },

    { type: 'separator', label: 'Visualizzazione' },
    { key: 'mode', label: 'Modalità', type: 'select', options: [
      { value: 'flipbook', label: 'Flipbook (sfoglia)' },
      { value: 'single', label: 'Pagina singola' },
      { value: 'double', label: 'Doppia pagina' },
      { value: 'scroll', label: 'Scroll continuo' },
    ]},
    { key: 'viewer_height', label: 'Altezza viewer (px)', type: 'range', min: 300, max: 1200, step: 10 },
    { key: 'start_page', label: 'Pagina iniziale', type: 'range', min: 1, max: 500, step: 1 },
    { key: 'initial_zoom', label: 'Zoom iniziale', type: 'select', options: [
      { value: 'fit-width', label: 'Adatta alla larghezza' },
      { value: 'fit-page', label: 'Adatta alla pagina' },
      { value: '100', label: '100%' },
      { value: '75', label: '75%' },
      { value: '50', label: '50%' },
    ]},
    { key: 'theme', label: 'Tema', type: 'select', options: [
      { value: 'light', label: 'Chiaro' },
      { value: 'dark', label: 'Scuro' },
    ]},
    { key: 'bg_color', label: 'Colore sfondo', type: 'color' },

    { type: 'separator', label: 'Controlli toolbar' },
    { key: 'show_toolbar', label: 'Mostra toolbar', type: 'toggle' },
    { key: 'show_page_nav', label: 'Navigazione pagine', type: 'toggle',
      condition: { field: 'show_toolbar', value: true } },
    { key: 'show_zoom', label: 'Zoom', type: 'toggle',
      condition: { field: 'show_toolbar', value: true } },
    { key: 'show_fullscreen', label: 'Schermo intero', type: 'toggle',
      condition: { field: 'show_toolbar', value: true } },
    { key: 'show_download', label: 'Download', type: 'toggle',
      condition: { field: 'show_toolbar', value: true } },
    { key: 'show_print', label: 'Stampa', type: 'toggle',
      condition: { field: 'show_toolbar', value: true } },
    { key: 'show_thumbnails', label: 'Miniature', type: 'toggle',
      condition: { field: 'show_toolbar', value: true } },

    { type: 'separator', label: 'Hotspot interattivi' },
    { key: 'hotspots', label: 'Hotspot', type: 'content-items',
      itemFields: [
        { key: 'page', label: 'Pagina', type: 'number', min: 1 },
        { key: '_placer', label: 'Posiziona su PDF', type: 'hotspot-position' },
        { key: 'x', label: 'Posizione X (%)', type: 'range', min: 0, max: 100, step: 0.5 },
        { key: 'y', label: 'Posizione Y (%)', type: 'range', min: 0, max: 100, step: 0.5 },
        { key: 'color', label: 'Colore', type: 'color' },
        { key: 'icon', label: 'Icona', type: 'icon' },
        { key: 'title', label: 'Titolo', type: 'text' },
        { key: 'description', label: 'Descrizione', type: 'textarea' },
        { key: 'image_url', label: 'Immagine', type: 'media' },
        { key: 'video_url', label: 'Video', type: 'media' },
        { key: 'btn_label', label: 'Testo pulsante', type: 'text' },
        { key: 'btn_url', label: 'URL pulsante', type: 'text' },
        { key: 'btn_target', label: 'Apri in nuova scheda', type: 'toggle' },
        // Tipografia pulsante
        { key: 'btn_font_size', label: 'Dim. testo (px)', type: 'range', min: 10, max: 24, step: 1 },
        { key: 'btn_font_weight', label: 'Peso testo', type: 'select', options: [
          { value: '', label: 'Medio (default)' },
          { value: '400', label: 'Normale' },
          { value: '600', label: 'Semi-grassetto' },
          { value: '700', label: 'Grassetto' },
          { value: '800', label: 'Extra-grassetto' },
        ]},
        { key: 'btn_letter_spacing', label: 'Spaziatura lettere (px)', type: 'range', min: 0, max: 5, step: 0.5 },
        { key: 'btn_text_transform', label: 'Trasformazione testo', type: 'select', options: [
          { value: '', label: 'Nessuna' },
          { value: 'uppercase', label: 'MAIUSCOLO' },
          { value: 'lowercase', label: 'minuscolo' },
          { value: 'capitalize', label: 'Prima Maiuscola' },
        ]},
        // Colori pulsante
        { key: 'btn_bg', label: 'Sfondo pulsante', type: 'color' },
        { key: 'btn_color', label: 'Colore testo', type: 'color' },
        // Spaziatura interna
        { key: 'btn_padding_v', label: 'Padding verticale (px)', type: 'spacing', max: 30 },
        { key: 'btn_padding_h', label: 'Padding orizzontale (px)', type: 'spacing', max: 50 },
        // Bordo
        { key: 'btn_radius', label: 'Raggio angoli (px)', type: 'border-radius' },
        { key: 'btn_border_width', label: 'Spessore bordo (px)', type: 'range', min: 0, max: 5, step: 1 },
        { key: 'btn_border_color', label: 'Colore bordo', type: 'color' },
        { key: 'btn_border_style', label: 'Stile bordo', type: 'select', options: [
          { value: 'solid', label: 'Solido' },
          { value: 'dashed', label: 'Tratteggiato' },
          { value: 'dotted', label: 'Punteggiato' },
          { value: 'double', label: 'Doppio' },
        ]},
        // Layout
        { key: 'btn_align', label: 'Allineamento', type: 'select', options: [
          { value: '', label: 'Sinistra' },
          { value: 'center', label: 'Centro' },
          { value: 'right', label: 'Destra' },
          { value: 'stretch', label: 'Larghezza piena' },
        ]},
      ],
      newItemDefaults: { page: 1, x: 50, y: 50, title: 'Nuovo hotspot', description: '',
        color: '', icon: '', image_url: '', video_url: '', btn_label: '', btn_url: '', btn_target: false,
        btn_font_size: '', btn_font_weight: '', btn_letter_spacing: '', btn_text_transform: '',
        btn_bg: '', btn_color: '', btn_padding_v: '', btn_padding_h: '',
        btn_radius: '', btn_border_width: '', btn_border_color: '', btn_border_style: 'solid',
        btn_align: '' },
      itemLabel: 'Hotspot',
    },
    { key: 'hotspot_color', label: 'Colore hotspot', type: 'color' },
    { key: 'hotspot_size', label: 'Dimensione hotspot (px)', type: 'range', min: 8, max: 30, step: 1 },
    { key: 'hotspot_pulse', label: 'Animazione pulse', type: 'toggle' },

  ],
};
