export default {
  type: 'serviceresults',
  name: 'Risultati strutture',
  icon: 'dashicons-list-view',
  category: 'dynamic',
  defaults: {
    layout: 'map-left',
    map_height: '500',
    map_sticky: true,
    tile_layer: 'positron',
    default_zoom: '10',
    fit_bounds: true,
    visible_filters: 'valley,guests,bedrooms,altitude,amenities',
    altitude_ranges: '0-1000,1000-1500,1500-2000,2000-9999',
    guests_ranges: '1-2,3-4,5-6,7-99',
    amenities_list: 'wifi,fireplace,parking,sauna,hottub,bbq,garden,pets',
    columns: '2',
    columns_mobile: '1',
    gap: 'medium',
    card_style: 'default',
    card_primary_bg: '#6366F1',
    match_height: false,
    image_height: '180',
    image_radius: '0',
    card_radius: '8',
    // Hover immagine
    hover_effect: 'none',
    fx_kenburns: false,
    fx_kenburns_speed: '20',
    fx_kenburns_scale: '1.12',
    // Overlay
    overlay_gradient: false,
    overlay_color: '#000000',
    overlay_opacity: '50',
    overlay_direction: 'bottom',
    overlay_height: '50',
    // Testo
    body_padding: '15',
    title_size: '1',
    title_color: '',
    excerpt_size: '0.92',
    excerpt_color: '',
    body_bg: '',
    body_bg_opacity: '100',
    // Contenuto card
    card_content: 'excerpt,stats,price',
    show_service_opening: false,
    opening_bg_annual: '#059669',
    opening_bg_seasonal: '#d97706',
    opening_size: '11',
    ribbon_field: '',
    ribbon_position: 'top-right',
    ribbon_bg: '#e11d48',
    ribbon_color: '#ffffff',
    excerpt_length: '15',
    price_prefix: '\u20ac',
    price_suffix: '/notte',
    link_text: 'Dettagli',
    link_style: 'text',
    random_order: false,
    items_per_page: '8',
    pagination_style: 'numbers',
    marker_color: '#e11d48',
  },
  fields: [
    // ─── Filtri: quali mostrare ───
    { type: 'separator', label: 'Filtri visibili nella pagina' },
    {
      key: 'visible_filters',
      label: 'Seleziona i filtri attivi',
      type: 'multi_pills',
      options: [
        { value: 'valley', label: 'Località / Valle', icon: 'location' },
        { value: 'guests', label: 'Ospiti', icon: 'users' },
        { value: 'bedrooms', label: 'Camere', icon: 'bed' },
        { value: 'altitude', label: 'Altitudine', icon: 'arrow-up' },
        { value: 'type', label: 'Tipologia', icon: 'home' },
        { value: 'amenities', label: 'Servizi', icon: 'star' },
        { value: 'club', label: 'Club di Prodotto', icon: 'award' },
      ],
    },

    // ─── Fasce altitudine ───
    { type: 'separator', label: 'Fasce altitudine nel dropdown' },
    {
      key: 'altitude_ranges',
      label: 'Clicca le fasce da mostrare',
      type: 'multi_pills',
      options: [
        { value: '0-1000', label: '< 1.000m' },
        { value: '1000-1500', label: '1.000 - 1.500m' },
        { value: '1500-2000', label: '1.500 - 2.000m' },
        { value: '2000-9999', label: '> 2.000m' },
      ],
    },

    // ─── Fasce ospiti ───
    { type: 'separator', label: 'Fasce ospiti nel dropdown' },
    {
      key: 'guests_ranges',
      label: 'Clicca le fasce da mostrare',
      type: 'multi_pills',
      options: [
        { value: '1-2', label: '1-2' },
        { value: '3-4', label: '3-4' },
        { value: '5-6', label: '5-6' },
        { value: '7-10', label: '7-10' },
        { value: '11-99', label: '11+' },
      ],
    },

    // ─── Amenities ───
    { type: 'separator', label: 'Servizi selezionabili dal visitatore' },
    {
      key: 'amenities_list',
      label: 'Clicca i servizi da mostrare',
      type: 'multi_pills',
      options: [
        { value: 'wifi', label: 'WiFi', icon: 'wifi' },
        { value: 'fireplace', label: 'Camino', icon: 'fire' },
        { value: 'parking', label: 'Parcheggio', icon: 'car' },
        { value: 'kitchen', label: 'Cucina', icon: 'cup' },
        { value: 'tv', label: 'TV' },
        { value: 'bbq', label: 'BBQ', icon: 'fire' },
        { value: 'terrace', label: 'Terrazza' },
        { value: 'heating', label: 'Riscaldamento', icon: 'bolt' },
        { value: 'sauna', label: 'Sauna', icon: 'droplet' },
        { value: 'hottub', label: 'Idromassaggio', icon: 'droplet' },
        { value: 'ski', label: 'Sci ai piedi', icon: 'snowflake' },
        { value: 'garden', label: 'Giardino', icon: 'tree' },
        { value: 'pets', label: 'Animali ammessi', icon: 'paw' },
        { value: 'washer', label: 'Lavatrice' },
        { value: 'highchair', label: 'Seggiolone' },
        { value: 'aircon', label: 'Aria condizionata', icon: 'snowflake' },
        { value: 'dishwasher', label: 'Lavastoviglie' },
        { value: 'linens', label: 'Biancheria', icon: 'bed' },
        { value: 'towels', label: 'Asciugamani' },
        { value: 'pool', label: 'Piscina', icon: 'droplet' },
        { value: 'hiking', label: 'Escursioni', icon: 'location' },
        { value: 'bikes', label: 'Biciclette' },
        { value: 'elevator', label: 'Ascensore', icon: 'arrow-up' },
        { value: 'accessible', label: 'Accessibile', icon: 'check' },
      ],
    },

    // ─── Mappa ───
    { type: 'separator', label: 'Mappa' },
    { key: 'layout', label: 'Posizione mappa', type: 'select', options: [
      { value: 'map-left', label: 'Mappa a sinistra' },
      { value: 'map-right', label: 'Mappa a destra' },
      { value: 'map-top', label: 'Mappa in alto' },
      { value: 'cards-only', label: 'Nessuna mappa (solo card)' },
    ]},
    { key: 'map_height', label: 'Altezza mappa (px)', type: 'range', min: 300, max: 900, step: 10,
      condition: { field: 'layout', operator: '!=', value: 'cards-only' } },
    { key: 'map_sticky', label: 'Mappa fissa durante lo scroll', type: 'toggle',
      condition: { field: 'layout', operator: '!=', value: 'cards-only' } },
    { key: 'tile_layer', label: 'Stile mappa', type: 'select', options: [
      { value: 'osm', label: 'OpenStreetMap' },
      { value: 'positron', label: 'Positron (chiaro)' },
      { value: 'dark', label: 'Dark' },
    ], condition: { field: 'layout', operator: '!=', value: 'cards-only' } },
    { key: 'default_zoom', label: 'Zoom iniziale', type: 'range', min: 5, max: 18, step: 1,
      condition: { field: 'layout', operator: '!=', value: 'cards-only' } },
    { key: 'fit_bounds', label: 'Auto-zoom sui risultati', type: 'toggle',
      condition: { field: 'layout', operator: '!=', value: 'cards-only' } },
    { key: 'marker_color', label: 'Colore pin', type: 'color',
      condition: { field: 'layout', operator: '!=', value: 'cards-only' } },

    // ─── Card risultati ───
    { type: 'separator', label: 'Card risultati' },
    { key: 'columns', label: 'Colonne', type: 'select', options: [
      { value: '1', label: '1' }, { value: '2', label: '2' },
      { value: '3', label: '3' }, { value: '4', label: '4' },
    ]},
    { key: 'columns_mobile', label: 'Colonne su mobile', type: 'select', options: [
      { value: '1', label: '1' }, { value: '2', label: '2' },
    ]},
    { key: 'gap', label: 'Spaziatura tra card', type: 'select', options: [
      { value: 'collapse', label: 'Nessuna' }, { value: 'small', label: 'Piccola' },
      { value: 'medium', label: 'Media' }, { value: 'large', label: 'Grande' },
    ]},
    { key: 'card_style', label: 'Stile card', type: 'select', options: [
      { value: 'default', label: 'Bordo sottile' },
      { value: 'shadow', label: 'Ombra' },
      { value: 'primary', label: 'Primary' },
      { value: 'minimal', label: 'Nessuno sfondo' },
    ]},
    { key: 'card_primary_bg', label: 'Colore sfondo card', type: 'color',
      condition: { field: 'card_style', value: 'primary' } },
    { key: 'match_height', label: 'Stessa altezza card', type: 'toggle' },
    { key: 'card_radius', label: 'Arrotondamento angoli (px)', type: 'range', min: 0, max: 20, step: 1 },

    // ─── Immagine ───
    { type: 'separator', label: 'Immagine' },
    { key: 'image_height', label: 'Altezza immagine (px)', type: 'range', min: 100, max: 350, step: 10 },
    { key: 'image_radius', label: 'Raggio bordo immagine (px)', type: 'range', min: 0, max: 30, step: 1 },
    { key: 'hover_effect', label: 'Effetto hover', type: 'select', options: [
      { value: 'none', label: 'Nessuno' },
      { value: 'zoom', label: 'Zoom' },
      { value: 'zoom-rotate', label: 'Zoom + rotazione' },
      { value: 'brightness', label: 'Luminosità' },
      { value: 'desaturate', label: 'Desatura → colore' },
      { value: 'blur-in', label: 'Sfocatura → nitido' },
      { value: 'slide-up', label: 'Scorrimento in alto' },
      { value: 'glow', label: 'Bagliore' },
      { value: 'tilt', label: 'Tilt 3D' },
    ]},
    { key: 'fx_kenburns', label: 'Ken Burns (zoom cinematico)', type: 'toggle' },
    { key: 'fx_kenburns_speed', label: 'Velocità Ken Burns (s)', type: 'range', min: 10, max: 40, step: 1,
      condition: { field: 'fx_kenburns', value: true } },
    { key: 'fx_kenburns_scale', label: 'Intensità zoom', type: 'range', min: 1.05, max: 1.25, step: 0.01,
      condition: { field: 'fx_kenburns', value: true } },

    // ─── Overlay immagine ───
    { type: 'separator', label: 'Overlay immagine' },
    { key: 'overlay_gradient', label: 'Overlay sfumato', type: 'toggle' },
    { key: 'overlay_color', label: 'Colore overlay', type: 'color',
      condition: { field: 'overlay_gradient', value: true } },
    { key: 'overlay_opacity', label: 'Opacità overlay (%)', type: 'range', min: 10, max: 90, step: 5,
      condition: { field: 'overlay_gradient', value: true } },
    { key: 'overlay_direction', label: 'Direzione sfumatura', type: 'select', options: [
      { value: 'bottom', label: 'Dal basso' },
      { value: 'top', label: "Dall'alto" },
      { value: 'left', label: 'Da sinistra' },
      { value: 'right', label: 'Da destra' },
    ], condition: { field: 'overlay_gradient', value: true } },
    { key: 'overlay_height', label: 'Altezza gradiente (%)', type: 'range', min: 20, max: 100, step: 5,
      condition: { field: 'overlay_gradient', value: true } },

    // ─── Stile testo ───
    { type: 'separator', label: 'Stile testo' },
    { key: 'body_padding', label: 'Padding area testo (px)', type: 'range', min: 0, max: 40, step: 1 },
    { key: 'title_size', label: 'Dimensione titolo (em)', type: 'range', min: 0.7, max: 2.5, step: 0.05 },
    { key: 'title_color', label: 'Colore titolo', type: 'color' },
    { key: 'excerpt_size', label: 'Dimensione estratto (em)', type: 'range', min: 0.7, max: 1.5, step: 0.05 },
    { key: 'excerpt_color', label: 'Colore estratto', type: 'color' },
    { key: 'body_bg', label: 'Sfondo area testo', type: 'color' },
    { key: 'body_bg_opacity', label: 'Opacità sfondo (%)', type: 'range', min: 0, max: 100, step: 5,
      condition: { field: 'body_bg', operator: '!=', value: '' } },

    // ─── Contenuto card ───
    { type: 'separator', label: 'Contenuto card' },
    {
      key: 'card_content',
      label: 'Cosa mostrare in ogni card',
      type: 'multi_pills',
      options: [
        { value: 'excerpt', label: 'Descrizione', icon: 'pencil' },
        { value: 'stats', label: 'Statistiche', icon: 'chart' },
        { value: 'price', label: 'Prezzo', icon: 'tag' },
      ],
    },
    { key: 'price_prefix', label: 'Prefisso prezzo', type: 'text' },
    { key: 'price_suffix', label: 'Suffisso prezzo', type: 'text' },
    { key: 'link_text', label: 'Testo link dettaglio', type: 'text' },
    { key: 'link_style', label: 'Stile link', type: 'select', options: [
      { value: 'text', label: 'Link testuale' },
      { value: 'button', label: 'Pulsante' },
      { value: 'card', label: 'Card intera cliccabile' },
    ]},

    // ─── Badge e ribbon ───
    { type: 'separator', label: 'Badge e ribbon' },
    { key: 'show_service_opening', label: 'Mostra badge apertura', type: 'toggle' },
    { key: 'opening_bg_annual', label: 'Sfondo apertura annuale', type: 'color',
      condition: { field: 'show_service_opening', value: true } },
    { key: 'opening_bg_seasonal', label: 'Sfondo apertura stagionale', type: 'color',
      condition: { field: 'show_service_opening', value: true } },
    { key: 'opening_size', label: 'Dimensione testo badge (px)', type: 'range', min: 8, max: 18, step: 1,
      condition: { field: 'show_service_opening', value: true } },
    { key: 'ribbon_field', label: 'Meta key ribbon', type: 'text' },
    { key: 'ribbon_position', label: 'Posizione ribbon', type: 'select', options: [
      { value: 'top-left', label: 'Alto sinistra' },
      { value: 'top-right', label: 'Alto destra' },
    ]},
    { key: 'ribbon_bg', label: 'Sfondo ribbon', type: 'color' },
    { key: 'ribbon_color', label: 'Testo ribbon', type: 'color' },

    // ─── Ordinamento ───
    { type: 'separator', label: 'Ordinamento' },
    { key: 'random_order', label: 'Ordine casuale', type: 'toggle' },

    // ─── Paginazione ───
    { type: 'separator', label: 'Paginazione' },
    { key: 'items_per_page', label: 'Strutture per pagina', type: 'select', options: [
      { value: '4', label: '4' }, { value: '6', label: '6' },
      { value: '8', label: '8' }, { value: '12', label: '12' },
      { value: '16', label: '16' },
    ]},
    { key: 'pagination_style', label: 'Stile navigazione', type: 'select', options: [
      { value: 'numbers', label: 'Numeri pagina' },
      { value: 'dots', label: 'Pallini' },
      { value: 'arrows', label: 'Frecce avanti/indietro' },
      { value: 'loadmore', label: 'Pulsante Carica altro' },
    ]},
  ],
};
