export default {
  type: 'servicesearch',
  name: 'Cerca strutture',
  icon: 'dashicons-search',
  category: 'dynamic',
  defaults: {
    results_url: '',
    layout: 'horizontal',
    visible_filters: 'valley,checkin,guests,bedrooms,altitude',
    altitude_ranges: '0-1000,1000-1500,1500-2000,2000-9999',
    guests_ranges: '1-2,3-4,5-6,7-99',
    amenities_list: 'wifi,fireplace,parking,sauna,hottub,bbq,garden,pets',
    button_text: 'Cerca',
    button_bg: '',
    button_color: '',
    filter_bg: '',
    filter_border: '',
    border_radius: '8',
    overlap: false,
    overlap_offset: '60',
    overlap_shadow: true,
    overlap_max_width: '1100',
    // Larghezza campi (%)
    width_valley: '',
    width_checkin: '',
    width_checkout: '',
    width_guests: '',
    width_bedrooms: '',
    width_altitude: '',
    width_type: '',
    width_club: '',
  },
  fields: [
    // ─── Quali filtri mostrare ───
    { type: 'separator', label: 'Quali filtri mostrare nella barra' },
    {
      key: 'visible_filters',
      label: 'Seleziona i campi visibili',
      type: 'multi_pills',
      options: [
        { value: 'valley', label: 'Località / Valle', icon: 'location' },
        { value: 'checkin', label: 'Check-in / out', icon: 'calendar' },
        { value: 'guests', label: 'Ospiti', icon: 'users' },
        { value: 'bedrooms', label: 'Camere', icon: 'bed' },
        { value: 'altitude', label: 'Altitudine', icon: 'arrow-up' },
        { value: 'type', label: 'Tipologia', icon: 'home' },
        { value: 'amenities', label: 'Servizi', icon: 'star' },
        { value: 'club', label: 'Club di Prodotto', icon: 'award' },
      ],
    },

    // ─── Fasce altitudine ───
    { type: 'separator', label: 'Fasce altitudine nel dropdown' },
    {
      key: 'altitude_ranges',
      label: 'Clicca le fasce da mostrare',
      type: 'multi_pills',
      options: [
        { value: '0-1000', label: '< 1.000m' },
        { value: '1000-1500', label: '1.000 - 1.500m' },
        { value: '1500-2000', label: '1.500 - 2.000m' },
        { value: '2000-9999', label: '> 2.000m' },
      ],
    },

    // ─── Fasce ospiti ───
    { type: 'separator', label: 'Fasce ospiti nel dropdown' },
    {
      key: 'guests_ranges',
      label: 'Clicca le fasce da mostrare',
      type: 'multi_pills',
      options: [
        { value: '1-2', label: '1-2' },
        { value: '3-4', label: '3-4' },
        { value: '5-6', label: '5-6' },
        { value: '7-10', label: '7-10' },
        { value: '11-99', label: '11+' },
      ],
    },

    // ─── Amenities ───
    { type: 'separator', label: 'Servizi selezionabili dal visitatore' },
    {
      key: 'amenities_list',
      label: 'Clicca i servizi da mostrare',
      type: 'multi_pills',
      options: [
        { value: 'wifi', label: 'WiFi', icon: 'wifi' },
        { value: 'fireplace', label: 'Camino', icon: 'fire' },
        { value: 'parking', label: 'Parcheggio', icon: 'car' },
        { value: 'kitchen', label: 'Cucina', icon: 'cup' },
        { value: 'tv', label: 'TV' },
        { value: 'bbq', label: 'BBQ', icon: 'fire' },
        { value: 'terrace', label: 'Terrazza' },
        { value: 'heating', label: 'Riscaldamento', icon: 'bolt' },
        { value: 'sauna', label: 'Sauna', icon: 'droplet' },
        { value: 'hottub', label: 'Idromassaggio', icon: 'droplet' },
        { value: 'ski', label: 'Sci ai piedi', icon: 'snowflake' },
        { value: 'garden', label: 'Giardino', icon: 'tree' },
        { value: 'pets', label: 'Animali ammessi', icon: 'paw' },
        { value: 'washer', label: 'Lavatrice' },
        { value: 'highchair', label: 'Seggiolone' },
        { value: 'aircon', label: 'Aria condizionata', icon: 'snowflake' },
        { value: 'dishwasher', label: 'Lavastoviglie' },
        { value: 'linens', label: 'Biancheria', icon: 'bed' },
        { value: 'towels', label: 'Asciugamani' },
        { value: 'pool', label: 'Piscina', icon: 'droplet' },
        { value: 'hiking', label: 'Escursioni', icon: 'location' },
        { value: 'bikes', label: 'Biciclette' },
        { value: 'elevator', label: 'Ascensore', icon: 'arrow-up' },
        { value: 'accessible', label: 'Accessibile', icon: 'check' },
      ],
    },

    // ─── Pagina risultati ───
    { type: 'separator', label: 'Destinazione' },
    {
      key: 'results_url',
      label: 'Pagina risultati',
      type: 'select',
      optionsSource: 'wpPages',
    },

    // ─── Posizionamento ───
    { type: 'separator', label: 'Posizionamento' },
    { key: 'overlap', label: 'Sovrapponi alla sezione sopra', type: 'toggle' },
    { key: 'overlap_offset', label: 'Sovrapposizione (px)', type: 'range', min: 20, max: 200, step: 5,
      condition: { field: 'overlap', value: true } },
    { key: 'overlap_shadow', label: 'Ombra portata', type: 'toggle',
      condition: { field: 'overlap', value: true } },
    { key: 'overlap_max_width', label: 'Larghezza max (px)', type: 'range', min: 600, max: 1400, step: 50,
      condition: { field: 'overlap', value: true } },

    // ─── Aspetto ───
    { type: 'separator', label: 'Aspetto barra' },
    {
      key: 'layout',
      label: 'Disposizione campi',
      type: 'select',
      options: [
        { value: 'horizontal', label: 'Orizzontale (una riga)' },
        { value: 'vertical', label: 'Verticale (colonna)' },
      ],
    },
    { key: 'button_text', label: 'Testo pulsante', type: 'text' },
    { key: 'button_bg', label: 'Colore pulsante', type: 'color' },
    { key: 'button_color', label: 'Colore testo pulsante', type: 'color' },
    { key: 'filter_bg', label: 'Sfondo barra', type: 'color' },
    { key: 'filter_border', label: 'Bordo barra', type: 'color' },
    {
      key: 'border_radius',
      label: 'Arrotondamento (px)',
      type: 'border-radius' },

    // ─── Larghezza campi ───
    { type: 'separator', label: 'Larghezza campi (%)' },
    { key: 'width_valley', label: 'Località / Valle (%)', type: 'range', min: 10, max: 50, step: 1,
      condition: { field: 'layout', value: 'horizontal' } },
    { key: 'width_checkin', label: 'Check-in (%)', type: 'range', min: 10, max: 40, step: 1,
      condition: { field: 'layout', value: 'horizontal' } },
    { key: 'width_checkout', label: 'Check-out (%)', type: 'range', min: 10, max: 40, step: 1,
      condition: { field: 'layout', value: 'horizontal' } },
    { key: 'width_guests', label: 'Ospiti (%)', type: 'range', min: 8, max: 30, step: 1,
      condition: { field: 'layout', value: 'horizontal' } },
    { key: 'width_bedrooms', label: 'Camere (%)', type: 'range', min: 8, max: 30, step: 1,
      condition: { field: 'layout', value: 'horizontal' } },
    { key: 'width_altitude', label: 'Altitudine (%)', type: 'range', min: 8, max: 30, step: 1,
      condition: { field: 'layout', value: 'horizontal' } },
    { key: 'width_type', label: 'Tipologia (%)', type: 'range', min: 10, max: 30, step: 1,
      condition: { field: 'layout', value: 'horizontal' } },
    { key: 'width_club', label: 'Club (%)', type: 'range', min: 10, max: 50, step: 1,
      condition: { field: 'layout', value: 'horizontal' } },
  ],
};
