export default {
  type: 'serviceinfo',
  name: 'Info Servizio',
  icon: 'dashicons-info-outline',
  category: 'booking',
  defaults: {
    acc_hero_height: '400',
    acc_max_width: '900',
    acc_card_radius: '16',
    acc_card_shadow: 'lg',
    acc_body_padding: '32',
    acc_title_size: '30',
    acc_show_gallery: true,
    acc_gallery_columns: '4',
    acc_gallery_height: '180',
    acc_show_description: true,
    acc_show_amenities: true,
    acc_show_checkin: true,
    acc_show_booking_btn: false,
    acc_amenity_cols_desktop: '4',
    acc_accent_color: '',
    acc_section_order: 'gallery,stats,prices,description,amenities,checkin',
  },
  fields: [
    // ── Layout ──
    { type: 'separator', label: 'Layout' },
    { key: 'acc_max_width', label: 'Larghezza max (px)', type: 'range', min: 600, max: 1200, step: 50 },
    { key: 'acc_hero_height', label: 'Altezza hero (px)', type: 'range', min: 200, max: 600, step: 20 },
    { key: 'acc_card_radius', label: 'Raggio bordi (px)', type: 'border-radius' },
    { key: 'acc_card_shadow', label: 'Ombra', type: 'select', options: [
      { value: 'none', label: 'Nessuna' },
      { value: 'sm', label: 'Leggera' },
      { value: 'md', label: 'Media' },
      { value: 'lg', label: 'Forte' },
      { value: 'custom', label: 'Personalizzata' },
    ]},
    { key: 'acc_card_shadow_h', label: 'Offset H (px)', type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'acc_card_shadow', op: 'eq', value: 'custom' } },
    { key: 'acc_card_shadow_v', label: 'Offset V (px)', type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'acc_card_shadow', op: 'eq', value: 'custom' } },
    { key: 'acc_card_shadow_blur', label: 'Sfocatura (px)', type: 'range', min: 0, max: 100, step: 1,
      condition: { field: 'acc_card_shadow', op: 'eq', value: 'custom' } },
    { key: 'acc_card_shadow_spread', label: 'Espansione (px)', type: 'range', min: -50, max: 50, step: 1,
      condition: { field: 'acc_card_shadow', op: 'eq', value: 'custom' } },
    { key: 'acc_card_shadow_color', label: 'Colore ombra', type: 'color',
      condition: { field: 'acc_card_shadow', op: 'eq', value: 'custom' } },
    { key: 'acc_card_shadow_inset', label: 'Ombra interna', type: 'toggle',
      condition: { field: 'acc_card_shadow', op: 'eq', value: 'custom' } },
    { key: 'acc_body_padding', label: 'Padding corpo (px)', type: 'range', min: 16, max: 48, step: 4 },
    { key: 'acc_title_size', label: 'Dimensione titolo (px)', type: 'range', min: 20, max: 42, step: 1 },
    { key: 'acc_accent_color', label: 'Colore accento', type: 'color' },

    // ── Sezioni ──
    { type: 'separator', label: 'Sezioni visibili' },
    { key: 'acc_show_gallery', label: 'Galleria foto', type: 'toggle' },
    { key: 'acc_show_description', label: 'Descrizione', type: 'toggle' },
    { key: 'acc_show_amenities', label: 'Servizi e comfort', type: 'toggle' },
    { key: 'acc_show_checkin', label: 'Check-in / Check-out', type: 'toggle' },
    { key: 'acc_show_booking_btn', label: 'Pulsante prenotazione', type: 'toggle' },

    // ── Galleria ──
    { type: 'separator', label: 'Galleria' },
    { key: 'acc_gallery_columns', label: 'Colonne', type: 'range', min: 2, max: 6, step: 1,
      condition: { field: 'acc_show_gallery', value: true } },
    { key: 'acc_gallery_height', label: 'Altezza miniature (px)', type: 'range', min: 100, max: 300, step: 10,
      condition: { field: 'acc_show_gallery', value: true } },

    // ── Amenities ──
    { type: 'separator', label: 'Servizi' },
    { key: 'acc_amenity_cols_desktop', label: 'Colonne servizi', type: 'range', min: 2, max: 6, step: 1,
      condition: { field: 'acc_show_amenities', value: true } },

    // ── Ordine sezioni ──
    { type: 'separator', label: 'Ordine sezioni' },
    { key: 'acc_section_order', label: 'Ordine (virgola)', type: 'text' },
  ],
};
