export default {
  type: 'servicestats',
  name: 'Stats Servizio',
  icon: 'dashicons-performance',
  category: 'booking',
  defaults: {
    meta_prefix: '_olo_service_',
    layout: 'grid',
    columns: '4',
    gap: '16',
    align: 'center',
    icon_size: '24',
    number_size: '22',
    label_size: '11',
    icon_color: '',
    number_color: '',
    label_color: '',
    show_dividers: false,
    divider_color: '',
    item_bg: '',
    item_border_radius: '8',
    item_tile_padding: { top: 0, right: 0, bottom: 0, left: 0 },
    item_border_color: '',
    bg_color: '',
    border_radius: '0',
    padding: '0',
  },
  fields: [
    { type: 'separator', label: 'Sorgente dati' },
    { key: 'meta_prefix', label: 'Tipo servizio', type: 'select', optionsSource: 'metaPrefixes' },

    { type: 'separator', label: 'Layout' },
    { key: 'layout', label: 'Disposizione', type: 'select', options: [
      { value: 'grid', label: 'Griglia verticale' },
      { value: 'inline', label: 'Riga orizzontale' },
    ]},
    { key: 'columns', label: 'Colonne', type: 'range', min: 2, max: 6, step: 1,
      condition: { field: 'layout', value: 'grid' } },
    { key: 'gap', label: 'Gap (px)', type: 'range', min: 4, max: 40, step: 2 },
    { key: 'align', label: 'Allineamento', type: 'select', options: [
      { value: 'left', label: 'Sinistra' },
      { value: 'center', label: 'Centro' },
      { value: 'right', label: 'Destra' },
    ]},
    { key: 'show_dividers', label: 'Mostra separatori', type: 'toggle' },
    { key: 'divider_color', label: 'Colore separatori', type: 'color',
      condition: { field: 'show_dividers', value: true } },

    { type: 'separator', label: 'Icone' },
    { key: 'icon_size', label: 'Dimensione icone (px)', type: 'range', min: 16, max: 40, step: 2 },
    { key: 'icon_color', label: 'Colore icone', type: 'color' },

    { type: 'separator', label: 'Testo' },
    { key: 'number_size', label: 'Dimensione numeri (px)', type: 'range', min: 14, max: 36, step: 1 },
    { key: 'number_color', label: 'Colore numeri', type: 'color' },
    { key: 'label_size', label: 'Dimensione etichette (px)', type: 'range', min: 9, max: 16, step: 1 },
    { key: 'label_color', label: 'Colore etichette', type: 'color' },

    { type: 'separator', label: 'Stile item' },
    { key: 'item_bg', label: 'Sfondo singolo item', type: 'color' },
    { key: 'item_border_color', label: 'Bordo item', type: 'color' },
    { key: 'item_border_radius', label: 'Raggio bordi item (px)', type: 'border-radius' },
    { key: 'item_padding', label: 'Padding item (px)', type: 'spacing', max: 24 },

    { type: 'separator', label: 'Contenitore' },
    { key: 'bg_color', label: 'Sfondo contenitore', type: 'color' },
    { key: 'border_radius', label: 'Raggio bordi (px)', type: 'border-radius' },
    { key: 'tile_padding', label: 'Padding (px)', type: 'spacing', max: 32 },
  ],
};
