export default {
  type: 'servicecipat',
  name: 'Codice CIPAT',
  icon: 'dashicons-id',
  category: 'booking',
  defaults: {
    meta_prefix: '_olo_service_',
    layout: 'inline',
    show_icon: true,
    show_label: true,
    label_text: 'Codice CIPAT',
    font_size: '14',
    code_weight: '600',
    label_color: '',
    code_color: '',
    icon_color: '',
    bg_color: '',
    border_color: '',
    border_radius: '8',
    padding: '12',
    align: 'left',
  },
  fields: [
    { type: 'separator', label: 'Sorgente dati' },
    { key: 'meta_prefix', label: 'Tipo servizio', type: 'select', optionsSource: 'metaPrefixes' },

    { type: 'separator', label: 'Layout' },
    { key: 'layout', label: 'Disposizione', type: 'select', options: [
      { value: 'inline', label: 'Icona + testo in riga' },
      { value: 'block', label: 'Impilato (verticale)' },
    ]},
    { key: 'align', label: 'Allineamento', type: 'select', options: [
      { value: 'left', label: 'Sinistra' },
      { value: 'center', label: 'Centro' },
      { value: 'right', label: 'Destra' },
    ]},
    { key: 'show_icon', label: 'Mostra icona', type: 'toggle' },
    { key: 'show_label', label: 'Mostra etichetta', type: 'toggle' },
    { key: 'label_text', label: 'Testo etichetta', type: 'text',
      condition: { field: 'show_label', value: true } },

    { type: 'separator', label: 'Testo' },
    { key: 'font_size', label: 'Dimensione codice (px)', type: 'range', min: 10, max: 24, step: 1 },
    { key: 'code_weight', label: 'Peso codice', type: 'select', options: [
      { value: '400', label: 'Normale' },
      { value: '600', label: 'Semi-grassetto' },
      { value: '700', label: 'Grassetto' },
    ]},
    { key: 'code_color', label: 'Colore codice', type: 'color' },
    { key: 'label_color', label: 'Colore etichetta', type: 'color' },
    { key: 'icon_color', label: 'Colore icona', type: 'color' },

    { type: 'separator', label: 'Contenitore' },
    { key: 'bg_color', label: 'Sfondo', type: 'color' },
    { key: 'border_color', label: 'Bordo', type: 'color' },
    { key: 'border_radius', label: 'Raggio bordi (px)', type: 'border-radius' },
    { key: 'padding', label: 'Padding (px)', type: 'range', min: 0, max: 24, step: 2 },
  ],
};
