export default {
  type: 'servicemushrooms',
  name: 'Funghi Baita',
  icon: 'dashicons-star-filled',
  category: 'booking',
  defaults: {
    meta_prefix: '_olo_service_',
    style: 'inline',
    size: '28',
    gap: '4',
    active_color: '#D97706',
    inactive_color: '#E5E7EB',
    show_label: true,
    label_text: 'Classificazione comfort',
    label_size: '13',
    label_color: '#6B7280',
    label_position: 'top',
    align: 'left',
    bg_color: '',
    border_radius: '0',
    padding: '0',
  },
  fields: [
    { type: 'separator', label: 'Sorgente dati' },
    { key: 'meta_prefix', label: 'Tipo servizio', type: 'select', optionsSource: 'metaPrefixes' },

    { type: 'separator', label: 'Stile funghi' },
    { key: 'style', label: 'Formato', type: 'select', options: [
      { value: 'inline', label: 'Solo funghi' },
      { value: 'with-number', label: 'Funghi + numero' },
    ]},
    { key: 'size', label: 'Dimensione (px)', type: 'range', min: 16, max: 48, step: 2 },
    { key: 'gap', label: 'Spaziatura (px)', type: 'range', min: 0, max: 12, step: 1 },
    { key: 'active_color', label: 'Colore fungo attivo', type: 'color' },
    { key: 'inactive_color', label: 'Colore fungo inattivo', type: 'color' },
    { key: 'align', label: 'Allineamento', type: 'select', options: [
      { value: 'left', label: 'Sinistra' },
      { value: 'center', label: 'Centro' },
      { value: 'right', label: 'Destra' },
    ]},

    { type: 'separator', label: 'Etichetta' },
    { key: 'show_label', label: 'Mostra etichetta', type: 'toggle' },
    { key: 'label_text', label: 'Testo etichetta', type: 'text',
      condition: { field: 'show_label', value: true } },
    { key: 'label_size', label: 'Dimensione testo (px)', type: 'range', min: 10, max: 18, step: 1,
      condition: { field: 'show_label', value: true } },
    { key: 'label_color', label: 'Colore testo', type: 'color',
      condition: { field: 'show_label', value: true } },
    { key: 'label_position', label: 'Posizione etichetta', type: 'select', options: [
      { value: 'top', label: 'Sopra' },
      { value: 'bottom', label: 'Sotto' },
    ], condition: { field: 'show_label', value: true } },

    { type: 'separator', label: 'Sfondo' },
    { key: 'bg_color', label: 'Colore sfondo', type: 'color' },
    { key: 'border_radius', label: 'Raggio bordi (px)', type: 'range', min: 0, max: 20, step: 1 },
    { key: 'padding', label: 'Padding (px)', type: 'range', min: 0, max: 32, step: 2 },
  ],
};
