import { shadowField } from './_shared.js';

export default {
  type: 'servicegallery',
  name: 'Galleria Servizio',
  icon: 'dashicons-images-alt2',
  category: 'booking',
  defaults: {
    meta_prefix: '_olo_service_',
    columns: '3',
    rows: '2',
    gap: '8',
    thumb_height: '200',
    thumb_radius: '12',
    lightbox: true,
    // Effects — automatic
    fx_kenburns: false,
    fx_kenburns_speed: '20',
    fx_kenburns_scale: '1.12',
    // Effects — hover
    fx_hover_zoom: true,
    fx_hover_zoom_scale: '1.08',
    fx_hover_tilt: false,
    fx_hover_tilt_angle: '8',
    // Effects — visual filters
    fx_vignette: false,
    fx_vignette_strength: '40',
    fx_grain: false,
    fx_grain_opacity: '6',
    fx_tint: false,
    fx_tint_color: '',
    fx_tint_opacity: '10',
    fx_tint_blend: 'multiply',
    // "+N" overlay
    more_bg: 'rgba(0,0,0,0.55)',
    more_color: '',
    more_size: '28',
    // Mobile
    mobile_columns: '2',
    shadow: 'none',
  },
  fields: [
    { type: 'separator', label: 'Sorgente dati' },
    { key: 'meta_prefix', label: 'Tipo servizio', type: 'select', optionsSource: 'metaPrefixes' },

    { type: 'separator', label: 'Griglia' },
    { key: 'columns', label: 'Colonne', type: 'range', min: 2, max: 6, step: 1 },
    { key: 'rows', label: 'Righe visibili', type: 'range', min: 1, max: 5, step: 1 },
    { key: 'gap', label: 'Gap (px)', type: 'range', min: 2, max: 24, step: 2 },
    { key: 'thumb_height', label: 'Altezza miniature (px)', type: 'range', min: 100, max: 350, step: 10 },
    { key: 'thumb_radius', label: 'Raggio bordi (px)', type: 'border-radius' },
    { key: 'mobile_columns', label: 'Colonne mobile', type: 'range', min: 1, max: 4, step: 1 },
    { key: 'lightbox', label: 'Lightbox (click per ingrandire)', type: 'toggle' },

    { type: 'separator', label: 'Effetti automatici' },
    { key: 'fx_kenburns', label: 'Ken Burns (zoom cinematico)', type: 'toggle' },
    { key: 'fx_kenburns_speed', label: 'Durata ciclo (sec)', type: 'range', min: 10, max: 40, step: 1,
      condition: { field: 'fx_kenburns', value: true } },
    { key: 'fx_kenburns_scale', label: 'Intensità zoom', type: 'range', min: 1.05, max: 1.25, step: 0.01,
      condition: { field: 'fx_kenburns', value: true } },

    { type: 'separator', label: 'Effetti hover' },
    { key: 'fx_hover_zoom', label: 'Zoom al passaggio', type: 'toggle' },
    { key: 'fx_hover_zoom_scale', label: 'Intensità zoom', type: 'range', min: 1.02, max: 1.15, step: 0.01,
      condition: { field: 'fx_hover_zoom', value: true } },
    { key: 'fx_hover_tilt', label: 'Tilt 3D al passaggio', type: 'toggle' },
    { key: 'fx_hover_tilt_angle', label: 'Angolo rotazione (deg)', type: 'range', min: 3, max: 15, step: 1,
      condition: { field: 'fx_hover_tilt', value: true } },

    { type: 'separator', label: 'Filtri visivi' },
    { key: 'fx_vignette', label: 'Vignettatura (bordi scuri)', type: 'toggle' },
    { key: 'fx_vignette_strength', label: 'Intensità vignettatura', type: 'range', min: 15, max: 60, step: 5,
      condition: { field: 'fx_vignette', value: true } },
    { key: 'fx_grain', label: 'Grana pellicola', type: 'toggle' },
    { key: 'fx_grain_opacity', label: 'Intensità grana (%)', type: 'range', min: 3, max: 20, step: 1,
      condition: { field: 'fx_grain', value: true } },
    { key: 'fx_tint', label: 'Tinta colore', type: 'toggle' },
    { key: 'fx_tint_color', label: 'Colore tinta', type: 'color',
      condition: { field: 'fx_tint', value: true } },
    { key: 'fx_tint_opacity', label: 'Intensità tinta (%)', type: 'range', min: 5, max: 50, step: 5,
      condition: { field: 'fx_tint', value: true } },
    { key: 'fx_tint_blend', label: 'Blend mode', type: 'select', options: [
      { value: 'multiply', label: 'Moltiplica' },
      { value: 'overlay', label: 'Sovrapposizione' },
      { value: 'color', label: 'Colore' },
      { value: 'soft-light', label: 'Luce soffusa' },
      { value: 'hard-light', label: 'Luce forte' },
    ], condition: { field: 'fx_tint', value: true } },

    { type: 'separator', label: 'Indicatore "+N"' },
    { key: 'more_bg', label: 'Sfondo overlay', type: 'color' },
    { key: 'more_color', label: 'Colore testo', type: 'color' },
    { key: 'more_size', label: 'Dimensione testo (px)', type: 'range', min: 16, max: 48, step: 2 },
    ...shadowField,
  ],
};
