export default {
  type: 'serviceaddress',
  name: 'Indirizzo Servizio',
  icon: 'dashicons-location',
  category: 'booking',
  defaults: {
    meta_prefix: '_olo_service_',
    show_icon: true,
    show_label: true,
    label_text: 'Indirizzo',
    show_locality: true,
    show_map_link: true,
    map_link_text: 'Apri in Google Maps',
    font_size: '15',
    label_color: '#6B7280',
    text_color: '#1F2937',
    icon_color: '#EF4444',
    link_color: '#2563EB',
    bg_color: '',
    border_color: '',
    border_radius: '8',
    padding: '16',
  },
  fields: [
    { type: 'separator', label: 'Sorgente dati' },
    { key: 'meta_prefix', label: 'Tipo servizio', type: 'select', optionsSource: 'metaPrefixes' },

    { type: 'separator', label: 'Contenuto' },
    { key: 'show_icon', label: 'Mostra icona', type: 'toggle' },
    { key: 'show_label', label: 'Mostra etichetta', type: 'toggle' },
    { key: 'label_text', label: 'Testo etichetta', type: 'text',
      condition: { field: 'show_label', value: true } },
    { key: 'show_locality', label: 'Mostra località', type: 'toggle' },
    { key: 'show_map_link', label: 'Link Google Maps', type: 'toggle' },
    { key: 'map_link_text', label: 'Testo link', type: 'text',
      condition: { field: 'show_map_link', value: true } },

    { type: 'separator', label: 'Stile' },
    { key: 'font_size', label: 'Dimensione testo (px)', type: 'range', min: 12, max: 22, step: 1 },
    { key: 'text_color', label: 'Colore indirizzo', type: 'color' },
    { key: 'label_color', label: 'Colore etichetta', type: 'color' },
    { key: 'icon_color', label: 'Colore icona', type: 'color' },
    { key: 'link_color', label: 'Colore link', type: 'color' },

    { type: 'separator', label: 'Contenitore' },
    { key: 'bg_color', label: 'Sfondo', type: 'color' },
    { key: 'border_color', label: 'Bordo', type: 'color' },
    { key: 'border_radius', label: 'Raggio bordi (px)', type: 'range', min: 0, max: 20, step: 2 },
    { key: 'padding', label: 'Padding (px)', type: 'range', min: 0, max: 24, step: 2 },
  ],
};
