export default {
  type: 'servicehero',
  name: 'Hero Servizio',
  icon: 'dashicons-format-image',
  category: 'booking',
  defaults: {
    meta_prefix: '_olo_service_',
    hero_height: '400',
    hero_radius: '16',
    hero_overlay: 'gradient',
    overlay_color: '#000000',
    overlay_opacity: '45',
    show_badges: true,
    badge_bg: 'rgba(30,41,59,0.75)',
    badge_color: '#FFFFFF',
    show_title: true,
    title_size: '30',
    title_color: '#FFFFFF',
    title_position: 'bottom',
    show_opening: true,
    opening_bg: '#059669',
    opening_color: '#FFFFFF',
    // Effects
    fx_kenburns: false,
    fx_kenburns_speed: '25',
    fx_kenburns_scale: '1.15',
    fx_shimmer: false,
    fx_shimmer_speed: '6',
    fx_hover_zoom: true,
    fx_hover_zoom_scale: '1.06',
    fx_hover_tilt: false,
    fx_vignette: false,
    fx_vignette_strength: '50',
    fx_grain: false,
    fx_grain_opacity: '8',
    fx_tint: false,
    fx_tint_color: '#1E3A5F',
    fx_tint_opacity: '15',
    fx_tint_blend: 'multiply',
  },
  fields: [
    { type: 'separator', label: 'Sorgente dati' },
    { key: 'meta_prefix', label: 'Tipo servizio', type: 'select', optionsSource: 'metaPrefixes' },

    { type: 'separator', label: 'Layout' },
    { key: 'hero_height', label: 'Altezza (px)', type: 'range', min: 200, max: 600, step: 20 },
    { key: 'hero_radius', label: 'Raggio bordi (px)', type: 'range', min: 0, max: 32, step: 2 },

    { type: 'separator', label: 'Overlay' },
    { key: 'hero_overlay', label: 'Tipo overlay', type: 'select', options: [
      { value: 'gradient', label: 'Sfumatura dal basso' },
      { value: 'radial', label: 'Radiale (centro chiaro)' },
      { value: 'dark', label: 'Scuro uniforme' },
      { value: 'none', label: 'Nessuno' },
    ]},
    { key: 'overlay_color', label: 'Colore sfumatura', type: 'color',
      condition: { field: 'hero_overlay', value: 'gradient' } },
    { key: 'overlay_opacity', label: 'Intensità overlay (%)', type: 'range', min: 10, max: 80, step: 5 },

    { type: 'separator', label: 'Effetti automatici' },
    { key: 'fx_kenburns', label: 'Ken Burns (zoom cinematico)', type: 'toggle' },
    { key: 'fx_kenburns_speed', label: 'Durata ciclo (sec)', type: 'range', min: 10, max: 40, step: 1,
      condition: { field: 'fx_kenburns', value: true } },
    { key: 'fx_kenburns_scale', label: 'Intensità zoom', type: 'range', min: 1.05, max: 1.3, step: 0.01,
      condition: { field: 'fx_kenburns', value: true } },
    { key: 'fx_shimmer', label: 'Shimmer (riflesso luce)', type: 'toggle' },
    { key: 'fx_shimmer_speed', label: 'Velocità shimmer (sec)', type: 'range', min: 3, max: 12, step: 1,
      condition: { field: 'fx_shimmer', value: true } },

    { type: 'separator', label: 'Effetti hover' },
    { key: 'fx_hover_zoom', label: 'Zoom al passaggio', type: 'toggle' },
    { key: 'fx_hover_zoom_scale', label: 'Intensità zoom', type: 'range', min: 1.02, max: 1.15, step: 0.01,
      condition: { field: 'fx_hover_zoom', value: true } },
    { key: 'fx_hover_tilt', label: 'Tilt 3D al passaggio', type: 'toggle' },

    { type: 'separator', label: 'Filtri visivi' },
    { key: 'fx_vignette', label: 'Vignettatura (bordi scuri)', type: 'toggle' },
    { key: 'fx_vignette_strength', label: 'Intensità vignettatura', type: 'range', min: 20, max: 80, step: 5,
      condition: { field: 'fx_vignette', value: true } },
    { key: 'fx_grain', label: 'Grana pellicola', type: 'toggle' },
    { key: 'fx_grain_opacity', label: 'Intensità grana (%)', type: 'range', min: 3, max: 20, step: 1,
      condition: { field: 'fx_grain', value: true } },
    { key: 'fx_tint', label: 'Tinta colore', type: 'toggle' },
    { key: 'fx_tint_color', label: 'Colore tinta', type: 'color',
      condition: { field: 'fx_tint', value: true } },
    { key: 'fx_tint_opacity', label: 'Intensità tinta (%)', type: 'range', min: 5, max: 50, step: 5,
      condition: { field: 'fx_tint', value: true } },
    { key: 'fx_tint_blend', label: 'Blend mode', type: 'select', options: [
      { value: 'multiply', label: 'Moltiplica' },
      { value: 'overlay', label: 'Sovrapposizione' },
      { value: 'color', label: 'Colore' },
      { value: 'soft-light', label: 'Luce soffusa' },
      { value: 'hard-light', label: 'Luce forte' },
    ], condition: { field: 'fx_tint', value: true } },

    { type: 'separator', label: 'Badge' },
    { key: 'show_badges', label: 'Mostra badge', type: 'toggle' },
    { key: 'badge_bg', label: 'Sfondo badge', type: 'color',
      condition: { field: 'show_badges', value: true } },
    { key: 'badge_color', label: 'Testo badge', type: 'color',
      condition: { field: 'show_badges', value: true } },

    { type: 'separator', label: 'Titolo' },
    { key: 'show_title', label: 'Mostra titolo', type: 'toggle' },
    { key: 'title_size', label: 'Dimensione (px)', type: 'range', min: 20, max: 48, step: 1,
      condition: { field: 'show_title', value: true } },
    { key: 'title_color', label: 'Colore', type: 'color',
      condition: { field: 'show_title', value: true } },
    { key: 'title_position', label: 'Posizione', type: 'select', options: [
      { value: 'bottom', label: 'In basso' },
      { value: 'center', label: 'Centro' },
    ], condition: { field: 'show_title', value: true } },

    { type: 'separator', label: 'Ribbon apertura' },
    { key: 'show_opening', label: 'Mostra ribbon apertura', type: 'toggle' },
    { key: 'opening_bg', label: 'Sfondo ribbon', type: 'color',
      condition: { field: 'show_opening', value: true } },
    { key: 'opening_color', label: 'Testo ribbon', type: 'color',
      condition: { field: 'show_opening', value: true } },
  ],
};
