import { shadowField } from './_shared.js';

export default {
  type: 'video',
  name: 'Video',
  icon: 'dashicons-video-alt3',
  category: 'essential',
  defaults: {
    source_type: 'embed',
    video_url: '',
    file_url: '',
    display_mode: '16:9',
    cover_height: '500',
    facade: true,
    autoplay: false,
    muted: false,
    loop: false,
    controls: true,
    start_time: '',
    end_time: '',
    poster_image: '',
    privacy_mode: false,
    show_play_icon: true,
    play_icon_size: '80',
    play_icon_color: '',
    overlay_text: '',
    overlay_color: '#000000',
    overlay_opacity: '0',
    caption: '',
    shadow: 'none',
  },
  fields: [
    { key: 'source_type', label: 'Sorgente', type: 'select', options: [
      { value: 'embed', label: 'YouTube / Vimeo' },
      { value: 'file', label: 'File (MP4 / WebM)' },
    ]},
    { key: 'video_url', label: 'URL video', type: 'text' },
    { key: 'file_url', label: 'File video', type: 'media' },
    { key: 'facade', label: 'Lazy Load (Facade)', type: 'toggle' },
    { key: 'display_mode', label: 'Visualizzazione', type: 'select', options: [
      { value: '16:9', label: '16:9' },
      { value: '4:3', label: '4:3' },
      { value: '1:1', label: '1:1' },
      { value: 'cover', label: 'Cover (altezza fissa)' },
    ]},
    { key: 'cover_height', label: 'Altezza (px)', type: 'range', min: 100, max: 1200, step: 10 },
    { type: 'separator', label: 'Riproduzione' },
    { key: 'autoplay', label: 'Riproduzione automatica', type: 'toggle' },
    { key: 'muted', label: 'Silenziato', type: 'toggle' },
    { key: 'loop', label: 'Ripeti', type: 'toggle' },
    { key: 'controls', label: 'Mostra controlli', type: 'toggle' },
    { key: 'start_time', label: 'Inizio (secondi)', type: 'text' },
    { key: 'end_time', label: 'Fine (secondi)', type: 'text' },
    { type: 'separator', label: 'Poster e overlay' },
    { key: 'poster_image', label: 'Immagine poster', type: 'image' },
    { key: 'show_play_icon', label: 'Mostra icona play', type: 'toggle' },
    { key: 'play_icon_size', label: 'Dimensione icona play (px)', type: 'range', min: 40, max: 160, step: 10 },
    { key: 'play_icon_color', label: 'Colore icona play', type: 'color' },
    { type: 'separator', label: 'Privacy' },
    { key: 'privacy_mode', label: 'Modo privacy (no-cookie)', type: 'toggle' },
    { type: 'separator', label: 'Overlay (cover)' },
    { key: 'overlay_text', label: 'Testo overlay', type: 'textarea' },
    { key: 'overlay_color', label: 'Colore overlay', type: 'color' },
    { key: 'overlay_opacity', label: 'Opacità overlay (%)', type: 'range', min: 0, max: 100, step: 5 },
    { type: 'separator', label: 'Didascalia' },
    { key: 'caption', label: 'Didascalia', type: 'text' },
    ...shadowField,
  ],
};
