import { borderFields, borderDefaults, shadowField } from './_shared.js';

export default {
  type: 'video',
  name: 'Video',
  icon: 'dashicons-video-alt3',
  category: 'media',
  defaults: {
    source_type: 'embed',
    video_url: '',
    file_url: '',
    display_mode: '16:9',
    cover_height: '500',
    autoplay: false,
    muted: false,
    loop: false,
    controls: true,
    overlay_text: '',
    overlay_color: '#000000',
    overlay_opacity: '0',
    caption: '',
    shadow: 'none',
    ...borderDefaults,
  },
  fields: [
    { key: 'source_type', label: 'Sorgente', type: 'select', options: [
      { value: 'embed', label: 'YouTube / Vimeo' },
      { value: 'file', label: 'File (MP4 / WebM)' },
    ]},
    { key: 'video_url', label: 'URL video', type: 'text' },
    { key: 'file_url', label: 'File video', type: 'media' },
    { key: 'display_mode', label: 'Visualizzazione', type: 'select', options: [
      { value: '16:9', label: '16:9' },
      { value: '4:3', label: '4:3' },
      { value: '1:1', label: '1:1' },
      { value: 'cover', label: 'Cover (altezza fissa)' },
    ]},
    { key: 'cover_height', label: 'Altezza (px)', type: 'range', min: 100, max: 1200, step: 10 },
    { type: 'separator', label: 'Riproduzione' },
    { key: 'autoplay', label: 'Riproduzione automatica', type: 'toggle' },
    { key: 'muted', label: 'Silenziato', type: 'toggle' },
    { key: 'loop', label: 'Ripeti', type: 'toggle' },
    { key: 'controls', label: 'Mostra controlli', type: 'toggle' },
    { type: 'separator', label: 'Overlay (cover)' },
    { key: 'overlay_text', label: 'Testo overlay', type: 'editor', mode: 'block' },
    { key: 'overlay_color', label: 'Colore overlay', type: 'color' },
    { key: 'overlay_opacity', label: 'Opacità overlay (%)', type: 'range', min: 0, max: 100, step: 5 },
    { type: 'separator', label: 'Didascalia' },
    { key: 'caption', label: 'Didascalia', type: 'editor', mode: 'inline' },
    shadowField,
    ...borderFields,
  ],
};
