<?php

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

class Olo_Quotation_Tile extends Olo_Tile_Base {

    protected $type     = 'quotation';
    protected $name     = 'Citazione';
    protected $icon     = 'dashicons-format-quote';
    protected $category = 'text';
    protected $defaults = [
        'preset' => 'custom',
        'content'   => 'La vita è ciò che ti succede mentre sei occupato a fare altri progetti.',
        'author'    => 'John Lennon',
        'style'     => 'default',
        'alignment' => 'left',
            'border'                  => [],
        'border_hover'            => [],
        'border_hover_duration'   => 300,
        'border_effect'           => 'none',
        'border_effect_intensity' => 'medium',
        'border_effect_color2'    => '',
        'border_effect_angle'     => 135,
        'border_effect_speed'     => 4,
    ];

    public function get_controls() {
        return [
            [ 'key' => 'content',   'type' => 'textarea', 'label' => 'Quote' ],
            [ 'key' => 'author',    'type' => 'text',     'label' => 'Author' ],
            [ 'key' => 'style',     'type' => 'select',   'label' => 'Style', 'options' => [
                'default' => 'Default',
                'footer'  => 'Footer Citation',
            ]],
            [ 'key' => 'alignment', 'type' => 'select',   'label' => 'Alignment', 'options' => [
                'left'   => 'Left',
                'center' => 'Center',
                'right'  => 'Right',
            ]],
        ];
    }

    public function render( $settings ) {
        $s = wp_parse_args( $settings, $this->defaults );

        $align_class = 'uk-text-' . esc_attr( $s['alignment'] );
        $quot_uid = 'olo-quot-' . wp_unique_id();
        $content_plain = wp_strip_all_tags( $s['content'] ?? '' );
        $author_plain  = $s['author'] ?? '';
        list( $c_tfx_cls, $c_tfx_data ) = $this->tfx_attrs( $s, 'content', $content_plain );
        list( $a_tfx_cls, $a_tfx_data ) = $this->tfx_attrs( $s, 'author', $author_plain );

        ob_start();
        ?>
        <blockquote class="olo-quotation <?php echo $align_class; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- $align_class esc_attr()'d at assignment above; $quot_uid is internally generated ?> <?php echo $quot_uid; ?> olo-quot-preset-<?php echo esc_attr( sanitize_key( $s['preset'] ?? 'custom' ) ); ?>">
            <p class="olo-quot-content<?php echo $c_tfx_cls; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- tfx_attrs() fragments are escaped internally (sanitize_html_class/esc_attr); content is esc_html()'d (nl2br only adds <br /> tags) ?>"<?php echo $c_tfx_data; ?>><?php echo nl2br( esc_html( $content_plain ) ); ?></p>
            <?php if ( ! empty( $s['author'] ) ) : ?>
                <?php if ( $s['style'] === 'footer' ) : ?>
                    <footer><cite class="olo-quot-author<?php echo $a_tfx_cls; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- tfx_attrs() fragments are escaped internally (sanitize_html_class/esc_attr); author is esc_html()'d ?>"<?php echo $a_tfx_data; ?>><?php echo esc_html( $author_plain ); ?></cite></footer>
                <?php else : ?>
                    <p class="uk-text-meta olo-quot-author<?php echo $a_tfx_cls; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- tfx_attrs() fragments are escaped internally (sanitize_html_class/esc_attr); author is esc_html()'d ?>"<?php echo $a_tfx_data; ?>>&mdash; <?php echo esc_html( $author_plain ); ?></p>
                <?php endif; ?>
            <?php endif; ?>
        </blockquote>
        <?php
        $tfx_css = $this->tfx_css( $s, '.' . $quot_uid );
        if ( $tfx_css ) echo '<style>' . $tfx_css . '</style>'; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- CSS generated by Olo_Text_Effects::css() from whitelisted effects, sanitized colors and integer timings
        $this->tfx_print_script();
                // Border system
        $border_css        = $this->build_border_css( $s['border'] ?? [] );
        $border_hover_css  = $this->build_border_hover_css( ".{$quot_uid}", $s['border'] ?? [], $s['border_hover'] ?? [], intval( $s['border_hover_duration'] ?? 300 ) );
        $border_effect_css = $this->build_border_effect_css( ".{$quot_uid}", $s['border'] ?? [], $s );
        if ( $border_css || $border_hover_css || $border_effect_css ) {
            echo '<style>';
            if ( $border_css ) echo ".{$quot_uid}{{$border_css}}"; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- CSS generated by Olo_Tile_Base::build_border_css() from sanitized settings; $quot_uid is internally generated
            echo $border_hover_css . $border_effect_css . '</style>'; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- CSS generated by Olo_Tile_Base::build_border_hover_css()/build_border_effect_css() from sanitized settings
        }
        return ob_get_clean();
    }
}
