<?php

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

class Olo_Totop_Tile extends Olo_Tile_Base {

    protected $type     = 'totop';
    protected $name     = 'Torna su';
    protected $icon     = 'dashicons-arrow-up-alt';
    protected $category = 'navigation';
    protected $defaults = [
        'alignment' => 'right',
        'style'     => 'default',
        'smooth'    => true,
            'border'                  => [],
        'border_hover'            => [],
        'border_hover_duration'   => 300,
        'border_effect'           => 'none',
        'border_effect_intensity' => 'medium',
        'border_effect_color2'    => '',
        'border_effect_angle'     => 135,
        'border_effect_speed'     => 4,
    ];

    public function get_controls() {
        return [
            [ 'key' => 'alignment', 'type' => 'select', 'label' => 'Alignment', 'options' => [
                'left'   => 'Left',
                'center' => 'Center',
                'right'  => 'Right',
            ]],
            [ 'key' => 'style', 'type' => 'select', 'label' => 'Style', 'options' => [
                'default' => 'Default',
                'primary' => 'Primary',
            ]],
            [ 'key' => 'smooth', 'type' => 'toggle', 'label' => 'Smooth Scroll' ],
        ];
    }

    public function render( $settings ) {
        $s = wp_parse_args( $settings, $this->defaults );
        $uid = 'olo-tt-' . wp_rand( 10000, 99999 );

        $align_class = 'uk-text-' . esc_attr( $s['alignment'] );
        $scroll_attr = ! empty( $s['smooth'] ) ? ' uk-scroll' : '';

        ob_start();
        ?>
        <div class="olo-totop <?php echo esc_attr( $uid ); ?> <?php echo esc_attr( $align_class ); ?>">
            <a href="#" uk-totop<?php echo $scroll_attr; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- fixed internal string (' uk-scroll' or '') set by a boolean toggle above ?>></a>
        </div>
        <?php
                // Border system
        $border_css        = $this->build_border_css( $s['border'] ?? [] );
        $border_hover_css  = $this->build_border_hover_css( ".{$uid}", $s['border'] ?? [], $s['border_hover'] ?? [], intval( $s['border_hover_duration'] ?? 300 ) );
        $border_effect_css = $this->build_border_effect_css( ".{$uid}", $s['border'] ?? [], $s );
        if ( $border_css || $border_hover_css || $border_effect_css ) {
            echo '<style>';
            if ( $border_css ) echo ".{$uid}{{$border_css}}"; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- CSS generated by Olo_Tile_Base::build_border_css() (integer-forced widths) for the internally generated uid
            echo $border_hover_css . $border_effect_css . '</style>'; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- CSS generated by Olo_Tile_Base::build_border_hover_css()/build_border_effect_css() shared helpers
        }
        return ob_get_clean();
    }
}
