export default {
  type: 'button',
  name: 'Pulsante',
  icon: 'dashicons-button',
  category: 'content',
  defaults: {
    text: 'Clicca qui',
    url: '#',
    target: '_self',
    alignment: 'center',
    bg_color: '#6366F1',
    text_color: '#FFFFFF',
    border_radius: '6',
    padding_x: '32',
    padding_y: '14',
    font_size: '16',
    full_width: false,
  },
  fields: [
    { key: 'text', label: 'Testo pulsante', type: 'text' },
    { key: 'url', label: 'URL', type: 'text' },
    { key: 'target', label: 'Apri in', type: 'select', options: [
      { value: '_self', label: 'Stessa finestra' },
      { value: '_blank', label: 'Nuova scheda' },
    ]},
    { key: 'alignment', label: 'Allineamento', type: 'select', options: [
      { value: 'left', label: 'Sinistra' },
      { value: 'center', label: 'Centro' },
      { value: 'right', label: 'Destra' },
    ]},
    { key: 'bg_color', label: 'Colore sfondo', type: 'color' },
    { key: 'text_color', label: 'Colore testo', type: 'color' },
    { key: 'border_radius', label: 'Border Radius', type: 'border-radius' },
    { key: 'padding_x', label: 'Padding O (px)', type: 'range', min: 8, max: 80, step: 4 },
    { key: 'padding_y', label: 'Padding V (px)', type: 'range', min: 4, max: 40, step: 2 },
    { key: 'font_size', label: 'Dim. carattere (px)', type: 'range', min: 12, max: 32, step: 1 },
    { key: 'full_width', label: 'Larghezza piena', type: 'toggle' },
  ],
};
