export default {
  type: 'counter',
  name: 'Contatore',
  icon: 'dashicons-performance',
  category: 'content',
  defaults: {
    number: '1250',
    label: 'Clienti soddisfatti',
    prefix: '',
    suffix: '+',
    icon_emoji: '\uD83C\uDFC6',
    text_color: '#F3F4F6',
    number_font_size: '48',
    number_font_weight: '700',
    label_color: '',
    label_font_size: '14',
    label_font_weight: '400',
    padding: '32',
  },
  fields: [
    { key: 'number', label: 'Numero', type: 'text' },
    { key: 'label', label: 'Etichetta', type: 'editor', mode: 'inline' },
    { key: 'prefix', label: 'Prefisso', type: 'text' },
    { key: 'suffix', label: 'Suffisso', type: 'text' },
    { key: 'icon_emoji', label: 'Icona / Emoji', type: 'icon' },
    { type: 'separator', label: 'Tipografia' },
    { key: 'number_font_size', label: 'Dim. numero (px)', type: 'range', min: 20, max: 120, step: 2 },
    { key: 'number_font_weight', label: 'Peso numero', type: 'select', options: [
      { value: '400', label: 'Normale' },
      { value: '500', label: 'Medio' },
      { value: '600', label: 'Semi-grassetto' },
      { value: '700', label: 'Grassetto' },
      { value: '800', label: 'Extra-grassetto' },
      { value: '900', label: 'Nero' },
    ]},
    { key: 'label_font_size', label: 'Dim. etichetta (px)', type: 'range', min: 10, max: 32, step: 1 },
    { key: 'label_font_weight', label: 'Peso etichetta', type: 'select', options: [
      { value: '400', label: 'Normale' },
      { value: '500', label: 'Medio' },
      { value: '600', label: 'Semi-grassetto' },
      { value: '700', label: 'Grassetto' },
    ]},
    { key: 'padding', label: 'Padding (px)', type: 'range', min: 0, max: 80, step: 4 },
    { type: 'separator', label: 'Colori' },
    { key: 'text_color', label: 'Colore testo', type: 'color' },
    { key: 'label_color', label: 'Colore etichetta', type: 'color' },
  ],
};
