export default {
  type: 'grid',
  name: 'Griglia',
  icon: 'dashicons-grid-view',
  category: 'content',
  defaults: {
    items: [
      { id: 'g-1', title: 'Elemento 1', content: 'Descrizione del primo elemento.', image: '', tag: 'all' },
      { id: 'g-2', title: 'Elemento 2', content: 'Descrizione del secondo elemento.', image: '', tag: 'all' },
      { id: 'g-3', title: 'Elemento 3', content: 'Descrizione del terzo elemento.', image: '', tag: 'all' },
    ],
    columns: '3',
    gap: 'default',
    show_filter: false,
    filter_style: 'pills',
    filter_align: 'left',
    masonry: false,
    card_style: 'default',
  },
  fields: [
    { key: 'items', label: 'Elementi', type: 'content-items', supportsDynamic: true,
      itemFields: [
        { key: 'title', label: 'Titolo', type: 'text' },
        { key: 'content', label: 'Contenuto', type: 'textarea' },
        { key: 'image', label: 'Immagine', type: 'image' },
        { key: 'tag', label: 'Tag', type: 'text' },
      ],
      newItemDefaults: { title: 'Nuovo elemento', content: '', image: '', tag: 'all' },
    },
    { key: 'columns', label: 'Colonne', type: 'select', options: [
      { value: '1', label: '1' },
      { value: '2', label: '2' },
      { value: '3', label: '3' },
      { value: '4', label: '4' },
      { value: '5', label: '5' },
      { value: '6', label: '6' },
    ]},
    { key: 'gap', label: 'Gap', type: 'select', options: [
      { value: 'collapse', label: 'Collassato' },
      { value: 'small', label: 'Piccolo' },
      { value: 'default', label: 'Predefinito' },
      { value: 'medium', label: 'Medio' },
      { value: 'large', label: 'Grande' },
    ]},
    { key: 'show_filter', label: 'Mostra filtro', type: 'toggle' },
    { key: 'filter_style', label: 'Stile filtro', type: 'select', options: [
      { value: 'pills', label: 'Pills' },
      { value: 'minimal', label: 'Minimale' },
    ], condition: { field: 'show_filter', value: true } },
    { key: 'filter_align', label: 'Allineamento filtri', type: 'select', options: [
      { value: 'left', label: 'Sinistra' },
      { value: 'center', label: 'Centro' },
      { value: 'right', label: 'Destra' },
    ], condition: { field: 'show_filter', value: true } },
    { key: 'masonry', label: 'Masonry', type: 'toggle' },
    { key: 'card_style', label: 'Stile card', type: 'select', options: [
      { value: 'default', label: 'Predefinito' },
      { value: 'minimal', label: 'Minimale' },
    ]},
  ],
};
