export default {
  type: 'iconbox',
  name: 'Icon Box',
  icon: 'dashicons-star-filled',
  category: 'content',
  defaults: {
    icon_emoji: '\uD83D\uDE80',
    title: 'Titolo funzionalità',
    description: 'Una breve descrizione.',
    link_url: '',
    link_text: 'Scopri di più',
    alignment: 'center',
    text_color: '#F3F4F6',
    icon_size: '3',
    title_font_size: '20',
    title_font_weight: '600',
    link_color: '#6366F1',
  },
  fields: [
    { key: 'icon_emoji', label: 'Icona / Emoji', type: 'icon' },
    { key: 'title', label: 'Titolo', type: 'editor', mode: 'inline' },
    { key: 'description', label: 'Descrizione', type: 'editor', mode: 'block' },
    { key: 'link_url', label: 'URL link', type: 'text' },
    { key: 'link_text', label: 'Testo link', type: 'editor', mode: 'inline' },
    { key: 'alignment', label: 'Allineamento', type: 'select', options: [
      { value: 'left', label: 'Sinistra' },
      { value: 'center', label: 'Centro' },
      { value: 'right', label: 'Destra' },
    ]},
    { type: 'separator', label: 'Tipografia' },
    { key: 'icon_size', label: 'Dimensione icona (em)', type: 'range', min: 1, max: 8, step: 0.5 },
    { key: 'title_font_size', label: 'Dimensione titolo (px)', type: 'range', min: 14, max: 48, step: 1 },
    { key: 'title_font_weight', label: 'Peso titolo', type: 'select', options: [
      { value: '400', label: 'Normale' },
      { value: '500', label: 'Medio' },
      { value: '600', label: 'Semi-grassetto' },
      { value: '700', label: 'Grassetto' },
    ]},
    { type: 'separator', label: 'Colori' },
    { key: 'text_color', label: 'Colore testo', type: 'color' },
    { key: 'link_color', label: 'Colore link', type: 'color' },
  ],
};
