export default {
  type: 'pricing',
  name: 'Listino prezzi',
  icon: 'dashicons-money-alt',
  category: 'content',
  defaults: {
    plan_name: 'Piano Pro',
    price: '29',
    period: '/mese',
    features: 'Progetti illimitati\n10 GB di spazio',
    cta_text: 'Inizia ora',
    cta_url: '#',
    is_popular: false,
    bg_color: '#1F2937',
    accent_color: '#6366F1',
    text_color: '#F3F4F6',
  },
  fields: [
    { key: 'plan_name', label: 'Nome piano', type: 'editor', mode: 'inline' },
    { key: 'price', label: 'Prezzo', type: 'text' },
    { key: 'period', label: 'Periodo', type: 'editor', mode: 'inline' },
    { key: 'features', label: 'Funzionalità (una per riga)', type: 'textarea' },
    { key: 'cta_text', label: 'Testo pulsante', type: 'editor', mode: 'inline' },
    { key: 'cta_url', label: 'URL pulsante', type: 'text' },
    { key: 'is_popular', label: 'Badge popolare', type: 'toggle' },
    { key: 'bg_color', label: 'Colore sfondo', type: 'color' },
    { key: 'accent_color', label: 'Colore accento', type: 'color' },
    { key: 'text_color', label: 'Colore testo', type: 'color' },
  ],
};
