#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Riempie i msgstr nei file .po di oloele-property-map per 11 lingue.

Le stringhe originali (msgid) sono in INGLESE.
Le 11 lingue target sono: cs_CZ, de_DE, en_US, es_ES, fr_FR, hu_HU, ja, nl_NL,
pl_PL, pt_BR, ru_RU.

Aggiorna anche header:
- Last-Translator: Claude (AI translation)
- PO-Revision-Date: 2026-05-21 12:00+0000
"""

import os
import re
import sys

LANG_DIR = r"D:\TECNICA\oloele-property-map\languages"

LANGS = [
    "cs_CZ", "de_DE", "en_US", "es_ES", "fr_FR",
    "hu_HU", "ja", "nl_NL", "pl_PL", "pt_BR", "ru_RU",
]

# Dizionario: msgid (EN) -> dict { lang_code: traduzione }
# Le traduzioni sono per la UI di un widget Elementor che mostra una mappa
# interattiva di immobili (real estate).
TRANSLATIONS = {
    "%1$s requires %2$s to work.": {
        "cs_CZ": "%1$s vyžaduje %2$s pro správnou funkci.",
        "de_DE": "%1$s benötigt %2$s, um zu funktionieren.",
        "en_US": "%1$s requires %2$s to work.",
        "es_ES": "%1$s necesita %2$s para funcionar.",
        "fr_FR": "%1$s nécessite %2$s pour fonctionner.",
        "hu_HU": "A(z) %1$s működéséhez %2$s szükséges.",
        "ja": "%1$s を動作させるには %2$s が必要です。",
        "nl_NL": "%1$s vereist %2$s om te werken.",
        "pl_PL": "%1$s wymaga %2$s do działania.",
        "pt_BR": "%1$s requer %2$s para funcionar.",
        "ru_RU": "Для работы %1$s требуется %2$s.",
    },
    "Data Source": {
        "cs_CZ": "Zdroj dat",
        "de_DE": "Datenquelle",
        "en_US": "Data Source",
        "es_ES": "Fuente de datos",
        "fr_FR": "Source de données",
        "hu_HU": "Adatforrás",
        "ja": "データソース",
        "nl_NL": "Gegevensbron",
        "pl_PL": "Źródło danych",
        "pt_BR": "Fonte de dados",
        "ru_RU": "Источник данных",
    },
    "Field preset": {
        "cs_CZ": "Přednastavení polí",
        "de_DE": "Feldvorlage",
        "en_US": "Field preset",
        "es_ES": "Preajuste de campos",
        "fr_FR": "Préréglage des champs",
        "hu_HU": "Mező-előbeállítás",
        "ja": "フィールドプリセット",
        "nl_NL": "Veldvoorinstelling",
        "pl_PL": "Predefiniowane pola",
        "pt_BR": "Predefinição de campos",
        "ru_RU": "Шаблон полей",
    },
    "Custom": {
        "cs_CZ": "Vlastní",
        "de_DE": "Benutzerdefiniert",
        "en_US": "Custom",
        "es_ES": "Personalizado",
        "fr_FR": "Personnalisé",
        "hu_HU": "Egyéni",
        "ja": "カスタム",
        "nl_NL": "Aangepast",
        "pl_PL": "Niestandardowe",
        "pt_BR": "Personalizado",
        "ru_RU": "Пользовательский",
    },
    "Post type": {
        "cs_CZ": "Typ příspěvku",
        "de_DE": "Beitragstyp",
        "en_US": "Post type",
        "es_ES": "Tipo de contenido",
        "fr_FR": "Type de contenu",
        "hu_HU": "Bejegyzéstípus",
        "ja": "投稿タイプ",
        "nl_NL": "Berichttype",
        "pl_PL": "Typ wpisu",
        "pt_BR": "Tipo de post",
        "ru_RU": "Тип записи",
    },
    "Max properties": {
        "cs_CZ": "Maximální počet nemovitostí",
        "de_DE": "Maximale Immobilien",
        "en_US": "Max properties",
        "es_ES": "Máx. de propiedades",
        "fr_FR": "Nombre max. de biens",
        "hu_HU": "Max. ingatlanok",
        "ja": "物件の最大数",
        "nl_NL": "Max. eigendommen",
        "pl_PL": "Maks. nieruchomości",
        "pt_BR": "Máx. de imóveis",
        "ru_RU": "Макс. объектов",
    },
    "Field Mapping": {
        "cs_CZ": "Mapování polí",
        "de_DE": "Feldzuordnung",
        "en_US": "Field Mapping",
        "es_ES": "Mapeo de campos",
        "fr_FR": "Mappage des champs",
        "hu_HU": "Mezőleképezés",
        "ja": "フィールドマッピング",
        "nl_NL": "Veldtoewijzing",
        "pl_PL": "Mapowanie pól",
        "pt_BR": "Mapeamento de campos",
        "ru_RU": "Сопоставление полей",
    },
    "Coordinates format": {
        "cs_CZ": "Formát souřadnic",
        "de_DE": "Koordinatenformat",
        "en_US": "Coordinates format",
        "es_ES": "Formato de coordenadas",
        "fr_FR": "Format des coordonnées",
        "hu_HU": "Koordináta formátum",
        "ja": "座標形式",
        "nl_NL": "Coördinatenformaat",
        "pl_PL": "Format współrzędnych",
        "pt_BR": "Formato das coordenadas",
        "ru_RU": "Формат координат",
    },
    "Separate fields (lat + lng)": {
        "cs_CZ": "Oddělená pole (lat + lng)",
        "de_DE": "Getrennte Felder (lat + lng)",
        "en_US": "Separate fields (lat + lng)",
        "es_ES": "Campos separados (lat + lng)",
        "fr_FR": "Champs séparés (lat + lng)",
        "hu_HU": "Külön mezők (lat + lng)",
        "ja": "個別フィールド (lat + lng)",
        "nl_NL": "Aparte velden (lat + lng)",
        "pl_PL": "Osobne pola (lat + lng)",
        "pt_BR": "Campos separados (lat + lng)",
        "ru_RU": "Раздельные поля (lat + lng)",
    },
    "Single field (lat,lng)": {
        "cs_CZ": "Jedno pole (lat,lng)",
        "de_DE": "Einzelnes Feld (lat,lng)",
        "en_US": "Single field (lat,lng)",
        "es_ES": "Campo único (lat,lng)",
        "fr_FR": "Champ unique (lat,lng)",
        "hu_HU": "Egyetlen mező (lat,lng)",
        "ja": "単一フィールド (lat,lng)",
        "nl_NL": "Eén veld (lat,lng)",
        "pl_PL": "Pojedyncze pole (lat,lng)",
        "pt_BR": "Campo único (lat,lng)",
        "ru_RU": "Одно поле (lat,lng)",
    },
    "Meta key: Latitude": {
        "cs_CZ": "Meta klíč: Zeměpisná šířka",
        "de_DE": "Meta-Schlüssel: Breitengrad",
        "en_US": "Meta key: Latitude",
        "es_ES": "Clave meta: Latitud",
        "fr_FR": "Clé meta : Latitude",
        "hu_HU": "Meta kulcs: Szélesség",
        "ja": "メタキー: 緯度",
        "nl_NL": "Metasleutel: Breedtegraad",
        "pl_PL": "Klucz meta: Szerokość",
        "pt_BR": "Chave meta: Latitude",
        "ru_RU": "Мета-ключ: Широта",
    },
    "Meta key: Longitude": {
        "cs_CZ": "Meta klíč: Zeměpisná délka",
        "de_DE": "Meta-Schlüssel: Längengrad",
        "en_US": "Meta key: Longitude",
        "es_ES": "Clave meta: Longitud",
        "fr_FR": "Clé meta : Longitude",
        "hu_HU": "Meta kulcs: Hosszúság",
        "ja": "メタキー: 経度",
        "nl_NL": "Metasleutel: Lengtegraad",
        "pl_PL": "Klucz meta: Długość",
        "pt_BR": "Chave meta: Longitude",
        "ru_RU": "Мета-ключ: Долгота",
    },
    "Meta key: Coordinates (lat,lng)": {
        "cs_CZ": "Meta klíč: Souřadnice (lat,lng)",
        "de_DE": "Meta-Schlüssel: Koordinaten (lat,lng)",
        "en_US": "Meta key: Coordinates (lat,lng)",
        "es_ES": "Clave meta: Coordenadas (lat,lng)",
        "fr_FR": "Clé meta : Coordonnées (lat,lng)",
        "hu_HU": "Meta kulcs: Koordináták (lat,lng)",
        "ja": "メタキー: 座標 (lat,lng)",
        "nl_NL": "Metasleutel: Coördinaten (lat,lng)",
        "pl_PL": "Klucz meta: Współrzędne (lat,lng)",
        "pt_BR": "Chave meta: Coordenadas (lat,lng)",
        "ru_RU": "Мета-ключ: Координаты (lat,lng)",
    },
    "Meta key: Price": {
        "cs_CZ": "Meta klíč: Cena",
        "de_DE": "Meta-Schlüssel: Preis",
        "en_US": "Meta key: Price",
        "es_ES": "Clave meta: Precio",
        "fr_FR": "Clé meta : Prix",
        "hu_HU": "Meta kulcs: Ár",
        "ja": "メタキー: 価格",
        "nl_NL": "Metasleutel: Prijs",
        "pl_PL": "Klucz meta: Cena",
        "pt_BR": "Chave meta: Preço",
        "ru_RU": "Мета-ключ: Цена",
    },
    "Meta key: Bedrooms": {
        "cs_CZ": "Meta klíč: Ložnice",
        "de_DE": "Meta-Schlüssel: Schlafzimmer",
        "en_US": "Meta key: Bedrooms",
        "es_ES": "Clave meta: Dormitorios",
        "fr_FR": "Clé meta : Chambres",
        "hu_HU": "Meta kulcs: Hálószobák",
        "ja": "メタキー: ベッドルーム",
        "nl_NL": "Metasleutel: Slaapkamers",
        "pl_PL": "Klucz meta: Sypialnie",
        "pt_BR": "Chave meta: Quartos",
        "ru_RU": "Мета-ключ: Спальни",
    },
    "Meta key: Bathrooms": {
        "cs_CZ": "Meta klíč: Koupelny",
        "de_DE": "Meta-Schlüssel: Badezimmer",
        "en_US": "Meta key: Bathrooms",
        "es_ES": "Clave meta: Baños",
        "fr_FR": "Clé meta : Salles de bain",
        "hu_HU": "Meta kulcs: Fürdőszobák",
        "ja": "メタキー: バスルーム",
        "nl_NL": "Metasleutel: Badkamers",
        "pl_PL": "Klucz meta: Łazienki",
        "pt_BR": "Chave meta: Banheiros",
        "ru_RU": "Мета-ключ: Ванные комнаты",
    },
    "Meta key: Area (sqm)": {
        "cs_CZ": "Meta klíč: Plocha (m²)",
        "de_DE": "Meta-Schlüssel: Fläche (m²)",
        "en_US": "Meta key: Area (sqm)",
        "es_ES": "Clave meta: Superficie (m²)",
        "fr_FR": "Clé meta : Surface (m²)",
        "hu_HU": "Meta kulcs: Terület (m²)",
        "ja": "メタキー: 面積 (m²)",
        "nl_NL": "Metasleutel: Oppervlakte (m²)",
        "pl_PL": "Klucz meta: Powierzchnia (m²)",
        "pt_BR": "Chave meta: Área (m²)",
        "ru_RU": "Мета-ключ: Площадь (м²)",
    },
    "Meta key: Rooms": {
        "cs_CZ": "Meta klíč: Pokoje",
        "de_DE": "Meta-Schlüssel: Zimmer",
        "en_US": "Meta key: Rooms",
        "es_ES": "Clave meta: Habitaciones",
        "fr_FR": "Clé meta : Pièces",
        "hu_HU": "Meta kulcs: Szobák",
        "ja": "メタキー: 部屋",
        "nl_NL": "Metasleutel: Kamers",
        "pl_PL": "Klucz meta: Pokoje",
        "pt_BR": "Chave meta: Cômodos",
        "ru_RU": "Мета-ключ: Комнаты",
    },
    "Meta key: Address": {
        "cs_CZ": "Meta klíč: Adresa",
        "de_DE": "Meta-Schlüssel: Adresse",
        "en_US": "Meta key: Address",
        "es_ES": "Clave meta: Dirección",
        "fr_FR": "Clé meta : Adresse",
        "hu_HU": "Meta kulcs: Cím",
        "ja": "メタキー: 住所",
        "nl_NL": "Metasleutel: Adres",
        "pl_PL": "Klucz meta: Adres",
        "pt_BR": "Chave meta: Endereço",
        "ru_RU": "Мета-ключ: Адрес",
    },
    "Taxonomy: Property type": {
        "cs_CZ": "Taxonomie: Typ nemovitosti",
        "de_DE": "Taxonomie: Immobilientyp",
        "en_US": "Taxonomy: Property type",
        "es_ES": "Taxonomía: Tipo de propiedad",
        "fr_FR": "Taxonomie : Type de bien",
        "hu_HU": "Taxonómia: Ingatlantípus",
        "ja": "タクソノミー: 物件タイプ",
        "nl_NL": "Taxonomie: Type eigendom",
        "pl_PL": "Taksonomia: Typ nieruchomości",
        "pt_BR": "Taxonomia: Tipo de imóvel",
        "ru_RU": "Таксономия: Тип недвижимости",
    },
    "Taxonomy: City": {
        "cs_CZ": "Taxonomie: Město",
        "de_DE": "Taxonomie: Stadt",
        "en_US": "Taxonomy: City",
        "es_ES": "Taxonomía: Ciudad",
        "fr_FR": "Taxonomie : Ville",
        "hu_HU": "Taxonómia: Város",
        "ja": "タクソノミー: 市区町村",
        "nl_NL": "Taxonomie: Stad",
        "pl_PL": "Taksonomia: Miasto",
        "pt_BR": "Taxonomia: Cidade",
        "ru_RU": "Таксономия: Город",
    },
    "Listing type (sale/rent)": {
        "cs_CZ": "Typ nabídky (prodej/pronájem)",
        "de_DE": "Angebotstyp (Verkauf/Vermietung)",
        "en_US": "Listing type (sale/rent)",
        "es_ES": "Tipo de anuncio (venta/alquiler)",
        "fr_FR": "Type d'annonce (vente/location)",
        "hu_HU": "Hirdetés típusa (eladás/bérlés)",
        "ja": "リストタイプ (販売/賃貸)",
        "nl_NL": "Type aanbieding (verkoop/verhuur)",
        "pl_PL": "Typ ogłoszenia (sprzedaż/wynajem)",
        "pt_BR": "Tipo de anúncio (venda/aluguel)",
        "ru_RU": "Тип объявления (продажа/аренда)",
    },
    "From taxonomy": {
        "cs_CZ": "Z taxonomie",
        "de_DE": "Aus Taxonomie",
        "en_US": "From taxonomy",
        "es_ES": "Desde taxonomía",
        "fr_FR": "Depuis taxonomie",
        "hu_HU": "Taxonómiából",
        "ja": "タクソノミーから",
        "nl_NL": "Vanuit taxonomie",
        "pl_PL": "Z taksonomii",
        "pt_BR": "Da taxonomia",
        "ru_RU": "Из таксономии",
    },
    "From meta field": {
        "cs_CZ": "Z meta pole",
        "de_DE": "Aus Meta-Feld",
        "en_US": "From meta field",
        "es_ES": "Desde campo meta",
        "fr_FR": "Depuis champ meta",
        "hu_HU": "Meta mezőből",
        "ja": "メタフィールドから",
        "nl_NL": "Vanuit metaveld",
        "pl_PL": "Z pola meta",
        "pt_BR": "Do campo meta",
        "ru_RU": "Из мета-поля",
    },
    "Taxonomy: Listing status": {
        "cs_CZ": "Taxonomie: Stav nabídky",
        "de_DE": "Taxonomie: Angebotsstatus",
        "en_US": "Taxonomy: Listing status",
        "es_ES": "Taxonomía: Estado del anuncio",
        "fr_FR": "Taxonomie : Statut de l'annonce",
        "hu_HU": "Taxonómia: Hirdetés állapota",
        "ja": "タクソノミー: リストステータス",
        "nl_NL": "Taxonomie: Status aanbieding",
        "pl_PL": "Taksonomia: Status ogłoszenia",
        "pt_BR": "Taxonomia: Status do anúncio",
        "ru_RU": "Таксономия: Статус объявления",
    },
    "Meta key: Listing type": {
        "cs_CZ": "Meta klíč: Typ nabídky",
        "de_DE": "Meta-Schlüssel: Angebotstyp",
        "en_US": "Meta key: Listing type",
        "es_ES": "Clave meta: Tipo de anuncio",
        "fr_FR": "Clé meta : Type d'annonce",
        "hu_HU": "Meta kulcs: Hirdetés típusa",
        "ja": "メタキー: リストタイプ",
        "nl_NL": "Metasleutel: Type aanbieding",
        "pl_PL": "Klucz meta: Typ ogłoszenia",
        "pt_BR": "Chave meta: Tipo de anúncio",
        "ru_RU": "Мета-ключ: Тип объявления",
    },
    "Term slug for \\\"Sale\\\"": {
        "cs_CZ": "Slug termínu pro „Prodej“",
        "de_DE": "Term-Slug für „Verkauf“",
        "en_US": "Term slug for \\\"Sale\\\"",
        "es_ES": "Slug del término para «Venta»",
        "fr_FR": "Slug du terme pour « Vente »",
        "hu_HU": "Kifejezés slug az „Eladás”-hoz",
        "ja": "「販売」の用語スラッグ",
        "nl_NL": "Term-slug voor \\\"Verkoop\\\"",
        "pl_PL": "Slug terminu dla „Sprzedaż”",
        "pt_BR": "Slug do termo para \\\"Venda\\\"",
        "ru_RU": "Слаг термина для «Продажа»",
    },
    "Term slug for \\\"Rent\\\"": {
        "cs_CZ": "Slug termínu pro „Pronájem“",
        "de_DE": "Term-Slug für „Vermietung“",
        "en_US": "Term slug for \\\"Rent\\\"",
        "es_ES": "Slug del término para «Alquiler»",
        "fr_FR": "Slug du terme pour « Location »",
        "hu_HU": "Kifejezés slug a „Bérlés”-hez",
        "ja": "「賃貸」の用語スラッグ",
        "nl_NL": "Term-slug voor \\\"Verhuur\\\"",
        "pl_PL": "Slug terminu dla „Wynajem”",
        "pt_BR": "Slug do termo para \\\"Aluguel\\\"",
        "ru_RU": "Слаг термина для «Аренда»",
    },
    "Layout": {
        "cs_CZ": "Rozvržení",
        "de_DE": "Layout",
        "en_US": "Layout",
        "es_ES": "Diseño",
        "fr_FR": "Mise en page",
        "hu_HU": "Elrendezés",
        "ja": "レイアウト",
        "nl_NL": "Lay-out",
        "pl_PL": "Układ",
        "pt_BR": "Layout",
        "ru_RU": "Макет",
    },
    "Map position": {
        "cs_CZ": "Pozice mapy",
        "de_DE": "Kartenposition",
        "en_US": "Map position",
        "es_ES": "Posición del mapa",
        "fr_FR": "Position de la carte",
        "hu_HU": "Térkép pozíciója",
        "ja": "地図の位置",
        "nl_NL": "Kaartpositie",
        "pl_PL": "Pozycja mapy",
        "pt_BR": "Posição do mapa",
        "ru_RU": "Положение карты",
    },
    "Left": {
        "cs_CZ": "Vlevo",
        "de_DE": "Links",
        "en_US": "Left",
        "es_ES": "Izquierda",
        "fr_FR": "Gauche",
        "hu_HU": "Bal",
        "ja": "左",
        "nl_NL": "Links",
        "pl_PL": "Lewa",
        "pt_BR": "Esquerda",
        "ru_RU": "Слева",
    },
    "Right": {
        "cs_CZ": "Vpravo",
        "de_DE": "Rechts",
        "en_US": "Right",
        "es_ES": "Derecha",
        "fr_FR": "Droite",
        "hu_HU": "Jobb",
        "ja": "右",
        "nl_NL": "Rechts",
        "pl_PL": "Prawa",
        "pt_BR": "Direita",
        "ru_RU": "Справа",
    },
    "Map width": {
        "cs_CZ": "Šířka mapy",
        "de_DE": "Kartenbreite",
        "en_US": "Map width",
        "es_ES": "Ancho del mapa",
        "fr_FR": "Largeur de la carte",
        "hu_HU": "Térkép szélessége",
        "ja": "地図の幅",
        "nl_NL": "Kaartbreedte",
        "pl_PL": "Szerokość mapy",
        "pt_BR": "Largura do mapa",
        "ru_RU": "Ширина карты",
    },
    "Height (px)": {
        "cs_CZ": "Výška (px)",
        "de_DE": "Höhe (px)",
        "en_US": "Height (px)",
        "es_ES": "Altura (px)",
        "fr_FR": "Hauteur (px)",
        "hu_HU": "Magasság (px)",
        "ja": "高さ (px)",
        "nl_NL": "Hoogte (px)",
        "pl_PL": "Wysokość (px)",
        "pt_BR": "Altura (px)",
        "ru_RU": "Высота (px)",
    },
    "Results per page": {
        "cs_CZ": "Výsledků na stránku",
        "de_DE": "Ergebnisse pro Seite",
        "en_US": "Results per page",
        "es_ES": "Resultados por página",
        "fr_FR": "Résultats par page",
        "hu_HU": "Találatok oldalanként",
        "ja": "ページあたりの結果数",
        "nl_NL": "Resultaten per pagina",
        "pl_PL": "Wyników na stronę",
        "pt_BR": "Resultados por página",
        "ru_RU": "Результатов на страницу",
    },
    "Filter columns": {
        "cs_CZ": "Sloupce filtrů",
        "de_DE": "Filterspalten",
        "en_US": "Filter columns",
        "es_ES": "Columnas de filtros",
        "fr_FR": "Colonnes de filtres",
        "hu_HU": "Szűrőoszlopok",
        "ja": "フィルター列",
        "nl_NL": "Filterkolommen",
        "pl_PL": "Kolumny filtrów",
        "pt_BR": "Colunas de filtros",
        "ru_RU": "Колонки фильтров",
    },
    "Grid view columns": {
        "cs_CZ": "Sloupce mřížkového zobrazení",
        "de_DE": "Spalten der Rasteransicht",
        "en_US": "Grid view columns",
        "es_ES": "Columnas de vista de cuadrícula",
        "fr_FR": "Colonnes de la vue grille",
        "hu_HU": "Rácsnézet oszlopai",
        "ja": "グリッドビューの列",
        "nl_NL": "Kolommen rasterweergave",
        "pl_PL": "Kolumny widoku siatki",
        "pt_BR": "Colunas da visualização em grade",
        "ru_RU": "Колонки сеточного вида",
    },
    "Map": {
        "cs_CZ": "Mapa",
        "de_DE": "Karte",
        "en_US": "Map",
        "es_ES": "Mapa",
        "fr_FR": "Carte",
        "hu_HU": "Térkép",
        "ja": "地図",
        "nl_NL": "Kaart",
        "pl_PL": "Mapa",
        "pt_BR": "Mapa",
        "ru_RU": "Карта",
    },
    "Initial zoom": {
        "cs_CZ": "Počáteční přiblížení",
        "de_DE": "Anfängliche Zoomstufe",
        "en_US": "Initial zoom",
        "es_ES": "Zoom inicial",
        "fr_FR": "Zoom initial",
        "hu_HU": "Kezdeti nagyítás",
        "ja": "初期ズーム",
        "nl_NL": "Beginzoom",
        "pl_PL": "Początkowe powiększenie",
        "pt_BR": "Zoom inicial",
        "ru_RU": "Начальный масштаб",
    },
    "Center latitude": {
        "cs_CZ": "Středová zeměpisná šířka",
        "de_DE": "Mittlerer Breitengrad",
        "en_US": "Center latitude",
        "es_ES": "Latitud central",
        "fr_FR": "Latitude du centre",
        "hu_HU": "Középpont szélessége",
        "ja": "中心の緯度",
        "nl_NL": "Centrale breedtegraad",
        "pl_PL": "Szerokość środka",
        "pt_BR": "Latitude central",
        "ru_RU": "Широта центра",
    },
    "Center longitude": {
        "cs_CZ": "Středová zeměpisná délka",
        "de_DE": "Mittlerer Längengrad",
        "en_US": "Center longitude",
        "es_ES": "Longitud central",
        "fr_FR": "Longitude du centre",
        "hu_HU": "Középpont hosszúsága",
        "ja": "中心の経度",
        "nl_NL": "Centrale lengtegraad",
        "pl_PL": "Długość środka",
        "pt_BR": "Longitude central",
        "ru_RU": "Долгота центра",
    },
    "Marker color": {
        "cs_CZ": "Barva značky",
        "de_DE": "Markerfarbe",
        "en_US": "Marker color",
        "es_ES": "Color del marcador",
        "fr_FR": "Couleur du marqueur",
        "hu_HU": "Jelölő színe",
        "ja": "マーカーの色",
        "nl_NL": "Markeerkleur",
        "pl_PL": "Kolor znacznika",
        "pt_BR": "Cor do marcador",
        "ru_RU": "Цвет маркера",
    },
    "Marker clustering": {
        "cs_CZ": "Shlukování značek",
        "de_DE": "Marker-Clustering",
        "en_US": "Marker clustering",
        "es_ES": "Agrupación de marcadores",
        "fr_FR": "Regroupement des marqueurs",
        "hu_HU": "Jelölők csoportosítása",
        "ja": "マーカーのクラスタリング",
        "nl_NL": "Markeerclustering",
        "pl_PL": "Grupowanie znaczników",
        "pt_BR": "Agrupamento de marcadores",
        "ru_RU": "Кластеризация маркеров",
    },
    "Popup on marker": {
        "cs_CZ": "Vyskakovací okno na značce",
        "de_DE": "Popup auf Marker",
        "en_US": "Popup on marker",
        "es_ES": "Ventana emergente en el marcador",
        "fr_FR": "Pop-up sur marqueur",
        "hu_HU": "Felugró ablak a jelölőn",
        "ja": "マーカーのポップアップ",
        "nl_NL": "Pop-up op markeerpunt",
        "pl_PL": "Wyskakujące okno na znaczniku",
        "pt_BR": "Pop-up no marcador",
        "ru_RU": "Всплывающее окно на маркере",
    },
    "Fullscreen button": {
        "cs_CZ": "Tlačítko celé obrazovky",
        "de_DE": "Vollbild-Schaltfläche",
        "en_US": "Fullscreen button",
        "es_ES": "Botón de pantalla completa",
        "fr_FR": "Bouton plein écran",
        "hu_HU": "Teljes képernyő gomb",
        "ja": "全画面表示ボタン",
        "nl_NL": "Volledig scherm-knop",
        "pl_PL": "Przycisk pełnego ekranu",
        "pt_BR": "Botão de tela cheia",
        "ru_RU": "Кнопка полного экрана",
    },
    "Filters": {
        "cs_CZ": "Filtry",
        "de_DE": "Filter",
        "en_US": "Filters",
        "es_ES": "Filtros",
        "fr_FR": "Filtres",
        "hu_HU": "Szűrők",
        "ja": "フィルター",
        "nl_NL": "Filters",
        "pl_PL": "Filtry",
        "pt_BR": "Filtros",
        "ru_RU": "Фильтры",
    },
    "Location search": {
        "cs_CZ": "Vyhledávání lokace",
        "de_DE": "Standortsuche",
        "en_US": "Location search",
        "es_ES": "Búsqueda por ubicación",
        "fr_FR": "Recherche par lieu",
        "hu_HU": "Helyszín keresése",
        "ja": "場所検索",
        "nl_NL": "Locatie zoeken",
        "pl_PL": "Wyszukiwanie lokalizacji",
        "pt_BR": "Busca por localização",
        "ru_RU": "Поиск по местоположению",
    },
    "Search radius": {
        "cs_CZ": "Vyhledávací poloměr",
        "de_DE": "Suchradius",
        "en_US": "Search radius",
        "es_ES": "Radio de búsqueda",
        "fr_FR": "Rayon de recherche",
        "hu_HU": "Keresési sugár",
        "ja": "検索範囲",
        "nl_NL": "Zoekstraal",
        "pl_PL": "Promień wyszukiwania",
        "pt_BR": "Raio de busca",
        "ru_RU": "Радиус поиска",
    },
    "Listing type": {
        "cs_CZ": "Typ nabídky",
        "de_DE": "Angebotstyp",
        "en_US": "Listing type",
        "es_ES": "Tipo de anuncio",
        "fr_FR": "Type d'annonce",
        "hu_HU": "Hirdetés típusa",
        "ja": "リストタイプ",
        "nl_NL": "Type aanbieding",
        "pl_PL": "Typ ogłoszenia",
        "pt_BR": "Tipo de anúncio",
        "ru_RU": "Тип объявления",
    },
    "Property type": {
        "cs_CZ": "Typ nemovitosti",
        "de_DE": "Immobilientyp",
        "en_US": "Property type",
        "es_ES": "Tipo de propiedad",
        "fr_FR": "Type de bien",
        "hu_HU": "Ingatlantípus",
        "ja": "物件タイプ",
        "nl_NL": "Type eigendom",
        "pl_PL": "Typ nieruchomości",
        "pt_BR": "Tipo de imóvel",
        "ru_RU": "Тип недвижимости",
    },
    "Bedrooms": {
        "cs_CZ": "Ložnice",
        "de_DE": "Schlafzimmer",
        "en_US": "Bedrooms",
        "es_ES": "Dormitorios",
        "fr_FR": "Chambres",
        "hu_HU": "Hálószobák",
        "ja": "ベッドルーム",
        "nl_NL": "Slaapkamers",
        "pl_PL": "Sypialnie",
        "pt_BR": "Quartos",
        "ru_RU": "Спальни",
    },
    "Bathrooms": {
        "cs_CZ": "Koupelny",
        "de_DE": "Badezimmer",
        "en_US": "Bathrooms",
        "es_ES": "Baños",
        "fr_FR": "Salles de bain",
        "hu_HU": "Fürdőszobák",
        "ja": "バスルーム",
        "nl_NL": "Badkamers",
        "pl_PL": "Łazienki",
        "pt_BR": "Banheiros",
        "ru_RU": "Ванные комнаты",
    },
    "Area": {
        "cs_CZ": "Plocha",
        "de_DE": "Fläche",
        "en_US": "Area",
        "es_ES": "Superficie",
        "fr_FR": "Surface",
        "hu_HU": "Terület",
        "ja": "面積",
        "nl_NL": "Oppervlakte",
        "pl_PL": "Powierzchnia",
        "pt_BR": "Área",
        "ru_RU": "Площадь",
    },
    "Price range": {
        "cs_CZ": "Cenové rozpětí",
        "de_DE": "Preisspanne",
        "en_US": "Price range",
        "es_ES": "Rango de precio",
        "fr_FR": "Fourchette de prix",
        "hu_HU": "Árkategória",
        "ja": "価格帯",
        "nl_NL": "Prijsklasse",
        "pl_PL": "Zakres cen",
        "pt_BR": "Faixa de preço",
        "ru_RU": "Диапазон цен",
    },
    "Search by ID": {
        "cs_CZ": "Hledat podle ID",
        "de_DE": "Suche nach ID",
        "en_US": "Search by ID",
        "es_ES": "Buscar por ID",
        "fr_FR": "Rechercher par ID",
        "hu_HU": "Keresés ID alapján",
        "ja": "IDで検索",
        "nl_NL": "Zoeken op ID",
        "pl_PL": "Szukaj według ID",
        "pt_BR": "Buscar por ID",
        "ru_RU": "Поиск по ID",
    },
    "Default radius (km)": {
        "cs_CZ": "Výchozí poloměr (km)",
        "de_DE": "Standardradius (km)",
        "en_US": "Default radius (km)",
        "es_ES": "Radio predeterminado (km)",
        "fr_FR": "Rayon par défaut (km)",
        "hu_HU": "Alapértelmezett sugár (km)",
        "ja": "デフォルトの範囲 (km)",
        "nl_NL": "Standaardradius (km)",
        "pl_PL": "Domyślny promień (km)",
        "pt_BR": "Raio padrão (km)",
        "ru_RU": "Радиус по умолчанию (км)",
    },
    "Results Card": {
        "cs_CZ": "Karta výsledků",
        "de_DE": "Ergebniskarte",
        "en_US": "Results Card",
        "es_ES": "Tarjeta de resultados",
        "fr_FR": "Carte des résultats",
        "hu_HU": "Eredménykártya",
        "ja": "結果カード",
        "nl_NL": "Resultatenkaart",
        "pl_PL": "Karta wyników",
        "pt_BR": "Cartão de resultados",
        "ru_RU": "Карточка результатов",
    },
    "Border radius": {
        "cs_CZ": "Zaoblení rohů",
        "de_DE": "Eckenradius",
        "en_US": "Border radius",
        "es_ES": "Radio del borde",
        "fr_FR": "Rayon de bordure",
        "hu_HU": "Szegély lekerekítése",
        "ja": "角丸の半径",
        "nl_NL": "Randradius",
        "pl_PL": "Zaokrąglenie krawędzi",
        "pt_BR": "Raio da borda",
        "ru_RU": "Радиус скругления",
    },
    "List photo height (px)": {
        "cs_CZ": "Výška fotografie v seznamu (px)",
        "de_DE": "Foto-Höhe in Liste (px)",
        "en_US": "List photo height (px)",
        "es_ES": "Altura de foto en lista (px)",
        "fr_FR": "Hauteur photo en liste (px)",
        "hu_HU": "Lista fotó magassága (px)",
        "ja": "リスト写真の高さ (px)",
        "nl_NL": "Hoogte foto in lijst (px)",
        "pl_PL": "Wysokość zdjęcia na liście (px)",
        "pt_BR": "Altura da foto na lista (px)",
        "ru_RU": "Высота фото в списке (px)",
    },
    "0 = adaptive to content": {
        "cs_CZ": "0 = přizpůsobí se obsahu",
        "de_DE": "0 = an Inhalt anpassen",
        "en_US": "0 = adaptive to content",
        "es_ES": "0 = adaptable al contenido",
        "fr_FR": "0 = adapté au contenu",
        "hu_HU": "0 = tartalomhoz igazodik",
        "ja": "0 = コンテンツに合わせる",
        "nl_NL": "0 = aanpassen aan inhoud",
        "pl_PL": "0 = dopasowuje się do treści",
        "pt_BR": "0 = adaptável ao conteúdo",
        "ru_RU": "0 = по содержимому",
    },
    "Max card height (px)": {
        "cs_CZ": "Maximální výška karty (px)",
        "de_DE": "Max. Kartenhöhe (px)",
        "en_US": "Max card height (px)",
        "es_ES": "Altura máx. de la tarjeta (px)",
        "fr_FR": "Hauteur max. de la carte (px)",
        "hu_HU": "Kártya max. magassága (px)",
        "ja": "カードの最大高さ (px)",
        "nl_NL": "Max. kaarthoogte (px)",
        "pl_PL": "Maks. wysokość karty (px)",
        "pt_BR": "Altura máx. do cartão (px)",
        "ru_RU": "Макс. высота карточки (px)",
    },
    "0 = no limit": {
        "cs_CZ": "0 = bez limitu",
        "de_DE": "0 = kein Limit",
        "en_US": "0 = no limit",
        "es_ES": "0 = sin límite",
        "fr_FR": "0 = sans limite",
        "hu_HU": "0 = nincs határ",
        "ja": "0 = 制限なし",
        "nl_NL": "0 = geen limiet",
        "pl_PL": "0 = bez limitu",
        "pt_BR": "0 = sem limite",
        "ru_RU": "0 = без ограничений",
    },
    "Show image": {
        "cs_CZ": "Zobrazit obrázek",
        "de_DE": "Bild anzeigen",
        "en_US": "Show image",
        "es_ES": "Mostrar imagen",
        "fr_FR": "Afficher l'image",
        "hu_HU": "Kép megjelenítése",
        "ja": "画像を表示",
        "nl_NL": "Afbeelding tonen",
        "pl_PL": "Pokaż obraz",
        "pt_BR": "Mostrar imagem",
        "ru_RU": "Показать изображение",
    },
    "Show specs": {
        "cs_CZ": "Zobrazit specifikace",
        "de_DE": "Spezifikationen anzeigen",
        "en_US": "Show specs",
        "es_ES": "Mostrar especificaciones",
        "fr_FR": "Afficher les caractéristiques",
        "hu_HU": "Jellemzők megjelenítése",
        "ja": "仕様を表示",
        "nl_NL": "Specificaties tonen",
        "pl_PL": "Pokaż parametry",
        "pt_BR": "Mostrar especificações",
        "ru_RU": "Показать характеристики",
    },
    "Show price": {
        "cs_CZ": "Zobrazit cenu",
        "de_DE": "Preis anzeigen",
        "en_US": "Show price",
        "es_ES": "Mostrar precio",
        "fr_FR": "Afficher le prix",
        "hu_HU": "Ár megjelenítése",
        "ja": "価格を表示",
        "nl_NL": "Prijs tonen",
        "pl_PL": "Pokaż cenę",
        "pt_BR": "Mostrar preço",
        "ru_RU": "Показать цену",
    },
    "Map Popup": {
        "cs_CZ": "Vyskakovací okno mapy",
        "de_DE": "Karten-Popup",
        "en_US": "Map Popup",
        "es_ES": "Ventana emergente del mapa",
        "fr_FR": "Pop-up de la carte",
        "hu_HU": "Térkép felugró ablak",
        "ja": "地図ポップアップ",
        "nl_NL": "Kaart-pop-up",
        "pl_PL": "Wyskakujące okno mapy",
        "pt_BR": "Pop-up do mapa",
        "ru_RU": "Всплывающее окно карты",
    },
    "Width (px)": {
        "cs_CZ": "Šířka (px)",
        "de_DE": "Breite (px)",
        "en_US": "Width (px)",
        "es_ES": "Ancho (px)",
        "fr_FR": "Largeur (px)",
        "hu_HU": "Szélesség (px)",
        "ja": "幅 (px)",
        "nl_NL": "Breedte (px)",
        "pl_PL": "Szerokość (px)",
        "pt_BR": "Largura (px)",
        "ru_RU": "Ширина (px)",
    },
    "Padding (px)": {
        "cs_CZ": "Vnitřní odsazení (px)",
        "de_DE": "Innenabstand (px)",
        "en_US": "Padding (px)",
        "es_ES": "Relleno (px)",
        "fr_FR": "Marge intérieure (px)",
        "hu_HU": "Belső margó (px)",
        "ja": "余白 (px)",
        "nl_NL": "Opvulling (px)",
        "pl_PL": "Wewnętrzny margines (px)",
        "pt_BR": "Espaçamento interno (px)",
        "ru_RU": "Внутренний отступ (px)",
    },
    "Border radius (px)": {
        "cs_CZ": "Zaoblení rohů (px)",
        "de_DE": "Eckenradius (px)",
        "en_US": "Border radius (px)",
        "es_ES": "Radio del borde (px)",
        "fr_FR": "Rayon de bordure (px)",
        "hu_HU": "Szegély lekerekítése (px)",
        "ja": "角丸の半径 (px)",
        "nl_NL": "Randradius (px)",
        "pl_PL": "Zaokrąglenie krawędzi (px)",
        "pt_BR": "Raio da borda (px)",
        "ru_RU": "Радиус скругления (px)",
    },
    "Background": {
        "cs_CZ": "Pozadí",
        "de_DE": "Hintergrund",
        "en_US": "Background",
        "es_ES": "Fondo",
        "fr_FR": "Arrière-plan",
        "hu_HU": "Háttér",
        "ja": "背景",
        "nl_NL": "Achtergrond",
        "pl_PL": "Tło",
        "pt_BR": "Fundo",
        "ru_RU": "Фон",
    },
    "Border color": {
        "cs_CZ": "Barva ohraničení",
        "de_DE": "Rahmenfarbe",
        "en_US": "Border color",
        "es_ES": "Color del borde",
        "fr_FR": "Couleur de la bordure",
        "hu_HU": "Szegély színe",
        "ja": "枠線の色",
        "nl_NL": "Randkleur",
        "pl_PL": "Kolor obramowania",
        "pt_BR": "Cor da borda",
        "ru_RU": "Цвет рамки",
    },
    "Empty = no border": {
        "cs_CZ": "Prázdné = bez ohraničení",
        "de_DE": "Leer = kein Rahmen",
        "en_US": "Empty = no border",
        "es_ES": "Vacío = sin borde",
        "fr_FR": "Vide = pas de bordure",
        "hu_HU": "Üres = nincs szegély",
        "ja": "空 = 枠線なし",
        "nl_NL": "Leeg = geen rand",
        "pl_PL": "Puste = bez obramowania",
        "pt_BR": "Vazio = sem borda",
        "ru_RU": "Пусто = без рамки",
    },
    "Border width (px)": {
        "cs_CZ": "Šířka ohraničení (px)",
        "de_DE": "Rahmenbreite (px)",
        "en_US": "Border width (px)",
        "es_ES": "Ancho del borde (px)",
        "fr_FR": "Épaisseur de la bordure (px)",
        "hu_HU": "Szegély szélessége (px)",
        "ja": "枠線の太さ (px)",
        "nl_NL": "Randbreedte (px)",
        "pl_PL": "Szerokość obramowania (px)",
        "pt_BR": "Largura da borda (px)",
        "ru_RU": "Толщина рамки (px)",
    },
    "Shadow": {
        "cs_CZ": "Stín",
        "de_DE": "Schatten",
        "en_US": "Shadow",
        "es_ES": "Sombra",
        "fr_FR": "Ombre",
        "hu_HU": "Árnyék",
        "ja": "影",
        "nl_NL": "Schaduw",
        "pl_PL": "Cień",
        "pt_BR": "Sombra",
        "ru_RU": "Тень",
    },
    "None": {
        "cs_CZ": "Žádný",
        "de_DE": "Keine",
        "en_US": "None",
        "es_ES": "Ninguna",
        "fr_FR": "Aucune",
        "hu_HU": "Nincs",
        "ja": "なし",
        "nl_NL": "Geen",
        "pl_PL": "Brak",
        "pt_BR": "Nenhuma",
        "ru_RU": "Нет",
    },
    "Light": {
        "cs_CZ": "Lehký",
        "de_DE": "Leicht",
        "en_US": "Light",
        "es_ES": "Ligera",
        "fr_FR": "Légère",
        "hu_HU": "Könnyű",
        "ja": "薄い",
        "nl_NL": "Licht",
        "pl_PL": "Lekki",
        "pt_BR": "Leve",
        "ru_RU": "Лёгкая",
    },
    "Medium": {
        "cs_CZ": "Střední",
        "de_DE": "Mittel",
        "en_US": "Medium",
        "es_ES": "Media",
        "fr_FR": "Moyenne",
        "hu_HU": "Közepes",
        "ja": "中",
        "nl_NL": "Gemiddeld",
        "pl_PL": "Średni",
        "pt_BR": "Média",
        "ru_RU": "Средняя",
    },
    "Strong": {
        "cs_CZ": "Silný",
        "de_DE": "Stark",
        "en_US": "Strong",
        "es_ES": "Fuerte",
        "fr_FR": "Forte",
        "hu_HU": "Erős",
        "ja": "強い",
        "nl_NL": "Sterk",
        "pl_PL": "Silny",
        "pt_BR": "Forte",
        "ru_RU": "Сильная",
    },
    "Image height (px)": {
        "cs_CZ": "Výška obrázku (px)",
        "de_DE": "Bildhöhe (px)",
        "en_US": "Image height (px)",
        "es_ES": "Altura de la imagen (px)",
        "fr_FR": "Hauteur de l'image (px)",
        "hu_HU": "Kép magassága (px)",
        "ja": "画像の高さ (px)",
        "nl_NL": "Afbeeldingshoogte (px)",
        "pl_PL": "Wysokość obrazu (px)",
        "pt_BR": "Altura da imagem (px)",
        "ru_RU": "Высота изображения (px)",
    },
    "Image border radius (px)": {
        "cs_CZ": "Zaoblení rohů obrázku (px)",
        "de_DE": "Bild-Eckenradius (px)",
        "en_US": "Image border radius (px)",
        "es_ES": "Radio del borde de la imagen (px)",
        "fr_FR": "Rayon de bordure de l'image (px)",
        "hu_HU": "Kép szegély lekerekítése (px)",
        "ja": "画像の角丸の半径 (px)",
        "nl_NL": "Randradius afbeelding (px)",
        "pl_PL": "Zaokrąglenie krawędzi obrazu (px)",
        "pt_BR": "Raio da borda da imagem (px)",
        "ru_RU": "Радиус скругления изображения (px)",
    },
    "Title size (px)": {
        "cs_CZ": "Velikost nadpisu (px)",
        "de_DE": "Titelgröße (px)",
        "en_US": "Title size (px)",
        "es_ES": "Tamaño del título (px)",
        "fr_FR": "Taille du titre (px)",
        "hu_HU": "Cím mérete (px)",
        "ja": "タイトルサイズ (px)",
        "nl_NL": "Titelgrootte (px)",
        "pl_PL": "Rozmiar tytułu (px)",
        "pt_BR": "Tamanho do título (px)",
        "ru_RU": "Размер заголовка (px)",
    },
    "Title color": {
        "cs_CZ": "Barva nadpisu",
        "de_DE": "Titelfarbe",
        "en_US": "Title color",
        "es_ES": "Color del título",
        "fr_FR": "Couleur du titre",
        "hu_HU": "Cím színe",
        "ja": "タイトルの色",
        "nl_NL": "Titelkleur",
        "pl_PL": "Kolor tytułu",
        "pt_BR": "Cor do título",
        "ru_RU": "Цвет заголовка",
    },
    "Price color": {
        "cs_CZ": "Barva ceny",
        "de_DE": "Preisfarbe",
        "en_US": "Price color",
        "es_ES": "Color del precio",
        "fr_FR": "Couleur du prix",
        "hu_HU": "Ár színe",
        "ja": "価格の色",
        "nl_NL": "Prijskleur",
        "pl_PL": "Kolor ceny",
        "pt_BR": "Cor do preço",
        "ru_RU": "Цвет цены",
    },
    "Empty = marker color": {
        "cs_CZ": "Prázdné = barva značky",
        "de_DE": "Leer = Markerfarbe",
        "en_US": "Empty = marker color",
        "es_ES": "Vacío = color del marcador",
        "fr_FR": "Vide = couleur du marqueur",
        "hu_HU": "Üres = jelölő színe",
        "ja": "空 = マーカーの色",
        "nl_NL": "Leeg = markeerkleur",
        "pl_PL": "Puste = kolor znacznika",
        "pt_BR": "Vazio = cor do marcador",
        "ru_RU": "Пусто = цвет маркера",
    },
    "Search Button": {
        "cs_CZ": "Tlačítko vyhledávání",
        "de_DE": "Suchschaltfläche",
        "en_US": "Search Button",
        "es_ES": "Botón de búsqueda",
        "fr_FR": "Bouton de recherche",
        "hu_HU": "Keresés gomb",
        "ja": "検索ボタン",
        "nl_NL": "Zoekknop",
        "pl_PL": "Przycisk wyszukiwania",
        "pt_BR": "Botão de busca",
        "ru_RU": "Кнопка поиска",
    },
    "Button text": {
        "cs_CZ": "Text tlačítka",
        "de_DE": "Schaltflächentext",
        "en_US": "Button text",
        "es_ES": "Texto del botón",
        "fr_FR": "Texte du bouton",
        "hu_HU": "Gomb szövege",
        "ja": "ボタンのテキスト",
        "nl_NL": "Knoptekst",
        "pl_PL": "Tekst przycisku",
        "pt_BR": "Texto do botão",
        "ru_RU": "Текст кнопки",
    },
    "Search": {
        "cs_CZ": "Hledat",
        "de_DE": "Suchen",
        "en_US": "Search",
        "es_ES": "Buscar",
        "fr_FR": "Rechercher",
        "hu_HU": "Keresés",
        "ja": "検索",
        "nl_NL": "Zoeken",
        "pl_PL": "Szukaj",
        "pt_BR": "Buscar",
        "ru_RU": "Поиск",
    },
    "Button background": {
        "cs_CZ": "Pozadí tlačítka",
        "de_DE": "Schaltflächen-Hintergrund",
        "en_US": "Button background",
        "es_ES": "Fondo del botón",
        "fr_FR": "Arrière-plan du bouton",
        "hu_HU": "Gomb háttere",
        "ja": "ボタンの背景",
        "nl_NL": "Knopachtergrond",
        "pl_PL": "Tło przycisku",
        "pt_BR": "Fundo do botão",
        "ru_RU": "Фон кнопки",
    },
    "Text color": {
        "cs_CZ": "Barva textu",
        "de_DE": "Textfarbe",
        "en_US": "Text color",
        "es_ES": "Color del texto",
        "fr_FR": "Couleur du texte",
        "hu_HU": "Szövegszín",
        "ja": "文字色",
        "nl_NL": "Tekstkleur",
        "pl_PL": "Kolor tekstu",
        "pt_BR": "Cor do texto",
        "ru_RU": "Цвет текста",
    },
    "Property search map": {
        "cs_CZ": "Mapa pro hledání nemovitostí",
        "de_DE": "Immobiliensuche-Karte",
        "en_US": "Property search map",
        "es_ES": "Mapa de búsqueda de propiedades",
        "fr_FR": "Carte de recherche de biens",
        "hu_HU": "Ingatlankereső térkép",
        "ja": "物件検索マップ",
        "nl_NL": "Kaart vastgoedzoekopdracht",
        "pl_PL": "Mapa wyszukiwania nieruchomości",
        "pt_BR": "Mapa de busca de imóveis",
        "ru_RU": "Карта поиска недвижимости",
    },
    "Fullscreen": {
        "cs_CZ": "Celá obrazovka",
        "de_DE": "Vollbild",
        "en_US": "Fullscreen",
        "es_ES": "Pantalla completa",
        "fr_FR": "Plein écran",
        "hu_HU": "Teljes képernyő",
        "ja": "全画面表示",
        "nl_NL": "Volledig scherm",
        "pl_PL": "Pełny ekran",
        "pt_BR": "Tela cheia",
        "ru_RU": "Полный экран",
    },
    "Toggle fullscreen": {
        "cs_CZ": "Přepnout celou obrazovku",
        "de_DE": "Vollbild umschalten",
        "en_US": "Toggle fullscreen",
        "es_ES": "Alternar pantalla completa",
        "fr_FR": "Basculer en plein écran",
        "hu_HU": "Teljes képernyő váltása",
        "ja": "全画面表示の切り替え",
        "nl_NL": "Volledig scherm wisselen",
        "pl_PL": "Przełącz pełny ekran",
        "pt_BR": "Alternar tela cheia",
        "ru_RU": "Переключить полный экран",
    },
    "Search city, area, address...": {
        "cs_CZ": "Hledat město, oblast, adresu...",
        "de_DE": "Stadt, Gegend, Adresse suchen...",
        "en_US": "Search city, area, address...",
        "es_ES": "Buscar ciudad, zona, dirección...",
        "fr_FR": "Rechercher ville, zone, adresse...",
        "hu_HU": "Város, terület, cím keresése...",
        "ja": "市区町村、エリア、住所を検索...",
        "nl_NL": "Zoek stad, gebied, adres...",
        "pl_PL": "Szukaj miasta, obszaru, adresu...",
        "pt_BR": "Buscar cidade, área, endereço...",
        "ru_RU": "Поиск города, района, адреса...",
    },
    "%d km": {
        "cs_CZ": "%d km",
        "de_DE": "%d km",
        "en_US": "%d km",
        "es_ES": "%d km",
        "fr_FR": "%d km",
        "hu_HU": "%d km",
        "ja": "%d km",
        "nl_NL": "%d km",
        "pl_PL": "%d km",
        "pt_BR": "%d km",
        "ru_RU": "%d км",
    },
    "Min": {
        "cs_CZ": "Min",
        "de_DE": "Min.",
        "en_US": "Min",
        "es_ES": "Mín",
        "fr_FR": "Min",
        "hu_HU": "Min.",
        "ja": "最小",
        "nl_NL": "Min",
        "pl_PL": "Min",
        "pt_BR": "Mín",
        "ru_RU": "Мин",
    },
    "Max": {
        "cs_CZ": "Max",
        "de_DE": "Max.",
        "en_US": "Max",
        "es_ES": "Máx",
        "fr_FR": "Max",
        "hu_HU": "Max.",
        "ja": "最大",
        "nl_NL": "Max",
        "pl_PL": "Maks",
        "pt_BR": "Máx",
        "ru_RU": "Макс",
    },
    "ID or Reference": {
        "cs_CZ": "ID nebo reference",
        "de_DE": "ID oder Referenz",
        "en_US": "ID or Reference",
        "es_ES": "ID o referencia",
        "fr_FR": "ID ou référence",
        "hu_HU": "ID vagy hivatkozás",
        "ja": "IDまたは参照番号",
        "nl_NL": "ID of referentie",
        "pl_PL": "ID lub numer",
        "pt_BR": "ID ou referência",
        "ru_RU": "ID или ссылка",
    },
    "Reset filters": {
        "cs_CZ": "Resetovat filtry",
        "de_DE": "Filter zurücksetzen",
        "en_US": "Reset filters",
        "es_ES": "Restablecer filtros",
        "fr_FR": "Réinitialiser les filtres",
        "hu_HU": "Szűrők visszaállítása",
        "ja": "フィルターをリセット",
        "nl_NL": "Filters resetten",
        "pl_PL": "Resetuj filtry",
        "pt_BR": "Redefinir filtros",
        "ru_RU": "Сбросить фильтры",
    },
    "%s Results Found": {
        "cs_CZ": "Nalezeno %s výsledků",
        "de_DE": "%s Ergebnisse gefunden",
        "en_US": "%s Results Found",
        "es_ES": "%s resultados encontrados",
        "fr_FR": "%s résultats trouvés",
        "hu_HU": "%s találat",
        "ja": "%s 件の結果",
        "nl_NL": "%s resultaten gevonden",
        "pl_PL": "Znaleziono %s wyników",
        "pt_BR": "%s resultados encontrados",
        "ru_RU": "Найдено %s результатов",
    },
    "List view": {
        "cs_CZ": "Zobrazení seznamu",
        "de_DE": "Listenansicht",
        "en_US": "List view",
        "es_ES": "Vista de lista",
        "fr_FR": "Vue liste",
        "hu_HU": "Lista nézet",
        "ja": "リスト表示",
        "nl_NL": "Lijstweergave",
        "pl_PL": "Widok listy",
        "pt_BR": "Visualização em lista",
        "ru_RU": "Вид списком",
    },
    "Grid view": {
        "cs_CZ": "Zobrazení mřížky",
        "de_DE": "Rasteransicht",
        "en_US": "Grid view",
        "es_ES": "Vista de cuadrícula",
        "fr_FR": "Vue grille",
        "hu_HU": "Rács nézet",
        "ja": "グリッド表示",
        "nl_NL": "Rasterweergave",
        "pl_PL": "Widok siatki",
        "pt_BR": "Visualização em grade",
        "ru_RU": "Вид сеткой",
    },
    "Searching...": {
        "cs_CZ": "Vyhledávání...",
        "de_DE": "Suche läuft...",
        "en_US": "Searching...",
        "es_ES": "Buscando...",
        "fr_FR": "Recherche en cours...",
        "hu_HU": "Keresés...",
        "ja": "検索中...",
        "nl_NL": "Zoeken...",
        "pl_PL": "Wyszukiwanie...",
        "pt_BR": "Buscando...",
        "ru_RU": "Поиск...",
    },
    "No results found": {
        "cs_CZ": "Nebyly nalezeny žádné výsledky",
        "de_DE": "Keine Ergebnisse gefunden",
        "en_US": "No results found",
        "es_ES": "No se han encontrado resultados",
        "fr_FR": "Aucun résultat trouvé",
        "hu_HU": "Nincs találat",
        "ja": "結果が見つかりません",
        "nl_NL": "Geen resultaten gevonden",
        "pl_PL": "Nie znaleziono wyników",
        "pt_BR": "Nenhum resultado encontrado",
        "ru_RU": "Результаты не найдены",
    },
    "Try modifying the search filters": {
        "cs_CZ": "Zkuste upravit vyhledávací filtry",
        "de_DE": "Versuchen Sie, die Suchfilter zu ändern",
        "en_US": "Try modifying the search filters",
        "es_ES": "Prueba a modificar los filtros de búsqueda",
        "fr_FR": "Essayez de modifier les filtres de recherche",
        "hu_HU": "Próbálja módosítani a keresési szűrőket",
        "ja": "検索フィルターを変更してみてください",
        "nl_NL": "Probeer de zoekfilters aan te passen",
        "pl_PL": "Spróbuj zmienić filtry wyszukiwania",
        "pt_BR": "Tente modificar os filtros de busca",
        "ru_RU": "Попробуйте изменить фильтры поиска",
    },
    "%s Result Found": {
        "cs_CZ": "Nalezen %s výsledek",
        "de_DE": "%s Ergebnis gefunden",
        "en_US": "%s Result Found",
        "es_ES": "%s resultado encontrado",
        "fr_FR": "%s résultat trouvé",
        "hu_HU": "%s találat",
        "ja": "%s 件の結果",
        "nl_NL": "%s resultaat gevonden",
        "pl_PL": "Znaleziono %s wynik",
        "pt_BR": "%s resultado encontrado",
        "ru_RU": "Найден %s результат",
    },
    "km": {
        "cs_CZ": "km",
        "de_DE": "km",
        "en_US": "km",
        "es_ES": "km",
        "fr_FR": "km",
        "hu_HU": "km",
        "ja": "km",
        "nl_NL": "km",
        "pl_PL": "km",
        "pt_BR": "km",
        "ru_RU": "км",
    },
    "rm": {
        "cs_CZ": "pok.",
        "de_DE": "Zi.",
        "en_US": "rm",
        "es_ES": "hab.",
        "fr_FR": "ch.",
        "hu_HU": "szoba",
        "ja": "室",
        "nl_NL": "kmr",
        "pl_PL": "pok.",
        "pt_BR": "qto",
        "ru_RU": "ком.",
    },
    "baths": {
        "cs_CZ": "koupelny",
        "de_DE": "Bäder",
        "en_US": "baths",
        "es_ES": "baños",
        "fr_FR": "sdb",
        "hu_HU": "fürdő",
        "ja": "浴室",
        "nl_NL": "badk.",
        "pl_PL": "łaz.",
        "pt_BR": "ban.",
        "ru_RU": "ванн.",
    },
    "m²": {
        "cs_CZ": "m²",
        "de_DE": "m²",
        "en_US": "m²",
        "es_ES": "m²",
        "fr_FR": "m²",
        "hu_HU": "m²",
        "ja": "m²",
        "nl_NL": "m²",
        "pl_PL": "m²",
        "pt_BR": "m²",
        "ru_RU": "м²",
    },
    "Location": {
        "cs_CZ": "Lokalita",
        "de_DE": "Standort",
        "en_US": "Location",
        "es_ES": "Ubicación",
        "fr_FR": "Lieu",
        "hu_HU": "Helyszín",
        "ja": "場所",
        "nl_NL": "Locatie",
        "pl_PL": "Lokalizacja",
        "pt_BR": "Localização",
        "ru_RU": "Местоположение",
    },
    "All": {
        "cs_CZ": "Vše",
        "de_DE": "Alle",
        "en_US": "All",
        "es_ES": "Todos",
        "fr_FR": "Tous",
        "hu_HU": "Mind",
        "ja": "すべて",
        "nl_NL": "Alle",
        "pl_PL": "Wszystkie",
        "pt_BR": "Todos",
        "ru_RU": "Все",
    },
    "All types": {
        "cs_CZ": "Všechny typy",
        "de_DE": "Alle Typen",
        "en_US": "All types",
        "es_ES": "Todos los tipos",
        "fr_FR": "Tous les types",
        "hu_HU": "Minden típus",
        "ja": "すべてのタイプ",
        "nl_NL": "Alle typen",
        "pl_PL": "Wszystkie typy",
        "pt_BR": "Todos os tipos",
        "ru_RU": "Все типы",
    },
    "Any": {
        "cs_CZ": "Jakékoli",
        "de_DE": "Beliebig",
        "en_US": "Any",
        "es_ES": "Cualquiera",
        "fr_FR": "Indifférent",
        "hu_HU": "Bármely",
        "ja": "指定なし",
        "nl_NL": "Willekeurig",
        "pl_PL": "Dowolne",
        "pt_BR": "Qualquer",
        "ru_RU": "Любое",
    },
    "Area (m²)": {
        "cs_CZ": "Plocha (m²)",
        "de_DE": "Fläche (m²)",
        "en_US": "Area (m²)",
        "es_ES": "Superficie (m²)",
        "fr_FR": "Surface (m²)",
        "hu_HU": "Terület (m²)",
        "ja": "面積 (m²)",
        "nl_NL": "Oppervlakte (m²)",
        "pl_PL": "Powierzchnia (m²)",
        "pt_BR": "Área (m²)",
        "ru_RU": "Площадь (м²)",
    },
    "Price (€)": {
        "cs_CZ": "Cena (€)",
        "de_DE": "Preis (€)",
        "en_US": "Price (€)",
        "es_ES": "Precio (€)",
        "fr_FR": "Prix (€)",
        "hu_HU": "Ár (€)",
        "ja": "価格 (€)",
        "nl_NL": "Prijs (€)",
        "pl_PL": "Cena (€)",
        "pt_BR": "Preço (€)",
        "ru_RU": "Цена (€)",
    },
    "Property Ref.": {
        "cs_CZ": "Reference nemovitosti",
        "de_DE": "Immobilien-Ref.",
        "en_US": "Property Ref.",
        "es_ES": "Ref. de propiedad",
        "fr_FR": "Réf. du bien",
        "hu_HU": "Ingatlan hivatk.",
        "ja": "物件番号",
        "nl_NL": "Eigendomsref.",
        "pl_PL": "Nr nieruchomości",
        "pt_BR": "Ref. do imóvel",
        "ru_RU": "Номер объекта",
    },
    "Default order": {
        "cs_CZ": "Výchozí řazení",
        "de_DE": "Standardsortierung",
        "en_US": "Default order",
        "es_ES": "Orden predeterminado",
        "fr_FR": "Tri par défaut",
        "hu_HU": "Alapértelmezett sorrend",
        "ja": "デフォルトの並び順",
        "nl_NL": "Standaardvolgorde",
        "pl_PL": "Domyślne sortowanie",
        "pt_BR": "Ordem padrão",
        "ru_RU": "Сортировка по умолчанию",
    },
    "Price ascending": {
        "cs_CZ": "Cena vzestupně",
        "de_DE": "Preis aufsteigend",
        "en_US": "Price ascending",
        "es_ES": "Precio ascendente",
        "fr_FR": "Prix croissant",
        "hu_HU": "Ár növekvő",
        "ja": "価格が安い順",
        "nl_NL": "Prijs oplopend",
        "pl_PL": "Cena rosnąco",
        "pt_BR": "Preço crescente",
        "ru_RU": "Цена по возрастанию",
    },
    "Price descending": {
        "cs_CZ": "Cena sestupně",
        "de_DE": "Preis absteigend",
        "en_US": "Price descending",
        "es_ES": "Precio descendente",
        "fr_FR": "Prix décroissant",
        "hu_HU": "Ár csökkenő",
        "ja": "価格が高い順",
        "nl_NL": "Prijs aflopend",
        "pl_PL": "Cena malejąco",
        "pt_BR": "Preço decrescente",
        "ru_RU": "Цена по убыванию",
    },
    "Newest": {
        "cs_CZ": "Nejnovější",
        "de_DE": "Neueste",
        "en_US": "Newest",
        "es_ES": "Más recientes",
        "fr_FR": "Plus récents",
        "hu_HU": "Legújabb",
        "ja": "新着順",
        "nl_NL": "Nieuwste",
        "pl_PL": "Najnowsze",
        "pt_BR": "Mais recentes",
        "ru_RU": "Самые новые",
    },
    "Distance": {
        "cs_CZ": "Vzdálenost",
        "de_DE": "Entfernung",
        "en_US": "Distance",
        "es_ES": "Distancia",
        "fr_FR": "Distance",
        "hu_HU": "Távolság",
        "ja": "距離",
        "nl_NL": "Afstand",
        "pl_PL": "Odległość",
        "pt_BR": "Distância",
        "ru_RU": "Расстояние",
    },
    "Previous": {
        "cs_CZ": "Předchozí",
        "de_DE": "Zurück",
        "en_US": "Previous",
        "es_ES": "Anterior",
        "fr_FR": "Précédent",
        "hu_HU": "Előző",
        "ja": "前へ",
        "nl_NL": "Vorige",
        "pl_PL": "Poprzedni",
        "pt_BR": "Anterior",
        "ru_RU": "Назад",
    },
    "Next": {
        "cs_CZ": "Další",
        "de_DE": "Weiter",
        "en_US": "Next",
        "es_ES": "Siguiente",
        "fr_FR": "Suivant",
        "hu_HU": "Következő",
        "ja": "次へ",
        "nl_NL": "Volgende",
        "pl_PL": "Następny",
        "pt_BR": "Próximo",
        "ru_RU": "Далее",
    },
    "Sale": {
        "cs_CZ": "Prodej",
        "de_DE": "Verkauf",
        "en_US": "Sale",
        "es_ES": "Venta",
        "fr_FR": "Vente",
        "hu_HU": "Eladó",
        "ja": "販売",
        "nl_NL": "Verkoop",
        "pl_PL": "Sprzedaż",
        "pt_BR": "Venda",
        "ru_RU": "Продажа",
    },
    "Rent": {
        "cs_CZ": "Pronájem",
        "de_DE": "Vermietung",
        "en_US": "Rent",
        "es_ES": "Alquiler",
        "fr_FR": "Location",
        "hu_HU": "Bérlés",
        "ja": "賃貸",
        "nl_NL": "Verhuur",
        "pl_PL": "Wynajem",
        "pt_BR": "Aluguel",
        "ru_RU": "Аренда",
    },
}


def parse_po(content):
    """Parse il contenuto di un .po e ritorna lista di tuple (msgid_raw, start_line_msgstr, end_line_msgstr).
    msgid_raw è la stringa esatta nel file (escape inclusi).
    Restituiamo posizioni come (msgid_string, msgstr_block_index_in_text).

    Usiamo un approccio basato sui caratteri: troviamo ogni 'msgid "..."' (possibilmente multi-linea),
    poi il corrispondente 'msgstr "..."' subito dopo.
    """
    pass  # not used directly


def extract_string_block(lines, start_idx):
    """Da una linea che inizia con 'msgid "' o 'msgstr "', estrae il contenuto della stringa
    (concatenando le continuation lines successive che sono solo '"..."').
    Ritorna (testo_concatenato_unescaped, indice_della_prima_linea_dopo_il_blocco).
    Le linee dopo la prima sono solo continuation: '"....."'.
    """
    # rimuove "msgid " o "msgstr " e i quotes
    line = lines[start_idx]
    if line.startswith('msgid "'):
        first_content = line[len('msgid "'):-1]  # rimuove anche \n? attento
    elif line.startswith('msgstr "'):
        first_content = line[len('msgstr "'):-1]
    else:
        raise ValueError(f"Linea inattesa: {line!r}")
    # se la linea termina con '\n', rimuovila
    if first_content.endswith('\n'):
        first_content = first_content[:-1]
    # se termina con '"' (delimitatore di chiusura)
    if first_content.endswith('"'):
        first_content = first_content[:-1]
    parts = [first_content]
    idx = start_idx + 1
    while idx < len(lines):
        ln = lines[idx]
        ln_stripped = ln.rstrip('\n')
        if ln_stripped.startswith('"') and ln_stripped.endswith('"'):
            parts.append(ln_stripped[1:-1])
            idx += 1
        else:
            break
    return ''.join(parts), idx


def write_string_block(text):
    """Genera la rappresentazione gettext: una singola linea o multilinea con \\n.
    text è la stringa "logica" (con escape già nel formato gettext).
    Per uniformità, se il testo contiene \\n (sequenze "\\n" letterali, due caratteri \\ + n),
    splittiamo per generare continuation lines come da convenzione gettext.

    In input text è già nella forma "escaped" per il file .po (es. con \\" per le virgolette).
    Per ora, semplice: usiamo single-line.
    """
    return f'"{text}"'


def main():
    if not os.path.isdir(LANG_DIR):
        print(f"ERRORE: directory non trovata: {LANG_DIR}", file=sys.stderr)
        sys.exit(1)

    stats = {}

    for lang in LANGS:
        po_path = os.path.join(LANG_DIR, f"oloele-property-map-{lang}.po")
        if not os.path.isfile(po_path):
            print(f"ATTENZIONE: file mancante {po_path}", file=sys.stderr)
            continue

        with open(po_path, "r", encoding="utf-8") as f:
            lines = f.readlines()

        # Header update: queste righe sono continuation del msgstr "" header.
        # Le aggiorniamo come pre-pass su content.
        new_lines = []
        i = 0
        translated_count = 0
        missing = []

        # Pre-update righe header
        updated_lines = []
        for ln in lines:
            if ln.startswith('"PO-Revision-Date:'):
                updated_lines.append('"PO-Revision-Date: 2026-05-21 12:00+0000\\n"\n')
            elif ln.startswith('"Last-Translator:'):
                updated_lines.append('"Last-Translator: Claude (AI translation)\\n"\n')
            else:
                updated_lines.append(ln)
        lines = updated_lines

        while i < len(lines):
            line = lines[i]

            # Trova msgid (saltando msgid_plural per ora)
            if line.startswith('msgid "') and not line.startswith('msgid_plural'):
                msgid_text, after_msgid = extract_string_block(lines, i)
                # Copia tutte le righe del msgid invariate
                for k in range(i, after_msgid):
                    new_lines.append(lines[k])

                # Ora attendiamo msgstr
                if after_msgid < len(lines) and lines[after_msgid].startswith('msgstr "'):
                    msgstr_text, after_msgstr = extract_string_block(lines, after_msgid)

                    # Se msgid è vuoto (header), copia msgstr esistente invariato
                    if msgid_text == "":
                        for k in range(after_msgid, after_msgstr):
                            new_lines.append(lines[k])
                    else:
                        # Cerca traduzione
                        translation = TRANSLATIONS.get(msgid_text, {}).get(lang)
                        if translation is None:
                            missing.append(msgid_text)
                            # Lascia msgstr vuoto
                            for k in range(after_msgid, after_msgstr):
                                new_lines.append(lines[k])
                        else:
                            new_lines.append(f'msgstr "{translation}"\n')
                            translated_count += 1

                    i = after_msgstr
                else:
                    # msgstr non trovato, copia e prosegui
                    i = after_msgid
            else:
                new_lines.append(line)
                i += 1

        # Scrivi file
        with open(po_path, "w", encoding="utf-8", newline="") as f:
            f.writelines(new_lines)

        stats[lang] = {
            "translated": translated_count,
            "missing": missing,
        }
        print(f"[{lang}] tradotte {translated_count} stringhe, mancanti: {len(missing)}")
        if missing:
            for m in missing[:5]:
                print(f"    MISS: {m!r}")
            if len(missing) > 5:
                print(f"    ... e altre {len(missing)-5}")

    print("\n=== RIEPILOGO ===")
    total_translated = sum(s["translated"] for s in stats.values())
    print(f"Totale traduzioni applicate: {total_translated}")
    print(f"Lingue processate: {len(stats)}")


if __name__ == "__main__":
    main()
