// OLObuild — element catalog (italian, matches screenshot)
window.OLO_CATEGORIES = [
  { id: "recenti",   label: "Recenti",     dot: "#a78bfa", icon: "clock",      count: 7 },
  { id: "preferiti", label: "Preferiti",   dot: "#f59e0b", icon: "star",       count: 8 },
  { id: "essenziale",label: "Essenziale",  dot: "#ef4444", icon: "square",     count: 9 },
  { id: "layout",    label: "Layout",      dot: "#3b82f6", icon: "layout",     count: 7 },
  { id: "testo",     label: "Testo",       dot: "#22c55e", icon: "text",       count: 10 },
  { id: "media",     label: "Media",       dot: "#a855f7", icon: "image",      count: 20 },
  { id: "marketing", label: "Marketing",   dot: "#ec4899", icon: "megaphone",  count: 19 },
  { id: "interattivo",label:"Interattivo", dot: "#06b6d4", icon: "spark",      count: 17 },
  { id: "form",      label: "Form",        dot: "#0ea5e9", icon: "form",       count: 8 },
  { id: "ecommerce", label: "E-commerce",  dot: "#10b981", icon: "cart",       count: 12 },
];

window.OLO_ELEMENTS = {
  recenti: [
    {id:"btn",     label:"Pulsante",          icon:"button"},
    {id:"map",     label:"Mappa Ricerca Strutture", icon:"map"},
    {id:"achero",  label:"Ac — Hero",         icon:"hero"},
    {id:"img",     label:"Immagine",          icon:"image", fav:true},
    {id:"sp",      label:"Spaziatore",        icon:"spacer", fav:true},
    {id:"flpan",   label:"Pannello flottante",icon:"floatpanel", fav:true},
    {id:"pan",     label:"Pannello",          icon:"panel"},
  ],
  preferiti: [
    {id:"cnt",     label:"Contenuto",         icon:"content", fav:true},
    {id:"img2",    label:"Immagine",          icon:"image", fav:true},
    {id:"video",   label:"Video",             icon:"video", fav:true},
    {id:"sp2",     label:"Spaziatore",        icon:"spacer", fav:true},
    {id:"pan2",    label:"Pannello",          icon:"panel", fav:true},
    {id:"pslide",  label:"Panel Slider",      icon:"slider", fav:true},
    {id:"oslide",  label:"Overlay Slider",    icon:"overlay", fav:true},
    {id:"flpan2",  label:"Pannello flottante",icon:"floatpanel", fav:true},
  ],
  essenziale: [
    {id:"e-cnt",   label:"Contenuto",         icon:"content", fav:true},
    {id:"e-img",   label:"Immagine",          icon:"image", fav:true},
    {id:"e-vid",   label:"Video",             icon:"video", fav:true},
    {id:"e-sp",    label:"Spaziatore",        icon:"spacer", fav:true},
    {id:"e-btn",   label:"Pulsante",          icon:"button"},
    {id:"e-h",     label:"Titolo",            icon:"heading"},
    {id:"e-txt",   label:"Testo",             icon:"text"},
    {id:"e-div",   label:"Divisore",          icon:"divider"},
    {id:"e-ic",    label:"Icona",             icon:"icon"},
  ],
  layout: [
    {id:"l-hero",  label:"Hero",              icon:"hero"},
    {id:"l-row",   label:"Riga / Colonne",    icon:"cols"},
    {id:"l-frag",  label:"Frammento",         icon:"fragment"},
    {id:"l-grid",  label:"Griglia",           icon:"grid"},
    {id:"l-cint",  label:"Colonne interne",   icon:"colsInner"},
    {id:"l-shape", label:"Shape Divider",     icon:"shape"},
    {id:"l-tpl",   label:"Includi template",  icon:"template"},
  ],
  testo: [
    {id:"t-warn",  label:"Avviso",            icon:"alert"},
    {id:"t-html",  label:"HTML / Codice",     icon:"code"},
    {id:"t-list",  label:"Lista",             icon:"list"},
    {id:"t-tab",   label:"Tabella",           icon:"table"},
    {id:"t-dl",    label:"Lista descrittiva", icon:"listDesc"},
    {id:"t-quote", label:"Citazione",         icon:"quote"},
    {id:"t-code",  label:"Codice",            icon:"codeTag"},
    {id:"t-icli",  label:"Lista icone",       icon:"listIcon"},
    {id:"t-anim",  label:"Titolo animato",    icon:"headingAnim"},
    {id:"t-path",  label:"Testo su Tracciato",icon:"textPath"},
  ],
  media: [
    {id:"m-img",   label:"Immagine",          icon:"image"},
    {id:"m-vid",   label:"Video",             icon:"video"},
    {id:"m-gal",   label:"Galleria",          icon:"gallery"},
    {id:"m-car",   label:"Carosello",         icon:"carousel"},
    {id:"m-light", label:"Lightbox",          icon:"lightbox"},
    {id:"m-audio", label:"Audio",             icon:"audio"},
    {id:"m-yt",    label:"YouTube",           icon:"youtube"},
    {id:"m-vim",   label:"Vimeo",             icon:"vimeo"},
    {id:"m-360",   label:"Immagine 360°",     icon:"sphere"},
    {id:"m-bgvid", label:"Video sfondo",      icon:"videoBg"},
  ],
  marketing: [
    {id:"mk-cta",  label:"CTA",               icon:"cta"},
    {id:"mk-pri",  label:"Pricing",           icon:"price"},
    {id:"mk-test", label:"Testimonianza",     icon:"testimonial"},
    {id:"mk-cnt",  label:"Countdown",         icon:"timer"},
    {id:"mk-team", label:"Team",              icon:"team"},
    {id:"mk-news", label:"Newsletter",        icon:"mail"},
    {id:"mk-stat", label:"Statistiche",       icon:"stats"},
  ],
  interattivo: [
    {id:"i-acc",   label:"Accordion",         icon:"accordion"},
    {id:"i-tab",   label:"Tabs",              icon:"tabs"},
    {id:"i-tip",   label:"Tooltip",           icon:"tooltip"},
    {id:"i-mod",   label:"Modale",            icon:"modal"},
    {id:"i-flip",  label:"Flip Card",         icon:"flip"},
    {id:"i-rev",   label:"Reveal",            icon:"reveal"},
  ],
  form: [
    {id:"f-form",  label:"Form",              icon:"form"},
    {id:"f-in",    label:"Input",             icon:"input"},
    {id:"f-sel",   label:"Select",            icon:"select"},
    {id:"f-chk",   label:"Checkbox",          icon:"check"},
    {id:"f-rad",   label:"Radio",             icon:"radio"},
    {id:"f-area",  label:"Textarea",          icon:"textarea"},
  ],
  ecommerce: [
    {id:"ec-prod", label:"Prodotto",          icon:"cart"},
    {id:"ec-grid", label:"Griglia prodotti",  icon:"grid"},
    {id:"ec-cart", label:"Carrello",          icon:"cart"},
    {id:"ec-buy",  label:"Pulsante acquisto", icon:"button"},
  ],
};

// Flatten for search
window.OLO_ELEMENTS_FLAT = Object.entries(window.OLO_ELEMENTS).flatMap(([cat, arr]) =>
  arr.map(e => ({...e, cat}))
);
